### DISCUSSION TITLE
[Bug] Failed docker-compose build on Raspberry Pi 4

### DISCUSSION THREAD

**Discussion by jtokash** [danny-avila/LibreChat#1170] [Troubleshooting]
I'm getting the following error trying to build on a Raspberry Pi 4:

```
npm notice 
npm notice New major version of npm available! 9.6.3 -> 10.2.3
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.2.3>
npm notice Run `npm install -g npm@10.2.3` to update!
npm notice 
npm ERR! code 1
npm ERR! path /app/node_modules/sharp
npm ERR! command failed
npm ERR! command sh -c (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)
npm ERR! sharp: Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.14.5/libvips-8.14.5-linuxmusl-armv6.tar.br
npm ERR! sharp: Please see https://sharp.pixelplumbing.com/install for required dependencies
npm ERR! sharp: Installation error: Prebuilt libvips 8.14.5 binaries are not yet available for linuxmusl-armv6
```

The only change I've made to docker-compose.yml is `image: mongo:4.4.18`

**Comment by danny-avila** [comment]
You may need to edit your dockerfile, see this github discussion for more info on this issue

https://github.com/nuxt/image/issues/204

it may be as simple as adding `--legacy-peer-deps` after `npm ci`
```dockerfile
# Project root path
# ./Dockerfile

# Base node image
FROM node:19-alpine AS node

COPY . /app
WORKDIR /app

# Install call deps - Install curl for health check
RUN apk --no-cache add curl && \
    # We want to inherit env from the container, not the file
    # This will preserve any existing env file if it's already in souce
    # otherwise it will create a new one
    touch .env && \
    # Build deps in seperate 
    npm ci --legacy-peer-deps

# React client build
ENV NODE_OPTIONS="--max-old-space-size=2048"
RUN npm run frontend

# Node API setup
EXPOSE 3080
ENV HOST=0.0.0.0
CMD ["npm", "run", "backend"]

# Optional: for client with nginx routing
# FROM nginx:stable-alpine AS nginx-client
# WORKDIR /usr/share/nginx/html
# COPY --from=node /app/client/dist /usr/share/nginx/html
# COPY client/nginx.conf /etc/nginx/conf.d/default.conf
# ENTRYPOINT ["nginx", "-g", "daemon off;"]

```

You can also look at the documentation for sharp which has other recommendations here: https://sharp.pixelplumbing.com/install#apple-m1

**Comment by jtokash** [comment]
Unfortunately --legacy-peer-deps didn't work.  Still digging into this.

**Reply by danny-avila** [reply]
the key will be needing to adjust the dockerfile located in the root of the project. For example, i used to have to reinstall sharp in my github workflow file like this (commented out because i no longer need to do this)
```yml
      - name: Install global dependencies
        run: npm ci

      # - name: Remove sharp dependency
      #   run: rm -rf node_modules/sharp

      # - name: Install sharp with linux dependencies
      #   run: cd api && SHARP_IGNORE_GLOBAL_LIBVIPS=1 npm install --arch=x64 --platform=linux --libc=glibc sharp
```

so you may need to add extra steps to the dockerfile.
