### DISCUSSION TITLE
Enhancement: Support https

### DISCUSSION THREAD

**Discussion by myxgenius** [danny-avila/LibreChat#1228] [Troubleshooting] [answered]
### What features would you like to see added?

Currently the service can't really be shared with friends over internet because http traffic is not secure. Supporting https would allow this.

### More details

Support https connection

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment, marked as answer]
I am securely connected to LibreChat in my deployment: 
![image](https://github.com/danny-avila/LibreChat/assets/110412045/9c1e831b-7e58-4d6c-9f30-4d41c369c15d)

You need NGINX/a domain/cloudflare setup

https://docs.librechat.ai/deployment/digitalocean.html#part-v-editing-the-nginx-file-for-custom-domains-and-advanced-configs

**Reply by acerspyro** [reply]
You can also use Traefik if you're on docker, here's my config in docker-compose.override.yml:

```yml
services:
  api:
#     volumes:
#       - ./librechat.yaml:/app/librechat.yaml
#     image: ghcr.io/danny-avila/librechat:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.librechat.rule=Host(`your.domain.name`)"
      - "traefik.http.routers.librechat.entrypoints=websecure"
      - "traefik.http.routers.librechat.tls.certresolver=leresolver"
      - "traefik.http.services.librechat.loadbalancer.server.port=3080"
    networks:
      - web
      - librechat_default
    volumes:
      - ./librechat.yaml:/app/librechat.yaml
 
# ...

networks:
  web:
    external: true
  librechat_default:
    external: true
```

Traefik will allow you to reverse-proxy LibreChat in a reproducible way over HTTPS using a LetsEncrypt certificate.
