### DISCUSSION TITLE
System-wide custom model settings (lightweight GPTs)

### DISCUSSION THREAD

**Discussion by davidmarble** [danny-avila/LibreChat#1291] [Feature Requests & Suggestions]
@danny-avila This project is awesome. I compared a handful of options before settling on deploying this on a VPS as a way to help family members explore GPTs under a single OpenAI API key and minimal setup for them.

## User Story

As an administrator, I'd like more options to customize the set of models offered to all users on my LibreChat instance.

## Proposed Features

1. Support defining a custom set of models per endpoint with options, some common to all models, some specific to particular models. For example:
	- Common options among all models:
		- name (default if blank/unspecified: model)
		- model (required)
		- desc
		- prompt_prefix (i.e. system prompt)
		- max_tokens
		- default: true (for one model that should be the initial default for all users; we can have a separate discussion about your work in #1275 and whether to also support persisting the last selected model for each user)
	- OpenAI specific:
		- temperature
		- top_p
		- freqency_penalty
		- presence_penalty
	- etc.
2. Support defining default options for all models of a particular endpoint
3. Support selecting a default model per endpoint for all users.
4. Display models with name and optional desc

## Mockup

Based on Example 2 below

![custom-system-wide-model-settings-mockup](https://github.com/danny-avila/LibreChat/assets/253443/d3e40621-1907-4be7-a092-178e90365e71)

## Example YAML configs

I haven't considered how this could best fit within the current dotenv extends/overwrites docker yaml config approach, or if it merits a re-think of how config is done (e.g. migrate env to yaml or put model config in a separate new yaml file or some other approach).

### Config docs draft

**Instructions:** Add models and add/edit options as needed. For each endpoint, e.g. OpenAI, `defaults` lists the default settings used by LibreChat. You can set defaults for all models of that endpoint type with the `defaults` key, or override values within individual model definitions. Set `default_model: true` on 1 model to make it the default for all users. If `default_model` is not set, the default will be ____ (not sure what the logic is). Consult endpoint provider API docs for documentation about options.

```yaml
endpoints:
  OpenAI:
    #defaults:
    #  temperature: 0.8
    #  top_p: 1
    #  freqency_penalty: 0
    #  presence_penalty: 0
    #  system_prompt:          # blank by default
    #  max_tokens:             # defaults defined in maxTokensMap in /api/utils/tokens.js, else 4095
    models:
      #- model:                # required, OpenAI API model name
      #  name:                 # optional display name
      #  prompt_prefix:        # optional system prompt
      #  temperature:          # optional
      #  top_p: <#>            # optional
      #  freqency_penalty: <#> # optional
      #  presence_penalty: <#> # optional
      #  default_model: true   # optional, can only be set on 1 model
      #- model:                # ... add models as needed ...
  ...
```

### Example 1 (minimal)

```yaml
endpoints:
  OpenAI:
    models:
      - model: gpt-4-1106-preview
      - model: gpt-3.5-turbo-1106
```

### Example 2 (custom options)

```yaml
endpoints:
  OpenAI:
    models:
      - model: gpt-4-1106-preview
        name: "GPT-4 Turbo Accurate"
        description: A logical AI who keeps answers dry and precise
        temperature: 0
        prompt_prefix: You are Accurate AI, a helpful, clear, concise, scientific minded assistant.
        default_model: true
      - model: gpt-4-1106-preview
        name: "GPT-4 Turbo Creative"
        description: A creative AI who loves to gab
        temperature: 1
        prompt_prefix: You are Creative AI, a helpful, friendly, and very creative assistant who loves to chat.
      - model: gpt-3.5-turbo-1106

```

### Example 3 (modified defaults)

```yaml
endpoints:
  OpenAI:
    defaults:
      temperature: 0.8
      top_p: 1
      freqency_penalty: 0
      presence_penalty: 0
    models:
      - model: gpt-4-1106-preview
      - model: gpt-3.5-turbo-1106
        default_model: true
```

### Example 4 (modified defaults + custom options)

Note the use of a multiline YAML string for instructions. Prob a good idea to include an example prompt_prefix like this in the config file or instructions.

```yaml
endpoints:
  OpenAI:
    defaults:
      temperature: 0.8
      top_p: 0.8
      freqency_penalty: 0
      presence_penalty: 0
    models:
      - name: GPT-4 Turbo
        model: gpt-4-1106-preview
        temperature: 0.5
        prompt_prefix: |
          You are LibreChat, a large language model based on the GPT-4 architecture by OpenAI.
          Knowledge cutoff: 2023-04
          Current date: 2023-12-05

          You are to provide clear, concise, and direct responses. Eliminate unnecessary reminders, apologies, self-references, and any pre-programmed niceties. Maintain a casual tone in your communication. Be transparent; if you're unsure about an answer or if a question is beyond your capabilities or knowledge cutoff, admit it.
      - model: gpt-3.5-turbo-1106
        default_model: true
```

---
## Additional Notes

Think of this as somewhere between a nice config enhancement only possible for a self-hosted ChatGPT-like experience (multiple instances of the same model with customized defaults available to all users of the LibreChat instance) and supporting lightweight [custom GPT](https://openai.com/blog/introducing-gpts) characteristics like a highly customized system prompt. I could even see this laying a foundation for later supporting more off-the-shelf GPTs-like enhancements.

While the config in this proposal is presented as YAML, I could see this kind of config being part of a future web console for admins, perhaps stored in mongo. That probably wouldn't replace the need for an initial easily-modifiable config file though.
