### DISCUSSION TITLE
Helm chart for deployment into K8S

### DISCUSSION THREAD

**Discussion by siriusfreak** [danny-avila/LibreChat#1490] [Feature Requests & Suggestions]
Hello.

I can (and I want) to implement a helm chart and documentation to simplify the deployment of this project into k8s.

According to the contribution guide, I should ask if it is required for the project.

**Comment by danny-avila** [comment]
Would any of the client/api code need to be modified? I don't have experience with this, but if it's non-breaking to users who will never use it, then I don't see why not. Thanks for bringing this up!

**Reply by siriusfreak** [reply]
No changes in the code. 

But need to establish actions to release the helm chart repository like here: https://github.com/helm/examples

**Reply by danny-avila** [reply]
this is fine with me, I would like to try Kubernetes myself through this if you implement it!

**Comment by iamNoah1** [comment]
Following up on the conversation in the issue. I had a look at https://github.com/Schluggi/helm-charts/tree/main/charts/librechat. The Chart looks good on the first sight. I am running some tests locally on my machine to see how the handling is. My suggestion would be to get the helm "code" over to this repository and have the chart build for release alongside the docker images. What you think? I would do it as well as respective documentation if you are ok with it @danny-avila

**Reply by danny-avila** [reply]
@iamNoah1 I'm not experienced with this but if I could have a thorough guide for noobies for setting it up, I would totally welcome it. I want to dabble with deployment setups like this

**Reply by iamNoah1** [reply]
nice, got it. I will prepare something :)

**Comment by hofq** [comment]
Currently, we at Blue Atlas are maintaining one!
https://github.com/bat-bs/helm-charts/tree/main/charts/librechat

**Reply by WynnD** [reply]
Thank you! I deployed this in my homelab cluster and it's working beautifully!

**Reply by hofq** [reply]
Great to hear!
Maybe we can make it official and move it to a repo here? @danny-avila

**Reply by danny-avila** [reply]
@hofq I'm going to honor @iamNoah1 who was first to contribute a helm chart and merge his helm chart PR, but please feel free to make pull requests to help us maintain and improve it.

I've mentioned the helm chart you shared in the new docs for this, because the more points of reference for this, the better!
https://github.com/LibreChat-AI/librechat.ai/pull/99

Please also feel free to improve the documentation as needed.

**Reply by danny-avila** [reply]
Relevant LibreChat PR: https://github.com/danny-avila/LibreChat/pull/3539

**Reply by danny-avila** [reply]
I think one thing missing is configuration of the `librechat.yaml` file but I'm going to go ahead and merge this as a starting point.

**Reply by hofq** [reply]
The Chart you merged looks pretty incomplete on first sight.
There are a few things missing we already handled in our implementation:
- `rag_api` support for Document Uploads in a subchart
- automatically maintained bitnami-pgvector image, to allow support for rag_api and not break bitnamis chart (see: [here](https://github.com/bat-bs/bitnami-pgvector))
- include values and docs for every component needed to operate librechat (we included them as subcharts, so the user can select if he wants them or not)

We continue to support our chart for now, and would love to get it in the main project (maybe with support from @iamNoah1)

**Reply by iamNoah1** [reply]
Thanks @danny-avila. It might be incomplete, but was a first shot from my side and works perfectly fine :). RAG is a minus I agree and I am happy to help improving with what you got in your implementation @hofq  :)

**Reply by danny-avila** [reply]
Awesome, the guide you wrote @iamNoah1 is live here: https://www.librechat.ai/docs/local/helm_chart

@hofq please free to submit a PR. I am still learning more about Helm and k8 on my own time, and what is in now should function as a reference and I agree we can improve it from here.

**Reply by hofq** [reply]
I will get started working on a PR Today. Thanks, @iamNoah1, for the offered help.

@danny-avila Helm can be quite annoying, but there isn't really a good alternative ;)

**Reply by R-Prady** [reply]
it would be great if we get instructions for deploying it using ArgoCD

**Reply by hofq** [reply]
Hi @R-Prady,

With ArgoCD you have to take care of 2 steps.

1. Create all the Secrets in the Cluster
This can be done via [sealed-secrets](https://github.com/bitnami-labs/sealed-secrets) or [other k8s secret solutions](https://argo-cd.readthedocs.io/en/stable/operator-manual/secret-management/) For us these secrets are librechat-credentials-env librechat-rag and librechat-vectordb.
2. Create the Librechat Application itself
Normally, this does not differ from the helm deployment process. You just have to tweak the syntax to match the one from argocd's helm wrapper and point to the secrets you have created.
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: librechat
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: librechat
    server: https://kubernetes.default.svc
  project: default
  sources:
    - chart: librechat
      helm:
        values: |
          image:
            tag: "v0.7.4"
          librechat-rag-api:
            enabled: true
            rag:
              configEnv:
                EMBEDDINGS_PROVIDER: azure
                EMBEDDINGS_MODEL: text-embedding-3-large
                AZURE_OPENAI_ENDPOINT: https://example.com
              existingSecret: "rag-openai-secret"
            postgresql:
              image:
                pullSecrets:
                - pgvector
              auth:
                existingSecret: "librechat-vectordb"
          librechat:
            configEnv:
              PLUGIN_MODELS: nousresearch/nous-capybara-7b:free,mistralai/mistral-7b-instruct:free,gryphe/mythomist-7b:free,undi95/toppy-m-7b:free,openroutopenssl rand -hex 32er/cinematika-7b:free,google/gemma-7b-it:free
              ENDPOINTS: openAI,assistants,azureOpenAI,bingAI,chatGPTBrowser,google,gptPlugins,anthropic,openRouter,OpenRouter,azureAssistants
              ALLOW_EMAIL_LOGIN: "false"
              ALLOW_SOCIAL_LOGIN: "true"
              ALLOW_SOCIAL_REGISTRATION: "true"
              DOMAIN_CLIENT: https://example.com
              DOMAIN_SERVER: https://example.com
              DALLE3_AZURE_API_VERSION: 2024-02-15-preview
              DALLE3_BASEURL: https://example.com
              OPENID_SCOPE: openid profile email
              APP_TITLE: RobadsAI
              HELP_AND_FAQ_URL: https://docs.example.com
              CUSTOM_FOOTER: "Librechat"
            configYamlContent: |
              version: "1.0.3"
              cache: true
              fileConfig:
                serverFileSizeLimit: 300
                endpoints:
                  default:
                    totalSizeLimit: 300
              rateLimits:
                fileUploads:
                  ipMax: 100
                  ipWindowInMinutes: 60  # Rate limit window for file uploads per IP
                  userMax: 50
                  userWindowInMinutes: 60  # Rate limit window for file uploads per user
              endpoints:
                azureAssistants:
                  privateAssistants: true
                azureOpenAI:
                  plugins: true
                  assistants: true
                  titleConvo: true
                  titleModel: "gpt-4o"
                  groups:
                  - group: "azure-openai" # arbitrary name
                    plugins: true
                    assistants: true
                    apiKey: "${AZURE_CFG_API_KEY}"
                    instanceName: "robads-ai-schweden"  # name of the resource group or instance
                    version: "2024-02-15-preview"
                    models:
                      gpt-4o:
                        deploymentName: gpt-4o
          mongodb:
            resources:
              requests:
                cpu: 300m
          ingress:
            enabled: true
            annotations:
              nginx.ingress.kubernetes.io/proxy-body-size: "0"
              nginx.ingress.kubernetes.io/modsecurity-snippet: |
                SecRuleRemoveById 949110
            hosts:
              - host: domain.example
                paths:
                  - path: /
                    pathType: ImplementationSpecific

      repoURL: https://charts.blue-atlas.de
      targetRevision: 1.*.*
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
```
Hope that helps. If there is anything missing let me know
