### DISCUSSION TITLE
Compatibility with llama-cpp-python and add documentation

### DISCUSSION THREAD

**Discussion by ghost** [danny-avila/LibreChat#1779] [Troubleshooting] [answered]
### What happened?

llama-cpp-python has a OpenAI compatible server

I am serving a model as:
```
GGML_SYCL_DEVICE=0 python3 -m llama_cpp.server --model mistral-7b-instruct-v0.2.Q8_0.gguf --chat_format mistral-instruct --host 0.0.0.0 --port 7836 --n_ctx 16192 --n_gpu_layers 35 

```

Output from llama-cpp-python:
```
INFO:     Started server process [12022]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:7836 (Press CTRL+C to quit)
INFO:     192.168.3.114:51186 - "GET /v1/models HTTP/1.1" 200 OK # Librechat is requesting
INFO:     192.168.3.114:51198 - "POST /v1 HTTP/1.1" 404 Not Found # Librechat is requesting
```

I have checked http://192.168.3.113:7836/docs works # the llama-cpp-python openapi spec endpoint with this ip on my system

This is my librechat output when I try to chat with my model

```
Something went wrong. Here's the specific error message we encountered: Failed to send message. HTTP 404 - {"detail":"Not Found"}
```

This is my librechat.yaml configuration

```
# Configuration version (required)
version: 1.0.1

# Cache settings: Set to true to enable caching
cache: true

# Definition of custom endpoints
endpoints:
  custom:

    - name: "llama"
      apiKey: "sk-1234"
      baseURL: "http://192.168.3.113:7836/v1" # I have tried with just "http://192.168.3.113:7836" also, librechat again hits invalid endpoint
      iconURL: "<some url>"
      models:
        default: ["mistral-7b-v0.1", "mistral-7b-instruct-v0.2"] # I was loading multiple models first, but I was trying to diagnose the error with 1 model only
        fetch: true
      titleConvo: true
      titleModel: "mistral-7b-v0.1"
      titleMethod: "completion"
      summarize: true
      summaryModel: "mistral-7b-v0.1"
      forcePrompt: true
      modelDisplayLabel : "llama"
```

Possibilities:
1. llama-cpp-python is not serving a OpenAI compatible server
2. I am missing some configuration in Librechat, since chat format is `--chat_format mistral-instruct`
3. I am missing some configuration for llama-cpp-python with chat format is `--chat_format mistral-instruct`

### Steps to Reproduce

Stated above

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ghost** [comment]
https://github.com/abetlen/llama-cpp-python/issues/1174

**Comment by danny-avila** [comment]
To be honest, I've never setup llama-cpp-python for use in LibreChat, which is why there are compatibility/documentation issues.

My next big priority will be open source LLMs, and I will look into this.

Also, maybe the compatibility is better addressed to openai-node, as the project relies on the official OpenAI node SDK, and llama-cpp-python compatibility with that library would mean compatibility with many other projects using openai-node.

https://github.com/openai/openai-node/issues

**Comment by vladiliescu** [comment, marked as answer]
@0x33taji I've managed to get it working -- the key was using `http://localhost:8000/v1` for `baseUrl`

## Run command

```
python3 -m llama_cpp.server \
    --model "<path-to-models>/nous-hermes-2-mixtral-8x7Bb-dpo/Nous-Hermes-2-Mixtral-8x7B-DPO.Q5_K_M.gguf" \
    --chat_format chatml --n_gpu_layers -1 --n_ctx 8192
```

## librechat.yaml

```
# Configuration version (required)
version: 1.0.2

cache: true

# Definition of custom endpoints
endpoints:
  custom:      
    - name: "Local LLAMA"   
      apiKey: "1234"
      baseURL: "http://localhost:8000/v1"
      models:
        default: ["Nous-Hermes-2-Mixtral-8×7B-DPO.Q5_K_M.gguf"]
        fetch: true
      titleConvo: true
      titleModel: "Nous-Hermes-2-Mixtral-8×7B-DPO.Q5_K_M.gguf"
      summarize: false
      summaryModel: "Nous-Hermes-2-Mixtral-8×7B-DPO.Q5_K_M.gguf"
      forcePrompt: false
      modelDisplayLabel: "Mixtral"
```
