### DISCUSSION TITLE
Fireworks.AI not working since last update

### DISCUSSION THREAD

**Discussion by comeback01** [danny-avila/LibreChat#1781] [Troubleshooting]
### What happened?

Since the last update, Fireworks.ai does not work.

I've tried with a new installation, and I have the same problem.

Let me show you my :

`version: 1.0.2
cache: true
# Example Registration Object Structure
endpoints:
  custom:
    # OpenRouter.ai API
    - name: "Chat"
      apiKey: "XXXXXX"
      baseURL: "https://openrouter.ai/api/v1"
      models:
        default: ["nousresearch/nous-hermes-2-mixtral-8x7b-dpo"]
        fetch: false
      titleConvo: true
      titleModel: "gryphe/mythomist-7b:free"
      summarize: false
      summaryModel: "gryphe/mythomist-7b:free"
      forcePrompt: false  # Changed to true to use the prompt system
      modelDisplayLabel: "Chat"

      
   

       # Fireworks.ai
    - name: "Vision"
      apiKey: "XXXXXX"
      baseURL: "https://api.fireworks.ai/inference/v1"
      models:
        default: ["accounts/fireworks/models/firellava-13b"]
        fetch: false
      titleConvo: true
      titleModel: "accounts/fireworks/models/llama-v2-7b-chat"
      summarize: false
      summaryModel: "accounts/fireworks/models/llama-v2-7b-chat"
      forcePrompt: false  # Changed to true to use the prompt system
      modelDisplayLabel: "Vision"      
      `

### Steps to Reproduce

Install a new VPS.

Install LibreChat.

Configure files

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
LibreChat         | 2024-02-12 17:16:54 error: [OpenAIClient.chatCompletion] Unhandled error type Error: 400 [{'loc': ('body', 'user'), 'msg': 'extra fields not permitted', 'type': 'value_error.extra'}]
LibreChat         | 2024-02-12 17:16:54 error: [handleAbortError] AI response error; aborting request: Error: 400 [{'loc': ('body', 'user'), 'msg': 'extra fields not permitted', 'type': 'value_error.extra'}]
```

### Screenshots

![Capture d'écran 2024-02-12 180920](https://github.com/danny-avila/LibreChat/assets/17897116/5228fd08-51e1-400e-95e7-db84a31150a5)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
See how to drop extra params: https://docs.librechat.ai/install/configuration/custom_config.html#dropparams

The `user` field is not recognized and will be rejected by a few APIs like mistral API as well

```yaml
   # Fireworks.ai
- name: "Vision"
  apiKey: "XXXXXX"
  baseURL: "https://api.fireworks.ai/inference/v1"
  models:
    default: ["accounts/fireworks/models/firellava-13b"]
    fetch: false
  titleConvo: true
  titleModel: "accounts/fireworks/models/llama-v2-7b-chat"
  summarize: false
  summaryModel: "accounts/fireworks/models/llama-v2-7b-chat"
  forcePrompt: false
  modelDisplayLabel: "Vision"      
  dropParams: ["user"] # <---------------------- added this
```

Note: To verify your YAML config, you can use online tools like yamlchecker.com
