### DISCUSSION TITLE
Using Authelia as OpenID client

### DISCUSSION THREAD

**Discussion by cellulosa** [danny-avila/LibreChat#1855] [Q&A]
Has anyone managed to use Authelia as OpenID client?

I set the following on my docker-compose under librechat's environment variables:

```yml
      - OPENID_CLIENT_ID=librechat
      - OPENID_CLIENT_SECRET=${LIBRECHAT_OPENID_SECRET}
      - OPENID_ISSUER=https://auth.${MY_DOMAIN}/api/oidc/authorization
      - OPENID_SESSION_SECRET=${LIBRECHAT_OPENID_SESSION_SECRET}
      - OPENID_SCOPE=openid profile email
      - OPENID_CALLBACK_URL=/oauth/openid/callback
      - OPENID_BUTTON_LABEL=Login with Authelia
```

and these on the authelia's `configuration.yml`

```yml
identify_providers:
  oicd:
    clients:
      - 
        id: librechat
        secret: ${LIBRECHAT_OPENID_SECRET}
```

But when I click on the login button I'm hit with `Internal Server Error`:

```bash
librechat           | Error: Unknown authentication strategy "openid"
librechat           |     at attempt (/app/node_modules/passport/lib/middleware/authenticate.js:193:39)
librechat           |     at authenticate (/app/node_modules/passport/lib/middleware/authenticate.js:370:7)
librechat           |     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
librechat           |     at next (/app/node_modules/express/lib/router/route.js:144:13)
librechat           |     at Route.dispatch (/app/node_modules/express/lib/router/route.js:114:3)
librechat           |     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
librechat           |     at /app/node_modules/express/lib/router/index.js:284:15
librechat           |     at Function.process_params (/app/node_modules/express/lib/router/index.js:346:12)
librechat           |     at next (/app/node_modules/express/lib/router/index.js:280:10)
librechat           |     at /app/node_modules/express-rate-limit/dist/index.cjs:659:7
```

**Comment by cellulosa** [comment]
Alright, after reading more slowly the [official documentation](https://www.authelia.com/c/oidc) and looking at some blog posts ([such as this one](https://helgeklein.com/blog/owncloud-infinite-scale-with-openid-connect-authentication-for-home-networks/)), I realised I was missing some settings on the `docker-file`:

```yml
      - DOMAIN_CLIENT=https://chat.${MY_DOMAIN}
      - DOMAIN_SERVER=https://chat.${MY_DOMAIN}
      - ALLOW_SOCIAL_LOGIN=true
      - OPENID_CLIENT_ID=${LIBRECHAT_OPENID_CLIENT}
      - OPENID_CLIENT_SECRET=${LIBRECHAT_OPENID_SECRET}
      - OPENID_ISSUER=https://auth.${MY_DOMAIN}
      - OPENID_SESSION_SECRET=${LIBRECHAT_OPENID_SESSION_SECRET}
      - OPENID_SCOPE=openid groups email profile
      - OPENID_CALLBACK_URL=/oauth/openid/callback
      - OPENID_BUTTON_LABEL=Login with Authelia
```

And on Authelia's config:

```yml
identify_providers:
  oicd:
    issuer_private_key: ${AUTHELIA_IDENTITY_PROVIDERS_OIDC_ISSUER_PRIVATE_KEY}
    clients:
      - 
        id: ${LIBRECHAT_OPENID_CLIENT}
        secret: ${LIBRECHAT_OPENID_SECRET}
        redirect_uris:
          - https://chat.${MY_DOMAIN}/oauth/openid/callback
```
