### DISCUSSION TITLE
[Bug]: custom stop words are not implemented for completions

### DISCUSSION THREAD

**Discussion by dannykorpan** [danny-avila/LibreChat#1913] [Troubleshooting]
### What happened?

I've tried using the openrouter.ai model "perplexity/sonar-medium-online," which is defined inside the librechat.yaml. However, when I attempt to use it now, I receive the following error:
```
Something went wrong. Here's the specific error message we encountered: Error: {"error":{"message":"custom stop words are not implemented for completions.","type":"unsupported_parameter","code":400}}
```

### Steps to Reproduce

1. Insert "perplexity/sonar-medium-online" in librechat.yaml
2. Docker compose down && docker compose up -d
3. Using it via OpenRouter

### Relevant log output

```shell
LibreChat API Container
`
2024-02-27 10:31:38 warn: [OpenAIClient.chatCompletion][stream] API error
2024-02-27 10:31:38 warn: [OpenAIClient.chatCompletion][finalChatCompletion] API error
2024-02-27 10:31:38 error: [OpenAIClient.chatCompletion] Unhandled error type Error: {"error":{"message":"custom stop words are not implemented for completions.","type":"unsupported_parameter","code":400}}
2024-02-27 10:31:38 error: [handleAbortError] AI response error; aborting request: Error: {"error":{"message":"custom stop words are not implemented for completions.","type":"unsupported_parameter","code":400}}
```
```


### Screenshots

<img width="772" alt="image" src="https://github.com/danny-avila/LibreChat/assets/8004507/ada64fbb-d04c-42b7-8d47-766039a2cc56">


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Use `dropParams` in your custom configuration to remove `stop` from being sent to the request: https://docs.librechat.ai/install/configuration/custom_config.html#dropparams

**Comment by dannykorpan** [comment]
Works, thanks!

**Reply by danny-avila** [reply]
Great! Do you mind sharing your setup? Going to be compiling a list of known compatible endpoints/setups soon.

**Reply by danny-avila** [reply]
Oh nevermind, saw you said OpenRouter, got that documented already :)

**Comment by dannykorpan** [comment]
Some endpoint examples
```
endpoints:
  custom:
    - name: "Gemini"
      apiKey: "APIKEYHERE"
      baseURL: "https://openrouter.ai/api/v1"
      models:
        default: ["google/gemini-pro", "google/gemini-pro-vision"]
        fetch: false
      titleConvo: true
      titleModel: "openai/gpt-3.5-turbo-0125"
      summarize: true
      summaryModel: "openai/gpt-3.5-turbo-0125"
      forcePrompt: false
      modelDisplayLabel: "Gemini"
    - name: "Perplexity"
      apiKey: "APIKEYHERE"
      baseURL: "https://openrouter.ai/api/v1"
      iconURL: "https://seeklogo.com/images/P/perplexity-ai-logo-13120A0AAE-seeklogo.com.png"
      models:
        default: ["perplexity/sonar-medium-online"]
        fetch: false
      titleConvo: true
      titleModel: "openai/gpt-3.5-turbo-0125"
      summarize: true
      summaryModel: "openai/gpt-3.5-turbo-0125"
      forcePrompt: false
      modelDisplayLabel: "Perplexity"
      dropParams:
        - "stop"
    - name: "Mistral AI"
      apiKey: "APIKEYHERE"
      baseURL: "https://openrouter.ai/api/v1"
      iconURL: "https://mistral.ai/images/favicon/favicon-32x32.png"
      models:
        default: ["mistralai/mistral-large"]
        fetch: false
      titleConvo: true
      titleModel: "openai/gpt-3.5-turbo-0125"
      summarize: true
      summaryModel: "openai/gpt-3.5-turbo-0125"
      forcePrompt: false
      modelDisplayLabel: "Mistral AI"
    - name: "Claude"
      apiKey: "APIKEYHERE"
      baseURL: "https://openrouter.ai/api/v1"
      iconURL: "https://claude.ai/apple-icon.png"
      models:
        default: ["anthropic/claude-2.1"]
        fetch: false
      titleConvo: true
      titleModel: "openai/gpt-3.5-turbo-0125"
      summarize: true
      summaryModel: "openai/gpt-3.5-turbo-0125"
      forcePrompt: false
      modelDisplayLabel: "Claude"
```
