### DISCUSSION TITLE
[Question]: Ask about the Azure OPENAI deployment

### DISCUSSION THREAD

**Discussion by tensorstart** [danny-avila/LibreChat#1939] [Troubleshooting] [answered]
### What is your question?

Hello, We can use this demo to communicate with our Azure Open AI, but we need to use **proxy http://xxx.xxx.xxx.xxx:3128**.
```python
import os
from openai import AzureOpenAI
# from langchain_community.document_loaders import DirectoryLoader
# from langchain.text_splitter import CharacterTextSplitter
os.environ["http_proxy"] = "http://xxx.xxx.xxx.xxx:3128"
os.environ["https_proxy"] = "http://xxx.xxx.xxx.xxx:3128"
 
access_token = "our_api key"
client = AzureOpenAI(
    api_key=access_token,
    api_version="2023-07-01-preview",
    azure_endpoint="https://openaichatgpt-xxxx.openai.azure.com/"
)
 
# 定义聊天交互（包括机器人的问候语）
conversation = [
    {"role": "system", "content": "You are a helpful assistant."}
]
 
# 发送聊天请求
response = client.chat.completions.create(
    model="gpt-35-turbo",
    messages=conversation,
    temperature=0.8,
    max_tokens=50
)
 
# 提取机器人的回复
bot_reply = response.choices[-1].message.content.strip()  # 获取最后一条助手的回复
 
# 打印机器人的回复
print(bot_reply)
current_path = os.getcwd()
print("Current Path:", current_path)
# loader = DirectoryLoader('/home/bcc1wx/repos/wave3_netcom/uut/', glob='**/*.pdf')
# documents = loader.load()
# text_splitter = CharacterTextSplitter(chunk_size=100, chunk_overlap=0)
# # 切割加载的 document
# split_docs = text_splitter.split_documents(documents)
```

The configuration of .env calling Docker is as follows：
.env

```yml
CONFIG_PATH="/home/xxxx/repos/xxxx/docker/LibreChat/librechat.yaml"

#===================================================#
#                     Endpoints                     #
#===================================================#

ENDPOINTS=azureOpenAI

PROXY="http://xx.xx.xx.xx:3128"

#============#
# Azure      #
#============#


# Note: these variables are DEPRECATED
# Use the `librechat.yaml` configuration for `azureOpenAI` instead
# You may also continue to use them if you opt out of using the `librechat.yaml` configuration

AZURE_OPENAI_DEFAULT_MODEL=gpt-3.5-turbo 
AZURE_OPENAI_MODELS=gpt-3.5-turbo
AZURE_USE_MODEL_AS_DEPLOYMENT_NAME=TRUE 
AZURE_API_KEY=fxxxxxxxxxxxxxxxxxxxxxxxxx5
AZURE_OPENAI_API_INSTANCE_NAME= 
AZURE_OPENAI_API_DEPLOYMENT_NAME= 
AZURE_OPENAI_API_VERSION=2023-07-01-preview 
AZURE_OPENAI_API_COMPLETIONS_DEPLOYMENT_NAME= 
AZURE_OPENAI_API_EMBEDDINGS_DEPLOYMENT_NAME= 
PLUGINS_USE_AZURE="true" 

```

Could you please help providing a sample of .env and librechat.yml to fit our demo，thank you very much

### More Details

The following error is reported in the web page dialog box：
```html
Something went wrong. Here's the specific error message we encountered: Error: 400 <HTML><HEAD> <TITLE>Request Error</TITLE> <link rel="shortcut icon" href="https://rbins.xxxxx.com/gfx/favicon.ico"> <link rel="stylesheet" href="https://rbins.xxxxx.com/gfx/styles.css"> </HEAD> <BODY> <table> <TR> <td width="128" ><img height=31 src=https://rbins.xxxxx.com/gfx/xxxxx_logo.png alt=xxxxx></td> <td width="700" align="center"><h1 class="errorsum_header">Request Error</h1></td> </TR> <TR> <.
```

We initially configured only the librechat.yml file, but it did not take effect.This is librechat.yml file:
```yml
endpoints:
  azureOpenAI:
    titleModel: "gpt-35-turbo"
    plugins: true
    groups:
      - group: "xxx_xxx1.1" # arbitrary name
        apiKey: "fexxxxxxxxxxxxxxxxxxxxx25"
        instanceName: "OpenAIChatGPT-xxxx" # name of the resource group or instance
        version: "2023-07-01-preview"
        baseURL: "https://openaichatgpt-xxxx.openai.azure.com/deployments/gpt-35-turbo"
        proxies:
          http: "http://xx.xxx.xxx.xx:3128"
          https: "http://xx.xxx.xxx.xx:3128"
        # additionalHeaders:
        #   X-Custom-Header: value
        models:
          gpt-3.5-turbo:
            deploymentName: "gpt-35-turbo"
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
