### DISCUSSION TITLE
LibreChat just outputs nonsense text using LiteLLM and Ollama

### DISCUSSION THREAD

**Discussion by Linutux** [danny-avila/LibreChat#1960] [Troubleshooting]
### What happened?

When even asking a simple question, the answer is just nonsense:

> You:
> What's your name?
> 
> AI:
> ::ass:tieWhatassie User youristant your Corieass duass he Wi AssistantistantWhat' Assistant?ass: name:istantsistant User Assistant heWhatistant4:: he Cor:::tass Wi
> ' name Cor

That is my librechat.yaml:

```
version: 1.0.1
cache: true
# see more config in https://docs.librechat.ai/install/configuration/ai_endpoints.html
endpoints:
  custom:
    # LiteLLM
    - name: "XXX.de"
      apiKey: "sk-XXXXXXXXXXXX"
      baseURL: "https://api.xxx.xxx.de"
      models:
        default: ["openhermes:latest", "starling-lm:7b", "openchat:latest", "dolphin-mistral:latest", "mistral-openorca:latest", "stable-code:latest"]
        fetch: true
      titleConvo: true
      titleModel: "openhermes:latest"
      summarize: false
      summaryModel: "openhermes:latest"
      forcePrompt: false
      modelDisplayLabel: "AI"
      drop_params: true
      stream: true
```

### Steps to Reproduce

1. Install LibreChat in docker
2. Connect to LiteLLM in docker
3. Connect LiteLLM to Ollama in docker

### What browsers are you seeing the problem on?

Firefox, Mobile (Android)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
You can try adjusting the temperature according to what's recommended for the model you are using. That might be affecting the response.

```yaml
    addParams:
        - temperature: 0.5
```

https://docs.librechat.ai/install/configuration/custom_config.html#addparams

**Reply by Linutux** [reply]
Unfortunately, that didn't help.

It's on every model, not just one. 

When connecting to LiteLLM via Chatbox AI (and other UIs) everything works fine. There must be some sort of difference in configuration.

**Reply by danny-avila** [reply]
It's probably one of the default parameters that is affecting every model: https://docs.librechat.ai/install/configuration/custom_config.html#default-parameters

You can try removing them all with `dropParams` which I noticed you have set to `drop_params`. This is not configured right:

```yaml
drop_params: true # won't do anything
```

The correct configuration for this field is shown here as `dropParams`: https://docs.librechat.ai/install/configuration/custom_config.html#dropparams

You should specify which params to drop.

Tagging @Berry-13 and @bsu3338 who use Ollama with LibreChat and have not reported this issue.

**Reply by danny-avila** [reply]
FWIW I just tested Ollama with mistral:latest with no issues and the following config:

```yaml
    - name: "Ollama"
      apiKey: "ollama"
      baseURL: "http://localhost:11434/v1/"
      models:
        default: [
          "mistral",
          ]
        fetch: false # fetching list of models is not supported
      titleConvo: true
      titleModel: "mistral"
      summarize: false
      summaryModel: "mistral"
      forcePrompt: false
      modelDisplayLabel: "Ollama"
```

I have the latest version of Ollama and I ran `ollama serve` and setup my config as above


![image](https://github.com/danny-avila/LibreChat/assets/110412045/fcfe48cf-bbd6-4010-915f-66b4b238728d)
