### DISCUSSION TITLE
[Question]: Azure OpenAI, troubleshoot error 500

### DISCUSSION THREAD

**Discussion by aechegoyan17** [danny-avila/LibreChat#2008] [Troubleshooting] [answered]
### What is your question?

I have configured Azure's vision preview GPT4, specifically version 2024-02-15-preview, but I can't get it to respond to anything.

I checked #1420 since it is the same problem but it seems that user shangbinpan fixed it on his own or forgot about the issue.

### More Details

I checked the deployment in other clients such as LobeChat to ensure it wasn't an issue with the model deployment in Azure and it seems to work fine so I guess it's either LibreChat or the way I have configured it.

Here is a sample of the endpoint definition in librechat.yml:
```
endpoints:
  azureOpenAI:
    titleConvo: true
    titleModel: "gpt-4-vision-preview"
    plugins: false
    groups:
      - group: "ai-tests" # arbitrary name
        apiKey: "whateverapikey"
        instanceName: "aivision-test" # name of the resource group or instance
        version: "2024-02-15-preview"
        models:
          gpt-4-vision-preview:
            deploymentName: gpt-4-vision
            version: "2024-02-15-preview"
```

Error traces:

[OpenAIClient.chatCompletion] Unhandled error type Error: 500 The server had an error while processing your request. Sorry about that!","stack":"Error: Error: 500 The server had an error while processing your request. Sorry about that!
at OpenAIClient.chatCompletion (/app/api/app/clients/OpenAIClient.js:1187:15)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async OpenAIClient.sendCompletion (/app/api/app/clients/OpenAIClient.js:604:15)
at async OpenAIClient.sendMessage (/app/api/app/clients/BaseClient.js:449:24)
at async AskController (/app/api/server/controllers/AskController.js:125:20)
at async /app/api/server/routes/ask/openAI.js:24:5"

[handleAbortError] AI response error; aborting request: Error: 500 The server had an error while processing your request. Sorry about that!","stack":"Error: Error: 500 The server had an error while processing your request. Sorry about that!
at OpenAIClient.chatCompletion (/app/api/app/clients/OpenAIClient.js:1187:15)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async OpenAIClient.sendCompletion (/app/api/app/clients/OpenAIClient.js:604:15)
at async OpenAIClient.sendMessage (/app/api/app/clients/BaseClient.js:449:24)
at async AskController (/app/api/server/controllers/AskController.js:125:20)
at async /app/api/server/routes/ask/openAI.js:24:5"

### What is the main subject of your question?

Installation, Endpoints

### Screenshots

<img width="670" alt="image" src="https://github.com/danny-avila/LibreChat/assets/161015547/870dff98-bf8f-4a20-a763-62cd7106f516">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
