### DISCUSSION TITLE
Enhancement: add option to customize favicon

### DISCUSSION THREAD

**Discussion by GauthierPLM** [danny-avila/LibreChat#2094] [Feature Requests & Suggestions]
### What features would you like to see added?

It's currently possible to change the title displayed in the tab browser and the text displayed in the footer. I'd like to customize the favicon to set a custom icon.

### More details

This would help in enterprise environment to customize LibreChat to the company' identity.

### Which components are impacted by your request?

UI

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by theorchestrator** [comment]
I haven't tried it personally, but wouldn't that already be achievable by replacing the favicon files in "\client\dist\assets" and "\client\public\assets" ?

However I understand that having automatic favicon generation would be a nice customization feature.

**Comment by GauthierPLM** [comment]
@theorchestrator that was my initial intention but when using the published docker images, it is necessary to override the favicons using docker-compose.override.yml. Having a configuration would avoid the changes in docker-compose configuration.

This is the config I used:

```yaml
version: '3.4'
services:
  api:
    volumes:
      - ./favicon-16x16.png:/app/client/dist/assets/favicon-16x16.png
      - ./favicon-32x32.png:/app/client/dist/assets/favicon-32x32.png
      - ./favicon-16x16.png:/app/client/public/assets/favicon-16x16.png
      - ./favicon-32x32.png:/app/client/public/assets/favicon-32x32.png
```
