### DISCUSSION TITLE
[Question]:

### DISCUSSION THREAD

**Discussion by PedroGruvhagen** [danny-avila/LibreChat#2127] [Troubleshooting]
### What is your question?

Hello guys :)
I have not been able to make Azure Assistants work, 
![image](https://github.com/danny-avila/LibreChat/assets/129173525/ab4ebe06-0f7d-46cb-b756-8571bca4a94f)

### More Details

First, many thanks for the great work and cheers from Sweden!

I have checked everything five times, and in Azure, the assistants are being created and they work, but in LibreChat, I only get "Assistant not supported" Also, I can see the list of all the agents I created in Librechat that are in Azure until I close the windows, is very weird, the plugins from Librechat appear in Azure, as a connection and from Azure all work like it should :(

### What is the main subject of your question?

Endpoints

### Screenshots

Assistants for Azure.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Hard to tell what's going on without your YAML configuration. Please provide it with sensitive details redacted

**Reply by danny-avila** [reply]
azure assistant working fine on my end: 
![image](https://github.com/danny-avila/LibreChat/assets/110412045/b7431cc3-8c7b-4570-9d96-4cb34db53db7)

**Reply by PedroGruvhagen** [reply]
Hello, wow, many thanks for the fast response!
[copylibrechat.txt](https://github.com/danny-avila/LibreChat/files/14628792/copylibrechat.txt)
Sorry it took me a minute or two to respond I was putting X in the keys hahaha

**Reply by danny-avila** [reply]
Part of the issue is that you have multiple deployments marked as assistants-capable. This is fine when they are all compatible, but they are not.

Try removing gpt-4-vision-preview and put it into its own group. it doesn't matter if the credentials are the same, as long as the group name is different.

**Reply by PedroGruvhagen** [reply]
Here is a photo of Azure's assistant's playground; they are being created... :(

![image](https://github.com/danny-avila/LibreChat/assets/129173525/bad7d992-974f-4570-9dbb-1af74a819364)

again, many thanks for the help

**Reply by danny-avila** [reply]
You can check the[ compatible regions and models in the Azure docs here ](https://learn.microsoft.com/en-us/azure/ai-services/openai/concepts/models#assistants-preview).

**Reply by danny-avila** [reply]
FYI `"Assistant not supported"`  is an error message when the Assistant you are using is not in the `supportedIds` list.

**Reply by PedroGruvhagen** [reply]
I tried that; it might be the vision thing; I messed up the whole file, I think; many thanks! I will come back after testing, to let everyone know, in case someone get the same problem, thanks

**Reply by PedroGruvhagen** [reply]
@danny-avila I have tried moving Vision to another group, also taking it out completely, and adding all the assistant's IDs to the un-commented supported IDs. Sadly, I got the same error; I checked the compatible regions for Vision and Assistants. I have the assistants here in Sweden, in Sweden Central, and as I said, they appear in Azure.
What else could it be?

**Reply by danny-avila** [reply]
if it's the same error, wouldn't it be your `supportedIds` configuration? or `excludedIds`? do you have that set?

**Reply by PedroGruvhagen** [reply]
hej! :)

I have it as this:
![image](https://github.com/danny-avila/LibreChat/assets/129173525/9f66665f-e481-4447-9179-c96e6b19effe)

**Reply by danny-avila** [reply]
and you're using one of those supported assistant ids? can you share your logs when the error happens

**Reply by PedroGruvhagen** [reply]
![image](https://github.com/danny-avila/LibreChat/assets/129173525/98093acd-e23d-4d56-870a-ca30e54328ad)
The error file is empty. Is there any debug option I'm missing?

**Reply by danny-avila** [reply]
no it's fine, the debug log is sufficient. if you recreate the error and we look at that

**Reply by PedroGruvhagen** [reply]
sure thing!, many thanks for all your time sir!

![image](https://github.com/danny-avila/LibreChat/assets/129173525/0957f350-3b36-4cee-8143-b2cfa95988cb)

![image](https://github.com/danny-avila/LibreChat/assets/129173525/e0ec7a4d-c2ef-41fc-ad4f-09f98490f383)
[debug-2024-03-18.log](https://github.com/danny-avila/LibreChat/files/14636055/debug-2024-03-18.log)

**Reply by danny-avila** [reply]
I don't see a request being made in the debug logs. You can also share the assistant builder form through a screenshot to confirm you are using the supported assistant ID.

You need to be sure you are using that same assistant, and make sure it's in the expected resource group you marked as assistants capable, i.e. "GPT-4Turbo".

My recommendation is to remove "supportedIds" or "excludedIds" for testing, and then configure them after you've confirmed it's working.

**Reply by PedroGruvhagen** [reply]
What do you think about the .env file? It contains some configurations for assistants, and I am using the Azure info there; do you know if that is correct?
![image](https://github.com/danny-avila/LibreChat/assets/129173525/be0279d3-dad9-479d-ac7a-805daf4c651e)

**Reply by PedroGruvhagen** [reply]
Hey! I tried following your recommendation and commented out both supported and excluded 
![image](https://github.com/danny-avila/LibreChat/assets/129173525/aa992f9e-64b4-4f30-b910-9d42bd692eb6)

After that, I got a new message, error 401, so undo the changes on the file, but still, now the whole Azure gives that error, Claude, SD, and the other work; I rotated the API key, but nothing :(

![image](https://github.com/danny-avila/LibreChat/assets/129173525/5cedb41e-4cf9-4004-a48e-3888a04ee840)
I cloned the repository from zero, only took the .env and yaml files with me, and started the whole thing, but I got the same new error. So weird

**Reply by PedroGruvhagen** [reply]
hello, I just wanted to let you know that I got everything working including the assistants, at the assistants configuration in the.env file in the endpoint I added /openai, at the end of my endpoint and everything worked direct.

I want to say many thanks for all the help, I appreciate it a lot, I know you probably have a lot to do .

Cheers!

**Reply by danny-avila** [reply]
Glad you got it figured out!

**Reply by acotor** [reply]
@PedroGruvhagen Hi, glad to hear you made it work🎉. Could you please provide the final YAML config that you revised as an example? With sensitive info redacted absolutely :)

**Reply by PedroGruvhagen** [reply]
Absolutely!
[librechat.txt](https://github.com/danny-avila/LibreChat/files/14694032/librechat.txt)

**Reply by acotor** [reply]
Thanks! But I find nothing that could be wrong with my YAML file. When start Libre, I can't select any assistant that I specified in `supportedIds`, the drop-down menu is empty at the right-hand side panel. I can't create new assistant with the Builder in Librechat.

> the.env file in the endpoint I added /openai

I wonder what do you mean by ‘add /openai’ and if any additional config should be added to the .env file. Could you tell me more details about this?

**Reply by PedroGruvhagen** [reply]
The drop-down menu at the right-hand side panel was also empty for me, so it must be the same problem.
![image](https://github.com/danny-avila/LibreChat/assets/129173525/2bcbaaa7-7054-458f-ab38-fd42ab0f5d55)

also, in my current setup, I deleted the supportedIds and restrictedIds, I want all assistants all the time, works perfect
![image](https://github.com/danny-avila/LibreChat/assets/129173525/6b8caaa6-1e4e-4162-8bb6-1bbc056b0b9c)

**Reply by danny-avila** [reply]
@acotor maybe I can help. Share your librechat.yaml, here's my working setup:

```yaml
version: 1.0.5
cache: true
endpoints:
  azureOpenAI:
    titleModel: "gpt-3.5-turbo-1106"
    titleConvo: true
    assistants: true # <-------- critical
    groups:
    - group: "region-westus"
      apiKey: "${WESTUS_API_KEY}"
      instanceName: "region-westus"
      version: "2024-03-01-preview"
      models:
        gpt-3.5-turbo:
          deploymentName: "gpt-35-turbo"
        gpt-3.5-turbo-1106:
          deploymentName: "gpt-35-turbo-1106"
        gpt-4:
          deploymentName: "gpt-4"
    - group: "region-sweden"
      apiKey: "${SWEDEN_API_KEY}"
      instanceName: "region-sweden"
      deploymentName: gpt-4-1106-preview
      version: "2024-03-01-preview"
      assistants: true # <-------- critical
      models:
        gpt-4-turbo: true
    - group: "azure-openai"
      apiKey: "${AZURE_OAI_API_KEY}"
      instanceName: "azure-openai"
      deploymentName: gpt-4-1106-preview
      version: "2024-03-01-preview"
      assistants: true # <-------- critical
      models:
        gpt-4-1106-preview: true
        gpt-4-vision-preview:
          deploymentName: gpt-4-vision-preview
  assistants:
    supportedIds: ["asst_Rfl3UX9tUU0A6reEbCvaN1kh"] # <-------- critical
```

### list of assistants before `supportedIds` config (not set)
![image](https://github.com/danny-avila/LibreChat/assets/110412045/9970773c-0c3c-4412-9033-33f0d59d6f55)


### list of assistants after `supportedIds` config
![image](https://github.com/danny-avila/LibreChat/assets/110412045/9b165f6f-9e8f-4faa-a0d1-81c897ec395e)

### Chatting with supported assistant

![image](https://github.com/danny-avila/LibreChat/assets/110412045/26bcface-d3c1-4f6b-bc63-90a730a24569)


My guess is that you are not marking the correct group as `assistants` compatible where your assistants are located, or you're not setting `assistants` at the endpoint level, both of which could be why they wouldn't show up, or your config file changes are not being picked up (less likely)
