### DISCUSSION TITLE
Connect htts

### DISCUSSION THREAD

**Discussion by mitya-shepelev** [danny-avila/LibreChat#2154] [Q&A]
Hi community, I have this question, it is about documentation, I can install chat on a clean ubuntu server, there is no problem with that. I can point my domain to the server so that the chat opens through the domain, no problem with that either.

1. What is the correct way to connect ssl certificate to the domain after installing the chat to make it work over a secure connection.

2. Can anyone make the correct instructions how to connect ssl through Traefik. To make it work normally!

There is a lot of confusion in the documentation.

**Comment by fuegovic** [comment]
I haven't tested, but adding something like this in the override file should retrieve a certificate from "Let's Encrypt"  

(Replace `your@email.com` with your email address)

```yaml
version: '3'

services:
  api:
      labels:
      - "traefik.enable=true"
      - "traefik.http.routers.librechat.rule=Host(`your.domain.name`)"
      - "traefik.http.routers.librechat.entrypoints=websecure"
      - "traefik.http.routers.librechat.tls.certresolver=leresolver"
      - "traefik.http.services.librechat.loadbalancer.server.port=3080"
      networks:
      - web
      - librechat_default
      volumes:
      - ./librechat.yaml:/app/librechat.yaml
  
  traefik:
      image: traefik:v2.9
      ports:
      - "80:80"
      - "443:443"
      volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
      networks:
      - web
      command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.leresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.leresolver.acme.email=your@email.com"
      - "--certificatesresolvers.leresolver.acme.storage=/letsencrypt/acme.json"
  
  networks:
    web:
        external: true
    librechat_default:
        external: true
```
