### DISCUSSION TITLE
Anthropic Claude 3 API issue

### DISCUSSION THREAD

**Discussion by a7t0fwa7** [danny-avila/LibreChat#2199] [Troubleshooting] [answered]
### What happened?

When I select a Claude 3 model i get an error message as shown in the image. API works fine for Claude 2.1 just not 3... :(
![image](https://github.com/danny-avila/LibreChat/assets/43460290/377aa5b7-c9d9-4ebe-9aa7-5f1fff30d48d)

### Steps to Reproduce

Enter Claude API key and try using Claude 3 Model

### What browsers are you seeing the problem on?

Chrome

### Screenshots

![image](https://github.com/danny-avila/LibreChat/assets/43460290/b77372e1-4d9e-42fe-9f33-dc99a48e7a68)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
I use claude 3 every day, can you confirm you're on the latest commit? 

![image](https://github.com/danny-avila/LibreChat/assets/110412045/13744b8b-92a9-4e13-b070-26d6235a03d7)

I think you're not on the latest version of LibreChat, also judging by the background color.

**Comment by a7t0fwa7** [comment]
I ran the following commands from the docs
```
# Stop the container (if running)
docker compose down
# Switch to the repo's main branch
git checkout main
# Pull the latest changes to the main branch from Github
git pull 
# Prune all LibreChat Docker images
docker rmi librechat:latest
# Remove all unused dangling Docker images.
# Be careful, as this will delete all dangling docker images on your
# computer, also those not created by LibreChat!
docker image prune -f
# Building a new LibreChat image without cache
docker compose build --no-cache

# Start LibreChat
docker compose up
```

And still ran into the same error above are you using a different Git branch?

Here is an output of my main branch 
![image](https://github.com/danny-avila/LibreChat/assets/43460290/5ecfd3d0-5bb3-42e2-b9dc-ef5d8981b709)

Everything works fine apart from Claude 3. Claude 2.1 works fine it's just when I switch to version 3 that I get the error message.

**Reply by danny-avila** [reply]
Those update steps are out of date. They do not include the new necessary step:
```bash
docker compose pull # no longer docker compose build --no-cache
docker compose up
```
will be updating the docs

**Reply by a7t0fwa7** [reply]
This has mitigated the issue, however this seems to have rendered the custom config file invalid
![image](https://github.com/danny-avila/LibreChat/assets/43460290/82596a73-2821-4629-99a8-99d8afedcd20)

Mistral and Groq configs no longer work

**Reply by danny-avila** [reply]
Here's mine, it works. Not sure what's different for you

![image](https://github.com/danny-avila/LibreChat/assets/110412045/9d971f60-5e4c-4bc1-a5dc-7b93f8f5d5b8)


```yaml
version: 1.0.5
cache: true
endpoints:
  custom:
    - name: "Mistral"
      apiKey: "${MISTRAL_API_KEY}"
      # apiKey: "user_provided"
      baseURL: "https://api.mistral.ai/v1"
      models:
        default: ["mistral-tiny", "mistral-small", "mistral-medium", "mistral-large-latest"]
        fetch: true
      titleConvo: true
      titleMethod: "completion"
      titleModel: "mistral-tiny"
      summarize: false
      summaryModel: "mistral-tiny"
      forcePrompt: false
      modelDisplayLabel: "Mistral"
      # Drop Default params parameters from the request. See default params in guide linked below.
      # NOTE: For Mistral, it is necessary to drop the following parameters or you will encounter a 422 Error:
      dropParams: ["stop", "user", "frequency_penalty", "presence_penalty"]
    # openrouter.ai
    - name: "OpenRouter"
      apiKey: "${OPENROUTER_KEY}"
      # apiKey: "user_provided"
      baseURL: "https://openrouter.ai/api/v1"
      models:
        default: ["gpt-3.5-turbo"]
        fetch: true
      titleConvo: true
      titleModel: "gpt-3.5-turbo"
      summarize: false
      summaryModel: "gpt-3.5-turbo"
      forcePrompt: false
      modelDisplayLabel: "OpenRouter"
      # Recommended: Drop the stop parameter from the request as Openrouter models use a variety of stop tokens.
      dropParams: ["stop"]
    - name: "groq"
      apiKey: "${GROQ_API_KEY}"
      baseURL: "https://api.groq.com/openai/v1/"
      models:
        default: [
          "llama2-70b-4096",
          "mixtral-8x7b-32768"
          ]
        fetch: false
      titleConvo: true
      titleModel: "mixtral-8x7b-32768"
      summarize: false
      summaryModel: "mixtral-8x7b-32768"
      forcePrompt: false
      modelDisplayLabel: "groq"
      iconURL: "https://raw.githubusercontent.com/fuegovic/lc-config-yaml/main/icons/groq.png"
    - name: "Ollama"
      apiKey: "ollama"
      baseURL: "http://localhost:11434/v1/"
      models:
        default: [
          "mistral",
          "llama2:13b"
          ]
        fetch: false # fetching list of models is not supported
      titleConvo: true
      titleModel: "mistral"
      summarize: false
      summaryModel: "mistral"
      forcePrompt: false
      modelDisplayLabel: "Ollama"
```

**Reply by a7t0fwa7** [reply]
cool thanks I will try it out and let you know if that does the trick.

**Reply by danny-avila** [reply]
`cache` omitted seems to be throwing an error when it shouldn't, just set it to true for now

**Reply by a7t0fwa7** [reply]
roger that

**Reply by danny-avila** [reply]
Made it optional now: https://github.com/danny-avila/LibreChat/commit/5c3c28009f47b3cffa6cde507f96244345b5dd10

**Reply by a7t0fwa7** [reply]
cool

**Reply by a7t0fwa7** [reply]
It's odd I tried using your librechat.yaml config file and it throws the same error message so I am stumped right now. Oh well at least Cluade 3 works just fine

**Reply by a7t0fwa7** [reply]
```yaml
version: 1.0.5
cache: true
# fileStrategy: "firebase"  # If using Firebase CDN
fileConfig:
  endpoints:
    assistants:
      fileLimit: 5
      # Maximum size for an individual file in MB
      fileSizeLimit: 100
      # Maximum total size for all files in a single request in MB
      totalSizeLimit: 500 
      # In case you wish to limit certain filetypes
      supportedMimeTypes: 
      - "image/.*"
      - "image/gif"
      - "image/jpeg"
      - "image/png"
      - "application/json"
      - "application/pdf"
      - "application/xml"
      - "text/html"
      - "text/css"
      - "text/javascript"
      - "audio/mpeg"
      - "video/mp4"
      - "text/plain" 
      - "application/javascript" 
      - "application/json" 
      - "application/xml" 
      - "text/html" 
      - "text/x-c" 
      - "text/x-c++" 
      - "text/x-csharp" 
      - "text/x-java-source" 
      - "text/x-python" 
      - "text/x-ruby" 
      - "text/x-php" 
      - "application/x-httpd-php" 
      - "text/markdown" 
      - "application/sql" 
      - "application/x-sh" 
      - "application/x-perl" 
      - "text/x-rust" 
      - "text/x-vlang" 
      - "text/x-zig" 
      - "text/x-odin" 
    openAI:
    # Disables file uploading to the OpenAI endpoint
      disabled: false
    default:
      totalSizeLimit: 20
    # Example for custom endpoints
    YourCustomEndpointName:
      fileLimit: 10
      fileSizeLimit: 100
  # Global server file size limit in MB
  serverFileSizeLimit: 100  
  # Limit for user avatar image size in MB, default: 2 MB
  avatarSizeLimit: 4 
rateLimits:
  fileUploads:
    ipMax: 100
    # Rate limit window for file uploads per IP
    ipWindowInMinutes: 60 
    userMax: 50
    # Rate limit window for file uploads per user
    userWindowInMinutes: 60  
registration:
  socialLogins: ["google", "facebook", "github", "discord", "openid"]
  allowedDomains:
    - "example.com"
    - "anotherdomain.com"
    - "protonmail.com"
    - "proton.me"
endpoints:
  assistants:
    # Disable Assistants Builder Interface by setting to `true`
    disableBuilder: false 
    # Polling interval for checking assistant updates
    pollIntervalMs: 750  
    # Timeout for assistant operations
    timeoutMs: 180000  
    # Should only be one or the other, either `supportedIds` or `excludedIds`
    supportedIds: ["asst_supportedAssistantId1", "asst_supportedAssistantId2"]
    # excludedIds: ["asst_excludedAssistantId"]
    # (optional) Models that support retrieval, will default to latest known OpenAI models that support the feature
    retrievalModels: ["gpt-4-turbo-preview"]
    # (optional) Assistant Capabilities available to all users. Omit the ones you wish to exclude. Defaults to list below.
    capabilities: ["code_interpreter", "retrieval", "actions", "tools"]

  # (optional) Custom endpoints
  custom:
    - name: "Mistral"
      apiKey: "${MISTRAL_API_KEY}"
      baseURL: "https://api.mistral.ai/v1"
      models:
        default: ["mistral-tiny", "mistral-small", "mistral-medium", "mistral-large-latest"]
        # Attempt to dynamically fetch available models
        fetch: true  
        userIdQuery: false
      iconURL: "https://mistral.ai/images/logo_hubc88c4ece131b91c7cb753f40e9e1cc5_2589_256x0_resize_q97_h2_lanczos_3.webp"
      titleConvo: true
      titleModel: "mistral-tiny"
      modelDisplayLabel: "Mistral AI"
      # addParams:
      # Mistral API specific value for moderating messages
      safe_prompt: false 
      dropParams:
        - "stop"
        - "user"
        - "presence_penalty"
        - "frequency_penalty"
      # headers:
      #    x-custom-header: "${CUSTOM_HEADER_VALUE}"
    
    - name: "Perplexity"
      apiKey: "${PERPLEXITY_API_KEY}"
      baseURL: "https://api.perplexity.ai/"
      models:
        default: [
          "mistral-7b-instruct",
          "sonar-small-chat",
          "sonar-small-online",
          "sonar-medium-chat",
          "sonar-medium-online"
          ]
        fetch: false # fetching list of models is not supported
      titleConvo: true
      titleModel: "sonar-medium-chat"
      summarize: false
      summaryModel: "sonar-medium-chat"
      forcePrompt: false
      dropParams: ["stop", "frequency_penalty"]
      modelDisplayLabel: "Perplexity"

    - name: "OpenRouter"
      apiKey: "${OPENROUTER_API_KEY}"
      baseURL: "https://openrouter.ai/api/v1"
      models:
        default: ["gpt-3.5-turbo"]
        fetch: false
      titleConvo: true
      titleModel: "gpt-3.5-turbo"
      modelDisplayLabel: "OpenRouter"
      dropParams:
        - "stop"
        - "frequency_penalty"

    # Groq Example
    - name: 'groq'
      apiKey: '${GROQ_API_KEY}'
      baseURL: 'https://api.groq.com/openai/v1/'
      models:
        default: ['llama2-70b-4096', 'mixtral-8x7b-32768', 'gemma-7b-it']
        fetch: false
      titleConvo: true
      titleModel: 'mixtral-8x7b-32768'
      modelDisplayLabel: 'groq'
```

Here is my YAML file that worked fine before the upgrade
