### DISCUSSION TITLE
How to update easily.

### DISCUSSION THREAD

**Discussion by Passerby1011** [danny-avila/LibreChat#230] [Troubleshooting]
I am a beginner and I am using docker-compose. I would like to ask how to update this project simply. Currently, I am keeping the .env file and deleting the entire project folder, as well as previous docker containers and images, and then recreating them. However, this will cause data loss and is very troublesome.

**Comment by hubbdavid** [comment]
Hi @Passerby1011,
To update this project without deleting the entire project folder and previous Docker containers and images, you can simply run the following command in your terminal while in the project directory:

```
version: "3.4"

services:
  # client:
  #   image: nginx-client
  #   build:
  #     context: .
  #     target: nginx-client
  #   restart: always
  #   ports:
  #     - 3080:80
  #   volumes:
  #     - /client/node_modules
  #   depends_on:
  #     - api
  api:
    container_name: chat-clone
    restart: unless-stopped                    # Ensure that the container always restarts unless stopped intentionally
    ports:
      - 3080:3080               # Change it to 9000:3080 to use nginx
    depends_on:
      - mongodb
    image: node-api            # Comment this & uncomment below to build from docker hub image
    build:
      context: .
      target: node-api
    # image: chatgptclone/app:latest # Uncomment this & comment above to build from docker hub image
    env_file:
      - ./api/.env
    environment:
      - HOST=0.0.0.0
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongodb:27017/chatgpt-clone
      # - CHATGPT_REVERSE_PROXY=http://host.docker.internal:8080/api/conversation # if you are hosting your own chatgpt reverse proxy
      - MEILI_HOST=http://meilisearch:7700
      - MEILI_HTTP_ADDR=meilisearch:7700
    volumes:
      - /client/node_modules
      - ./api:/api
      - /api/node_modules
  mongodb:
    container_name: chat-mongodb
    restart: unless-stopped                     # Ensure that the container always restarts unless stopped intentionally
    ports:
      - 27018:27017
    image: mongo
    volumes:
      - ./data-node:/data/db
    command: mongod --noauth
  meilisearch:
    container_name: chat-meilisearch
    restart: unless-stopped                    # Ensure that the container always restarts unless stopped intentionally
    image: getmeili/meilisearch:v1.0
    ports:
      - 7700:7700
    env_file:
      - ./api/.env
    environment:
      - MEILI_HOST=http://meilisearch:7700
      - MEILI_HTTP_ADDR=meilisearch:7700
    volumes:
      - ./meili_data:/meili_data
```

By doing so, your Docker containers will restart automatically when the Docker daemon starts, and they will not be removed by any Docker commands that stop or restart containers.

I hope this helps! Please let me know if you need help with anything else.

--
David (Developer & Sponsor)
