### DISCUSSION TITLE
Azure OpenAI API instance name not found

### DISCUSSION THREAD

**Discussion by Passerby1011** [danny-avila/LibreChat#2314] [Troubleshooting]
### What happened?

"When I use the plugins endpoint, it prompts Azure OpenAI API instance name not found, but my Azure OpenAI can be used normally. I deployed it using docker and confirmed it is the latest version."
```
version: 1.0.5
cache: true

endpoints:
  azureOpenAI:
    titleModel: "gpt-3.5-turbo"
    assistants: true
    plugins: true
    groups:
    - group: ""
      apiKey: ""
      instanceName: "xxxxx"
    # Mark this group as assistants compatible
      assistants: true
    # version must be "2024-02-15-preview" or later
      version: "2024-03-01-preview"
      models:
        gpt-3.5-turbo:
          deploymentName: "gpt-35-turbo-0125"
        gpt-3.5-turbo-16k: 
          deploymentName: "gpt-35-turbo-16k"
        gpt-4-1106-preview:
          deploymentName: "gpt-4-1106-preview"
        gpt-4-vision-preview:
          deploymentName: "gpt-4-vision-preview"
          version: "2024-03-01-preview"
```
### Steps to Reproduce

"Use plugins endpoint"

### Relevant log output

```
Attempting to load an OpenAPI 3.0.1 spec. This may result in degraded performance. Convert your OpenAPI spec to 3.1.0 for better support.
2024-04-04 17:28:39 error: [handleAbortError] AI response error; aborting request: Azure OpenAI API instance name not found
Attempting to load an OpenAPI 3.0.1 spec. This may result in degraded performance. Convert your OpenAPI spec to 3.1.0 for better support.
Attempting to load an OpenAPI 3.0.0 spec. This may result in degraded performance. Convert your OpenAPI spec to 3.1.0 for better support.
2024-04-04 17:29:37 error: [handleAbortError] AI response error; aborting request: Azure OpenAI API instance name not found
```

### Screenshots

![image](https://github.com/danny-avila/LibreChat/assets/63802758/e157c0ab-015e-410e-92b2-e72ad5505afa)
![image](https://github.com/danny-avila/LibreChat/assets/63802758/e46ea986-5695-4c2c-a21d-e52d2935b1fc)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
is your group name actually empty? Try adding more text there

> group: ""

My config:

```yaml
version: 1.0.5
cache: true
registration:
  socialLogins: ["github", "google", "discord"]
endpoints:
  azureOpenAI:
    titleModel: "gpt-3.5-turbo-1106"
    titleConvo: true
    plugins: true
    groups:
    - group: "region-1"
      apiKey: "${SOME_KEY_MAPPING}"
      instanceName: "REDACTED"
      version: "2024-03-01-preview"
      models:
        gpt-3.5-turbo:
          deploymentName: "gpt-35-turbo"
        gpt-3.5-turbo-1106:
          deploymentName: "gpt-35-turbo-1106"
        gpt-4:
          deploymentName: "gpt-4"
```

Also, I do not recommend selecting multiple plugins with similar functions, that may actually degrade performance. Tavily and Traversaal are the best for web search.

![image](https://github.com/danny-avila/LibreChat/assets/110412045/af3a0492-16e6-442e-b3e6-f68c19c7865f)
![image](https://github.com/danny-avila/LibreChat/assets/110412045/dc0c1c6a-c0b6-4948-b35c-a92b2c4782ae)

I removed my OpenAI api key for these tests to confirm azure was being used.

Also stepping into the code, I can see the configured values being used: 
![image](https://github.com/danny-avila/LibreChat/assets/110412045/58e9afb1-e30f-4545-a4b9-0cfffd43e821)
