### DISCUSSION TITLE
Set max_tokens on model-level

### DISCUSSION THREAD

**Discussion by hofq** [danny-avila/LibreChat#2375] [Help Wanted]
Hey there,
ive wanted to ask a quick question:

how can i set max_tokens for a specific model?

We use the Azure OpenAI Endpoint with gpt-35-turbo in Version 1106. The Model's Token Limit from OpenAI Docs is 16385, but Librechat is Returning an Error on anything higher than 4092.

How can i overwrite that?

**Comment by danny-avila** [comment]
This is planned and have been working on this

**Comment by danny-avila** [comment]
Also if you name your model according to its version, it won’t be an issue. You can decouple the deployment name from the model name for more control by using the librechat.yaml file as well for azure configuration

https://docs.librechat.ai/install/configuration/azure_openai.html

**Reply by hofq** [reply]
i'm currently doing this, but the deployment name is the same. Do you recommend changing  it?

```yaml
    endpoints:
      azureOpenAI:
        plugins: true
        assistants: true
        groups:
        - group: "azure-openai" # arbitrary name
          plugins: true
          assistants: true
          apiKey: "${AZURE_CFG_API_KEY}"
          instanceName: "prod-ai-schweden"  # name of the resource group or instance
          version: "2024-02-15-preview"
          models:
            gpt-3.5-turbo:
              deploymentName: gpt-35-turbo
            gpt-4-vision-preview:
              deploymentName: gpt-4-vision-preview
```
