### DISCUSSION TITLE
Improving the Developer Experience Workflow

### DISCUSSION THREAD

**Discussion by mawburn** [danny-avila/LibreChat#2379] [Feature Requests & Suggestions]
I believe that there is room to improve the developer experience for this repo. I'm not certain if there's a missing document or a detailed guide for everyone's flow, but, starting and running the repo in dev mode can be challenging. This certainly **IS NOT** a critique on the team or the project itself, but sometimes, these inconveniences happen with time, and it takes fresh eyes to identify things.

## Identifying the Issue

Being new to this, [my first PR](https://github.com/danny-avila/LibreChat/pull/2368) has been a learning curve and gave me some insight into potential improvements. Despite the PR being small and trivial, getting the groundwork established wasn't. It actually took me quite a while between to work and life to get some time to sit down and figure out how to get a local dev environment up.

I set up the dev environment on two different MacOS machines, and the following steps were more or less the same on both. I don't use any other type of machine though, but I understand some of the limitations of other platforms. I admit, I might've overlooked some documented details, but here are the steps I followed:

1. Ran `npm install`, followed by `npm install` in `api`, `data-provider`, and `client` folders. Post this, went back to root and again ran `npm install`. At some point I also ran `npm ci` to ensure everything was installed properly. There seems to be an insufficient documentation about this particular command, but it appears to perform more or less the same function as I did. Then I ran `backend:dev` and `frontend:dev` respectively. 
2. Created a personal `dev-compose.yml` to get the bare minimum features up and running.
3. The API did not seem to use the .env file from either the root or `api/.env`, forcing me to modify the command to match the Port correctly for `backend:dev`. 
4. The main branch isn't stable. Maybe I used the wrong branch, but ideally there should be a semi-stable branch that everyone operates from. I had to [resolve a Cohere issue](https://github.com/danny-avila/LibreChat/compare/main...mawburn:LibreChat:my-tweaks#diff-4baebf0fc5a5ada51f7d951ceb40365e7248bb35e4bde0ca4428e5dd7440d60bR6-R8) to run my instance. I think I've had similar issues in past attempts, which resulted in taking so long to get my first dev instance up and going.

## Suggested Remedies

1. Here are a few feasible solutions:
   a. Transition to [Turbo Repo](https://turbo.build/repo/docs). I have been utilizing monorepos for node/js/ts projects since workspaces were first added to yarn and Turbo Repo has proven to be a game changer in terms of how to work with them. It makes things easier all around.
    b. Switch to a more efficient workspace setup. The current arrangement seems like a chaotic blend of monorepo and other patterns, leading to disarray. A workspace revamp could be beneficial. [Here is an example of a project](https://github.com/mawburn/portaler-core) that I have with a more standard yarn 1.x workspace. It's old, but the structure is still the same. The documentation isn't very good, but the repo structure should be familiar. 
    c. Beef up the documentation if I'm missing something, but I still think there is some room for some of the above.
2. I'm not clear about the purpose of the main `docker-compose.yml` since `deploy-compose.yml` is what I use on 2 small scale production instances I have running, but it might be useful to establish this as the basic installation requirement for operating in dev mode. Alternatively, a `dev-compose.yml`, similar to the one I used, could work.
3. This might just be a bug with the initial steps that needs fixing. 
4. Make the `main` a tested branch vetted by multiple people on an occasional basis. PRs can merge to another branch which gets periodically reviewed on a local machine and then rebase into the main.
  a. Alternatively, setup a CI/CD pipeline that blocks merges to main until the full suite of tests are ran. Everything including linting, type checking, and tests including playwright. This is a lot more work both up front and in the long term though... but it cuts out the tedium. 

**My `dev-compose.yml` file**

```yml
services:
  mongodb:
    container_name: chat-mongodb
    ports:
      - "27017:27017"
    image: mongo
    restart: always
    volumes:
      - type: volume
        source: mongodb_data
        target: /data/db
    command: mongod --noauth
    security_opt:
      - label=disable
  meilisearch:
    container_name: chat-meilisearch
    image: getmeili/meilisearch:v1.7.3
    ports:
      - "7700:7700"
    env_file:
      - .env
    environment:
      - MEILI_HOST=http://meilisearch:7700
      - MEILI_NO_ANALYTICS=true
    volumes:
      - type: volume
        source: meilisearch_data
        target: /meili_data
    security_opt:
      - label=disable

volumes:
  mongodb_data:
  meilisearch_data:
```

Note: I intentionally did not include any of the other services that seem to be in development still.
