### DISCUSSION TITLE
Ollama Configuration Help

### DISCUSSION THREAD

**Discussion by shuther** [danny-avila/LibreChat#2474] [Troubleshooting]
### What happened?

While I only saw garbage replied by ollama/litellm, see issue #1960, I was able to identify that the problem was the selected endpoint: GPTPlugins vs Ollama/Litellm.
However, it is still not clear why this endpoint is retuning dummy data (no error).
Also, Litellm endpioint still returns dummy data, ollama is working fine.
MeiliSearch is returning an error, not sure if it is connected.
Nothing particular in the logs. ollama endpoint is working fine.

### Steps to Reproduce

1. see issue #1960

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
LibreChat             | 2024-04-20 16:00:27 info: Custom config file loaded:
...
LibreChat             | 2024-04-20 16:01:43 warn: [OpenAIClient.chatCompletion][finalChatCompletion] Aborted Message
LibreChat             | 2024-04-20 16:01:43 warn: [OpenAIClient.chatCompletion][finalChatCompletion] API error
LibreChat             | 2024-04-20 16:04:44 error: [MeiliMongooseModel.findOneAndUpdate] Convo not found in MeiliSearch and will index 44030f61-9286-4e0f-a9be-29e8200e953f Document `44030f61-9286-4e0f-a9be-29e8200e953f` not found.

---
endpoints:
  # assistants:
  #   disableBuilder: false # Disable Assistants Builder Interface by setting to `true`
  #   pollIntervalMs: 750  # Polling interval for checking assistant updates
  #   timeoutMs: 180000  # Timeout for assistant operations
  #   # Should only be one or the other, either `supportedIds` or `excludedIds`
  #   supportedIds: ["asst_supportedAssistantId1", "asst_supportedAssistantId2"]
  #   # excludedIds: ["asst_excludedAssistantId"]
  #   # (optional) Models that support retrieval, will default to latest known OpenAI models that support the feature
  #   retrievalModels: ["gpt-4-turbo-preview"]
  #   # (optional) Assistant Capabilities available to all users. Omit the ones you wish to exclude. Defaults to list below.
  #   capabilities: ["code_interpreter", "retrieval", "actions", "tools", "image_vision"]
  custom:

    - name: "Lite LLM"
    # Provide the key instead in each "model" block within "litellm/litellm-config.yaml"
      apiKey: "sk-litellm-librechat"
    # See the required changes above in "Start LiteLLM Proxy Server" step.
      baseURL: "http://linuxmain.local:4000"
    # A "default" model to start new users with. The "fetch" will pull the rest of the available models from LiteLLM
    # More or less this is "irrelevant", you can pick any model. Just pick one you have defined in LiteLLM.
      models:
        default: [
          "wizardlm2", "llama3"
        ]
        fetch: false # not supported
      titleConvo: true
      titleModel: "wizardlm2"
      summarize: false
      summaryModel: "wizardlm2"
      forcePrompt: false
      modelDisplayLabel: "Lite LLM"
#      addParams:
#        "stop": [
#          "<|start_header_id|>",
#          "<|end_header_id|>",
#          "<|eot_id|>",
#          "<|reserved_special_token"
#              ]

    - name: "Ollama"
      apiKey: "ollama"
      baseURL: "http://linuxmain.local:11434/v1"
      models:
        default: [
          "mistral",
          ]
        fetch: false # fetching list of models is not supported
      titleConvo: true
      titleModel: "mistral"
      summarize: false
      summaryModel: "mistral"
      forcePrompt: false
      modelDisplayLabel: "Ollama"
```

### Screenshots

<img width="973" alt="Screenshot 2024-04-20 at 18 09 57" src="https://github.com/danny-avila/LibreChat/assets/33225407/a84a2f2f-7ed0-495f-a3ac-28dfde725a17">
<img width="959" alt="Screenshot 2024-04-20 at 18 13 56" src="https://github.com/danny-avila/LibreChat/assets/33225407/4ccfbff1-6dca-463c-8705-20e71c45fe1a">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
I don't see any indication of the plugins endpoint being used.

Please see this discord thread for correct configuration: https://discord.com/channels/1086345563026489514/1230791900634677278/1230791900634677278

from the thread:

> I figured it out in case it helps anyone else. I needed to create a custom provider in librechat.yaml and add the stop words to the provider definition there, instead of in the litellm config.

```yaml
    - name: "LiteLLM"
      apiKey: "sk-1234"
      baseURL: "http://litellm:3000"
      models:
        default: ["llama3-8b"]
        fetch: true
      titleConvo: true
      titleModel: "llama3-8b"
      summarize: false
      summaryModel: "llama3-8b"
      forcePrompt: false
      modelDisplayLabel: "LiteLLM"
      addParams:
            "stop": [
              "<|start_header_id|>",
              "<|end_header_id|>",
              "<|eot_id|>",
              "<|reserved_special_token"
            ]
```
