### DISCUSSION TITLE
How to upload image?

### DISCUSSION THREAD

**Discussion by imsarah** [danny-avila/LibreChat#2579] [Help Wanted]
I have enabled openai 

```
 fileConfig:
   endpoints:
     assistants:
       fileLimit: 5
       fileSizeLimit: 10  # Maximum size for an individual file in MB
       totalSizeLimit: 50  # Maximum total size for all files in a single request in MB
       supportedMimeTypes:
         - "image/.*"
         - "application/pdf"
     openAI:
       disabled: false # Disables file uploading to the OpenAI endpoint
     default:
       totalSizeLimit: 50
```

however after docker-compose up --build -d, openai gives no response to my image
![image](https://github.com/danny-avila/LibreChat/assets/19930284/e48e9de2-b8db-4a64-b822-df01b57d0b1a)

I am able to use file upload but not in image format.
