### DISCUSSION TITLE
UI Not Showing Text Box for Chat

### DISCUSSION THREAD

**Discussion by ryancurrah** [danny-avila/LibreChat#2626] [Troubleshooting] [answered]
I have started LibreChat locally using Docker Compose with MongoDB. It starts up fine, the issue is when I get to the UI I see no text box and in the java script console I get the following log and error. I'm not seeing any relevant info in the logs as well. Any clue as to what I'm missing?

```
Error: GET http://127.0.0.1:3080/c/new 404 (Not Found)
Warning: No endpoint selected
```

<img width="2056" alt="Screenshot 2024-05-05 at 7 36 11 PM" src="https://github.com/danny-avila/LibreChat/assets/6209771/8eb02897-5064-4a48-8103-e86ec3b5cadc">

Here is my Docker-Compose:

```yaml
version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    volumes:
      - ~/mongo-data:/data/db
    ports:
      - "27017:27017"
    restart: always

  librechat:
    image: ghcr.io/danny-avila/librechat:v0.7.1
    container_name: librechat
    environment:
      MONGO_URI: mongodb://mongo:27017/LibreChat
      CREDS_KEY: fb838dd31c0c0fe8ba79e9a01330b13c0fcfba4066e820fd87a1534ea084c2f3
      CREDS_IV: 18663af1799397ae57de52cf348614de
      JWT_SECRET: 634f8e3f78d485278ee13cb37f909e0c25214d2760f9e7c957ee099b8e48a3d9
      JWT_REFRESH_SECRET: ff24a17e8999b8beb917ec26321fb2d573e9ca6b32b8a499cea4ff7a2961a28a
      ALLOW_REGISTRATION: true
    volumes:
      - ./config.yaml:/app/librechat.yaml
    ports:
      - "3080:3080"
    restart: unless-stopped
    depends_on:
      - mongo
```

Here is my config:

```yaml
version: 1.0.6
endpoints:
  custom:
    - name: vllm
      baseURL: http://[REDACTED]/v1
      models:
        default: ["meta-llama/Meta-Llama-3-70B"]
        fetch: true
      titleConvo: true
      titleModel: "meta-llama/Meta-Llama-3-70B"
      summarize: false
      summaryModel: "meta-llama/Meta-Llama-3-70B"
      forcePrompt: false
      addParams:
            "stop": [
              "<|start_header_id|>",
              "<|end_header_id|>",
              "<|eot_id|>",
              "<|reserved_special_token"
            ]
```

Logs:

```
❯ docker logs librechat -f

> LibreChat@0.7.1 backend
> cross-env NODE_ENV=production node api/server/index.js

2024-05-05 23:47:27 info: [Optional] Redis not initialized. Note: Redis support is experimental.
2024-05-05 23:47:29 info: Connected to MongoDB
2024-05-05 23:47:29 info: Custom config file loaded:
2024-05-05 23:47:29 info: {
  "version": "1.0.6",
  "endpoints": {
    "custom": [
      {
        "name": "vllm",
        "baseURL": "http://[REDACTED]/v1",
        "models": {
          "default": [
            "meta-llama/Meta-Llama-3-70B"
          ],
          "fetch": true
        },
        "titleConvo": true,
        "titleModel": "meta-llama/Meta-Llama-3-70B",
        "summarize": false,
        "summaryModel": "meta-llama/Meta-Llama-3-70B",
        "forcePrompt": false,
        "addParams": {
          "stop": [
            "<|start_header_id|>",
            "<|end_header_id|>",
            "<|eot_id|>",
            "<|reserved_special_token"
          ]
        }
      }
    ]
  }
}
2024-05-05 23:47:29 warn: RAG API is either not running or not reachable at undefined, you may experience errors with file uploads.
Social logins are disabled. Set Environment Variable "ALLOW_SOCIAL_LOGIN" to true to enable them.
2024-05-05 23:47:29 info: Custom config file loaded:
2024-05-05 23:47:29 info: {
  "version": "1.0.6",
  "endpoints": {
    "custom": [
      {
        "name": "vllm",
        "baseURL": "http://[REDACTED]/v1",
        "models": {
          "default": [
            "meta-llama/Meta-Llama-3-70B"
          ],
          "fetch": true
        },
        "titleConvo": true,
        "titleModel": "meta-llama/Meta-Llama-3-70B",
        "summarize": false,
        "summaryModel": "meta-llama/Meta-Llama-3-70B",
        "forcePrompt": false,
        "addParams": {
          "stop": [
            "<|start_header_id|>",
            "<|end_header_id|>",
            "<|eot_id|>",
            "<|reserved_special_token"
          ]
        }
      }
    ]
  }
}
2024-05-05 23:47:29 info: Server listening on all interfaces at port 3080. Use http://localhost:3080 to access it
{"level":"info","message":"[Login] [Login successful] [Username: ryan.currah@acme.com] [Request-IP: 192.168.65.1]","timestamp":"2024-05-05T23:48:22.437Z"}
2024-05-05 23:48:22 info: Custom config file loaded:
2024-05-05 23:48:22 info: {
  "version": "1.0.6",
  "endpoints": {
    "custom": [
      {
        "name": "vllm",
        "baseURL": "http://[REDACTED]/v1",
        "models": {
          "default": [
            "meta-llama/Meta-Llama-3-70B"
          ],
          "fetch": true
        },
        "titleConvo": true,
        "titleModel": "meta-llama/Meta-Llama-3-70B",
        "summarize": false,
        "summaryModel": "meta-llama/Meta-Llama-3-70B",
        "forcePrompt": false,
        "addParams": {
          "stop": [
            "<|start_header_id|>",
            "<|end_header_id|>",
            "<|eot_id|>",
            "<|reserved_special_token"
          ]
        }
      }
    ]
  }
}
2024-05-05 23:48:22 info: Custom config file loaded:
2024-05-05 23:48:22 info: {
  "version": "1.0.6",
  "endpoints": {
    "custom": [
      {
        "name": "vllm",
        "baseURL": "http://[REDACTED]/v1",
        "models": {
          "default": [
            "meta-llama/Meta-Llama-3-70B"
          ],
          "fetch": true
        },
        "titleConvo": true,
        "titleModel": "meta-llama/Meta-Llama-3-70B",
        "summarize": false,
        "summaryModel": "meta-llama/Meta-Llama-3-70B",
        "forcePrompt": false,
        "addParams": {
          "stop": [
            "<|start_header_id|>",
            "<|end_header_id|>",
            "<|eot_id|>",
            "<|reserved_special_token"
          ]
        }
      }
    ]
  }
}
```
