### DISCUSSION TITLE
[Bug]:

### DISCUSSION THREAD

**Discussion by nolandubeau** [danny-avila/LibreChat#2650] [Troubleshooting]
### What happened?

I am using a custom config.yaml file instead of the default librechat.yaml.  I have set my CONFIG_PATH to:

CONFIG_PATH="config.yaml"

The file is located in the root of the project, however when I restart the app I get the following error:

error: Config file YAML format is invalid: ENOENT: no such file or directory, open 'config.yaml'

The same applies if I use the default librechat.yaml file/location and I comment out CONFIG_PATH.

### Steps to Reproduce

1. Set CONFIG_PATH="config.yaml" and uncomment
2. Rename librechat.yaml to config.yaml
3. Restart app
4. Error occurs

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Thanks for checking out the project!

That would work, but if you are using docker, the container won't know about the file even if it was `librechat.yaml` in the same directory.

You need to follow this step:

https://docs.librechat.ai/install/configuration/custom_config.html#docker-setup

there's no reason to rename the file unless you really need to, in which case, you would need to adapt this:

```yaml
# For more details on the override file, see the Docker Override Guide:
# https://docs.librechat.ai/install/configuration/docker_override.html

version: '3.4'

services:
  api:
    volumes:
# local/filepath:container/filepath
      - ./librechat.yaml:/app/librechat.yaml 
```

`CONFIG_PATH` mainly gives you the flexibility to host the file somewhere remotely (for example, you can put it in a public repo you own), or put it in a different directory or rename as you did.

The remote option is an alternative to using the docker override file for this reason.
