### DISCUSSION TITLE
Can I alias custom endpoints?

### DISCUSSION THREAD

**Discussion by a13782425** [danny-avila/LibreChat#2728] [Q&A]
example: real enpoint name is "mistral-large", alias name is "mistral" or other。

**Comment by danny-avila** [comment]
I’m not sure what the question is.

In general, You can name custom endpoints whatever you want

**Reply by a13782425** [reply]
Sorry, that's not quite the right description
```
  - name: "OpenRouter"
      # For `apiKey` and `baseURL`, you can use environment variables that you define.
      # recommended environment variables:
      apiKey: "${OPENROUTER_KEY}" # NOT OPENROUTER_API_KEY
      baseURL: "https://openrouter.ai/api/v1"
      models:
        default: ["meta-llama/llama-3-70b-instruct"]
        fetch: true
      titleConvo: true
      titleModel: "meta-llama/llama-3-70b-instruct"
      # Recommended: Drop the stop parameter from the request as Openrouter models use a variety of stop tokens.
      dropParams: ["stop"]
      modelDisplayLabel: "OpenRouter"
```
Example configuration above, can I alias "meta-llama/llama 3-70b-instruct" in "models"?

**Reply by danny-avila** [reply]
You mean the models then? You can sort of "alias" presets with `modelSpecs`: 
https://www.librechat.ai/docs/configuration/librechat_yaml/object_structure/model_specs#overview

![Screenshot 2024-05-15 235428](https://github.com/danny-avila/LibreChat/assets/110412045/ee45e1b2-00ca-4a1e-99bb-518dea1fd307)
![image](https://github.com/danny-avila/LibreChat/assets/110412045/df24a875-0093-4cd7-87ca-8374dca6a76c)


### Config for this

```yaml
modelSpecs:
  enforce: false
  prioritize: false
  list:
    - name: "Llama3"
      showIconInHeader: false
      label: "Llama3"
      description: "Meta's Latest Open Source model"
      preset:
        modelLabel: "LLama3"
        endpoint: "OpenRouter"
        model: "meta-llama/llama-3-70b-instruct"
```

### More info:

https://www.librechat.ai/docs/configuration/librechat_yaml/object_structure/model_specs

---

By default, configuring modelSpecs will remove some UI elements. You can re-enable them with the `interface` config:
https://www.librechat.ai/docs/configuration/librechat_yaml/object_structure/interface

```yaml
interface:
    endpointsMenu: true
    modelSelect: true
    parameters: true
    presets: true
    sidePanel: true
```
