### DISCUSSION TITLE
Enhancement: add support for DeepSeek platform

### DISCUSSION THREAD

**Discussion by ErykCh** [danny-avila/LibreChat#2770] [Feature Requests & Suggestions]
### What features would you like to see added?

platform.deepseek.com
https://github.com/deepseek-ai/DeepSeek-V2

### More details

Low cost: input 0,14$  output 0,28$ for milions tokens
yet powerfull model

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mu-ct** [comment]
You can use it through OpenRouter

**Reply by quacrobat** [reply]
how exactly?

**Reply by danny-avila** [reply]
Or use it as a custom endpoint:
```yaml
version: 1.2.1
cache: true
endpoints:
  custom:
    - name: "Deepseek"
      apiKey: "${DEEPSEEK_API_KEY}"
      baseURL: "https://api.deepseek.com/v1"
      models:
        default: ["deepseek-chat", "deepseek-coder"]
        fetch: false
      titleConvo: true
      # titleMethod: "completion"
      titleModel: "current_model"
      summarize: false
      summaryModel: "current_model"
      forcePrompt: false
      modelDisplayLabel: "Deepseek"

```
![firefox_z8aijiTBgx](https://github.com/user-attachments/assets/03a7c2bc-a150-40db-ab5a-017dee5e1629)

More info: 

https://www.librechat.ai/docs/quick_start/custom_endpoints
