### DISCUSSION TITLE
Is it possible to see a list of users and chat histories in mongo?

### DISCUSSION THREAD

**Discussion by tttll1091** [danny-avila/LibreChat#278] [Q&A] [answered]
Is it possible to see a list of users and chat histories in mongo?
As an administrator, I would like to know who had what kind of conversation.

**Comment by danny-avila** [comment]
No, unless you look directly at the database. Look into mongo express

**Reply by ingoau** [reply]
https://www.librechat.ai/blog/2023-11-30_mongoexpress

**Reply by HASH717** [reply]
> https://www.librechat.ai/blog/2023-11-30_mongoexpress

Thank you

**Comment by SharpLu** [comment]
Hi @danny-avila  now is possible to see how many users are using the librechat now by logs or mangodb? because we are using the 0.75, i saw the last answer from 2023-05-17. Thank you

**Comment by Joshfindit** [comment, marked as answer]
Adding to this discussion as it came up quickly in my research.
_Apologies if it's rude to post to old threads in this repo._

Instead of running (and exposing) express, you can get the users by using `mongosh`
I run docker-compose so I added this:
```
  mongosh:
    image: alpine/mongosh
    command: "/bin/true" # Stops it from running during `up`
    depends_on:
      mongodb:
        condition: service_started
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
    volumes:
      - ./mongosh/scripts:/scripts
```

and then added the `list_users.sh script to `./mongosh/scripts/`
```bash
#!/bin/bash

MONGO_CONNECTION_STRING="mongodb://mongodb:27017/LibreChat"

# --- MongoDB Command ---
# This is a JavaScript command executed within mongosh.
MONGO_COMMAND="
  db.users.find().pretty();
"

mongosh --quiet "$MONGO_CONNECTION_STRING" --eval "$MONGO_COMMAND"

# --- Check for errors ---
if [ $? -eq 0 ]; then
  echo "MongoDB command executed successfully."
else
  echo "Error executing MongoDB command."
  exit 1
fi
```

It can then be run with `docker-compose run --rm mongosh /scripts/list_users.sh`
To go further AI can help you do limits, sorting, and other output formats such as TSV with just `name    username        email   createdAt`
