### DISCUSSION TITLE
chat persistence breaks and chat deletion not working offline

### DISCUSSION THREAD

**Discussion by weipienlee** [danny-avila/LibreChat#2787] [Troubleshooting]
### What happened?

using the app offline i.e. disconnected from network/internet. Although, chatting with a ollama model works, switching between chats and/or creating a new one shows no/wrong content. deleting a chat is not possible.

It all seems to recover in a while when network/internet connection is available again.

potential cause: chat title uses another llm, likely a cloud service version/openai, since it is not generated when off-line. Not sure why this would be related to deleting

### Steps to Reproduce

1. Assure you have a local llm inference service
2. disconnect network/internet
3. create a chat/thread (simple, just a model without tools) => get answer, chat title remain "New Chat"
4. create a new chat => content in chat pane remains, but you can just chat
5. switch back to previous chat => no chat content visible
6. delete chat => chat 

main commit: f0e8cca5df818af3fa79534be4f2218431352f97
docker install on macos

### What browsers are you seeing the problem on?

Firefox

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
You can chat completely offline, I do it often.

Use this config for ollama

```yaml
    - name: "Ollama"
      apiKey: "ollama"
      baseURL: "http://localhost:11434/v1/" # adjust as needed
# baseURL: "http://host.docker.internal:11434/v1/" # <-- usual value needed for docker
      models:
        default: [
          "llama3:latest",
          "command-r",
          "mixtral",
          "phi3",
          ]
        fetch: true
      dropParams: ["presence_penalty"]
      titleConvo: true
      titleModel: "current_model"
```
