### DISCUSSION TITLE
Stable Diffusion does not seem to be working when used with ModelSpecs

### DISCUSSION THREAD

**Discussion by Kryszn0** [danny-avila/LibreChat#2793] [Troubleshooting]
### What happened?

Trying to get Stable Diffusion plugin to become available in my self hosted environment. Before I was getting Stable Diffusion plugin to work by using LiteLLM as a proxy for OpenAI to connect over to LocalAI (which does actually work). But I think the newly implemented modelSpecs would be a cleaner way to achieve what I'm trying to setup and it seems like it should be able to work without requiring LiteLLM at all, or at least that's what I understand from reading the new documentation. I understand it as the modelSpec should allow LibreChat to simply directly connect to a StableDiffusion instance

The following is what I am doing:

### Steps to Reproduce

1. Created working modelSpec following [modelSpec guide](https://www.librechat.ai/docs/configuration/librechat_yaml/object_structure/model_specs)
2. Install stable-diffusion-webui per [LibreChat guide](https://www.librechat.ai/docs/configuration/tools/stable_diffusion)
3. Set variable `SD_WEBUI_URL=https://stablediffusion.example.com' (SD is reverse proxied in homelab)
4. To the working modelSpec, follow [modelSpec guide](https://www.librechat.ai/docs/configuration/librechat_yaml/object_structure/model_specs)
and add the following [pluginKey](https://github.com/danny-avila/LibreChat/blob/main/api/app/clients/tools/manifest.json) to the preset tool:
`tools: ["stable-diffusion"]`   

Expectation:
Plugins will become available via endpointsMenu & will be able to install/use Stable Diffusion

Reality:
Model works as if there is no stable-diffusion tool added, plugins are still not made available. 

The following is my modelSpec

```
modelSpecs:
  list:
    - name: "myai"
      label: "MyAI"
      default: true
      description: "My AI"
      iconURL: "https://upload.wikimedia.org/wikipedia/commons/examplelogo.png"
      preset:
        chatGptLabel: "MyAI"
        endpoint: "MyAI"
        greeting: "Hello there!"
        frequency_penalty: 0
        model: "gpt-4"
        presence_penalty: 0
        promptPrefix: >
          You are a helpful AI, answer any question asked.
        resendFiles: false
        temperature: 0.8
        top_p: 0.5
        tools: ["stable-diffusion"]
```

- [X] I agree to follow this project's Code of Conduct
