### DISCUSSION TITLE
Assistants with/on Azure OpenAI

### DISCUSSION THREAD

**Discussion by ervet** [danny-avila/LibreChat#2817] [General]
Hello;

does somebody have a working Azure Assistants config. Im struggling. I have one assistant configured within Azure but always get.

debug-2024-05-21.log:2024-05-21T12:20:19.289Z error: [/assistants] Error listing assistants 401 Incorrect API key provided: . You can find your API key at https://platform... [truncated]

But the key is 100% correct. Does somebody have working example. And how to remove [the truncated] ?? 

Greetings
Erik

**Comment by Sander-OS** [comment]
same here. I cant get it to work.

**Reply by tommartens1997** [reply]
I have a slightly different error, but I do not find the required documentation on how to set up the Azure OpenAI Assistants.
An example of a working yaml file would be great.
Here is what I have for reference.

2024-06-06T09:39:46.529Z error: [/assistants] Error listing assistants 404 Resource not found

 ----- librechat.yaml ----- 
version: 1.1.4
cache: true
endpoints:
  azureOpenAI:
      titleModel: "Azure OpenAI"
      assistants: true
      groups:
        - group: "MyGroup"
          apiKey: "the-very-sercure-api-key"
          instanceName: "the-instance-name" # name of the resource group or instance
          assistants: true
          models:
            gpt-4o:
              deploymentName: GPT4oUS
              version: "2024-02-01" # Keep in mind the version is the API version, not the model version

  azureAssistants:
     disableBuilder: false # Disable Assistants Builder Interface by setting to `true`
     pollIntervalMs: 3000  # Polling interval for checking assistant updates
     timeoutMs: 180000  # Timeout for assistant operations
     supportedIds: ["asst_****"]
     capabilities: ["code_interpreter"]  # , "retrieval", "actions", "tools", "image_vision"
     
 ----- .env -----
 ...
 #=======================#
#                     Endpoints                     #
#=========########=======#
ENDPOINTS=azureOpenAI,azureAssistants
...

**Comment by danny-avila** [comment]
From discord:

> For those looking to set up Azure OpenAI Assistants: I had to use the gpt-4 model with the api-version "2024-05-01-preview". Azure assistants with gpt-4o do not seem to work yet

**Reply by ervet** [reply]
Hello,

I have updated to the newest Version 0.7.3 and now I have a working assistants. 

n the .env I have configured the following endpoints

`ENDPOINTS=azureOpenAI,gptPlugins,assistants,azureAssistants`

my librechat.yaml looks like

endpoints:
  azureAssistants:
    disableBuilder: false
    pollIntervalMs: 750
    timeoutMs: 180000
    capabilities: ["code_interpreter", "actions", "tools", "image_vision"]
  azureOpenAI:
    titleModel: "gpt3.5-turbo"
    assistants: true
    titleConvo: true
    plugins: true
    groups:
    - group: "MYGROUP"
      apiKey: "MYAPI"
      instanceName: "MYINSTANCE"
      version: "2024-03-01-preview"
      assistants: true
      models:
        gpt3.5-turbo:
          deploymentName: "gpt-35-turbo"
        gpt3.5-turbo-16k:
          deploymentName: "gpt-35-turbo-16k"
        gpt4:
          deploymentName: "gpt-4"
          version: "2024-05-01-preview"
        gpt4o:
          deploymentName: "gpt-4o"



I have created the assistants directly in Azure a select the model their (it must match of course the models you have available in librechat. For some reason change the model in the Builder does not work for me. 

At the moment I'm only using gpt3.5-turbo for assistances


But if you modify the assistant only in Azure AI Studio it works perfectly.

**Comment by hvdv99** [comment]
Hi! But why does the Azure documentation mention that Azure Assistants works with gpt-4o but not with LibreChat? 
Anyone who had gpt-4o working on with assistants and librechat?

**Comment by dannykorpan** [comment]
Hi, this configuration is working with my setup and gpt-4o.

```
endpoints:
  azureOpenAI:
    titleModel: "gpt-4o-mini"
    assistants: true
    plugins: false
    summarize: true
    summaryModel: "gpt-4o-mini"
    titleConvo: true
    groups:
      - group: "swedencentral" # arbitrary name
        assistants: true
        apiKey: "XXX"
        instanceName: "librechat" # name of the resource group or instance
        version: "2024-05-01-preview"
        models:
          gpt-4o:
            deploymentName: "gpt-4o"
          gpt-4o-mini:
            deploymentName: "gpt-4o-mini"
  azureAssistants:
    capabilities: ["code_interpreter", "actions", "tools", "image_vision"]
    disableBuilder: false # Disable Assistants Builder Interface by setting to true
    pollIntervalMs: 3000 # Polling interval for checking assistant updates
    timeoutMs: 180000 # Timeout for assistant operations
```
