### DISCUSSION TITLE
TTS code 500

### DISCUSSION THREAD

**Discussion by wupengfei0904** [danny-avila/LibreChat#2850] [Troubleshooting] [answered]
![image](https://github.com/danny-avila/LibreChat/assets/125854485/8e03a4cd-6502-4e38-a7de-620c640f1a34)
This is my librechat.yaml configuration for the OpenAI TTS (Text-to-Speech) service. I have also set theTTS_API_KEY in the environment variables, but I get an error when using the voice function. Here are the logs:
"An error occurred while creating the audio stream: No TTS schema is set. Did you configure TTS in the custom config (librechat.yaml)?\n# Example TTS configuration","stack":"Error: No TTS schema is set. Did you configure TTS in the custom config (librechat.yaml)?

**Comment by danny-avila** [comment, marked as answer]
You have this:

```yaml
registration:
  tts:
    # your config
  stt:
    # your config
```


it should be

```yaml
registration:
  # your registration config
tts:
  # your config
stt:
  # your config
```
