### DISCUSSION TITLE
Librechat deployed on kubernetes its outputs is not full.

### DISCUSSION THREAD

**Discussion by Chethanibms** [danny-avila/LibreChat#2875] [Troubleshooting]
Librechat deployed on kubernetes its outputs in not full, every time we need press the continue button.
attaching screenshot for your reference.
<img width="1430" alt="Screenshot 2024-05-27 at 12 58 51 PM" src="https://github.com/danny-avila/LibreChat/assets/54358087/c56c6032-e165-4adb-8e22-042dc5aaa326">

**Comment by danny-avila** [comment]
This is not the norm.

Usually this happens when “max_tokens” is a lower value, but no idea why this would be the case for you. It could be the fact that you’re using “gpt-4-vision-preview.” Or some predefined value to the Azure deployment.

try using another model or increasing the value for “Max Output Tokens” in the conversation settings here: 
<img width="414" alt="image" src="https://github.com/danny-avila/LibreChat/assets/110412045/fd7b757f-4712-49d5-9e23-239a3b19c170">

**Comment by danny-avila** [comment]
This seems to be a recent change with Azure OpenAI: https://github.com/danny-avila/LibreChat/issues/2884

Troubleshooting this.

**Comment by Chethanibms** [comment]
This is my configmap looks like, Please suggest if this is correct
```
apiVersion: v1
data:
  librechat.yaml: |
    version: 1.1.0
    cache: true
    endpoints:
      azureOpenAI:
        titleModel: "gpt-4-vision-preview"
        titleConvo: true
        plugins: true
        groups:
        - group: "azure-openai"
          apiKey: *****
          instanceName: "proview-vision"
          deploymentName: proview-vision
          version: "2024-02-15-preview"
          models:
            gpt-4-vision-preview:
              maxContextTokens: 128000
              max_tokens: 4096
              temperature: 0.2
              deploymentName: proview-vision
```
