### DISCUSSION TITLE
After updating the Docker image, the conversation will cause the program to crash.

### DISCUSSION THREAD

**Discussion by Passerby1011** [danny-avila/LibreChat#2876] [Troubleshooting]
### What happened?

我开始使用的版本是0.7.2，是librechat最早的0.7.2的docker镜像，没有过更新，今天我对librechat的docker镜像进行了更新，更新后显示版本依旧是0.7.2，但是在最新版本，我一旦开始对话整个网页就会崩溃（刷新网页依旧可以正常进入librechat），设置里的消息选项也不能点击，同样会报崩溃
I started using version 0.7.2, which was the earliest 0.7.2 Docker image of librechat, and I have never updated it. Today, I updated the Docker image of librechat, and after the update, it still shows version 0.7.2, but in the latest version, the entire web page crashes as soon as I start a conversation (refreshing the web page still allows me to enter librechat normally), and the message option in the settings also cannot be clicked, which also reports a crash.
```
Unexpected Application Error!
Unexpected token 'i', "includeBranches" is not valid JSON
SyntaxError: Unexpected token 'i', "includeBranches" is not valid JSON
    at JSON.parse (<anonymous>)
    at Ne.xe.effects_UNSTABLE (https://xxxxxx.xxxxxx.xxxxx/assets/index-DwzNzXY-.js:2:21758)
    at Object.v [as init] (https://xxxxxx.xxxxxx.xxxxx/assets/vendor-DxTdAtaa.js:47:63931)
    at jM (https://xxxxxx.xxxxxx.xxxxx/assets/vendor-DxTdAtaa.js:47:14820)
    at sX (https://xxxxxx.xxxxxx.xxxxx/assets/vendor-DxTdAtaa.js:47:15091)
    at _X (https://xxxxxx.xxxxxx.xxxxx/assets/vendor-DxTdAtaa.js:47:17212)
    at https://xxxxxx.xxxxxx.xxxxx/assets/vendor-DxTdAtaa.js:47:37850
    at https://xxxxxx.xxxxxx.xxxxx/assets/vendor-DxTdAtaa.js:47:37921
    at Object.useSyncExternalStore (https://xxxxxx.xxxxxx.xxxxx/assets/vendor-DxTdAtaa.js:38:26585)
    at jt.useSyncExternalStore (https://xxxxxx.xxxxxx.xxxxx/assets/vendor-DxTdAtaa.js:9:6453)
```

### Steps to Reproduce

Update using `docker compose pull`

### Relevant log output

```shell
LibreChat-API     | 2024-05-27 06:34:41 info: Server listening on all interfaces at port 3080. Use http://localhost:3080 to access it
chat-meilisearch  | 2024-05-27T06:44:16.789315Z  INFO HTTP request{method=GET host="chat-meilisearch:7700" route=/health query_parameters= user_agent=node status_code=200}: meilisearch: close time.busy=198µs time.idle=1.08ms
chat-mongodb      | {"t":{"$date":"2024-05-27T06:44:34.243+00:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"WTCheckpointThread","msg":"WiredTiger message","attr":{"message":"[1716792274:243367][1:0x7fe166e52700], WT_SESSION.checkpoint: [WT_VERB_CHECKPOINT_PROGRESS] saving checkpoint snapshot min: 45, snapshot max: 45 snapshot count: 0, oldest timestamp: (0, 0) , meta checkpoint timestamp: (0, 0) base write gen: 331"}}
chat-meilisearch  | 2024-05-27T06:44:42.412644Z  INFO HTTP request{method=GET host="chat-meilisearch:7700" route=/health query_parameters= user_agent=node status_code=200}: meilisearch: close time.busy=184µs time.idle=886µs
```

### Screenshots

![image](https://github.com/danny-avila/LibreChat/assets/63802758/ba645947-3db6-4ef2-bf41-586e44520f46)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
You likely have a merge conflict, how did you update exactly? how do you run the app?

**Reply by danny-avila** [reply]
And have you edited any of the codebase yourself?

**Reply by Passerby1011** [reply]
> You likely have a merge conflict, how did you update exactly? how do you run the app?



> And have you edited any of the codebase yourself?

I haven't edited the code myself, I just updated the image with a docker compose pull

**Reply by danny-avila** [reply]
Try these exact steps: https://www.librechat.ai/docs/local/docker#update-librechat

**Comment by Passerby1011** [comment]
```
version: "3.4"

# Do not edit this file directly. Use a ‘docker-compose.override.yaml’ file if you can.
# Refer to `docker-compose.override.yaml.example’ for some sample configurations.

services:
  api:
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - mongodb
      - rag_api
    #image: librechat
    image: ghcr.io/danny-avila/librechat-dev:latest
    container_name: LibreChat-API
    restart: unless-stopped
    user: "${UID}:${GID}"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - HOST=0.0.0.0
      - MONGO_URI=mongodb://chat-mongodb:27017/LibreChat
      - MEILI_HOST=http://chat-meilisearch:7700
      - RAG_API_URL=http://rag_api:8000
    volumes:
      - type: bind
        source: ./.env
        target: /app/.env
      - ./images:/app/client/public/images
      - ./logs:/app/api/logs
      - ./librechat.yaml:/app/librechat.yaml
      #- ./api/app/clients/tools/.well-known:/app/api/app/clients/tools/.well-known
  mongodb:
    container_name: chat-mongodb
    image: mongo:4.4.18
    restart: unless-stopped
    user: "${UID}:${GID}"
    ports:
      - 27017:27017
    volumes:
      - ./data-node:/data/db
    command: mongod --noauth
  meilisearch:
    container_name: chat-meilisearch
    image: getmeili/meilisearch:v1.7.3
    restart: unless-stopped
    user: "${UID}:${GID}"
    environment:
      - MEILI_HOST=http://meilisearch:7700
      - MEILI_NO_ANALYTICS=true
    volumes:
      - ./meili_data_v1.7:/meili_data

  vectordb:
    image: ankane/pgvector:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - ./pgdata:/var/lib/postgresql/data
#    ports:
#      - "5433:5432" 

  rag_api:
    image: ghcr.io/danny-avila/librechat-rag-api-dev-lite:latest
    container_name: rag_api
    restart: unless-stopped
    environment:
      - DB_HOST=vectordb
#      - DB_PORT=5432
#      - POSTGRES_DB=mydatabase
#      - POSTGRES_USER=myuser
#      - POSTGRES_PASSWORD=mypassword
#    ports:
#      - "3090:8000"
    depends_on:
      - vectordb
    env_file:
      - .env  
```
