### DISCUSSION TITLE
How to view MongoDB data in Docker in production environment?

### DISCUSSION THREAD

**Discussion by Kevin-free** [danny-avila/LibreChat#2945] [Q&A]
I see `deploy-compose.yml`

```yaml
mongodb:
container_name: chat-mongodb
# ports: # Uncomment this to access mongodb from outside docker, not safe in deployment
# - 27018:27017
image: mongo
restart: always
volumes:
- ./data-node:/data/db
command: mongod --noauth
```

Hint: You can expose the port, but it is not safe.

I tried to execute `docker exec -it chat-mongodb bash` to enter the MongoDB container and execute `mongo` to view it, but it prompted `bash: mongo: command not found`.

In a production environment, how do you generally view MongoDB data running in Docker?

**Comment by danny-avila** [comment]
We have a guide on this: https://www.librechat.ai/blog/2023-11-30_mongoexpress

If you want to take it a step further, you can also secure your local MongoDB, though it is a bit involved, and there are some special notes about connecting Mongo Express: https://www.librechat.ai/docs/configuration/mongodb/mongodb_auth#tldr

**Reply by Kevin-free** [reply]
Thank you! I see that I need to modify `docker-compose.override.yml`, but not `deploy-compose.yml`? What is the difference? Which one should I use for production environment?

**Reply by danny-avila** [reply]
Whichever is convenient for your setup. We recommend using the override file to avoid git conflicts when using the default setup, for users who are utilizing the `docker-compose.yml` as defined by the project.

If you have already edited `docker-compose.yml` and know how to reconcile git conflicts when pulling upstream changes, then feel free to do so.

Using `docker-compose.override.yml` is perfectly suitable for production. It's just one way to avoid editing your "main" compose file.

**Reply by Kevin-free** [reply]
Thank you very much for your answer! Sorry I am not familiar with this aspect and still have questions. I saw in [doc](https://www.librechat.ai/docs/remote/docker_linux#part-iii-updating-librechat) that when updating services, Docker commands all have `deploy-compose.yml`, so my current operation is:

1. Use npm for local development. After development and testing, execute the `git` command to push the code, and execute `docker buildx build --platform linux/amd64 -t MY_IMAGE_NAME --push .` to build and push the image (I have not yet learned to use automatic build).
2. On the production server, modify the `image` in `deploy-compose.yml` to `MY_IMAGE_NAME`, and execute `npm run update:deployed` to update the service.

Is this correct?

<img width="1440" alt="image" src="https://github.com/danny-avila/LibreChat/assets/26422757/5e788357-fa43-485d-a741-1e7ec7641efa">

**Reply by Kevin-free** [reply]
> We have a guide on this: https://www.librechat.ai/blog/2023-11-30_mongoexpress
> 
> If you want to take it a step further, you can also secure your local MongoDB, though it is a bit involved, and there are some special notes about connecting Mongo Express: https://www.librechat.ai/docs/configuration/mongodb/mongodb_auth#tldr

@danny-avila  Hello, I followed the [guide](https://www.librechat.ai/blog/2023-11-30_mongoexpress), but there is a problem: the browser fails to access `http://SERVER_IP:8081` "HTTP ERROR 502". I hope to get your help, thank you!

My operation is:

I added `mongo-express` in `deploy-compose.yml`:

```Yaml
services:
  mongodb:
    container_name: chat-mongodb
    # ports:  # Uncomment this to access mongodb from outside docker, not safe in deployment
    #   - 27018:27017
    image: mongo
    restart: always
    volumes:
      - ./data-node:/data/db
    command: mongod --noauth
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
    ports:
      - '8081:8081'
    depends_on:
      - mongodb
    restart: always
```

Execute `docker-compose -f ./deploy-compose.yml up -d` to start Docker, prompt:

```Shell
✔ Container chat-mongodb Started 0.1s
✔ Container mongo-express Started
```

The server IP is `SERVER_IP`, but accessing `http://SERVER_IP:8081` fails with "HTTP ERROR 502". I tried to check:

- The firewall is closed
- Both chat-mongodb and mongo-express containers are running.
- Enter the mongo-express container and ping chat-mongodb successfully
- Executing the `mongo` command in the container always prompts `mongo: command not found`
- `docker logs mongo-express` output:

```Shell
kevin@chat-sg:~/chat$ docker logs mongo-express
Waiting for mongo:27017...
/docker-entrypoint.sh: line 15: mongo: Try again
/docker-entrypoint.sh: line 15: /dev/tcp/mongo/27017: Invalid argument
Sun Jun 2 02:56:07 UTC 2024 retrying to connect to mongo:27017 (2/10)
/docker-entrypoint.sh: line 15: mongo: Try again
/docker-entrypoint.sh: line 15: /dev/tcp/mongo/27017: Invalid argument
No custom config.js found, loading config.default.js
Welcome to mongo-express 1.0.2
------------------------

Mongo Express server listening at http://0.0.0.0:8081
Server is open to allow connections from anyone (0.0.0.0)
```

**Reply by ckoehncke** [reply]
+1 Getting same results

**Reply by Odrec** [reply]
I had a similar issue and I think I found an error in the guide. If you look into the env variables on the mongo-express server with the command

```
docker exec -it mongo-express /bin/sh
/app # printenv
```

You will see this variable which was not set in the override file:

`ME_CONFIG_MONGODB_URL=mongodb://mongo:27017`

This seems to be a default variable from mongo-express that is overriding the variable

`ME_CONFIG_MONGODB_SERVER=mongodb` 

That's why it's looking in the mongo entrypoint and not in the mongodb one like it should

So you need to put this in your override file:

```
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
```

Instead of setting the `ME_CONFIG_MONGODB_SERVER` variable, set the ME_CONFIG_MONGODB_URL one to the correct entrypoint.

After changing that, the server worked for me

```
$ sudo docker logs mongo-express
Waiting for mongodb:27017...
No custom config.js found, loading config.default.js
Welcome to mongo-express 1.0.2
------------------------


Mongo Express server listening at http://0.0.0.0:8081
Server is open to allow connections from anyone (0.0.0.0)
GET / 200 86.027 ms - 10011

```
