### DISCUSSION TITLE
Question about the presets / plug-ins

### DISCUSSION THREAD

**Discussion by TroRon** [danny-avila/LibreChat#2972] [Q&A] [answered]
### What is your question?

I have set the following preset in librechat.yaml:

modelSpecs:
  enforce: false
  prioritize: true
  list:
    - name: "gpt-4o"
      label: "AI Assistant"
      description: "The Quick Brown Fox Jumps over the lazy dog"
      iconURL: "https://www.xyz.com/static/images/favicon.ico"
      preset:
        default: true
        endpoint: "OpenAI"
        model: "gpt-4o"  # Ensure this is the correct model name for your use case
        maxContextTokens: 8192  # Adjust to realistic values, GPT-4 typically supports up to 8k context tokens
        max_tokens: 4096  # Maximum output tokens, should be realistic
        temperature: 0.2
        modelLabel: "AI Assistant"
        greeting: |
          Hi..
    
The whole thing works, but I can't get the DALL-E3 plug-in to be activated for EVERY new user.

The user could go to the plug-in store and activate the plug-in (key stored). But I would like to ensure that the plug-in is ALWAYS active.

Am I missing something?

Thanks for a tip.

Greetings

Ronny      

### More Details

See question

### What is the main subject of your question?

UI

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TroRon** [comment, marked as answer]
![image](https://github.com/danny-avila/LibreChat/assets/62324756/442855ec-7c5f-45f3-afd9-fb54d7166320)

Found, sorry ;)

**Reply by TroRon** [reply]
But it probably only works halfway ...

The settings are not pulled on a new browser :(

I'll keep looking ...

**Reply by danny-avila** [reply]
on a new browser? What do you mean by this? It should work on any browser as long as the model spec is selected.

**Reply by TroRon** [reply]
Browser 1
![image](https://github.com/danny-avila/LibreChat/assets/62324756/a100d269-b67d-4971-9cf9-32f1fc2973f2)

Browser 2
![image](https://github.com/danny-avila/LibreChat/assets/62324756/688cc954-dce9-4aeb-a389-1e78e262e893)


Same User logged in ...

No possibility to activate the plug-ins

Interface:
  endpointsMenu: false
  modelSelect: false
  parameters: false
  sidePanel: true
  presets: false
  
  includedTools: ["dalle", "web-browser","calculator"]


modelSpecs:
  enforce: false
  prioritize: true
  list:
    - name: "gpt-4o"
      label: "Liberty AI Assistant"
      description: "Dein persönlicher Assistent"
      iconURL: "https://www.xyz/liberty/images/favicon.ico"
      preset:
        default: true
        tools: ["dalle", "web-browser","calculator"]
        endpoint: "OpenAI"
        model: "gpt-4o"  # Ensure this is the correct model name for your use case
        maxContextTokens: 8192  # Adjust to realistic values, GPT-4 typically supports up to 8k context tokens
        max_tokens: 4096  # Maximum output tokens, should be realistic
        temperature: 0.2
        modelLabel: "Liberty AI Assistant"
        greeting: |
          Hi, wie kann ich Dir heute helfen?
        
        
        When I switch on enforce, I get a model mismatch error message


Also found out:

If I write in another browser in a chat in which the plug-ins were activated, it works.

If I make a new chat, the settings do not seem to work.

The goal should be that the plugins are active for EVERY chat.

Have I misunderstood something somewhere, or have I missed something?

**Reply by danny-avila** [reply]
I think the issue is that you're using the "OpenAI" endpoint. For tool use, it needs to be "gptPlugins"

```yaml
modelSpecs:
  enforce: false
  prioritize: true
  list:
    - name: "gpt-4o"
      label: "Liberty AI Assistant"
      description: "Dein persönlicher Assistent"
      iconURL: "https://www.xyz/liberty/images/favicon.ico"
      preset:
        default: true
        tools: ["dalle", "web-browser","calculator"]
        endpoint: "gptPlugins" # THIS VALUE CHANGED
        model: "gpt-4o"
        maxContextTokens: 8192
        max_tokens: 4096
        temperature: 0.2
        modelLabel: "Liberty AI Assistant"
        greeting: Hi, wie kann ich Dir heute helfen?
        agentOptions: # Add this if you want to also decide the model that actually calls the tool
          model: "gpt-4o"
```

This is on a user, without plugins installed.

![image](https://github.com/danny-avila/LibreChat/assets/110412045/004a3504-7a80-44c5-a9df-23e22fd496cf)
