### DISCUSSION TITLE
Error 400 When Using Azure As Endpoint

### DISCUSSION THREAD

**Discussion by IAmStoxe** [danny-avila/LibreChat#3027] [Troubleshooting]
### What happened?

I have configured my instance to utilize Azure but returns a 400 error when making a request.

I have read the other discussions (#1631) about extraneous Azure configuration options but no luck.

This is my `.env` configuration:

```
AZURE_API_KEY="REDACTED"
AZURE_OPENAI_API_COMPLETIONS_DEPLOYMENT_NAME="GPT-35-Turbo"
AZURE_OPENAI_API_DEPLOYMENT_NAME="GPT-35-Turbo"
AZURE_OPENAI_API_INSTANCE_NAME="REDACTED"
AZURE_OPENAI_API_VERSION="2024-02-01"
AZURE_OPENAI_DEFAULT_MODEL="GPT-35-Turbo"
AZURE_OPENAI_MODELS="GPT-35-Turbo,GPT-4"
AZURE_USE_MODEL_AS_DEPLOYMENT_NAME="true"
```

In discussion #1631 they mention trying to use only the below keys, but that returns the same error.

```
AZURE_API_KEY="REDACTED"
AZURE_OPENAI_API_INSTANCE_NAME="REDACTED""
AZURE_OPENAI_API_DEPLOYMENT_NAME="GPT-35-Turbo"
AZURE_OPENAI_API_VERSION="2023-07-01-preview"
```

```json
{
  "level": "error",
  "message": "[handleAbortError] AI response error; aborting request: Failed to send message. HTTP 400 - Unsupported data type\n",
  "stack": "Error: Failed to send message. HTTP 400 - Unsupported data type\n\n    at onopen (/media/data/home/dstokes/LibreChat2/api/app/clients/ChatGPTClient.js:224:25)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async create (/media/data/home/dstokes/LibreChat2/node_modules/@waylaidwanderer/fetch-event-source/lib/cjs/fetch.cjs:56:17)",
  "status": 400,
}
```

I would **GREATLY** appreciate any guidance on what to try.

### Steps to Reproduce

1. Load up the project
2. Fill in the .env as described
3. Send a message
4. Notice that you get a `400 Error`

### Relevant log output

```shell
{"level":"error","message":"[handleAbortError] AI response error; aborting request: Failed to send message. HTTP 400 - Unsupported data type\n","stack":"Error: Failed to send message. HTTP 400 - Unsupported data type\n\n    at onopen (/media/data/home/dstokes/LibreChat2/api/app/clients/ChatGPTClient.js:224:25)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async create (/media/data/home/dstokes/LibreChat2/node_modules/@waylaidwanderer/fetch-event-source/lib/cjs/fetch.cjs:56:17)","status":400}
{"level":"error","message":"[handleAbortError] AI response error; aborting request: Failed to send message. HTTP 400 - Unsupported data type\n","stack":"Error: Failed to send message. HTTP 400 - Unsupported data type\n\n    at onopen (/media/data/home/dstokes/LibreChat2/api/app/clients/ChatGPTClient.js:224:25)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async create (/media/data/home/dstokes/LibreChat2/node_modules/@waylaidwanderer/fetch-event-source/lib/cjs/fetch.cjs:56:17)","status":400}
{"level":"error","message":"[handleAbortError] AI response error; aborting request: Failed to send message. HTTP 400 - Unsupported data type\n","stack":"Error: Failed to send message. HTTP 400 - Unsupported data type\n\n    at onopen (/media/data/home/dstokes/LibreChat2/api/app/clients/ChatGPTClient.js:224:25)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async create (/media/data/home/dstokes/LibreChat2/node_modules/@waylaidwanderer/fetch-event-source/lib/cjs/fetch.cjs:56:17)","status":400}
{"level":"error","message":"[handleAbortError] AI response error; aborting request: Failed to send message. HTTP 400 - Unsupported data type\n","stack":"Error: Failed to send message. HTTP 400 - Unsupported data type\n\n    at onopen (/media/data/home/dstokes/LibreChat2/api/app/clients/ChatGPTClient.js:224:25)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async create (/media/data/home/dstokes/LibreChat2/node_modules/@waylaidwanderer/fetch-event-source/lib/cjs/fetch.cjs:56:17)","status":400}
```

### Screenshots

![image](https://github.com/danny-avila/LibreChat/assets/16467875/536b80b5-ad8a-4472-9b23-a25aeb689612)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
See the new method of configuring Azure: https://www.librechat.ai/docs/configuration/azure

**Reply by IAmStoxe** [reply]
Thanks @danny-avila 
Is there any old documentation I can use to get this working on an older version without merging all the changes?

When I try to use librechat.yaml I get this:

```
2024-06-10 19:40:44 error: Invalid custom config file at /media/data/home/dstokes/LibreChat2/librechat.yaml [
  {
    "code": "invalid_type",
    "expected": "array",
    "received": "undefined",
    "path": [
      "endpoints",
      "custom"
    ],
    "message": "Required"
  },
  {
    "code": "unrecognized_keys",
    "keys": [
      "azureOpenAI"
    ],
    "path": [
      "endpoints"
    ],
    "message": "Unrecognized key(s) in object: 'azureOpenAI'"
  }
]
```

**Reply by IAmStoxe** [reply]
Any guidance would be greatly appreciated <3

**Comment by IAmStoxe** [comment]
@danny-avila - I have upgraded to version v0.7.2 and configured librechat.yaml (below) and getting the folllowing error now:

`Something went wrong. Here's the specific error message we encountered: An error occurred while processing your request. Please contact the Admin.`

It seems to be even less troubleshoot-able.

```yaml
# Configuration version (required)
version: 1.0.9

# Cache settings: Set to true to enable caching
cache: true

endpoints:
  azureOpenAI:
    # Endpoint-level configuration
    titleModel: 'GPT-35-Turbo'
    plugins: true
    assistants: false
    groups:
      # Group-level configuration
      - group: 'bpmwestopenai'
        apiKey: '${AZURE_API_KEY}'
        instanceName: 'bpmwestopenai'
        version: '2024-04-01-preview'
        # Model-level configuration
        models:
          GPT-35-Turbo:
            deploymentName: GPT-35-Turbo
          GPT-4:
            deploymentName: GPT-4
```

**Reply by danny-avila** [reply]
check your logs in project root, `./logs`

it's plenty possible to troubleshoot, see the error and debug logs

**Reply by danny-avila** [reply]
Also it's recommended to define the model names with their matching identifiers: 

https://platform.openai.com/docs/models ( the table values under the "model" column)

```yaml
        models:
          gpt-3.5-turbo:
            deploymentName: GPT-35-Turbo
          gpt-4:
            deploymentName: GPT-4
```

Note that the deploymentNames remain the same

**Reply by IAmStoxe** [reply]
Thanks for the help!

I grabbed the logs from `api/logs` and see the same messaging as the console. 
```
2024-06-10T21:42:16.846Z debug: [BaseClient] Loading history:
{
  conversationId: "9e7cdb87-c873-44ce-ac75-600f2321723e",
  parentMessageId: "00000000-0000-0000-0000-000000000000",
}
2024-06-10T21:42:17.098Z error: [handleAbortError] AI response error; aborting request: Failed to send message. HTTP 400 - Unsupported data type
2024-06-10T21:42:17.105Z debug: [AskController] Request closed
2024-06-10T21:43:28.841Z debug: [AskController]
{
  text: "test",
  conversationId: "9e7cdb87-c873-44ce-ac75-600f2321723e",
  endpoint: "azureOpenAI",
  chatGptLabel: null,
  promptPrefix: null,
  resendFiles: true,
  imageDetail: "auto",
  iconURL: undefined,
  greeting: undefined,
  spec: undefined,
  maxContextTokens: undefined,
    modelOptions.model: "GPT-3.5-Turbo",
    modelOptions.temperature: 1,
    modelOptions.top_p: 1,
    modelOptions.presence_penalty: 0,
    modelOptions.frequency_penalty: 0,
    modelOptions.stop: undefined,
    modelOptions.max_tokens: undefined,
    // 20 openAI(s)
    modelsConfig.openAI: ["gpt-4o-2024-05-13","gpt-3.5-turbo-16k","gpt-4-turbo-2024-04-09","gpt-4-turbo","gpt-4-1106-preview","gpt-3.5-turbo-1106","gpt-4-0125-preview","gpt-3.5-turbo-0125","gpt-3.5-turbo","gpt-3.5-turbo-0301","gpt-4-turbo-preview","gpt-3.5-turbo-16k-0613","gpt-3.5-turbo-0613","gpt-4","gpt-4-1106-vision-preview","gpt-4-0613","gpt-4-vision-preview","gpt-4o","gpt-3.5-turbo-instruct-0914","gpt-3.5-turbo-instruct"],
    // 12 google(s)
    modelsConfig.google: ["gemini-pro","gemini-pro-vision","chat-bison","chat-bison-32k","codechat-bison","codechat-bison-32k","text-bison","text-bison-32k","text-unicorn","code-gecko","code-bison","code-bison-32k"],
    // 10 anthropic(s)
    modelsConfig.anthropic: ["claude-3-opus-20240229","claude-3-sonnet-20240229","claude-3-haiku-20240307","claude-2.1","claude-2","claude-1.2","claude-1","claude-1-100k","claude-instant-1","claude-instant-1-100k"],
    // 2 gptPlugin(s)
    modelsConfig.gptPlugins: ["GPT-3.5-Turbo","GPT-4"],
    // 2 azureOpenAI(s)
    modelsConfig.azureOpenAI: ["GPT-3.5-Turbo","GPT-4"],
    // 2 bingAI(s)
    modelsConfig.bingAI: ["BingAI","Sydney"],
    // 1 chatGPTBrowser(s)
    modelsConfig.chatGPTBrowser: ["text-davinci-002-render-sha"],
    // 20 assistant(s)
    modelsConfig.assistants: ["gpt-4o-2024-05-13","gpt-3.5-turbo-16k","gpt-4-turbo-2024-04-09","gpt-4-turbo","gpt-4-1106-preview","gpt-3.5-turbo-1106","gpt-4-0125-preview","gpt-3.5-turbo-0125","gpt-3.5-turbo","gpt-3.5-turbo-0301","gpt-4-turbo-preview","gpt-3.5-turbo-16k-0613","gpt-3.5-turbo-0613","gpt-4","gpt-4-1106-vision-preview","gpt-4-0613","gpt-4-vision-preview","gpt-4o","gpt-3.5-turbo-instruct-0914","gpt-3.5-turbo-instruct"],
}
2024-06-10T21:43:28.845Z debug: [BaseClient] Loading history:
{
  conversationId: "9e7cdb87-c873-44ce-ac75-600f2321723e",
  parentMessageId: "00000000-0000-0000-0000-000000000000",
}
2024-06-10T21:43:28.995Z error: [handleAbortError] AI response error; aborting request: Failed to send message. HTTP 400 - Unsupported data type
2024-06-10T21:43:29.001Z debug: [AskController] Request closed
```

**Reply by danny-avila** [reply]
you should also try changing the API version, some versions are not supported in certain regions and/or with certain deployments

Try making a cURL request as shown here:
https://learn.microsoft.com/en-us/azure/ai-services/openai/reference

Then I can help you configure your yaml accordingly

**Reply by IAmStoxe** [reply]
Appreciate the tip. I should've mentioned cUrl works perfectly fine with my current version (and the `2024-02-01` referenced in the link)

**Reply by danny-avila** [reply]
Share a log of the cURL request working with redacted values, and I can try to see how the YAML might be misconfigured

**Reply by IAmStoxe** [reply]
Is this what you're looking for?

```
dstokes@SJO-PF4TH4NH-M:/mnt/c/Users/dstokes$ curl --location 'https: //REDACTED.openai.azure.com/openai/deployments/GPT-35-Turbo/chat/completions?api-version=2024-04-01-preview' --header 'Content-Type: application/json' --header 'api-key: REDACTED' --data '{
"messages": [
    {
        "role": "system",
        "content": "You are an AI assistant that helps people find information."
    }
],
"max_tokens": 800,
"temperature": 0.7,
"frequency_penalty": 0,
"presence_penalty": 0,
"top_p": 0.95,
"stop": null
}'
```

```json
{
"choices": [
    {
        "content_filter_results": {
            "hate": {
                "filtered": false,
                "severity": "safe"
            },
            "self_harm": {
                "filtered": false,
                "severity": "safe"
            },
            "sexual": {
                "filtered": false,
                "severity": "safe"
            },
            "violence": {
                "filtered": false,
                "severity": "safe"
            }
        },
        "finish_reason": "stop",
        "index": 0,
        "logprobs": null,
        "message": {
            "content": "Hello! How can I assist you today?",
            "role": "assistant"
        }
    }
],
"created": 1718056342,
"id": "chatcmpl-9YhE60862jQe6SLasnptqh5HHACWn",
"model": "gpt-35-turbo",
"object": "chat.completion",
"prompt_filter_results": [
    {
        "prompt_index": 0,
        "content_filter_results": {}
    }
],
"system_fingerprint": "fp_811936bd4f",
"usage": {
    "completion_tokens": 9,
    "prompt_tokens": 18,
    "total_tokens": 27
}
}
```

**Reply by IAmStoxe** [reply]
Would it have anything to do with Azure Open AI using Open AI models in `client/src/store/models.ts` ?

![image](https://github.com/danny-avila/LibreChat/assets/16467875/619281cc-cfb4-457e-ad5b-a9d77291c931)

**Reply by danny-avila** [reply]
> Would it have anything to do with Azure Open AI using Open AI models in client/src/store/models.ts ?

no there's no issue with that, otherwise it wouldn't work for me either.

---

This is how I would set it up based on your cURL request.

Assuming REDACTED is your instance name i.e. "https: //REDACTED.openai.azure.com"

```yaml
version: 1.1.4
cache: true
endpoints:
  azureOpenAI:
    titleModel: "gpt-3.5-turbo"
    titleConvo: true
    plugins: true
    groups:
    - group: "your-group-name" # arbitrary name
      apiKey: "${ARBITRARY_API_KEY}"
      instanceName: "REDACTED"
      version: "2024-04-01-preview"
      models:
        gpt-3.5-turbo:
          deploymentName: "GPT-35-Turbo"
        gpt-4:
          deploymentName: "GPT-4" # assuming the "GPT-4" deployment is on the same instance
```

`ARBITRARY_API_KEY` would actually be defined in your .env file like this:

```.env
ARBITRARY_API_KEY=your-key
```

Make sure you updated as shown here: https://www.librechat.ai/docs/local/docker#update-librechat

After trying this, can you share the logs from when the app starts?

Any time you make changes to the YAML file, you must restart the containers.

```bash
docker compose down
docker compose up
```

**Reply by IAmStoxe** [reply]
It looks like you got it on the head! Thanks a TON @danny-avila - Owe you big time.

 Looks like model names are case sensitive. 


This fails:
```
      models:
        GPT-3.5-Turbo:
          deploymentName: "GPT-35-Turbo"
        GPT-4:
          deploymentName: "GPT-4" # assuming the "GPT-4" deployment is on the same instance
```



This works:

```
      models:
        gpt-3.5-turbo:
          deploymentName: "GPT-35-Turbo"
        gpt-4:
          deploymentName: "GPT-4" # assuming the "GPT-4" deployment is on the same instance
```

I am hoping to have the UI result in Capitalized (title case effectively) model names. Can I achieve that while avoiding this bug?
