### DISCUSSION TITLE
Presets did not work with custom model.

### DISCUSSION THREAD

**Discussion by Alex-Karmazin** [danny-avila/LibreChat#3072] [Troubleshooting]
### What happened?

I have a custom endpoint that implements agent logic on server side with streaming interface. It mimics openai API. I want to have brief description for user about agent capabilities. And decide to use presets because they have "greeting" section that could do what I want. But when I edit librechat.yaml file to accomplish this, it appears not working. Yaml file I checked in validator and it is ok. Also, I do docker compose down and docker compose up commands to update the system. I add librechat.yaml file in Relevant log output section. I use LibreChat v0.7.2

### Steps to Reproduce

1 Add custom endpoint in librechat.yaml file.
2 Add preset referring this custom endpoint.

Expected result: preset is working and greeting message present on UI.
Actual result: nothing changed in UI.

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
# For more information, see the Configuration Guide:
# https://www.librechat.ai/docs/configuration/librechat_yaml

# Configuration version (required)
version: 1.0.9

# Cache settings: Set to true to enable caching
cache: false

# Custom interface configuration
interface:
  presets: true
  # Privacy policy settings
  privacyPolicy:
    externalUrl: 'https://librechat.ai/privacy-policy'
    openNewTab: true

  # Terms of service
  termsOfService:
    externalUrl: 'https://librechat.ai/tos'
    openNewTab: true
    
    
modelSpecs:
  enforce: true
  prioritize: true
  list:
    - name: 'just_DNA_Seq_preset'
      label: 'just_DNA_Seq_preset'
      description: "just-DNA-Seq agent"
      iconURL: ""
      preset:
        default: true
        endpoint: "just_DNA_Seq"
        model: "groq/llama3-70b-8192"
        maxContextTokens: 128000 # Maximum context tokens
        max_tokens: 4096 # Maximum output tokens
        temperature: 0.0
        modelLabel: "just_DNA_Seq_preset"
        greeting: |
          This is just_DNA_Seq genetics genie agent to answer your questions abou genetics and longevity.
        promptPrefix: "Something"
          

# Example Registration Object Structure (optional)
registration:
  socialLogins: ['github', 'google', 'discord', 'openid', 'facebook']
  # allowedDomains:
  # - "gmail.com"

# rateLimits:
#   fileUploads:
#     ipMax: 100
#     ipWindowInMinutes: 60  # Rate limit window for file uploads per IP
#     userMax: 50
#     userWindowInMinutes: 60  # Rate limit window for file uploads per user
#   conversationsImport:
#     ipMax: 100
#     ipWindowInMinutes: 60  # Rate limit window for conversation imports per IP
#     userMax: 50
#     userWindowInMinutes: 60  # Rate limit window for conversation imports per user

# Definition of custom endpoints
endpoints:
#  assistants:
#      disableBuilder: false # Disable Assistants Builder Interface by setting to `true`
#  #   pollIntervalMs: 750  # Polling interval for checking assistant updates
#  #   timeoutMs: 180000  # Timeout for assistant operations
#  #   # Should only be one or the other, either `supportedIds` or `excludedIds`
#      supportedIds: ["asst_EFVxISukwIkKqkmQrBerGOrU"]
#  #   # excludedIds: ["asst_excludedAssistantId"]
#  #   # (optional) Models that support retrieval, will default to latest known OpenAI models that support the feature
#      retrievalModels: ["gpt-4-turbo-preview"]
#  #   # (optional) Assistant Capabilities available to all users. Omit the ones you wish to exclude. Defaults to list below.
#  #   capabilities: ["code_interpreter", "retrieval", "actions", "tools", "image_vision"]
#      capabilities: ["actions"]
  custom:
    # just_DNA_Seq custom endpoint
    - name: 'just_DNA_Seq'
      apiKey: 'API key is in .env file.'
      baseURL: 'http://host.docker.internal:8088/v1/'
      models:
        default: [
          "gpt-4o",
          "groq/llama3-70b-8192",
          ]
        fetch: false
      titleConvo: true
      titleModel: "groq/llama3-70b-8192"
      addParams:
        stream: true
      modelDisplayLabel: 'just_DNA_Seq'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Check your container logs or the logs found in the `./logs` directory in project root, the debug/error logs would be helpful

**Comment by Alex-Karmazin** [comment]
[error-2024-06-16.log](https://github.com/user-attachments/files/15859246/error-2024-06-16.log)
[debug-2024-06-16.log](https://github.com/user-attachments/files/15859247/debug-2024-06-16.log)

Error log is empty. In debug nothing suspicious.

**Reply by zhnedyalkow** [reply]
I think the issue in your case was 

```
interface:
  presets: true  <-- it should be `false` according to the documentation
```

**Comment by zhnedyalkow** [comment]
Hello @danny-avila,

I'm experiencing the same issue using similar configuration:

```
modelSpecs:
  enforce: true
  prioritize: true
  list:
    - name: 'prompt'
      label: 'Prompt'
      description: 'Prompt'
      preset: 
        default: true
        endpoint: 'http://{MY_IP}:4000/v1/chat/completions'
        model: 'Legal-7B-0'
        promptPrefix: "As a legal advisor, ..."

endpoints:
  assistants:
    disableBuilder: true # Disable Assistants Builder Interface by setting to `true`
    # Mistral AI API
    - name: 'Legal-7B-01'
      apiKey: '1234'
      baseURL: '{MY_IP}:4000/v1/'
      models:
        default:
          - 'Legal-7B-01'
        fetch: false
      titleConvo: false
      titleMethod: 'completion'
      titleModel: 'MyModel'
      summarize: false
      summaryModel: 'Legal-7B-01'
      forcePrompt: false
      modelDisplayLabel: 'Legal Advisor'
      addParams:
        stream: true
        presence_penalty: 1.04
        top_p: 0.3
      dropParams: ['stop', 'user', 'frequency_penalty', 'max_tokens']
```

Any thoughts? Do you have any example with custom endpoint availabe?
