### DISCUSSION TITLE
Upgrade policy for meilisearch?

### DISCUSSION THREAD

**Discussion by rcdailey** [danny-avila/LibreChat#3109] [Q&A] [answered]
I noticed that meilisearch v1.8 is available. However, that release does contain some breaking changes. I typically consult LibreChat's `docker-compose.yml` for guidance on which version of meilisearch to use (which is currently v1.7.3).

Is the official recommendation to follow the exact version used in the LibreChat compose file? Or is it always safe to upgrade? I just want to make sure I'm following recommended upgrade practices, since librechat contains a fairly sophisticated service stack.

Thanks!

**Comment by fuegovic** [comment, marked as answer]
You can safely update. We're using 1.8 on the public demo and it works fine. The only thing is that you need to delete the 1.7.x index and re-index after updating with 1.8 ( I'd recommend mapping another folder for the 1.8 index)

You can add this to your `docker-compose.override.yml` file to try it out yourself:

```yml
version: '3.4'

services:

# Your existing override file content....

  meilisearch:
    image: getmeili/meilisearch:v1.8
    volumes:
      - ./meili_data_v1.8:/meili_data
```
