### DISCUSSION TITLE
Reset Email not sending

### DISCUSSION THREAD

**Discussion by matthias-at-merona** [danny-avila/LibreChat#3113] [Troubleshooting] [answered]
Hi all,
sorry if this is a duplicate, but I could not find similar issues.

First: Great product you built. I deployed it on a Hetzner server in a Docker Coolify environment and after initial struggles it works really well.

However, I noticed that password reset mails do not arrive. All I can find in the logs is "`error: [sendEmail] Connection timeout`" for the ssl configuration. I tried email configurations according to [your password reset docs](https://www.librechat.ai/docs/configuration/authentication/password_reset) both with a throwaway google mail account and with a dedicated Strato smtp email address. Tried tls and ssl with respective ports 587 and 465 according to their documentation. The tls configuration specifically works for other services, only librechat runs into issues.

Do you have an idea what the problem could be? Is the timeout just kind of a catch-all error message, or a specific indication on a misconfiguration I can follow? Is the issue that it runs inside of Docker and that I need additional wiring? If so, are there variables I can set inside .env that let me do this, or would I need scripts to handle any of that?

My .env email configuration (in case of obvious issues here already) is 

```
EMAIL_ALLOW_SELFSIGNED=false
EMAIL_ENCRYPTION=tls
EMAIL_ENCRYPTION_HOSTNAME=
EMAIL_FROM=some@mail
EMAIL_FROM_NAME=somename
EMAIL_HOST=smtp.strato.de
EMAIL_PASSWORD=somelongandsecurepassword
EMAIL_PORT=587
EMAIL_SERVICE=
EMAIL_USERNAME=some@mail
```

Thanks for reading and thanks in advance 😄 

**Edit:** 
Actually, for my tls configuration I receive the error `error: [sendEmail] E8D16D12967A0000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:354:` which is at least different to a timeout.

**Edit 2:**
I don't think this has anything to do with the issue here but just for future readers who are stuck in a similar way:
After googling the above error I tried starttls (which is not a protocol, I know, and which is not supported by Strato) and tried various ports, all of which only resulted in `error: [sendEmail] Invalid login: 535 5.7.8 Authentication failed: wrong user/password`.

**Comment by danny-avila** [comment]
Sorry that you're struggling here. it could be that the port is not being correctly interpreted as an integer, I will try that and see if it works for you with your original settings.

**Reply by danny-avila** [reply]
Before I get to investigate, I will add that it might be helpful to search for these issues alongside "nodemailer" in your search queries.

`nodemailer` is the library we use and it's very well established.

**Reply by matthias-at-merona** [reply]
Thank you, that is a potentially very helpful hint!

**Reply by ctwhome** [reply]
Hi @matthias-at-merona would you mind to share the steps to install it with coolidy? using docker, docker-compose? Many thanks!

**Reply by matthias-at-merona** [reply]
Oh ctwhome strap up cause this might take a bit to figure out. It has been weeks ago for me, so please don't mind if there are gaps in my memory. Disclaimer: I am still running Coolify v4.0.0-beta.285. Thing might look different in other versions.

First: I assume you have your server and all running, and coolify is otherwise working. Tried for instance one of the test things on there, like an empty wordpress project, and that just worked.
Next up is a Git Based Public Repository import from the libre chat docker compose into a probably new coolify project. Once you set a domain for the API you should be able to access a 503 or 501 (forgot which) under whatever you set there. Pro tip: Set the port the thing is running under behind your set domain, for instance
instead of `mydomain` use `mydomain:3080`.
That way you can navigate to your desired location `mydomain` directly instead of navigating to your domain plus port. Coolify is nice like that. Afterwards make sure to press "Reload Compose File" and probably "Save". Redeploy (important).

Nice falling hazard one can get stuck on when careless: If you followed some coolify tutorial and activated a firewall on your server but you did not proxy to 3080 in your "domains for API" field then you are probably going to be very sad and don't know why you cannot reach your application, because 3080 is usually not one of the ports people leave open on their firewalls and chat is just successfully hidden.


So you navigate to your correctly routed chat application and get a 503 or 501 or something, it was probably Forbidden. At this point I was very much stuck for days because I saw no good way to adjust my docker compose or env variables the way I was meant to. The solution: Grab your whole env file, the one with which it works on your localhost (make sure it does there), and put it into the Environment Variables. To do that, navigate to the tab in your configuration, click developer view and just throw the whole thing in there. Save. Yeet it into the `Preview Environment Variables` box as well for good measure. Don't know what that box does, but it did not hurt me having all my variables in there as well so I left it after initial experimentation. Save again.
Redeploy.

Turns out that these environment variables are actually used to create your env file inside your project. Not having that means your application cannot properly function. You should now be able to navigate to libre chat, but on your server instead of on your localhost.


Bonus knowledge if you are starting out with this and you successfully deployed on server: set stuff into your email fields in your environment variables. Not having anything in there means anyone can pick an email address they know is registered in your server chat database and reset it without email verification link. [That is a feature](https://github.com/danny-avila/LibreChat/discussions/1653).
Also, for your own peace of mind, tell everyone who is meant to be on there to register right away, then set all environment variables that contain the words "allow" and "registration" to false. Otherwise you need to find a way to check your registered users and kick the ones that use your paid subscriptions without you noticing.

Once you have users who need to reset their account passwords, either make the environment variable email fields empty, redeploy, reset their password with the scary unsafe method, fill the email fields again, and redeploy again as fast as you can, or join us in trying to figure out why emails don't go out into the world despite coolify managing to send them from the same hardware with the same credentials.

Edit: These steps got me to get it running on a basic level. I should probably take some time to figure out how to [override dockercompose for security reasons I think?](https://www.librechat.ai/docs/configuration/docker_override) but I did not do that yet. If you do and get it working, please let all of us know how to do that in coolify.

Edit 2: Changed Initial setup instructions from Docker Compose to Git Public Repository. This mistake causes some of the confused messages further down in this discussion.

**Reply by ctwhome** [reply]
thanks @matthias-at-merona for you detailed response. I didin' tmanage to get it to work. The env variables are set, and all the containers are running oke, but the domain is indeed a problem. 
<img width="758" alt="image" src="https://github.com/user-attachments/assets/92bbbead-dc17-4fa3-8691-bb7fdc1b3ba9">


---

# Setting Up LibreChat with Coolify

Follow these steps to set up LibreChat using Coolify:

### 1. Check Coolify Setup
- Ensure your server and Coolify (v4.0.0-beta.285) are running properly.
- Test with a sample project like an empty WordPress to confirm.

### 2. Import Docker Compose
- Create a new Coolify project.
- Import the LibreChat Docker Compose file.
- Set a domain for the API, and include the port (e.g., `mydomain:3080`).
- Click “Reload Compose File” and "Save".
- Redeploy the project.

### 3. Firewall Configuration
- Make sure your server's firewall allows traffic on the port (e.g., `3080`).

### 4. Environment Variables
- If you encounter a `503` or `501` error, import your local `.env` file into Coolify’s Environment Variables tab.
- Save and redeploy your project.

### 5. Email Configuration
- Add email settings to the environment variables to avoid security issues with password resets.
- Have intended users register immediately, then disable open registration by setting relevant environment variables (keywords `allow` and `registration`) to `false`.

### 6. Password Reset
- For password resets, temporarily clear email environment variables, redeploy, reset passwords manually, then reinstate the email variables and redeploy promptly.

This should get LibreChat running on your server. For better security, consider custom Docker Compose modifications.

**Reply by ctwhome** [reply]
I have created a feature request inside Coolify https://github.com/coollabsio/coolify/discussions/2867

**Reply by matthias-at-merona** [reply]
Your interface looks way different than mine.

When I was talking about the Domains for API field, I meant this one:

![image](https://github.com/user-attachments/assets/4d653350-3568-4493-8a31-e0bdef893617)

Your step by step guide has some specifics that are unique to my situation, like the Coolify version. I would advise changing those. Also, I would not put port 3080 onto the Firewall OK list. It has no business being exposed to the rest of the internet, let your proxy rewire that. Only access user oriented web pages over 80 (http) and 443 (https), and then configure it so that 80 redirects to 443.

You can set that in Coolify Project Configuration > Advanced. I at least have a Force Https field I can check.

**Reply by ctwhome** [reply]
that is funny because my version is only two more than yours 
![image](https://github.com/user-attachments/assets/51e0525c-5b26-454c-b713-64dd8bacf469)

**Reply by matthias-at-merona** [reply]
I noticed than in new services I set up I am missing the General and Advanced Tabs is well. Those are important, why would they take them out?

**Reply by matthias-at-merona** [reply, marked as answer]
@danny-avila Figured it out.
[Apparently 587 cannot handle TLS on server connection sometimes?](https://appwrite.io/threads/1197150984984604723) Usually people get around this by setting the nodemailer secure flag to false, which means initial communication to server is not encrypted. I did some trial and error experimentation, and apparently setting the librechat EMAIL_ENCRYPTION variable to nothing instead of TLS or whatnot achieves this behaviour. As a workaround this works for now. I am not sure about the implications here. Did I generally give up encryption? Does it use some default? How does this work if my server insists on encrypted communication?
Having an env variable for this while keeping the encryption as TLS might be nice. If the communication is still encrypted and this only affects the initial handshake then leave it like this I'd say.

**Reply by matthias-at-merona** [reply]
@ctwhome 
In the meantime I also figured out why my interface looks different from yours. 
> docker compose import from the libre chat docker compose into a probably new coolify project.

This was not true. When initially creating the project resource, do not create anything Docker based. Do Git based, select Public Repository. This gives you a much wider array of options to configure your application. Sorry for the mixup.

**Reply by rafae2k** [reply]
@matthias-at-merona can you share your docker compose deploy of librechat?

**Reply by matthias-at-merona** [reply]
@rafae2k Nothing fancy if you mean the automatically generated Docker Compose file. It mostly takes the librechat compose and adds labels and network stuff. Looks like this:

```
services:
  api:
    container_name: api-<containername>-bunchanumbers
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      - mongodb
      - rag_api
    image: 'ghcr.io/danny-avila/librechat-dev:latest'
    restart: always
    user: '${UID}:${GID}'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      - HOST=0.0.0.0
      - 'MONGO_URI=mongodb://mongodb:27017/LibreChat'
      - 'MEILI_HOST=http://meilisearch:7700'
      - 'RAG_PORT=${RAG_PORT:-8000}'
      - 'RAG_API_URL=http://rag_api:${RAG_PORT:-8000}'
    volumes:
      - '/data/coolify/applications/<containername>/.env:/app/.env'
      - '/data/coolify/applications/<containername>/images:/app/client/public/images'
      - '/data/coolify/applications/<containername>/logs:/app/api/logs'
    networks:
      <containername>: null
    labels:
      - whole lot of auto generated traefik and caddy stuff, just let coolify do its thing
      - in here will also be the info you set using the "Domains for API (i)" field. Set that.
  mongodb:
    container_name: mongodb-<containername>-bunchanumbers
    image: mongo
    restart: always
    user: '${UID}:${GID}'
    volumes:
      - '/data/coolify/applications/<containername>/data-node:/data/db'
    command: 'mongod --noauth'
    networks:
      <containername>: null
    labels:
      - coolify.managed=true
      - coolify.version=4.0.0-beta.360
      - coolify.applicationId=4
      - coolify.type=application
      - coolify.name=mongodb-<containername>-bunchanumbers
      - coolify.pullRequestId=0
  meilisearch:
    container_name: meilisearch-<containername>-bunchanumbers
    image: 'getmeili/meilisearch:v1.7.3'
    restart: always
    user: '${UID}:${GID}'
    environment:
      - 'MEILI_HOST=http://meilisearch:7700'
      - MEILI_NO_ANALYTICS=true
    volumes:
      - '/data/coolify/applications/<containername>/meili_data_v1.7:/meili_data'
    networks:
      <containername>: null
    labels:
      - coolify.managed=true
      - coolify.version=4.0.0-beta.360
      - coolify.applicationId=4
      - coolify.type=application
      - coolify.name=meilisearch-<containername>-bunchanumbers
      - coolify.pullRequestId=0
  vectordb:
    container_name: vectordb-<containername>-bunchanumbers
    image: 'ankane/pgvector:latest'
    environment:
      POSTGRES_DB: <somedatabase>
      POSTGRES_USER: <someuser>
      POSTGRES_PASSWORD: <somepassword>
    restart: always
    volumes:
      - 'pgdata2:/var/lib/postgresql/data'
    networks:
      <containername>: null
    labels:
      - coolify.managed=true
      - coolify.version=4.0.0-beta.360
      - coolify.applicationId=4
      - coolify.type=application
      - coolify.name=vectordb-<containername>-bunchanumbers
      - coolify.pullRequestId=0
  rag_api:
    container_name: rag_api-<containername>-bunchanumbers
    image: 'ghcr.io/danny-avila/librechat-rag-api-dev-lite:latest'
    environment:
      - DB_HOST=vectordb
      - 'RAG_PORT=${RAG_PORT:-8000}'
    restart: always
    depends_on:
      - vectordb
    env_file:
      - .env
    networks:
      <containername>: null
    labels:
      - coolify.managed=true
      - coolify.version=4.0.0-beta.360
      - coolify.applicationId=4
      - coolify.type=application
      - coolify.name=rag_api-<containername>-bunchanumbers
      - coolify.pullRequestId=0
volumes:
  pgdata2:
    name: pgdata2
networks:
  <containername>:
    name: <containername>
    external: true
configs: {  }
secrets: {  }
```
