### DISCUSSION TITLE
Model Specs Settings a little buggy

### DISCUSSION THREAD

**Discussion by prononext** [danny-avila/LibreChat#3187] [Troubleshooting]
### What happened?

I noticed when using Model Specs https://www.librechat.ai/docs/configuration/librechat_yaml/object_structure/model_specs, that when I have different endpoints in several specs like openai, google, gptPlugins and I change to a spec that has the plugins endpoint and then go back to the one that has a openai or google endpoint, the endpoint does not change and stays on plugins. 

Also changing ` prioritize: true` did not help. When having set that its the same. 

### Steps to Reproduce

1. Create a librechat.yml with several modelSpecs like openai, google, gptPlugins and define also tools in the gptPlugins endpoint modelSpec.
2. Open the LibreChat Gui and click on the openai ModelSpecs template
3. Then click on the gptPlugins modelSpecs template
4. Then again on the openai 

you will see that the endpoint does not change back, after the settings you have set in the modelSpecs but stays on the gptPlugins endpoint. 

The only way to get it working is to manually change the endpoint. 

Worse it gets when you have set ` prioritize: true` in one of your modelSpecs presets then the only way to change the endpoint is to go to one chat in your history wich has that endpoint as somehow the endpoint selector does not work anymore. 

Hopefully its clear, if there are any questions I am happy to help. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Can you walk me through a video of what you mean exactly? I think I see what you mean for the first part:
> change to a spec that has the plugins endpoint and then go back to the one that has a openai or google endpoint, the endpoint does not change and stays on plugins.

I can't reproduce it, it actually changes the Endpoint for me, however I agree that it should then change the "model spec" to "None Selected" instead of this: 

![image](https://github.com/danny-avila/LibreChat/assets/110412045/85cec105-5972-4c48-8960-ae4647971c42)

Note that it does this before a conversation is started:
![image](https://github.com/danny-avila/LibreChat/assets/110412045/8ca83da1-56f9-44a6-b431-362349ff844a)



> Worse it gets when you have set  prioritize: true in one of your modelSpecs presets then the only way to change the endpoint is to go to one chat in your history wich has that endpoint as somehow the endpoint selector does not work anymore.

This is somewhat expected behavior for `prioritize: true`, but I agree it's not ideal. I've discussed this elsewhere already and the conclusion was that this could be alleviated by adding a "none selected" option for model Specs


In general, the model specs are mostly designed to be used without the other settings, but I agree that there should be more to accommodate all of the possibilities

**Reply by danny-avila** [reply]
https://github.com/danny-avila/LibreChat/assets/110412045/d5df8812-cb34-4ad5-ac0c-0dccff67f6ce

here's a video of what i mean. I can see the confusion, since all the "plugins" rendering (the name, icon, the selected spec) is still active, but it has actually switched the endpoint (this is with `prioritize: false`)

This for sure should be fixed to remove the spec if the endpoint was outright selected.

My config for reference:
```yaml
interface:
  endpointsMenu: true
  modelSelect: true
  parameters: true
  presets: true
modelSpecs:
  enforce: false
  prioritize: false
  list:
      - name: "Gemini-Flash"
        label: "Gemini Flash"
        description: "Fastest model for quick responses."      
        preset:
          default: false
          endpoint: "google"
          model: "gemini-1.5-flash-preview-0514"
          temperature: 0.7
          modelLabel: "Gemini Flash"        
          greeting: |          
            Fast model for quick responses.
      - name: "image-generation"
        label: "Image generator"
        description: "Generate images starting form text."      
        preset:
          default: false
          endpoint: "gptPlugins"        
          tools: ["dalle"]                
          model: "gpt-3.5-turbo"
          temperature: 0.3
          modelLabel: "AI"        
          greeting: |          
            Try to be accurate while describing your image and remember that each generation is independent.
```

**Reply by prononext** [reply]
I was using `agentOptions` in the preset before, and ajusted it to your style. but still the same behavior. 

Here is my modelSpecs yml part: 

```
modelSpecs:
  enforce: false
  prioritize: false
  list:
      - name: "librechat-assistant"
        label: "Chat Assistant (GPT4o)"
        description: "Universal Assistant for general Tasks."
        iconURL: "https://librechat-image.s3.eu-central-1.amazonaws.com/chat-logo.svg"
        preset:
          default: true
          endpoint: "openai"
          model: "gpt-4o"
          modelLabel: "LibreChat Assistant"
          greeting: |
            This Assistant created by LibreChat can help you in general tasks.
            Capable of processing also visual image and file input.
          promptPrefix: |
            You are a helpful assistant. Your Name is LibreChat-Assistant. You are created by LibreChat. 
      - name: "librechat-assistant-tools"
        label: "Chat Assistantˣ² (GPT4o+Tools)"
        description: "Universal Assistant with Search, Browsing, Calculation and Image Capability"
        iconURL: "https://librechat-image.s3.eu-central-1.amazonaws.com/chat-logo.svg"
        preset:
          default: false
          endpoint: "gptPlugins"
          model: "gpt-4o"
          tools: ["web-browser", "calculator", "wolfram", "dalle", "google", "earthImagesAndVisualizations"]
          modelLabel: "LibreChat Assistantˣ²"
          greeting: |
            This Assistant created by LibreChat can help you in general tasks.
            Capable of processing also images and file input.
            With extensive capabilities to search the web, browse pages, calculate, get info from Wolfram|Alpha and create images and maps. 
          promptPrefix: |
            You are a helpful assistant. Your Name is LibreChat-Assistant. You are created by LibreChat.  
      - name: "librechat-assistant-gpt3"
        label: "Chat Assistant (GPT3.5)"
        description: "Universal Assistant for general Tasks."
        iconURL: "https://librechat-image.s3.eu-central-1.amazonaws.com/chat-logo.svg"
        preset:
          default: false
          endpoint: "openai"
          model: "gpt-3.5-turbo"
          modelLabel: "LibreChat Assistant"
          greeting: |
            This Assistant created by LibreChat can help you in general tasks.
            Capable of processing text file input.
          promptPrefix: |
            You are a helpful assistant. Your Name is LibreChat-Assistant. You are created by LibreChat.                  
      - name: "meeting-notes-gpt4"
        label: "Meeting Notes Assistant (GPT4o)"
        description: "Generate meeting notes by simply pasting in the transcript from a Teams recording."
        iconURL: "https://librechat-image.s3.eu-central-1.amazonaws.com/images/meeting-notes.png"
        preset:
          default: false
          endpoint: "openai"
          model: "gpt-4o"
          maxContextTokens: 128000 # Maximum context tokens
          max_tokens: 4096 # Maximum output tokens
          temperature: 0.2
          modelLabel: "Meeting Summarizer"
          greeting: |
            This assistant creates meeting notes based on transcripts of Teams recordings.
            To start, simply paste the transcript into the chat box.
          promptPrefix: |
            Based on the transcript, create coherent meeting minutes for a business meeting. Include the following sections:
            - Date and Attendees
            - Agenda
            - Minutes
            - Action Items
  
            Focus on what items were discussed and/or resolved. List any open action items.
            The format should be a bulleted list of high level topics in chronological order, and then one or more concise sentences explaining the details.
            Each high level topic should have at least two sub topics listed, but add as many as necessary to support the high level topic. 
  
            - Do not start items with the same opening words.
  
            Take a deep breath and be sure to think step by step. 
```

When I go to the librechat-assistant endpoint its fine. then changing to librechat-assistant-tools its changing to Plugins endpoint but back to librechat-assistant it stays on plugins endpoint and not goes back to the openai endpoint. 

strange when I test yours the change is working, but cannot see any bugs. 

When prioritize: false is active I can manually change the endpoint but when prioritize: true is active I also cannot do that.
