### DISCUSSION TITLE
Files are being lost on container redeploys

### DISCUSSION THREAD

**Discussion by javon27** [danny-avila/LibreChat#3235] [Q&A]
https://github.com/danny-avila/LibreChat/blob/a87d4e0b7587ff4ebe55a8cde184bf28d0575656/deploy-compose.yml#L90

I'm not an expert on containers, but I think the reason files are lost is because we don't have a named volume that can persist between deployments? This includes avatar images and other file uploads. I'm using the Railway one-click deployment.

**Comment by danny-avila** [comment]
> persist between deployments

if you are using the same directory the containers were initialized on, they should be persisting .

### MongoDB
```yaml
  mongodb:
    container_name: chat-mongodb
    image: mongo
    restart: always
    volumes:
      - ./data-node:/data/db
```
Mounts the host directory `./data-node` to the container's `/data/db` directory, ensuring MongoDB data persists.

### Meilisearch
```yaml
  meilisearch:
    container_name: chat-meilisearch
    image: getmeili/meilisearch:v1.7.3
    restart: always
    volumes:
      - ./meili_data_v1.7:/meili_data
```
Mounts the host directory `./meili_data_v1.7` to the container's `/meili_data` directory, ensuring Meilisearch data persists.

### VectorDB (PostgreSQL with pgvector)
```yaml
  vectordb:
    image: ankane/pgvector:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    restart: always
    volumes:
      - pgdata2:/var/lib/postgresql/data
```
Uses a Docker named volume `pgdata2` to persist PostgreSQL data in the container's `/var/lib/postgresql/data` directory.

### Volumes Definition
```yaml
volumes:
  pgdata2:
```
Defines the named volume `pgdata2` used by the `vectordb` service for data persistence.

```yaml
    ./images:/app/client/public/images: This line mounts the ./images directory from the host machine to the /app/client/public/images directory within the container.
```
This ensures that any images stored by the api service are persisted on the host machine, making them accessible even if the container restarts or is recreated.
