### DISCUSSION TITLE
Need help to make tools work on Azure Assistants

### DISCUSSION THREAD

**Discussion by djuillard** [danny-avila/LibreChat#3255] [Help Wanted]
I have setup tools and plugin on my LibreChat instances. I want them to work for both AzureOpenAI  and AzureAssistants endpoints, but so far it only works for AzureOpenAI.

Here is my conf of my .env file : 

```
#=====================================================================#
#                       LibreChat Configuration                       #
#=====================================================================#
# Please refer to the reference documentation for assistance          #
# with configuring your LibreChat environment. The guide is           #
# available both online and within your local LibreChat               #
# directory:                                                          #
# Online: https://docs.librechat.ai/install/configuration/dotenv.html #
# Locally: ./docs/install/configuration/dotenv.md                     #
#=====================================================================#

#==================================================#
#               Server Configuration               #
#==================================================#

HOST=localhost
PORT=3080

MONGO_URI=mongodb://127.0.0.1:27017/LibreChat

DOMAIN_CLIENT=http://localhost:3080
DOMAIN_SERVER=http://localhost:3080

NO_INDEX=true

#===============#
# JSON Logging  #
#===============#

# Use when process console logs in cloud deployment like GCP/AWS
CONSOLE_JSON=false

#===============#
# Debug Logging #
#===============#

DEBUG_LOGGING=true
DEBUG_CONSOLE=false

#=============#
# Permissions #
#=============#

# UID=1000
# GID=1000

#===============#
# Configuration #
#===============#
# Use an absolute path, a relative path, or a URL

# CONFIG_PATH="/alternative/path/to/librechat.yaml"

#===================================================#
#                     Endpoints                     #
#===================================================#

ENDPOINTS=azureOpenAI,azureAssistants,gptPlugins
#azureOpenAI,bingAI,google,gptPlugins,anthropic

PROXY=

#===================================#
# Known Endpoints - librechat.yaml  #
#===================================#
# https://docs.librechat.ai/install/configuration/ai_endpoints.html

AZUREOPENAI_SWEDEN_API_KEY=my_azure_openai_key


#============#
# Azure      #
#============#


RAG_AZURE_OPENAI_ENDPOINT=https://myinstance.openai.azure.com/
#DEBUG_RAG_API=true
RAG_AZURE_OPENAI_API_KEY=my_azure_openai_key
#RAG_AZURE_OPENAI_API_VERSION=2024-05-01-preview
EMBEDDINGS_PROVIDER=azure
EMBEDDINGS_MODEL=text-embedding-3-large




DEBUG_PLUGINS=true



# DALL·E
#----------------
# DALLE_API_KEY=
DALLE3_API_KEY=my_azure_openai_key
# DALLE2_API_KEY=
# DALLE3_SYSTEM_PROMPT=
# DALLE2_SYSTEM_PROMPT=
# DALLE_REVERSE_PROXY=
DALLE3_BASEURL=https://myinstance.openai.azure.com/openai/deployments/Dall-E3/
# DALLE2_BASEURL=

# DALL·E (via Azure OpenAI)
# Note: requires some of the variables above to be set
#----------------
DALLE3_AZURE_API_VERSION="2024-02-01"
# DALLE2_AZURE_API_VERSION=

# Google
#-----------------
GOOGLE_SEARCH_API_KEY=my_key
GOOGLE_CSE_ID=my_id

# SerpAPI
#-----------------
SERPAPI_API_KEY=

# Stable Diffusion
#-----------------
SD_WEBUI_URL=http://host.docker.internal:7860

# Tavily
#-----------------
TAVILY_API_KEY=my_key

# Traversaal
#-----------------
TRAVERSAAL_API_KEY=my_key

# WolframAlpha
#-----------------
WOLFRAM_APP_ID=

# Zapier
#-----------------
ZAPIER_NLA_API_KEY=
```

Here is my conf of my librechat.yaml file : 

```
# For more information, see the Configuration Guide:
# https://www.librechat.ai/docs/configuration/librechat_yaml

# Configuration version (required)
version: 1.1.4

# Cache settings: Set to true to enable caching
cache: true

includedTools: ["calculator", "google", "dalle", "tavily_search_results_json", "traversaal_search"]

# Custom interface configuration
interface:
  # Privacy policy settings
  privacyPolicy:
    externalUrl: 'https://librechat.ai/privacy-policy'
    openNewTab: true

  # Terms of service
  termsOfService:
    externalUrl: 'https://librechat.ai/tos'
    openNewTab: true
  endpointsMenu: true
  modelSelect: true
  parameters: true
  sidePanel: true
  presets: true


# Example Registration Object Structure (optional)
registration:
  socialLogins: ['github', 'google', 'discord', 'openid', 'facebook']

endpoints:
  azureAssistants:
     disableBuilder: false # Disable Assistants Builder Interface by setting to `true`
     pollIntervalMs: 750  # Polling interval for checking assistant updates
     timeoutMs: 180000  # Timeout for assistant operations
  #   # Should only be one or the other, either `supportedIds` or `excludedIds`
  #   supportedIds: ["asst_supportedAssistantId1", "asst_supportedAssistantId2"]
  #   # excludedIds: ["asst_excludedAssistantId"]
  #   # (optional) Models that support retrieval, will default to latest known OpenAI models that support the feature
     retrievalModels: ["gpt-4o"]
  #   # (optional) Assistant Capabilities available to all users. Omit the ones you wish to exclude. Defaults to list below.
     capabilities: ["code_interpreter", "actions", "tools", "image_vision"]
     privateAssistants: true

  azureOpenAI:
    titleModel: "gpt-35-turbo"
    plugins: true
    assistants: true
    groups:
      - group: "Azure_OpenAI_RG1"
        apiKey: "${AZUREOPENAI_SWEDEN_API_KEY}"
        instanceName: "myinstance"
        deploymentName: "GPT-4-SWEDEN"
        assistants: true
        version: "2024-05-01-preview" # Update with the correct version if needed
        models:
          gpt-4:
            deploymentName: "GPT-4-SWEDEN"
            version: "2024-05-01-preview"
          gpt-35-turbo: 
            deploymentName: "GPT-35-turbo"
            version: "2024-05-01-preview"
          gpt-4o: 
            deploymentName: "GPT-4o"
            version: "2024-05-01-preview"
          whisper:
            deploymentName: "whisper"
            version: "2024-05-01-preview"          


fileConfig:
  endpoints:
    azureOpenAI:
      fileLimit: 3
      fileSizeLimit: 10
      totalSizeLimit: 15
```

I can see in the dropdown list the plugin : 

![image](https://github.com/danny-avila/LibreChat/assets/11016691/ef0c0d5f-a736-407e-8176-d73c80979e7f)

And it works fine.

But when I select the azure assistant endpoint, and try to add tool, that's strange, I only see "Calculator" and nothing else....

![image](https://github.com/danny-avila/LibreChat/assets/11016691/4e67f6e4-fdd8-4084-a8a8-56055f750fd8)

I guess there is something wrong in my config files, but I cannot figure out what !
