### DISCUSSION TITLE
[Bug]: Creating a new conversation unselects the current modelSpec

### DISCUSSION THREAD

**Discussion by ghost** [danny-avila/LibreChat#3277] [Troubleshooting]
### What happened?

Before clicking on a new conversation (modelSpec):
![image](https://github.com/danny-avila/LibreChat/assets/34800546/d26bc6b7-6a20-4df5-beac-3dc02f0e7ede)

After clicking on a new conversation (no modelSpec):
![image](https://github.com/danny-avila/LibreChat/assets/34800546/ab1c6893-0f16-4892-a598-e6957f2e40e4)

```yml
modelSpecs:
  enforce: false
  prioritize: false
  list:
    - name: "gpt-4o-model1"
      label: "model1"
      description: "Using gpt-4o by OpenAI."
      iconURL: "{{baseurl}}/model1.jpg"
      preset:
        default: true
        endpoint: "openAI"
        model: "gpt-4o"
        maxContextTokens: 128000
        max_tokens: 4096
        temperature: 0.5
        resendFiles: false
        imageDetail: "auto"
        modelLabel: "model1"
        promptPrefix: |
          You are a useful assistant
    - name: "gpt-4o-model2"
      label: "model2"
      description: "Using gpt-4o by Azure."
      iconURL: "{{baseurl}}/model2.jpg"
      preset:
        default: false
        endpoint: "azureOpenAI"
        model: "gpt-4o-2024-05-13-1"
        maxContextTokens: 128000
        max_tokens: 4096
        temperature: 0.5
        resendFiles: false
        imageDetail: "auto"
        modelLabel: "model2"
        promptPrefix: |
          You are a useful assistant
    - name: "gpt-4o-model3"
      label: "model3"
      description: "Using gpt-4o by Azure."
      iconURL: "{{baseurl}}/model3.jpg"
      preset:
        default: false
        endpoint: "azureOpenAI"
        model: "gpt-4o-2024-05-13-2"
        maxContextTokens: 128000
        max_tokens: 4096
        temperature: 0.5
        resendFiles: false
        imageDetail: "auto"
        modelLabel: "model3"
        promptPrefix: |
          You are a useful assistant
```

Using prioritize=true resolves the issue, but now I can't select the API provider. The provider menu is open, but there is no reaction when clicking on a new endpoint.

### Steps to Reproduce

1. Select a model spec
2. Click "New conversation"

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
