### DISCUSSION TITLE
Custom Model Grouping

### DISCUSSION THREAD

**Discussion by fbaeumer** [danny-avila/LibreChat#3334] [Q&A]
Hello everyone, we have several models that are located on several base URLs but should all belong to one provider. Currently we can only consider them with single entries in librechat.yaml. Is there a function to combine multiple custom models with different base URLs? Like the grouping in Azure?

```
    - name: 'Test1'
      # For `apiKey` and `baseURL`, you can use environment variables that you define.
      # recommended environment variables:
      # Known issue: you should not use `OPENROUTER_API_KEY` as it will then override the `openAI` endpoint to use OpenRouter as well.
      apiKey: 'a'
      baseURL: 'http://172.17.0.1:9002/v1'
      models:
        default: ['Gemma-2-27b']
        fetch: false
      titleConvo: true
      titleModel: 'Gemma-2-27b'
      # Recommended: Drop the stop parameter from the request as Openrouter models use a variety of stop tokens.
      dropParams: ['stop']
      modelDisplayLabel: 'Gemma2'

    - name: 'Test2'
      # For `apiKey` and `baseURL`, you can use environment variables that you define.
      # recommended environment variables:
      # Known issue: you should not use `OPENROUTER_API_KEY` as it will then override the `openAI` endpoint to use OpenRouter as well.
      apiKey: 'a'
      baseURL: 'http://172.17.0.1:9001/v1'
      models:
        default: ['Qwen2 72B Instruct']
        fetch: false
      titleConvo: true
      titleModel: 'Qwen2 72B Instruct'
      # Recommended: Drop the stop parameter from the request as Openrouter models use a variety of stop tokens.
      dropParams: ['stop']
      modelDisplayLabel: 'Qwen2'

```
