### DISCUSSION TITLE
stream error

### DISCUSSION THREAD

**Discussion by portboy** [danny-avila/LibreChat#3335] [Troubleshooting]
I have an issue with the azureOpenAI config.

I always get this error ...
```
warn: [OpenAIClient.chatCompletion][stream] API error
error: [handleAbortError] AI response error; aborting request: 403 {"status":403,"title":"Forbidden","detail":"Streaming is not allowed. Set value: "stream":false"}
```

This is my Config:

```
   azureOpenAI:
    titleModel: "GAIA"
    plugins: true
    azureAssistants:
      capabilities: ["code_interpreter", "actions", "tools"]
    groups:
      - group: "riobs-group" # arbitrary name
        apiKey: "xxxx"
        instanceName: "robs-instance" # name of the resource group or instance
        version: "2023-12-01-preview"
        baseURL: "xxx"
        models:
          gpt-4-vision-preview:
            deploymentName: gpt-4-vision-preview
            version: "2024-02-15-preview"
          gpt-3.5-turbo:
            deploymentName: gpt-35-turbo
          gpt-3.5-turbo-1106:
            deploymentName: gpt-35-turbo-1106
          gpt-4:
            deploymentName: gpt-4
          gpt-4-1106-preview:
            deploymentName: gpt-4-1106-preview
          gpt-35-turbo-0301:
            deploymentName: gpt-35-turbo-0301
            version: "2023-05-15"
```

How could I handle this stream error..... ?
where could I set "stream":false"
