### DISCUSSION TITLE
(RAG System) Fix for the PPTX-Upload Bug

### DISCUSSION THREAD

**Discussion by fbaeumer** [danny-avila/LibreChat#3362] [Troubleshooting]
# Fix for PPTX File Handling in RAG System

## Issue
Some users are experiencing issues with the RAG system not correctly processing PPTX files (e.g., [#2462](https://github.com/danny-avila/LibreChat/discussions/2462)).

## Root Cause
The problem stems from the RAG system being started as Docker-Lite, which uses `requirements.lite.txt`. This file doesn't include the `python-pptx==0.6.23` package, which is present in the full `requirements.txt`.

## Solution
Manually installing the `python-pptx` package in the Docker container resolves the issue. However, a more permanent solution is to modify the `docker-compose.yml` file in LibreChat.

## Proposed Change
Update the `rag_api` section in `docker-compose.yml`:

```
yaml
rag_api:
  container_name: rag_api
  image: ghcr.io/danny-avila/librechat-rag-api-dev:latest
  environment:
    - DB_HOST=vectordb
    - RAG_PORT=${RAG_PORT:-8000}
  restart: always
  depends_on:
    - vectordb
  env_file:
    - .env
```

After making this change, run:

`docker-compose pull`

## Question for Maintainers

@danny-avila Is this issue already known? If not, would you consider implementing this fix?

Thank you for your attention to this matter.

Best regards,
Frederik
