### DISCUSSION TITLE
OpenAI TTS or STT now working at all

### DISCUSSION THREAD

**Discussion by carlosaln** [danny-avila/LibreChat#3433] [Help Wanted]
I have gone through the documentation and looked at some example config files on here, but I cannot seem to be able to get either TTS or STT to work using OpenAI. 

* My config file looks as follows:

```yaml
version: 1.1.5

speech:
  tts:
    openai:
      apiKey: 'my-key'
      model: 'tts-1'
      voices: ['alloy', 'echo', 'fable', 'onyx', 'nova', 'shimmer']
  stt:
    openai:
      apiKey: 'my-key'
      model: 'whisper-1'
```
* I have updated the docker compose override [as noted here](https://www.librechat.ai/docs/configuration/librechat_yaml/setup#docker-setup)
* I do `docker compose down` then `docker compose up` and I do get confirmation of my settings (screenshot 1), but then I open the settings on the UI and nothing seems to populate (I only get browser option) :-( I'm at a loss here, can anyone provide some guidance?

OS: Sonoma 14.5 / M3 macbook pro
Browser: Firefox 128 && Safari 

**Screenshot 1:**
![image](https://github.com/user-attachments/assets/ae089297-60dd-4d06-a126-aa63fbc06bf5)
**Screenshot 2:**
![image](https://github.com/user-attachments/assets/c08aaf2f-27f0-4dd0-8104-c8a0d259bddf)
