### DISCUSSION TITLE
Error on OpenAI TTS

### DISCUSSION THREAD

**Discussion by luandro** [danny-avila/LibreChat#3480] [Troubleshooting]
### What happened?

When trying to use OpenAI TTS I get this error:
`ReferenceError: caches is not defined`

I have `librechat.yaml` configured as the example:
```
speech:
  tts:
    openai:
      apiKey: 'sk-xxx'
      model: 'tts-1'
      voices: ['alloy', 'echo', 'fable', 'onyx', 'nova', 'shimmer']
```

### Steps to Reproduce

1. Deploy LibreChat
2. Add speech config
3. Try to use "Read Alout" on app

### What browsers are you seeing the problem on?

Chrome

### Screenshots

![image](https://github.com/user-attachments/assets/03594454-fc91-4d63-842b-9b876ce2fed9)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
