### DISCUSSION TITLE
[Question]: Cannot Use Assistant if Either modelSelect or sidePanel Is Set to False

### DISCUSSION THREAD

**Discussion by afunworm** [danny-avila/LibreChat#3525] [Troubleshooting]
### What is your question?

Is it possible to create a chat UI, without modelSelect or sidePanel, that uses a default selected Assistant?

### More Details

Hello.

I'd like to just have a simple chat interface with the default assistant (OpenAI) with no sidebar or model select or endpoint select. However, whenever modelSelect or sidePanel is configured to be `false`, the chat won't work since it'll say "Please select an Assistant from the Sidebar menu". Both of these options must be turned on for the Assistant to work, even though there's only 1 Assistant.

Is it possible to select an Assistant by default without modelSelect or sidePanel enabled?

Below is the full `librechat.yml` file:

```
version: 1.0.9

# Cache settings: Set to true to enable caching
cache: true

# File upload
fileStrategy: local

# Custom interface configuration
interface:
  endpointsMenu: false # Different types of bots
  modelSelect: true # If this is false, Assistant won't work
  parameters: false
  sidePanel: true # If this is false, Assistant won't work
  presets: false

# Definition of custom endpoints
endpoints:
  assistants:
    disableBuilder: true # Disable Assistants Builder Interface by setting to `true`
    pollIntervalMs: 1000  # Polling interval for checking assistant updates, default 2000
    timeoutMs: 180000
    supportedIds:
      - "asst_id_goes_here"
    retrievalModels:
      - "gpt-4o"
    capabilities:
      - "code_interpreter"
      - "retrieval"
      - "actions"
      - "tools"
      - "image_vision"
```

### What is the main subject of your question?

UI, Endpoints

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Hi thanks for reporting this. Still need to double check still but should be an easy fix

**Comment by danny-avila** [comment]
When investigating this, this seems to be an edge case with the initial page load state due to assistants not yet being available (fetched remotely from OpenAI).

Really for this setup, you should be using [modelSpecs](https://www.librechat.ai/docs/configuration/librechat_yaml/object_structure/model_specs#overview) but it runs into the same issue.

I'm going to slot this as an issue for v0.7.5 and will be taken care of with some other present issues with model specs.

**Reply by afunworm** [reply]
> When investigating this, this seems to be an edge case with the initial page load state due to assistants not yet being available (fetched remotely from OpenAI).
> 
> Really for this setup, you should be using [modelSpecs](https://www.librechat.ai/docs/configuration/librechat_yaml/object_structure/model_specs#overview) but it runs into the same issue.
> 
> I'm going to slot this as an issue for v0.7.5 and will be taken care of with some other present issues with model specs.

Thank you for the response. I tried using modelSpecs but I run into this message:

`Something went wrong. Here's the specific error message we encountered: Model spec mismatch`

Would you please let me know how to fix this? Below is the configuration:

```
modelSpecs:
  enforce: true
  prioritize: true
  list:
    - name: "my-stupid-bot"
      label: "My  Stupid Bot"
      description: "My stupid bot"
      iconURL: "https://example.com/icon.png"
      preset:
        default: true
        endpoint: "OpenAI"
        model: "gpt-4o"
        maxContextTokens: 128000 # Maximum context tokens
        max_tokens: 4096 # Maximum output tokens
        temperature: 0.2
        modelLabel: "Bryan's Stupid Bot"
        greeting: |
          This stupid AI bot can help you with most of the thing you want. It can also tell you jokes.
          To start, just type something.
        promptPrefix:
```

Thank you.
