### DISCUSSION TITLE
Enhancement: Ability to configure names for ElevenLabs voices in Speech menu

### DISCUSSION THREAD

**Discussion by jcdiv47** [danny-avila/LibreChat#3540] [Feature Requests & Suggestions]
### Motivation

<details>
<summary>In the current way of configuring ElevenLabs TTS service, the voice ids are listed in `voices`.</summary>

```yaml
speech:
  tts:
    elevenlabs:
      apiKey: '${TTS_API_KEY}'
      model: 'eleven_multilingual_v2'
      voices: ['202898wioas09d2', 'addwqr324tesfsf', '3asdasr3qrq44w', 'adsadsa']
```

</details>

However in practice the user may be confused or have a difficult time trying to select/switch a voice because the voice ids from ElevenLabs API are not so human readable

![screenshot-20240802-174647](https://github.com/user-attachments/assets/7752d8e2-4e6e-412f-a714-c796260b8408)

compared to say something like:

```yaml
voices: ['alloy', 'echo', 'fable', 'onyx', 'nova', 'shimmer']
```

I was wondering if the configuration could be something like a map rather than a list for configuring `voices`:

```yaml
voices:
  - '202898wioas09d2': 'David'
  - 'addwqr324tesfsf': 'John'
```

where the keys are the ElevenLabs voice ids and the values are more human-readable, memorable names for each voice.

**Comment by ndhanh96** [comment]
Hey how can you get the frontend to display elevenlabs voices? I added it to `librechat.yaml` file but it didn't show up in the speech setting, just `browser` and `edge` options. the elevenlabs key is already in `.env` file. 
```
# Configuration version (required)
version: 1.0.5
# This setting caches the config file for faster loading across app lifecycle
cache: true

registration:
  socialLogins: ["discord", "facebook", "github", "google", "openid"]
  speech:
    tts:
      elevenlabs:
        apiKey: '${TTS_API_KEY}'
        model: 'eleven_multilingual_v2'
        voices: ['202898wioas09d2', 'addwqr324tesfsf', '3asdasr3qrq44w', 'adsadsa']

```

**Reply by kukoboris** [reply]
You need to add Speech Tab Menu
<img width="740" alt="изображение" src="https://github.com/user-attachments/assets/35b3e8e4-3b26-47b7-873c-9b917bbee35c">

Look at https://www.librechat.ai/docs/configuration/stt_tts

**Reply by ndhanh96** [reply]
I did, but it didn't work at all, after editing the `librechat.yaml` file did you run any command? 
```
# Configuration version (required)
version: 1.0.5
# This setting caches the config file for faster loading across app lifecycle
cache: true

registration:
  socialLogins: ["discord", "facebook", "github", "google", "openid"]
  speech:
    speechTab:
      conversationMode: true
      advancedMode: false
      speechToText:
        engineSTT: "external"
        languageSTT: "English (US)"
        autoTranscribeAudio: true
        decibelValue: -45
        autoSendText: 0
      textToSpeech:
        engineTTS: "external"
        voice: "alloy"
        languageTTS: "en"
        automaticPlayback: true
        playbackRate: 1.0
        cacheTTS: true
    tts:
      elevenlabs:
        apiKey: '${TTS_API_KEY}'
        model: 'eleven_multilingual_v2'
        voices: ['202898wioas09d2', 'addwqr324tesfsf', '3asdasr3qrq44w', 'adsadsa']
```

**Reply by kukoboris** [reply]
voice: "alloy" - is not a ElevenLabs voice. Try to change

**Reply by ndhanh96** [reply]
can you share your `librechat.yaml` file ? appreciate

**Reply by ndhanh96** [reply]
I figure the problem you need to put speech at the root, in the document they put it below `registration`.

**Reply by kukoboris** [reply]
I do not use ElevenLabs, but anyway
```yaml
# Example Registration Object Structure (optional)
registration:
  socialLogins: ['github', 'google', 'discord', 'openid', 'facebook']
  allowedDomains:
  - "gmail.com"

speech:
   tts:
     openai:
       apiKey: '${TTS_API_KEY}'
       model: 'tts-1'
       voices: ['alloy', 'echo', 'fable', 'onyx', 'nova', 'shimmer']
   speechTab:
    conversationMode: true
    advancedMode: false
    speechToText:
      engineSTT: "external"
      languageSTT: "English (US)"
      autoTranscribeAudio: true
      decibelValue: -45
      autoSendText: 0
    textToSpeech:
      engineTTS: "external"
      voice: "alloy"
      languageTTS: "en"
      automaticPlayback: true
      playbackRate: 1.0
      cacheTTS: true   
```
