### DISCUSSION TITLE
Container crash on v0.7.4: There was an uncaught error: Cannot read properties of undefined (reading 'toLowerCase')

### DISCUSSION THREAD

**Discussion by rnavarroz** [danny-avila/LibreChat#3700] [Troubleshooting] [answered]
These are the steps to reproduce the error on v0.7.4
```
git clone https://github.com/danny-avila/LibreChat.git
git checkout tags/v0.7.4
cp .env.example .env
cp docker-compose.override.yml.example docker-compose.override.yml
```
Edit docker-compose.override.yml
```
services:
# # LOCAL BUILD
  api:
    image: librechat
    build:
      context: .
      target: node
    restart: no
```
Edit Dockerfile
```
#CMD ["npm", "run", "backend"]
CMD ["node", "api/server/index.js"]
```

```
docker compose build
docker compose up -d
docker compose logs api --follow
```
request to http://localhost:3080
You are getting:
```
error: There was an uncaught error: Cannot read properties of undefined (reading 'toLowerCase')
```
