### DISCUSSION TITLE
[Question]: Change logo, color and images

### DISCUSSION THREAD

**Discussion by rivindubandara** [danny-avila/LibreChat#3706] [Q&A] [answered]
### What is your question?

I want to change the main logo, the color of the ui and also the chatgpt logo
![image](https://github.com/user-attachments/assets/6a0835dd-adf6-45c2-9c46-956e8a351a46)
![image](https://github.com/user-attachments/assets/d88528e8-c3e9-44dc-828c-38c0b31a3979)
![image](https://github.com/user-attachments/assets/5ba41fe3-e744-4986-b3f1-b353316cb9f4)
![image](https://github.com/user-attachments/assets/8a0a92a3-e0c0-461e-bcdf-1a90b17b41e6)

### More Details

What I have done to change the colors temporarily is override the root colors however, sometimes when i refresh it doesnt stick.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by berry-13** [comment]
you can change logo of the endpoint by creating a custom endpoint. You can modify the logo by changing the logo.svg in `client/public/assets`. What you did with the css it's pretty good, it's more likely to be a cache issue, try disabling cache in the inspect network tab and also test the changes on a fresh browser

**Comment by berry-13** [comment, marked as answer]
@rivindubandara If you want to set a global "preset" for everyone, use a [modelSpec](https://www.librechat.ai/docs/configuration/librechat_yaml/object_structure/model_specs)., where you can image and custom instructions

**Comment by DanielHay17** [comment]
Hey, whenever I change the logo in client/public/assets, it never updates when deployed via docker. Does anyone know why?

**Reply by joseph-holland** [reply]
Are you rebuilding the image or just using the deploy-compose.yml?  If deploy with docker compose you should look into the docker-override docs here https://www.librechat.ai/docs/configuration/docker_override

This will allow you to pass your own custom logos, etc. into the built image without having to rebuild it yourself.
```
version: '3.4'
 
services:
  api:
    volumes:
      - ./client/public/assets/logo.svg:/app/client/public/assets/logo.svg
      - etc....
```

**Comment by DanielHay17** [comment]
I have this and no version, I will try yours 

services:
  api:
    volumes:
      - ./client/public/assets:/app/client/public/assets
      - type: bind
        source: ./librechat.yaml
        target: /app/librechat.yaml

**Reply by joseph-holland** [reply]
This didn't work for me as there are some .js files loaded in on start or something.  I had to specify each individual file.

**Reply by DanielHay17** [reply]
When I make the edits to the override file do I do it with nano or in the text editor and push it to my fork?

**Reply by joseph-holland** [reply]
Either _should_ work, but be aware of line endings (lf vs crlf) if you're editing in Windows.  I'm just editing using nano on the machine iteself and then pushing changes to my git fork.

This is my override file currently:
```
version: '3.4'

services:
  api:
    volumes:
      - ./client/public/assets/favicon-16x16.png:/app/client/public/assets/favicon-16x16.png
      - ./client/public/assets/favicon-32x32.png:/app/client/public/assets/favicon-32x32.png
      - ./client/public/assets/favicon-16x16.png:/app/client/dist/assets/favicon-16x16.png
      - ./client/public/assets/favicon-32x32.png:/app/client/dist/assets/favicon-32x32.png
      - ./client/public/assets/logo.svg:/app/client/dist/assets/logo.svg
      - ./client/public/assets/custom_icon.png:/app/client/dist/assets/custom_icon.png
      - ./client/public/assets/apple-touch-icon-180x180.png:/app/client/public/assets/apple-touch-icon-180x180.png
      - ./client/public/assets/apple-touch-icon-180x180.png:/app/client/dist/assets/apple-touch-icon-180x180.png
      - ./client/public/assets/maskable-icon.png:/app/client/public/assets/maskable-icon.png
      - ./client/public/assets/maskable-icon.png:/app/client/dist/assets/maskable-icon.png
      - ./client/manifest.webmanifest:/app/client/dist/manifest.webmanifest
```

I've also copied the existing manifest.webmanifest and edited it to change the title used by Android and Apple devices when saving the site to homescreen.

I reference the custom_icon.png from my modelSpec too.

I hope this helps.

**Reply by InvaderJ** [reply]
@joseph-holland Hello! You're the only one that I could find who successfully changed the apple-touch-icon-180x180.png via overrides, and I'm hoping you can help me out. Posted this on Discord as well.

I'm running LibreChat via DigitalOcean droplet, running Ubuntu, using the Docker image provided in the LibreChat documentation. My goal is to replace a few of the assets, most importantly the apple-touch-icon-180x180.png. I've yet to succeed. 

My current overrides file, located in ~/LibreChat, contains: 

```
services:
  api:
    volumes:
            - /home/justin/icons/apple-touch-icon-180x180.png:/home/justin/LibreChat/client/public/assets/apple-touch-icon-180x180.png
```

(I tried using the path order and type in your example above, but that didn't work for me. So this version is my latest attempt. A few places mentioned that the order for overrides should be host:docker hence my switching it like this.) 

I bring up Docker by specifying the overrides file:

`sudo docker-compose -f ./deploy-compose.yml -f docker-compose.override.yml up -d`

This command threw an error at me before for malformed paths, so I at least know this is reading the overrides file.

But once everything is up and running… nothing is overridden. It still serves the default image, not the one I'm specifying.

Any advice you might have would be greatly appreciated!  :)

**Reply by InvaderJ** [reply]
Some progress! Finally had success with a path structure as follows: 

```
    - /home/justin/icons/apple-touch-icon-180x180.png:/app/client/public/assets/apple-touch-icon-180x180.png
    - /home/justin/icons/apple-touch-icon-180x180.png:/app/client/dist/assets/apple-touch-icon-180x180.png
```

This results in showing my custom icon in certain views, but, the icon that is shown when saving the site to the Home screen on iOS is still the original LibreChat one. Wondering if you had to troubleshoot that specific case. Thanks again in advance for any insight!

**Reply by joseph-holland** [reply]
Let me check my install tomorrow and get back to you.

**Reply by joseph-holland** [reply]
Here is my docker-compose.override.yml file contents:
```
version: '3.4'

services:
  api:
    volumes:
      - ./client/public/assets/favicon-16x16.png:/app/client/public/assets/favicon-16x16.png
      - ./client/public/assets/favicon-32x32.png:/app/client/public/assets/favicon-32x32.png
      - ./client/public/assets/favicon-16x16.png:/app/client/dist/assets/favicon-16x16.png
      - ./client/public/assets/favicon-32x32.png:/app/client/dist/assets/favicon-32x32.png
      - ./client/public/assets/logo.svg:/app/client/dist/assets/logo.svg
      - ./client/public/assets/custom_icon.png:/app/client/dist/assets/custom_icon.png
      - ./client/public/assets/apple-touch-icon-180x180.png:/app/client/public/assets/apple-touch-icon-180x180.png
      - ./client/public/assets/apple-touch-icon-180x180.png:/app/client/dist/assets/apple-touch-icon-180x180.png
      - ./client/public/assets/maskable-icon.png:/app/client/public/assets/maskable-icon.png
      - ./client/public/assets/maskable-icon.png:/app/client/dist/assets/maskable-icon.png
      - ./client/manifest.webmanifest:/app/client/dist/manifest.webmanifest
      - ./client/new_index.html:/app/client/dist/index.html
```

I can't remember which one worked to change the icon for the saved webapp thing, but I think it was something to do with the ./client/manifest.webmanifest or something
`{"name":"CustomName Chat","short_name":"CustomName Chat","start_url":"/","display":"standalone","background_color":"#000000","lang":"en","scope":"/","theme_color":"#009688","icons":[{"src":"/assets/favicon-32x32.png","sizes":"32x32","type":"image/png"},{"src":"/assets/favicon-16x16.png","sizes":"16x16","type":"image/png"},{"src":"/assets/apple-touch-icon-180x180.png","sizes":"180x180","type":"image/png"},{"src":"/assets/maskable-icon.png","sizes":"512x512","type":"image/png","purpose":"maskable"}]}`

I hope this helps @InvaderJ, sorry for not getting back sooner.

**Reply by InvaderJ** [reply]
@joseph-holland No sorries allowed! This is hugely helpful, thank you so much. I managed to solve my PWA icon issue. 

Of course the next hurdle, which is technically answered by your own manifest content, is the name of the PWA. I've changed it in vite.config.ts, no dice. I then made an override to try and force my own vote.config.ts in, no dice. And, I changed the title in index.html and have an override *there* as well. 

My manifest.webmanifest always comes back with the original "LibreChat" name for the PWA. 

Wondering if there was anything else you did to get the PWA title changed? I see you are forcing your own manifest.webmanifest. I'm still assuming Vite would generate properly against its own config file but that seems not to be the case. Hmm.

Thanks again!

**Reply by joseph-holland** [reply]
I think I also had to create a custom index.html too and override the default.  AFAIK when I was looking at this the ts file wouldn't be processed properly because we're not building it, don't quote me on that 😁.

The answer is definitely in the list above.  Also I started from the first line down, so the index.html was the last file I modified, so I'm 99% sure that was it.  I think it was as simple at the title attribute.

**Reply by joseph-holland** [reply]
Make sure the modified manifest file is being put in the correct destination folder too.  I think something like that tripped me up also.

**Reply by joseph-holland** [reply]
Make sure to clear cache too or something.  I think when I was originally hitting this, even if I removed the PWA icon from the homescreen when i added it back it kept the old name.  I think I had to go into the site in the browser and remove any files from that site to fix this.  It's been about six months since I hit these issues, so I can't fully remember.

**Comment by mlin01** [comment]
I have the same issue to change the background color on the login page and I am new to react app.
Can someone give detail instructions?  Thanks in advance!

**Comment by kamaldua65** [comment]
i am totally lost. i tried various settings in docker override but unable to make it work. I am using remote server as per https://www.librechat.ai/docs/remote/docker_linux

here is what file structure i have on my server.
![image](https://github.com/user-attachments/assets/3cd61ffe-27aa-47fe-8d45-0ef785f3c637)

![image](https://github.com/user-attachments/assets/67e33e88-4a7d-4b59-8c99-6f9adc7e5102)

 this is what i am adding to docker override, ( i have even tried different settings as per above posts). 
  api:
    volumes:
    - ./librechat.yaml:/app/librechat.yaml
    - ./assets/favicon-16x16.png:/app/assets/favicon-16x16.png
    - ./assets/favicon-32x32.png:/app/assets/favicon-32x32.png
    - ./assets/logo.svg:/app/assets/logo.svg
also if i add mapping to custom file name i get 404 error when try to access it directly.

Any suggestions

**Comment by omarnadhim** [comment]
I changed the logo icon but it didn''t reflect at all !
@danny-avila

**Comment by estone81** [comment]
You need to use /app/client/dist/assets not /app/assets. Like so.

- ./logo.svg:/app/client/dist/assets/logo.svg

**Reply by omarnadhim** [reply]
I edit it like this 
- ./logo.svg:/root/LibreChat/client/dist/assets/logo.svg
but mothing also happened still the icon not changed in the tab and also in the home page of the login 
@estone81

**Reply by joseph-holland** [reply]
One tricky thing I found here too is that your browser can cache the old logo also.  I found some strange behaviour like that when originally testing this.  Try in a new private window, etc.

**Reply by estone81** [reply]
and your new logo.svg needs to be your base /LibreChat folder. You also did /root instead of /app. and then this should be part of the docker compose override file.

**Comment by kamaldua65** [comment]
nothing works, and i believe this is due to remote server installation, as app is already built by danny  and logo gets overwritten from compiled version every time.

here is from remote server installation page:
Quote
Note: this is using a special compose file optimized for this deployed environment. If you would like more configuration here, you should inspect the deploy-compose.yml and Dockerfile.multi files to see how they are setup. We are not building the image in this environment since it’s not enough RAM to properly do so. Instead, we pull the latest dev-api image of librechat, which is automatically built after each push to main.
unQuote

**Reply by estone81** [reply]
I'm not sure. This is my docker compose override file and it works for me. I also start via sudo docker compose -f deploy-compose.yml -f docker-compose.override.yml

services:
   api:
     volumes:
     - type: bind
       source: ./librechat.yaml
       target: /app/librechat.yaml
     - ./apple-touch-icon-180x180.png:/app/client/dist/assets/apple-touch-icon-180x180.png
     - ./apple-touch-icon-180x180.png:/app/client/dist/assets/favicon-16x16.png
     - ./apple-touch-icon-180x180.png:/app/client/dist/assets/favicon-32x32.png
     - ./logo.svg:/app/client/dist/assets/logo.svg
     - ./button-arrow.svg:/app/client/dist/assets/button-arrow.svg
     - ./index.html:/app/client/dist/index.html

**Comment by liHai001** [comment]
Hi, did you solve this problem. I also can't change logo, when i change the file "docker-compose.override.yml" like this:
and finally run command: `docker compose up`
```
services:
  api:
    volumes:
       - type: bind
         source: ./librechat.yaml
         target: /app/librechat.yaml
       - ./librechat.yaml:/app/librechat.yaml
       - ./client/public/assets/favicon-16x16.png:/app/client/public/assets/favicon-16x16.png
       - ./client/public/assets/favicon-32x32.png:/app/client/public/assets/favicon-32x32.png
       - ./client/public/assets/apple-touch-icon-180x180.png:/app/client/public/assets/apple-touch-icon-180x180.png
```
