### DISCUSSION TITLE
specific assistant endpoint using custom endpoint

### DISCUSSION THREAD

**Discussion by woojuini** [danny-avila/LibreChat#3725] [Q&A] [answered]
I want to expose one of the assistants using as an endpoint.
```
librechat.yaml: |
    version: 1.1.5
    endpoints:
      custom:
      - name: 'search nwiki'
         apiKey: 'apikey'
         baseURL: 'https://api.openai.com/v1/assistants/{my assistant id}'
         models:
           default: ['gpt-4o']
``` 

expose as I wanted
![image](https://github.com/user-attachments/assets/7c7af6ae-63d3-4b88-b5ae-5a3865092fd5)

but when i try to use , then it doesn't work as assistant
