### DISCUSSION TITLE
[Bug]: Cohere API returns 404 NotFoundError

### DISCUSSION THREAD

**Discussion by haoblackj** [danny-avila/LibreChat#3727] [Troubleshooting]
### What happened?

After upgrading to the latest version of LibreChat, I encountered an issue where requests to the Cohere API consistently return a 404 error. Downgrading to a previous version(0.7.3) of LibreChat resolves the issue, so this appears to be a bug related to the latest release.

I confirmed that the Cohere API key and the base URL are correct. The issue seems to be related specifically to the latest version of LibreChat. The issue was not present in v0.7.3. The problem persists across multiple environments.

Environment:
Docker: Yes
Image: ghcr.io/danny-avila/librechat-api:latest

The following configuration is set in librechat.yaml, and the COHERE_API_KEY is confirmed to be correct:
```yaml
endpoints:
  custom:
  - name: "cohere"
    apiKey: "${COHERE_API_KEY}"
    baseURL: "https://api.cohere.ai/v1"
    models:
      default: ["command-r","command-r-plus","command-light","command-light-nightly","command","command-nightly"]
      fetch: false
    modelDisplayLabel: "cohere"
    titleModel: "command"
    dropParams: ["stop", "user", "frequency_penalty", "presence_penalty", "temperature", "top_p"]
```

### Steps to Reproduce

1. Configure LibreChat to use the Cohere API.
2. Attempt to make a request to the Cohere API.
3. The request fails with a 404 NotFoundError.

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### Relevant log output

```shell
{"body":{},"level":"error","message":"[handleAbortError] AI response error; aborting request: NotFoundError\nStatus code: 404\nBody: {}","stack":"Error: NotFoundError\nStatus code: 404\nBody: {}\n    at CohereClient.<anonymous> (/app/api/node_modules/cohere-ai/Client.js:119:31)\n    at Generator.next (<anonymous>)\n    at fulfilled (/app/api/node_modules/cohere-ai/Client.js:31:58)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","statusCode":404}
```

### Screenshots

![image](https://github.com/user-attachments/assets/b655f900-8537-4b2c-961f-72a1f8ab2347)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by berry-13** [comment]
I'm using the latest image, and it's working fine:

![image](https://github.com/user-attachments/assets/81cf803e-c5a3-449b-9fb0-660ee5c1bab5)


configuration (it's exactly the same as yours)
```yaml
    - name: "cohere"
      apiKey: "${COHERE_API_KEY}"
      baseURL: "https://api.cohere.ai/v1"
      models:
        default: ["command-r","command-r-plus","command-light","command-light-nightly","command","command-nightly"]
        fetch: false
      modelDisplayLabel: "cohere"
      titleModel: "command"
      dropParams: ["stop", "user", "frequency_penalty", "presence_penalty", "temperature", "top_p"]
```
