### DISCUSSION TITLE
Invalid model name passed in model

### DISCUSSION THREAD

**Discussion by iwgth** [danny-avila/LibreChat#3771] [Troubleshooting] [answered]
I am using a model from aws bedrock and when answering my question in chat, I get an error. 
`error: [handleAbortError] AI response error; aborting request: 400 {"error":"chat_completion: Invalid model name passed in model=llama3-70b"}`

The documentation I referred to:
1.https://litellm.vercel.app/docs/proxy/quick_start - litellm-config
2. https://github.com/aws-samples/bedrock-litellm/blob/main/litellm/proxy_config.yaml - librechat

can you tell me what could be wrong? 

_litellm-config_
```
model_list:
  https://litellm.vercel.app/docs/proxy/quick_start

  AWS Bedrock - Meta Llama

  - model_name: llama2-70b
    litellm_params:
      model: "bedrock/meta.llama2-70b-chat-v1"
      #aws_region_name: us-east-1
      #aws_access_key_id: A...
      #aws_secret_access_key: 

  - model_name: llama3-8b
    litellm_params:
      model: "bedrock/meta.llama3-8b-instruct-v1:0"
       #aws_region_name: us-east-1
       #aws_access_key_id: A...
       #aws_secret_access_key: 

  - model_name: llama3-70b
    litellm_params:
      model: "bedrock/meta.llama3-70b-instruct-v1:0"
      #aws_region_name: us-east-1
      #aws_access_key_id: A...
      #aws_secret_access_key: 

```

_librechat_
```
version: 1.0.8
cache: true
interface:
  #Privacy policy settings
  privacyPolicy:
    externalUrl: 'https://librechat.ai/privacy-policy'
    openNewTab: true
  #Terms of service
  termsOfService:
    externalUrl: 'https://librechat.ai/tos'
    openNewTab: true
registration:
  socialLogins: ["discord", "facebook", "github", "google", "openid"]
endpoints:
  custom:
    - name: "Lite LLM"
      # A place holder - otherwise it becomes the default (OpenAI) key
      # Provide the key instead in each "model" block within "litellm/litellm-config.yaml"
      apiKey: "sk-from-config-file"
      # See the required changes above in "Start LiteLLM Proxy Server" step.
      baseURL: "http://host.docker.internal:4000"
      # A "default" model to start new users with. The "fetch" will pull the rest of the available models from LiteLLM
      # More or less this is "irrelevant", you can pick any model. Just pick one you have defined in LiteLLM.
      models:
        default: [llama3-8b,
          llama3-70b, llama2-70b]
        fetch: true
      titleConvo: true
      titleModel: "llama3-8b"
      summarize: false
      summaryModel: "llama3-8b"
      forcePrompt: false
      modelDisplayLabel: "Lite LLM"
```
