### DISCUSSION TITLE
[Question]: can't setup librechat.yaml to work with azureopani for love nor for money.

### DISCUSSION THREAD

**Discussion by thisismygitrepo** [danny-avila/LibreChat#3811] [Troubleshooting]
### What is your question?

I had 4 hours long session trying to configure librechat.yaml to work with my businsess subscription of azureopenai.
I reached a point where the terminal log messages no longer showing any complaint about the syntax of the file. But, I still get `No key found. Please provide a key and try again.` no matter what model I choose.

### More Details

my `.env` is not touched.
My `librechat.yaml` is 

```yaml

endpoints:
  azureOpenAI:
    # Endpoint-level configuration
    titleModel: "shcc-azure-gpt4-turbo"
    plugins: true
    assistants: true
    groups:
    # Group-level configuration
    - group: "readacted1"
      apiKey: "redacted2"
      baseURL: "redacted1.openai.azure.com"
      instanceName: "redacted1"
      version: "1106-Preview"  # tried everything else to no avail.
      deploymentName: "gpt-4-turbo-default"
      assistants: true
      # Model-level configuration
      models:
        # default: ['gpt-4-turbo-default']
        # gpt-4:
        #   deploymentName: "gpt-4-turbo-default"
        #   version: "2024-03-01-preview"
        assistants: true
        gpt-4-turbo: true

```

This is at least one of hundereds of variants. In retrospect, I think the designers overcomplicated the config with the group concept. Any help would be appreciated.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Exioness** [comment]
dont use both instance name and base url, just one... this is how my setup looks

```
version: 1.0.5
cache: true
endpoints:
  azureOpenAI:
    assistants: true
    titleConvo: true
    titleModel: "gpt-4o-mini"
    summarize: true
    summaryModel: "gpt-4o-mini"
    plugins: true
    groups:
    - group: "nameOfMyResource"
      apiKey: "api_key"
      assistants: true
      instanceName: "nameOfMyResource"
      version: "2024-07-01-preview"
      models:
        gpt-4o:
          deploymentName: "gpt-4o_2"
          version: "2024-07-01-preview"
        gpt-4o-mini:
          deploymentName: "gpt-4o-mini"
          version: "2024-07-01-preview"
        text-embedding-3-large:
          deploymentName: "text-emb-3"
          version: "2024-07-01-preview"
```

**Reply by danny-avila** [reply]
There are a few issues with the provided configuration. Let's go through them:

1. The `version` field at the group level should be a full date-based version string. Instead of "1106-Preview", it should be something like "2024-03-01-preview".

Human in the loop: Check the Azure API version you wish to use: https://learn.microsoft.com/en-us/azure/ai-services/openai/reference#rest-api-versioning

3. The `models` section is not properly formatted. Each model should be a key-value pair, where the key is the model identifier and the value is either `true` or an object with additional configurations.

4. The `assistants` field is incorrectly placed within the `models` section.

5. The `titleModel` at the endpoint level refers to a model that is not defined in the configuration.

Here's a corrected version of the configuration:

```yaml
endpoints:
  azureOpenAI:
    # Endpoint-level configuration
    titleModel: "gpt-4-turbo"  # Changed to match the defined model
    plugins: true
    assistants: true
    groups:
    # Group-level configuration
    - group: "readacted1"
      apiKey: "redacted2"
      baseURL: "https://redacted1.openai.azure.com"  # Added 'https://' prefix
      instanceName: "redacted1"
      version: "2024-03-01-preview"  # Corrected version format
      deploymentName: "gpt-4-turbo-default"
      assistants: true
      # Model-level configuration
      models:
        gpt-4-turbo: 
          deploymentName: "gpt-4-turbo-default"
          version: "2024-03-01-preview"
```

Key changes:

1. Corrected the `version` format.
2. Removed the commented-out lines in the `models` section.
3. Properly formatted the `gpt-4-turbo` model configuration.
4. Removed the misplaced `assistants: true` from the `models` section.
6. Changed the `titleModel` to match the defined model.
7. Added the 'https://' prefix to the `baseURL`.

This configuration should now be valid according to the provided documentation. Make sure to replace "redacted1" and "redacted2" with your actual Azure instance name and API key, respectively.

https://demo.librechat.ai/share/wjliorrN3XGQHVsv-6NoC

**Reply by thisismygitrepo** [reply]
@danny-avila 
I copy-catted your kindly provided setup, but I was not lucky.

Extra-content:
This is my azure deployment webpage

![image](https://github.com/user-attachments/assets/de03ff86-eb4b-4d8c-bc19-9dfe52eb4550)

Lastly, my irreducibly simple config

```yaml

endpoints:
  azureOpenAI:
    # Endpoint-level configuration
    titleModel: "gpt-4-turbo-model"
    plugins: true
    assistants: true
    groups:
    # Group-level configuration
    - group: "redacted1"
      apiKey: "redacted2"
      baseURL: "redacted1.openai.azure.com"
      instanceName: "redacted1"
      version: "2023-11-06-Preview"
      deploymentName: "gpt-4-turbo-default"
      assistants: true
      # Model-level configuration
      models:
        gpt-4-turbo-model:
          deploymentName: "gpt-4-turbo-default"
          version: "2023-11-06-Preview"
```

**Reply by danny-avila** [reply]
try removing the `baseURL` actually.. This is not necessary when you're using the default `openai.azure.com` domain

**Reply by danny-avila** [reply]
I should add a warning about that

**Reply by danny-avila** [reply]
also double check the API version, seems wrong. try `2024-03-01-preview`

**Reply by thisismygitrepo** [reply]
@danny-avila 

still no luck.

I should probably report this

```shell
LibreChat         | 2024-09-02 02:38:49 error: Config file YAML format is invalid: ENOENT: no such file or directory, op
en './librechat.yaml'                                                                                                   
LibreChat         | 2024-09-02 02:38:49 warn: Default value for CREDS_KEY is being used.                                
LibreChat         | 2024-09-02 02:38:49 warn: Default value for CREDS_IV is being used.                                 
LibreChat         | 2024-09-02 02:38:49 warn: Default value for JWT_SECRET is being used.                               
LibreChat         | 2024-09-02 02:38:49 warn: Default value for JWT_REFRESH_SECRET is being used.     
```

In a separate thread, you said that's not a bug, so I left it  as is.

Fronten-end-wise, I'm not sure if I'm meant to see the models I defined, but I only see those:

![image](https://github.com/user-attachments/assets/242899ba-ccb2-4a1d-9839-2addc911b59b)

Any of which, when chatting to, gives the backend error:

```shell
LibreChat         | 2024-09-02 02:40:58 error: [handleAbortError] AI response error; aborting request: {"type":"no_user_
key"}                                                                                                                   
chat-meilisearch  | 2024-09-02T02:40:58.179582Z  INFO HTTP request{method=POST host="meilisearch:7700" route=/indexes/me
ssages/documents query_parameters= user_agent=node status_code=202}: meilisearch: close time.busy=549µs time.idle=2.36ms
chat-meilisearch  | 2024-09-02T02:40:58.195497Z  INFO index_scheduler::batch: document indexing done indexing_result=Doc
umentAdditionResult { indexed_documents: 1, number_of_documents: 62 }                                                   
chat-meilisearch  | 2024-09-02T02:40:58.197916Z  INFO index_scheduler: A batch of tasks was successfully completed with 
1 successful tasks and 0 failed tasks. 
```


```
endpoints:
  azureOpenAI:
    titleModel: "gpt-4-turbo-model"
    plugins: true
    assistants: true
    groups:
    - group: "redacted1"
      apiKey: "redacted2"
      instanceName: "redacted1"
      version: "2024-03-01-preview"
      deploymentName: "gpt-4-turbo-default"
      assistants: true
      models:
        gpt-4-turbo-model:
          deploymentName: "gpt-4-turbo-default"
          version: "2024-03-01-preview"
```

**Comment by krahnikblis** [comment]
@thisismygitrepo , in my (working) Azure setup i've got a few differences in the yaml you might try: the baseURL references the .env variable deployment name, i don't have the version parameters for the models, and for some reason i recall i needed to use the addparams method to put in token and temp, which i think get overridden by the individual model settings? i also put the api key in .env, and reference it in the yaml:
```yaml
  azureOpenAI:
  # Enable use of Assistants with Azure
    assistants: false
    plugins: false
    titleConvo: true # enables auto-titling like the real one
    titleModel: gpt-4o-mini
    summarize: true
    summaryModel: gpt-4o-mini
    groups:
      - group: eastus # arbitrary name
        apiKey: ${OPENAI_API_KEY}
        # doc recommends using env vars for these 3:
        instanceName: Redacted # name of the resource group or instance
        version: "2024-02-01"
        baseURL: http://redacted:8000/openai/deployments/${DEPLOYMENT_NAME}
        # Mark this group as assistants compatible
        assistants: false
        addParams:
          max_tokens: 4000
          temperature: 0.7
          #stream: false # check if streaming still has issue
        # additionalHeaders:
        #   X-Custom-Header: value
        models:
          gpt-4o:
            deploymentName: gpt-4o
            # version: "2024-05-13" # this is not model version, this is this model's selection for api version
          gpt-4o-mini:
            deploymentName: gpt-4o-mini
            # version: "0613"
          gpt-4-preview:
            deploymentName: gpt-4
            # version: 0125-Preview
```
somewhere i remember seeing something about making sure a yaml file has a final newline after whatever last text, not sure if that's the ENOENT thing? and you do need to set up arbitrary values for the search and stuff - i used the provided keygen script from this repo. if you're using Docker and/or RAG-API, more fun configuring there too. basically, it's not surprising it's taking a number of hours (i spent a number of days, getting dockers and proxies and azure and yamls and such talking together correctly), but eventually the right combination of button-smashing will get it working.
