### DISCUSSION TITLE
LibreChat 0.7.5rc Docker Node Build

### DISCUSSION THREAD

**Discussion by reramjiawan** [danny-avila/LibreChat#3818] [Troubleshooting] [answered]
### What happened?

I am unable to create a local docker build since the new release.

I am using the docker.override.yaml

```
version: '3.4'

services:
   api:
     image: librechat
     build:
       context: .
       target: node
     volumes:
      - type: bind
        source: ./librechat.yaml
        target: /app/librechat.yaml
```

Vite seems stuck on transforming the modules. I don't know if this just a problem on my own machine or if others are facing the same issue.

### Steps to Reproduce

1. Use docker.override as shown above
2. docker-compose up
3. Docker is forever stuck same goes for a normal production build

### Screenshots

<img width="1871" alt="image" src="https://github.com/user-attachments/assets/f6b746a6-1cd7-43bd-9833-fe94ffa074d2">

<img width="566" alt="image" src="https://github.com/user-attachments/assets/0af02fd9-834e-4038-8c94-acbc6b2c12f1">

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
