### DISCUSSION TITLE
[Bug]: An error occurred when I used the includedTools: ["dalle"] environment variable

### DISCUSSION THREAD

**Discussion by sunsky89757** [danny-avila/LibreChat#3852] [Troubleshooting]
### What happened?

error: [loadAndFormatTools] Error initializing `CodeSherpa.js` tool; if it requires authentication, is the `override` field configured? Missing CODESHERPA_SERVER_URL environment variable.

### Steps to Reproduce

1. config docker-compose.override.yml file

```
version: '3.4'
 
services:
  api:
    volumes:
      - type: bind
        source: ./librechat.yaml
        target: /app/librechat.yaml
```

2. config librechat.yaml file

```
version: 1.1.5
includedTools: ["dalle"]
```

3. config .env

```
ENDPOINTS=openAI,gptPlugins
```

4. docker-compose up

![image](https://github.com/user-attachments/assets/a5698262-9294-4cc7-b974-e7415e212471)

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
