### DISCUSSION TITLE
[Question]: Working with files in the Azure Assistant endpoint stopped working

### DISCUSSION THREAD

**Discussion by dareima** [danny-avila/LibreChat#3963] [Troubleshooting] [answered]
### What is your question?

Today we've noticed that although we can upload files to the Azure Assistants endpoint, the files cannot be processed. This worked before.

The LibreChat container log states this error when we try to start a conversation with the Azure Assistant about the uploaded file.

`2024-09-09 17:32:16 2024-09-09 15:32:16 error: [/assistants/chat/] 400 Unknown parameter: 'messages[0].file_ids'.`

### More Details

Does this look like an issue with LibreChat or rather with Azure? It wouldn't be surprising if Microsoft is working on the assistants backend. It's in preview afterall.

We tried downgrading to LibreChat 0.7.4 but got the same error there as well.

Any help or suggestion what to check is appreciated, thank you.

### What is the main subject of your question?

Endpoints

### Screenshots

![Screenshot 2024-09-09 173653](https://github.com/user-attachments/assets/eb892050-1ab0-49de-b4e6-5e7cc233cebe)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
seems to be an azure issue (I don't have code interpreter enabled): 

![image](https://github.com/user-attachments/assets/dbbfd645-4043-4c84-bfb8-03d9777c8bf5)

**Reply by dareima** [reply]
@danny-avila thanks for your quick reply, much appreciated.
Can I ask, in which region is your Azure OpenAI endpoint where your assistant lives?

**Comment by ppatayane** [comment]
We have Sweden central region, 0.7.4 rc1 release, Azure Assistant works fine

**Comment by dareima** [comment, marked as answer]
Thank you everyone.

We were able to mitigate the issue and found out that a wrong API version used in the Azure model endpoints was the cause for our Azure assistants to stop working.

```
    groups:
      - group: "swe-central" # arbitrary name
        apiKey: "${AZURE_OPEN_AI_API_KEY}"
        assistants: true
        instanceName: "swe1234567890"
        version: "2024-05-01-preview"
        models:
          swe-gpt-4o:
            deploymentName: swe-gpt-4o
            version: "2024-02-15-preview" #<-- a wrong API version used here will break working with files in Azure assistants
```

**Reply by maxesse** [reply]
I have the same issue since today, I’m also using 2024-05-01-preview, set at the group level, with no api version specified for the models. Did you fix it by adding that even older version to the model entry or by removing it?

**Reply by dareima** [reply]
Yes. 2024-05-01-preview doesn’t work with the models in assistants. I’ve derived the February version from the Azure Chat playground for GPT-4o and Mini and that fixed the problem right away. You need to add it on model level to overwrite the group level version.

**Reply by maxesse** [reply]
Thanks a lot, just done it and now it all works fine again. While I was tinkering, out of curiosity I tried to use the 2024-08-01-preview version and, while it doesn't fix the assistant file upload, it actually allows assistants to work at a base level. The GA one 2024-06-01 breaks everything instead, retrieving the assistant list returns a 404.

**Reply by dareima** [reply]
@maxesse good info, thanks! Btw, we've figured out that our Azure OpenAI resource in the East US 2 region does in fact support the 2024-05-01-preview API version for the models. Assistants work well over there. Due to the region this isn't an option for us though.

**Reply by maxesse** [reply]
Yeah I'm in the same boat, locked to sweden central and north/west europe unfortunately. It's really annoying having all these inconsistencies between regions, api versions, and having to wonder every two weeks whether assistants stopped working because I did something, Microsoft did something, or Librechat changed something. Can't wait to switch to OpenAI tbh.

**Reply by dareima** [reply]
With you on that. Switching to OpenAI however can never be an option when we want to maintain conformity with EU regulations.
We're pretty glad there even is a provider like Microsoft offering powerful models in EU regions. As most of this is still in preview, it is kind of a hassle though.

**Reply by maxesse** [reply]
I actually spoke with them recently, and they said they're gonna open an EU datacenter this autumn - that will make them compliant. Agree that atm it's impossible since the prompts you send get load balanced anywhere in the world where there is capacity available.

**Reply by dareima** [reply]
Good to know, thanks for the update, Max. Appreciate this conversation!

**Reply by ppatayane** [reply]
While using Azure assistant - We are able to upload only via prompt and not via 'upload file' section under assistant menu (right had side). Is this the same case with you all as well? We are on sweden central and using May version for 4 o model since Aug is incompatible with Assistant

**Comment by AbidheshA** [comment]
Hi, I'm trying to add my Azure OpenAI credentials, but I'm getting an error. I've gone through the documentation, but I'm still a bit confused about what exactly I need to update in the .env file. Can you please assist me in resolving this issue?

**Reply by dareima** [reply]
> Hi, I'm trying to add my Azure OpenAI credentials, but I'm getting an error. I've gone through the documentation, but I'm still a bit confused about what exactly I need to update in the .env file. Can you please assist me in resolving this issue?

@AbidheshA to get you started you'll need two things:

- Your Azure OpenAI API key in `.env`
- An endpoint configuration in `librechat.yaml`

As for `.env` we're doing it like this (custom variable):

`AZURE_OPEN_AI_API_KEY=abcdefghijklmnop1234567890`

Example config In `librechat.yaml`

```
endpoints:
  azureOpenAI:
    titleModel: "current_model"
    plugins: true
    assistants: true
    groups:
      - group: "swe-central" # arbitrary name
        apiKey: "${AZURE_OPEN_AI_API_KEY}"
        assistants: true
        instanceName: "ai-aihubswe1234567890"
        version: "2024-05-01-preview"
        models:
          ai-hub-swe-gpt-4o:
            deploymentName: ai-hub-swe-gpt-4o
            version: "2024-02-15-preview"
```

That should give you a first glance at what's the minimum to get an Azure OpenAI endpoint up and running.

**Comment by ABHIJITH-EA** [comment]
@dareima I'm encountering the same issue and have tried multiple approaches as well as different assistant models. However, I'm still a bit confused about the availability of the models following the Azure documentation. 

I've shared my Azure configuration below. Could you please take a look and let me know what I'm doing wrong in the setup?

```
endpoints:
 azureOpenAI:
  assistants: true
  groups:
   - group: "wu-region-group"
     apiKey: "XXXXXX"
     instanceName: "YYYYYY"
     version: "2024-07-01-preview"
     assistants: false
     models:
      gpt-4o-mini:
       deploymentName: gpt-4o-mini
   - group: "eu-region-group"
     apiKey: "XXXXXX"
     instanceName: "YYYYYY"
     version: "2024-07-01-preview"
     assistants: true
     models:
      gpt-4o-mini-assistant:
       deploymentName: gpt-4o-mini
       version: "2024-05-01-preview"
   - group: "jp-region-group"
     apiKey: "XXXXXX"
     instanceName: "YYYYYY"
     assistants: false
     version: "2024-07-01-preview"
     models:
      gpt-4o:
       deploymentName: gpt-4o
   - group: "sc-region-group"
     apiKey: "XXXXXX"
     instanceName: "YYYYYY"
     assistants: false
     version: "2024-07-01-preview"
     models:
      gpt-4o-0806:
       deploymentName: gpt-4o
  plugins: true
  titleConvo: true
  titleModel: gpt-4o-mini
 azureAssistants:
    capabilities: ["code_interpreter", "actions", "tools"]
```

Any help would be greatly appreciated!
