### DISCUSSION TITLE
Read Aloud button does not work on Chrome

### DISCUSSION THREAD

**Discussion by rnavarroz** [danny-avila/LibreChat#4002] [Troubleshooting]
### What happened?

On v0.7.4 the read aloud button stops working. You can start a conversation and click on the "read aloud" button and nothing is listened. I verified on v0.7.3 works and on v0.7.5-rc2 persists the issue.

### Steps to Reproduce

1. Select a model
2. Ask a question
3. Click on "read aloud" icon/button

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Not enough information to reproduce, I've tried all TTS options and the read aloud button is playing audio for all of them (browser/edge/external)

![image](https://github.com/user-attachments/assets/d21157f4-04e4-4446-af89-97c7cd58c0a1)

**Reply by rnavarroz** [reply]
interesting, I decided to try on the demo librechat  https://librechat-librechat.hf.space/ as well. Watching the console logs show 'Selected voice not found'. That message I don't see on my instance but still the read aloud does not work.

![read-aloud](https://github.com/user-attachments/assets/ad43f8f9-52c1-4a3c-bbc2-87b42537adf9)

**Comment by rnavarroz** [comment]
Hi @danny-avila
if you don't mind could you share what settings/configuration on librechat are used in your screenshot.

**Reply by danny-avila** [reply]
```yaml
speech:
  tts:
    openai:
      voices: ['alloy', 'echo', 'fable', 'onyx', 'nova', 'shimmer']
      apiKey: '${OPENAI_API_KEY}'
      model: 'gpt-4o-mini-tts'
  stt:
    openai:
      apiKey: '${OPENAI_API_KEY}'
      model: 'whisper-1'
```
