### DISCUSSION TITLE
How to Set an API Key for Each User via the UI in Azure OpenAI

### DISCUSSION THREAD

**Discussion by kash203** [danny-avila/LibreChat#4028] [Q&A]
Could you please explain how to set an API key via the UI in Azure OpenAI? 
I tried setting user_provided for the apiKey like in the `ANTHROPIC_API_KEY`, `OPENAI_API_KEY` settings, but it didn’t work correctly.

**Comment by fuegovic** [comment]
In the .env file: 
```sh
AZURE_API_KEY=user_provided
```
![image](https://github.com/user-attachments/assets/c66c6df4-e4ac-426f-9db0-2ceefccdb3d0)

**Reply by kash203** [reply]
Thank you for your quick response!
I set `AZURE_API_KEY` to `.env` as`user_provided` and set configuration to `librechat.yml`, but it didn't stull work correctly.
(I have confirmed that it works as expected if I specify the API Key directly in librechat.yml.)

```yaml
  azureOpenAI:
    # Endpoint-level configuration
    titleModel: "current_model"
    plugins: false
    assistants: false
    groups:
    # Group-level configuration
    - group: "my-apim"
      apiKey: '${AZURE_API_KEY}'
      instanceName: "my-instance"
      version: "2024-06-01"
      models:
        gpt-4o-0513:
          deploymentName: gpt-4o
          version: "2024-06-01"
      baseURL: "https://xxx/openai/deployments/gpt-4o"
```

The relevant logs are as folow:
```
LibreChat      | 2024-09-13 --:--:-- error: [handleAbortError] AI response error; aborting request: {"type":"no_user_key"}
LibreChat      | 2024-09-13 --:--:-- warn: Invalid conversation ID: null
LibreChat      | 2024-09-13 --:--:-- info: ---`saveMessage` context: undefined
LibreChat      | 2024-09-13 --:--:-- info: ---Invalid conversation ID Params: {
LibreChat      |   "sender": "GPT-4",
LibreChat      |   "messageId": "xxxx",
LibreChat      |   "conversationId": null,
LibreChat      |   "parentMessageId": "00000000-0000-0000-0000-000000000000",
LibreChat      |   "unfinished": false,
LibreChat      |   "error": true,
LibreChat      |   "final": true,
LibreChat      |   "text": "{\"type\":\"no_user_key\"}",
LibreChat      |   "isCreatedByUser": false,
LibreChat      |   "user": "xxxx"
LibreChat      | }
```

The relevant part of `.env` is below:
```sh
#============#
# Azure      #
#============#

# Note: these variables are DEPRECATED
# Use the `librechat.yaml` configuration for `azureOpenAI` instead
# You may also continue to use them if you opt out of using the `librechat.yaml` configuration

# AZURE_OPENAI_DEFAULT_MODEL=gpt-3.5-turbo # Deprecated
# AZURE_OPENAI_MODELS=gpt-3.5-turbo,gpt-4 # Deprecated
# AZURE_USE_MODEL_AS_DEPLOYMENT_NAME=TRUE # Deprecated
AZURE_API_KEY=user_provided # Deprecated
# AZURE_OPENAI_API_INSTANCE_NAME= # Deprecated
# AZURE_OPENAI_API_DEPLOYMENT_NAME= # Deprecated
# AZURE_OPENAI_API_VERSION= # Deprecated
# AZURE_OPENAI_API_COMPLETIONS_DEPLOYMENT_NAME= # Deprecated
# AZURE_OPENAI_API_EMBEDDINGS_DEPLOYMENT_NAME= # Deprecated
# PLUGINS_USE_AZURE="true" # Deprecated
```

Version of LibreChat: v0.7.5-rc1

Thank you.
