### DISCUSSION TITLE
[Question]: How can i get this running on AWS via docker

### DISCUSSION THREAD

**Discussion by noobskies** [danny-avila/LibreChat#406] [Q&A]
### Contact Details

t.noobskie@gmail.com

### What is your question?

how exactly can I expose this with docker on aws?

I have changed the following

```
version: "3.4"

services:
  client:
    image: nginx-client
    build:
      context: .
      target: nginx-client
    restart: always
    ports:
      - 3080:80
    volumes:
      - /client/node_modules
    depends_on:
      - api
  api:
    container_name: chat-clone
    ports:
      - 9000:3080         
```

what else do I need changed?

### More Details

do I need to change anything in the .env?

### What is the main subject of your question?

Installation

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
