### DISCUSSION TITLE
How to modify UI color ?

### DISCUSSION THREAD

**Discussion by RAPHCVR** [danny-avila/LibreChat#4078] [Help Wanted]
Hey, I am trying to do as mentioned in this thread: https://github.com/danny-avila/LibreChat/discussions/3706
Indeed, I would need to change colors in the UI. But I can't manage to change the primary color.
Having this file:
```css
/* Custom Variables */
:root {
  --white: #fff;
  --black: #000;
  --gray-20: #fbeaea;  /* light red for gray.20 */
  --gray-50: #f8dada;  /* light red for gray.50 */
  --gray-100: #f5caca; /* light red for gray.100 */
  --gray-200: #f2baba; /* light red for gray.200 */
  --gray-300: #eb8a8a; /* red for gray.300 */
  --gray-400: #c56161; /* darker red for gray.400 */
  --gray-500: #993d3d; /* dark red for gray.500 */
  --gray-600: #732d2d; /* dark red for gray.600 */
  --gray-700: #592323; /* very dark red for gray.700 */
  --gray-800: #411919; /* very dark red for gray.800 */
  --gray-850: #341414; /* custom dark red for gray.850 to match gradient needs */
  --gray-900: #260f0f; /* darkest red for gray.900 */
  --gizmo-gray-500: #a03b3b; /* red for gizmo-gray-500 */
  --gizmo-gray-600: #8b3636; /* red for gizmo-gray-600 */
  --gizmo-gray-950: #4e1c1c; /* dark red for gizmo-gray-950 */
  --font-size-xs: 0.75rem;
  --font-size-sm: 0.875rem;
  --font-size-base: 1rem;
  --font-size-lg: 1.125rem;
  --font-size-xl: 1.25rem;
}
```
This is the result:
![image](https://github.com/user-attachments/assets/ac7639c2-f85c-492f-bd60-b39a7289a4bb)
![image](https://github.com/user-attachments/assets/db043e37-e85b-4960-889f-013f2d3f0266)
Indeed, I would like to change also the white part.
