### DISCUSSION TITLE
`librechat.yaml` doesn't recognize `speech` settings at root level.

### DISCUSSION THREAD

**Discussion by pechyonkin** [danny-avila/LibreChat#4084] [Troubleshooting] [answered]
### What happened?

I am trying to configure STT via `librechat.yaml` but it doesn't seem to be working. Is there something wrong that I am doing, or is documentation incomplete?

### Steps to Reproduce

When I place the following snippet in `librechat.yaml` at the root level, by following docs [here](https://www.librechat.ai/docs/configuration/stt_tts#configuring-cloud-stt):

```
speech:
  stt:
    openai:
      apiKey: '${STT_API_KEY}'
      model: 'whisper-1'
```

I am not getting speech working, please see error logs below.

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
{
    "issues": [
        {
            "code": "unrecognized_keys",
            "keys": [
                "speech"
            ],
            "message": "Unrecognized key(s) in object: 'speech'",
            "path": []
        }
    ],
    "level": "error",
    "message": "Invalid custom config file at /app/librechat.yaml [
  {
    \"code\": \"unrecognized_keys\",
    \"keys\": [
      \"speech\"
    ],
    \"path\": [],
    \"message\": \"Unrecognized key(s) in object: 'speech'\"
  }
]",
    "name": "ZodError",
    "stack": "ZodError: [
  {
    \"code\": \"unrecognized_keys\",
    \"keys\": [
      \"speech\"
    ],
    \"path\": [],
    \"message\": \"Unrecognized key(s) in object: 'speech'\"
  }
]
    at get error [as error] (/app/node_modules/zod/lib/types.js:43:31)
    at loadCustomConfig (/app/api/server/services/Config/loadCustomConfig.js:64:13)
    at AppService (/app/api/server/services/AppService.js:22:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async startServer (/app/api/server/index.js:36:3)"
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment, marked as answer]
It's recognized on my end, from my startup logs:

```bash
  },
  "speech": {
    "tts": {
      "openai": {
        "voices": [
          "alloy",
          "echo",
          "fable",
          "onyx",
          "nova",
          "shimmer"
        ],
        "apiKey": "${OPENAI_API_KEY}",
        "model": "tts-1"
      }
    },
    "stt": {
      "openai": {
        "apiKey": "${OPENAI_API_KEY}",
        "model": "whisper-1"
      }
    }
  }
}
```

Are you using an older version of LibreChat?

**Comment by pechyonkin** [comment]
@danny-avila I have purged docker and pulled from scratch, after which it started working. Thank you for looking into this!

**Comment by mroozspace** [comment]
could you share your config @pechyonkin?
I've set STT/TTS api keys in .env.
I've added snippet below to librechat.yaml, and I can't see option to set STT/TTS engine to external.

```
speech:
  tts:
    openai:
      # url: ''
      apiKey: '${TTS_API_KEY}'
      model: 'whisper-1'
      voices: ['alloy', 'echo', 'fable', 'onyx', 'nova', 'shimmer']


  stt:
    openai:
      # url: ''
      apiKey: '${STT_API_KEY}'
      model: 'whisper-1'

  speechTab:
    conversationMode: true
    advancedMode: false
    speechToText:
      engineSTT: "external"
      languageSTT: "English (US)"
      autoTranscribeAudio: true
      decibelValue: -45
      autoSendText: 0
    textToSpeech:
      engineTTS: "external"
      voice: "alloy"
      languageTTS: "en"
      automaticPlayback: true
      playbackRate: 1.0
      cacheTTS: true
```
