### DISCUSSION TITLE
Enhancement: Bring back the parameters button in the top bar

### DISCUSSION THREAD

**Discussion by ghost** [danny-avila/LibreChat#4116] [Feature Requests & Suggestions]
### What features would you like to see added?

Since the last commit, the parameter button has been removed from the top bar, and it is now exclusive to the right side panel.

Please bring it back. Some of us use LibreChat with the right side panel hidden in the settings, or even worse, disabled in the librechat.yml config file.

### More details

None

### Pictures

![image](https://github.com/user-attachments/assets/35b72a74-c462-48a3-b624-712d99c5bb61)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
This is currently not planned. The side panel is receiving more functionality and I believe a large part of the reason why it was hidden a lot to begin with was that it had no function before. Furthermore, the parameters are relatively, little used to justify prominence in the Header Options (the "+" button will go the same way soon).

**Reply by ghost** [reply]
Thanks for your response.

I need the parameter tab every time I use a custom endpoint, especially to set the default context window above 4096. It's also handy for adjusting the model's creativity when switching between code and chat modes.

To maintain LibreChat's modularity and flexibility, how about customizing the top bar via `librechat.yml`?

```yaml
interface:
  endpointsMenu: true
  modelSelect: true
  sidePanel: true
  presets: false
  parameters: true            # already exists
  multiConversation: false    # for example
  bookmarkConversation: false # for example
```

Setting `parameters` to true would bring it back to the top bar. If false, it stays in the right side panel.
