### DISCUSSION TITLE
error: [handleAbortError] AI response error; aborting request: 403 status code (no body): DeepL custom endpoint

### DISCUSSION THREAD

**Discussion by vi-xl** [danny-avila/LibreChat#4199] [Help Wanted]
Hello there! 

I am trying to integrated DeepL API endpoint into LibreChat so people can just translate their sentences at one place in LibreChat. 

For this I added the following in librechat.yaml in custom endpoint section in my local docker environment:

```
custom:
    - name: 'DeepL'
      apiKey: '${DEEPL_API_KEY}'
      baseURL: "https://api-free.deepl.com/v2/translate" 
      models:
        default: [ "translate" ]
      titleConvo: false
      titleModel: 'translate'
      modelDisplayLabel: 'DeepL Translation'
      addParams:
        text: "{{input}}"  # This is where the user input goes
        source_lang: "EN"  # Default source language
        target_lang: "DE"   # Default target language
        auth_key: "${DEEPL_API_KEY}"  # Include the key in the body
      dropParams: [ "stop", "user", "frequency_penalty", "presence_penalty" ]
```

But I keep getting _**error: [handleAbortError] AI response error; aborting request: 403 status code (no body).**_ 

Looks like the auth key is not getting properly passed in the params provided. The auth key and base url is correct, as I can get the response correctly through curl and postman. 

Can someone help here please? Also let me know if I am not using the right approach. Thanks a lot!
