### DISCUSSION TITLE
Token Exceed for librechat but not when directly invoking same model

### DISCUSSION THREAD

**Discussion by amitkewal** [danny-avila/LibreChat#4259] [Troubleshooting]
### What happened?

Token Exceed for librechat but not when directly invoking model with the same prompt

I have found one issue that I am getting the following error with librechat  but when I am directly invoking the same model via streamlit + AWS lambda I am getting a proper response. 

`{"level":"error","message":"[handleAbortError] AI response error; aborting request: Prompt token count of 37165 exceeds max token count of 4095.","stack":"Error: Prompt token count of 37165 exceeds max token count of 4095.\n    at OpenAIClient.handleContextStrategy (/app/api/app/clients/BaseClient.js:374:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async OpenAIClient.buildMessages (/app/api/app/clients/OpenAIClient.js:559:61)`

### Steps to Reproduce

I am working on internal 2 hours transcript data.
So I cant share it here.

### Relevant log output

```shell
{"level":"error","message":"[handleAbortError] AI response error; aborting request: Prompt token count of 37165 exceeds max token count of 4095.","stack":"Error: Prompt token count of 37165 exceeds max token count of 4095.\n    at OpenAIClient.handleContextStrategy (/app/api/app/clients/BaseClient.js:374:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async OpenAIClient.buildMessages (/app/api/app/clients/OpenAIClient.js:559:61)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Which model, via a custom endpoint? The system has a specific list of models and uses a default context window if it's not recognized. 

There will be a way to set the max context via config, but for now you can use the parameters for this:

![image](https://github.com/user-attachments/assets/c5e31fb4-cf74-422a-a0a5-1f59afed08c5)

**Reply by AmgadHasan** [reply]
@danny-avila Hi
Any updates about this? Can we set the default context window in the configs?

**Reply by danny-avila** [reply]
Not yet.

**Comment by amitkewal** [comment]
@danny-avila I am using `anthropic.claude-3-5-sonnet-20240620-v1:0`

Sharing the librechat yaml.

# ---
```
version: 1.0.9
cache: false
interface:
  endpointsMenu: true
  modelSelect: true
  parameters: false
  sidePanel: false
  presets: false
  privacyPolicy:
    externalUrl: https://www.dummy.com/privacy
    openNewTab: true
  termsOfService:
    externalUrl: https://www.dummy.com/terms-of-use
    openNewTab: true

endpoints:
  custom:
    - name: DUMMY
      apiKey: xxxxxxxxxxxxxxxxxxxxxx
      baseURL: http://litellm:8000/v1
      models:
        default:          
          - bedrock/meta.llama3-70b-instruct-v1:0          
        fetch: true
      titleConvo: true
      titleModel: llama3-70b
      summarize: false
      summaryModel: llama3-70b
      forcePrompt: false
      modelDisplayLabel: "AI Chat"
fileConfig:
  endpoints:
    DUMMY: 
      disabled: true
```
