### DISCUSSION TITLE
Unable to disable assistant builder

### DISCUSSION THREAD

**Discussion by ar2427** [danny-avila/LibreChat#4341] [Help Wanted]
Hi,

I am trying to implement code interpreter for Azure Open AI, but I am unable to disable assistant builder.

I tried putting endpoints -> assistants -> disableBuilder to true, but that didn't help.

See screenshots for more reference.
![Screenshot 2024-10-04 at 9 46 25 PM](https://github.com/user-attachments/assets/a631a8e7-549a-499e-aeae-1db2ef7048b6)
![Screenshot 2024-10-04 at 9 46 07 PM](https://github.com/user-attachments/assets/0ff6013d-69b5-4602-b859-954b859a887e)

**Comment by ar2427** [comment]
Hi @danny-avila ,

Any update on this?

**Comment by ar2427** [comment]
Resolved. It turns out that for disabling assistants for azure based models, I have to use 'azureAssistants' keywords instead of 'assistants' keyword. See first comment in the code below.

```
endpoints:
  # azureAssistants: # <-- Azure-specific configuration has the same structure as `assistants`
    #  pollIntervalMs: 500
    #  timeoutMs: 10000
 
  assistants:
    disableBuilder: false
    # Use either `supportedIds` or `excludedIds` but not both
    supportedIds: ["asst_supportedAssistantId1", "asst_supportedAssistantId2"]
    # excludedIds: ["asst_excludedAssistantId"]
    # `privateAssistants` do not work with `supportedIds` or `excludedIds`
    # privateAssistants: false
    # (optional) Models that support retrieval, will default to latest known OpenAI models that support the feature
    # retrievalModels: ["gpt-4-turbo-preview"]
    # (optional) Assistant Capabilities available to all users. Omit the ones you wish to exclude. Defaults to list below.
    # capabilities: ["code_interpreter", "retrieval", "actions", "tools", "image_vision"]
```
 [Reference](https://www.librechat.ai/docs/configuration/librechat_yaml/object_structure/assistants_endpoint#example)
