### DISCUSSION TITLE
Azure o1 mini not supported

### DISCUSSION THREAD

**Discussion by philipbrembeck** [danny-avila/LibreChat#4355] [Troubleshooting]
Hi there, 
I could not find any info regarding this, so I thought here would be the best place. 

I've added o1-mini to Librechat:
```yaml
  groups:
          - group: "gpt-azure"
            apiKey: "{{ .Values.azureOpenAI.apiKey }}"
            instanceName: "{{ .Values.azureOpenAI.instanceName }}"
            version: "2024-04-01-preview"
            assistants: true
            models:
              gpt-4o:
                deploymentName: gpt-4o
              gpt-4o-mini:
                deploymentName: gpt-4o-mini
              gpt-4-turbo-128k:
                deploymentName: gpt-4-turbo-128k
              gpt-4-8k:
                deploymentName: gpt-4-8k
              gpt-o1-mini:
                deploymentName: gpt-o1-mini
```

But I get this error on chatting:
<img width="740" alt="Screenshot 2024-10-08 at 13 43 48" src="https://github.com/user-attachments/assets/2eddcb9a-a2fd-4e1f-8184-6dfa6585b157">

With those logs:
```
2024-10-08 11:35:25 warn: [OpenAIClient.chatCompletion][stream] API error
2024-10-08 11:35:25 error: [handleAbortError] AI response error; aborting request: 400 Unsupported value: 'stream' does not support true with this model. Only the default (false) value is supported.
```

Is there a way to disable streaming for this model? I'm on the latest dev build. 

Thank you in advance!
