### DISCUSSION TITLE
Enhancement: Mention necessities when installing own plugins in docs

### DISCUSSION THREAD

**Discussion by fkohrt** [danny-avila/LibreChat#4465] [Feature Requests & Suggestions]
### What features would you like to see added?

I found the LibreChat documentation to be very comprehensive and helpful! One thing I noticed concerns the installation of own plugins: As far as I understand it, when one adds a manifest file to `api/app/clients/tools/.well-known` (as described by the page “[Using official ChatGPT Plugins / OpenAPI specs](https://docs.librechat.ai/features/plugins/chatgpt_plugins_openapi.html#adding-a-plugin)”), changes need to be made to `docker-compose.override.yml`.

### More details

If I just restart the Docker service, the new file doesn't show up within the restarted Docker container (and consequently, the plugin doesn't show up in the plugin store in the UI), given that I started with the [pre-provided `docker-compose.override.yml`](https://github.com/danny-avila/LibreChat/blob/78f5285/docker-compose.override.yml.example). I needed to also copy the file to the Docker image, which I did by configuring the following:

```yml
services:

# USE LIBRECHAT CONFIG FILE
  api:
    volumes:
      - ./librechat.yaml:/app/librechat.yaml
      - ./api/app/clients/tools/.well-known:/app/api/app/clients/tools/.well-known # <----- this line needed to be added
```

But I reckon one could also uncomment the following lines:

```yml
# # LOCAL BUILD
#   api:
#     image: librechat
#     build:
#       context: .
#       target: node
```

In any way, I suggest the documentation to be a little more specific about this necessity, as it is very comprehensive in other regards and newbies might stumble upon this.

Thanks for developing and maintaining such a nice piece of software!

### Which components are impacted by your request?

Documentation

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
