### DISCUSSION TITLE
Azure Mistral - Error 422

### DISCUSSION THREAD

**Discussion by THByte** [danny-avila/LibreChat#4514] [Troubleshooting]
Hi everyone, 

we face an issue with Mistral hosted serverless on MS Azure. 
If we are using presets in a chat we get the following error message: 

```Something went wrong. Here's the specific error message we encountered: 422 {"detail":[{"type":"extra_forbidden","loc":["body","messages",0,"system","name"],"msg":"Extra inputs are not permitted","input":"instructions"}]}```

I could pin the error down the body of the HTTP POST request to the Azure API: 
```{
    "messages": [
    {
        "role": "system",
        "name": "instructions",  // If this is dropped the request works 
        "content": "You are a helpful assistant"
    },
    {
        "role": "user",
        "content": "Explain Riemann's conjecture in 1 paragraph"
    }
    ],
    "temperature": 0,
    "top_p": 1,
    "response_format": { "type": "text" },
    "safe_prompt": true
}
```
  
If the objects in the messages body only contain the keys `role` and `content` the request works.   
I tried to use `extra-parameters: drop` as described in the [Azure API description](https://learn.microsoft.com/en-us/azure/ai-studio/reference/reference-model-inference-api?tabs=rest). However this doesn't fix the issue. 
  
Is there any possibility to drop the parameter on Librechat side? I saw the dropParams configuration but I think it does not work on nested objects in messages array. 

Thanks a lot for the help. 

Our configuration: 
```
- group: "mistral-large-inference"
            apiKey: "..."
            baseURL: ".../v1/chat/completions"
            serverless: true
            headers:
              extra-parameters: "drop"
            modelDisplayLabel: "Mistral"
            dropParams: ["stop", "user", "frequency_penalty", "presence_penalty"]
            # Model-level configuration
            models:
              mistral-large: true
```
