### DISCUSSION TITLE
Getting error while uploading file like images, .csv files

### DISCUSSION THREAD

**Discussion by Chethanibms** [danny-avila/LibreChat#4522] [Troubleshooting]
this is the error message i am getting

Something went wrong. Here's the specific error message we encountered: An error occurred while processing your request. Please contact the Admin.

error: [/files] Error processing file: RAG_API_URL not defined

this is my spec 
```
librechat.yaml: |-
  version: 1.1.0
  cache: true
  endpoints:
    azureOpenAI:
      titleModel: "gpt-4o-2024-05-13"
      titleConvo: true
      plugins: true
      groups:
      - group: "azure-openai"
        apiKey: "********"
        instanceName: "librechat"
        deploymentName: librechat
        version: "2024-03-01-preview"
        models:
          gpt-4o-2024-05-13:
            deploymentName: librechat
```
