### DISCUSSION TITLE
Unable to generate image via dalle using modelspec after updating to 0.7.5

### DISCUSSION THREAD

**Discussion by nathanwong91** [danny-avila/LibreChat#4579] [Troubleshooting] [answered]
### What happened?

While being on 0.7.5-rc1 we have been using modelspecs to give users an option for image generation. Here's the config we've been using

```
- name: "Generate Images using DALLE3"
  label: "Image Generation Tool (DALLE3)"
  description: "Generate images using DALLE3"
  preset:
    default: false
    endpoint: "gptPlugins"
    model: "gpt-4o"
    modelLabel: "Image Generation"
    tools: ["dalle"]
    greeting: |
      This assistant will generate images based on your query using DALLE3
    promptPrefix: |
      Taking the users input, generate an image using dalle3
```
Since moving to 0.7.5 this is now broken. We see an error in the logs
```
error: [PluginsClient] executorCall error: Cannot read properties of null (reading 'call')
```
and this error from the UI
```
Something went wrong. Here's the specific error message we encountered: Encountered an error while attempting to respond: Cannot read properties of null (reading 'call')
```

Another issue we've seen is the models are no longer selected properly
<img width="424" alt="image" src="https://github.com/user-attachments/assets/bc3ae98c-8622-4f01-b9d8-614f3d6fa5a4">
Even though we've set the following
```
    modelSpecs:
      enforce: true
      prioritize: true
      list:
        - name: "GPT4"
          label: "Basic (GPT4)"
          description: "Assist users"
          preset:
            default: true
            endpoint: "azureOpenAI"
            model: "gpt-4o"
            ~~~

```

I don't see anything in the changelogs to reflect changes to do with modelspecs other than labels

### Steps to Reproduce

1. Setup ModelSpecs dalle on 0.7.5-rc1
2. Update to 0.7.5 without changing configuration
3. Ask it to generate an image

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment, marked as answer]
Add this:

```yaml
          agentOptions:
            model: "gpt-4o"
```

```yaml
      - name: "Generate Images using DALLE3"
        label: "Image Generation Tool (DALLE3)"
        description: "Generate images using DALLE3"
        preset:
          default: false
          endpoint: "gptPlugins"
          model: "gpt-4o"
          modelLabel: "Image Generation"
          tools: ["dalle"]
          agentOptions:
            model: "gpt-4o"
          greeting: |
            This assistant will generate images based on your query using DALLE3
          promptPrefix: |
            Taking the users input, generate an image using dalle
```

![image](https://github.com/user-attachments/assets/6ba55009-568c-4212-b389-e35bc3444b37)

---

Note: plugins will be deprecated soon in favor of a better system: https://github.com/danny-avila/LibreChat/issues/3607
