### DISCUSSION TITLE
Nvidia NIM

### DISCUSSION THREAD

**Discussion by Dual-0** [danny-avila/LibreChat#4642] [Feature Requests & Suggestions]
Hello,

Nvidia offers a "[NIM access through the NVIDIA Developer Program](https://build.nvidia.com/)". This has some [limits](https://forums.developer.nvidia.com/t/nvidia-nim-faq/300317) but I think it can be integrated easily cause its based on OpenAI API. Good news who wanna try Nvidias `llama-3.1-nemotron-70b`, it already works via custom endpoint

URL: https://integrate.api.nvidia.com/
Endpoint: POST /v1/chat/completions

custom endpoint
```yaml
# Definition of custom endpoints
endpoints:
  custom:
    - name: "Nvidia"
      apiKey: "${NVIDIA_API_KEY}"
      baseURL: "https://integrate.api.nvidia.com/v1/"
      models:
        default: [
          "nvidia/llama-3.1-nemotron-51b-instruct",
          "nvidia/llama-3.1-nemotron-70b-instruct",
          "nvidia/nemotron-mini-4b-instruct",
          "nvidia/nemotron-4-340b-instruct",
        ]
        fetch: false
      titleConvo: true
      titleModel: "nvidia/nemotron-mini-4b-instruct"
      modelDisplayLabel: "Nvidia"
```

example with curl:
```shell
curl --request POST \
     --url https://integrate.api.nvidia.com/v1/chat/completions \
     --header 'accept: application/json' \
     --header 'content-type: application/json' \
     --data '
{
  "model": "nvidia/llama-3.1-nemotron-70b-instruct",
  "max_tokens": 1024,
  "stream": false,
  "temperature": 0.5,
  "top_p": 1,
  "stop": null,
  "frequency_penalty": 0,
  "presence_penalty": 0,
  "seed": 0,
  "messages": [
    {
      "role": "user",
      "content": "Write a limerick about the wonders of GPU computing."
    }
  ]
}
'
```
output:
```json
{
  "id": "string",
  "object": "chat.completion",
  "created": 0,
  "model": "nvidia/llama-3.1-nemotron-70b-instruct",
  "choices": [
    {
      "index": 0,
      "message": {
        "role": "string",
        "content": "string"
      },
      "finish_reason": "stop"
    }
  ],
  "usage": {
    "prompt_tokens": 0,
    "total_tokens": 0,
    "completion_tokens": 0
  }
}
```
