### DISCUSSION TITLE
OpenRouter doesn't show up in the list of providers

### DISCUSSION THREAD

**Discussion by TonySimonovsky** [danny-avila/LibreChat#4676] [Troubleshooting] [answered]
### What happened?

I'm trying to add openrouter to my digital ocean deployment of librechat, but it doesn't show up in the list for some reason.

### Steps to Reproduce

My librechat.yaml content:
```
# For more information, see the Configuration Guide:
# https://www.librechat.ai/docs/configuration/librechat_yaml

# Configuration version (required)
# version: 1.1.5

# Cache settings: Set to true to enable caching
# cache: true


endpoints:
  custom:
    - name: 'OpenRouter'
      # For `apiKey` and `baseURL`, you can use environment variables that you define.
      # recommended environment variables:
      # Known issue: you should not use `OPENROUTER_API_KEY` as it will then override the `openAI` endpoint to use OpenRouter as well.
      apiKey: '${OPENROUTER_KEY}'
      baseURL: 'https://openrouter.ai/api/v1'
      models:
        default: ['meta-llama/llama-3-70b-instruct']
        fetch: true
      titleConvo: true
      titleModel: 'meta-llama/llama-3-70b-instruct'
      # Recommended: Drop the stop parameter from the request as Openrouter models use a variety of stop tokens.
      dropParams: ['stop']
      modelDisplayLabel: 'OpenRouter'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
