### DISCUSSION TITLE
Document of Authelia part `OPENID_CALLBACK_URL` is wrong.

### DISCUSSION THREAD

**Discussion by juntong20XX** [danny-avila/LibreChat#4685] [Troubleshooting]
### What happened?

If fill the full callback URL on `OPENID_CALLBACK_URL` part, librechat will set `redirect_uri` with value "app_url + OPENID_CALLBACK_URL".
Therefore, `OPENID_CALLBACK_URL` should be `/oauth/openid/callback`.

By the way, during the process of writing the issue, I found that the content corresponding to Authetik in the document is correct.

### Steps to Reproduce

(just fill the value as document tould: `OPENID_CALLBACK_URL=https://auth.example.com/api/oidc/authorization`)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Karstensson** [comment]
I still did not manage to get it work with the callback url set according to your suggestion. 

`Error: Unknown authentication strategy "openid"
    at attempt (/app/node_modules/passport/lib/middleware/authenticate.js:193:39)
    at authenticate (/app/node_modules/passport/lib/middleware/authenticate.js:370:7)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/app/node_modules/express/lib/router/route.js:149:13)
    at Route.dispatch (/app/node_modules/express/lib/router/route.js:119:3)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at /app/node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/app/node_modules/express/lib/router/index.js:346:12)
    at next (/app/node_modules/express/lib/router/index.js:280:10)
    at /app/api/node_modules/express-rate-limit/dist/index.cjs:752:7
`

**Reply by juntong20XX** [reply]
Can you show me your openid part of `librechat.yaml` and `librechat.env`?

Btw, here is my config in librechat.yaml:

```yaml
# includedTools: ["google"]
# Example Registration Object Structure (optional)
registration:
# socialLogins: ['github', 'google', 'discord', 'openid', 'facebook']
socialLogins: ['openid']
```

and env file:

```dotenv
# OpenID
OPENID_CLIENT_ID="{{The Username for Librechat}}"
OPENID_CLIENT_SECRET="{{The Secret for Librechat}}"
OPENID_ISSUER="Url for Authelia"
OPENID_SESSION_SECRET="{{Any random string}}"
OPENID_SCOPE="openid profile email"
OPENID_CALLBACK_URL="/oauth/openid/callback"
OPENID_REQUIRED_ROLE=
OPENID_REQUIRED_ROLE_TOKEN_KIND=
OPENID_REQUIRED_ROLE_PARAMETER_PATH=
# Set to determine which user info property returned from OpenID Provider to store as the User's username
OPENID_USERNAME_CLAIM=
# Set to determine which user info property returned from OpenID Provider to store as the User's name
OPENID_NAME_CLAIM=

OPENID_BUTTON_LABEL="Log in with Authelia"
OPENID_IMAGE_URL=
```

That works for me.

**Comment by juntong20XX** [comment]
Can you show me your openid part of `librechat.yaml` and `librechat.env`?

Btw, here is my config in librechat.yaml:

```yaml
# includedTools: ["google"]
# Example Registration Object Structure (optional)
registration:
  # socialLogins: ['github', 'google', 'discord', 'openid', 'facebook']
  socialLogins: ['openid']
```

and env file:

```env
# OpenID
OPENID_CLIENT_ID="{{The Username for Librechat}}"
OPENID_CLIENT_SECRET="{{The Secret for Librechat}}"
OPENID_ISSUER="Url for Authelia"
OPENID_SESSION_SECRET="{{Any random string}}"
OPENID_SCOPE="openid profile email"
OPENID_CALLBACK_URL="/oauth/openid/callback"
OPENID_REQUIRED_ROLE=
OPENID_REQUIRED_ROLE_TOKEN_KIND=
OPENID_REQUIRED_ROLE_PARAMETER_PATH=
# Set to determine which user info property returned from OpenID Provider to store as the User's username
OPENID_USERNAME_CLAIM=
# Set to determine which user info property returned from OpenID Provider to store as the User's name
OPENID_NAME_CLAIM=

OPENID_BUTTON_LABEL="Log in with Authelia"
OPENID_IMAGE_URL=
```

That works for me.
