### DISCUSSION TITLE
[Question]: Cannot connect to local OpenAI compatible API

### DISCUSSION THREAD

**Discussion by tsoernes** [danny-avila/LibreChat#4757] [Troubleshooting]
### What is your question?

I have made a OpenAI compatible API that runs locally. I'm trying to connect to it with librechat.

I have this in librechat.yaml:
```
endpoints:
  custom:
    - name: "LocalOpenAI"
      apiKey: "XXX"
      baseURL: "http://10.99.10.81:7071/api/v1/"
      models:
        default: ["gpt-4o"]
        fetch: true
      titleConvo: true
      titleModel: "current_model"
      summarize: false
      summaryModel: "current_model"
      forcePrompt: false
      modelDisplayLabel: "LocalOpenAI"
```
      
 And I can successfully use the API within the container:
```
$ podman exec -it a217631b0d73 /bin/sh      
/app # curl -X POST http://10.99.10.81:7071/api/v1/models -H "Authorization: Bearer XXXXX"
{"object": "list", "data": [{"id": "gpt-4o", "object": "model", "created": 1700000000, "owned_by": "Bouvet"}]}/app # ⏎  

/app # curl -X POST http://10.99.10.81:7071/api/v1/chat/completions -H "Content-Type: application/json" -H "Authorization: Bearer XXXX" -d '{"messages": [{"role"
: "user", "content": "What wells are in the maria field?"}]}'

{"choices": [{"content_filter_results": {"hate": {"filtered": false, "severity": "safe"}, "self_harm": {"filtered": false, "severity": "safe"}, "sexual": {"filtered": false, "severity": "safe"}, "violence": {"filtered": false, "severity": "safe"}}, "finish_reason": "stop", "index": 0, "logprobs": null, "message": {"audio": null, "content": "Answer:\nThe Maria field includes the well 6406/3-G-4 H, which is mentioned in the context of the Maria project.\n\nSupporting Quotes:\n\nReference #1:\n  Text: The 6406/3-G-4 H well was the fourth producer to be completed in the Maria project.\n  Document Title: Final Well Report \u2013 6406/3-G-4 H\n  File Name: MA01-WDN-D-IW-0002_01M_003.PDF\n  PDF Pages: 14, 15\n  Section: 4.1 Geology\n\n--------------------------------------------------------------------------------\n\n", "function_call": null, "refusal": null, "role": "assistant", "tool_calls": null}}], "created": 1732028785, "id": "chatcmpl-LmULnRcGwIplrVeggNXtNuRjYuqDY", "model": "gpt-4o", "object": "chat.completion", "prompt_filter_results": [{"content_filter_results": {"hate": {"filtered": false, "severity": "safe"}, "self_harm": {"filtered": false, "severity": "safe"}, "sexual": {"filtered": false, "severity": "safe"}, "violence": {"filtered": false, "severity": "safe"}}, "prompt_index": 0}], "service_tier": null, "system_fingerprint": "fp_000eow_rag", "usage": {"completion_tokens": 1, "prompt_tokens": 1, "completion_tokens_details": {"accepted_prediction_tokens": 0, "audio_tokens": 0, "reasoning_tokens": 0, "rejected_prediction_tokens": 0}, "prompt_tokens_details": {"audio_tokens": 0, "cached_tokens": 0}, "total_tokens": 2}}/app #
 ```     
 
 I can also select the model in librechat, but not use it:
 
![image](https://github.com/user-attachments/assets/8b6bda36-64c4-42d1-94fc-72c8006a779b)

Logs say:
```
[api]         | 2024-11-19 15:11:59 error: Failed to fetch models from LocalOpenAI API The request was made and the server responded with a status code that falls out of the range of 2xx: Request failed with status code 404. Error response data:
[api]
[mongodb]     | {"t":{"$date":"2024-11-19T15:12:03.289+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"10.89.0.74:34682","uuid":{"uuid":{"$uuid":"377ea852-0e9c-4af0-9187-6b099844e6b0"}},"connectionId":15,"connectionCount":15}}
[mongodb]     | {"t":{"$date":"2024-11-19T15:12:03.289+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn15","msg":"client metadata","attr":{"remote":"10.89.0.74:34682","client":"conn15","negotiatedCompressors":[],"doc":{"driver":{"name":"nodejs","version":"4.17.2"},"platform":"Node.js v20.18.0, LE","os":{"name":"linux","architecture":"x64","version":"6.11.8-300.fc41.x86_64","type":"Linux"}}}}
[mongodb]     | {"t":{"$date":"2024-11-19T15:12:03.298+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"10.89.0.74:34692","uuid":{"uuid":{"$uuid":"81ead876-b2ac-4ebc-aa57-891ffc44eccb"}},"connectionId":16,"connectionCount":16}}
[mongodb]     | {"t":{"$date":"2024-11-19T15:12:03.299+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn16","msg":"client metadata","attr":{"remote":"10.89.0.74:34692","client":"conn16","negotiatedCompressors":[],"doc":{"driver":{"name":"nodejs|Mongoose","version":"5.9.2|7.8.1"},"platform":"Node.js v20.18.0, LE","os":{"name":"linux","architecture":"x64","version":"6.11.8-300.fc41.x86_64","type":"Linux"}}}}
[api]         | 2024-11-19 15:12:11 warn: [OpenAIClient.chatCompletion][stream] API error
[api]         | 2024-11-19 15:12:11 error: [handleAbortError] AI response error; aborting request: 404 status code (no body)
```

### More Details

Let me know if you need any details

### What is the main subject of your question?

Endpoints

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jmaddington** [comment]
Try changing `fetch` to `false` in your YAML.

**Comment by tsoernes** [comment]
@jmaddington Okay. Now I am able to connect, and the API response. But there librechat shows an error.

![image](https://github.com/user-attachments/assets/f6d098ed-0069-4d44-90eb-ba4bc2d27125)

librechat log:
```
[api]         | 2024-11-20 07:48:47 warn: [OpenAIClient.chatCompletion][stream] Unhandled error type
[api]         | 2024-11-20 07:48:47 error: [OpenAIClient.chatCompletion] Unhandled error type request ended without sending any chunks
[api]         | 2024-11-20 07:48:47 error: [handleAbortError] AI response error; aborting request: request ended without sending any chunks
```
API log:
```
[2024-11-20T07:48:47.674Z] HTTP Request: POST https://oai-skynet-testsite-sweden.openai.azure.com//openai/deployments/m-gpto-06082024/chat/completions?api-version=2023-05-15 "HTTP/1.1 200 OK"
[2024-11-20T07:48:47.674Z] Request: {'model': 'gpt-4o', 'user': '673ca2298e58109b2fd02343', 'stream': True, 'messages': [{'role': 'user', 'content': 'hi'}, {'role': 'assistant', 'content': 'An error occurred while processing your request. Please contact the Admin.'}, {'role': 'user', 'content': 'hi'}, {'role': 'assistant', 'content': 'An error occurred while processing your request. Please contact the Admin.'}, {'role': 'user', 'content': 'hi'}, {'role': 'assistant', 'content': 'An error occurred while processing your request. Please contact the Admin.'}, {'role': 'user', 'content': 'hi'}]}
[2024-11-20T07:48:47.674Z] messages=[{'role': 'user', 'content': 'hi'}, {'role': 'assistant', 'content': 'An error occurred while processing your request. Please contact the Admin.'}, {'role': 'user', 'content': 'hi'}, {'role': 'assistant', 'content': 'An error occurred while processing your request. Please contact the Admin.'}, {'role': 'user', 'content': 'hi'}, {'role': 'assistant', 'content': 'An error occurred while processing your request. Please contact the Admin.'}, {'role': 'user', 'content': 'hi'}]
[2024-11-20T07:48:47.674Z] Returning {"choices": [{"content_filter_results": {"hate": {"filtered": false, "severity": "safe"}, "self_harm": {"filtered": false, "severity": "safe"}, "sexual": {"filtered": false, "severity": "safe"}, "violence": {"filtered": false, "severity": "safe"}}, "finish_reason": "stop", "index": 0, "logprobs": null, "message": {"audio": null, "content": "Answer:\nHello! How can I assist you today?\n\nSupporting Quotes:\n\n", "function_call": null, "refusal": null, "role": "assistant", "tool_calls": null}}], "created": 1732088927, "id": "chatcmpl-DHWXiGzKbFlZYHBFchPUgJNsJinbj", "model": "gpt-4o", "object": "chat.completion", "prompt_filter_results": [{"content_filter_results": {"hate": {"filtered": false, "severity": "safe"}, "self_harm": {"filtered": false, "severity": "safe"}, "sexual": {"filtered": false, "severity": "safe"}, "violence": {"filtered": false, "severity": "safe"}}, "prompt_index": 0}], "service_tier": null, "system_fingerprint": "fp_000eow_rag", "usage": {"completion_tokens": 1, "prompt_tokens": 1, "completion_tokens_details": {"accepted_prediction_tokens": 0, "audio_tokens": 0, "reasoning_tokens": 0, "rejected_prediction_tokens": 0}, "prompt_tokens_details": {"audio_tokens": 0, "cached_tokens": 0}, "total_tokens": 2}}
```
API code:
```python

default_response = {
    "choices": [
        {
            "content_filter_results": {
                "hate": {"filtered": False, "severity": "safe"},
                "self_harm": {"filtered": False, "severity": "safe"},
                "sexual": {"filtered": False, "severity": "safe"},
                "violence": {"filtered": False, "severity": "safe"},
            },
            "finish_reason": "stop",
            "index": 0,
            "logprobs": None,
            "message": {
                "audio": None,
                "content": "PLACEHOLDER",
                "function_call": None,
                "refusal": None,
                "role": "assistant",
                "tool_calls": None,
            },
        }
    ],
    "created": 1731669457,
    "id": "chatcmpl-ATocTflkPHoUliboru2hb5h9tk0ox",
    "model": "gpt-4o",
    "object": "chat.completion",
    "prompt_filter_results": [
        {
            "content_filter_results": {
                "hate": {"filtered": False, "severity": "safe"},
                "self_harm": {"filtered": False, "severity": "safe"},
                "sexual": {"filtered": False, "severity": "safe"},
                "violence": {"filtered": False, "severity": "safe"},
            },
            "prompt_index": 0,
        }
    ],
    "service_tier": None,
    "system_fingerprint": "fp_000eow_rag",
    "usage": {
        "completion_tokens": 1,
        "prompt_tokens": 1,
        "completion_tokens_details": {
            "accepted_prediction_tokens": 0,
            "audio_tokens": 0,
            "reasoning_tokens": 0,
            "rejected_prediction_tokens": 0,
        },
        "prompt_tokens_details": {"audio_tokens": 0, "cached_tokens": 0},
        "total_tokens": 2,
    },
}

@app.route(route="v1/chat/completions", auth_level=func.AuthLevel.ANONYMOUS)
def chat_completions(req: func.HttpRequest) -> func.HttpResponse:
    # OpenAI API compatible
    print(f"Request headers: {req.headers}")
    try:
        print(f"Request: {req.get_json()}")
    except Exception as e:
        return func.HttpResponse(str(e), status_code=400)
    token = req.headers.get("Authorization")
    if not token:
        return func.HttpResponse("Unauthorized", status_code=401)
    token = token.replace("Bearer ", "")
    if token != function_key:
        return func.HttpResponse("Incorrect function key", status_code=401)

    logging.info(f"Python HTTP trigger function processed a request: {req}")
    try:
        js = req.get_json()
        messages = js["messages"]
        print(f"{messages=}")
        content = messages[-1]["content"]
        if isinstance(content, list):
            query = content[-1]["text"]
        else:
            query = content
        _, response = run_query(query=query, history=messages[:-1])
        default_response["id"] = "chatcmpl-" + "".join(
            random.choices(ascii_letters, k=29)
        )
        default_response["created"] = int(time.time())
        default_response["choices"][0]["message"]["content"] = format_response(response)

        js = json.dumps(default_response)
        print(f"Returning {js}")
        return func.HttpResponse(js, status_code=200, mimetype="application/json")
    except Exception as e:
        stackprinter.show_current_exception()
        print(f"{req=}, {req.headers=}, {req.params=}, {type(e)}, {e=}")
        logging.error(f"{req=}, {req.headers=}, {req.params=}, {type(e)}, {e=}")
        return func.HttpResponse(str(e), status_code=400)
```

**Reply by shivani1998-nsui** [reply]
I am also facing the same issue, have you found any solution for it ?

**Reply by jmaddington** [reply]
I'm sorry I missed the last response from November. LibreChat has a config especially for AzureAI. This is a sample of mine:

```
endpoints:
  agents:
    recursionLimit: 100          # Default limit users see
    maxRecursionLimit: 200      # Maximum limit users can set
    disableBuilder: false

  assistants:
    disableBuilder: true # Disable Assistants Builder Interface by setting to `true`
      
  azureOpenAI:
    # Set title model to GPT-4.1-nano
    titleModel: "gpt-4.1-nano"
    
    # Disable assistants
    assistants: false
    
    groups:
      # Azure OpenAI Service Models (Standard Deployments)
      - group: "azure-openai-standard"
        apiKey: "${AZURE_AI_FOUNDRY_API_KEY}"
        baseURL: "https://[redacted-fqdn].cognitiveservices.azure.com/openai/deployments/gpt-4.1/chat/completions?api-version=2025-01-01-preview"
        instanceName: "my-name-of-librechat-resource"
        version: "2024-12-01-preview"
        models:
          gpt-4.1:
            deploymentName: "gpt-4.1"
          gpt-4.1-nano:
            deploymentName: "gpt-4.1-nano"
          gpt-4o:
            deploymentName: "gpt-4o"
          gpt-4o-mini:
            deploymentName: "gpt-4o-mini"
          o3-mini:
            deploymentName: "o3-mini"
          o4-mini:
            deploymentName: "o4-mini"

      # Azure AI Foundry Serverless Models
      - group: "azure-ai-foundry-serverless"
        serverless: true
        apiKey: "${AZURE_AI_FOUNDRY_API_KEY}"
        baseURL: "https://[redacted-fqdn].services.ai.azure.com/models"
        version: "2024-05-01-preview"
        models:
          deepseek-r1:
            deploymentName: "DeepSeek-R1-0528"
          grok-3:
            deploymentName: "grok-3"
          grok-3-mini:
            deploymentName: "grok-3-mini"
          phi-4:
            deploymentName: "phi-4"
          phi-4-reasoning:
            deploymentName: "phi-4-reasoning"
```

`AZURE_AI_FOUNDRY_API_KEY` is set in the `.env` file.

I'd also try running the requests without any custom settings to temperature, top_k, etc.
