### DISCUSSION TITLE
`prompts` and `bookmarks` settings don't seem to work properly

### DISCUSSION THREAD

**Discussion by cmurtaugh** [danny-avila/LibreChat#4840] [Troubleshooting]
I'm using LibreChat `0.7.5` and I have the following in our librechat.yaml file: 
```
interface:
  parameters: false
  presets: false
  endpointsMenu: false
  modelSelect: false
  prompts: true
  bookmarks: false
  multiConvo: false
```
Note that `prompts` are enabled and `bookmarks` are disabled. 

However, this is what I get: 
<img width="1051" alt="image" src="https://github.com/user-attachments/assets/9460df52-f900-4707-aacf-3cc613b0cecb">

* Bookmarks show up in the UI, despite being disabled. I can't, however, add a bookmark as far as I can tell. 
* Prompts are enabled as expected, but there's no way for me to create a new prompt. 

The `Manage Prompts` screen also doesn't give me an option to create a new prompt:
<img width="1051" alt="image" src="https://github.com/user-attachments/assets/d4d76b5c-0af1-42f0-8775-e7a5d508cdd1">
