### DISCUSSION TITLE
Errors using Llama models via the `bedrock` endpoint.

### DISCUSSION THREAD

**Discussion by cmurtaugh** [danny-avila/LibreChat#4841] [Troubleshooting]
I'm trying to use a Llama model via Bedrock but keep getting an error:
```
The latest message token count is too long, exceeding the token limit (12 / undefined respectively). 
Please shorten your message, adjust the max context size from the conversation parameters, 
or fork the conversation to continue.
```

I have this in my librechat.yaml:
```yaml
modelSpecs:
  list:
    - name: "us.meta.llama3-2-11b-instruct-v1:0"
      label: "Meta Llama 3.2 11b"
      description: "Reliable, good quality at moderate speed"
      iconURL: "https://[...]/img/meta.png"
      showIconInMenu: true
      preset:
        endpoint: "bedrock"
        model: "us.meta.llama3-2-11b-instruct-v1:0"
        modelLabel: "Llama 3.2 11b"
        greeting: "Hello! I'm Llama 3.2 11b. How can I help you today?"
        maxContextTokens: 128000
```
but continue to get the same error. 

If I nest `maxContextTokens` under `model_options` like below ([as the docs appear to direct](https://www.librechat.ai/docs/configuration/librechat_yaml/object_structure/model_specs#model_options)) then the `maxContextTokens` setting seems to be ignored entirely:
```yaml
modelSpecs:
  list:
    - name: "us.meta.llama3-2-11b-instruct-v1:0"
      label: "Meta Llama 3.2 11b"
      description: "Reliable, good quality at moderate speed"
      iconURL: "https://[...]/img/meta.png"
      showIconInMenu: true
      preset:
        endpoint: "bedrock"
        model: "us.meta.llama3-2-11b-instruct-v1:0"
        modelLabel: "Llama 3.2 11b"
        greeting: "Hello! I'm Llama 3.2 11b. How can I help you today?"
        model_options:
          maxContextTokens: 128000
```

How is this supposed to work?
