### DISCUSSION TITLE
Enhancement:

### DISCUSSION THREAD

**Discussion by cauvang32** [danny-avila/LibreChat#4858] [Feature Requests & Suggestions]
### What features would you like to see added?

Add GPT-4o mini, o1-preview and o1-mini support (or even more) for Github Model.

### More details

Github Models has many different types of models so I hope your team can add that functionality, I have been waiting for that for a long timeee.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Have you tried adding it as a custom endpoint?

https://www.librechat.ai/docs/quick_start/custom_endpoints

**Reply by cauvang32** [reply]
Yes I've tried that, however I get this error when using o1-mini and o1-preview
2024-12-07 13:53:33 info: Server listening on all interfaces at port 3080. Use http://localhost:3080 to access it
{"level":"info","message":"[Login] [Login successful] [Username: vuquocanh1979@gmail.com] [Request-IP: 172.19.0.1]","timestamp":"2024-12-07T13:53:49.000Z"}
2024-12-07 13:53:50 error: Failed to fetch models from Github OAI API
Something happened in setting up the request. Error message:
 Cannot read properties of undefined (reading 'map')
2024-12-07 13:54:03 warn: [OpenAIClient.chatCompletion][stream] API error
2024-12-07 13:54:03 error: [handleAbortError] AI response error; aborting request: 400 Unsupported value: 'stream' does not support true with this model. Only the default (false) value is supported.
2024-12-07 13:54:16 warn: [OpenAIClient.chatCompletion][stream] API error
2024-12-07 13:54:16 error: [handleAbortError] AI response error; aborting request: 400 Unsupported value: 'stream' does not support true with this model. Only the default (false) value is supported.

**Reply by harrisonhxy** [reply]
Have you implemented the GitHub models o1-mini and o1-preview in librechat? 4o as well as 4o-mini etc. of GitHub models work fine, how should the o1 series models be called?
By the way, I'm sure I've got access to GitHub models o1-mini and o1-preview!

**Reply by cauvang32** [reply]
I'm using custom api endpoint in Librechat.yaml like this:
```yaml 
version: 1.1.4
cache: true
endpoints:
  custom:
    - name: "Github OAI"
      apiKey: "my_github_personal_token"
      baseURL: "https://models.inference.ai.azure.com"
      models:
        default: ["gpt-4o","gpt-4o-mini","o1-mini","o1-preview"]
        fetch: true
      titleConvo: true
      titleModel: "current_model"
      summarize: false
      summaryModel: "current_model"
      forcePrompt: false
      modelDisplayLabel: "OpenAI-Github"
  ```
