### DISCUSSION TITLE
[Question] Can Agent be used in modelSpecs?

### DISCUSSION THREAD

**Discussion by dvejsada** [danny-avila/LibreChat#4905] [General]
Similarly as in case of assistants, is it possible to use a specific Agent as a basis for modelSpecs "endpoint"? It is currently not mentioned in the documentation.

**Comment by yashsinha-aero** [comment]
Same qs

**Comment by dvejsada** [comment]
So I managed to get it working by trial and error, using "agent_id" in presets.

```
    - name: "financial-advisor-agent"
      label: "My financial advisor"
      description: "Chat with your personal financial information."
      iconURL: "https://upload.wikimedia.org/wikipedia/commons/1/14/Anthropic.png"
      preset:
        default: true
        endpoint: "agents"
        agent_id: "agent_4ctGeaRIDZxKJLRC0ywzm"
        maxContextTokens: 200000 # Maximum context tokens
        max_tokens: 4096 # Maximum output tokens
        modelLabel: "Claude 3.5 Chat"
        greeting: |
          Ahoj, jak Ti můžu dnes poradit s tvými finančními záležitostmi?
```

**Reply by dvejsada** [reply]
However, a drawback of this approach is that if the user does not have the Agent used in the modelSpec available, it will cause an error. Therefore, this is usable only if the agent used in modelSpecs is available to all users.

**Reply by yashsinha-aero** [reply]
So can we not create the agent through the model spec as well? Or do we have to manually create the agent through agent builder and then use the agent ID?

**Reply by dvejsada** [reply]
That is my understanding yes. And also there is no way to disable agent builder for the specific modelSpec to avoid users tinker with the agent settings.

**Reply by yashsinha-aero** [reply]
There is actually, justset parameters : false. Then agent builder is disabled

**Reply by dvejsada** [reply]
> There is actually, justset parameters : false. Then agent builder is disabled

Unfortunately, if I do this, I am not able to edit the Agent even as an admin.

**Comment by danny-avila** [comment]
Yes, will add it to the docs soon. Here's another example:

```
modelSpecs:
  enforce: true
  prioritize: true
  list:
      - name: "LibreChat Coder"
        label: "LibreChat Coder"
        description: "Can execute code in various languages, with the ability to input and output files. Ask for help with your code!"
        greeting: |
          Can execute code in C, C++, Python, Java, Ruby, PHP, Rust, Go, JS/TS (node.js) and can generate files. Upload files for data analysis, ask for graphs, or help with your code! 👍
        preset:
          default: true
          endpoint: "agents"
          agent_id: "agent_4LkVNVeIhCKBEr22z9i09"
```

You can safely share your agent without exposing any of its instructions or allowing others to edit it.
