### DISCUSSION TITLE
can't seem to get app to recognize LibreChat.yaml

### DISCUSSION THREAD

**Discussion by danielrosehill** [danny-avila/LibreChat#4933] [Help Wanted]
Hi everyone, 

Just posting on the off-chance anyone can help, it would be much appreciated. 

I have LibreChat deployed on a VPS and it works great, but the only thing I can't figure out is how to get the values I've declared in LibreChat.yaml to be recognised by the app.

I followed the documentation and added both values for speech-to-text as well as a custom endpoint for OpenRouter 

My docker-compose override has the following and I verified that librechat.yaml is in the same directory as the docker-compose and docker-compose override are running from within. 

```yaml
version: '3.4'

services:
   api:
     volumes:
     - type: bind
       source: ./librechat.yaml
       target: /app/librechat.yaml
     image: ghcr.io/danny-avila/librechat:latest
```

In my .env I've added the API keys for the two custom endpoints I'm trying to add, specifically OpenRouter and DeepSeek. 

I've tried restarting the Docker Compose, but none of the changes that I've applied there appear to be being parsed.
