### DISCUSSION TITLE
Cannot get Open AI TTS working with librechat.yaml etc

### DISCUSSION THREAD

**Discussion by jhmonroe** [danny-avila/LibreChat#4988] [Troubleshooting]
### What happened?

Love this project! Thank you so much for creating so we can explore models in one window.

Am trying to add the OpenAI TTS voices as outlined here: https://www.librechat.ai/docs/configuration/stt_tts

I followed and double-checked the steps outlined below but the settings never show up and I get a Docker error pasted below in the output area.

I also searched this repo and saw other issues where you suggested path changes and tried to just change the path to see if anything changed. Same error.

Am I missing something?

Mac here running Docker 4.35.1 and updated to 4.36 to rule that out. :-)

### Steps to Reproduce

- copy/rename **librechat.yaml** in the root as per [instructions](https://www.librechat.ai/docs/configuration/librechat_yaml/setup)
- uncommented this:
```
speech:
  tts:
    openai:
      apiKey: 'API KEY HERE'
      model: 'tts-1'
      voices: ['alloy', 'echo', 'fable', 'onyx', 'nova', 'shimmer']
```

- followed the [docker setup instructions](https://www.librechat.ai/docs/configuration/librechat_yaml/setup) to create **docker-compose.override.yml** with the following uncommented:
```
version: '3.4'
 
services:
  api:
    volumes:
      - type: bind
        source: ./librechat.yaml
        target: /app/librechat.yaml
```
- stopped and restarted the container several times
- still get that warning and still not setting the openAI TTS 
- stop containers, remove those 2 files, restart. no errors

### Relevant log output

```shell
In Docker: "error: Config file YAML format is invalid: ENOENT: no such file or directory, open '/app/librechat.yaml'"
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Thanks for the detailed report! This seems to be an issue with Docker not properly mounting your configuration file. Let's try a few things to troubleshoot:

1. First, let's verify your file structure. Make sure your `librechat.yaml` is in the same directory as your `docker-compose.yml` file. You can check this with:
```bash
ls -la | grep yaml
```

2. Try using an absolute path in your docker-compose.override.yml:
```yaml
version: '3.4'
 
services:
  api:
    volumes:
      - type: bind
        source: ${PWD}/librechat.yaml
        target: /app/librechat.yaml
```

3. You can also try these troubleshooting steps:
   - Check file permissions: `chmod 644 librechat.yaml`
   - Verify the file contents: `cat librechat.yaml`
   - Try rebuilding the container: 
     ```bash
     docker-compose down
     docker-compose build --no-cache
     docker-compose up
     ```

4. To debug the mounting, you can:
   - Check if the file is actually in the container:
     ```bash
     docker-compose exec api ls -la /app/librechat.yaml
     ```
   - Look at the container logs:
     ```bash
     docker-compose logs api
     ```

Could you try these steps and let me know what you find? Also, could you share:
- The output of `pwd` in your project directory
- The result of `ls -la librechat.yaml`

One more important thing to clarify - which compose file are you using as your base? LibreChat has two options:
- `docker-compose.yml` 
- `deploy-compose.yml` 

Could you also share:
1. Which base compose file you're using?
2. The exact commands you're using to start the application?
