### DISCUSSION TITLE
Model's maximum context length error using Agents and Azure provider.

### DISCUSSION THREAD

**Discussion by lxDaniel** [danny-avila/LibreChat#5107] [Q&A]
Hi, I'm consistently getting this error ONLY when using **Agents**. 
Interestingly, it works perfectly well with Azure _Assistants_ (I need the features that Agents offer tho).:
![error - agents](https://github.com/user-attachments/assets/34307051-4465-43ed-a473-3e870ba195bc)

The librechat-api log indicates the following:
`2024-12-26 09:01:49 error: [handleAbortError] AI response error; aborting request: 400 This model's maximum context length is 128000 tokens. However, your messages resulted in 202177 tokens (202122 in the messages, 55 in the functions). Please reduce the length of the messages or functions. `
The token count may vary, the largest number I got so far is around 450k.

I'm using Librechat v0.76, last commit as of today (12/26) (not like it worked at some point, it didn't), to interact with an Azure AI Search Index using Librechat's Agents. 
AzureOpenAI provider, gpt-4o model (the error also happens with gpt-35-turbo-16k).
My librechat.yml file looks like this:

```
endpoints:
  agents:
    disableBuilder: false
  azureOpenAI:
    titleModel: "gpt-35-turbo-16k"
    titleConvo: true
    plugins: true
    agents: true
    assistants: true
    groups:
      - group: "eastus"
        apiKey: myapikey
        agents: true
        assistants: true
        instanceName: "myinstance"
        version: "2024-08-01-preview"
        models:
          gpt-4o:
            deploymentName: mydeploy-4o
          gpt-35-turbo-16k:
            deploymentName: mydeploy-35
  azureAssistants:
    capabilities: ["code_interpreter", "actions", "tools"]
```

Any guidance is welcomed!
