### DISCUSSION TITLE
MCP: repeatedly hitting recursionLimit

### DISCUSSION THREAD

**Discussion by basilesportif** [danny-avila/LibreChat#5133] [Help Wanted]
Often, while running MCP tools that do a lot independently, I'll get the error:

```
error: [handleAbortError] AI response error; aborting request: Recursion limit of 25 reached without hitting a stop condition. You can increase the limit by setting the "recursionLimit" config key.

Troubleshooting URL: https://js.langchain.com/docs/troubleshooting/errors/GRAPH_RECURSION_LIMIT
```

Where is the config option to increase this?

**Comment by danny-avila** [comment]
This isn’t configurable yet but I’ll add an option soon.

**Reply by basilesportif** [reply]
Sounds good--I can see why it wasn't needed before, but it becomes important when various MCP tools get deep in solving a task, only to break midway through.

**Reply by danny-avila** [reply]
Just merged this in! https://github.com/danny-avila/LibreChat/pull/5170

**Reply by danny-avila** [reply]
https://www.librechat.ai/docs/configuration/librechat_yaml/object_structure/agents#recursionlimit

**Comment by belisarius222** [comment]
I'm also hitting this a lot, especially when using an agent to write and then test code.

**Reply by danny-avila** [reply]
Just merged this in! https://github.com/danny-avila/LibreChat/pull/5170

**Reply by danny-avila** [reply]
https://www.librechat.ai/docs/configuration/librechat_yaml/object_structure/agents#recursionlimit

**Comment by Futyn-Maker** [comment]
Hi! I encountered this when using MCP servers directly in the chat, without configuring the agent - this is convenient for quick tests, where, nevertheless, there are often many requests. Is it possible to solve this problem when the MCP is working in a chat?

**Reply by danny-avila** [reply]
Add a higher recursion limit. This applies to all LLMs 

https://www.librechat.ai/docs/configuration/librechat_yaml/object_structure/agents#recursionlimit

**Comment by Futyn-Maker** [comment]
@danny-avila Thank you for your promptness! Unfortunately, it doesn't work in the chat:(

```yaml
interface:
  prompts: true
  parameters: true
  
  presets: false
  agents: false
  fileSearch: false
  runCode: false
  webSearch: false
  
  endpointsMenu: true
  modelSelect: true
  sidePanel: true
...

endpoints:
  custom:
...
  agents:
    recursionLimit: 100
    maxRecursionLimit: 100
    disableBuilder: true  # I do not need an agent functional in fact
...
```

When using the MCP server in a chat with a model, I still encounter the same error at some point.:

```
Something went wrong. Here's the specific error message we encountered: An error occurred while processing the request: Recursion limit of 25 reached without hitting a stop condition. You can increase the limit by setting the "recursionLimit" config key. Troubleshooting URL: https://langchain-ai.github.io/langgraphjs/troubleshooting/errors/GRAPH_RECURSION_LIMIT/
```
