### DISCUSSION TITLE
Generate Excel file?

### DISCUSSION THREAD

**Discussion by adrianmihalko** [danny-avila/LibreChat#5171] [Q&A]
On chatgpt.com I can generate Excel files, but when I am trying to do the same in LibreChat I get error:

_I can't directly create or send files, including Excel files. However, I can guide you on how to create an Excel file using various tools like Microsoft Excel, Google Sheets, or programming languages like Python. Let me know which method you prefer, and I can provide you with the steps or code to do so._

Currently it is not supported?

**Comment by Alan-Billi** [comment]
Any news on this ? 
This feature should be a must have!

**Comment by gaborvadasz** [comment]
Any news on this ?

**Comment by danny-avila** [comment]
https://www.librechat.ai/docs/features/code_interpreter

**Reply by Alan-Billi** [reply]
Hello @danny-avila 

I don't understand how the code interpreter could be used to tell the chatbot to put in an Excel file some data that it's generating.
Could you give me more details on the right procedure?
Thanks

**Reply by thefunny1983** [reply]
I don't like that the code_interpreter is behind a paywall without any alternative. I am in Europe working for a company which requires high security standards, for which the code-interpreter is not an option (GDPR-regulations, storage of data outside of the EEA and such).

**Reply by jasongilman** [reply]
You can pay them to get access to a self hosted version of it and deploy it yourself into your own environment.

**Comment by dvejsada** [comment]
You can try: [https://github.com/dvejsada/mcp-ms-office-documents](https://github.com/dvejsada/mcp-ms-office-documents)

**Reply by jasongilman** [reply]
This looks awesome. I was thinking about creating something similar that could work with existing MS Office Documents. Does Librechat have the ability to send a full file to an MCP server?

**Reply by dvejsada** [reply]
> This looks awesome. I was thinking about creating something similar that could work with existing MS Office Documents. Does Librechat have the ability to send a full file to an MCP server?

Not yet, there is however a request to implement it. However this would be the easy part, the actual modification of the file would be the hard one (especially when working with docx files is quite cumbersome in general).

**Reply by jasongilman** [reply]
Do you happen to know which issue or discussion contains the request to implement it?

**Reply by dvejsada** [reply]
> Do you happen to know which issue or discussion contains the request to implement it?

#8301

**Reply by Alan-Billi** [reply]
Hey @dvejsada 
i've installed and runned your MCP server but Librechat is not able to connect.
At launch it tries 3 times and fail.

> 2025-09-04T10:56:34.114Z debug: [MCP][office-docs] Transport sending: {"method":"initialize","params":{"protocolVersion":"2025-06-18","capabilities":{},"clientInfo":{"name":"@librech... [truncated]

This is the server URL i see in the container terminal 
🔗 Server URL:      [http://0.0.0.0:8958/mcp⁠](http://0.0.0.0:8958/mcp)

so this is my config in the librechat.yml file 

```
mcpServers:
  office-docs:
    type: streamable-http
    url: http://0.0.0.0:8958/mcp  # Adjust URL if running on different host
    timeout: 120000  # Allow extra time for document generation
```

Am I missing something ?

**Reply by dvejsada** [reply]
> Hey @dvejsada 
> i've installed and runned your MCP server but Librechat is not able to connect.
> At launch it tries 3 times and fail.
> 
> > 2025-09-04T10:56:34.114Z debug: [MCP][office-docs] Transport sending: {"method":"initialize","params":{"protocolVersion":"2025-06-18","capabilities":{},"clientInfo":{"name":"@librech... [truncated]
> 
> This is the server URL i see in the container terminal 
> 🔗 Server URL:      [http://0.0.0.0:8958/mcp⁠](http://0.0.0.0:8958/mcp)
> 
> so this is my config in the librechat.yml file 
> 
> ```
> mcpServers:
>   office-docs:
>     type: streamable-http
>     url: http://0.0.0.0:8958/mcp  # Adjust URL if running on different host
>     timeout: 120000  # Allow extra time for document generation
> ```
> 
> Am I missing something ?

It has to be http://localhost:8958/mcp if running locally on your computer. Port 8958 must be also published to host from container.

**Reply by Alan-Billi** [reply]
Thanks for your suggestion.
I was missing 2 things : 
- connect the office-docs container to the same network as my librechat container
- modify the url in the config file with the container name like this http://mcp-office-docs:8958/mcp

Now I can see the new actions available in the chat window and on the agents configuration.
I was able to ask for a document and run the function call : create_word_from_markdown

This was the answer from your MCP Server 
```
[
  {
    "type": "text",
    "text": "Inform user that the document 53f3515a-2cba-425f-906e-fb2070291a88.docx was saved to his output folder."
  }
]
```


The file has been correctly generated in the /app/output folder of my office-docs container , but the link created within Librechat is incorrect : http://localhost:3080/file-server/output/53f3515a-2cba-425f-906e-fb2070291a88.docx


First the domain should be the linking to the mcp-office-docs container and not Librechat itself.
Any idea on how to fix this generated link?

Thanks a lot!

**Reply by Alan-Billi** [reply]
For now I've managed to resolve this by creating a web server on the same container, share a volume between your ms-office-docs container and the web one so the web server is exposing the output folder through a url, and then give instructions to my agent to build the url. 

Here is my docker-compose file 

```
services:
  web:
    image: python:3.9-slim
    working_dir: /app/output
    volumes:
      - shared-output:/app/output # Mount the /app folder
    command: python -m http.server 8888 # Start a simple HTTP server on port 8888
    ports:
      - "8888:8888" # Expose port 8080
  mcp-office-docs:
    platform: linux/x86_64
    image: georgx22/mcp-office-docs:latest
    container_name: mcp-office-docs
    restart: always
    ports:
      - "8958:8958"
    networks:
      - librechat_default
    environment:
      UPLOAD_STRATEGY: LOCAL # LOCAL or S3
      AWS_ACCESS_KEY: Your AWS access key # Required for S3 upload strategy
      AWS_REGION: Your AWS region, e.g. us-east-1 # Required for S3 upload strategy
      AWS_SECRET_ACCESS_KEY: Your AWS secret access key # Required for S3 upload strategy
      S3_BUCKET: Name of your AWS S3 bucket # Required for S3 upload strategy
    volumes:
      - shared-output:/app/output # Directory to save created presentations to, required for LOCAL upload strategy
      - /app/templates # Directory with custom templates, if used
      - /app/config # Directory with config.yaml for email styling customization, optional

networks:
  librechat_default:
    external: true

volumes:
  shared-output:
```

**Comment by geodanchev** [comment]
Hi everyone,

I have been working on the same use case discussed here: allowing LibreChat users to generate Word, Excel, PowerPoint, and other files through an MCP server.

The `mcp-ms-office-documents` server can already generate DOCX, XLSX, PPTX, EML, and XML files. However, the current approaches require exposing an output folder through a separate web server, using external cloud storage, or returning a manually constructed URL.

I implemented a prototype that integrates the MCP server directly with LibreChat’s file storage.

## Proposed functionality

An MCP tool can generate a file on behalf of the current LibreChat user, upload it to LibreChat, and return it as a native downloadable attachment in the chat.

The flow is:

```text
User requests a document
        ↓
LibreChat calls the MCP tool
        ↓
MCP server generates the file
        ↓
MCP server uploads it to LibreChat
        ↓
LibreChat stores it under the current user
        ↓
The file appears in the assistant message
```

From the user’s perspective, it works similarly to generated files in ChatGPT: the document appears directly in the conversation and can be downloaded without exposing a separate file server.

## Security and user isolation

The implementation includes:

* Service-to-service authentication between the MCP server and LibreChat
* User ownership assigned when the file is uploaded
* Optional conversation association
* Access controlled through LibreChat rather than a public URL
* Missing user context rejected by default
* Support for LibreChat’s existing file-storage strategy
* Temporary upload-file cleanup

LibreChat passes the user context to the MCP server through headers such as:

```yaml
headers:
  X-User-Id: "{{LIBRECHAT_USER_ID}}"
  X-User-Email: "{{LIBRECHAT_USER_EMAIL}}"
```

The MCP server then uploads the generated file to an internal LibreChat endpoint using a separate service token.

## MCP artifact response

The MCP tool returns structured file metadata:

```json
{
  "result": {
    "message": "Document created successfully.",
    "file": {
      "file_id": "uuid-string",
      "filename": "report.xlsx",
      "mimeType": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
      "bytes": 12345,
      "source": "local"
    }
  }
}
```

LibreChat recognizes this response and attaches the file to the corresponding assistant message.

## Why this may be useful upstream

This would not be limited to Microsoft Office documents. The same mechanism could support any MCP server that generates files, including:

* PDF reports
* CSV exports
* ZIP archives
* Images
* Source-code packages
* Data exports
* Generated email files

It would provide a standard output path:

```text
MCP server → LibreChat storage → user-scoped chat attachment
```

This is complementary to proposals that allow MCP servers to access files uploaded by users. Together, these capabilities would provide bidirectional file exchange between LibreChat and MCP tools.

I already have a working implementation across both LibreChat and the MCP Office Documents server. I would be happy to prepare the changes as an upstream pull request if the maintainers are interested in this approach.

Would this architecture be acceptable for LibreChat, or would you prefer generated MCP files to be returned through a different artifact protocol?
