### DISCUSSION TITLE
Update perplexity.mdx

### DISCUSSION THREAD

**Discussion by Medenor** [danny-avila/LibreChat#5201] [Feature Requests & Suggestions]
File to update : pages/docs/configuration/librechat_yaml/ai_endpoints/perplexity.mdx
Reason to update : Alignment with https://docs.perplexity.ai/guides/model-cards current available models

```
- **Known issue:** fetching list of models is not supported.
- API may be strict for some models, and may not allow fields like `stop` and `frequency_penalty` may cause an error when set to 0, in which case, you should use [`dropParams`.](./custom_config.md#dropparams)
- The example includes a model list, which was last updated on 30 December 2024, for your convenience.

```yaml
    - name: "Perplexity"
      apiKey: "${PERPLEXITY_API_KEY}"
      baseURL: "https://api.perplexity.ai/"
      models:
        default: [
          "llama-3.1-sonar-small-128k-online",
          "llama-3.1-sonar-large-128k-online",
          "llama-3.1-sonar-huge-128k-online"
          ]
        fetch: false # fetching list of models is not supported
      titleConvo: true
      titleModel: "llama-3.1-sonar-small-128k-online"
      summarize: false
      summaryModel: "llama-3.1-sonar-small-128k-online"
      forcePrompt: false
      dropParams: ["stop", "frequency_penalty"]
      modelDisplayLabel: "Perplexity"
```
