### DISCUSSION TITLE
modelspec unselected after webpage refresh

### DISCUSSION THREAD

**Discussion by cjccjj** [danny-avila/LibreChat#5231] [Troubleshooting]
### What happened?

modelspec becomes unselected after webpage refresh. 
Therefore, cannot continue a convo without reselect a modelspecs. Also, cannot continue a convo from left panel convo history without reselect a modelspecs again.

I expect the same modelspec remain selected. And I expect if I click on a historical convo from left panel, the modelspecs that used be selected automatically.

### Steps to Reproduce

1. start a converstaion with a selected modelspec
2. refresh webpage

### What browsers are you seeing the problem on?

Chrome

### Screenshots

https://github.com/user-attachments/assets/2670117d-cfe0-45f9-9eeb-d205d07ae34a

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Hi, this can't be recreated. It would be helpful if you shared your config file to see what's going on.

https://github.com/user-attachments/assets/e8d3591f-1da9-4f44-a621-79a4546173b3

My config here:
```yaml
modelSpecs:
  enforce: false
  prioritize: false
  list:
    - name: "Max"
      label: "Max"
      description: "Smartest model"
      iconURL: "https://code.librechat.ai/_next/image?url=%2Ficon.png&w=32&q=75"
      preset:
        endpoint: "bedrock"
        modelLabel: "Max"
        model: "anthropic.claude-3-haiku-20240307-v1:0"
        greeting: |
          Hello there!
```

Also note the difference that setting `prioritize: true` makes here (you will not get "None selected" on New Chat):


https://github.com/user-attachments/assets/27800247-962b-4353-9f63-510baec01aad


A similar effect can be made with `prioritize: false` and the `default` model spec option:

https://www.librechat.ai/docs/configuration/librechat_yaml/object_structure/model_specs#default

My config in this last case:

```yaml
modelSpecs:
  enforce: false
  prioritize: false
  list:
    - name: llama3.3:latest
      label: "Llama 3.3"
      iconURL: https://cdn1.cloud.e-infra.cz/logos/meta-llama.png
      showIconInMenu: true
      default: true
      preset:
        endpoint: "Ollama"
        model: "llama3.3:latest"
        maxContextTokens: 128000
        max_tokens: 16384
    - name: "Max"
      label: "Max"
      description: "Smartest model"
      iconURL: "https://code.librechat.ai/_next/image?url=%2Ficon.png&w=32&q=75"
      preset:
        endpoint: "bedrock"
        modelLabel: "Max"
        model: "anthropic.claude-3-haiku-20240307-v1:0"
        greeting: |
          Hello there!
```

Please review the documentation as it was recently updated:
https://www.librechat.ai/docs/configuration/librechat_yaml/object_structure/model_specs

Make sure you are up to date as there were improvements to model specs made this week, and you may be experiencing an issue before these changes.

**Reply by cjccjj** [reply]
I tried to look into the the mongoDB, I expect to see some data that marks a conversation to a certain modelSpec, however, I can't find any in my conversations table. 

a conversation record using modelSpecs, no info relate to modelSpecs (like name or label) can be found. the conversationtags table are also completely empty (I don't use bookmark, but not sure if tag is also related to modelSpecs). looks like modelSpecs info are not saving to DB?

```
{
  "_id": {
    "$oid": "678150997a357422ed6aa1d7"
  },
  "conversationId": "88ba9011-2639-47d0-9f8f-173ea941739c",
  "user": "66ff91ec8b0ed79db67e97f0",
  "__v": 0,
  "_meiliIndex": true,
  "assistant_id": "asst_WxMcOTBAchgcmDf6AfPXcQSs",
  "createdAt": {
    "$date": "2025-01-10T16:53:45.572Z"
  },
  "endpoint": "assistants",
  "files": [],
  "isArchived": false,
  "messages": [
    {
      "$oid": "678150997a357422ed6aa1d6"
    },
    {
      "$oid": "6781509d7a357422ed6aa1d9"
    },
    {
      "$oid": "678152317a357422ed6aa1da"
    },
    {
      "$oid": "678152357a357422ed6aa1db"
    }
  ],
  "model": "gpt-4o",
  "tags": [],
  "title": "Greeting And Assistance Inquiry",
  "updatedAt": {
    "$date": "2025-01-10T17:00:37.269Z"
  }
}
```

**Comment by cjccjj** [comment]
Hi, thanks for the help!

I included my configuration below, along with some interface settings that may be relevant. It is running the latest Docker image on a DigitalOcean droplet. And using Cloudflare to proxy the domain.

I had also reviewed the recent update/issues discussion regarding modelSpecs, particularly about the default selection. The default selection when creating new conversations works fine.

My config:
```YAML
# interface configurations
interface:
# # Config UI elements for using modelSpecs
    endpointsMenu: false
    modelSelect: false
    parameters: false
    sidePanel: true
    presets: false
    prompts: true
    bookmarks: false
    multiConvo: false
    agents: false

# Config of modelSpces
modelSpecs:
  enforce: false
  prioritize: true
  list:
     - name: "Quick_Chat"
       label: "Quick Chat"
       default: true
       description: "Quick Chat with gpt-4o"
       iconURL: "https://QuickChat.png"
       showIconInMenu: true
       showIconInHeader: true
       preset:
         endpoint: "assistants"
         assistant_id: "asst_WxMcTBAchgcDf6AfPXQSs"
         model: "gpt-4o"
     - name: "Image_Chat"
       label: "Image Chat"
       description: "Draw image with gpt-4o & Dall-E 3"
       iconURL: "https://ImageChat.png"
       showIconInMenu: true
       showIconInHeader: true
       preset:
         endpoint: "assistants"
         assistant_id: "asst_5FnGDJK0oCKGvbVt4859S"
         model: "gpt-4o"
     - name: "ChatGPT_latest"
       label: "ChatGPT latest"
       description: "the current version of ChatGPT"
       iconURL: "https://gpt.png"
       showIconInMenu: true
       showIconInHeader: true
       preset:
         endpoint: "openAI"
         model: "gpt-4o-latest"
     - name: "o1-mini"
       label: "o1-mini"
       description: "complex tasks and problems - mini"
       iconURL: "https://o1m.png"
       showIconInMenu: true
       showIconInHeader: true
       preset:
         endpoint: "openAI"
         model: "o1-mini"
     - name: "o1-preview"
       label: "o1-preview"
       description: "complex tasks and problems - full"
       iconURL: "https://o1p.png"
       showIconInMenu: true
       showIconInHeader: true
       preset:
         endpoint: "openAI"
         model: "o1-preview"
```
