### DISCUSSION TITLE
Custom Icons for Custom Enpoints

### DISCUSSION THREAD

**Discussion by goldenroostergigi** [danny-avila/LibreChat#5257] [Q&A] [answered]
I see we can add Icons to models, but I can't find in the docs how to add the icon for a custom endpoint. Example is that custom endpoints like OpenRouter, Mistral or Groq have custom icons but this feature is not defined in librechat.yaml

**Comment by fuegovic** [comment, marked as answer]
here's how you can specify icons on custom endpoints: https://www.librechat.ai/docs/configuration/librechat_yaml/object_structure/custom_endpoint#iconurl

**Reply by goldenroostergigi** [reply]
thank you!

**Comment by danny-avila** [comment]
Some, like the ones you mentioned (OpenRouter, Mistral or Groq) will use their recognized icons just based on the `name` value you specify

e.g.:

![chrome_Y91kyusENa](https://github.com/user-attachments/assets/379ddacb-4c88-4cac-b66f-ae66b15e9ffc)


The `iconURL` field can also be specified as one of the main endpoint names in order to user their respective icons.

Normally, OpenRouter would use its icon as determined by the name, but configuring this way, we can make it use the OpenAI icon.

![chrome_Lxk7BkjCdH](https://github.com/user-attachments/assets/b9f9da0c-d632-4b3b-aa3c-5ba104ba91d3)
```yaml
    # openrouter.ai
    - name: "OpenRouter"
      apiKey: "user_provided"
      baseURL: "https://openrouter.ai/api/v1"
      iconURL: openAI
```
