### DISCUSSION TITLE
Unable to chat with an Agent

### DISCUSSION THREAD

**Discussion by LufinityLucas** [danny-avila/LibreChat#5286] [Troubleshooting]
### What happened?

I have enabled the Agent Builder and created an agent named `Test`. However, when chatting with it, I get error `Something went wrong. Here's the specific error message we encountered: No model spec selected`. Indeed no model spec is selected in the top menu:

![image](https://github.com/user-attachments/assets/b0e58ee3-1109-4d55-a27b-54456e880a1c)

If I select a model spec (I have two of them configured in the YAML file), the endpoint changes back to my `Azure OpenAI`. Selecting the `Agent` endpoint again and now a model spec is selected:

![image](https://github.com/user-attachments/assets/2468352c-461f-460f-b796-033c7450c6ce)

However, when chatting now I get error `Something went wrong. Here's the specific error message we encountered: Model spec mismatch`.

Relevant parts from my YAML file:

```
...
interface:
  endpointsMenu: true
  modelSelect: true
  parameters: false
  sidePanel: true
  presets: false
  prompts: true
  bookmarks: true
  multiConvo: false
...
modelSpecs:
  enforce: false
  prioritize: false
  list:
    - name: "ada-gpt"
      label: "Ada"
      preset:
        default: true
      ...
...
```

I don't know if I have a specific set of configuration settings causing this, or if it's actually a bug. I would suspect no model spec to be selected when using your own agent.

### Steps to Reproduce

1. Configure the YAML file as per above
2. Add two specs to the `modelSpecs` section, where one is set to default
3. Go to the web UI and start a new chat.
4. Select `Agent` from the endpoint menu.
5. Select an agent (or create a new one using the Agent Builder and select it)
6. Write something to the bot. Observere the error.
7. Select a model spec, and change back to `Agent` in the endpoint menu.
8. Write something to the bot. Observe the error.

### What browsers are you seeing the problem on?

Microsoft Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
This could not be reproduced, see my video:
https://github.com/user-attachments/assets/1f9f7845-0bb4-4dde-812a-295c5e74db9a

This is relevant part of my config, matching what you wrote:

```yaml
interface:
  endpointsMenu: true
  modelSelect: true
  parameters: false
  sidePanel: true
  presets: false
  prompts: true
  bookmarks: true
  multiConvo: false
modelSpecs:
  enforce: false
  prioritize: false
  list:
    - name: "Phi4"
      label: "Phi4"
      iconURL: https://cdn1.cloud.e-infra.cz/logos/meta-llama.png
      showIconInMenu: true
      showIconInHeader: true
      preset:
        endpoint: "Ollama"
        model: "phi4:latest"
        modelLabel: "Phi4"
        maxContextTokens: 15000
    - name: "Max"
      label: "Max"
      default: true
      description: "Smartest model"
      iconURL: "https://code.librechat.ai/_next/image?url=%2Ficon.png&w=32&q=75"
      preset:
        endpoint: "bedrock"
        modelLabel: "Max"
        model: "anthropic.claude-3-haiku-20240307-v1:0"
        greeting: |
          Hello there!
```

Try updating, as there were many fixes to modelSpecs in the last week:

https://www.librechat.ai/docs/local/docker#update-librechat
