### DISCUSSION TITLE
Enhancement: Add default model setting for each user

### DISCUSSION THREAD

**Discussion by TedLin1993** [danny-avila/LibreChat#5291] [Feature Requests & Suggestions]
### What features would you like to see added?

Add default model setting for each user

### More details

It seems LibreChat is missing the ability for users to choose a default model through the UI. This means that new chats always start with the model from the previous conversation. It would be great to have a default model setting;it feels like a core feature. 

I've also experimented with modelSpecs to try and set a global default, but I haven't been able to get it working. Is there a way to set a default model in LibreChat? I'm hoping to use google gemini-2.0-flash-exp as the default.

### Pictures

Hoping each user can set default model by a button, like this:
![image](https://github.com/user-attachments/assets/fcd76d8e-eff9-451e-9af4-e51f0dea52cb)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
> I've also experimented with modelSpecs to try and set a global default, but I haven't been able to get it working

Please give it a try, as this is the way to do it:

![image](https://github.com/user-attachments/assets/0fbc9262-037a-431c-8bcd-9495acefe898)


This is the minimal `librechat.yaml` configuration you would need for this (while still allowing all other features, providers, models):

```yaml
version: 1.2.1
cache: true
interface:
  endpointsMenu: true
  modelSelect: true
  parameters: true
  sidePanel: true
  presets: true
  prompts: true
  bookmarks: true
  multiConvo: true
modelSpecs:
  enforce: false
  prioritize: false
  list:
    - name: "Google: Gemini 2.0 Flash Experimental"
      label: "Google: Gemini 2.0 Flash Experimental"
      showIconInMenu: true
      showIconInHeader: true
      default: true
      preset:
        endpoint: "google"
        model: "gemini-2.0-flash-exp"
        modelLabel: "Google: Gemini 2.0 Flash Experimental"
```

Make sure `google` is included in your .env file `ENDPOINTS` environment variable, as well as `GOOGLE_KEY` and `GOOGLE_MODELS` match expectations:

```.env
ENDPOINTS=google,agents
GOOGLE_KEY=someKey
# Gemini API
GOOGLE_MODELS=gemini-2.0-flash-exp,gemini-2.0-flash-thinking-exp-1219,gemini-exp-1206,gemini-exp-1121,gemini-exp-1114,gemini-1.5-pro-002,gemini-1.5-flash-latest,gemini-1.0-pro,gemini-1.0-pro-001,gemini-1.0-pro-latest,gemini-1.0-pro-vision-latest,gemini-1.5-pro-latest,gemini-pro,gemini-pro-vision

```
