### DISCUSSION TITLE
[Bug]: iconURL cannot be loaded from npmmirror

### DISCUSSION THREAD

**Discussion by zjjxwhh** [danny-avila/LibreChat#5297] [Troubleshooting]
### What happened?

When I specify the iconURL in `librechat.yaml` as a CDN link from **npmmirror**, the icon fails to display, and the browser's developer tools indicate `net::ERR_BLOCKED_BY_ORB`. However, when I specify it as a CDN link from **UNPKG**, the icon displays correctly. If I directly access the CDN links from **npmmirror** and **UNPKG** in the browser, the icons can both be displayed normally.

### Steps to Reproduce

Configure the iconURL for endpoints in `librechat.yaml` as a CDN link from **npmmirror**

```yaml
endpoints:
  custom:
    - name: "DeepSeek"
      apiKey: "${OPENAI_API_KEY}"
      baseURL: "${OPENAI_REVERSE_PROXY}"
      iconURL: "https://registry.npmmirror.com/@lobehub/icons-static-svg/latest/files/icons/deepseek-color.svg"
      # iconURL: "https://unpkg.com/@lobehub/icons-static-svg@latest/icons/deepseek-color.svg"
      models:
        default: ["deepseek-free-api"]
        fetch: false
      titleConvo: true
      titleMethod: "completion"
      titleModel: "gpt-4o-mini"
      summarize: false
      summaryModel: "gpt-4o-mini"
      forcePrompt: false
      modelDisplayLabel: "DeepSeek"
      dropParams:
        - "stop"
        - "user"
        - "presence_penalty"
        - "frequency_penalty"
```

I provided two iconURLs for testing. The first one, the npmmirror link, fails to display properly, while the second one, the commented-out UNPKG link, displays correctly.

### What browsers are you seeing the problem on?

Chrome, Mobile (iOS)

### Relevant log output

```shell
no errors reported in the Docker container logs
```

### Screenshots

![image](https://github.com/user-attachments/assets/1cb1ae00-f985-4324-9a93-89832756cfe4)

![image](https://github.com/user-attachments/assets/7121b390-b6ae-4ea4-b848-bb2d0fdbe124)

![image](https://github.com/user-attachments/assets/9fbcf196-8d5c-4305-a7cb-f07f82a99298)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
