### DISCUSSION TITLE
Azure OpenAI o1 model has no vision support?

### DISCUSSION THREAD

**Discussion by aadishj19** [danny-avila/LibreChat#5321] [Troubleshooting]
### What happened?

when I upload an image to Azure o1, it immediately replies in a second which led me to check the logs. I believe it Is it using 4o instead?

In the console I see this when I only use text:

LibreChat         |   id: "chatcmpl-AprNJUwupj6EdgSR5yoRRTnjJPVJT",
LibreChat         |   model: "o1-2024-12-17",
LibreChat         |   object: "chat.completion",

However when I insert an image:

LibreChat         |   id: "chatcmpl-AprLzmEtslgjQZjjupoiNYRsM2Esu",
LibreChat         |   model: "gpt-4o-2024-08-06",
LibreChat         |   object: "chat.completion",

I guess its using 4o? I thought with the o1 we can now also use vision with it, right? Do note that I have the updated version of the repo as I noticed a similar issue was raised for the openAI o1 model a few days ago. However, even after updating, the issue remains.

### Steps to Reproduce

1. Choose Azure OpenAI o1 model
2. Upload an image and notice it'll immediately reply without spending any time reasoning.
3. Check the console debug logs.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
![chrome_5kJ9uuzYBI](https://github.com/user-attachments/assets/13216ecc-bf13-43c8-953c-b7183af658a7)
```yaml
    - group: "region-eastus"
      apiKey: "${EASTUS_API_KEY}"
      instanceName: "my_instance_name"
      version: "2024-12-01-preview" # latest version
      models:
        o1-mini:
          deploymentName: "o1-mini"
        o1-preview:
          deploymentName: "o1-preview"
    - group: "region-sweden"
      apiKey: "${SWEDEN_API_KEY}"
      instanceName: "my_instance_name"
      version: "2024-12-01-preview" # latest version
      models:
        o1-2024-12-17:
          deploymentName: "o1"
```

Currently, o1-mini is not considered a vision model so it will switch to `gpt-4o`. If I override this, using o1-mini, you'll get this error, which is from Azure:
```bash
2025-01-16T01:05:08.594Z error: [OpenAIClient.chatCompletion] Unhandled error type Error: 400 Invalid content type. image_url is only supported by certain models.
```
same with o1-preview:

```bash
2025-01-16T01:07:24.748Z error: [OpenAIClient.chatCompletion] Unhandled error type Error: 400 Invalid content type. image_url is only supported by certain models.
```

Same issue with o1-mini and o1-preview on OpenAI (not azure):

```
2025-01-16T01:08:51.189Z error: [handleAbortError] AI response error; aborting request: 400 Invalid content type. image_url is only supported by certain models.
```

-- 

TL;DR only o1 and not `-preview` or `-mini` will work

https://oai.azure.com/resource/models/o1/version/2024-12-17/registry/azure-openai
