### DISCUSSION TITLE
Plugin store can not be opened from 0.7.5 or 0.7.6

### DISCUSSION THREAD

**Discussion by elvis-cai** [danny-avila/LibreChat#5335] [Q&A]
Hi team

I am not sure if it's related to it being replaced by Agent mode soon, when I click plugin store, nothing happened
<img width="528" alt="image" src="https://github.com/user-attachments/assets/672ebdde-d2c3-468a-87a7-673414f66de0" />
Thanks.

**Comment by elvis-cai** [comment]
```
       interface:
         modelSelect: true
         endpointsMenu: true
-        parameters: false
+        parameters: true
         sidePanel: true
         presets: false
       modelSpecs:
```
all good now
