### DISCUSSION TITLE
UI Text overflow on mobile: "Message [...] or type "@" to switch AI"

### DISCUSSION THREAD

**Discussion by ThomasBaruzier** [danny-avila/LibreChat#5373] [Feature Requests & Suggestions]
### What happened?

Hello, here's a bug i encountered since updating a few days ago:

![Image](https://github.com/user-attachments/assets/393cf991-9858-41eb-870d-2f8cddfcb126)

Disabling the "@" command in the UI settings doesn't change this placeholder message, but it would be best if we were able to disable help hints all together.
I'd rather have "Message [...]" as a placeholder than a two lines tall input box.

Have a great day.

### Steps to Reproduce

Using any model spec, haven't tried without:
```
    - name: 'cohere-command-r-plus-08-2024'
      label: 'EXAMPLE'
      description: 'Command-R Plus'
      preset:
        default: false
        endpoint: 'Cohere'
        model: 'command-r-plus-08-2024'
        maxContextTokens: 131072
        max_tokens: 4096
        temperature: 0.0
        top_p: 0.7
        top_k: 10
        frequency_penalty: 0
        presence_penalty: 0
        resendFiles: false
        imageDetail: 'low'
        modelLabel: 'EXAMPLE'
```

### What browsers are you seeing the problem on?

Firefox mobile

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
