### DISCUSSION TITLE
Why Do File Inputs Only Fail in DeepSeek?

### DISCUSSION THREAD

**Discussion by kihyunnn** [danny-avila/LibreChat#5385] [Help Wanted]
I've noticed that with default embedding settings, models like GPT or Claude can process image or PDF inputs without issues. However, DeepSeek seems to struggle with this capability. My current file configuration is as follows:
```

fileConfig:
  endpoints:
    assistants:
      fileLimit: 10
      fileSizeLimit: 50
      totalSizeLimit: 200
      supportedMimeTypes:
        - "application/pdf"
        - "image/.*"
    openAI:
      disabled: false
    default:
      totalSizeLimit: 20
  serverFileSizeLimit: 100
  avatarSizeLimit: 2
```
Despite this setup, DeepSeek does not handle image or PDF inputs effectively. Can anyone explain why this difference exists? Are there any specific configurations or settings I need to adjust to enable this functionality in DeepSeek?
