### DISCUSSION TITLE
Custom groq Endpoint not showing up

### DISCUSSION THREAD

**Discussion by sorenmulli** [danny-avila/LibreChat#5387] [Troubleshooting] [answered]
### What happened?

No custom groq endpoint shows up in model selection window even though it is included in the librechat.yaml and I can see that it is applied in the log. The Azure endpoint works perfectly but there is no groq in the chat model selector
librechat.yaml
```yaml
# Configuration version (required)
version: 1.2.1
cache: true

endpoints:
  azureOpenAI:
    titleModel: "gpt-35-turbo"
    plugins: false
    assistants: false
    groups:
    - group: "<group name>"
      apiKey: "${AZURE_OPENAI_API_KEY}"
      instanceName: "<instance name>"
      version: "2024-02-15-preview"
      models:
        gpt-4o:
          deploymentName: "gpt-4o"
            #version: "2024-08-06"
        gpt-4:
          deploymentName: "gpt-4"
        gpt-35-turbo:
          deploymentName: "gpt-35-turbo"
  custom:
    - name: "groq"
      apiKey: "${GROQ_API_KEY}"
      baseUrl: "https://api.groq.com/openai/v1/"
      models:
        default: [
          "gemma2-9b-it",
          "llama-3.3-70b-versatile",
          "llama-3.1-8b-instant",
          "llama3-70b-8192",
          "llama3-8b-8192",
          "mixtral-8x7b-32768",
        ]
        fetch: false
      titleConvo: true
      titleModel: "llama-3.1-8b-instant"
      modelDisplayLabel: "groq"
```

.env, I only changed
```bash
ALLOW_REGISTRATION=false
APP_TITLE=AlvenirChat
CUSTOM_FOOTER="At udbetale løn er et maraton. Ikke en sprint."
AZURE_OPENAI_API_KEY="<KEY>"
GROQ_API_KEY="<KEY>"
```

I attempted to follow https://www.librechat.ai/docs/configuration/librechat_yaml/ai_endpoints/groq as closely as possible

### Steps to Reproduce

1. Clone
2. Use supplied librechat.yaml
3. Use supplied .env
4. Use docker override
5. `docker-compose up`

### What browsers are you seeing the problem on?

Firefox, Chrome

### Relevant log output

```shell
2025-01-21 12:50:16 info: {
  "version": "1.2.1",
  "cache": true,
  "endpoints": {
    "azureOpenAI": {
      "titleModel": "gpt-35-turbo",
      "plugins": false,
      "assistants": false,
      "groups": [
        {
          "group": "<hidden>",
          "apiKey": "${AZURE_OPENAI_API_KEY}",
          "instanceName": "<hidden>",
          "version": "2024-02-15-preview",
          "models": {
            "gpt-4o": {
              "deploymentName": "gpt-4o"
            },
            "gpt-4": {
              "deploymentName": "gpt-4"
            },
            "gpt-35-turbo": {
              "deploymentName": "gpt-35-turbo"
            }
          }
        }
      ]
    },
    "custom": [
      {
        "name": "groq",
        "apiKey": "${GROQ_API_KEY}",
        "baseUrl": "https://api.groq.com/openai/v1/",
        "models": {
          "default": [
            "gemma2-9b-it",
            "llama-3.3-70b-versatile",
            "llama-3.1-8b-instant",
            "llama3-70b-8192",
            "llama3-8b-8192",
            "mixtral-8x7b-32768"
          ],
          "fetch": false
        },
        "titleConvo": true,
        "titleModel": "llama-3.1-8b-instant",
        "modelDisplayLabel": "groq"
      }
    ]
  }
}
```

### Screenshots

![Image](https://github.com/user-attachments/assets/0ba616fe-818c-4c82-b42c-8f08ec17e533)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
