### DISCUSSION TITLE
Model Mismatch for Custom Endpoint

### DISCUSSION THREAD

**Discussion by kevindaffaarr** [danny-avila/LibreChat#5583] [Troubleshooting] [answered]
So I want to use Portkey due to the easiness for monitoring. But I got something strange:

1. LibreChat try to call OpenAI for defining the title. Below is my librechat.yaml snippet, and the screenshots of logs and the web app

```
# Definition of custom endpoints
endpoints:
  custom:
    # Portkey Google AI Studio
    - name: 'Gemini'
      apiKey: 'dummy'
      baseURL: 'https://api.portkey.ai/v1'
      headers:
        x-portkey-api-key: '${PORTKEY_API_KEY}'
        x-portkey-virtual-key: 'google-virtual-123abc'
      models:
        default: ['gemini-2.0-flash-thinking-exp','gemini-2.0-flash-exp','gemini-1.5-flash','gemini-1.5-pro','gemini-1.5-flash-8b']
        fetch: false
      titleConvo: true
      titleModel: 'gemini-1.5-flash-8b'
      modelDisplayLabel: 'Portkey: Gemini'
```

LibreChat Screenshot
![Logs](https://github.com/user-attachments/assets/1995e184-c7b4-45d2-b733-272f0ea97c73)

Logs
![LibreChat WebApp](https://github.com/user-attachments/assets/54016e2d-4df3-43d2-80c0-90045e8cf2e4)

The Portkey Virtual Key
![image](https://github.com/user-attachments/assets/e2e54ac6-974d-4da1-99c0-4e86838a6704)

2. Then I inspect the Portkey, the model called is correct, but I think this token number is very big that doesn't sounds like the testing chat.

![Chart 1 Portkey](https://github.com/user-attachments/assets/61417765-3f82-429c-992d-26c9c1e04c3b)

![Chart 2](https://github.com/user-attachments/assets/4eced6ce-c146-42c0-a635-ce8fcb4ce527)

I'm running LibreChat via docker with tutorial for local installation, although I ran it on my Debian server. The changes is on librechat.yaml, and .env for API Keys, and list of endpoint.

Please help me find the problem here.
