### DISCUSSION TITLE
Endpoint Options Not Limited by ENDPOINTS Environment Variable

### DISCUSSION THREAD

**Discussion by watarutmnh** [danny-avila/LibreChat#5587] [Troubleshooting]
## Description
When hosting on Railway, all endpoint options are displayed in the dropdown menu regardless of the `ENDPOINTS` environment variable setting. Currently, even when `ENDPOINTS` is set to `openAI,anthropic` in the Railway dashboard's environment variables, the UI continues to show all available endpoint options instead of only the specified ones.

### Steps to Reproduce

1. Deploy application to Railway
2. Set `ENDPOINTS=openAI,anthropic` in Railway dashboard environment variables
3. Access the application
4. Open the endpoint selection dropdown
5. Observe that all endpoint options are still visible

This issue appears to be specific to Railway hosting, suggesting a possible issue with environment variable handling or UI configuration when deployed on Railway.

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell

```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Does railway use Redis btw? It could be caching the response to that endpoint.

railway is also not officially supported by me but rather the community

**Reply by watarutmnh** [reply]
No, I'm not using Redis in my Railway project. Here's my current service configuration:

Services:
1. VectorDB (pgvector/pgvector:pg16)
2. RAG API (danny-avila/librechat-rag-api)
3. LibreChat (danny-avila/librechat-dev:latest)
4. Meilisearch (getmeili/meilisearch:v1.1)
5. MongoDB (mongo)

I've tried:
- Redeploying the application
- Waiting for potential cache expiration
- Checking the environment variables are correctly set

**Reply by harrylaou** [reply]
This seems to be working for me. 
<img width="933" alt="image" src="https://github.com/user-attachments/assets/3cc81f38-ec12-4889-9121-2571a591f5e9" />

Are you setting it on the variables of the librechat component?

**Reply by jedrus2000** [reply]
Struggling with this as well. Using local`docker` and Redis in my case.

LibreChat v0.8.1-rc1

<img width="559" height="532" alt="image" src="https://github.com/user-attachments/assets/5decea9d-97e5-443e-9658-14a114cf6e66" />

`.env`:

```
ENDPOINTS=custom,agents
```

`docker-compose.override.yml`:
```
services:                                                                                                                                                                                                                    
  api:                                                                                                                                                                                                                       
    volumes:                                                                                                                                                                                                                 
    - type: bind                                                                                                                                                                                                             
      source: ./librechat.yaml                                                                                                                                                                                               
      target: /app/librechat.yaml
```

`librechat.yaml`

```yaml
endpoints:                                                                                                                                                                                                                                                                                                                                                                   
  custom:                                                                                                                                                                                                                    
    # OpenRouter Example                                                                                                                                                                                                     
    - name: 'OpenRouter'                                                                                                                                                                                                     
      # For `apiKey` and `baseURL`, you can use environment variables that you define.                                                                                                                                       
      # recommended environment variables:                                                                                                                                                                                   
      apiKey: '${OPENROUTER_KEY}'                                                                                                                                                                                            
      baseURL: 'https://openrouter.ai/api/v1'                                                                                                                                                                                
      headers:                                                                                                                                                                                                               
        x-librechat-body-parentmessageid: '{{LIBRECHAT_BODY_PARENTMESSAGEID}}'                                                                                                                                               
      models:                                                                                                                                                                                                                
        default:                                                                                                                                                                                                             
          - 'anthropic/claude-sonnet-4.5'                                                                                                                                                                                    
        fetch: true                                                                                                                                                                                                          
      titleConvo: true                                                                                                                                                                                                       
      titleModel: 'current_model'                                                                                                                                                                                            
      # Recommended: Drop the stop parameter from the request as Openrouter models use a variety of stop tokens.                                                                                                             
      dropParams:                                                                                                                                                                                                            
        - 'stop'                                                                                                                                                                                                             
      modelDisplayLabel: 'OpenRouter'       
```
