### DISCUSSION TITLE
Super-simple single-file docker compose

### DISCUSSION THREAD

**Discussion by jyio** [danny-avila/LibreChat#5617] [Feature Requests & Suggestions]
First of all, thank you for sharing this amazing piece of software.

I struggled to get it working because my workflow does not support the use of environment files and bind mounts. After reading the recommended compose/environment files, taking some hints from this [Coolify discussion](https://github.com/coollabsio/coolify/discussions/2867), and throwing spaghetti at the wall... this is what stuck for me:

```yaml
x-env-scalars:
  - &x-env-fulltextdb-key MEILISEARCH-SECRET-0123456789ABCDEF
x-env-vectordb: &x-env-vectordb
  POSTGRES_DB: librechat-db
  POSTGRES_USER: librechat-user
  POSTGRES_PASSWORD: librechat-password
x-env-apikeys: &x-env-apikeys
  #OPENAI_API_KEY: ${OPENAI_API_KEY:-user_provided}
  #ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY:-user_provided}
  #GOOGLE_KEY: ${GOOGLE_API_KEY:-user_provided}
  #BINGAI_TOKEN: ${BINGAI_TOKEN:-user_provided}
  #ASSISTANTS_API_KEY: ${ASSISTANTS_API_KEY:-user_provided}
  #MISTRAL_API_KEY: ${MISTRAL_API_KEY:-user_provided}
  #GROQ_API_KEY: ${GROQ_API_KEY:-user_provided}
  #PERPLEXITY_API_KEY: ${PERPLEXITY_API_KEY:-user_provided}
  #ANYSCALE_API_KEY: ${ANYSCALE_API_KEY:-user_provided}
  #TOGETHERAI_API_KEY: ${TOGETHERAI_API_KEY:-user_provided}
  #DEEPSEEK_API_KEY: ${DEEPSEEK_API_KEY:-user_provided}
  _ : _

services:
  main:
    image: ghcr.io/danny-avila/librechat-dev:latest
    user: '${UID:-1000}:${GID:-1000}'
    environment:
      << : *x-env-apikeys
      DOMAIN_CLIENT: https://librechat.example.com
      DOMAIN_SERVER: https://librechat.example.com
      MONGO_URI: mongodb://docdb:27017/LibreChat
      SEARCH: 'true'
      MEILI_HOST: http://fulltextdb:7700
      MEILI_MASTER_KEY: *x-env-fulltextdb-key
      RAG_API_URL: http://rag-api:${RAG_PORT:-8000}
      CONFIG_PATH: /config/librechat.yaml
      # Authentication
      JWT_SECRET: 0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef
      JWT_REFRESH_SECRET: fedcba9876543210fedcba9876543210fedcba9876543210fedcba9876543210
      # Encryption
      CREDS_KEY: 456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123
      CREDS_IV: 3210fedcba9876543210fedcba987654
    ports:
      - '3080:3080'
    volumes:
      - config:/config:ro
      - images:/app/client/public/images
      - logs:/app/api/logs
    depends_on:
      docdb:
        condition: service_healthy
      rag-api:
        condition: service_healthy
    healthcheck:
      test:
        - CMD
        - wget
        - --no-verbose
        - --tries=1
        - --spider
        - http://127.0.0.1:3080/api/health
      interval: 5s
      timeout: 10s
      retries: 3
    restart: always
  rag-api:
    image: ghcr.io/danny-avila/librechat-rag-api-dev-lite:latest
    environment:
      OPENAI_API_KEY: user_provided
      << : [*x-env-vectordb, *x-env-apikeys]
      DB_HOST: vectordb
      RAG_PORT: ${RAG_PORT:-8000}
    depends_on:
      vectordb:
        condition: service_healthy
    healthcheck:
      test:
        - CMD
        - sh
        - -c
        - "printf 'GET /health HTTP/1.0\r\nHost: 127.0.0.1\r\n\r\n' | nc -w4 127.0.0.1 ${RAG_PORT:-8000}"
      interval: 5s
      timeout: 20s
      retries: 10
    restart: always
  docdb:
    image: mongo
    user: '${UID:-1000}:${GID:-1000}'
    command: mongod --noauth
    volumes:
      - docdb:/data/db
    healthcheck:
      test:
        - CMD
        - mongosh
        - --eval
        - db.runCommand('ping').ok
        - 127.0.0.1:27017/test
        - --quiet
      interval: 5s
      timeout: 10s
      retries: 3
    restart: always
  fulltextdb:
    image: getmeili/meilisearch:v1.12.3
    user: '${UID:-1000}:${GID:-1000}'
    environment:
      MEILI_ENV: production
      MEILI_NO_ANALYTICS: 'true'
      MEILI_MASTER_KEY: *x-env-fulltextdb-key
    volumes:
      - fulltextdb:/meili_data
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://127.0.0.1:7700/health
      interval: 2s
      timeout: 10s
      retries: 15
    restart: always
  vectordb:
    image: ankane/pgvector:latest
    environment:
      << : *x-env-vectordb
    volumes:
      - vectordb:/var/lib/postgresql/data
    healthcheck:
      test:
        - CMD
        - pg_isready
        - '--host=127.0.0.1'
        - '--port=5432'
      interval: 2s
      timeout: 1m
      retries: 5
      start_period: 10s
    restart: always
volumes:
  config:
  docdb:
  fulltextdb:
  vectordb:
  images:
  logs:
```

To mitigate repetition without using an environment file, we use anchors and aliases. To avoid the bind-mounted config file, we allow it to live in its own volume as `/config/librechat.yaml`. Health checks are optional. You should change the secrets before using, obviously. I've dispensed with the UID/GID settings because I already have the userns remapped, and I have some additional environment variables to enable SSO, but that's out of scope here.

I hope this could be a starting point for a more flexible deployment template.
