### DISCUSSION TITLE
[Question]: How to use o3-mini-hight

### DISCUSSION THREAD

**Discussion by k-toki** [danny-avila/LibreChat#5623] [Q&A]
### What is your question?

Please tell me how to use o3-mini-hight as I could not find a way to do this, although it may have been answered elsewhere.

### More Details

none

### What is the main subject of your question?

Endpoints

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by chemeris** [comment]
Starting the most recent dev image I believe you can just use o3-mini and choose "high" reasoning effort at the bottom of the model parameters:

![Image](https://github.com/user-attachments/assets/7a130309-98f4-42fb-b982-61d54029bb3b)

**Comment by danny-avila** [comment]
This might be helpful: https://platform.openai.com/docs/guides/reasoning#advice-on-prompting

**Comment by khfung** [comment]
I use modelspac, I dunno is it really working but o3 shows response
```
   list:
    - name: "o3-mini-high"
      label: "o3 mini high"
      default: true
      description: "high is great at reasoning"
      preset:
        endpoint: "openAI"
        model: "o3-mini-2025-01-31"
        reasoning_effort: high
```
