### DISCUSSION TITLE
[Question]: How to deploy o3-mini azure model

### DISCUSSION THREAD

**Discussion by andremachado94** [danny-avila/LibreChat#5630] [Q&A]
### What is your question?

o3-mini was recently added to the available Azure models and I wanted to see if I could use it with Librechat. I simply tried to add it to the list of available models. My configuration looks like this:

```yaml
version: 1.2.0
cache: true
fileStrategy: local
endpoints:
    azureOpenAI:
        titleModel: gpt-4o-mini
        plugins: true
        groups:
          - group: chat-models
            apiKey: ${AZURE_OPENAI_API_KEY}
            instanceName: ${LIBRECHAT_AZURE_API_INSTANCE_NAME}
            version: ${LIBRECHAT_AZURE_API_VERSION}
            models:
              gpt-4o-mini:
                deploymentName: gpt-4o-mini-2024-07-18
              o3-mini:
                deploymentName: o3-mini-2025-01-31
```

Model `gpt-4o-mini` works fine as expected, however `o3-mini` fails and the only log message I can get is:

```
2025-02-03T16:13:38.215Z debug: [AskController]
{
  text: "Hello",
  conversationId: null,
  endpoint: "azureOpenAI",
  resendFiles: true,
    modelOptions.model: "o3-mini",
  modelsConfig: "exists",
}
2025-02-03T16:13:38.220Z debug: [BaseClient] Loading history:
{
  conversationId: "6cd350f8-c6a3-45f8-92c2-c0cdd0699d44",
  parentMessageId: "00000000-0000-0000-0000-000000000000",
}
2025-02-03T16:13:38.246Z debug: [saveConvo] api/app/clients/BaseClient.js - saveMessageToDatabase #saveConvo
2025-02-03T16:13:38.509Z error: [handleAbortError] AI response error; aborting request: Failed to send message. HTTP 400 - Unsupported data type
2025-02-03T16:13:38.521Z debug: [AskController] Request closed
```

Am I missing anything on this configuration?

### More Details

Doing a curl request to the azure chat completions endpoint works fine. While doing that I noticed that some params like `temperature`, `frequency_penalty` or `presence_penalty` were not supported by this model.

```json
{
  "error": {
    "message": "Unsupported parameter: 'temperature' is not supported with this model.",
    "type": "invalid_request_error",
    "param": "temperature",
    "code": "unsupported_parameter"
    ...
  }
}
```

I figured Librechat could be sending these params by default, leading to the 400 error so I also added the following property:

```yaml
dropParams: ["user", "frequency_penalty", "presence_penalty", "temperature"]
````

Using API version: `2025-01-01-preview`
Using Librechat version: `v0.7.6`

Issue persists

### What is the main subject of your question?

Endpoints

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Update to latest to be able to use o3-mini

**Comment by goalkeepr** [comment]
I just pulled the latest dev (7c8a930061f5dcf6b416ca9706bda86a1a49254a) and it's still throwing errors. No issues with o1.

**Reply by danny-avila** [reply]
o3-mini requires the `2024-12-01-preview` API version or later, make sure to check your error logs

```yaml
    - group: "region-eastus2"
      apiKey: "${EASTUS2_API_KEY}"
      instanceName: "region-eastus2"
      version: "2024-12-01-preview"
      models:
        gpt-4o-latest:
          deploymentName: "gpt-4o-mini"
          version: "2024-02-15-preview"
        o1-mini:
          deploymentName: "o1-mini"
        o1-preview:
          deploymentName: "o1-preview"
        o3-mini:
          deploymentName: "o3-mini"
```

**Reply by andremachado94** [reply]
Was able to make it work by replacing:

```yaml
models:
   o3-mini:
      deploymentName: o3-mini-2025-01-31
```

by

```yaml
models:
   gpt-o3-mini:
      deploymentName: o3-mini-2025-01-31
```

Seems to be looking for the prefix gpt- (using v0.7.6)
