### DISCUSSION TITLE
Perplexity Custom Endpoint Config

### DISCUSSION THREAD

**Discussion by mansiibm** [danny-avila/LibreChat#5701] [Troubleshooting]
### What happened?

The following is my valid yaml configuration- 

![Image](https://github.com/user-attachments/assets/5cb25705-6420-4f9d-a3f9-8031af8e936e)

The issues I am facing with perplexity endpoint are - 

1. Title of the conversation is not getting generated. In the backend it states to keep frequency penalty>0 . 

![Image](https://github.com/user-attachments/assets/6c730076-31e0-41fe-98c0-81ed59ada88a)
Correspondingly, I increment the value, still the chat remains untitled. 

2. Consecutively chats related to two files are not supported. If I upload a file at the beginning of the conversation and query from it ,I receive response , if in next chat in the same session, I again upload a file, I get an error. 

![Image](https://github.com/user-attachments/assets/d091f581-9471-4f7b-9bf1-6962a1a3f339)

![Image](https://github.com/user-attachments/assets/bcf2006c-0cab-4e62-9777-478765724791)

![Image](https://github.com/user-attachments/assets/960b735e-ea9c-4d44-b919-b3a921089b5f)

3. If I upload a file first and then pass a normal text message it fails again with the same message as above. 

### Steps to Reproduce

1. Upload a file to perplexity and query from it.
2. It answers.
3. Upload another file in same session and query error comes up.
4. Or in the same session, after uploading a file ask or query something same error comes up. 
5. Titles are not being generated in the left hand side panel. 

### What browsers are you seeing the problem on?

Microsoft Edge

### Relevant log output

```shell

```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by mansiibm** [comment]
Hi, I have updated my yaml to following configuration - 

![Image](https://github.com/user-attachments/assets/ee356338-b0f8-4527-89a7-8a982f76d282)

to include the latest models released, and now it is not supporting any file at all. Generating the same error logs as shared earlier.

**Comment by danny-avila** [comment]
After further review, it seems no code changes are needed that have not already been implemented.

Successful title completion:
![chrome_jTMA1mQihh](https://github.com/user-attachments/assets/7b9a147c-a38d-4f2d-b0f7-7ab756d3ea84)

Successful message completion:
![Hi There Casual Greeting Explained](https://github.com/user-attachments/assets/077f2618-f10b-419f-9655-f8dd95f9f6ab)

---

I will update the docs to include the new sonar models:


```yaml
endpoints:
  custom:
    - name: "Perplexity"
      apiKey: "${PERPLEXITY_API_KEY}"
      baseURL: "https://api.perplexity.ai/"
      models:
        default:
          - "sonar-reasoning-pro"
          - "sonar-reasoning"
          - "sonar-pro"
          - "sonar"
        fetch: false
      titleConvo: true
      titleModel: "current_model"
      forcePrompt: false
      titleMessageRole: "user"
      modelDisplayLabel: "Perplexity"
      dropParams: ["stop", "user", "frequency_penalty", "presence_penalty"]
```
