### DISCUSSION TITLE
Error message interacting with the Azure OpenAI API

### DISCUSSION THREAD

**Discussion by jmartinezb3** [danny-avila/LibreChat#5707] [Troubleshooting]
### What happened?

Yesterday, I was configuring the Azure OpenAI endpoint in LibreChat. Initially, everything was going well, but today I am encountering the errors shown in the attached screenshots.

I have restarted and updated the LibreChat images as mentioned in the documentation, but I have not been successful in getting it to work again.

I tested the deployed models in the Azure Playground, and they work correctly, so it seems to be an issue with the client. I also tried using another client, and it works as expected.

The strange thing is that it works until the third interaction, but after that, it shows error messages.

Output of the `docker images` command:

````
REPOSITORY                                  TAG       IMAGE ID       CREATED         SIZE
ghcr.io/danny-avila/librechat-dev           latest    b39b350dca9e   6 hours ago     865MB
getmeili/meilisearch                        v1.12.3   9547aac4aabc   3 weeks ago     141MB
ghcr.io/danny-avila/librechat-rag-api-dev   latest    9a0541a57bb1   7 weeks ago     7.65GB
mongo                                       latest    6fe2220a3a52   2 months ago    881MB
ankane/pgvector                             latest    f2c967e41f72   16 months ago   440MB
````

My librechat.yaml configuration:

````
version: 1.2.1
 
cache: true
 
interface:
  # Privacy policy settings
  privacyPolicy:
    externalUrl: 'https://librechat.ai/privacy-policy'
    openNewTab: true
 
  # Terms of service
  termsOfService:
    externalUrl: 'https://librechat.ai/tos'
    openNewTab: true
 
registration:
  socialLogins: ["discord", "facebook", "github", "google", "openid"]
 
endpoints:
  azureOpenAI:
    # Endpoint-level configuration
    titleModel: "gpt-4o-mini"
    plugins: true
    assistants: false
    groups:
    # Group-level configuration
    - group: "azure-chat"
      apiKey: "${EASTUS2_API_KEY}"
      instanceName: "${INSTANCE_NAME}"
      version: "2025-01-01-preview"
      # Model-level configuration
      models:
        gpt-4o:
          deploymentName: gpt-4o_2024-11-20
        gpt-4o-mini:
          deploymentName: gpt-4o-mini_2024-07-18
        o1:
          deploymentName: o1_2024-12-17
        o1-mini:
          deploymentName: o1-mini_2024-09-12
        o3-mini:
          deploymentName: o3-mini_2025-01-31
````

### Steps to Reproduce

1.- Pick Azure OpenAI Endpoint
2.- Start an interaction

### What browsers are you seeing the problem on?

Microsoft Edge

### Relevant log output

```shell

```

### Screenshots

LibreChat interface:

![Image](https://github.com/user-attachments/assets/a8d5399d-8374-4c3c-8a5c-d27c6bde9bdf)

Browser consolo log output:

![Image](https://github.com/user-attachments/assets/d7eefdd9-0023-42e3-bbd9-98b393ad40aa)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
