### DISCUSSION TITLE
Illegal model request Error using ModelSpecs

### DISCUSSION THREAD

**Discussion by JMLX42** [danny-avila/LibreChat#5722] [Troubleshooting]
### What happened?

Hello,

When I send a first message, everything works fine.

Then, I get an "Illegal model request" error if I send a 2nd message.

### Steps to Reproduce

```yaml
            DEBUG_LOGGING: "true"
            DEBUG_CONSOLE: "true"
            CONSOLE_JSON: "true"
            ENDPOINTS: "custom"
            ALLOW_EMAIL_LOGIN: "false"
            ALLOW_REGISTRATION: "true"
            ALLOW_SOCIAL_LOGIN: "true"
            ALLOW_SOCIAL_REGISTRATION: "true"
            OPENID_CLIENT_ID: <ID>
            OPENID_CLIENT_SECRET: <SECRET>
            OPENID_CALLBACK_URL: /oauth/openid/callback
            OPENID_SESSION_SECRET: <SECRET>
            OPENID_ISSUER: <ISSUER-URL>
            OPENID_SCOPE: "openid profile email"
```

```yaml
            version: 1.0.3
            cache: true
            interface:
              endpointsMenu: true
              modelSelect: true
              parameters: true
              sidePanel: true
              presets: true
              prompts: true
              bookmarks: true
              multiConvo: true
              agents: true
            registration:
              socialLogins: ['openid']
            modelSpecs:
              enforce: true
              prioritize: true
              list:
                - name: deepseek-r1
                  label: "deepseek-r1"
                  showIconInMenu: true
                  default: true
                  preset:
                    endpoint: "ollama"
                    model: "deepseek-r1"
            endpoints:
              custom:
                - name: "Ollama"
                  apiKey: "ollama"
                  baseURL: "http://ollama:11434/v1/chat/completions" 
                  models:
                    default: [
                      "deepseek-r1"
                    ]
                    # fetching list of models is supported but the `name` field must start
                    # with `ollama` (case-insensitive), as it does in this example.
                    fetch: true
                  titleConvo: true
                  titleModel: "current_model"
                  summarize: false
                  summaryModel: "current_model"
                  forcePrompt: false
                  modelDisplayLabel: "Ollama"
```

`librechat-dev/33e60c379b963ebac9bdb5e512161977c6711316`

1. Send a message
2. Send a second message

### What browsers are you seeing the problem on?

Firefox

### Relevant log output

```shell
Server response to `POST https://chat.vpn.aerys.in/api/ask/custom`:


event: error
data: {"text":"Illegal model request"}
```

### Screenshots

![Image](https://github.com/user-attachments/assets/e728480c-522e-4512-bd14-8c9eab51a974)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by JMLX42** [comment]
Commenting the `modelSpec` section in the YAML config solves the problem.

**Comment by danny-avila** [comment]
You are using `fetch: true`, which means the model list is likely not matching what you defined in your spec.

![chrome_jJcTnk2mlY](https://github.com/user-attachments/assets/5ed97881-3e8f-4f1f-a86a-91b8c6c41176)


```yaml
modelSpecs:
  enforce: true
  prioritize: true
  list:
    - name: deepseek-r1
      label: "deepseek-r1"
      showIconInMenu: true
      default: true
      preset:
        endpoint: "ollama"
        model: "deepseek-r1:32b" # changed this to match exact model name
```
