### DISCUSSION TITLE
Custom Endpoint Perplexity not creating chat title with latest sonar models

### DISCUSSION THREAD

**Discussion by anphex** [danny-avila/LibreChat#5739] [Troubleshooting]
### What happened?

As stated by 
https://docs.perplexity.ai/guides/model-cards
the following models will be the only ones available starting from March 2025:

**Model	Context Length	Model Type**
sonar-reasoning-pro	127k	Chat Completion
sonar-reasoning	127k	Chat Completion
sonar-pro	200k	Chat Completion
sonar	127k	Chat Completion

By implementing this change in the librechat.yml and opting for the cheapest model "sonar" (since currently config doesn't allow for using chat title generation with one global model from a different provider) the model does not generate a title and remains at "New Chat". My hunch is that since Sonar models have a hard wired web search in every query no matter what, the title generation somehow quirks out.

### Steps to Reproduce

1. Setup Perplexity as custom endpoint in librechat.yaml with titleConvo set to "true" and selecting the cheapest model "sonar".

```
`  custom:
    - name: "Perplexity"
      apiKey: "${PERPLEXITY_API_KEY}"
      baseURL: "https://api.perplexity.ai/"
      models:
        default: [
          "sonar-pro",
          "sonar",
          "sonar-reasoning-pro",
          "sonar-reasoning"
        ]
        fetch: false
      titleConvo: true
      titleModel: "sonar"
      summarize: false
      #summaryModel: "llama-3-sonar-small-32k-chat"
      forcePrompt: false
      dropParams: ["stop", "frequency_penalty"]
      modelDisplayLabel: "Perplexity"
`
```

2. Try a query with any of these models in the LibreChatUI, title conversion will not trigger.

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
-
```

### Screenshots

![Image](https://github.com/user-attachments/assets/85da7d63-9829-477f-94f3-53a6dcc6055a)

![Image](https://github.com/user-attachments/assets/71e0e76f-c2b5-4478-8028-0028593d77ac)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Search discussions for a working perplexity config. If you’re still having issues, check your logs and share them here

**Reply by danny-avila** [reply]
This is it: https://github.com/danny-avila/LibreChat/discussions/5701#discussioncomment-12086640

**Comment by febryanvaldo** [comment]
I have no problem with Perplexity creating the Chat Title. Could be your Perplexity config is wrong.

![](https://i.febryan.me/up60i.png)

![](https://i.febryan.me/hag5j.png)

My Perplexity custom endpoints

```
    - name: Perplexity
      apiKey: user_provided
      baseURL: https://api.perplexity.ai
      models:
        default:
          - sonar
          - sonar-pro
          - sonar-reasoning
          - sonar-reasoning-pro
        fetch: false
      titleConvo: true
      titleModel: sonar
      summarize: false
      summaryModel: sonar
      forcePrompt: false
      dropParams:
        - frequency_penalty
      modelDisplayLabel: Perplexity
      iconURL: https://i.febryan.me/aiu3z.png
  ```
