### DISCUSSION TITLE
Removing mongo-db and vectordb containers.

### DISCUSSION THREAD

**Discussion by rwmehta** [danny-avila/LibreChat#5877] [Q&A]
Hello, I'm using MongoDB Atlas as my database for LibreChat and for the RAG API. Because of this, I thought I'd no longer need to run the vectordb and MongoDB containers; however, when I try to remove them from the docker-compose file LibreChat no longer runs properly (Internal Server Error). I am not very familiar with docker, so it's highly likely there is some user error in trying to remove them.

I was wondering if it is possible to remove these containers, and if it is, what changes do I need to make to do so?

Here is my docker compose file:

```
services:
  api:
    container_name: LibreChat
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      # - mongodb
      - rag_api
    image: ghcr.io/danny-avila/librechat-dev:latest
    restart: always
    user: "${UID}:${GID}"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - HOST=0.0.0.0
      - MONGO_URI=mongodb://mongodb:27017/LibreChat
      - MEILI_HOST=http://meilisearch:7700
      - RAG_PORT=${RAG_PORT:-8000}
      - RAG_API_URL=http://rag_api:${RAG_PORT:-8000}
    volumes:
      - type: bind
        source: ./.env
        target: /app/.env
      - ./images:/app/client/public/images
      - ./logs:/app/api/logs
  # mongodb:
  #   container_name: chat-mongodb
  #   image: mongo
  #   restart: always
  #   user: "${UID}:${GID}"
  #   volumes:
  #     - ./data-node:/data/db
  #   command: mongod --noauth
  meilisearch:
    container_name: chat-meilisearch
    image: getmeili/meilisearch:v1.12.3
    restart: always
    user: "${UID}:${GID}"
    environment:
      - MEILI_HOST=http://meilisearch:7700
      - MEILI_NO_ANALYTICS=true
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
    volumes:
      - ./meili_data_v1.12:/meili_data
  # vectordb:
  #   container_name: vectordb
  #   image: ankane/pgvector:latest
  #   environment:
  #     POSTGRES_DB: mydatabase
  #     POSTGRES_USER: myuser
  #     POSTGRES_PASSWORD: mypassword
  #   restart: always
  #   volumes:
  #     - pgdata2:/var/lib/postgresql/data
  rag_api:
    container_name: rag_api
    image: ghcr.io/danny-avila/librechat-rag-api-dev-lite:latest
    environment:
      - DB_HOST=vectordb
      - RAG_PORT=${RAG_PORT:-8000}
    restart: always
    # depends_on:
    #   - vectordb
    env_file:
      - .env

volumes:
  pgdata2:

```

These are the errors I see:

```
LibreChat         | {"level":"error","message":"KeyvMongo connection error: getaddrinfo ENOTFOUND mongodb","reason":{"commonWireVersion":0,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Unknown"},"stack":"MongoServerSelectionError: getaddrinfo ENOTFOUND mongodb\n    at Timeout._onTimeout (/app/node_modules/@keyv/mongo/node_modules/mongodb/lib/sdam/topology.js:292:38)\n    at listOnTimeout (node:internal/timers:581:17)\n    at process.processTimers (node:inter...","timestamp":"2025-02-14T15:02:54.869Z"}
LibreChat         | {"level":"error","message":"There was an uncaught error: getaddrinfo ENOTFOUND mongodb","reason":{"commonWireVersion":0,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Unknown"},"stack":"MongoServerSelectionError: getaddrinfo ENOTFOUND mongodb\n    at Timeout._onTimeout (/app/node_modules/@keyv/mongo/node_modules/mongodb/lib/sdam/topology.js:292:38)\n    at listOnTimeout (node:internal/timers:581:17)\n    at process.processTimers (node:inter...","timestamp":"2025-02-14T15:02:54.870Z"}
LibreChat exited with code 0
```

**Comment by harrylaou** [comment]
In case you try to run it locally, this is my `docker-compose.override.yml` file 
```
services:
    api:
        volumes:
        - type: bind
          source: ./librechat.yaml
          target: /app/librechat.yaml
        environment:
        - MONGO_URI=${MONGO_URI}
    mongodb:
        image: alpine:latest
        command: "true"
    db:
        image: alpine:latest
        command: "true"
    client:
        image: alpine:latest
        command: "true"
```
