### DISCUSSION TITLE
token count exceeds while using xAI

### DISCUSSION THREAD

**Discussion by sirlaurie** [danny-avila/LibreChat#5965] [Help Wanted]
I add xAI by edit `librechat.yaml`
```yaml
- name: 'xAI'
      apiKey: user_provided
      baseURL: 'https://api.x.ai/v1'
      models:
        default:
          [
            'grok-2-1212',
            'grok-2-vision-1212',
          ]
        fetch: false
      titleConvo: true
      titleModel: 'grok-2-1212'
      modelDisplayLabel: 'xAI'
```
but it keeps saying the token count exceeds even just say 'Hi'

<img width="748" alt="image" src="https://github.com/user-attachments/assets/69fd6832-4fe0-409a-a537-7536f7f28187" />

the logs didn't helpful 
```
LibreChat         | 2025-02-21 03:15:24 warn: Instructions token count exceeds max token count (4959 / 4095).
LibreChat         | 2025-02-21 03:15:24 error: [handleAbortError] AI response error; aborting request: { "type": "INPUT_LENGTH", "info": "4959 / 4095" }
```

how do I fix it?
