### DISCUSSION TITLE
Model Specs iconURL not Working

### DISCUSSION THREAD

**Discussion by rwmehta** [danny-avila/LibreChat#6046] [Troubleshooting]
I think I may be misunderstanding the iconURL, showIconInMenu, and showIconInHeader fields from Model Specs. I wanted to replace the model provider icons (Azure in this case) with an icon of my own. 
<img width="1265" alt="image" src="https://github.com/user-attachments/assets/e070eac7-ece4-4360-a2cc-30279bdd6d91" />

The problem is when I add those fields in, and just use a test image url it disables Azure altogether somehow and re-enables agents which should be off. 

Here is my librechat.yaml with the lines in question commented out:
```
version: 1.2.1
cache: true
endpoints:
  azureOpenAI:
    titleModel: "Llama-3.2-11B-Vision-Instruct"
    titleConvo: true
    groups:
    - group: "serverless-example"
      apiKey: "${AZUREFOUNDRY_KEY}"  # arbitrary env var name
      baseURL: <MODEL URL>
      version: "2024-05-01-preview" # Optional: specify API version
      serverless: true
      models:
        # Must match the deployment name of the model
        Llama-3.2-11B-Vision-Instruct: true
        Llama-3.3-70B-Instruct: true
        
    agents:
    disableBuilder: true
interface:
  agents: false
  endpointsMenu: false
  modelSelect: true
  parameters: true
  presets: true
  sidePanel: true
  prompts: true
  bookmarks: true
  multiConvo: true
registration:
  socialLogins: ["google"]
modelSpecs:
  enforce: false
  prioritize: false
  list:
    - name: "Llama-3.2-11B-Vision-Instruct"
      label: "Azure"
      showIconInMenu: true
      showIconInHeader: true
      default: true
      # iconURL: "https://fullstop360.com/blog/wp-content/uploads/2020/10/PURPOSE-OF-THE-LOGO.jpg"
      # showIconInMenu: true
      # showIconInHeader: true
      preset:
        endpoint: "azureOpenAI"
        model: "Llama-3.2-11B-Vision-Instruct"
        modelLabel: "Llama 11B"
```

For reference, when I run it with these lines uncommented this is what happens (agents shows up and azure dissapears):
![image](https://github.com/user-attachments/assets/2840f30e-2110-4de0-b6da-d75eb3dbcd3a)
