### DISCUSSION TITLE
Disable File Uploads Per User

### DISCUSSION THREAD

**Discussion by jmariquit-tvlk** [danny-avila/LibreChat#6055] [Feature Requests & Suggestions]
We already have the capability to disable file uploads on a per model basis.  (**Thank you very much for that one!**)

Are there plans on of having the ability to disable it per user as well (either via an npm CLI or as a config parameter):

- perhaps as a role/attribute in the OpenID claim
- or a property as part of the user profile (so that we can have two types of users:  chat users versus power users who attaches files for enhanced context) -- like a 'allowUpload' property that can be set via npm CLI

_My apologies in advanced if this has been brought up before -- my search-fu skills is crap_

**Comment by nth347** [comment]
hi @jmariquit-tvlk , could you please tell how you configured file upload controls (file types, file size)?

**Reply by jmariquit-tvlk** [reply]
here you go:  https://www.librechat.ai/docs/configuration/librechat_yaml/object_structure/file_config

let me know if you can't get the yaml figured out

also, do remember that file uploads will be charged against your tokens (i.e. OpenAI tokens, etc.) -- including Librechat's own token credit balances

**Reply by nth347** [reply]
hello @jmariquit-tvlk,

here is my config
```
fileConfig:
  endpoints:
    assistants:
      fileLimit: 5
      fileSizeLimit: 10  # Maximum size for an individual file in MB
      totalSizeLimit: 50  # Maximum total size for all files in a single request in MB
      supportedMimeTypes:
        - "image/.*"
        - "application/pdf"
    openAI:
      disabled: true  # Disables file uploading to the OpenAI endpoint
    google:
      disabled: true
      fileLimit: 1
      fileSizeLimit: 1
      totalSizeLimit: 3
      supportedMimeTypes:
#        - "image/.*"
        - "application/pdf"
    default:
      totalSizeLimit: 20
    YourCustomEndpointName:
      fileLimit: 2
      fileSizeLimit: 5
  serverFileSizeLimit: 100  # Global server file size limit in MB
  avatarSizeLimit: 2  # Limit for user avatar image size in MB
  ```
  
For `google`, I set `disabled` to `true` and updated `supportedMimeTypes` to `application/pdf`. However, I was still able to upload a picture in jpeg format and ask about it in the chat using Google Gemini. Did I miss something?

**Reply by jmariquit-tvlk** [reply]
according to the docs, setting the `disabled: true` under that endpoint (in this case Google), should override any other file-related settings.  You might have to raise this as a bug.  

in the meantime, try commenting out the other keys so that you have something like
```
fileConfig:
  endpoints:
    google:
      disabled: true
    openAI:
      disabled: true
```

**Reply by nth347** [reply]
hi @jmariquit-tvlk , I used the minimized config as you suggested, but it didn't work anyway.
```yaml
fileConfig:
  endpoints:
    google:
      disabled: true
    openAI:
      disabled: true
```
Hi @danny-avila, could you please share your opinion before I raise an issue?
