### DISCUSSION TITLE
Can't add whisper STT

### DISCUSSION THREAD

**Discussion by saeedesmaili** [danny-avila/LibreChat#6190] [Help Wanted]
Groq provides openai compatible api for whisper:
https://console.groq.com/docs/openai

<img width="820" alt="image" src="https://github.com/user-attachments/assets/bef1b88d-e604-4e18-b31e-1a8ace3e576b" />
<img width="410" alt="image" src="https://github.com/user-attachments/assets/963d28ff-cfff-4357-bf13-a8d3988e451b" />

 I have done the followings:

librechat.yaml:
```yaml
speech:
  stt:
    openai:
      url: 'https://api.groq.com/openai/v1'
      apiKey: '${GROQ_API_KEY}'
      model: 'distil-whisper-large-v3-en'
```

deploy-compose.yml:
```yaml
services:
  api:
    image: ghcr.io/danny-avila/librechat-dev-api:latest
    container_name: LibreChat-API
    ports:
      - 3080:3080
    depends_on:
      - mongodb
      - rag_api
    restart: always
    extra_hosts:
    - "host.docker.internal:host-gateway"
    env_file:
      - .env
    environment:
      - HOST=0.0.0.0
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongodb:27017/LibreChat
      - MEILI_HOST=http://meilisearch:7700
      - RAG_PORT=${RAG_PORT:-8000}
      - RAG_API_URL=http://rag_api:${RAG_PORT:-8000}
      - GROQ_API_KEY=${GROQ_API_KEY} ## added this
    volumes:
      - type: bind
        source: ./librechat.yaml
        target: /app/librechat.yaml
      - ./images:/app/client/public/images
      - ./logs:/app/api/logs
```

and added `GROQ_API_KEY` environment variable.

But when I visit the speech settings after deploy, I still only have "browser" for the engine:
<img width="741" alt="image" src="https://github.com/user-attachments/assets/87583204-e39f-414b-8bf8-8cb3b299f03c" />

What should I do next to troubleshoot this?

**Comment by berry-13** [comment]
you used the key `tts` when the correct one should be `stt`

here's the correct YAML configuration:

```yaml
speech:
  stt:
    openai:
      url: 'https://api.groq.com/openai/v1'
      apiKey: '${GROQ_API_KEY}'
      model: 'distil-whisper-large-v3-en'
```
