### DISCUSSION TITLE
Properly installing & configuring the MCP-Fileystem server on MacOS local installation

### DISCUSSION THREAD

**Discussion by ghost** [danny-avila/LibreChat#6200] [Troubleshooting] [answered]
Hello there,

I was looking for guidance on how to install the MCP filesystem from here: 

https://github.com/modelcontextprotocol/servers/tree/main/src/filesystem

From what I understand this setup is intended to run within a docker container though when I read the LibreChat docs I get the impression that the MCP server is a child process of LibreChat and should be run from the same docker container. 

My own attempts at resolving the problem have failed so far. 

Any guidance would be very much appreciated.

Cheers

**Comment by danny-avila** [comment, marked as answer]
You either need to mount volumes or bind mounts you want docker to have access to.

You could try using the override file for volume mounting.

https://www.librechat.ai/docs/configuration/docker_override

**Reply by ghost** [reply]
Yes, this was indeed the problem, not understanding how the network was properly configured and that I need to mount a local folder into the container. I had not realized until now what power the docker override file has. Cheers!

**Comment by ghost** [comment]
Here is my docker override configuration that made the MCP filesystem server work:

```
services:
  api:
    volumes:
    - type: bind
      source: ./librechat.yaml
      target: /app/librechat.yaml
    - type: bind
      source: /Users/my_username/obsidian_vault/vault_name
      target: /obsidian-vault
    - type: bind             
      source: ./files        
      target: /app/files
   # - type: bind
   #   source: ./api/data/auth.json
   #   target: /app/api/data/auth.json
```

in the root of the project, in my case /Users/username/LibreChat I created a new folder called "files" which the AI agents can access for context. Setting the paths correctly in the docker override file is key to make things work. Kind of stunning how simple and confusing it can be at the same time. 

Edit: I know just realize that the same had to be done if you want to use the Obsidian MCP server.
