### DISCUSSION TITLE
Help setting up DeepSeek

### DISCUSSION THREAD

**Discussion by mrussogit** [danny-avila/LibreChat#6221] [Help Wanted]
Hey, I'm having a hard time to get DeepSeek to run in LibreChat.

I found this was asked before but so far it isn't working
https://github.com/danny-avila/LibreChat/discussions/5422

I followed the same steps:
in duplicated docker-copmpose.override.yml I have uncommented:

```
 services:

# # USE LIBRECHAT CONFIG FILE
   api:
     volumes:
     - type: bind
       source: ./librechat.yaml
       target: /app/librechat.yaml
```

in librechat.yaml I also have the code given by Deep Seek

```
  custom:
    - name: "Deepseek"
      apiKey: "${DEEPSEEK_API_KEY}"
      baseURL: "https://api.deepseek.com/v1"
      models:
        default: ["deepseek-chat", "deepseek-coder", "deepseek-reasoner"]
        fetch: false
      titleConvo: true
      titleModel: "deepseek-chat"
      modelDisplayLabel: "Deepseek"

```

then in .env
```

#===================================================#
#                     Endpoints                     #
#===================================================#

ENDPOINTS=openAI,assistants,azureOpenAI,bingAI,google,gptPlugins,anthropic,custom


```

I also tried to use just ENDPOINTS=openAI,anthropic,custom
Then I have

```
#===================================#
# Known Endpoints - librechat.yaml  #
#===================================#
# https://www.librechat.ai/docs/configuration/librechat_yaml/ai_endpoints

# ANYSCALE_API_KEY=
# APIPIE_API_KEY=
# COHERE_API_KEY=
DEEPSEEK_API_KEY= my API key entered here.
```

I restarted Docker etc but no sign of DeepSeek. I'm running version 0.7.7-rc1

**Comment by ghost** [comment]
I don't understand why you edited your docker override file? That is not necessary to add custom AI providers. It can make sense to double check the indentation in librechat.yaml though first look it seems right. You can also try other formatting. Maybe this helps. 

For example for Perplexity I used this format since it is easier for me to edit:

# Perplexity Endpoint
    - name: "Perplexity"
      apiKey: "${PERPLEXITY_API_KEY}"
      baseURL: "https://api.perplexity.ai/"
      models:
        default: [
          "sonar-reasoning-pro",
          "sonar-reasoning",
          "sonar-pro",
          "sonar",
          "r1-1776",
          ]
        fetch: false # fetching list of models is not supported
      titleConvo: true
      titleModel: "sonar"
      summarize: false
      summaryModel: "sonar"
      forcePrompt: false
      dropParams: ["stop", "frequency_penalty"]
      modelDisplayLabel: "Perplexity"

After my custimazation my docker override currently looks like this:

```
services:
  api:
    volumes:
    - type: bind
      source: ./librechat.yaml
      target: /app/librechat.yaml
    - type: bind
      source: /Users/my_username/obsidian_vault/my_vault_name
      target: /obsidian-vault
    - type: bind
      source: ./files
      target: /app/files
# - type: bind
   #   source: ./api/data/auth.json
   #   target: /app/api/data/auth.json

```
Hope this is helpful. Running this on MacOS.
