### DISCUSSION TITLE
Token Limit Error When Using Custom Qwen Model

### DISCUSSION THREAD

**Discussion by HAL9990** [danny-avila/LibreChat#6252] [Troubleshooting]
### What happened?

When utilizing the custom Qwen model, whether set as a custom endpoint in YAML or included in the models list compatible with OpenAI, an error occurs when starting a new session and sending a "hi" message. The error message indicates that the token count of the latest message exceeds the limit: "Token count for the latest message is too long, exceeding the limit (4959 / 4095)." This issue did not exist in the previous version released approximately three months ago and only began occurring after the recent update yesterday.

Please let me know if you need any modifications or additional details!

![Image](https://github.com/user-attachments/assets/444f3d27-b482-4c6d-9eec-09bfcd60f0f7)

Here is my console's error:
```
{
    "sender": "Qwen",
    "messageId": "ae7fa2ba-b56f-4ac3-92b2-b1b6fa06517a",
    "conversationId": "388b6894-b060-4e5f-9836-100a93590520",
    "parentMessageId": "d3b33663-b70e-4d9b-a8fe-2112ab2b78e5",
    "unfinished": false,
    "error": true,
    "final": true,
    "text": "{ \"type\": \"INPUT_LENGTH\", \"info\": \"4959 / 4095\" }",
    "isCreatedByUser": false
}
```

Here is my yaml:
```
  custom:
    - name: "Qwen"
      apiKey: "${QWEN_API_KEY}"
      baseURL: "${QWEN_REVERSE_PROXY}"
      models:
        default: ["qwen-max", "qwen-plus", "qwen-turbo", "Qwen2.5-72B-Instruct", "Qwen2.5-32B-Instruct", "Qwen2.5-14B-Instruct"]
        fetch: false # fetching list of models is not supported
      titleConvo: true
      titleModel: "qwen-turbo"
      summarize: false
      summaryModel: "qwen-turbo"
      forcePrompt: false
      modelDisplayLabel: "Qwen"
```

### Version Information
ghcr.io/danny-avila/librechat-dev latest 59660cbf7aa2 19 hours ago 872MB
ghcr.io/danny-avila/librechat-rag-api-dev-lite latest 6550e7ddf180 42 hours ago 1.3GB

### Steps to Reproduce

1. Update the software to the latest version.
2. Ensure that the custom Qwen model is configured correctly, either as a custom endpoint in YAML or listed among the OpenAI models.
3. Open the application and create a new session.
4. Send a message containing the text "hi".
5. Observe the error message that appears indicating the token count exceeds the limit: "Token count for the latest message is too long, exceeding the limit (4959 / 4095)."

### Relevant log output

```shell

```

### Screenshots

![Image](https://github.com/user-attachments/assets/444f3d27-b482-4c6d-9eec-09bfcd60f0f7)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by xoChrisCo** [comment]
I seem to be getting the same for Mistral codestral-latest as well:
`The latest message token count is too long, exceeding the token limit (4959 / 4095 respectively). Please shorten your message, adjust the max context size from the conversation parameters, or fork the conversation to continue.`

**Comment by danny-avila** [comment]
This happens when the context window of the model you are using is not recognized (defaults to 4095). This will be alleviated with the following this week:

https://github.com/danny-avila/LibreChat/issues/1633

I will also add codestral, and qwen models to the default config.

For now, you can also specify the max context tokens via agent/preset.

![firefox_vLUoX4VSYC](https://github.com/user-attachments/assets/66baf0b6-a424-4631-992a-0c81b0ff3219)

**Comment by mapleroyal** [comment]
I am also experiencing this issue in librechat when using `qwen3-30b-a3b-thinking-2507-mlx` via LM Studio.

> The latest message token count is too long, exceeding the token limit, or your token limit parameters are misconfigured, adversely affecting the context window. More info: 4013 / 3686. Please shorten your message, adjust the max context size from the conversation parameters, or fork the conversation to continue.

- No issues with shorter prompts.
- No issues with the same prompt directly in LM Studio.

The relevant part from my `librechat.yaml`:

```yaml
- name: 'LM Studio'
  apiKey: 'not-needed'
  baseURL: 'http://host.docker.internal:1234/v1'
  models:
    default: ['qwen3-30b-a3b-thinking-2507-mlx']
    fetch: true
  titleConvo: true
  titleModel: 'deepseek/deepseek-chat-v3-0324:free'
  modelDisplayLabel: 'LM Studio'
```

Just installed LibreChat yesterday via docker.
