### DISCUSSION TITLE
Title gen is not working with Openrouter and agents

### DISCUSSION THREAD

**Discussion by twinity1** [danny-avila/LibreChat#6319] [Troubleshooting]
Title generation is not working with OpenRouter when using an agent, but it works when using the OpenRouter endpoint directly.

When I check the network tab, I see that the gen_title endpoint returns a 404 error with the following message:

```json
{
    "message": "Title not found or method not implemented for the conversation's endpoint"
}
```

Does anybody know how to set it up correctly?

My config:

```yaml
endpoints:
  custom:
    - name: 'OpenRouter'
      apiKey: '${OPENROUTER_KEY}'
      baseURL: 'https://openrouter.ai/api/v1'
      models:
        default: ['anthropic/claude-3.7-sonnet', 'anthropic/claude-3.5-sonnet', 'anthropic/claude-3.5-haiku', 'openai/o3-mini', 'google/gemini-2.0-flash-001']
        fetch: false
      titleConvo: true
      titleModel: 'anthropic/claude-3.5-haiku'
      dropParams: ['stop']
      modelDisplayLabel: 'OpenRouter'
```

Thank you.
