### DISCUSSION TITLE
Settings Azure OpenAI

### DISCUSSION THREAD

**Discussion by DevDorrejo** [danny-avila/LibreChat#6330] [Help Wanted]
Hello, just setup the docker-compose, and set my Azure OpenAI config in librechat.yaml:

```
endpoints:
  azureOpenAI:
    titleModel: "gpt-4-turbo"
    plugins: true
    groups:
      - group: "AI-US2" # Custom group name for your deployment
        apiKey: "xxx"
        instanceName: "AIUS2"
        version: "2024-10-21"
        baseURL: "https://xxxx.openai.azure.com/"
        models:
          gpt-4-turbo:
            deploymentName: "AI-One"
            version: "2024-10-21"
```

But the model it is not appearing in the model's panel, and I am getting this error:

```
c37334dc65fd Traceback (most recent call last):
c37334dc65fd   File "/app/main.py", line 49, in <module>
c37334dc65fd     from psql import PSQLDatabase, ensure_custom_id_index_on_embedding, pg_health_check
c37334dc65fd   File "/app/psql.py", line 3, in <module>
c37334dc65fd     from config import DSN, logger
c37334dc65fd   File "/app/config.py", line 258, in <module>
c37334dc65fd     embeddings = init_embeddings(EMBEDDINGS_PROVIDER, EMBEDDINGS_MODEL)
c37334dc65fd   File "/app/config.py", line 186, in init_embeddings
c37334dc65fd     return OpenAIEmbeddings(
c37334dc65fd   File "/usr/local/lib/python3.10/site-packages/pydantic/main.py", line 214, in __init__
c37334dc65fd     validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
c37334dc65fd   File "/usr/local/lib/python3.10/site-packages/langchain_openai/embeddings/base.py", line 338, in validate_environment
c37334dc65fd     self.client = openai.OpenAI(**client_params, **sync_specific).embeddings  # type: ignore[arg-type]
c37334dc65fd   File "/usr/local/lib/python3.10/site-packages/openai/_client.py", line 110, in __init__
c37334dc65fd     raise OpenAIError(
c37334dc65fd openai.OpenAIError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable
```

Don't know why this appear if the only endpoint I am setting is the one of Azure and not openai
