### DISCUSSION TITLE
Default modelSpec for endpoint

### DISCUSSION THREAD

**Discussion by rm-1997** [danny-avila/LibreChat#6337] [Troubleshooting]
I am wondering whether there is an option to set a default modelSpec item for a given endpoint such that if I select a different/new endpoint from the (left) dropdown, it does not appear `None selected` but the default modelSpec item (if one was configured).

*When changing endpoint to Azure OpenAI using drop-down:*

What I want:
<img width="521" alt="image" src="https://github.com/user-attachments/assets/c26fa68e-5e0d-4f12-a196-a9990f57fcf9" />

What I have at the moment:
<img width="521" alt="image" src="https://github.com/user-attachments/assets/8a18d97d-c725-46c6-8965-62a4df15aa6a" />

I would be very happy if some could help me out here.

This is my (simplified) `librechat.yaml` configuration:

```
interface:

  endpointsMenu: true
  modelSelect: true
  parameters: true
  sidePanel: true
  presets: true
  prompts: false
  bookmarks: true
  multiConvo: false
  agents: true

endpoints:

  azureOpenAI:
      titleModel: "gpt-4o-mini"
      titleConvo: true
      titleMethod: "completion"
      plugins: true
      assistans: false
      summarize: false
      groups:
        - group: "aoai"
          apiKey: "${AZURE_OAI_API_KEY}"
          instanceName: "${AZURE_OAI_RESOURCE}"
          version: "${AZURE_OAI_API_VERSION}"
          models:
            gpt-4o:
              deploymentName: "gpt-4o"
        - group: "aoai2"
          apiKey: "${AZURE_OAI_API_KEY}"
          instanceName: "${AZURE_OAI_RESOURCE}"
          version: "${AZURE_OAI_API_VERSION}"
          models:
            gpt-4o-mini:
              deploymentName: "gpt-4o-mini"

  agents:
    recursionLimit: 25
    disableBuilder: false
    capabilities:
      - "file_search"
      - "tools"

modelSpecs:
  enforce: false
  prioritize: false
  list:
      - name: "Azure OpenAI"
        label: "Azure OpenAI"
        description: "Models for daily usage."      
        preset:
          default: true
          endpoint: "azureOpenAI"
          greeting: |          
            Azure OpenAI models.
```
