### DISCUSSION TITLE
Add descriptions to models in the top menu

### DISCUSSION THREAD

**Discussion by dhaussener** [danny-avila/LibreChat#6347] [Help Wanted]
Is it possible to add a description to individual models of custom endpoints in the top menu? I have seen that the object modelSpecs provides corresponding keys but do not understand how to bring this together.

```
# For more information, see the Configuration Guide:
# https://docs.librechat.ai/install/configuration/custom_config.html

# Configuration version (required)
version: 1.0.5
# This setting caches the config file for faster loading across app lifecycle
cache: true

endpoints:

  # Perplexity
  custom:
    - name: "Perplexity"
      apiKey: "${PERPLEXITY_API_KEY}"
      baseURL: "https://api.perplexity.ai/"
      models:
        default:
          - "sonar"
          - "sonar-pro"
        fetch: false
      titleConvo: true
      titleModel: "sonar"
      forcePrompt: false
      modelDisplayLabel: "Perplexity"
      dropParams: ["stop", "user", "frequency_penalty", "presence_penalty"]

modelSpecs:
  enforce: true
  prioritize: true
  list:
    - name: "sonar"
      label: "Sonar"
      default: true
      description: "This model excels at general tasks."
    - name: "sonar-pro"
      label: "Sonar Pro"
      description: "This is the advanced version of the Sonar model."
```

Is this possible and if so, how?
