### DISCUSSION TITLE
Models are not displayed by endpoint in the menu

### DISCUSSION THREAD

**Discussion by dhaussener** [danny-avila/LibreChat#6365] [Troubleshooting] [answered]
I have added descriptions to the models with `modelSpecs`. However all models are displayed now in the submenu regardless of the endpoint. The aim would be that only the models of the selected endpoint appear in the submenu, as is the case in the standard menu.

<img width="384" alt="model_menu" src="https://github.com/user-attachments/assets/3813d9e4-b7f8-43b8-8f3d-c82bf6611ef1" />

librechat.yml:
```
endpoints:

  # Perplexity
  custom:
    - name: "Perplexity"
      apiKey: "${PERPLEXITY_API_KEY}"
      baseURL: "https://api.perplexity.ai/"
      models:
        default:
          - "sonar"
          - "sonar-pro"
        fetch: false
      titleConvo: true
      titleModel: "sonar"
      forcePrompt: false
      modelDisplayLabel: "Perplexity"
      dropParams: ["stop", "user", "frequency_penalty", "presence_penalty"]

  # Mistral
    - name: "Mistral"
      apiKey: "${MISTRAL_API_KEY}"
      ...

interface:
   endpointsMenu: true
   modelSelect: false
   
modelSpecs:
  enforce: true
  prioritize: true
  list:

    # Perplexity-Modelle
    - name: "sonar"
      label: "Sonar"
      default: true
      description: "Echtzeit-Recherche für Fakten und Trends"
      preset:
        endpoint: "Perplexity"
        model: "sonar"
    - name: "sonar-pro"
      label: "Sonar Pro"
      description: "Umfassende Recherche und Marktanalysen"
      preset:
        endpoint: "Perplexity"
        model: "sonar-pro"

    # Mistral-Modelle
    - name: "mistral-small-latest"
      label: "Mistral Small"
      ...

    # OpenAI-Modelle
    - name: "gpt-4o-mini"
      label: "GPT-4o mini"
      ...

    # Anthropic-Modelle
    - name: "claude-3.5-haiku"
      label: "Claude 3.5 Haiku"
      ...
```

### Version Information
v0.7.7 via elest.io

**Comment by dhaussener** [comment]
If all models with a description appears in one new menu, the default menus with the endpoints and models could be hidden, as they would become practically unnecessary/redundant.

**However, the agents can no longer be used in this way:**
`endpointsMenu = false` -> Agents can no longer be selected in the endpoint menu and have to added with `modelSpecs`
`selectMenu = false` -> Agents are no longer displayed in the SideBar and can no longer be selected

**Comment by danny-avila** [comment, marked as answer]
This is not how `modelSpecs` were designed, rather to override endpoint/model selection into a simpler component.

**Comment by Joshfindit** [comment]
@danny-avila Since there are more and more uses for creating a `modelSpec` to "tweak" an existing model without the desire to have it stand out, is it possible to allow something like:

```
    - name: "gpt-5"
      label: "gpt-5-non-streaming"
      group: "Edge"
      
      menuFolder: "OpenAI"
      
      preset:
        endpoint: "openAI"
        model: "gpt-5"
        disableStreaming: true # Works around "400 Your organization must be verified to stream this model"
```

Then merge the listing in the menu?
