### DISCUSSION TITLE
Image Generation not working

### DISCUSSION THREAD

**Discussion by SimplyCorbett** [danny-avila/LibreChat#6400] [Troubleshooting]
### What happened?

I cannot get stable diffusion image generation working on a local model with either tools: ["stable_diffusion"] and/or stable diffusion tools on a agent.

Is this feature broken?

### Version Information

ghcr.io/danny-avila/librechat-dev                latest    e4979ae60fba   21 hours ago    866MB
ghcr.io/danny-avila/librechat-rag-api-dev        latest    5f0a3f475b72   11 days ago     7.79GB
ghcr.io/danny-avila/librechat-rag-api-dev-lite   latest    6550e7ddf180   11 days ago     1.3GB

### Steps to Reproduce

Described above

### What browsers are you seeing the problem on?

Firefox

### Relevant log output

```shell

```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
no relevant logs provided, can't help. it is working.

**Reply by SimplyCorbett** [reply]
my reply is below, sorry, should have replied here.

**Comment by SimplyCorbett** [comment]
I don't see anything in the logs, and its not making a connection (at all) to the SD server.

librechat.yaml:

```
endpoints:
  custom:
    - name: "Ready.Art"
      apiKey: "blankhereintentional"
      # use 'host.docker.internal' instead of localhost if running LibreChat in a docker container
      baseURL: "https://tabby.ready.art/v1"
      models:
        default: [
            "L3.3-Electra-R1-70b-4.0bpw-h8-exl2"
          ]
        # fetching list of models is supported but the `name` field must start
        # with `ollama` (case-insensitive), as it does in this example.
        fetch: false
      titleConvo: true
      titleModel: "L3.3-Electra-R1-70b-4.0bpw-h8-exl2"
      summarize: false
      summaryModel: "L3.3-Electra-R1-70b-4.0bpw-h8-exl2"
      forcePrompt: false
      modelDisplayLabel: "Ready.Art | Q8 32k Context"
      tools: ["stable_diffusion"]
      addParams:
        max_tokens: 1024
      assistants: false
```

.env:

`SD_WEBUI_URL=http://images.ready.art:7860 (internal domain)`

Agent:

<img width="1032" alt="Screenshot 2025-03-18 at 11 41 39 AM" src="https://github.com/user-attachments/assets/b7495f37-e82d-4805-9269-78bed64aa24d" />

Model:

<img width="1032" alt="Screenshot 2025-03-18 at 11 42 19 AM" src="https://github.com/user-attachments/assets/554d47fc-e41c-4ccf-a735-6ba05e30f978" />
