### DISCUSSION TITLE
librechat.yaml custom endpoints and agent config dont work together

### DISCUSSION THREAD

**Discussion by eroo36** [danny-avila/LibreChat#6418] [Troubleshooting]
### What happened?

When setting custom endpoints and agents config in librechat.yaml file, custom endpoints are disabled/ignored

If I don't set custom agents config in yaml file and only enable in .env endpoints i can have the custom endpoints and agents with default config

### Version Information

efed1c461de3c3cf143190b7ee37d5fe57e89cdb

### Steps to Reproduce

use librechat.yaml file with:

```yaml
endpoints:
  custom:
    - name: "Perplexity"
      apiKey: "${PERPLEXITY_API_KEY}"
      baseURL: "https://api.perplexity.ai/"
      models:
        default: [
          "sonar-deep-research",
          "sonar-reasoning-pro",
          "sonar-reasoning",
          "sonar-pro",
          "sonar",
          "r1-1776"
          ]
        fetch: false # fetching list of models is not supported
      titleConvo: true
      titleModel: "sonar"
      summarize: false
      summaryModel: "sonar"
      forcePrompt: false
      dropParams: ["stop", "frequency_penalty"]
      modelDisplayLabel: "Perplexity"
  agents:
    recursionLimit: 50
    disableBuilder: false
    capabilities: ["file_search", "actions", "tools", "artifacts", "ocr", "chain"]
```

### Relevant log output

```shell

```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
