### DISCUSSION TITLE
Summerize feature doesn't work

### DISCUSSION THREAD

**Discussion by frenzybiscuit** [danny-avila/LibreChat#6420] [Troubleshooting]
### What happened?

When enabling the summerize feature, it doesn't work. Chat says the following (which works with summerize disabled):

`The latest message token count is too long, exceeding the token limit (2452 / 2047 respectively). Please shorten your message, adjust the max context size from the conversation parameters, or fork the conversation to continue.`

The model has 16k context.

```
docker images | grep librechat
ghcr.io/danny-avila/librechat-dev                latest    c83689215440   About an hour ago   882MB
ghcr.io/danny-avila/librechat-dev                <none>    e4979ae60fba   36 hours ago        866MB
ghcr.io/danny-avila/librechat-rag-api-dev        latest    5f0a3f475b72   12 days ago         7.79GB
ghcr.io/danny-avila/librechat-rag-api-dev-lite   latest    6550e7ddf180   12 days ago         1.3GB
```

librechat.yml:

```   
 - name: "Ready.Art | Secondary"
      apiKey: "apikeyhere"
      # use 'host.docker.internal' instead of localhost if running LibreChat in a docker container
      baseURL: "https://koboldcpp.ready.art/v1/"
      models:
        default: [
            "Fallen-Gemma3-12B-v1a-Q4_K_M.gguf"
          ]
        # fetching list of models is supported but the `name` field must start
        # with `ollama` (case-insensitive), as it does in this example.
        fetch: false
      titleConvo: true
      titleModel: 'current_model'
      summarize: true
      summaryModel: 'current_model'
      forcePrompt: false
      modelDisplayLabel: "Ready.Art | Secondary | 16k Context"
      addParams:
        max_tokens: 512
        min_p: 0.02
      assistants: false

```

### Version Information

docker images | grep librechat
ghcr.io/danny-avila/librechat-dev                latest    c83689215440   About an hour ago   882MB
ghcr.io/danny-avila/librechat-dev                <none>    e4979ae60fba   36 hours ago        866MB
ghcr.io/danny-avila/librechat-rag-api-dev        latest    5f0a3f475b72   12 days ago         7.79GB
ghcr.io/danny-avila/librechat-rag-api-dev-lite   latest    6550e7ddf180   12 days ago         1.3GB

### Steps to Reproduce

listed above

### What browsers are you seeing the problem on?

Firefox

### Relevant log output

```shell
LibreChat         | 2025-03-19T08:57:44.066Z debug: [AskController]
LibreChat         | {
LibreChat         |   text: "What? Why?",
LibreChat         |   conversationId: null,
LibreChat         |   endpoint: "Ready.Art | Secondary",
LibreChat         |   endpointType: "custom",
LibreChat         |   resendFiles: true,
LibreChat         |     modelOptions.model: "Fallen-Gemma3-12B-v1a-Q4_K_M.gguf",
LibreChat         |   artifactsPrompt: "The assistant can create and reference artifacts during conversations.\n\nArtifacts are for substantia... [truncated]",
LibreChat         |   modelsConfig: "exists",
LibreChat         | }
LibreChat         | 2025-03-19T08:57:44.186Z debug: [BaseClient] Loading history:
LibreChat         | {
LibreChat         |   conversationId: "a205cd9b-b1db-4511-9483-ecc9bdbde199",
LibreChat         |   parentMessageId: "00000000-0000-0000-0000-000000000000",
LibreChat         | }
LibreChat         | 2025-03-19T08:57:44.271Z debug: [BaseClient] instructions tokenCount: 2452
LibreChat         | 2025-03-19T08:57:44.271Z warn: Instructions token count exceeds max token count (2452 / 2047).
LibreChat         | 2025-03-19T08:57:44.273Z error: [handleAbortError] AI response error; aborting request: { "type": "INPUT_LENGTH", "info": "2452 / 2047" }
LibreChat         | 2025-03-19T08:57:44.290Z debug: [AskController] Request closed
```

### Screenshots

<img width="1057" alt="Image" src="https://github.com/user-attachments/assets/fb9ab12f-af17-4659-830e-b2665df75761" />

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
