### DISCUSSION TITLE
Local MCP server is running but errors in Librechat

### DISCUSSION THREAD

**Discussion by sterankin** [danny-avila/LibreChat#6444] [Help Wanted]
Here is my yaml, I have the correct server running which hosts my mcp servers:

```
# Example MCP Servers Object Structure
mcpServers:
  everything:
    # type: sse # type can optionally be omitted
    url: http://localhost:8000/sse
    timeout: 60000  # 1 minute timeout for this server, this is the default timeout for MCP servers.
  puppeteer:
    type: stdio
    command: npx
    args:
      - -y
      - "@modelcontextprotocol/server-puppeteer"
    timeout: 300000  # 5 minutes timeout for this server
  filesystem:
    # type: stdio
    command: npx
    args:
      - -y
      - "@modelcontextprotocol/server-filesystem"
      - /home/user/LibreChat/
    iconPath: /home/user/LibreChat/client/public/assets/logo.svg
  mcp-obsidian:
    command: npx
    args:
      - -y
      - "mcp-obsidian"
      - /path/to/obsidian/vault
```

Not sure if the rest is needed there I only need the url under `everything`.

But it results in the following in the error log, I guess it retries so many times:

```
{"event":{},"level":"error","message":"[MCP][everything] Connection failed: SSE error: undefined","stack":"Error: SSE error: undefined\n    at _eventSource.onerror (file:///app/packages/mcp/dist/index.es.js:1:88138)\n    at EventSource.scheduleReconnect_fn (file:///app/node_modules/eventsource/dist/index.js:192:53)\n    at file:///app/node_modules/eventsource/dist/index.js:45:174\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"}
{"code":-32000,"level":"error","message":"[MCP][filesystem] Connection failed: MCP error -32000: Connection closed","name":"McpError","stack":"McpError: MCP error -32000: Connection closed\n    at an._onclose (file:///app/packages/mcp/dist/index.es.js:1:71241)\n    at _transport.onclose (file:///app/packages/mcp/dist/index.es.js:1:70846)\n    at ChildProcess.<anonymous> (file:///app/packages/mcp/dist/index.es.js:1:91808)\n    at ChildProcess.emit (node:events:524:28)\n    at maybeClose (node:internal/child_process:1104:16)\n    at ChildProcess._handle.onexit (node:internal/child_process:304:5)"}
{"event":{},"level":"error","message":"[MCP][everything] Connection failed: SSE error: undefined","stack":"Error: SSE error: undefined\n    at _eventSource.onerror (file:///app/packages/mcp/dist/index.es.js:1:88138)\n    at EventSource.scheduleReconnect_fn (file:///app/node_modules/eventsource/dist/index.js:192:53)\n    at file:///app/node_modules/eventsource/dist/index.js:45:174\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"}
{"level":"error","message":"[MCP][everything] Failed after 3 attempts"}
{"event":{},"level":"error","message":"[MCP][everything] Initialization failed SSE error: undefined","stack":"Error: SSE error: undefined\n    at _eventSource.onerror (file:///app/packages/mcp/dist/index.es.js:1:88138)\n    at EventSource.scheduleReconnect_fn (file:///app/node_modules/eventsource/dist/index.js:192:53)\n    at file:///app/node_modules/eventsource/dist/index.js:45:174\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"}
{"code":-32000,"level":"error","message":"[MCP][mcp-obsidian] Connection failed: MCP error -32000: Connection closed","name":"McpError","stack":"McpError: MCP error -32000: Connection closed\n    at an._onclose (file:///app/packages/mcp/dist/index.es.js:1:71241)\n    at _transport.onclose (file:///app/packages/mcp/dist/index.es.js:1:70846)\n    at ChildProcess.<anonymous> (file:///app/packages/mcp/dist/index.es.js:1:91808)\n    at ChildProcess.emit (node:events:524:28)\n    at maybeClose (node:internal/child_process:1104:16)\n    at ChildProcess._handle.onexit (node:internal/child_process:304:5)"}

```

Its just a python server which should respond with the tools,  I know it works as I have a working client which I can call with:

`uv run client.py http://localhost:8000/sse`

Any ideas here?

**Comment by sterankin** [comment]
OK I seem to have it working, in the sense that its reading in from my MCP server now and can pull in the tools, based on the logs,

you can see the 3 tools bring brought in:

Available tools: get_alerts, get_forecast, fetch

```
2025-03-20T20:32:13.682Z info: [MCP] Initializing servers
2025-03-20T20:32:13.683Z info: [MCP][everything] Connection state: connecting
2025-03-20T20:32:13.683Z info: [MCP][everything] Creating SSE transport: https://my-mcp-server-url.com/sse
2025-03-20T20:32:14.161Z debug: [MCP][everything] Transport sending: {"method":"initialize","params":{"protocolVersion":"2024-11-05","capabilities":{},"clientInfo":{"name":"librechat... [truncated]
2025-03-20T20:32:14.569Z debug: [MCP][everything] Transport sending: {"method":"notifications/initialized","jsonrpc":"2.0"}
2025-03-20T20:32:14.710Z info: [MCP][everything] Connection state: connected
2025-03-20T20:32:14.711Z info: [MCP][everything] Capabilities: {"experimental":{},"prompts":{"listChanged":false},"resources":{"subscribe":false,"listChanged":false},"tools":{"listC... [truncated]
2025-03-20T20:32:14.712Z debug: [MCP][everything] Transport sending: {"method":"tools/list","jsonrpc":"2.0","id":1}
2025-03-20T20:32:15.144Z info: [MCP][everything] Available tools: get_alerts, get_forecast, fetch
2025-03-20T20:32:15.144Z info: [MCP] Initialized 1/1 server(s)
2025-03-20T20:32:15.145Z info: [MCP][everything] ✓ Initialized
2025-03-20T20:32:15.145Z info: [MCP] All servers initialized successfully
2025-03-20T20:32:15.146Z debug: [MCP][everything] Transport sending: {"method":"tools/list","jsonrpc":"2.0","id":2}
2025-03-20T20:32:15.353Z info: No changes needed for 'USER' role permissions
2025-03-20T20:32:15.355Z info: No changes needed for 'ADMIN' role permissions
```

But it doesn't seem to be using the tools in the chat, there is no tool calls in the payload.  Is there a setting needed to be able to use the tools somehow or enable them to be used?

current yaml:

```
# Example MCP Servers Object Structure
mcpServers:
  everything:
    # type: sse # type can optionally be omitted
    url: https://my-mcp-server-url.com/sse
    timeout: 60000  # 1 minute timeout for this server, this is the default timeout for MCP servers.
```

I should be able to trigger a tool by asking for current weather alerts in a given state *see the anthropic quickstart server guide).  It works ok for my custom client - but is there a way it needs to be turned on in LibreChat?

if it helps here is the logs from my MCP server when its returning the tools list when LibreChat requests it on startup:


2025-03-20 21:12:09.756 | 2025-03-20 21:12:09,755 DEBUG Sending message via SSE: root=JSONRPCResponse(jsonrpc='2.0', id=2, result={'tools': [{'name': 'get_alerts', 'description': '\n    Get weather alerts for a US state.\n    \n    Args:\n        state: Two-letter US state code (e.g. CA, NY)\n    ', 'inputSchema': {'properties': {'state': {'title': 'State', 'type': 'string'}}, 'required': ['state'], 'title': 'get_alertsArguments', 'type': 'object'}}, {'name': 'get_forecast', 'description': '\n    Get weather forecast for a location.\n    \n    Args:\n        latitude: Latitude of the location.\n        longitude: Longitude of the location.\n    ', 'inputSchema': {'properties': {'latitude': {'title': 'Latitude', 'type': 'number'}, 'longitude': {'title': 'Longitude', 'type': 'number'}}, 'required': ['latitude', 'longitude'], 'title': 'get_forecastArguments', 'type': 'object'}}, {'name': 'fetch', 'description': '\n    Fetch a URL from the internet, optionally simplifying HTML to Markdown.\n    \n    Parameters:\n      - url: The URL to fetch.\n      - max_length: Maximum number of characters to return.\n      - start_index: Starting character index for the returned content.\n      - raw: If True, return the raw HTML content.\n    ', 'inputSchema': {'properties': {'url': {'title': 'Url', 'type': 'string'}, 'max_length': {'default': 5000, 'title': 'Max Length', 'type': 'integer'}, 'start_index': {'default': 0, 'title': 'Start Index', 'type': 'integer'}, 'raw': {'default': False, 'title': 'Raw', 'type': 'boolean'}}, 'required': ['url'], 'title': 'fetchArguments', 'type': 'object'}}]})
-- | --
2025-03-20 21:12:09.756 | 2025-03-20 21:12:09,755 DEBUG chunk: b'event: message\r\ndata: {"jsonrpc":"2.0","id":2,"result":{"tools":[{"name":"get_alerts","description":"\\n    Get weather alerts for a US state.\\n    \\n    Args:\\n        state: Two-letter US state code (e.g. CA, NY)\\n    ","inputSchema":{"properties":{"state":{"title":"State","type":"string"}},"required":["state"],"title":"get_alertsArguments","type":"object"}},{"name":"get_forecast","description":"\\n    Get weather forecast for a location.\\n    \\n    Args:\\n        latitude: Latitude of the location.\\n        longitude: Longitude of the location.\\n    ","inputSchema":{"properties":{"latitude":{"title":"Latitude","type":"number"},"longitude":{"title":"Longitude","type":"number"}},"required":["latitude","longitude"],"title":"get_forecastArguments","type":"object"}},{"name":"fetch","description":"\\n    Fetch a URL from the internet, optionally simplifying HTML to Markdown.\\n    \\n    Parameters:\\n      - url: The URL to fetch.\\n      - max_length: Maximum number of characters to return.\\n      - start_index: Starting character index for the returned content.\\n      - raw: If True, return the raw HTML content.\\n    ","inputSchema":{"properties":{"url":{"title":"Url","type":"string"},"max_length":{"default":5000,"title":"Max Length","type":"integer"},"start_index":{"default":0,"title":"Start Index","type":"integer"},"raw":{"default":false,"title":"Raw","type":"boolean"}},"required":["url"],"title":"fetchArguments","type":"object"}}]}}\r\n\r\n'

2025-03-20 21:12:09.755 | 2025-03-20 21:12:09,754 DEBUG Dispatching request of type ListToolsRequest
2025-03-20 21:12:09.755 | 2025-03-20 21:12:09,754 DEBUG Received message: <mcp.shared.session.RequestResponder object at 0x7f2daed1e450>
2025-03-20 21:12:09.755 | 2025-03-20 21:12:09,754 INFO Processing request of type ListToolsRequest



Thanks

**Reply by ghost** [reply]
Yes .... you should. But because I feared problems like this I never went down this route though I am still interested since this is a cool idea. If you get it working it would be interesting to know what the issue is.  It looks like you already got far. I dont understand LC enough to understand what is actually going on here.

**Comment by sterankin** [comment]
It turns out that in order to use those tools from the MCP server, you need to build an agent.  So you need to uncomment out the lines in the librechat.yaml for agent endpoints:

```
  agents:
    #(optional) Maximum recursion depth for agents, defaults to 25
    recursionLimit: 50
    #(optional) Disable the builder interface for agents
    disableBuilder: false
    #(optional) Agent Capabilities available to all users. Omit the ones you wish to exclude. Defaults to list below.
    #capabilities: ["execute_code", "file_search", "actions", "tools"]
```

then when you restart, in the main model dropdown you will see Agent, when you go to build an agent there is an option to Add Tools.  You can select your custom Tools (as well as any built in tools).
![Screenshot 2025-03-21 at 13 45 38](https://github.com/user-attachments/assets/b476ff9b-9787-4aa9-83cf-7ec408ecac10)
