### DISCUSSION TITLE
Support for Mistral based AI Agents

### DISCUSSION THREAD

**Discussion by ghost** [danny-avila/LibreChat#6490] [Troubleshooting]
I tried everything the documentation and the AI models suggested, possibly 4 or 5 different versions of the librechat.yaml file to make Agents with Mistral models. However I failed. 

The worst thing is I dont even get an error, my request just stalls forever and nothing happens.

If someone could help me out or clarify that Mistral Agents are currently not possible until LC transfers to fully agentic framework under the hood that would also help me a lot. 

I simply wonder if it is an issue on my side or no support for Mistral Agents yet. 

Thanks for you assistance. 

/mq

**Comment by danny-avila** [comment]
If you mean the Mistral Agents i.e. https://docs.mistral.ai/capabilities/agents/ they will not be supported as we have our own agent framework. Though theoretically if it is openai compatible, I'm not sure that it is, it should work.

If you're having trouble with Mistral models, you should share the relevant parts of your librechat.yaml config

**Comment by amengus87** [comment]
I'm encountering the same issue : I want to create a **LibreChat Agent** (not Mistral ones) and use Mistral AI for the provider.
I use the documentation provided here : https://www.librechat.ai/docs/configuration/librechat_yaml/ai_endpoints/mistral

```yaml
endpoints:
  custom:
    - name: 'Mistral'
      apiKey: '${MISTRALAI_API_KEY}'
      baseURL: 'https://api.mistral.ai/v1'
      models:
        default: ['mistral-large-latest', 'mistral-large-2411', 'pixtral-large-latest', 'pixtral-large-2411']
        fetch: false
      titleConvo: true
      titleMethod: "completion"
      titleModel: 'mistral-large-2411'
      modelDisplayLabel: 'Mistral AI'
      # NOTE: For Mistral, it is necessary to drop the following parameters or you will encounter a 422 Error:
      dropParams: ['stop', 'user', 'frequency_penalty', 'presence_penalty']
```

```bash
2025-03-24 11:15:42 error: [api/server/controllers/agents/client.js #sendCompletion] Operation aborted Aborted
2025-03-24 11:16:48 error: [api/server/controllers/agents/client.js #sendCompletion] Operation aborted 422 status code (no body)
2025-03-24 11:16:48 error: [api/server/controllers/agents/client.js #sendCompletion] Unhandled error type 422 status code (no body)
2025-03-24 11:17:14 error: [api/server/controllers/agents/client.js #sendCompletion] Operation aborted Aborted
```
