### DISCUSSION TITLE
Support for grok-2-vision-latest and grok-2-image-latest

### DISCUSSION THREAD

**Discussion by Zz9uk3** [danny-avila/LibreChat#6518] [Help Wanted]
Hello,
I successfully talk to grok-2-latest adding the below part to my librechat.yaml (I am on Huggingface):

```yaml
- name: "xai"
  apiKey: "user_provided"
  baseURL: "https://api.x.ai/v1"
  models:
    default: [
      "grok-2-latest",
      "grok-2-vision-latest",
      "grok-2-image-latest"
    ]
    fetch: false
  titleConvo: true
  titleMethod: "completion"
  titleModel: "grok-2-latest"
  summarize: false
  summaryModel: "grok-2-latest"
  forcePrompt: false
  modelDisplayLabel: "Grok"
```

When I select grok-2-vision-latest and upload a picture it is succesfully uploaded to firebase however later on I recieve an error about the filetype being unsupported:

```
2025-03-25 11:05:40 warn: [OpenAIClient.chatCompletion][stream] API error
2025-03-25 11:05:40 error: 
2025-03-25 11:05:40 error: [handleAbortError] AI response error; aborting request: 412 "Unsupported content-type encountered when downloading image. The only supported content types are [\"image/jpeg\", \"image/jpg\", \"image/png\"]"
```

The same procedure works with gpt-4o-mini without a problem: 

![image](https://github.com/user-attachments/assets/755c430c-fc2d-4276-babc-87213a8e60b1)

The image generation is also not working since I have to use another endpoint:

```
2025-03-25 10:53:26 error: [handleAbortError] AI response error; aborting request: 400 "The model grok-2-image-latest is an image model and is therefore not available on this endpoint. Please use a compatible endpoint such as https://api.x.ai/v1/images/generations. For more information, see https://docs.x.ai/docs/api-reference#image-generations"
```

From what I could gather around the web LibreChat currently can only generate images with the help of plugins. Is there anyone that got image generation with Grok working? At least I couldnt find any solution.

Thank you for any hint in the right direction
