### DISCUSSION TITLE
Docker-compose.yml access to custom librechat.yaml overwritten in upgrade

### DISCUSSION THREAD

**Discussion by hopeseekr** [danny-avila/LibreChat#6545] [Troubleshooting]
## The Problem

Upon doing an upgrade of LibreChat, I lost access to all custom LLM configs (DeepSeek, Perplexity, etc.).

The reason wasn't immediately clear. I thought at first it was the UI refresh, as that seemed most logical.

Upon further investigation, it seems that my `docker-compose.yml` file was overwritten, leading tot he loss of the mapping to `librechat.yaml`.

## The Solution

1. Copy the default `/app/librechat.yaml` to `librechat.yaml` in the root directory.
2. Add the following to `docker-compose.yml`:

```yaml
    volumes:
      - type: bind
        source: ./librechat.yaml
        target: /app/librechat.yaml
```

Now, when the systme is upgraded, the docker-compose.yml will still have proper references for loading librechat.yaml, and the user's custom settings won't be lost.
