### DISCUSSION TITLE
append_current_datetime doesn't seem to work with Bedrock based modelSpecs

### DISCUSSION THREAD

**Discussion by djriversq** [danny-avila/LibreChat#6567] [Troubleshooting]
I have my modelSpec configured as shown below:
```
modelSpecs:
  enforce: false
  prioritize: true
  list:
    - name: "Chat"
      label: "Chat"
      default: true
      description: "Chat"
      iconURL: "/app/client/public/assets/logo.svg"
      preset:
        endpoint: "bedrock"
        region: "eu-west-2"
        model: "mistral.mistral-large-2402-v1:0"
        maxContextTokens: 128000 # Maximum context tokens
        maxTokens: 8192 # Maximum output tokens
        temperature: 0.7
        modelLabel: "Chat"
        greeting: |
          <Greeting>
        promptPrefix: |
          <Prompt prefix>
        append_current_datetime: true
```
However, when asking the model what the current date and time is, it will either hallucinate a random date or tell me it doesn't know.

Looking at the Bedrock invocation logs, I can't see a datetime being passed across to Bedrock. Is this a bug or just unsupported?
