### DISCUSSION TITLE
Azure Foundry endpoint not working

### DISCUSSION THREAD

**Discussion by loureirodnl** [danny-avila/LibreChat#6572] [Troubleshooting]
### What happened?

Hello

Did Azure AI Foundry changed anything recently ?

Because I'm following exactly the explanations on discussion https://github.com/danny-avila/LibreChat/discussions/5924 but I'm having the following error :

![image](https://github.com/user-attachments/assets/1587d0a7-fae6-4e8a-8c5b-b9d1ccb2750a)

![Image](https://github.com/user-attachments/assets/001fb211-7fc6-4027-ae16-8214ef5cca7e)

Version: LibreChat v0.7.7 using docker compose and @rubentalstra suggested librechat.yml config in https://github.com/danny-avila/LibreChat/discussions/5924

```
error: [OpenAIClient.chatCompletion] Unhandled error type Invalid URL
error: [handleAbortError] AI response error; aborting request: Invalid URL
```

I tried everything that is explained in this discussion but nothing worked

My Azure AI Foundry setup :
![image](https://github.com/user-attachments/assets/ae21311e-4f13-4634-96a1-2abd415a2742)

Thank you for your help

Linked to discussion: https://github.com/danny-avila/LibreChat/discussions/5924

### Version Information

```
docker images | grep librechat
ghcr.io/danny-avila/librechat-dev                                                                latest             2947f02d5e16   2 weeks ago     876MB
```

### Steps to Reproduce

Put the following config in librechat.yaml

```
endpoints:
  azureOpenAI:
    groups:
      - group: "DeepSeek-R1"
        apiKey: "${AZURE_DEEPSEEK_API_KEY}"
        baseURL: "https://XXXX.services.ai.azure.com/models/"
        version: "2024-05-01-preview"
        serverless: true
        models:
          DeepSeek-R1: true

```

### Relevant log output

```shell
error: [OpenAIClient.chatCompletion] Unhandled error type Invalid URL
error: [handleAbortError] AI response error; aborting request: Invalid URL
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
For me, it works with the v1 endpoint they give:

```yaml
    - group: "Azure AI Foundry"
      assistants: false 
      apiKey: "${AZURE_DEEPSEEK_API_KEY}"
      baseURL: "https://my-private-endpoint.models.ai.azure.com/v1/"
      version: "2024-08-01-preview"
      serverless: true
      models:
        DeepSeek-R1:
          deploymentName: "DeepSeek-R1"
```

![chrome_ad8NVgkK3R](https://github.com/user-attachments/assets/6ebb6154-74f0-4ad0-8f00-70cb33983c1d)
