### DISCUSSION TITLE
openAI is not listed in UI group selection

### DISCUSSION THREAD

**Discussion by kmilo9999** [danny-avila/LibreChat#6688] [Troubleshooting]
want to have openAI and 'azure openAI' endpoints in libreachat, but only 1 shows. Taking a look at the documentation is possible to separate them:
This is my librechat.yaml, but only azure is listed:
```
endpoints:
      openAI:
        # Endpoint-level configuration
        titleModel: "gpt-4o"
        fileSizeLimit: 5000
        groups:
        # Group-level configuration
        - group: "gpt-4o"
          apiKey: "${AZURE_OPENAI_API_KEY
          instanceName: "ccv-ai"
          version: "${OPENAI_API_VERSION}"
          # Model-level configuration
          models:
            gpt-4o:
              deploymentName: "gpt-4o"
              version: "${OPENAI_API_VERSION}"
      azureOpenAI:
        # Endpoint-level configuration
        titleModel: "Llama-3.3-70B-Instruct"
        fileSizeLimit: 5000
        groups:
        - group: "Llama-3.3-70B-Instruct"
          apiKey: "${LLAMA_KEY}"
          version: "2024-05-01-preview" 
          serverless: true
          models:
             Llama-3.3-70B-Instruct: true

```
What could I be missing that's causing OpenAI not to show up?

![Image](https://github.com/user-attachments/assets/ba8d7cfc-5099-4a56-91db-05b8ace91a2c)

Thank you for the help in advance

**Comment by kmilo9999** [comment]
I just realized the OpenAI group only appears if the OPENAI_API_KEY is set in the environment variables. However, my GPT-4o model is coming from Azure OpenAI.
Since GPT-4o is technically an OpenAI model, it feels a bit off to have it listed under the Azure group — ideally, I’d like to move it to the OpenAI group instead.
I tried adding it as a custom endpoint, but since OpenAI isn’t supported under customEndpoints, it throws an error. I also tried the following configuration, but the model didn’t work:
```
custom:
        # Groq Example
        - name: 'groq'
          apiKey: "${OPENAI_API_KEY}"
          baseURL: "${AZURE_OPENAI_UR:}"
          instanceName: "ccv-ai"
          version: "${OPENAI_API_VERSION}"
          models:
            default:
              [
                'gpt-4o',
              ]
          titleConvo: true
          titleModel: 'gpt-4o'
          modelDisplayLabel: 'groq'

```
```
2025-04-03 17:47:01 error: 
2025-04-03 17:47:01 error: [handleAbortError] AI response error; aborting request: 404 Resource not found
```
