### DISCUSSION TITLE
LibreChat Can't Connect to Ollama

### DISCUSSION THREAD

**Discussion by F1zzyD** [danny-avila/LibreChat#6718] [Troubleshooting]
### What happened?

Even through making the appropriate changes to the config.yaml, LibreChat does not seem to see Ollama, even though Ollama is set up correctly and reports models being ready. I have made all of the changes that have been suggested to LibreChat but nothing changes. It still won't see it.

### Version Information

latest

### Steps to Reproduce

1. Run LibreChat through `docker compose up`
2. Attempt to add Ollama
3. LibreChat doesn't show Ollama

### What browsers are you seeing the problem on?

Firefox

### Relevant log output

```shell

```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
You didn't share your config so I can't help you troubleshoot very well. 

Please review: https://www.librechat.ai/docs/quick_start/custom_endpoints
And try this config:
```yaml
endpoints:
  custom:
    - name: "Ollama"
      apiKey: "ollama"
      baseURL: "http://host.docker.internal:11434/v1/"
      models:
        default: [
          # some defaults in case fetching the list fails
          "llama3.3",
          "llama3.2",
          "llama3.2-vision",
          "qwen2.5",
          "qwen2.5-coder",
          "command-r",
          "mixtral",
          "phi3",
          "phi4",
          ]
        fetch: true
      titleConvo: true
      # titleModel: "phi3"
      titleModel: "current_model" # uses the currently selected model
      modelDisplayLabel: "Ollama"
```
