### DISCUSSION TITLE
I tried hosting it on GKE but failed. It is not able to detect the main index.js file somehow. What to do?

### DISCUSSION THREAD

**Discussion by kambleakash0** [danny-avila/LibreChat#672] [Troubleshooting]
Okay, so I was using the [Docker Install](https://github.com/danny-avila/LibreChat/blob/main/docs/install/docker_install.md) to run the app locally using `docker-compose.yml`, I wanted to host it as a service on Google cloud. Turns out simple Cloud Run service deployment is not possible because it's not a simple, single-container app. So, I broke it down to three separate containers with three deployment and service YAML files and tried to deploy on a GKE cluster that I created. Now, the rest of the two containers are running fine but for the `api` container, I'm getting this error:
```

> LibreChat@0.5.2 backend
> cross-env NODE_ENV=production node api/server/index.js

node:internal/modules/cjs/loader:1093
  throw err;
  ^

Error: Cannot find module '/app/api/server/index.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1090:15)
    at Module._load (node:internal/modules/cjs/loader:934:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v19.9.0
```
Am I doing something wrong?
Or, is there a way to convert it into a single-container app and host it on Google Cloud Run?

**Comment by danny-avila** [comment]
I would need more info on how your compose file looks like for the former question. My guess is you removed volumes and they are not being referenced correctly in the container, but for this
>  Or, is there a way to convert it into a single-container app and host it on Google Cloud Run?

Yes, you can omit meilisearch and mongodb completely and just use mongodb atlas for the mongo_uri var.

I made a compose file working for you, let me know if it works, about to push it up to main. 

If it works, writing a guide would be really appreciated!

**Comment by danny-avila** [comment]
Just pushed: https://github.com/danny-avila/LibreChat/pull/676

### single-compose.yml: 
- Dockerfile for building app image without meilisearch and mongodb services
  - This is useful for deploying on Google, Azure, etc., as a single, leaner container.
- From root dir of the project, run `docker-compose -f ./docs/dev/single-compose.yml up --build`
  - When you don't need to build, run `docker-compose -f ./docs/dev/single-compose.yml up`
- This requires you use a MongoDB Atlas connection string for the `MONGO_URI` env var
  - A URI string to a mongodb service accessible to your container is also possible.
  - Remote Meilisearch may also be possible in the same manner, but is not tested.

**Reply by dkindlund** [reply]
@danny-avila , where is this `single-compose.yml` file currently?  I can't seem to find it in `main` anymore...

**Reply by fuegovic** [reply]
that file isn't in the repo anymore, it's been deprecated following the introduction of the override file...

You can always make your own compose file that doesn't include meilisearch / mongodb / rag_api / vectordb to reproduce the `single-compose.yml`

**Reply by dkindlund** [reply]
Hey @fuegovic , got it.  The fact that there isn't a pre-built `docker-compose.yml` like `single-compose.yml` probably explains why users are having trouble getting LibreChat deployed to GCP, for example:
https://github.com/danny-avila/LibreChat/discussions/3122

**Reply by dkindlund** [reply]
Hey @fuegovic and @danny-avila , so I tried to re-create the `single-compose.yml` file here:
https://github.com/fletch-ai/LibreChat/blob/main/docker-compose.yml

And even after deploying to GCP as a new Cloud Run container, it still fails startup health checks:
![image](https://github.com/danny-avila/LibreChat/assets/85660/e7e8ac0a-eae1-48a8-917f-a440601a86bd)

Even though the logs say the container is listening in on port 3080, the container health checks consistently fail:
![image](https://github.com/danny-avila/LibreChat/assets/85660/6db5a15b-2994-49d8-80a8-5ee68301de27)

Any ideas as to why this is still happening?

**Reply by fuegovic** [reply]
@dkindlund 
I have this in my custom compose file for healthcheck:

```yml
version: "3.9"

services:
  # LibreChat
  api:
    container_name: LibreChat
    image: ghcr.io/danny-avila/librechat-dev:latest
    ports:
      - "${PORT}:${PORT}"
    restart: always
    env_file:
      - stack.env
    volumes:
      - ./images:/app/client/public/images
      - ./uploads/temp:/app/uploads/temp
      - ./api/logs:/app/api/logs/ 
      - ./app/data:/app/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3080/health"]
      interval: 30s
      timeout: 5s
      retries: 3
```
