### DISCUSSION TITLE
Openrouter agents?

### DISCUSSION THREAD

**Discussion by vanadium23** [danny-avila/LibreChat#6742] [Troubleshooting]
I have setup an example config to grab an MCP server.
```

endpoints:
  custom:
    # OpenRouter Example
    - name: "openrouter"
      # For `apiKey` and `baseURL`, you can use environment variables that you define.
      # recommended environment variables:
      apiKey: "${OPENROUTER_KEY}"
      baseURL: "https://openrouter.ai/api/v1"
      models:
        default: ["anthropic/claude-3.7-sonnet"]
        fetch: true
      titleConvo: true
      titleModel: "anthropic/claude-3.7-sonnet"
      # Recommended: Drop the stop parameter from the request as Openrouter models use a variety of stop tokens.
      dropParams: ["stop"]
      modelDisplayLabel: "OpenRouter"

mcpServers:
  wallabag:
    command: npx
    args:
      - -y
      - "@modelcontextprotocol/server-postgres"
      - "postgresql://my_hos/my_db"
  ```

And have a following .env:
```
ENDPOINTS=agents,custom
```

But all I can see in UI is openrouter chat. There is no button to add agent. What should I do?
