### DISCUSSION TITLE
MCP - Handling Complex Schemas + System Prompt

### DISCUSSION THREAD

**Discussion by lnvestor** [danny-avila/LibreChat#6773] [Troubleshooting]
# Claude/Anthropic Model Unable to Handle Complex JSON Schema with anyOf/oneOf

## Description
I've set up LibreChat with a custom MCP server containing 20 tools with complex schemas. While the tools are correctly displayed and accessible, I'm encountering issues when Claude (Anthropic's model) attempts to create connections using schemas that contain `anyOf`/`oneOf` conditions.https://github.com/danny-avila/LibreChat/issues/new/choose

## Environment
- LibreChat (Docker deployment)
- Custom MCP server
- Anthropic's latest model with Tools support

## Configuration

**docker-compose.override.yml**
```yaml
services:
  api:
    environment:
      - MONGO_URI=${MONGO_URI}
    volumes:
      - ./librechat.yaml:/app/librechat.yaml
      - /Users/drisstalainte/Documents/Cline/MCP:/app/mcp
  mongodb:
    image: arm64v8/mongo:latest
    command: ""
    entrypoint: ""
```

**MCP server yaml config**
```yaml
myMCP:
  type: stdio
  command: "node"
  args:
    - "/app/mcp/MyMCP-server/build/index.js"
  env:
    NODE_ENV: production
    MyMCP_BEARER_TOKEN: "f596**********9dcf7f44c0"
```

## Error
When attempting to create a connection, the following error occurs:
```
2025-01-24 00:05:26 LibreChat | 2025-01-23 23:05:26 error: create_connection MCP server tool call failed MCP error -32603: MCP error -32603: MCP error -32602: Missing required parameters: type, name
```

## Investigation
The issue appears to be related to how complex JSON schemas with `anyOf`/`oneOf` conditions are handled. Looking at Cline's implementation (specifically [this code](https://github.com/cline/cline/blob/2dceadbb2428d1504c7a4f6d9a8efa4add6ae570/src/core/prompts/system.ts#L372)), they handle this by:
1. Using custom prompts
2. Using `JSON.stringify` to send the input schema

## Potential Solution
Implementing similar handling of complex schemas as Cline does might resolve this issue.

## Additional Context
- Full schema implementation is provided in the comment below (due to length)
- [Screenshot of tools display](https://github.com/user-attachments/assets/fd0e69fc-be31-4d77-87af-6c1779f19de1)

---

Would you like me to post the schema as a comment to maintain better readability of the main issue?
