### DISCUSSION TITLE
Ollama Endpoint Not Showing in LibreChat UI Despite Correct Setup (Windows + Docker)

### DISCUSSION THREAD

**Discussion by neverresting77** [danny-avila/LibreChat#6779] [Troubleshooting] [answered]
**Goal:**
I'm trying to integrate my locally running Ollama instance (installed via the Windows installer, running directly on the host) with LibreChat (v0.7.7, running in Docker via `docker compose`).

**Environment:**

*   **OS:** Windows 10 (Version 10.0.19045.5608)
*   **Docker:** Docker Desktop 28.0.4
*   **LibreChat:** v0.7.7 (Cloned from GitHub, running via `docker compose`)
*   **Ollama:** Running directly on the Windows host (installed via official installer), accessible at `http://localhost:11434`.

**Problem:**
The "Ollama" endpoint and its models do not appear in the LibreChat model selection menu in the web UI (`http://localhost:3080`). The LibreChat container starts without apparent errors in the logs related to YAML loading, and network connectivity to the host Ollama server from within the container is confirmed.

**Troubleshooting Steps Performed:**

1.  **Initial Setup:** Successfully installed LibreChat using Docker Compose, including cloning the repo, copying `.env.example` to `.env`, creating `docker-compose.yml` from the repository source, creating necessary data directories, and mounting the `.env` file.
2.  **`librechat.yaml` Configuration:**
    *   Created `librechat.yaml` in the project root.
    *   Mounted the file into the `api` container using `docker-compose.yml`:
        ```yaml
        volumes:
          - type: bind
            source: ./librechat.yaml
            target: /app/librechat.yaml
        ```
    *   Configured the `endpoints.custom` section for Ollama. The final, simplified configuration (after several iterations) is:
        ```yaml
        version: 1.2.1
        cache: true
        interface:
          customWelcome: "Welcome to LibreChat! Enjoy your experience."
        privacyPolicy:
          externalUrl: 'https://librechat.ai/privacy-policy'
          openNewTab: true
        termsOfService:
          externalUrl: 'https://librechat.ai/terms-of-service'
          openNewTab: true
        endpoints:
          custom:
            - name: "Ollama"
              apiKey: "ollama"          # Re-added based on guides, seems required by LibreChat
              baseURL: "http://host.docker.internal:11434/v1/" # For accessing host from Docker
              models:
                # Updated based on `ollama list` output
                default: ["llama3:8b-instruct-q4_K_M", "mistral:7b"]
                fetch: true
              titleModel: "current_model" # Changed from "self-host"
              modelDisplayLabel: "Ollama"
              order: 10
        mcp:
          enabled: false
          port: 3090
          plugins: {}
        ```
    *   **YAML Errors Resolved:** During the process, corrected errors found in logs, including "invalid API key" (initially removed `apiKey`, then re-added it) and "duplicated mapping key" / "invalid YAML format" (removed duplicate `endpoints:` section and stray ```).
3.  **`.env` Configuration:**
    *   To isolate the Ollama issue, API keys for other services (OpenAI, Google, Anthropic, Assistants) were commented out (e.g., `# OPENAI_API_KEY=user_provided`). The `ENDPOINTS` variable remains commented out.
4.  **Network Connectivity Test:**
    *   Successfully confirmed that the LibreChat container can reach the host Ollama server using:
        ```bash
        docker exec LibreChat curl http://host.docker.internal:11434/api/tags
        ```
    *   This command returned the start of the JSON model list (`{"models":[{"name":"llama...`), indicating successful communication.
5.  **Container Management:** Consistently restarted containers using `docker compose down && docker compose up -d` after each configuration change.
6.  **LibreChat Reinstallation:** Performed a full reinstallation by stopping/removing containers and volumes (`docker compose down --volumes`), deleting the `LibreChat` directory, re-cloning, and repeating the setup steps.
7.  **Browser Cache:** Cleared browser cache and performed hard refreshes.
8.  **Log Analysis:** Current `docker logs LibreChat` show no errors related to YAML loading or API keys after the latest corrections. The server starts successfully and listens on port 3080.

**Current Status:**
Despite all the steps above, the Ollama endpoint is still not visible in the LibreChat UI model selection menu. Only the default "Agents" item might appear, or standard endpoints if their API keys are uncommented in `.env`.

**Request:**
I've exhausted the common troubleshooting steps. Could there be a subtle issue with the `librechat.yaml` configuration for Ollama specifically in v0.7.7 on Windows, a specific Docker Desktop interaction, or another hidden factor preventing the endpoint from registering correctly in the UI? Any insights or suggestions would be greatly appreciated.

**Comment by neverresting77** [comment, marked as answer]
Finally, I found the soultion by myself.
# Troubleshooting Log: Connecting Local Ollama to LibreChat (v0.7.7) on Docker

## Goal

Configure a Dockerized LibreChat (v0.7.7) instance to use models hosted on a local Ollama server.

## Initial State

*   LibreChat (v0.7.7) running via Docker Desktop on a Windows environment.
*   Local Ollama server installed with necessary models (e.g., `llama3:8b-instruct-q4_K_M`, `mistral:7b`) downloaded.
*   LibreChat UI, by default, only shows external API models like OpenAI.

## Troubleshooting Process

### 1. Issue: Ollama Endpoint Configuration Not Applied

*   **Symptom:** Modifying the `.env` file to add Ollama settings or changing existing endpoint variables has no effect on the UI. Only default models (like OpenAI) are displayed.
*   **Diagnosis:** LibreChat likely prioritizes the `ENDPOINTS` environment variable or the `librechat.yaml` file over individual endpoint settings in the `.env` file. If `ENDPOINTS` is set to something else (or perhaps even its default), it might ignore other API key settings in `.env`.
*   **Attempt 1 (Modify `.env`):**
    *   Locate the `ENDPOINTS` variable in the `.env` file and set it to use `librechat.yaml`:
        ```dotenv
        ENDPOINTS=librechat.yaml
        ```
    *   Comment out or leave API key variables for other endpoints (OpenAI, Google, etc.) as they are (e.g., `user_provided`), as they will be ignored when `librechat.yaml` is used.
*   **Attempt 2 (Create and Configure `librechat.yaml`):**
    *   Create a `librechat.yaml` file in the LibreChat project root.
    *   Add a `custom` endpoint configuration for Ollama:
        ```yaml
        version: 1.2.1 # Specify the config version
        endpoints:
          custom:
            - name: "Ollama"
              apiKey: "ollama"  # Dummy value as Ollama doesn't require an API key
              baseURL: "http://host.docker.internal:11434/v1/" # Address for the Docker container to reach the host's Ollama
              models:
                default: ["llama3:8b-instruct-q4_K_M", "mistral:7b"] # Specify the exact names of the models to use
                fetch: true # Enable dynamic loading of the model list from the Ollama server
              titleModel: "current_model" # Use the current model for generating conversation titles
              modelDisplayLabel: "Ollama" # Label for the endpoint shown in the UI
              order: 10 # Display order in the UI
        ```
    *   Rebuild and restart Docker containers: `docker-compose up -d --build`
*   **Result:** All models disappeared from the UI. This is a positive sign, indicating that the `ENDPOINTS=librechat.yaml` setting is now active, and LibreChat is attempting to read the `librechat.yaml` file instead of `.env`. However, the Ollama models are still not displayed.

### 2. Issue: Models Not Displayed After Loading `librechat.yaml`

*   **Symptom:** The model selection menu in the UI is empty after setting `ENDPOINTS=librechat.yaml`.
*   **Diagnosis 1 (Potential `librechat.yaml` Content Error):**
    *   The `fetch: true` option might be disabled, or the model names specified in `models.default` might not exactly match the names on the Ollama server.
    *   **Test:** Comment out `fetch: true`, simplify `models.default` (e.g., `["llama3"]`) -> Failed. Re-enable `fetch: true`, use exact model names -> Failed.
*   **Diagnosis 2 (Check LibreChat API Container Logs):**
    *   Command: `docker logs LibreChat --tail 100` (Later corrected to `docker logs api --tail 100` after identifying the correct service name).
    *   **Error Found:**
        ```
        error: Invalid custom config file at /app/librechat.yaml:
        ...
        message: "Unrecognized key(s) in object: 'privacyPolicy', 'termsOfService', 'tools', 'mcp'"
        ...
        ```
        The current LibreChat version (v0.7.7) does not recognize certain configuration keys (`privacyPolicy`, `termsOfService`, `tools`, `mcp`) present in the `librechat.yaml` file (likely from a newer template). This prevents the file from being parsed correctly.
*   **Solution:** Comment out the entire sections related to the unrecognized keys (`privacyPolicy`, `termsOfService`, `tools`, `mcp`) in the `librechat.yaml` file.
*   **Application:**
    1.  Modify `librechat.yaml` (comment out the problematic sections).
    2.  Restart the Docker container (using `docker-compose restart api` after confirming the service name).
*   **Result:** The Ollama models configured in `librechat.yaml` (including those fetched dynamically via `fetch: true`, like `llama3:8b-instruct-q4_K_M`, `mistral:7b`) are now correctly displayed in the UI's model selection menu.

### 3. Side Issue: Docker Service Restart Error

*   **Symptom:** Running `docker-compose restart LibreChat` results in a `no such service: LibreChat` error.
*   **Cause:** Mismatch between the service name defined in `docker-compose.yml` and the name used in the command. Checking the file revealed the service name is `api`, while the container name is `LibreChat`.
*   **Solution:** Use the correct service name `api` in the command: `docker-compose restart api`.

## Final Successful Configuration Summary

*   **`.env` file:** `ENDPOINTS=librechat.yaml` setting enabled.
*   **`librechat.yaml` file:**
    *   `version: 1.2.1` specified.
    *   Ollama configuration added under the `endpoints.custom` section (including `baseURL`, `models.default`, `fetch: true`).
    *   Keys unrecognized by v0.7.7 (`privacyPolicy`, `termsOfService`, `tools`, `mcp`) commented out.
*   **`docker-compose.yml` file:** No changes needed (aware that the service name is `api`).
![image](https://github.com/user-attachments/assets/291a5416-9fda-46fa-a55a-0df8a4fb92b8)

**Reply by danny-avila** [reply]
>       * Locate the `ENDPOINTS` variable in the `.env` file and set it to use `librechat.yaml`:
>         ```dotenv
>         ENDPOINTS=librechat.yaml
>         ```

For using Ollama exclusively, you can use `ENDPOINTS=custom`, that is the correct configuration

**Reply by neverresting77** [reply]
Hi Danny,

Thanks for the suggestion to use ENDPOINTS=custom in the .env file when exclusively using Ollama via librechat.yaml.
I'm trying to integrate my local Ollama setup with LibreChat v0.7.7 and also utilize the Tools and MCP features defined in librechat.yaml.

However, I'm encountering an issue:

1.   When I uncomment the tools: and mcp: sections at the top level of my librechat.yaml file (following the structure in librechat.example.yaml), the LibreChat container fails to load the configuration correctly. The logs show an Invalid custom config file ... Unrecognized key(s) in object: 'tools', 'mcp' error (ZodError). This results in the model selection menu disappearing or becoming empty in the UI.
2.  Commenting out the tools: and mcp: sections allows the endpoints.custom.Ollama configuration to load successfully (using either ENDPOINTS=librechat.yaml or ENDPOINTS=custom in .env), and I can use my Ollama models.
3. Setting ENDPOINTS=custom in .env unfortunately doesn't resolve the issue if the tools: or mcp: keys are uncommented in librechat.yaml, as the file parsing fails before the endpoint selection logic seems to apply.

It appears that LibreChat v0.7.7 does not recognize the top-level tools: and mcp: keys in librechat.yaml.
Is there a different way to configure Tools and MCP integration in v0.7.7, specifically when primarily using a local LLM like Ollama defined in the endpoints.custom section? I'd really like to leverage these features alongside my local models.

Thanks for your help!
<img width="755" alt="20250408_211615" src="https://github.com/user-attachments/assets/fa2f5a81-d919-41fc-949a-fb0f49a29413" />

**Comment by tandryukha** [comment]
I solved it following these steps:
1. specified local ollama models in librechat.yaml
```endpoints:
  
  custom:
    - name: "Ollama"
      apiKey: "ollama"  # Dummy value as Ollama doesn't require an API key
      baseURL: "http://host.docker.internal:11434/v1/" # Address for the Docker container to reach the host's Ollama
      models:
        default: ["deepseek-coder:latest"] # Specify the exact names of the models to use
        fetch: true # Enable dynamic loading of the model list from the Ollama server
      titleModel: "current_model" # Use the current model for generating conversation titles
      modelDisplayLabel: "Ollama" # Label for the endpoint shown in the UI
      order: 10 # Display order in the UI

```

2. specified both custom and pre-built endpoints in .env
```ENDPOINTS=openAI,ollama-deepseek```

3. added the volume in docker-compose.yml for librechat.yaml:
```   volumes:
      - type: bind
        source: ./.env
        target: /app/.env
      - type: bind
        source: ./librechat.yaml
        target: /app/librechat.yaml```

**Reply by tandryukha** [reply]
<img width="420" alt="Screenshot 2025-04-11 at 23 29 52" src="https://github.com/user-attachments/assets/ce011810-a747-4e8b-95b8-f60b6d644773" />

**Reply by CyprienGille** [reply]
Your 3rd step is what fixed the same issue for me, thank you!

**Reply by kwadwoadu** [reply]
Thank you! I've been dealing with this all day!

**Comment by thebearking-cmd** [comment]
### Discussion #6779: Ollama Endpoint Not Showing (Chiming in)

**Experiencing the same issue on Garuda Linux (Arch-based) with LibreChat v0.7.9 Docker and native Ollama 0.2.9.
My Setup**

LibreChat running in Docker (v0.7.9)
Ollama running natively on host at 0.0.0.0:11434
Firewall port 11434 open

What I've Tried

**1) .env configuration:**

```
envENABLE_OLLAMA=true
OLLAMA_BASE_URL=http://172.17.0.1:11434
```

Also tried: `localhost`, `127.0.0.1`, `host.docker.internal`

**2) Verified connectivity:**

From host: `curl http://localhost:11434/api/tags`  (shows all models)
From inside container: `wget http://172.17.0.1:11434/api/tags` (works)
**_Ollama is definitely reachable from the container_**


**3) docker-compose.override.yml attempts:**

`network_mode: host` - breaks LibreChat UI entirely
`extra_hosts entries` - no effect



Result
Same as OP - backend logs show `[Provider] Ollama not enabled, skipping model init` despite `ENABLE_OLLAMA=true`

**_Additional Context_**
This issue led me to attempt building from source, which revealed a separate bug with Bun builds failing (will file separately). After 6+ hours across two days, still no working Ollama integration. Had to build from source due to binaries being yanked the morning after I nuked a failed repair attempt.

**Reply by danny-avila** [reply]
Hi @thebearking-cmd 

You are referencing environment variables that may be specific to Ollama but not LibreChat, and you haven't shared your custom endpoint config.

You need your `librechat.yaml` to have something like the following:

```yaml
endpoints:
  custom:
    - name: "Ollama"
      apiKey: "ollama"
      # `baseURL` should be whatever is accessible in your LC env
      # baseURL: "http://host.docker.internal:11434/v1/"
      baseURL: "http://127.0.0.1:11434/v1/"
      models:
        default: [
          "llama3.3",
          "llama3.2",
          "llama3.2-vision",
          "qwen2.5",
          "qwen2.5-coder",
          "command-r",
          "mixtral",
          "phi3",
          "phi4",
          "deepseek-r1:32b",
          ]
        fetch: true
      titleConvo: true
      titleModel: "current_model"
      modelDisplayLabel: "Ollama"
```

Please review the following docs:
- https://www.librechat.ai/docs/quick_start/custom_endpoints
- https://www.librechat.ai/docs/configuration/librechat_yaml/ai_endpoints/ollama
