### DISCUSSION TITLE
Help with modelDisplayLabel for Bedrock

### DISCUSSION THREAD

**Discussion by dannykorpan** [danny-avila/LibreChat#6888] [Help Wanted]
Hi Community,

I'm using Amazon Bedrock to access Claude. However, the menu displays the entire model name as provided by Amazon. How can I change this to a nicer name, like simply "Claude"?

Here is the relevant part of my .env:
```
...
BEDROCK_AWS_DEFAULT_REGION=eu-central-1
BEDROCK_AWS_ACCESS_KEY_ID=XYZ
BEDROCK_AWS_SECRET_ACCESS_KEY=XYZ
BEDROCK_AWS_MODELS=arn:aws:bedrock:eu-central-1:471112931003:inference-profile/eu.anthropic.claude-3-7-sonnet-20250219-v1:0
ENDPOINTS=azureOpenAI,bedrock,azureAssistants,agents
...
```

And here the relevant part of my librechat.yaml:
```
...
endpoints:
  custom:
  bedrock:
    enabled: true
    modelDisplayLabel: "Claude 3.7 Sonnet"
    models:
      default: ["arn:aws:bedrock:eu-central-1:471112931003:inference-profile/eu.anthropic.claude-3-7-sonnet-20250219-v1:0"]
...
```

<img width="735" alt="image" src="https://github.com/user-attachments/assets/5bca32a4-0de3-4b14-ad50-98b423d86e30" />

Thanks in advance for your help,
Danny
