### DISCUSSION TITLE
LibreChat always enforces a max context length of 4096

### DISCUSSION THREAD

**Discussion by pedrib** [danny-avila/LibreChat#6894] [Help Wanted]
I'm using the dockerized LibreChat, Ollama backend, with the cogito:32b model (supports up to 128k context length).

When I try to send a message with more than 4096 tokens, I get the following error message on the LibreChat web UI:
> The latest message token count is too long, exceeding the token limit (13948 / 4095 respectively). Please shorten your message, adjust the max context size from the conversation parameters, or fork the conversation to continue.

Looking at the docker logs, I also see:
```
LibreChat         | 2025-04-15 10:30:16 warn: Prompt token count exceeds max token count (13952 / 4095).
LibreChat         | 2025-04-15 10:30:16 error: [handleAbortError] AI response error; aborting request: { "type": "INPUT_LENGTH", "info": "13952 / 4095"
```

I've tried editing `librechat.yaml` and adding the following:

```yaml
custom:
  - name: Ollama
  (...)
  maxContextTokens: 128000
  max_tokens: 128000
  addParams:
    max_tokens: 128000
    maxContextTokens: 128000
```

But I still get the same error after restarting all the docker containers (with `docker compose ...`). 
Using Ollama on the command line, the model seems to accept at least 32k tokens without a problem. 

Am I doing something wrong here? What is the right way to increase the context length?

**Comment by pedrib** [comment]
A quick update:

I've added `OLLAMA_CONTEXT_LENGTH: 16384` as an enviroment variable in `docker-compose.override.yml` and confirm that Ollama processes up to that context length via the command line (of course, memory usage increases substantially).

Also tried to modify `librechat.yaml` with the following:

```yaml
custom:
  - name: Ollama
  (...)
  addParams:
    num_ctx: 16384
```

... but I still get the 4095 max context length message as shown above.
