### DISCUSSION TITLE
Chat History Not Displayed After Upgrading to v0.7.7

### DISCUSSION THREAD

**Discussion by alanqs18** [danny-avila/LibreChat#6914] [Troubleshooting]
### What happened?

Description:
After upgrading from LibreChat v0.7.5/v0.7.6 to v0.7.7, all chat history from previous days no longer appears in the sidebar. When I downgrade back to v0.7.5 or v0.7.6, the chat history is visible again.

Environment:
LibreChat version: v0.7.7 (issue), v0.7.6/v0.7.5 (working)
Deployment method: Docker Compose
Operating system: macOS Sequoia Version 15.4

Expected Behavior:
All previous chat history should be visible in the sidebar, as it is in v0.7.5/v0.7.6.

Actual Behavior
Chat history from previous days is not displayed in the sidebar when using v0.7.7. Only new chats created today and yesterday appear.

# Base docker-compose.yml
services:
  api:
    container_name: LibreChat
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - mongodb
    #  - rag_api
    image: ghcr.io/danny-avila/librechat-dev:latest
    restart: always
    user: "${UID}:${GID}"
    extra_hosts:
    - "host.docker.internal:host-gateway"
    environment:
      - HOST=0.0.0.0
      - MONGO_URI=mongodb://mongodb:27017/LibreChat
      - MEILI_HOST=http://meilisearch:7700
      - RAG_PORT=${RAG_PORT:-8000}
      - RAG_API_URL=http://rag_api:${RAG_PORT:-8000}
          # Add Timezone setting Beijing Time
      - TZ=Asia/Shanghai  #
    volumes:
      - type: bind
        source: ./.env
        target: /app/.env
      - ./images:/app/client/public/images
      - ./uploads:/app/uploads
      - ./logs:/app/api/logs
      - ./app_data:/app/data
  mongodb:
    container_name: chat-mongodb
    image: mongo
    restart: always
    user: "${UID}:${GID}"
    volumes:
      - ./data-node:/data/db
    command: mongod --noauth
  meilisearch:
    container_name: chat-meilisearch
    image: getmeili/meilisearch:v1.12.3
    restart: always
    user: "${UID}:${GID}"
    environment:
      - MEILI_HOST=http://meilisearch:7700
      - MEILI_NO_ANALYTICS=true
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
    volumes:
      - ./meili_data_v1.12:/meili_data
  vectordb:
    container_name: vectordb
    image: ankane/pgvector:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    restart: always
    volumes:
      - pgdata2:/var/lib/postgresql/data
  #  rag_api:
  #    container_name: rag_api
  #    image: ghcr.io/danny-avila/librechat-rag-api-dev-lite:latest
  #    environment:
  #      - DB_HOST=vectordb
  #      - RAG_PORT=${RAG_PORT:-8000}
  #    restart: always
  #    depends_on:
  #      - vectordb
  #    env_file:
  #      - .env

volumes:
  pgdata2:

# Override file (docker-compose.override.yml)
services:
   api:
     volumes:
     - type: bind
       source: ./librechat.yaml
       target: /app/librechat.yaml
     image: ghcr.io/danny-avila/librechat:latest

### Version Information

ghcr.io/danny-avila/librechat-dev                latest    5e51e467b29c   3 days ago      942MB
ghcr.io/danny-avila/librechat-rag-api-dev-lite   latest    49a785a50986   7 days ago      1.28GB
ghcr.io/danny-avila/librechat                    latest    0eded051543d   5 weeks ago     894MB
ghcr.io/danny-avila/librechat                    v0.7.6    feb898da4806   3 months ago    898MB
ghcr.io/danny-avila/librechat                    v0.7.5    70b426c6424b   5 months ago    888MB

### Steps to Reproduce

Run LibreChat v0.7.5 or v0.7.6 and I can see all the historic chats.
Update docker-compose.override.yml to use latest image (v0.7.7)
Run docker compose up -d
Open the UI - all previous chat history except for today and yesterday is missing.

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell

```

### Screenshots

v0.7.6 or v0.7.5:

<img width="987" alt="Image" src="https://github.com/user-attachments/assets/374f9fc2-b624-42af-b771-4948640a16a9" />

v0.7.7:

<img width="1141" alt="Image" src="https://github.com/user-attachments/assets/d5c0fc07-8d2f-4b6a-92f8-8d904896cd00" />

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by Odrec** [comment]
Seems you're running the 0.7.5, 0.7.6 and 0.7.7 (latest) containers alongside the latest dev?

**Comment by alanqs18** [comment]
Originally, I just wanted to use the latest version of LibreChat, but I noticed that the UI looked different compared to what other users have shown. I tried an older version and discovered that the conversation history is incomplete in v0.7.7.

**Reply by Odrec** [reply]
There are two latest versions. One is the dev latest and the other is the latest. You seem to be running both as well as other versions. You should first get rid of those.

What is the output when you do `docker ps`?

**Comment by alanqs18** [comment]
@Odrec , thank you very much for your attention.

The Output of docker ps:

<img width="1155" alt="image" src="https://github.com/user-attachments/assets/29013699-d0b8-4893-8b9c-2178fa41ac60" />

**Reply by Odrec** [reply]
Ok, that looks fine. Are you sure your mongodb container is the same? Also, remember that 0.7.7 came with a meilisearch upgrade so the indexing has to be redone. Depending on how big your database was, that might take a while.

**Reply by Odrec** [reply]
Maybe try logging into the mongodb container and querying how many conversations are there.

**Reply by alanqs18** [reply]
Thank you @Odrec  for your prompt reply and suggestion, however I'm not sure how to do that.

**Comment by danny-avila** [comment]
If you can, go into your chrome network tab and compare the results of the `convos` requests, how different they are between versions.

![chrome_p5YaNC61fq](https://github.com/user-attachments/assets/7723624c-cf82-42cd-879e-837855b518be)


also i have a suspicion you are not on the same user account when comparing users. you can also check in the network tab with `user` filter.

**Reply by alanqs18** [reply]
Thank you so much for your reply. 

I’m using the same account, but today I noticed that in v0.7.7, I can see the chat history up to the day before yesterday, but not further back. However, when I switch to v0.7.6 or an earlier version, I can access even older chat history.

So, I believe that starting from April 15th, the v0.7.7 version began retaining chat history. However, when I switch to v0.7.6 or v0.7.5, I can still see all the previous chat history.

v0.7.7:
<img width="1024" alt="image" src="https://github.com/user-attachments/assets/4b108b45-4056-4832-8e77-b9c89fa83f1c" />

v0.7.6:
<img width="1028" alt="image" src="https://github.com/user-attachments/assets/431fae6d-1073-40f6-8139-82adf3fe1902" />

**Reply by alanqs18** [reply]
v0.7.6:
<img width="1916" alt="image" src="https://github.com/user-attachments/assets/1d172dc7-22ba-4f07-ad6c-4e72af3bbc6a" />


v0.7.7:
<img width="1915" alt="image" src="https://github.com/user-attachments/assets/657cee58-ade3-4479-96db-1ebb475976ba" />

**Comment by programmeddeath1** [comment]
Hey I have insatlled and run the lates version of librechat. I just cloned and then ran compose up. it runs but none of my chat gets saved. Im not sure what is the reason. I even tried to add auth to mongodb as below - 
```
cat docker-compose.yml 
# Do not edit this file directly. Use a ‘docker-compose.override.yaml’ file if you can.
# Refer to `docker-compose.override.yaml.example’ for some sample configurations.

services:
  api:
    container_name: LibreChat
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - mongodb
      - rag_api
    image: ghcr.io/danny-avila/librechat-dev:latest
    restart: always
    user: "${UID}:${GID}"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - HOST=0.0.0.0
#    - MONGO_URI=mongodb://mongodb:27017/LibreChat
      - MONGO_URI=mongodb://librechat:securepassword123@mongodb:27017/LibreChat?authSource=admin
      - MEILI_HOST=http://meilisearch:7700
      - RAG_PORT=${RAG_PORT:-8000}
      - RAG_API_URL=http://rag_api:${RAG_PORT:-8000}
    volumes:
      - type: bind
        source: ./.env
        target: /app/.env
      - ./images:/app/client/public/images
      - ./uploads:/app/uploads
      - ./logs:/app/api/logs
  mongodb:
    container_name: chat-mongodb
    image: mongo
    restart: always
    user: "${UID}:${GID}"
    environment:
      MONGO_INITDB_ROOT_USERNAME: librechat
      MONGO_INITDB_ROOT_PASSWORD: securepassword123
    volumes:
      - ./data-node:/data/db
      - mongodb_data:/data/db
    ports:
      - "27017"
    #command: mongod --noauth
    command: mongod --bind_ip_all

  meilisearch:
    container_name: chat-meilisearch
    image: getmeili/meilisearch:v1.12.3
    restart: always
    user: "${UID}:${GID}"
    environment:
      - MEILI_HOST=http://meilisearch:7700
      - MEILI_NO_ANALYTICS=true
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
    volumes:
      - ./meili_data_v1.12:/meili_data
  vectordb:
    container_name: vectordb
    image: ankane/pgvector:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    restart: always
    volumes:
      - pgdata2:/var/lib/postgresql/data
  rag_api:
    container_name: rag_api
    image: ghcr.io/danny-avila/librechat-rag-api-dev-lite:latest
    environment:
      - DB_HOST=vectordb
      - RAG_PORT=${RAG_PORT:-8000}
    restart: always
    depends_on:
      - vectordb
    env_file:
      - .env

volumes:
  mongodb_data:  
  pgdata2:

```

 to check if it was permissins issue. But still only current chat shows.

![Screenshot from 2025-05-11 11-52-53](https://github.com/user-attachments/assets/f8c4f0ea-3b9a-4546-bca0-baa85e908997)
