### DISCUSSION TITLE
Agent builder doesn't respect `modelSpecs`

### DISCUSSION THREAD

**Discussion by eparreno** [danny-avila/LibreChat#7009] [Troubleshooting]
### What happened?

When using `modelSpecs` and hiding endpoints, the Agent Builder is not aware of these settings and shows all defined endpoints, bypassing the `modelSpecs` configuration.

### Version Information

```
ghcr.io/danny-avila/librechat-dev                latest    a283dc00e48c   3 days ago    1.61GB
ghcr.io/danny-avila/librechat-rag-api-dev-lite   latest    566585698235   13 days ago   1.8GB
```

### Steps to Reproduce

1. Use `modelSpecs` and hide any enpoint e.g.
```
endpoints:
  agents:
    disableBuilder: false
    recursionLimit: 10
    maxRecursionLimit: 15
    allowedProviders:
    - azureOpenAI
    capabilities: [ "chain" ]

  azureOpenAI:
    titleModel: "gpt-4o-mini"
    titleConvo: true
    assistants: false
    plugins: false
    groups:
    - group: "sweden"
      apiKey: "foo"
      instanceName: "service-ai..."
      version: "2025-01-01-preview"
      models:
        gpt-4o-mini:
          deploymentName: gpt-4o-mini
        gpt-4o:
          deploymentName: gpt-4o

modelSpecs:
  enforce: true
  prioritize: true
  addedEndpoints:
  - agents
  list:
  - name: "gpt-4o-mini"
    label: "GPT-4o mini"
    default: true
    description: "OpenAI's general-purpose model great for everyday tasks."
    showIconInMenu: false
    showIconInHeader: false
    iconURL: "https://url.com/icon.png"
```

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell

```

### Screenshots

<img width="1254" alt="Image" src="https://github.com/user-attachments/assets/7784de1e-7627-4299-8d49-8571fa4beafa" />

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
