### DISCUSSION TITLE
Title not found or method not implemented for the conversation's endpoint

### DISCUSSION THREAD

**Discussion by Adetona** [danny-avila/LibreChat#7017] [Troubleshooting]
### What happened?

Hi,

I kept getting that on this endpoint `/api/convos/gen_title` despite setting up redis. Do I need to setup another thing to make that endpoint work?

```
{
    "message": "Title not found or method not implemented for the conversation's endpoint"
}
```

### Version Information

{
    "message": "Title not found or method not implemented for the conversation's endpoint"
}

### Steps to Reproduce

When creating a new chat.

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell

```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
No, this means the title was likely not generated or timed out.

**Comment by sanjibnarzary** [comment]
I am also getting the same error while using Custom Endpoint
```
XHRPOST
http://localhost:3080/api/convos/gen_title
[HTTP/1.1 404 Not Found 2519ms]

	
POST
	http://localhost:3080/api/convos/gen_title
Status
404
Not Found
VersionHTTP/1.1
Transferred384 B (87 B size)
Referrer Policystrict-origin-when-cross-origin
DNS ResolutionSystem

    	
    Access-Control-Allow-Origin
    	*
    Connection
    	keep-alive
    Content-Length
    	87
    Content-Type
    	application/json; charset=utf-8
    Date
    	Tue, 22 Apr 2025 16:19:15 GMT
    ETag
    	W/"57-EWjnpEcyDc/NcHSjf8p7soqmiYI"
    Keep-Alive
    	timeout=5
    Vary
    	Accept-Encoding
    X-Robots-Tag
    	noindex
    	
    Accept
    	application/json, text/plain, */*
    Accept-Encoding
    	gzip, deflate, br, zstd
    Accept-Language
    	en-US,en;q=0.5
    Authorization
    	Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZTYzZDM2ZDY5NzkwNjZmOWRhMDViMiIsInVzZXJuYW1lIjoiYWxheWFyYW4iLCJwcm92aWRlciI6ImxvY2FsIiwiZW1haWwiOiJhbGF5YXJhbkBnbWFpbC5jb20iLCJpYXQiOjE3NDUzMzg2MTEsImV4cCI6MTc0NTMzOTUxMX0.4GgVEIf1KN4JfRWjh2QTBiUMO77bzuM3-2v9bpXtRNI
    Connection
    	keep-alive
    Content-Length
    	57
    Content-Type
    	application/json
    Cookie
    	refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZTYzZDM2ZDY5NzkwNjZmOWRhMDViMiIsInNlc3Npb25JZCI6IjY4MDYzNTc3MjQ2MmM3ZDY4ZjQxODk4NiIsImlhdCI6MTc0NTMzODYxMSwiZXhwIjoxNzQ1ODQyMTY2fQ.QEWEo8mGyLd0lhm6I0i7JXdBWtFc_vYMotzeP6mD9xc
    DNT
    	1
    Host
    	localhost:3080
    Origin
    	http://localhost:3080
    Referer
    	http://localhost:3080/c/0931f65e-39ca-40f8-ad0a-e71c2ebbea77
    Sec-Fetch-Dest
    	empty
    Sec-Fetch-Mode
    	cors
    Sec-Fetch-Site
    	same-origin
    Sec-GPC
    	1
    User-Agent
    	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:137.0) Gecko/20100101 Firefox/137.0
```

My librechat.yaml

```
 custom:
    - name: 'ollama'
      apiKey: 'No Key'
      baseURL: 'http://localhost:11434/v1'
      models:
        default:
          [
            'llama3.2',
          ]
        fetch: false
      titleConvo: true
      titleModel: "current_model"
      modelDisplayLabel: "Ollama"
```

**Comment by Adetona** [comment]
Yes, this is an issue on custom endpoint. Not sure where it’s coming from

**Reply by MaximilianoGutierrez** [reply]
@danny-avila is there a workaround for this issue? I'm having the same problem with a custom endpoint:

```
modelSpecs:
  list:
    - name: "grok-3-mini"
      label: "xAI | Grok"
      prioritize: false
      showIconInMenu: true
      showIconInHeader: true
      preset:
        endpoint: "xAI-grok-foundry"
        model: "grok-3-mini"
        modelLabel: "Grok 3 Mini"
        greeting: "Asistente Grok mini"
  addedEndpoints:
    - azureOpenAI
    - google
    - anthropic
  endpoints:
      custom:
    - name: "xAI-grok-foundry"
      apiKey: "${AZURE_FOUNDRY_API_KEY}"
      baseURL:  "https://example-resource.services.ai.azure.com/models/"
      models:
        default: ["grok-3-mini"]
        fetch: false
      titleConvo: true
      titleModel: "current_model"
      summarize: true
      summaryModel: "current_model"
      forcePrompt: false
      modelDisplayLabel: "Grok 3 Mini"
```
