### DISCUSSION TITLE
Azure OpenAI o4-mini doesn't work while o3-mini does (release v0.7.7)

### DISCUSSION THREAD

**Discussion by hardware-is-not-software** [danny-avila/LibreChat#7045] [Help Wanted]
Error: Failed to send message. HTTP 400 - Unsupported data type
    at onopen (/app/api/app/clients/ChatGPTClient.js:359:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async create (/app/node_modules/@waylaidwanderer/fetch-event-source/lib/cjs/fetch.cjs:56:17) {
  status: 400
}
{"level":"error","message":"[handleAbortError] AI response error; aborting request: Failed to send message. HTTP 400 - Unsupported data type\n","stack":"Error: Failed to send message. HTTP 400 - Unsupported data type\n\n    at onopen (/app/api/app/clients/ChatGPTClient.js:359:25)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async create (/app/node_modules/@waylaid...","status":400,"timestamp":"2025-04-24T06:26:29.637Z"}

**Comment by danny-avila** [comment]
Updating Instructions (docker):
```bash
# Linux command to Remove all existing images
docker images -a | grep "librechat" | awk '{print $3}' | xargs docker rmi

# Windows Powershell
docker images -a | findstr "librechat" | ForEach-Object { docker rmi $_.Split()[2] }
```

Then follow the directions here: https://www.librechat.ai/docs/local/docker#update-librechat

**Reply by fabsau** [reply]
Did not fix the issue for me.

- **Config version:** `1.2.1`
- **Image version:** `0.7.7` (latest)
- **Problem:** Everything works except for `o4-mini`. Getting the same error as OP.

---

**My config (with hidden secrets):**

```yaml
endpoints:
  azureOpenAI:
    titleConvo: true
    titleModel: "gpt-4.1-nano"
    assistants: false
    plugins: true
    agents:
      recursionLimit: 50
      disableBuilder: false
    groups:
      - group: "Sweden"
        apiKey: "{{ OPENAI_AZURE_API_KEY_1 }}"
        instanceName: "{{ OPENAI_AZURE_INSTANCENAME_1 }}"
        version: "2025-03-01-preview" # latest
        models:
          gpt-4.1:
            deploymentName: "gpt-4.1"
          gpt-4.1-mini:
            deploymentName: "gpt-4.1-mini"
          gpt-4.1-nano:
            deploymentName: "gpt-4.1-nano"
      - group: "Sweden-Reasoning"
        apiKey: "{{ OPENAI_AZURE_API_KEY_1 }}"
        instanceName: "{{ OPENAI_AZURE_INSTANCENAME_1 }}"
        version: "2025-03-01-preview" # latest
        dropParams: ["stream", "temperature", "top_p", "presence_penalty", "frequency_penalty", "best_of", "max_tokens", "stop"]
        models:
          o4-mini:
            deploymentName: "o4-mini"
          o3-mini:
            deploymentName: "o3-mini"
```
---
- Let me know if you need additional logs or config details.
- Happy to test any suggestions!

**Reply by danny-avila** [reply]
It works for me, here's my example azure config

```yaml
endpoints:
  azureOpenAI:
    streamRate: 35
    titleModel: "gpt-4o"
    titleConvo: true
    groups:
    - group: "eastus"
      apiKey: "${EASTUS_API_KEY}"
      instanceName: "example-eastus"
      version: "2024-02-15-preview"
      models:
        gpt-4o:
          deploymentName: gpt-4o
    - group: "region-eastus"
      apiKey: "${EASTUS2_API_KEY}"
      instanceName: "example-eastus2"
      version: "2024-12-01-preview"
      models:
        gpt-4o-latest:
          deploymentName: "gpt-4o-mini"
          version: "2024-02-15-preview"
        o1-mini:
          deploymentName: "o1-mini"
        o1-preview:
          deploymentName: "o1-preview"
        o3-mini:
          deploymentName: "o3-mini"
    - group: "o4-mini"
      apiKey: "${O4_API_KEY}"
      instanceName: "example-eastus2"
      version: "2025-03-01-preview"
      deploymentName: "o4-mini"
      models:
        o4-mini: true
```

### you can use the example they give in your deployment page as a reference for these values

![firefox_PKCHufr4gl](https://github.com/user-attachments/assets/d66a0398-0f6d-40e8-868f-06bffcfe0951)
