### DISCUSSION TITLE
How do I pass in environment variables to mcp server args?

### DISCUSSION THREAD

**Discussion by leblancfg** [danny-avila/LibreChat#7050] [Q&A]
My setup works if I paste the key as-is instead of the templated string, but fails if I have e.g.

```yml
mcpServers:
  my_mcp_server:
    type: stdio
    command: npx
    args: [
      "mcp-remote",
      "https://path/to/url/sse",
      "--header",
      "Authorization: Bearer ${MY_API_KEY}",
    ]
```

or the more explicit

```yml
  my_mcp_server:
    type: stdio
    command: npx
    args: [
      "mcp-remote",
      "https://path/to/url/sse",
      "--header",
      "Authorization: Bearer ${MY_API_KEY}",
    ]
    env:
      MY_API_KEY: "${MY_API_KEY}"
```

How do I pass in an env var in this context?
