### DISCUSSION TITLE
[Enhancement]: Can I configure each Agent in `librechat.yml` instead of in the frontend UI

### DISCUSSION THREAD

**Discussion by harrisonhxy** [danny-avila/LibreChat#7056] [Q&A]
### What features would you like to see added?

Configuring Agents in the front-end UI is a bit cumbersome to do, and I was wondering if I could configure each Agent I want to create directly using a configuration file, say like **custom endpoint** in `librechat.yml`.

Because I've looked a lot in issue, as well as looking up the documentation, and I can't find out exactly where the image of the Agent avatar uploaded on my front end is stored to 😖

### More details

  ```yml
agents:
    recursionLimit: 25
    maxRecursionLimit: 50
    disableBuilder: false 
    capabilities:
      - "execute_code"
      - "file_search"
      - "actions" 
      # - "tools" 
      - "artifacts"
      - "ocr"
      - "chain"
``` 

These current configurations for Agents in `librechat.yml` are supposed to be for all Agents (if I understand correctly.) It would be great to be able to be specific about operating each Agent!

Another small question, can I control Agent permissions in the config file, **e.g.** for **normal users** I only allow them to use and share Agents, not to create them, and for **admin**, always have all permissions

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
