### DISCUSSION TITLE
MCP servers enabled but not seeing it in UI

### DISCUSSION THREAD

**Discussion by AngusHsu-cubewise** [danny-avila/LibreChat#7067] [Troubleshooting]
I've set up mcpServers in librechat.yml, and the log shows it has initialized, but the `server` doesn't show up in the UI. Is there any additional configuration I need to modify to make the mcpServer appear in the UI?

librechat.yml
```
mcpServers:
  server:
    command: npx
    args:
      - "@modelcontextprotocol/server-memory"
```

logs:
```
4f753562f8cb 2025-04-25 07:17:38 info: [MCP] Initialized 1/1 app-level server(s)
4f753562f8cb 2025-04-25 07:17:38 info: [MCP][memory] ✓ Initialized
4f753562f8cb 2025-04-25 07:17:38 info: [MCP] All app-level servers initialized successfully
```

**Comment by danny-avila** [comment]
Make sure you update, then you will see it in the chatarea.

![chrome_nFLxanbXFB](https://github.com/user-attachments/assets/90b112b3-6056-49ec-b94d-70b8b69bc0be)


Otherwise, you can use it with Agents:
https://www.librechat.ai/docs/features/agents#model-context-protocol-mcp

---


Updating Instructions (docker):
```bash
# Linux command to Remove all existing images
docker images -a | grep "librechat" | awk '{print $3}' | xargs docker rmi

# Windows Powershell
docker images -a | findstr "librechat" | ForEach-Object { docker rmi $_.Split()[2] }
```

Then follow the directions here: https://www.librechat.ai/docs/local/docker#update-librechat

**Reply by dingfengshaoDD** [reply]
Hi Danny! We love the MCP integration! 
Just want to ask: if we decide to use the agent, is there a way to disable the "MCP servers" drop down menu? 
for now, looks like the drop down menu will always be there even if I only use it for agents.

**Reply by danny-avila** [reply]
Awesome, that is a practical use case. I will add a configuration option before the next release, since this is a new interface item, ETA due in a week's time. I'll be releasing a release candidate over the next 2 days, possibly today.

**Reply by dingfengshaoDD** [reply]
Thanks for the quick response!

**Reply by dingfengshaoDD** [reply]
Hi Danny! Do you have an issue/PR to track this? just want to follow up on this. Thanks!

**Reply by todiadiyatmo** [reply]
I've the same issue
MCP already installed as log :
```
2025-05-04 04:19:50 info: [MCP][ddg-search] Available tools: search, fetch_content
2025-05-04 04:19:50 info: [MCP] Initialized 2/2 app-level server(s)
2025-05-04 04:19:50 info: [MCP][server] ✓ Initialized
2025-05-04 04:19:50 info: [MCP][ddg-search] ✓ Initialized
2025-05-04 04:19:50 info: [MCP] All app-level servers initialized successfully
```
docker  images  also has the ltest
But mcp drop down not found

**Reply by danny-avila** [reply]
@dingfengshaoDD no but I will work on it between today or Tuesday

@todiadiyatmo you should update your instance.

To update, follow the directions here: https://www.librechat.ai/docs/local/docker#update-librechat

**Reply by todiadiyatmo** [reply]
@danny-avila i have update my instance also use the latest 0.7.8-rc-1 but unfortunately not show up. I'am using custom endpoint with litellm backend, is there anything need to be set up for my endpoint or maybe modelspecs ?

**Reply by todiadiyatmo** [reply]
i found the problem ! 

```
ENDPOINTS=groq,OpenRouter
```

I set endpoints with this value on .env, commenting it out make the mcp toggle show up

**Reply by yohannj** [reply]
Thanks @todiadiyatmo , I was able to investigate further thanks to you.
You need to include `agents` inside ENDPOINTS for mcp servers to show up.

So in your case, `ENDPOINTS=groq,OpenRouter,agents` should do the trick.
I suppose it would help to add this value inside .env.example, so that it's easier to find. Potentially with it's own comment because "agents" doesn't feel obvious either.

**Reply by keskinberkem** [reply]
@yohannj Thanks for your solution. I want to remove agent builder from ui, however when I set agents to false in interface field, also mcp servers are disappearing. Is there a way to keep only mcp and remove agent builder ? Thanks.

**Reply by danny-avila** [reply]
https://www.librechat.ai/docs/configuration/librechat_yaml/object_structure/agents#disablebuilder

**Reply by kshitijg30** [reply]
Hi, i tried adding agents inside the ENDPOINTS, still i cant see the MCP Server in ui.
![image](https://github.com/user-attachments/assets/edda78cb-10b0-478b-9c9e-f0667e2cf277)
ENDPOINTS=openAI,agents,assistants,gptPlugins,azureOpenAI,google,anthropic

**Reply by MaLub** [reply]
@light23-i 
make sure that your MCP-Servers are connected without any errors.

```docker logs LibreChat```

In my case there were an error and so no mcp-server will be shown (what is correct)
```
2025-05-25 10:15:03 error: [MCP][filesystem] Connection failed: MCP error -32000: Connection closed
2025-05-25 10:15:03 error: [MCP][filesystem] Failed to connect after 3 attempts MCP error -32000: Connection closed
2025-05-25 10:15:03 error: [MCP][filesystem] Initialization failed MCP error -32000: Connection closed
2025-05-25 10:15:03 info: [MCP] Initialized 0/1 app-level server(s)
2025-05-25 10:15:03 warn: [MCP] 1/1 app-level server(s) failed to initialize
2025-05-25 10:15:03 info: [MCP][filesystem] ✗ Failed
```

**Comment by estone81** [comment]
In your librechat.yaml file you need to also turn on the agents endpoints. 

# Definition of custom endpoints
endpoints:
  #assistants:
  #   disableBuilder: false # Disable Assistants Builder Interface by setting to `true`
  #   pollIntervalMs: 3000  # Polling interval for checking assistant updates
  #   timeoutMs: 180000  # Timeout for assistant operations
  #   # Should only be one or the other, either `supportedIds` or `excludedIds`
  #   supportedIds: ["asst_supportedAssistantId1", "asst_supportedAssistantId2"]
  #   # excludedIds: ["asst_excludedAssistantId"]
  #   Only show assistants that the user created or that were created externally (e.g. in Assistants playground).
  #   # privateAssistants: false # Does not work with `supportedIds` or `excludedIds`
  #   # (optional) Models that support retrieval, will default to latest known OpenAI models that support the feature
  #   retrievalModels: ["gpt-4-turbo-preview"]
  #   # (optional) Assistant Capabilities available to all users. Omit the ones you wish to exclude. Defaults to list below.
  #    capabilities: ["code_interpreter", "retrieval", "actions", "tools", "image_vision"]
  agents:
  #   # (optional) Default recursion depth for agents, defaults to 25
  #   recursionLimit: 50
  #   # (optional) Max recursion depth for agents, defaults to 25
  #   maxRecursionLimit: 100
  #   # (optional) Disable the builder interface for agents
  #   disableBuilder: false
  #   # (optional) Agent Capabilities available to all users. Omit the ones you wish to exclude. Defaults to list below.
    capabilities: ["execute_code", "file_search", "actions", "tools"]

**Comment by torcato** [comment]
I am having the same problem.
I have set in the .env file:
```
ENDPOINTS=openAI,agents,assistants,gptPlugins,azureOpenAI,google,anthropic
```
my librechat.yaml
```yaml
# For more information, see the Configuration Guide:
# https://www.librechat.ai/docs/configuration/librechat_yaml

# Configuration version (required)
version: 1.2.1

# Cache settings: Set to true to enable caching
cache: true

# File strategy s3/firebase
# fileStrategy: "s3"


# Example MCP Servers Object Structure
mcpServers:
  raw-oxial:
    type: sse
    url: http://172.17.0.1:8000/sse
    timeout: 30000  


# Definition of custom endpoints
endpoints:
  assistants:
    disableBuilder: false # Disable Assistants Builder Interface by setting to `true`
    pollIntervalMs: 3000  # Polling interval for checking assistant updates
    timeoutMs: 180000  # Timeout for assistant operations
    # Should only be one or the other, either `supportedIds` or `excludedIds`
    supportedIds: ["asst_supportedAssistantId1", "asst_supportedAssistantId2"]
    # excludedIds: ["asst_excludedAssistantId"]
    # Only show assistants that the user created or that were created externally (e.g. in Assistants playground).
    # privateAssistants: false # Does not work with `supportedIds` or `excludedIds`
    # (optional) Models that support retrieval, will default to latest known OpenAI models that support the feature
    retrievalModels: ["gpt-4-turbo-preview"]
    # (optional) Assistant Capabilities available to all users. Omit the ones you wish to exclude. Defaults to list below.
    capabilities: ["code_interpreter", "retrieval", "actions", "tools", "image_vision"]
  agents:
    # (optional) Default recursion depth for agents, defaults to 25
    recursionLimit: 50
    # (optional) Max recursion depth for agents, defaults to 25
    maxRecursionLimit: 100
    # (optional) Disable the builder interface for agents
    disableBuilder: false
    # (optional) Agent Capabilities available to all users. Omit the ones you wish to exclude. Defaults to list below.
    capabilities: ["execute_code", "file_search", "actions", "tools"]
  custom:
    - name: "ollama"
      apiKey: ollama
      # use 'host.docker.internal' instead of localhost if running LibreChat in a docker container
      baseURL: "http://172.17.0.1:11434" 
      models:
        default: [
            "qwen3:32b",
            "qwen3:30b",
            "qwen2.5-coder:32b",
            "qwq:latest",
            "deepseek-r1:70b",
            "deepseek-r1:32b",
            "codestral:latest",
            "mistral-small:latest",
            "qwen:32b",
            "deepseek-v2:16b",
            "deepseek-coder:33b"
          ]
        # fetching list of models is supported but the `name` field must start
        # with `ollama` (case-insensitive), as it does in this example.
        fetch: true
 ```
 I can see that the mcp server was initialized without errors:
 
 ```
 LibreChat         | 2025-06-05 14:07:53 info: RAG API is running and reachable at http://rag_api:8000.
LibreChat         | 2025-06-05 14:07:53 info: [MCP] Initializing app-level servers
LibreChat         | 2025-06-05 14:07:53 info: [MCP][raw-oxial] Creating SSE transport: http://172.17.0.1:8000/sse
LibreChat         | 2025-06-05 14:07:53 info: [MCP][raw-oxial] Capabilities: {"experimental":{},"prompts":{"listChanged":false},"resources":{"subscribe":false,"listChanged":false},"tools":{"listChanged":false}}
LibreChat         | 2025-06-05 14:07:53 info: [MCP] Initialized 1/1 app-level server(s)
LibreChat         | 2025-06-05 14:07:53 info: [MCP][raw-oxial] ✓ Initialized
LibreChat         | 2025-06-05 14:07:53 info: [MCP] All app-level servers initialized successfully
```
Am I doing something wrong ?

**Reply by torcato** [reply]
Ok, my mcp server had a bug and did not have any tools.
Sorry for the spam

**Comment by hinewin** [comment]
Im getting a different issue where I'm getting a `Access token missing` from my MCP server connection
https://github.com/danny-avila/LibreChat/discussions/8594

**Comment by thisismydesign** [comment]
On a fresh checkout I needed to:

`cp librechat.example.yaml librechat.yaml`

And mount `librechat.yaml` config in docker

`docker-compose.yml`
```yml
services:
  api:
    volumes:
      - type: bind
        source: ./librechat.yaml
        target: /app/librechat.yaml
```
