### DISCUSSION TITLE
'Agent Not Found' Error

### DISCUSSION THREAD

**Discussion by Ria-c3alabs** [danny-avila/LibreChat#7090] [Troubleshooting]
### What happened?

When attempting to use custom contract agents configured in librechat.yaml, the system consistently returns an "Agent not found" error. The error appears in the UI as "An error occurred while processing your request. Please contact the Admin." In the logs, it shows "error: [handleAbortError] AI response error; aborting request: Agent not found".

# Environment Details
LibreChat Version: Latest (as of April 2025)
Deployment Method: Docker
Configuration Method: Using librechat.yaml for agent definitions
Provider: OpenAI
Browser: Chrome (latest)

# Error Messages

```
LibreChat | 2025-04-26 12:37:59 error: [handleAbortError] AI response error; aborting request: Agent not found
LibreChat | 2025-04-26 12:37:59 warn: Invalid conversation ID: undefined
LibreChat | 2025-04-26 12:37:59 info: ---`saveMessage` context: undefined
LibreChat | 2025-04-26 12:37:59 info: ---Invalid conversation ID Params: {
LibreChat |   "messageId": "d4429f7a-9c5a-478c-9442-f33f18427115",
LibreChat |   "parentMessageId": "00000000-0000-0000-0000-000000000000",
LibreChat |   "unfinished": false,
LibreChat |   "error": true,
LibreChat |   "final": true,
LibreChat |   "text": "An error occurred while processing your request. Please contact the Admin.",
LibreChat |   "isCreatedByUser": false,
LibreChat |   "spec": "contract-search-agent",
LibreChat |   "iconURL": "https://cdn.iconscout.com/icon/premium/png-256-thumb/contract-8597389-6953248.png",
LibreChat |   "agent_id": "contract_search_agent",
LibreChat |   "user": "680cc75d0da1a0c630ec1846"
LibreChat | }
```

# Librechat.yaml config:

- added modelSpecs:
```
modelSpecs:
  enforce: true
  prioritize: true
  list:
    - name: "contract-search-agent"
      label: "Contract Search Assistant"
      default: true
      description: "Specialized agent for searching and analyzing contracts"
      iconURL: "https://cdn.iconscout.com/icon/premium/png-256-thumb/contract-8597389-6953248.png"
      showIconInMenu: true
      showIconInHeader: true
      preset:
        endpoint: "agents"
        agent_id: "contract_search_agent"  # Add "agent:" prefix here

    - name: "contract-generator-agent"
      label: "Contract Generator"
      description: "Specialized agent for generating legal contracts"
      iconURL: "https://cdn.iconscout.com/icon/premium/png-256-thumb/contract-11759188-9601742.png"
      showIconInMenu: true
      showIconInHeader: true
      preset:
        endpoint: "agents"
        agent_id: "contract_generator_agent"
```

- interface config:
```
endpointsMenu: true
  modelSelect: true
  parameters: true
  sidePanel: false
  presets: true
  prompts: true
  bookmarks: true
  multiConvo: true
  agents: true
  showAgentIcons: true
  showModelIcons: true
  agentsMenu: true
  showAgentsInModelSelect: true
  agentBuilder: true
```

- endpoint config:
```
agents:
    enabled: true
    defaults:
      - id: "contract_search_agent"
        name: "Contract Search Assistant"
        allowedProviders: ["openai"]
        description: "Specialized agent for searching and analyzing contracts"
        instructions: |
          You are a specialized Contract Search and Analysis agent with expertise in legal document analysis. Your purpose is to help users search, analyze, and extract information from contracts with precision and accuracy.
        provider: "openai"
        model: "gpt-3.5-turbo"
        model_parameters:
          temperature: 0.2
          top_p: 1
        tools: ["file_search"]
        capabilities: ["file_search", "tools"]

      - id: "contract_generator_agent"
        name: "Contract Generator"
        allowedProviders: ["openai"]
        description: "Specialized agent for generating legal contracts"
        instructions: |
          You are a specialized Contract Generation agent with expertise in legal document creation. Your purpose is to help users create new contracts based on their specific requirements and past contract templates.
        provider: "openai"
        model: "gpt-3.5-turbo"
        model_parameters:
          temperature: 0.5
          top_p: 1
        tools: ["file_search"]
        capabilities: ["file_search", "tools"]
```

Kindly resolve this. 

### Version Information

ghcr.io/danny-avila/librechat-dev                latest    74b3b760963f   9 hours ago     1.62GB
ghcr.io/danny-avila/librechat-rag-api-dev-lite   latest    566585698235   2 weeks ago     1.85GB

### Steps to Reproduce

1. Configure custom agents in librechat.yaml as described above
2. Restart LibreChat using docker
3. Select one of the custom agents from the model selection dropdown
4. Enter a prompt and submit
5. Observe the "Agent not found" error

### Relevant log output

```shell
LibreChat | 2025-04-26 12:37:59 error: [handleAbortError] AI response error; aborting request: Agent not found
LibreChat | 2025-04-26 12:37:59 warn: Invalid conversation ID: undefined
LibreChat | 2025-04-26 12:37:59 info: ---`saveMessage` context: undefined
LibreChat | 2025-04-26 12:37:59 info: ---Invalid conversation ID Params: {
LibreChat |   "messageId": "d4429f7a-9c5a-478c-9442-f33f18427115",
LibreChat |   "parentMessageId": "00000000-0000-0000-0000-000000000000",
LibreChat |   "unfinished": false,
LibreChat |   "error": true,
LibreChat |   "final": true,
LibreChat |   "text": "An error occurred while processing your request. Please contact the Admin.",
LibreChat |   "isCreatedByUser": false,
LibreChat |   "spec": "contract-search-agent",
LibreChat |   "iconURL": "https://cdn.iconscout.com/icon/premium/png-256-thumb/contract-8597389-6953248.png",
LibreChat |   "agent_id": "contract_search_agent",
LibreChat |   "user": "680cc75d0da1a0c630ec1846"
LibreChat | }
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Are you using the actual agent ID below the name?

**Reply by Ria-c3alabs** [reply]
Yes, both the agent_ids here are correctly set in modelSpecs and also match the ID in my agent definition.

**Reply by danny-avila** [reply]
There are some issues with your config. Sadly I’m on my phone and can’t run it through an AI but I would ask you to review the documentation for both agents and model specs.

https://www.librechat.ai/docs/configuration/librechat_yaml/object_structure/agents

https://www.librechat.ai/docs/configuration/librechat_yaml/object_structure/model_specs

**Reply by Ria-c3alabs** [reply]
@danny-avila I reviewed the entire docs, and I am still unable to find the issue. I have also added allowedProviders key but still the same issue. Can you please guide me through the issue?

**Reply by Ria-c3alabs** [reply]
@danny-avila, kindly help me with this, as I have been stuck for a long time now.

**Reply by danny-avila** [reply]
First, the options you specified for the agents config don't even exist, so that could be creating issues. Reviewing the documentation would show this to you.

Here's the relevant parts of my `librechat.yaml` for you to use as a reference:
```yaml
endpoints:
  agents:
    disableBuilder: false
interface:
  agents: true
  prompts: true
  parameters: true
  presets: true
  runCode: true
  modelSelect: false
  bookmarks: true
  multiConvo: true
modelSpecs:
  enforce: false
  prioritize: true
  list:
    - name: "Claude Coder"
      label: "Claude Coder"
      iconURL: https://cdn1.cloud.e-infra.cz/logos/meta-llama.png
      preset:
        endpoint: "agents"
        agent_id: "agent_someAgentId"
```
### No issues
![chrome_3Vbzs28DvJ](https://github.com/user-attachments/assets/df21a61f-bf2a-4679-b8b9-6fe55521616a)

**Comment by iamronr** [comment]
I'm getting the same error. I'm trying to use Qwen 3 and add Google search via the agent.

modelSpecs
```
list:
    - name: "Qwen3 Agent"
      label: "Qwen3-8B-Q8 Agent"
      default: false
      description: "Qwen3 w/Google Search"
      iconURL: "https://huggingface.co/spaces/Qwen/Qwen3-Demo/resolve/500a858287c9d594643270b80f1e28f6e9b89c9c/assets/qwen.png"
      preset:
        endpoint: "agents"
        agent_id: "qwen3agent"
```

agents
```
enabled: true
    defaults:
      - id: "qwen3agent"
        name: "Qwen3 Agent"
        allowedProviders: ["google"]
        description: "Qwen3 with Google Search access"
        instructions: |
        provider: "Ollama - rGPT"
        model: "hf.co/unsloth/Qwen3-8B-GGUF:Q8_0"
        model_parameters:
          temperature: 0.2
          top_p: 1
        tools: ["tools"]
        capabilities: ["tools"]
```

Not sure what I'm missing...
