### DISCUSSION TITLE
[Enhancement]: n8n Agent Support

### DISCUSSION THREAD

**Discussion by dpnmw** [danny-avila/LibreChat#7116] [Feature Requests & Suggestions]
### What features would you like to see added?

Hi, I'm looking into using my n8n to create custom responses to users that use the chat, I don't need the api models that are listed and not looking into training my own model, but provide a support chat for customers.

The issue i've seen is that my n8n webhooks are not OpenAI APIs.
I want to send raw messages, and get raw answers — not OpenAI chat completions.

Thus, using the Custom Endpoint system as-is won't work cleanly for my use case scenario.

I've modified the messages.js

`const webhookMap = {
  sales: process.env.N8N_WEBHOOK_SALES,
  support: process.env.N8N_WEBHOOK_SUPPORT,
  hr: process.env.N8N_WEBHOOK_HR,
};

const defaultWebhook = process.env.N8N_WEBHOOK_SUPPORT;

router.post('/:conversationId', validateMessageReq, async (req, res) => {
  try {
    const { conversationId } = req.params;
    const { text, selectedWebhook = 'support' } = req.body;

    const targetWebhook = webhookMap[selectedWebhook] || defaultWebhook;

    if (!targetWebhook) {
      return res.status(500).json({ error: 'No webhook configured.' });
    }

    const response = await fetch(targetWebhook, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        message: text,
        conversationId,
        user: req.user.id,
      }),
    });

    if (!response.ok) {
      throw new Error(`Webhook error: ${response.status}`);
    }

    const data = await response.json();

    if (!data.reply) {
      throw new Error('Invalid webhook response: missing "reply" field.');
    }

    res.status(201).json({
      conversationId,
      reply: data.reply,
    });
  } catch (error) {
    console.error('Error sending to webhook:', error);
    res.status(500).json({ error: 'Failed to process webhook message.' });
  }
});
`
and added the following to my .env
`# ==============================
#       N8N Webhook URLs
# ==============================

N8N_WEBHOOK_SALES=https://n8n.tld.com/webhook/sales
N8N_WEBHOOK_SUPPORT=https://n8n.tld.com/webhook/support
N8N_WEBHOOK_HR=https://n8n.tld.com/webhook/hr
`

Doesn't seem to work, so want to know where did I go wrong? Is there another way I could achieve my goal without editing the messages.js? 

### More details

I'm using LibreChat in docker and I used docker-compose up --build after making my edits.

### Which components are impacted by your request?

General

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by oxeone** [comment]
Hi

I tried this in multiple ways.
You at least need directEndpoint: false, forcePrompt: true, stream: false in your custom endpoint to get a non streaming webhook response.

I can get a valid response that is empty, but had to do horrible hacks in baseclient.js to get the message through that was not sustainable for me.

I ended up making a tool instead:
[Librechat Docu](https://www.librechat.ai/docs/development/tools_and_plugins)
Just copy the TraversaalSearch plugin and match the return format in N8N

Might not fit you use case, but you can make an agents with instructions that uses the tool like an MCP.

**Comment by dpnmw** [comment]
Thanks for your response @oxeone I got it to work with the custom endpoints :

```
endpoints:
  custom:
    - name: 'n8n-chat'
      apiKey: '${N8N_CHAT_KEY}'
      baseURL: 'https://tld.com/webhook/v1/chat/completions'
      models:
        default: ['n8n-chat']
        fetch: false
      addParams:
        session_id: "{{user._id}}"   # << This sends the user ID to n8n
        user_email: "{{user.email}}" # Optional for better logging
        stream: false
      titleConvo: true
      titleModel: 'n8n-chat'
      modelDisplayLabel: 'n8n-chat'
```
Had to use addParams to set session id and stream to false 

In the .env 
`N8N_CHAT_KEY=**********`

In the webhook set authentication to "Header Auth" with credentials of Authorization: Bearer (N8N_CHAT_KEY Values from .env)

In the primary ai agent User message set as : 

`{{ $json.body.messages[$json.body.messages.length - 1].content || "Hi" }}
`

Had to create an n8n "code" (run once for all items) before webhook response

```
return {
  json: {
    id: "chatcmpl-n8n-" + $executionId,
    object: "chat.completion",
    created: Math.floor(Date.now() / 1000),
    model: "n8n-chat",
    choices: [
      {
        index: 0,
        message: {
          role: "assistant",
          content: $json.output || $json.text || "I'm not sure how to respond."
        },
        finish_reason: "stop"
      }
    ]
  }
};
```

And it works, my initial goal is complete, will now move onto creating the secondary implementations.

**Reply by maxesse** [reply]
This worked great for me - just wanted to ask, how do you populate {{session_id}}? Did you have to change librechat's code to pass it over? Because for me it sends literally {{session_id}} to n8n.

**Reply by dpnmw** [reply]
Hi, that was a placeholder, librechat doesn't expose session_id for logged in users, I made a change to this as:

`addParams:
        session_id: "{{user._id}}"    
        user_email: "{{user.email}}" `
<br>
You should get an output in n8n json as :
`{
  "session_id": "6639c1fd2a...",
  "user_email": "john@example.com",`

**Reply by maxesse** [reply]
Thank you - I did a change to Librechat to send its own session, but then I realised the whole thing was superfluous and I could simply manipulate the chat history that gets sent with every single request from Librechat, so the session wasn't even needed. 

I added a set node that extracts body.messages from the initial webhook, and then a code node that puts all the messages into a single prompt to give to the ai agent afterwards:

```
const messages = $input.first().json.body.messages

let text = `Here's the conversation so far:\n\n`;
for (let i = 0; i < messages.length - 1; i++) {
  const m = messages[i];
  const speaker = m.role === 'user' ? 'User' : 'Assistant';
  text += `${speaker}: ${m.content}\n\n`;
}

const last = messages[messages.length - 1];
const lastSpeaker = last.role === 'user' ? 'User' : 'Assistant';
text += `Here's the current prompt:\n\n${lastSpeaker}: ${last.content}`;

return [
  {
    json: {
      conversation: text
    }
  }
];
```

**Reply by dpnmw** [reply]
Okay, great to know you found a solution. I've moved away from librechat for now. As I'm focusing on a mobile application to handle my needs.

**Comment by devgauchocode** [comment]
Hi @dpnmw !

I wanted to let you know that I tried the exact configuration you described, including the directEndpoint: false, forcePrompt: true, and stream: false settings. Here's my current librechat.yaml config:

```
custom:
  - name: 'n8n-chat'
    apiKey: '${N8N_CHAT_KEY}'
    baseURL: 'https://test.n8n.com/webhook/c72f31c4-ee69-411a-935c-57d28797fc31'
    models:
      default: ['n8n-chat']
      fetch: false
    addParams:
      stream: false
    headers:
      Content-Type: "application/json"
      Authorization: "Bearer ${N8N_CHAT_KEY}"
    directEndpoint: false
    forcePrompt: true
    titleConvo: true
    titleModel: 'n8n-chat'
    modelDisplayLabel: 'n8n-chat'
```

I have the ${N8N_CHAT_KEY} properly set in my .env file.

The model does show up in the LibreChat UI, but when I try sending a message, I get this error:

_Something went wrong. Here's the specific error message we encountered: An error occurred while processing your request. Please contact the Admin._

I also tested the same webhook using curl, and it works fine:

```
curl -X POST https://test.n8n.com/webhook/c72f31c4-ee69-411a-935c-57d28797fc31 \
  -H 'Content-Type: application/json' \
  -H 'Authorization: Bearer <my_key>' \
  -d '{"messages":[{"role":"user","content":"Hello"}]}'
```


This returns a valid JSON response in the expected chat.completion format.

However, LibreChat never seems to actually send the request — the webhook workflow in n8n is never triggered and no incoming request is logged.

Is there anything else I could check? Maybe a way to enable more verbose logging from LibreChat? Or could something internal be silently blocking the request?
