### DISCUSSION TITLE
[Enhancement]: Customize Parameters for Custom Endpoints

### DISCUSSION THREAD

**Discussion by danny-avila** [danny-avila/LibreChat#7185] [Feature Requests & Suggestions]
### What features would you like to see added?

Custom parameters for custom endpoints via librechat.yaml configuration, using existing parameters from other providers or brand new, dynamic ones

### More details

See #6503, #7179, #7180 

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by mawburn** [comment]
@danny-avila is this meant to be suggested default settings or overrides?

The linked PR changes the way model specs work and don't seem to be related?

**Comment by nhtruong** [comment]
I'd like to take a crack at this.

**Comment by danny-avila** [comment]
@nhtruong thanks!

@mawburn there's a long discussion in the linked PR and this is the relevant comment: https://github.com/danny-avila/LibreChat/pull/6503#pullrequestreview-2808055514

This is not related to default settings or overrides, this would change what parameters appear and the user can choose from for custom endpoints:

![Image](https://github.com/user-attachments/assets/6715c4d3-f68b-4a98-8eb3-3af79d458cf3)

**Comment by mawburn** [comment]
@danny-avila 

> This is not related to default settings or overrides, this would change what parameters appear and the user can choose from for custom endpoints:

Ok, but I don't think those are the same thing that @nhtruong created in his tickets, we are on the same team and were discussing this on Slack. We are looking for default parameters to be set per model or just globally for the project. Mostly things like Temp, because 1.0 temp is not a good setting to be default. 

I can see if this is rolled into what parameters are seen too, but they seem like separate concerns to me because default parameters should also apply to OpenAI endpoints.

**Comment by nhtruong** [comment]
For clarification, my original issue attempts to add something like this in the `librechat.yaml` for custom endpoints:
```yaml
    - name: 'Cohere'
      ...
      addParams:
        temperature:
          - min_range: 0.2
          - max_range: 0.7
          - default: 0.6
          - step: 0.1
        top_p: 0.5
```
That setting will enforce the range for temperature when the user updates this parameter for Cohere or Cohere agents. The goal is allowing the admin to limit the range of this value but still give the user some wiggle room instead of a single overriden value.

**Comment by danny-avila** [comment]
I moved this to discussions since some clarification is needed. I think we're saying the same thing more or less, since customization of the parameters can limit the parameters and set defaults. 

I understand this as "parameter customization" or "dynamic parameters." All the mentioned refs fall into this one way or another: https://github.com/danny-avila/LibreChat/pull/6503, https://github.com/danny-avila/LibreChat/issues/7179, https://github.com/danny-avila/LibreChat/issues/7180

I guess we can make some distinctions though:
A. Customize/set-defaults for existing parameters
B. introduce new, dynamic parameters unknown to LC
C. include parameters from other providers

I think the thing you want to tackle is A and then I can move on to B, C, since they would involve similar changes.

I have a branch where I started on all 3, including something very similar to what @nhtruong is suggesting, but not via `addParams`. I think we should leave that alone although it's functionally similar. It's more of a "parameter guard" before the API call than a way to influence the full stack.

I will update that branch and push it up soon.

**Comment by nhtruong** [comment]
Thanks @danny-avila 
Should I still work on this feature to add custom range for existing parameters?  (i.e. part A) since your new branch is gonna cover that as well? I'd rather not step on your foot if you're already working on it but I'd love to take that off of your plate if you haven't really started yet.

**Comment by danny-avila** [comment]
No worries @nhtruong, I just realized I had already merged most of the changes I made. Please feel free to take over. I'm going to share some code that is hopefully valuable to get you started.

---

Basically we can customize any of the parameters, both the UI and the backend, by making use of `SettingDefinition` I already made:
https://github.com/danny-avila/LibreChat/blob/5efad8f646a8efb7c010e85f355d9ac88b823048/packages/data-provider/src/generate.ts#L52-L82

This structure is already being used for what we see in the UI now:

https://github.com/danny-avila/LibreChat/blob/5efad8f646a8efb7c010e85f355d9ac88b823048/client/src/components/SidePanel/Parameters/settings.ts#L10-L13

Our custom config would have to be transmitted to the client to make use of it in:
https://github.com/danny-avila/LibreChat/blob/main/client/src/components/SidePanel/Parameters/Panel.tsx

There are 2 helper functions I already made, feel free to improve/adjust as needed.

For validating the "SettingDefinition":
https://github.com/danny-avila/LibreChat/blob/5efad8f646a8efb7c010e85f355d9ac88b823048/packages/data-provider/src/generate.ts#L214

For dynamic zod schema generation:
https://github.com/danny-avila/LibreChat/blob/5efad8f646a8efb7c010e85f355d9ac88b823048/packages/data-provider/src/generate.ts#L104

The zod schemas are used to parse model parameters throughout the app. I tried to centralize this through the following functions:

https://github.com/danny-avila/LibreChat/blob/5efad8f646a8efb7c010e85f355d9ac88b823048/packages/data-provider/src/parsers.ts#L163

https://github.com/danny-avila/LibreChat/blob/5efad8f646a8efb7c010e85f355d9ac88b823048/packages/data-provider/src/parsers.ts#L331


There may be a few places where the "endpoint schemas" are used individually, but it would just be a matter of cross-referencing the following:

https://github.com/danny-avila/LibreChat/blob/5efad8f646a8efb7c010e85f355d9ac88b823048/packages/data-provider/src/parsers.ts#L24-L46

**Reply by nhtruong** [reply]
Great and thanks for the tips.

**Comment by jameslamine** [comment]
Thanks Danny and @nhtruong for tackling this! Really looking forward to this, especially B and C

**Reply by nhtruong** [reply]
What I'm working on will handle B/C too. Aiming to have some draft PR sometime next week.

**Comment by dlouzan** [comment]
I've just stumbled upon this discussion while trying to add configuration for the following use case:

- We have a custom enterprise endpoint, over which we offer multiple different models such as deepseek, mistral, qwq, etc
- I was trying to setup "startup defaults" per each of these models while at the same time allowing users to modify them at their leisure after the fact
- The idea is that a user selects a dropdown model, and gets by default the admin-selected values
- For instance, deepseek suggests using a default 0.5 to 0.7 temperature, perhaps we wanted to set specific max tokens for some models, others recommend not using a system prompt, and so on.

As I understand it, with the existing configuration options, and even with the approach currently being discussed here, we'd need to create individual duplicated endpoint entries for each model default parameters that I wanted to configure right? That's probably not optimal but I guess it'd work, with several hiccups, e.g. we'd get menu entries for each duplicate endpoint, perhaps request tracking, api keys are not correctly tracked/duplicated in request tracking, etc.

Thanks for any feedback!

**Comment by nhtruong** [comment]
Here's the progress update:

If you add the following entry to `endpoints.custom` in `librechat.yaml`:
```yaml
    - name: 'Google my Google'
      apiKey: ...
      baseURL: ...
      models:
        default:
          [
            'googlevertexai-us-central1:gemini-2.5-pro-preview-03-25',
            'googlevertexai-us-central1:gemini-2.5-pro-exp-03-25',
            'googlevertexai-us-central1:gemini-2.5-flash-preview-04-17',
          ]
        fetch: false
      titleConvo: true
      titleModel: 'gpt-3.5-turbo'
      summarize: false
      modelDisplayLabel: 'Gemini'
      customParams:
        includeDefaultParams: [temperature]
        paramDefinitions:
          - key: atmospheric_pressure
            type: number
            component: slider
            range:
              min: 0
              max: 0.7
              step: 0.1
            optionType: custom
            default: 0.5
            columnSpan: 4
          - key: agent_name
            type: string
            component: input
            default: ''
            optionType: custom
            columnSpan: 2
          - key: agent_code
            type: string
            component: input
            default: ''
            optionType: custom
            columnSpan: 2
```
the following parameters will be populated when editing an agent:
![Screenshot 2025-05-05 at 11 44 58 AM](https://github.com/user-attachments/assets/c467ef82-e17b-43f2-a338-7d5bbd33ef7e)
 This also validates `includeDefaultParams` (boolean or an array of default param keys) and the properties of `paramDefinitions`.
 
 There's still a lot of work left:
 - [x] Persisting custom param values for agents
 - [ ] Retrieving and applying these values when sending a prompt to an endpoint.
 - [ ] Apply all of this to the Parameters section (as opposed to Agent Parameters)
 
Here's the WIP Draft: https://github.com/danny-avila/LibreChat/pull/7225

**Reply by danny-avila** [reply]
looks great, thank you!

**Reply by nhtruong** [reply]
So, I managed to persist the custom `agent.model_parameters` on mongoDB. However I'm having trouble pinpointing where these parameters are retrieved and applied when you ask an agent a question. I traced it down to `AgentController` but the `model_parameters` that this controller receives is just a blank object `{}`. Any pointer is greatly appreciated.

**Reply by danny-avila** [reply]
Agent parameters are processed in a few places.


Function to load agent:
https://github.com/danny-avila/LibreChat/blob/3606349a0f1c9ad2242e3c1ea15e09181374f407/api/models/Agent.js#L91

Agent initialization:
https://github.com/danny-avila/LibreChat/blob/3606349a0f1c9ad2242e3c1ea15e09181374f407/api/server/services/Endpoints/agents/initialize.js#L147

Agent run creation:
https://github.com/danny-avila/LibreChat/blob/3606349a0f1c9ad2242e3c1ea15e09181374f407/api/server/controllers/agents/run.js#L34

**Reply by nhtruong** [reply]
Thank you!

**Reply by nhtruong** [reply]
I've traced the `agent.model_parameters` to [graphConfig](https://github.com/danny-avila/LibreChat/blob/24c0433dcf3b84a82eafce055c9076de98efc57b/api/server/controllers/agents/run.js#L89) in
```ts
  return Run.create({
    runId,
    graphConfig,
    customHandlers,
  });
```

however, `Run` is part of `@librechat/agents` npm package. The source code of the package is stored in https://github.com/danny-avila/agents and it's a private repo.

**Reply by nhtruong** [reply]
I'll focus on existing parameters for now as the ability to set your own min/max and default value for these parameters is very valuable.

**Reply by danny-avila** [reply]
@nhtruong can you give an example of what you're seeing vs. what you're expecting?

**Reply by nhtruong** [reply]
Let's say I hook Librechat up to a homegrown LLM model that accepts `temperature` and `pressure` as parameters to finetune the the answers given by the model. So, I add these parameters to `endpoints.custom.[].customParams.paramDefinitions` of `librechat.yaml`. When I create an agent, I'll set the `temperature` at 0.5 and `pressure` at 3.0 (pressure is just a hypothetical new parameter), and the `agent.model_parameters` will be saved as `{ temperature: 0.5, pressure: 3.0 }`.

Then I ask this agent a question, those parameters will go through several transformations and in `agents/run.js`, these parameters will be included in `graphConfig`, which has the following value:
```json
{"signal":{},"llmConfig":{"provider":"openAI","streaming":true,"streamUsage":false,
"temperature":0.5,"pressure":3.0,
"user":"--redacted--","openAIApiKey":"--redacted--",
"configuration":{"baseURL":"--readacted--","defaultHeaders":{}},
"model":"gemini-x2","usage":true},"instructions":""}
```
It appears to me that only known parameters like `temperature` will be extracted from that JSON object and fed into to the LLM endpoints. So, my goal is updating the bit of code that sends API requests to the LLM endpoint to also include new parameters.

**Reply by danny-avila** [reply]
Understood, yes "unknown" params will get discarded. I need to add this functionality as described here: https://github.com/danny-avila/LibreChat/discussions/7251#discussioncomment-13057622

**Comment by nhtruong** [comment]
I'm almost done with part A, which is Customize/set-defaults for existing parameters. I just need to add more tests and tidy up my [code](https://github.com/danny-avila/LibreChat/pull/7225). While working on this, I also added a small feature that lets user of custom endpoints pick the appropriate set of params for their endpoints.

As of right now if you the following custom endpoints defined:
```yaml
# librechat.yaml

endpoints:
  custom:
    - name: 'Αnthropic'
      # ...
    - name: 'Google Gemini'
      # ...
```
### The set of parameters available to both of these endpoints are identical. It inherits from OpenAI params, which doesn't make sense for neither Anthropic nor Google:

![Screenshot 2025-05-09 at 5 30 32 PM](https://github.com/user-attachments/assets/ad22527b-6073-41bc-86cf-1d6050879f8f)

---
---

### With this new feature you can update the `librechat.yaml` file like so:

```yaml
endpoints:
  custom:
    - name: 'Αnthropic'
      # ...
      customParams:
        defaultParamsEndpoint: 'anthropic'

    - name: 'Google my Google'
      # ...
      customParams:
        defaultParamsEndpoint: 'google'
        paramDefinitions:
          - key: temperature
            range:
              min: 0
              max: 0.7
              step: 0.1
            default: 0.5
 ```

### Now `Anthropic` custom endpoint will use parameters for `anthropic`:


![Screenshot 2025-05-09 at 5 31 38 PM](https://github.com/user-attachments/assets/dd8454b7-3ee1-4fc9-a800-d083ff55509b)

### And `Google Gemini` custom endpoint will use parameters for `google`. On top of that, we get to pick our own range and default value for `temperature` parameter:

![image](https://github.com/user-attachments/assets/dbc239ef-886a-4f46-8161-4d4a7c17cfb7)

---

I also added a lot of validation checkpoints to assure that values put into `customParams` are legit.
