### DISCUSSION TITLE
`includedTools` setting not respected when agents chain is active

### DISCUSSION THREAD

**Discussion by sbruel** [danny-avila/LibreChat#7197] [Troubleshooting]
### What happened?

We use the following settings in `librechat.yml`
```yml
endpoints:
  agents:
    disableBuilder: false
    capabilities:
      - 'file_search'
      - 'actions'
      - 'tools'
      - 'artifacts'
...
includedTools:
  - google
  - dalle
  - calculator

mcpServers:
  some-server:
    ...
```
and everything works as expected.
When adding `chain` to the list of capabilities, as in:
```yml
endpoints:
  agents:
    disableBuilder: false
    capabilities:
      - 'file_search'
      - 'actions'
      - 'tools'
      - 'artifacts'
      - 'chain'
...
includedTools:
  - google
  - dalle
  - calculator

mcpServers:
  some-server:
    ...
```

The `includedTools` list is not respected and the tools from the MCP server don't appear anymore when creating an agent.
All the default tools appear again:

![Image](https://github.com/user-attachments/assets/8149e252-d3a1-4ffe-b285-83fc017bda59)

### Version Information

5efad8f646a8efb7c010e85f355d9ac88b823048

### Steps to Reproduce

1. Add `includedTools` configuration to `librechat.yml`
2. Disable `chain` in  `endpoints.agents.capabilities`
3. Try creating an agent
4. Confirm only the included tools are visible
5. Add `chain` to `endpoints.agents.capabilities`
6. Try creating an agent
7. All the tools are now visible (but not MCP servers provided ones if configured)

### Relevant log output

```shell
N/A
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
I can't replicate this.

```yml
endpoints:
  agents:
    disableBuilder: false
    capabilities:
      - 'file_search'
      - 'actions'
      - 'tools'
      - 'artifacts'
      - 'chain'
...
includedTools: ["youtube","image_gen_oai"]
...
mcpServers:
  some-server:
    ...
```

![chrome_iwmgpmdwhZ](https://github.com/user-attachments/assets/ac39f1bb-268e-4bb4-b505-77db44315146)


> Relevant log output

You need to provide logs, there are some loaded at startup that would be helpful here.

Here's my relevant log output:

```bash
2025-05-02T19:05:02.480Z info: Custom config file loaded:
2025-05-02T19:05:02.481Z info: {
  "includedTools": [
    "youtube",
    "image_gen_oai"
  ],
  "imageOutputType": "png",
  "secureImageLinks"... [truncated]
2025-05-02T19:05:02.481Z debug: Custom config:
{
  includedTools: ["youtube","image_gen_oai"],
    agents.disableBuilder: false,
    // 5 capabilitie(s)
    agents.capabilities: ["file_search","actions","tools","artifacts","chain"],

```

Lastly, make sure you are up to date:

Updating Instructions (docker):

https://www.librechat.ai/docs/local/docker#update-librechat
