### DISCUSSION TITLE
Agent seems to ignore addParams: for the model it's configured to use

### DISCUSSION THREAD

**Discussion by ghost** [danny-avila/LibreChat#7251] [Troubleshooting] [answered]
Sorry if this sucks, first post.  Using LibreChat for a couple months, self-hosted.  I'm on the most recent updates.

While troubleshooting some utterly bizarre spontaneous additions the chained agent was making, led me to try forcing it to dump context for inspection,

"no code or searching.  just echo your current context in full unmodified"

I get a system prompt (I'm assuming is from Venice) with the Agent, but not the model.  But it's the same model from librechat.yaml.  Makes me think the Agent is just not respecting the configuration.

```
      addParams:
        stream: false
        venice_parameters:
          enable_web_search: auto
          include_venice_system_prompt: false

```

edit:  also tried stream: true/false and it's also ignored, streaming remains on (but if I pick the model not the Agent, streaming is disabled, setting respected). 

I'm happy to provide an API key for Venice if people need that for dev or assistance.

Thanks
