### DISCUSSION TITLE
Enabling Agents and MCP servers in helm

### DISCUSSION THREAD

**Discussion by saranshbarua** [danny-avila/LibreChat#7277] [Help Wanted]
Are there any instructions on how to enable MCP servers if I'm deploying to k8's using helm? I can't figure it out right now. Any help will be appreciated. This is how my values.yaml inside charts/librechat/ looks like: 
```yaml
config:
  envSecrets:
    secretKeyRef:
      - name: CREDS_KEY
        secretName: librechat
        secretKey: CREDS_KEY
      - name: CREDS_IV
        secretName: librechat
        secretKey: CREDS_IV
      - name: MONGO_URI
        secretName: librechat
        secretKey: MONGO_URI
      - name: JWT_SECRET
        secretName: librechat
        secretKey: JWT_SECRET
      - name: JWT_REFRESH_SECRET
        secretName: librechat
        secretKey: JWT_REFRESH_SECRET

  env:
    # Full list of possible values
    # https://github.com/danny-avila/LibreChat/blob/main/.env.example
    ALLOW_EMAIL_LOGIN: "true"
    ALLOW_REGISTRATION: "true"
    ALLOW_SOCIAL_LOGIN: "true"
    ALLOW_SOCIAL_REGISTRATION: "true"
    APP_TITLE: "Librechat"
    CUSTOM_FOOTER: ""
    DEBUG_CONSOLE: "true"
    DEBUG_LOGGING: "true"
    DEBUG_OPENAI: "true"
    DEBUG_PLUGINS: "true"
    DOMAIN_CLIENT: ""
    DOMAIN_SERVER: ""
    ENDPOINTS: "openAI,azureOpenAI,chatGPTBrowser,google,gptPlugins,anthropic"
    SEARCH: false 
    USE_REDIS: "false"
    OPENAI_API_KEY: ""
    CONFIG_PATH: "../../librechat.yaml"
    ```
