### DISCUSSION TITLE
LibreChat crashes on startup: ERR_INVALID_ARG_TYPE in crypto.js despite valid ENCRYPTION_KEY

### DISCUSSION THREAD

**Discussion by joshiestevens** [danny-avila/LibreChat#7298] [Troubleshooting] [answered]
### What happened?

I'm trying to self-host LibreChat using Docker (Hetzner VPS, Ubuntu 22.04) and running into a persistent crash. Same issue on Railway too.

```
TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
    at Function.from (node:buffer:322:9)
    at Object.<anonymous> (/app/api/server/utils/crypto.js:6:20)
```
The logs show the container exits immediately after this error.
I’ve confirmed:

I'm using ghcr.io/danny-avila/librechat:latest

ENCRYPTION_KEY is base64-encoded, 44 characters, decodes to 32 bytes

MONGO_URI and all other required environment variables are set directly in docker-compose.yml (no .env file)

Container is built with docker compose up -d from /opt/librechat

Despite all this, I consistently get the same crash. The same happened on Railway, so I suspect an upstream issue in parsing or reading the environment.

docker-compose.yml as follows:
```
services:
  librechat:
    image: ghcr.io/danny-avila/librechat:latest
    ports:
      - "3000:3000"
    environment:
      - OPENAI_API_KEY="XXX
      - NEXTAUTH_SECRET="librechat-secret-123"
      - NEXTAUTH_URL="http://167.235.242.20:3000"
      - NEXTAUTH_PROVIDER="credentials"
      - ENCRYPTION_KEY="v1uJBqv2HKNZYSBqd5HoNS3C02tcI4RH2BsHo68msZo=“
      - DATABASE_URL="mongodb://mongo:27017/librechat"
      - ALLOW_CHAT_HISTORY="false"
      - CLOUD_UPLOADS="false"
      - DISABLE_TELEMETRY="true"
      - MONGODB_DB_NAME="librechat"
    volumes:
      - ./uploads:/app/uploads

  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
```

Any help would be appreciated. docker-compose.yml or logs if needed.

Thanks!

### Version Information

ghcr.io/danny-avila/librechat:latest

### Steps to Reproduce

Deploy ghcr.io/danny-avila/librechat:v0.7.8 using Docker Compose on a VPS (Ubuntu 22.04)

Set all required environment variables directly in docker-compose.yml, including:

ENCRYPTION_KEY (valid base64, 32 bytes)

MONGO_URI

OPENAI_API_KEY

Run docker compose up -d

Observe that librechat-librechat-1 crashes immediately with ERR_INVALID_ARG_TYPE from Buffer.from(...) in crypto.js

### Relevant log output

```shell
TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
    at Function.from (node:buffer:322:9)
    at Object.<anonymous> (/app/api/server/utils/crypto.js:6:20)
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
