### DISCUSSION TITLE
[Question] How do I setup OpenAI, Google (Gemini), and/or Groq? Need help with model spec, and selecting one.

### DISCUSSION THREAD

**Discussion by iamronr** [danny-avila/LibreChat#7343] [Help Wanted]
I have the APIs for all of them. I have the setting set up in .env where the API is set up per user. When I enter the API for Gemini or OpenAI, the window closes, but nothing happens. When I go to test, I get this error:

![tr 2025-05-12 at 7 43 19 PM](https://github.com/user-attachments/assets/1182ab57-f039-4cfe-8feb-40742af50bca)
![tr 2025-05-12 at 7 43 42 PM](https://github.com/user-attachments/assets/214c351d-a725-40e8-9532-f21a4838ca35)

What am I missing regarding selecting a model spec?

**Comment by iamronr** [comment]
Here's another screenshot, after I pasted my API key again in Gemini. I even went to add a modelSpec in librechat.yaml, see below as well, still the same thing unfortunately. 

![tr 2025-05-12 at 7 59 18 PM](https://github.com/user-attachments/assets/1fc6fce8-2249-431c-a2f0-2dca7a784d9a)

```
- name: "Google Gemini 2.0 Flash-Lite"
      label: "Google Gemini 2.0 Flash-Lite"
      default: false
      description: "Gemmiiinnniiiiiiii"
      preset:
        endpoint: "google"
        model: "gemini-2.0-flash-lite"
        modelLabel: "Google Gemini 2.0 Pro Exp"
        greeting: |
          Google Gemini 2.0 Flash-Lite • 🚀🖼️💰
```
