### DISCUSSION TITLE
Configuration of librechat.yaml for Azure OpenAI

### DISCUSSION THREAD

**Discussion by apamildner** [danny-avila/LibreChat#7364] [Troubleshooting] [answered]
### What happened?

When using a custom key for models( see example), the chat fails with: "Something went wrong. Here's the specific error message we encountered: An error occurred while processing your request. Please contact the Admin."
<img width="933" alt="Image" src="https://github.com/user-attachments/assets/786ca551-c6a5-45b9-a995-3cdac3549c50" />

### Version Information

v.0.7.8

### Steps to Reproduce

This doesn't work:
```yaml
version: 1.2.1
endpoints:
  azureOpenAI:
    plugins: true
    summarize: true
    titleConvo: true
    groups:
      - group: "some-grp"
        apiKey: ${OPENAI_API_KEY}
        instanceName: some-instance-name
        version: 2025-01-01-preview
        models:
          foo: # key differs from deploymentName
            deploymentName: "gpt-4.1"
```

But this works (notice that the name `gpt-4.1` is same for the key and the `deploymentName` under models)

```yaml
version: 1.2.1
endpoints:
  azureOpenAI:
    plugins: true
    summarize: true
    titleConvo: true
    groups:
      - group: "some-grp"
        apiKey: ${OPENAI_API_KEY}
        instanceName: some-instance-name
        version: 2025-01-01-preview
        models:
          gpt-4.1: # Here we use the same name as deploymentName
            deploymentName: "gpt-4.1"
```

### Relevant log output

```shell
error: [handleAbortError] AI response error; aborting request: Failed to send message. HTTP 400 - Unsupported data type
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment, marked as answer]
Thanks for the report but this is not a bug—it's expected behavior.

- In your config, the key under `models:` (the "model identifier") must match an actual LLM model name or identifier (like `gpt-4.1`).  
- If you use a random key (like `foo:`), LibreChat can't recognize the model, resulting in errors.
- This matches what's stated in the [docs](https://www.librechat.ai/docs/configuration/azure#model-level-configuration):  
  > The model identifier must match its corresponding OpenAI model name.

**Fix:**  
Change your model config to:
```yaml
models:
  gpt-4.1:
    deploymentName: "gpt-4.1"
```
Arbitrary keys are not meant to be used under `models:`. The motivation behind this is to allow cases where the deployment name is not a valid LLM model name or identifier (like `gpt-4.1`). 

Do you have a specific use case for customizing this key? As long as it's a partial match to a system-known model, it will work as expected.

![chrome_kgLqS38M9R](https://github.com/user-attachments/assets/90dd4617-80bd-4c23-bd0c-6de8d6a3bf16)

```yaml
endpoints:
  azureOpenAI:
    streamRate: 35
    titleModel: "gpt-4o"
    titleConvo: true
    groups:
    - group: "my-group-name"
      apiKey: "${MY_API_KEY_REFERENCE}"
      instanceName: "my-instance-name"
      version: "2024-12-01-preview"
      models:
        gpt-4.1:
          deploymentName: "gpt-4.1"
```

**Reply by apamildner** [reply]
I see! I think I just misunderstood it. My intuition was just that the names under `models` would be arbitrary, because then I could call them what I want when the user opens the drop down to select models. The model used is already decided by the deploymentName that I chose. So if I set this up for my customers, I could instead call the model for example `recommended` and I know that the model is gpt-4.1, but the user doesn't need to know:
```yaml
      models:
        recommended:
          deploymentName: "gpt-4.1"
```
