### DISCUSSION TITLE
Getting 400 is too short - 'messages' - Trying to Use Google Search as an agent

### DISCUSSION THREAD

**Discussion by iamronr** [danny-avila/LibreChat#7376] [Troubleshooting]
I'm trying to use Google Search as an agent. It seems to work, as it starts to load, but then it errors with `400 [] is too short - 'messages'`. Any insight on how to fix this? I'm kinda lost at the moment.

![tr 2025-05-14 at 1 42 01 PM](https://github.com/user-attachments/assets/73207644-ac1f-4bf6-812d-4a6382785c9f)

![tr 2025-05-14 at 1 42 33 PM](https://github.com/user-attachments/assets/6ae76556-48d5-42f1-8f41-f86809ffeecd)

```
defaults:
    - id: "agent_ztMchXv1zcoWvWcxCquNC"
      name: "Qwen3 Agent"
      allowedProviders: ["google"]
      description: "Qwen3 with Google Search access"
      # instructions: |
      #   You are a specialized Contract Search and Analysis agent with expertise in legal document analysis. Your purpose is to help users search, analyze, and extract information from contracts with precision and accuracy.
      provider: "Ollama - rGPT"
      model: "hf.co/unsloth/Qwen3-8B-GGUF:Q8_0"
      model_parameters:
        temperature: 0.2
        top_p: 1
      tools: ["tools"]
      capabilities: ["tools"]
```
