### DISCUSSION TITLE
[Enhancement]: Configure a read-only default agent accessible by all users of my instance

### DISCUSSION THREAD

**Discussion by jbkoh** [danny-avila/LibreChat#7381] [Feature Requests & Suggestions]
### What features would you like to see added?

I'm using LibreChat as a chat solution for my customers, and I'd like to provide a predefined agent to any users using my service. It'd be great if I can define an agent through configuration so that it shows up as a default agent to all users.

### More details

n/a

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by dareima** [comment]
@jbkoh that is already possible through ModelSpecs.

[ModelSpecs Documentation](https://www.librechat.ai/docs/configuration/librechat_yaml/object_structure/model_specs)

You need to create and configure your LibreChat agent, share it as an admin with all users and then create a ModelSpec for it. Here's an example how we are doing it:

```
modelSpecs:
  enforce: false
  prioritize: true
  list:
    - name: "your-agent-name"
      label: "Display name of your agent"
      description: "Short description of your agent"
      iconURL: "https://url-to-an-optional-agent-icon/images/agent.jpeg"
      preset:
        default: true      
        endpoint: "agents"
        agent_id: "agent_your-agent-id-derived-from-the-agent-builder"
        max_tokens: 16000 # Maximum output tokens depending on the configured agent model
        maxContextTokens: 128000 # Maximum context tokens depending on the configured agent model
        temperature: 0.75
        top_p: 0.95
    - name: "Agent 2"
   ...
```

The only downside of using ModelSpecs is still, that you cannot make a difference between ADMINs and USERS. As in, have users using ModelSpecs but admins not, or just have specific users and groups using ModelSpecs. That might be something for future releases.
