### DISCUSSION TITLE
Invalid custom config file at

### DISCUSSION THREAD

**Discussion by yidasanqian** [danny-avila/LibreChat#7430] [Troubleshooting]
librechat.yaml
```
endpoints:
  azureOpenAI:
    # Endpoint-level configuration
    titleModel: "gpt-image-1"
    plugins: true
    groups:
      # Group-level configuration
      - group: "xxxxx"
        apiKey: "${AZURE_API_KEY}"
        instanceName: "xxxxx" # name of the resource group or instance
        baseURL: "https://xxxx.openai.azure.com"
        version: "2025-04-01-preview"
        # Model-level configuration
        models:
          gpt-image-1:
            deploymentName: gpt-image-1
            version: "2025-04-01-preview"
```
LOG:
```
2025-05-17 05:14:49 error: Invalid custom config file at /app/librechat.yaml:
{
  "issues": [
    {
      "code": "invalid_type",
      "expected": "string",
      "received": "undefined",
      "path": [
        "version"
      ],
      "message": "Required"
    }
  ],
  "name": "ZodError"
}
```
how to fix?

**Comment by tlze** [comment]
Why does your YAML file differ a lot from the example?
My librechat.yaml works well.
```
endpoints:
  custom:
    - name: "Oai"
      apiKey: "${OPENAI_API_KEY}"
      baseURL: "https://oai.xxx.xxx/v1"
      models:
        default: ["gpt-4o-mini", "gpt-4.1"]
        fetch: true
      titleConvo: true
      titleModel: "current_model"
```
