### DISCUSSION TITLE
Is it possible to use environment variables that are not set on librechat.yaml?

### DISCUSSION THREAD

**Discussion by f-avelar** [danny-avila/LibreChat#7438] [Q&A] [answered]
Hello,
I'm trying to setup a simple mcp server on librechat with the following block:
```yaml
mcpServers:
  notionApi:
    type: stdio
    command: npx
    args:
      - -y
      - "@notionhq/notion-mcp-server"
    env:
      OPENAPI_MCP_HEADERS: xxx
```

When I use this example, everything works fine. However, I'm wondering if it's possible to set OPENAPI_MCP_HEADERS directly in the environment or another location, instead of putting it in plain text in the librechat.yaml file. Is this possible?

I have already tried exporting the variable, but it doesn't seem to work.
