### DISCUSSION TITLE
[Enhancement] Conditional Parameters

### DISCUSSION THREAD

**Discussion by nhtruong** [danny-avila/LibreChat#7494] [Feature Requests & Suggestions]
When using Claude, the user can toggle `Thinking` on and off.  However, there are 2 issues:
- You can still adjust `Temperature` to any value (even though it should be locked at 1.0) when `Thinking` is turned on.
- You can still adjust `Thinking Budget` when `Thinking` is turned off.

We need the ability to visually display the parameter constraints to avoid confusion for the user. Instead of hard-coding this logic for Claude's `Thinking` parameter specifically, we can turn this into a feature called conditional parameters. I'm thinking of putting the info into the parameter definitions like so for `thinking`:

```yaml
key: thinking
type: boolean
...
conditions:
 - if: "{{value}} == true"
   then:
     thinking_budget:
        enabled: true
     temperature:
        enabled: false
        value: 1.0
  - if: "{{value}} == false"
    then:
      thinking_budge:
         enabled: false
      temperature:
         enabled: true
```

This info is then sent to the frontend to setup event listeners to adjust the states of these parameters accordingly.
