### DISCUSSION TITLE
Support for `grok-3` in Azure OpenAI

### DISCUSSION THREAD

**Discussion by taurit** [danny-avila/LibreChat#7508] [Q&A] [answered]
### What features would you like to see added?

Hey! Microsoft [recently added `grok-3`](https://devblogs.microsoft.com/foundry/announcing-grok-3-and-grok-3-mini-on-azure-ai-foundry/) model to its Azure AI Foundry offering.

Do you know if this model can be already used right now in LibreChat with proper config, or a support needs to be explicitly added to LibreChat code first? My attempt to use it failed with an error.

### More details

I attempted to set it up similarly to other models (which work for me):

```librechat.yaml
endpoints:
  azureOpenAI:
    groups:
      - group: "somethingSomething-eastus2"
        apiKey: "${AZURE_API_KEY}"
        instanceName: "${AZURE_INSTANCE_NAME}"
        assistants: false
        models:
          gpt-4.1:
            deploymentName: gpt-4.1
            version: "2025-01-01-preview"

          # (...)

          grok-3:
            deploymentName: grok-3
            version: "2025-01-01-preview"
```

When I try to use the prompt I see error in logs:

```
 2025-05-22T16:23:11.488Z debug: [AskController]
 {
   text: "hey, what model are you?",
   conversationId: "43e00e22-29ff-4cb3-9c60-24743da9ef68",
   endpoint: "azureOpenAI",
   resendFiles: true,
   modelOptions.model: "grok-3",
   modelsConfig: "exists",
 }
 
 2025-05-22T16:23:11.672Z error: [AskController] Error handling request Failed to send message. HTTP 400 - Unsupported data type
 2025-05-22T16:23:11.673Z error: [handleAbortError] AI response error; aborting request: Failed to send message. HTTP 400 - Unsupported data type
```

### Pictures

![Image](https://github.com/user-attachments/assets/1465039c-1913-4484-9679-1cfd2f64dfad)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment, marked as answer]
You can add it already:
```
      - group: "serverless-example"
        apiKey: "${AZURE_SERVERLESS_API_KEY}"
        baseURL: "https://aoai-syourendpoint.services.ai.azure.com/models/"
        version: "2024-05-01-preview"
        serverless: true
        models:
          grok-3: true
```

More info: 

https://www.librechat.ai/docs/configuration/azure#serverless-inference-endpoints

**Reply by taurit** [reply]
Works indeed, thanks! Librechat is awesome 😊

![image](https://github.com/user-attachments/assets/530bf1af-6273-4cf9-a3c6-a8b300919407)

**Comment by danny-avila** [comment]
For the record, you can also use Grok 3 (from Azure) as a custom endpoint:
```yaml
    - name: "azure_xai"
      apiKey: "$AZURE_OAI_API_KEY}"
      baseURL: "https://your-endpoint.ai.azure.com/models/"
      models:
        default: ["grok-3"]
        fetch: true
      titleConvo: true
      titleMethod: "completion"
      titleModel: "grok-beta"
      summarize: false
      summaryModel: "grok-beta"
      forcePrompt: false
      modelDisplayLabel: "Grok"
      headers:
        "api-version": "2024-05-01-preview"
```
![chrome_D7GXG1n6NC](https://github.com/user-attachments/assets/b7971b82-7a1f-4143-ac37-7074f7bbe73c)
