### DISCUSSION TITLE
MCP error

### DISCUSSION THREAD

**Discussion by gcanlin** [danny-avila/LibreChat#7514] [Q&A]
Hi. I deployed librechat in my personal server and used GitHub mcp server. But I met two bugs. The first one is that I can't send the first message to my custom llm with mcp config, which will lead to the below error 1. And the second one is that llm can't send the right parameters to mcp server. It will divide them. I don't think that it's llm's fault. It's ok that I used other agent chat to do the same thing. Maybe I lose some configs. Please help me.

error 1:
```
Something went wrong. Here's the specific error message we encountered: An error occurred while processing the request: litellm.APIConnectionError: APIConnectionError: OpenAIException - litellm.APIConnectionError: APIConnectionError: OpenAIException - peer closed connection without sending complete message body (incomplete chunked read)
```

My mcp config:
```yaml
mcpServers:
  github:
    type: "stdio"
    command: "/root/github-mcp-server/cmd/github-mcp-server/github-mcp-server"
    args: 
      - stdio
    env: 
      GITHUB_PERSONAL_ACCESS_TOKEN: "xxxx"
```

error 2:
![image](https://github.com/user-attachments/assets/0ad12f0b-f14b-4ef5-b6fa-7082e6c3ebeb)
