### DISCUSSION TITLE
web search not working or not intuitive

### DISCUSSION THREAD

**Discussion by im360john** [danny-avila/LibreChat#7581] [Troubleshooting]
### What happened?

installed serper, firecrawl and cohere api keys into env variables.  

when trying the web search with gpt 4 mini or claude 3.7, i get a cannot search the web response:  

<img width="707" alt="Image" src="https://github.com/user-attachments/assets/9d6deea0-12cd-40e2-9832-63246c535634" />

also, does agents have access to the same web search or is it limited to google's api path as a tool

### Version Information

latest

### Steps to Reproduce

see above

### Relevant log output

```shell
na
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
try to toggle the "Search" button on/off, and check server logs

**Reply by im360john** [reply]
nothing in the logs.  tried toggling on and off.  also tried incognito mode

**Comment by doprado** [comment]
I am facing the same problem.

![image](https://github.com/user-attachments/assets/9378232e-84b5-42ad-a2c9-eecbe34b8045)

**Comment by im360john** [comment]
{
  baseURL: "https://api.openai.com/v1",
    modelOptions.model: "gpt-4o-mini",
    modelOptions.user: "6834a2822f462c3d2a1b3b77",
    modelOptions.stream: true,
    // 1 message(s)
    modelOptions.messages: [{"role":"user","content":"google the best prices"}],
}
2025-05-26T21:36:30.078Z debug: Making request to https://api.openai.com/v1/chat/completions
2025-05-26T21:36:30.083Z debug: [saveConvo] api/app/clients/BaseClient.js - saveMessageToDatabase #saveConvo
2025-05-26T21:36:30.117Z debug: [FinalizationRegistry] Cleaning up client for user 68267c068706445bb3167dc9
2025-05-26T21:36:30.117Z debug: [FinalizationRegistry] Cleaning up client for user 6834a2822f462c3d2a1b3b77
2025-05-26T21:36:33.613Z debug: [OpenAIClient] chatCompletion response
{
  object: "chat.completion",
  service_tier: "default",
    usage.prompt_tokens: 11,
    usage.completion_tokens: 231,
    usage.total_tokens: 242,
    prompt_tokens_details.cached_tokens: 0,
    prompt_tokens_details.audio_tokens: 0,
    completion_tokens_details.reasoning_tokens: 0,
    completion_tokens_details.audio_tokens: 0,
    completion_tokens_details.accepted_prediction_tokens: 0,
    completion_tokens_details.rejected_prediction_tokens: 0,
  id: "chatcmpl-BbZmgyEr34F7m54z9stwhuCCbUihI",
  // 1 choice(s)
  choices: [{"message":{"role":"assistant","content":"I can't browse the internet in real time, but I can sugges... [truncated]],
  created: 1748295390,
  model: "gpt-4o-mini-2024-07-18",
  system_fingerprint: "fp_34a54ae93c",
}
2025-05-26T21:36:33.622Z debug: [spendTokens] conversationId: 3ceca4fe-7070-4b02-bec2-7f4a365d3133 | Context: message | Token usage:
{
  promptTokens: 11,
  completionTokens: 231,
}
2025-05-26T21:36:33.660Z debug: [spendTokens] Transaction data record against balance:
{
  user: "6834a2822f462c3d2a1b3b77",
  prompt: -1.65,
  promptRate: 0.15,
  completion: -138.6,
  completionRate: 0.6,
  balance: 199829.9,
}
2025-05-26T21:36:33.660Z debug: [spendTokens] conversationId: 3ceca4fe-7070-4b02-bec2-7f4a365d3133 | Context: reasoning | Token usage:
{
  promptTokens: undefined,
  completionTokens: 0,
}
2025-05-26T21:36:33.673Z debug: [spendTokens] Transaction data record against balance:
{
  user: "6834a2822f462c3d2a1b3b77",
  prompt: undefined,
  promptRate: undefined,
  completion: 0,
  completionRate: 0.6,
  balance: 199829.9,
}
2025-05-26T21:36:33.681Z debug: [saveConvo] api/app/clients/BaseClient.js - saveMessageToDatabase #saveConvo
2025-05-26T21:36:33.693Z debug: [AskController] Request closed
2025-05-26T21:36:33.701Z debug: [AskController] Performing cleanup
2025-05-26T21:36:33.701Z debug: [AskController] Cleaning up abort controller
2025-05-26T21:36:33.701Z debug: [AskController] Cleanup completed

--

nothing specific about the search tool being triggered or any of the apis (serper, cohere, firecrawl) being called.

**Comment by danny-avila** [comment]
I think I know the issue, what is the value of your `ENDPOINTS` environment variable? For now, `agents` needs to be included, but I will think about this case where it may not be set.

```bash
ENDPOINTS=openAI,agents
```

**Reply by Odrec** [reply]
I'm having the same issue as OP and I have the agents endpoint activated. But is the web search function only for agents? I tried it with a regular model from openrouter by pressing the Search button.

**Reply by danny-avila** [reply]
No, you can use it directly:

![chrome_io7ZR9KJ04](https://github.com/user-attachments/assets/208ae90f-2c72-4f7e-ac41-0d6cc8c3573c)

@Odrec do you have anything configured for agents in `librechat.yaml`

Right now, I've only reproduced the issue when omitting agents from `ENDPOINTS`, i.e.:
```bash
ENDPOINTS=openAI,custom
# instead of:
# ENDPOINTS=openAI,custom,agents
```

**Reply by Odrec** [reply]
I have this in the librechat.yaml file

```
endpoints:
  agents:
    recursionLimit: 50
    maxRecursionLimit: 100
    disableBuilder: false
    capabilities:
      - "file_search"
      - "artifacts"
      - "actions"
      - "tools"
```

and this in .env

`ENDPOINTS=custom,agents`

**Reply by danny-avila** [reply]
`web_search` is a capability that needs to be added:

```yaml
endpoints:
  agents:
    recursionLimit: 50
    maxRecursionLimit: 100
    disableBuilder: false
    capabilities:
      - "file_search"
      - "artifacts"
      - "actions"
      - "tools"
      - "web_search"
```

https://www.librechat.ai/docs/features/web_search#usage
https://www.librechat.ai/docs/configuration/librechat_yaml/object_structure/agents#capabilities

**Reply by danny-avila** [reply]
going to improve the UX here and make sure this badge only shows up if is all set for usage

**Reply by doprado** [reply]
Now it worked. It really needs the "web_search." But, with custom endponts dont working, Only with OpenAI model selected 

![image](https://github.com/user-attachments/assets/9193e002-75b1-4fbd-b091-725747f3adfb)

**Reply by danny-avila** [reply]
@doprado do you have `allowedProviders` configured in your yaml? This error should only show up when it is set.

https://www.librechat.ai/docs/configuration/librechat_yaml/object_structure/agents#allowedproviders

**Reply by doprado** [reply]
@danny-avila  Yes:

```
endpoints: 
  agents:
    recursionLimit: 50
    maxRecursionLimit: 100
    disableBuilder: false
    allowedProviders:
      - openAI
    capabilities:
      - "file_search"
      - "actions"
      - "tools"
      - "artifacts"
      - "ocr"
      - "chain" 
      - "web_search"
```

```
modelSpecs:
  prioritize: true
  list:    
    - name: "openai/gpt-4o-mini"
      label: "ChatGPT 4o Mini"
      default: true
      description: "Excelente para maioria das tarefas"
      iconURL: "https://unpkg.com/@lobehub/icons-static-svg@1.45.0/icons/openai.svg"
      preset:
        endpoint: "ChatGPT"
        modelLabel: "GPT-4o Mini"
        greeting: "Este o modelo é excelente para maioria das tarefas"
        append_current_datetime: true
```

```
custom:    
    - name: "ChatGPT"
      apiKey: "dummy"
      baseURL: "${PORTKEY_GATEWAY_URL}"
      headers:
        x-portkey-api-key: "${PORTKEY_API_KEY}"
      models:
        default: 
          - "openai/gpt-4o-mini"
          - "openai/gpt-4o-mini-search-preview"
          - "openai/gpt-4o"
          - "openai/o1-mini"	
          - "openai/o3-mini"
          - "openai/o4-mini"
          - "openai/gpt-4.1-mini"
        fetch: false
      titleConvo: true      
      summarize: false
      summaryModel: "current_model"
      forcePrompt: false      
      titleModel: 'google/gemini-2.0-flash-001'
      iconURL: https://unpkg.com/@lobehub/icons-static-svg@latest/icons/openai.svg

```

**Reply by im360john** [reply]
[libreyaml.txt](https://github.com/user-attachments/files/20463013/libreyaml.txt)
hmm, agents on claude or openai still responding that they can't search the web.   Anything wrong from my attached librechat.yaml file?   My env variables has ENDPOINTS set to custom,agents,openAI    and I have the keys for serper, etc.  

nothing in the log that indicates errors

**Reply by doprado** [reply]
@im360john 
I believe something is missing.
```
allowedProviders:
 - openAI
```

**Reply by im360john** [reply]
tried adding and still the same response.  
allowedProviders:
      - openAI
      - anthropic      
      - google

**Reply by danny-avila** [reply]
@im360john the config looks good and should work. To be sure webSearch wasn't disabled (although you shouldn't see it if it were), you can add `webSearch: true` to `interface:`
```yaml
interface:
  runCode: true
  agents: true
  webSearch: true
  modelSelect: true
  customWelcome: "Hey {{user.name}}! Welcome"
```

Also, what does your ENDPOINTS environment variable look like? For now, it should include `agents`, but I'm going to handle the case where `agents` endpoint is not defined.

```.env
# example
ENDPOINTS=openAI,agents
# instead of:
# ENDPOINTS=openAI
```

See changes merging soon: https://github.com/danny-avila/LibreChat/pull/7598

I'm also adding better logging for when the capability is disabled (and therefore not being added to the chat run).
