### DISCUSSION TITLE
after install with helm chart librechat installation always return error

### DISCUSSION THREAD

**Discussion by Slach** [danny-avila/LibreChat#7620] [Troubleshooting]
### What happened?

I use following deploy approach
install ollama models with ollama-operator
```bash
kubectl apply --server-side=true -f https://github.com/nekomeowww/ollama-operator/raw/refs/heads/main/dist/install.yaml
kubectl apply -n ollama-operator-system -f librechat/ollama-models.yaml
kubectl apply -n ollama-operator-system -f librechat/ollama-services.yaml
```
install gateway database MCP server
```
rm -rf /tmp/gateway
helm pull oci://ghcr.io/centralmind/gateway-helm/gateway --destination /tmp/ --untar
kubectl create namespace gateway-system || true
helm upgrade --install gateway /tmp/gateway --namespace gateway-system --values "$CUR_DIR/gateway-values.yaml"
```

## install librechat + librechat-rag-api
```bash
git clone https://github.com/danny-avila/LibreChat.git /tmp/LibreChat
helm repo add bitnami https://charts.bitnami.com/bitnami
helm repo add meilisearch https://meilisearch.github.io/meilisearch-kubernetes

# Create namespace for LibreChat
kubectl create namespace librechat || true

# Install LibreChat with Helm
cd /tmp/LibreChat/helm/librechat-rag-api && helm dependency build && cd -
helm upgrade --install librechat-rag-api /tmp/LibreChat/helm/librechat-rag-api \
  --namespace librechat \
  --values "$CUR_DIR/librechat-rag-api-values.yaml"

# Build Helm dependencies
cd /tmp/LibreChat/helm/librechat && helm dependency build && cd -

# Install LibreChat with Helm
helm upgrade --install librechat /tmp/LibreChat/helm/librechat \
  --namespace librechat \
  --values "$CUR_DIR/librechat-values.yaml"

```

**librechat-values.yaml**
```yaml
librechat:
  configEnv:
    PLUGIN_MODELS: "devstral:latest"
    DEBUG_LOGGING: "true"
    DEBUG_CONSOLE: "true"

  configYamlContent: |
    version: "1.2.5"
    interface:
      customWelcome: "Welcome to Altinity ClickHouse LLM Prototype! Enjoy your experience."
      endpointsMenu: true
      modelSelect: true
      parameters: true
      sidePanel: true
      presets: true
      prompts: true
      bookmarks: true
      multiConvo: true
      agents: true    
    endpoints:
      custom:
      - name: ollama
        baseURL: "http://ollama-srv-devstral.ollama-operator-system.svc.cluster.local:11434"
        models:
          default: [ 'devstral:latest' ]
        agentOptions:
          model: "devstral:latest"
  
    mcpServers:
      gateway:
        type: sse
        url: "http://gateway.gateway-system.svc.cluster.local:8080/sse"
        chatMenu: true
```

**librechat-rag-api-values.yaml**
```yaml
global:
  librechat:
    existingSecretName: ""
image:
  repository: danny-avila/librechat-rag-api-dev
  registry: ghcr.io
  pullPolicy: IfNotPresent
  tag: latest

rag:
  enabled: true
  configEnv:
    EMBEDDINGS_PROVIDER: ollama
    OLLAMA_BASE_URL: http://ollama-srv-graphite.ollama-operator-system.svc.cluster.local:11434/
    EMBEDDINGS_MODEL: granite-embedding:278m
```

all pods run

all `ollama` and `gateway` services available 
and `curl -vvv http://ollama-srv-graphite.ollama-operator-system.svc.cluster.local:11434/api/tags` return expected model description

librechat UI run on 3080 port
`kubectl port-forward -n librechat svc/librechat --address 0.0.0.0 3080`

i can login with user which create with npm run create-user
but any chat message return error

inside librchat logs i see only following

```
2025-05-29T11:16:31.504Z debug: Custom config:
{
  version: "1.2.5",
    interface.customWelcome: "Welcome to Altinity ClickHouse LLM Prototype! Enjoy your experience.",
    interface.endpointsMenu: true,
    interface.modelSelect: true,
    interface.parameters: true,
    interface.sidePanel: true,
    interface.presets: true,
    interface.prompts: true,
    interface.bookmarks: true,
    interface.multiConvo: true,
    interface.agents: true,
    // 1 custom(s)
    endpoints.custom: [{"name":"ollama","baseURL":"http://ollama-srv-devstral.ollama-operator-system.svc.cluster.local:11434... [truncated]],
    gateway.type: "sse",
    gateway.url: "http://gateway.gateway-system.svc.cluster.local:8080/sse",
    gateway.chatMenu: true,
}
2025-05-29T11:16:31.504Z debug: [MCP][gateway] Transport sending: {"method":"tools/list","jsonrpc":"2.0","id":3}

2025-05-29T11:19:21.145Z error: [handleAbortError] AI response error; aborting request: Agent not found
2025-05-29T11:19:21.146Z debug: [AgentController] Performing cleanup
2025-05-29T11:19:21.146Z debug: [AgentController] Cleanup completed
```

# which Agent shall I add to allow usage MCP+Ollama?

### Version Information

```
root@gpu-01:~# minikube image ls | grep libre
ghcr.io/danny-avila/librechat:v0.7.8
ghcr.io/danny-avila/librechat-rag-api-dev:latest
```

### Steps to Reproduce

* install ollama-operator + models
* install gateway database MCP server helm chart
* install librechat + librechat-rag-api helm charts

### Relevant log output

```shell
## cat ./api/logs/error-2025-05-29.log

{"level":"error","message":"[handleAbortError] AI response error; 
aborting request: Agent not found",
"stack":"Error: Agent not found
    at initializeClient (/app/api/server/services/Endpoints/agents/initialize.js:319:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async AgentController (/app/api/server/controlle
rs/agents/request.js:105:20)
    at async controller (/app/api/server/routes/agents/chat.js:27:3)"}
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by Slach** [comment]
i tried to capture traffic inside `librechat` container

i don't see any 11434 port related traffic
all `:8080/sse` traffic return 200 OK

**Comment by danny-avila** [comment]
@hofq can you look into this?

**Comment by Slach** [comment]
@danny-avila @hofq could you suggest what exactly wrong with my `librechat.yaml` ? how to properly define agent which will connect to gateway MCP and OLLAMA models?

**Comment by hofq** [comment]
i'm not familiar with mcp support in Librechat, but as there is no seperate container i don't see how this has anything to do with the helm chart.

Correct me if i'm wrong tho @danny-avila

**Reply by hofq** [reply]
configYaml is just parsed to the configmap and ConfigEnv as Environment variables. you should be able to adopt the docker-compose config. To access the Service you can just type the service's name as the chart does it for meilisearch. Should be just librechat by default without all the cluster domain stuff as you are in the same k8s namespace

Does mcp need a seperate port which is not open on the service?

**Reply by Slach** [reply]
> 2025-05-29T11:16:31.504Z debug: [MCP][gateway] Transport sending: {"method":"tools/list","jsonrpc":"2.0","id":3}

mcp deployed as SSE on separate endpoint in separate namespace 
and according to logs it successful works
```
2025-05-31T13:02:03.734Z info: [MCP] Initializing app-level servers
2025-05-31T13:02:03.735Z info: [MCP][gateway] Creating SSE transport: http://gateway.gateway-system.svc.cluster.local:8080/sse
2025-05-31T13:02:03.742Z debug: [MCP][gateway] Transport sending: {"method":"initialize","params":{"protocolVersion":"2024-11-05","capabilities":{},"clientInfo":{"name":"librechat-mc... [truncated]    
2025-05-31T13:02:03.750Z debug: [MCP][gateway] Transport sending: {"method":"notifications/initialized","jsonrpc":"2.0"}
2025-05-31T13:02:03.752Z info: [MCP][gateway] Capabilities: {"prompts":{"listChanged":true},"tools":{"listChanged":true}}
2025-05-31T13:02:03.752Z debug: [MCP][gateway] Transport sending: {"method":"tools/list","jsonrpc":"2.0","id":1}
2025-05-31T13:02:03.753Z info: [MCP][gateway] Available tools: discover_data, list_tables, prepare_query, query                                                                                          2025-05-31T13:02:03.754Z info: [MCP] Initialized 1/1 app-level server(s)                                                                                                                                 2025-05-31T13:02:03.754Z info: [MCP][gateway] ✓ Initialized                                                                                                                                              2025-05-31T13:02:03.754Z info: [MCP] All app-level servers initialized successfully                                                                                                                      2025-05-31T13:02:03.754Z debug: [MCP][gateway] Transport sending: {"method":"tools/list","jsonrpc":"2.0","id":2}
```

i asked nothing about MCP
i asked about error which happens after start of librechat daemon
when i type any message , i got following error
```
{"level":"error","message":"[handleAbortError] AI response error; 
aborting request: Agent not found",
"stack":"Error: Agent not found
    at initializeClient (/app/api/server/services/Endpoints/agents/initialize.js:319:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async AgentController (/app/api/server/controlle
rs/agents/request.js:105:20)
    at async controller (/app/api/server/routes/agents/chat.js:27:3)"}
```

which agent means here? how properly to define it in `configYamlContent` in helm value?


>  you should be able to adopt the docker-compose config.
I tried, but looks like I did something wrong
@hofq could you look to my `configYamlContent` config and confirm it looks correctly?

>  access the Service you can just type the service's name as the chart does it for meilisearch. Should be just librechat by default without all the cluster domain stuff as you are in the same k8s namespace

I don't see `librechat` service, only librechat-meilisearch, where i should add this service?
```
kubectl get svc -n librechat
NAME                                  TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)          AGE   SELECTOR
librechat-librechat                   ClusterIP      10.107.206.48    <none>        3080/TCP         22m   app.kubernetes.io/instance=librechat,app.kubernetes.io/name=librechat-librechat
librechat-meilisearch                 ClusterIP      10.97.210.187    <none>        7700/TCP         22m   app.kubernetes.io/instance=librechat,app.kubernetes.io/name=meilisearch
librechat-mongodb                     ClusterIP      10.104.32.223    <none>        27017/TCP        22m   app.kubernetes.io/component=mongodb,app.kubernetes.io/instance=librechat,app.kubernetes.io/name=mongodb
librechat-rag-api-librechat-rag-api   ClusterIP      10.109.124.113   <none>        8000/TCP         22m   app.kubernetes.io/instance=librechat-rag-api,app.kubernetes.io/name=librechat-rag-api-librechat-rag-api-rag
librechat-rag-api-postgresql          ClusterIP      10.109.5.83      <none>        5432/TCP         22m   app.kubernetes.io/component=primary,app.kubernetes.io/instance=librechat-rag-api,app.kubernetes.io/name=postgresql
librechat-rag-api-postgresql-hl       ClusterIP      None             <none>        5432/TCP         22m   app.kubernetes.io/component=primary,app.kubernetes.io/instance=librechat-rag-api,app.kubernetes.io/name=postgresql
```

Could you provide librechat.yaml part where i can define meilisearch or something which related to agent?

**Reply by Slach** [reply]
@hofq @danny-avila 
![image](https://github.com/user-attachments/assets/e09e5dbf-8dcb-4ca2-8aba-abab9de1ff2e)
could you look to my `configYamlContent`?

**Reply by hofq** [reply]
ment libresearch-libresearch. I don't see how this is an helm issue.

**Reply by Slach** [reply]
@hofq ok. this is maybe not helm chart related issue

guys, could you try look to my config and just suggest what i did get wrong? or it will just silence instead of answers?

**Reply by Slach** [reply]
@hofq @danny-avila how to setup agent in librechat.yaml properly? why provided helm chart can't

why following librechat.yaml config
```
endpoints:
  agents:
    disableBuilder: false
    maxRecursionLimit: 100
    recursionLimit: 50
  custom:
  - agentOptions:
      model: devstral:latest
    baseURL: http://ollama-srv-devstral.ollama-operator-system.svc.cluster.local:11434
    models:
      default:
      - devstral:latest
    name: ollama
interface:
  agents: true
  bookmarks: true
  customWelcome: Welcome to Altinity ClickHouse LLM Prototype! Enjoy your experience.
  endpointsMenu: true
  modelSelect: true
  multiConvo: true
  parameters: true
  presets: true
  prompts: true
  sidePanel: true
mcpServers:
  gateway:
    chatMenu: true
    type: sse
    url: http://gateway.gateway-system.svc.cluster.local:8080/sse
version: 1.2.5
```
always
return
```
{"level":"error","message":"[handleAbortError] AI response error; 
aborting request: Agent not found",
"stack":"Error: Agent not found
    at initializeClient (/app/api/server/services/Endpoints/agents/initialize.js:319:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async AgentController (/app/api/server/controlle
rs/agents/request.js:105:20)
    at async controller (/app/api/server/routes/agents/chat.js:27:3)"}
```
