### DISCUSSION TITLE
Perplexity Ai not showing

### DISCUSSION THREAD

**Discussion by youvnor** [danny-avila/LibreChat#7781] [General]
I'm encountering an issue setting up a custom Perplexity endpoint in LibreChat, and despite following the documentation and troubleshooting steps, it doesn't appear in the UI.

Problem Description:
I have configured Perplexity as a custom endpoint in my librechat.yaml and enabled custom in my .env ENDPOINTS variable. The LibreChat application starts without any errors related to the librechat.yaml configuration. However, the Perplexity option does not show up in the model selection menu in the LibreChat UI.

My Environment:

LibreChat Version: last
Deployment Method: Docker Compose
Operating System: Debian bookworm
Configuration Details:

librechat.yaml (relevant snippet):

```
custom:
      Perplexity:
      #- name: "Perplexity"
        apiKey: "${PERPLEXITY_API_KEY}"
        baseURL: "https://api.perplexity.ai/"
        models:
          default: [
            #"sonar-deep-research",
            #"sonar-reasoning-pro",
            #"sonar-reasoning",
            #"sonar-pro",
            "sonar"
            ]
          fetch: false # fetching list of models is not supported
        titleConvo: true
        titleModel: "current_model"
        forcePrompt: false
        titleMessageRole: "user"
        modelDisplayLabel: "Perplexity"
        dropParams: ["stop", "user", "frequency_penalty", "presence_penalty"]
```

.env (relevant snippet for ENDPOINTS):
ENDPOINTS=openAI,google,anthropic,custom,agents

Troubleshooting Steps Taken:
YAML Syntax: Confirmed the librechat.yaml syntax is correct.
.env Configuration: Ensured custom is included in ENDPOINTS.
API Key Verification: The PERPLEXITY_API_KEY is set in my .env file and verified to be correct and active by testing it directly via curl to https://api.perplexity.ai/chat/completions.
Log Analysis: Checked LibreChat Docker container logs during startup. There are no explicit error messages

Expected Behavior:
I expect "Perplexity" to appear as a selectable option in the LibreChat UI's model dropdown menu.

Actual Behavior:
The Perplexity endpoint does not appear in the UI.

**Comment by youvnor** [comment]
Adding some more context to the issue.

For the LibreChat installation, I followed the official guide for Docker on Linux, which can be found here:
https://www.librechat.ai/docs/remote/docker_linux

I'm also attaching my complete librechat.yaml file below, hoping it can be helpful for analysis:

```
version: 1.2.1
cache: true

fileConfig:
  endpoints:
    google:
      fileLimit: 5
      fileSizeLimit: 25
      totalSizeLimit: 50
    openAI:
      disabled: false
      fileLimit: 5
      fileSizeLimit: 25
      totalSizeLimit: 50
    custom:
      Perplexity:
      #- name: "Perplexity"
        apiKey: "${PERPLEXITY_API_KEY}"
        baseURL: "https://api.perplexity.ai/"
        models:
          default: [
            #"sonar-deep-research",
            #"sonar-reasoning-pro",
            #"sonar-reasoning",
            #"sonar-pro",
            "sonar"
            ]
          fetch: false # fetching list of models is not supported
        titleConvo: true
        titleModel: "current_model"
        forcePrompt: false
        titleMessageRole: "user"
        modelDisplayLabel: "Perplexity"
        dropParams: ["stop", "user", "frequency_penalty", "presence_penalty"]
    default:
      totalSizeLimit: 25
      serverFileSizeLimit: 1000
      avatarSizeLimit: 2
webSearch:
  # Search Provider Configuration
  serperApiKey: "${SERPER_API_KEY}"
  searchProvider: "serper" # Options: "serper", "searxng"

  # Scraper Configuration
  firecrawlApiKey: "${FIRECRAWL_API_KEY}"
  #firecrawlApiUrl: "${FIRECRAWL_API_URL}"
  scraperType: "firecrawl" # Options: "firecrawl", "serper"

  # Reranker Configuration
  jinaApiKey: "${JINA_API_KEY}"
  #cohereApiKey: "${COHERE_API_KEY}"
  rerankerType: "jina" # Options: "jina", "cohere"

  # General Settings
  scraperTimeout: 7500 # Timeout in milliseconds for scraper requests (default: 7500)
  safeSearch: 0 # Options: 0 (OFF), 1 (MODERATE - default), 2 (STRICT)
mcpServers:
  n8n:
    url: https://d360connect.app.n8n.cloud/mcp/xxxxxxxxxxxxxxx
```
