### DISCUSSION TITLE
[Custom Endpoints] fileConfig.endpoints.custom array structure not supported in release images (incorrect config)

### DISCUSSION THREAD

**Discussion by youvnor** [danny-avila/LibreChat#7799] [Troubleshooting] [answered]
### What happened?

Describe the bug

When attempting to configure a custom endpoint (e.g., Perplexity) via fileConfig.endpoints.custom in librechat.yaml, the application throws a Zod schema validation error if custom is defined as an array (the documented, correct method).

Zod validation error:
```
{
  "code": "invalid_type",
  "expected": "object",
  "received": "array",
  "path": ["fileConfig", "endpoints", "custom"],
  "message": "Expected object, received array"
}
```

**Version info**
LibreChat Version: latest (ghcr.io/danny-avila/librechat-dev-api:latest)
Deployment: Docker Compose (official docs for Linux)
OS: Debian bookworm

Relevant config (redacted):
```
fileConfig:
  endpoints:
    custom:
      - name: "Perplexity"
        apiKey: "${PERPLEXITY_API_KEY}"
        baseURL: "https://api.perplexity.ai/"
        models:
          default: ["sonar"]
          fetch: false
        modelDisplayLabel: "Perplexity"
```

```
ENDPOINTS=openAI,google,anthropic,custom,agents
PERPLEXITY_API_KEY=xxxx
```

I opened a discussion about it:
https://github.com/danny-avila/LibreChat/discussions/7781

Additional context

At the moment I am unable to build the project from source in my current environment, but I will provide feedback as soon as I am able to test in a fresh environment. Should you require tests or logs from a newly built setup, please let me know and I'll prioritize that.

### Version Information

ghcr.io/danny-avila/librechat-dev-api            latest          ec732384bd62   3 days ago      1.12GB
ghcr.io/danny-avila/librechat                    latest          17cfdb1df083   4 weeks ago     1.02GB
ghcr.io/danny-avila/librechat-rag-api-dev-lite   latest          e7da8e6aca0f   4 weeks ago     1.31GB

### Steps to Reproduce

1. Use ghcr.io/danny-avila/librechat-dev-api:latest image.
2. Configure fileConfig.endpoints.custom as array (per documentation).
3. Start the server.
4. Observe Zod validation error.

### Relevant log output

```shell
{"level":"error","message":"Invalid custom config file at /app/librechat.yaml:\n{\n  "issues": [\n    {\n      "code": "invalid_type",\n      "expected": "object",\n      "received": "array",\n      "path": [\n        "fileConfig",\n        "endpoints",\n        "custom"\n      ],\n      "message": "Expected object, received array"\n    }\n  ],\n  "name": "ZodError"\n}"}
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment, marked as answer]
Hi @youvnor 

You are confusing the [endpoints config](https://www.librechat.ai/docs/configuration/librechat_yaml/object_structure/config#endpoints) with the [`fileConfig` object structure](https://www.librechat.ai/docs/configuration/librechat_yaml/object_structure/file_config).

They are slightly different in schema, but serve very different purposes. You do not define custom endpoints under `fileConfig`.

Here's a working YAML file using both, note the distinctions. `fileConfig` is for setting file parameters (and note that it only supports defining blanket settings to `custom` instead of individual custom endpoints, i.e. `Perplexity`
```yaml
endpoints:
  custom:
    - name: "Perplexity"
      apiKey: "${PERPLEXITY_API_KEY}"
      baseURL: "https://api.perplexity.ai/"
      models:
        default:
          - "sonar-reasoning-pro"
          - "sonar-reasoning"
          - "sonar-pro"
          - "sonar"
        fetch: false
      titleConvo: true
      titleModel: "current_model"
      forcePrompt: false
      titleMessageRole: "user"
      modelDisplayLabel: "Perplexity"
      dropParams: ["stop", "user", "frequency_penalty", "presence_penalty"]
fileConfig:
  endpoints:
    default:
      fileLimit: 5
      fileSizeLimit: 1024
      totalSizeLimit: 10240
      supportedMimeTypes:
        - "image/.*"
        - "text/.*"
        - "application/.*"
        - "application/x-sh"
    custom:
      fileLimit: 2
      fileSizeLimit: 1024  # Maximum size for an individual file in MB
      totalSizeLimit: 10240  # Maximum total size for all files in a single request in MB
      supportedMimeTypes:
        - "text/.*"
        - "application/.*"
        - "application/x-sh"
```
