### DISCUSSION TITLE
Help setting up WebSearch

### DISCUSSION THREAD

**Discussion by nathanwong91** [danny-avila/LibreChat#7827] [Help Wanted]
Looking to get websearch going in our environment but while there is documentation its not clear enough for me. One question first:

- is WebSearch only available to Agents? As we don't have any agents but use ModelSpecs

When I try using an agent I do see the option for WebSearch
<img width="302" alt="image" src="https://github.com/user-attachments/assets/ddcb8296-f7bd-479c-8a1f-b1e6d9ce8a43" />
It's enabled and I've provided the API keys as well both via code and via the UI but all I get is a blank reply and there are no errors in pod logs (app is deployed on kubernetes)
<img width="515" alt="image" src="https://github.com/user-attachments/assets/4a4bbe8c-1c64-404d-8a52-a1857561c18f" />
If would be good if we can use them via ModelSpecs as I'm still waiting for Agents to be configurable via Code (I know it's being worked on).
Here's bits of code that might be relevant
```
    interface:
      agents: true
      webSearch: true
    endpoints:
      agents:
        allowedProviders:
          - "litellm-proxy"
        recursionLimit: 50
        maxRecursionLimit: 100
        disableBuilder: false
        capabilities:
          - "web_search"
    webSearch:
      serperApiKey: "${SERPER_API_KEY}"
      firecrawlApiKey: "${FIRECRAWL_API_KEY}"
      jinaApiKey: "${JINA_API_KEY}"
      searchProvider: "serper"
      scraperType: "firecrawl"
      rerankerType: "jina"
      scraperTimeout: 7500
      safeSearch: 1
```
We serve all the models via LiteLLM. That has an option to enable Google Search for Vertex AI Gemini Models which works fine but I want to get websearch for other models through Librechat. Would Litellm be the issue here?
