### DISCUSSION TITLE
AzureOpenAI Assistant - Can't read uploaded files

### DISCUSSION THREAD

**Discussion by magnurgit** [danny-avila/LibreChat#7828] [Help Wanted]
I'm fairly new to Librechat, and setting this up has been a yourney, let me tell you!
My big focus in all this was to get it working with AzureOpenAI instead og regular OpenAI.
I've finally firgured that stuff out, and spun up some models via our Azure pages.
The regular models are working just fine, but i'm having a hard time gettings assistants to be able to read files.
It seems like the files are not stored properly, or that the assistant does not have access to them because of read/write properties.
I'm not sure to be honest. 

Can anyone give me some tips. I'm stuck!

I'm running Librechat in Docker via a Digital Ocean server.
I would paste my docker logs, but there ain't much going on there while using the assistant and uploading files.
The best clues i've found was talking to the assistant itself:

It keeps saying this:
`# Let's take a look at the uploaded files to identify the content for review and correction.
msearch()

# Let's fetch the list of uploaded files to identify the document provided by the user.
uploaded_files = !ls /mnt/data
uploaded_files`

And than tells me it cannot find the file i've uploaded.

This is my librechat.yml:

```
version: 1.0.5
cache: true

endpoints:
  azureAssistants:
    capabilities: ["code_interpreter", "actions", "tools", "retrieval"]
  azureOpenAI:
    assistants: true
    titleConvo: true
    titleModel: gpt-35-turbo

    groups:
      - group: "groupOne"
        apiKey: "${API_KEY}"
        instanceName: "myInstance"
        version: "2024-12-01-preview"
        assistants: true

        models:
          gpt-4o:
            deploymentName: gpt-4o
            version: "2024-12-01-preview"
          gpt-4.1:
            deploymentName: gpt-4.1
            version: "2024-12-01-preview"
          o3-mini:
            deploymentName: o3-mini
            version: "2024-12-01-preview"
          gpt-4o-mini:
            deploymentName: gpt-4o-mini
            version: "2024-12-01-preview"
          gpt-35-turbo:
            deploymentName: gpt-35-turbo
            version: "2024-12-01-preview"

```

If you need additional information, tell me and i'll keep an eye on this discussion to update when needed.
