### DISCUSSION TITLE
Bedrock promptPrefix in modelSpec (librechat.yml)

### DISCUSSION THREAD

**Discussion by swarmaero-it** [danny-avila/LibreChat#7946] [Troubleshooting] [answered]
### What happened?

Describe the bug
When using modelSpecs in librechat.yaml, the promptPrefix field works correctly for openAI and azureOpenAI endpoints — injecting the prefix as a system message. However, when using a bedrock endpoint (e.g., amazon.nova-pro-v1:0 or anthropic.claude-*), the promptPrefix is silently ignored and not included in the conversation context.

Expected behavior
The promptPrefix should be applied to the first message in the conversation, same as it is for OpenAI-backed models. This is especially important for structured prompt injection use cases.

Proposed fix (optional)
Ensure promptPrefix is prepended to the initial message or added to the system context regardless of model provider, ideally in a unified controller location before calling generate().

### Version Information

ubuntu@i-0fc80bc0f43aea0b1:/LibreChat/LibreChat$ docker images | grep librechat
ghcr.io/danny-avila/librechat-dev-api            latest           acde1376ced6   6 weeks ago     1.09GB
ghcr.io/danny-avila/librechat-dev                latest           7440a8b751db   6 weeks ago     950MB
ghcr.io/danny-avila/librechat-rag-api-dev-lite   latest           817faebddae9   2 months ago    1.31GB
ubuntu@i-0fc80bc0f43aea0b1:/LibreChat/LibreChat$

### Steps to Reproduce

Define a bedrock model in modelSpecs with a promptPrefix in the preset

Start a new chat session with that model

Observe that the prefix is not applied (check system messages, behavior, or logs)

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
I don't see any relevant logs
```

### Screenshots

![Image](https://github.com/user-attachments/assets/05e32994-3303-4f0f-b9f9-da527b15d645)
![Image](https://github.com/user-attachments/assets/c5bd03fe-9266-4273-92af-321cf6056beb)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment, marked as answer]
You won't see it in the UI, but it still works:
```yaml
modelSpecs:
  enforce: false
  prioritize: true
  addedEndpoints: ["agents"]
  list:
  - name: "Bedrock Sonnet 4"
    label: "Bedrock Sonnet 4"
    iconURL: "bedrock"
    description: "Smart, Efficient Conversational AI"
    default: false
    preset:
      endpoint: "bedrock"
      model: "us.anthropic.claude-sonnet-4-20250514-v1:0" # actual model label
      modelLabel: "Bedrock Sonnet 4"
      promptPrefix: "End every message with [END]"
```

![chrome_OTLdozi5Ib](https://github.com/user-attachments/assets/cae7bd24-5b00-4a82-9dd4-7b61c851927d)
