### DISCUSSION TITLE
Title generation

### DISCUSSION THREAD

**Discussion by mazierovictor** [danny-avila/LibreChat#7957] [General]
How to change the model for generating agent titles, so that it does not use the agent model, but rather a gpt4.1-nano, for example?

**Comment by exousia-doxa** [comment]
In `librechat.yaml`:
[Link](https://www.librechat.ai/docs/configuration/librechat_yaml/object_structure/custom_endpoint#titlemodel)

In `.env` (but this configuration is depricated):
[Link](https://www.librechat.ai/docs/configuration/dotenv#openai)

**Reply by mazierovictor** [reply]
@exousia-doxa 

Let me get this straight.

I need to configure OpenAI as a Custom Endpoint to define the title generation engine. And does this apply to agents?

**Reply by exousia-doxa** [reply]
@mazierovictor

Same setup as mine. When you choose a provider for your agent, it includes all the settings from the Custom Endpoint you’ve created, as well as the titleModel.

Example of my `librechat.yaml`:
```
endpoints:
  custom:
    - name: "OpenAI"
      apiKey: "${OPENAI_API_KEY}"
      baseURL: "https://api.openai.com/v1"
      iconURL: "https://raw.githubusercontent.com/danny-avila/LibreChat/0103b4b08a6ee1339569d7d4af16beaaac0228ed/client/public/assets/openai.svg"
      models:
        default: ["gpt-4.1-mini"]
        fetch: true
      titleConvo: true
      titleModel: "gpt-4.1-mini"
      summarize: true
      summaryModel: "gpt-4.1-mini"
      modelDisplayLabel: "OpenAI"
```
![image](https://github.com/user-attachments/assets/41bd9b09-70d8-4c8e-a019-ca6ca5932eae)
