### DISCUSSION TITLE
GPT Image 1 using an Azure Provisioned Model.

### DISCUSSION THREAD

**Discussion by kjanssens-ili** [danny-avila/LibreChat#7971] [Feature Requests & Suggestions]
### What features would you like to see added?

Since the previous discussion has been answered as 'answered', i would like to know if there is going the be a feature coming soon where the tool (in agent builder): OpenAI Image Tools allows an Azure API key to generate images. Or if there is going to be a different tool to allow me to generate images using the Azure gpt-image-1 model

### More details

It would be nice to generate images using the Azure GPT-image-1 model. If it's already possible, i'm sorry, please let me know how!

### Which components are impacted by your request?

No response

### Pictures

No response

### Code of Conduct

- [x]  I agree to follow this project's Code of Conduct

**Comment by aekusal** [comment]
I have tried every way known to man to get this to work, tried every suggestion 10 pages deep into Google results, and at this point I am thoroughly convinced gpt-image-1 does not work with Azure OpenAI

**Comment by jsiegmund** [comment]
Following the docs, I got stuck on the part where I need to add the "OpenAI Image Tools" to my agent. The tools pop-up I'm getting doesn't contain that tool, only DALL-E-3, Stable Diffusion and others not image related. Have you guys succeeded in doing that?

**Reply by jsiegmund** [reply]
To answer my own question; this was caused by use of an older image version. Upgrading to the latest version (refer to the upgrade guide in the LibreChat docs) resolved this issue. That said, I still can't generate images successfully.

**Comment by jimmyland22** [comment]
It works for me. You have to add these setting into the .env before that tool shows up.
IMAGE_GEN_OAI_API_KEY=
IMAGE_GEN_OAI_BASEURL=
IMAGE_GEN_OAI_AZURE_API_VERSION=2025-04-01-preview

**Reply by jsiegmund** [reply]
That's very strange. I have these same parameters in my env: 

```
IMAGE_GEN_OAI_API_KEY=<key>
IMAGE_GEN_OAI_BASEURL=https://<instance>-resource.cognitiveservices.azure.com/openai/deployments/gpt-image-1/
IMAGE_GEN_OAI_AZURE_API_VERSION=2025-04-01-preview
```

I've created an agent in LibreChat using the OpenAI Image tools, but when I give it any prompt it takes a while and then comes back with: 

`Something went wrong. Here's the specific error message we encountered: An error occurred while processing the request: Connection error.`

**Reply by alexff77** [reply]
I used this URL on [LibreChat v0.7.9-rc1] and it worked
yourdeployment.openai.azure.com/openai/deployments/gpt-image-1/
even though on Azure I have URL like yours.

I have another issue, when I add the tool to the agent it still asks me for API key even though I have 
IMAGE_GEN_OAI_API_KEY=<key>
 variable setup.
Any ides on this?

**Reply by jimmyland22** [reply]
Hmm, not really sure. I have that same exact setting, and clicking on + for the tool just enables it and it never prompted me for anything.

**Comment by akusalconmet** [comment]
I am hopeful someone can point out my mistake, I have spent days trying to get this to work. 

Here is a sanitized version of librechat.yaml with the relevant configuration:

```
interface:
  endpointsMenu: true
  modelSelect: true
  parameters: true
  sidePanel: true
  presets: true
  prompts: true
  bookmarks: true
  multiConvo: true
  agents: true
  runCode: false

endpoints:
  azureAssistants:
    privateAssistants: true
  agents:
    disableBuilder: false
  azureOpenAI:
    assistants: true
    plugins: true
    titleConvo: true
    titleModel: 'gpt-4.1'
    summarize: true
    summaryModel: 'gpt-4.1'
    groups:
      - group: 'openai_models'
        apiKey: '${AZURE_OPENAI_API_KEY}'
        instanceName: '<redacted name>-OpenAI-Models'
        version: '2025-01-01-preview'
        assistants: false
        models:
          gpt-5:
            deploymentName: 'gpt-5-chat'
            version: '2025-01-01-preview'
          gpt-4.1:
            deploymentName: 'gpt-4.1'
            version: '2025-01-01-preview'
      - group: "azure-image-generation"
        apiKey: '${IMAGE_GEN_OAI_API_KEY}'
        instanceName: '<redacted>-Image-Generation'
        assistants: true
        models:
          gpt-4o:
            deploymentName: "gpt-4o"
            version: "2025-01-01-preview"
```

Here is .env:

```
ENDPOINTS=azureOpenAI,azureAssistants

# OpenAI Image Tools Customization
#----------------
IMAGE_GEN_OAI_API_KEY=${IMAGE_GEN_OAI_API_KEY}
IMAGE_GEN_OAI_BASEURL=<redacted>.openai.azure.com/openai/deployments/gpt-image-1/
IMAGE_GEN_OAI_AZURE_API_VERSION=2025-04-01-preview

```

Here is my interface with this loaded up:

I can see Azure Assistants:
<img width="643" height="218" alt="image" src="https://github.com/user-attachments/assets/1fb95e5d-6c5b-43da-b695-bf4b64878f7c" />

This is the assistant configuration with OpenAI Image Tools selected:
<img width="484" height="1510" alt="image" src="https://github.com/user-attachments/assets/da60bb26-a847-4547-a292-fd2376e93bda" />

A query returns a prompt, not an image:
<img width="1047" height="436" alt="image" src="https://github.com/user-attachments/assets/fff27c5e-7ae9-4f76-84e6-d4f9bf48cc2c" />

Error in the logs:
<img width="1049" height="114" alt="image" src="https://github.com/user-attachments/assets/2488a457-bbb0-4cb6-b89d-f904eb944f3b" />
```
LibreChat         | 2025-08-22 21:27:49 error: Error loading tool image_gen_oai: This tool is only available for agents.
LibreChat         | 2025-08-22 21:27:49 error: [/assistants/chat/] 400 Invalid type for 'tool_outputs': expected an array of objects, but got an object instead.

```

As a Sanity check, the following works and returns b64 image data:

```
curl -s -X POST \
  "https://<redacted>.openai.azure.com/openai/deployments/gpt-image-1/images/generations?api-version=2025-04-01-preview" \
  -H "Content-Type: application/json" \
  -H "api-key: ${IMAGE_GEN_OAI_API_KEY}" \
  -d '{
        "prompt": "A frog in a top hat",
        "model": "gpt-image-1",
        "size": "1024x1024",
        "n": 1,
        "quality": "high"
      }'
```

Any help is greatly appreciated!
