### DISCUSSION TITLE
[Enhancement]: Replace python 3.12 for 3.13 in image

### DISCUSSION THREAD

**Discussion by lesandie** [danny-avila/LibreChat#7984] [Feature Requests & Suggestions]
### What features would you like to see added?

In my case clickhouse-mcp server uses python 3.13 and I wanted to add  it to the mcp server list, but I get the error by uv that python 3.13 is a req.

### More details

It is nice that uv is included in the image already, and including python 3.13 would be awesome.

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
I'm able to specify python 3.13 like this (using docker):
```yaml
mcpServers:
  fetch:
      command: uvx
      args:
        - "--python"
        - "3.13"
        - "mcp-server-fetch"
```

seems to work!

logs:
```bash
LibreChat         | Downloading cpython-3.13.3-linux-x86_64-musl (download) (26.9MiB)
LibreChat         | 2025-06-20 00:27:28 info: [MCP][spotify] Instructions not included (serverInstructions not configured)
LibreChat         | 2025-06-20 00:27:28 info: [MCP][spotify] Capabilities: {"tools":{"listChanged":true}}
LibreChat         | 2025-06-20 00:27:28 info: [MCP][spotify] Available tools: searchTracks, searchArtists, searchAlbums, searchPlaylists, getCurrentUserProfile, getCurrentPlayback, pausePlayback, resumePlayback, skipToNext, skipToPrevious, getUserPlaylists, getPlaylistTracks, createPlaylist, addTracksToPlaylist, getRecentlyPlayed, getTopTracks, getTopArtists
LibreChat         |  Downloading cpython-3.13.3-linux-x86_64-musl (download)
LibreChat         | Downloading lxml (4.8MiB)
LibreChat         | Downloading pydantic-core (2.1MiB)
LibreChat         |  Downloading pydantic-core
LibreChat         |  Downloading lxml
LibreChat         | Installed 35 packages in 67ms
LibreChat         | realpath: --: No such file or directory
LibreChat         | 2025-06-20 00:27:33 info: [MCP][fetch] Instructions not included (serverInstructions not configured)
LibreChat         | 2025-06-20 00:27:33 info: [MCP][fetch] Capabilities: {"experimental":{},"prompts":{"listChanged":false},"tools":{"listChanged":false}}
LibreChat         | 2025-06-20 00:27:33 info: [MCP][fetch] Available tools: fetch
LibreChat         | 2025-06-20 00:27:33 info: [MCP] Initialized 2/2 app-level server(s)
LibreChat         | 2025-06-20 00:27:33 info: [MCP][spotify] ✓ Initialized
LibreChat         | 2025-06-20 00:27:33 info: [MCP][fetch] ✓ Initialized
LibreChat         | 2025-06-20 00:27:33 info: [MCP] All app-level servers initialized successfully
LibreChat         | 2025-06-20 00:27:33 info: MCP servers initialized successfully
```

**Comment by RemcoE33** [comment]
@danny-avila 

I'm trying to install the [Klaviyo MCP](https://developers.klaviyo.com/en/docs/klaviyo_mcp_server) with no luck. I don't see 3.13 being installed in the logging. 

```yaml
  klaviyo:
    type: stdio
    command: uvx
    args:
      - "--python"
      - "3.13"
      - klaviyo-mcp-server@latest
    env:
      PRIVATE_API_KEY: "${KLAVIYO_TOKEN}"
      READ_ONLY: "true"
      ALLOW_USER_GENERATED_CONTENT: "false"
    serverInstructions: true
    chatMenu: true
```

When I docker exc:

```bash
/app # echo '{ "jsonrpc": "2.0", "id": "1", "method": "initialize", "params": {} }' | uvx klaviyo-mcp-server@latest
  x No solution found when resolving tool dependencies:
  `-> Because the current Python version (3.12.11) does not satisfy Python>=3.13 and all versions of klaviyo-mcp-server depend on Python>=3.13, we can conclude that all versions of klaviyo-mcp-server cannot be used.
      And because you require klaviyo-mcp-server, we can conclude that your requirements are unsatisfiable.
/app # echo '{ "jsonrpc": "2.0", "id": "1", "method": "initialize", "params": {} }' | uvx --python 3.13 klaviyo-mcp-server@latest
error: No interpreter found for Python 3.13 in managed installations or search path
/app #
```

Is there something i'm doing wrong?
