### DISCUSSION TITLE
azureOpenAI Configuration Rejected in Main Branch

### DISCUSSION THREAD

**Discussion by scgreenhalgh** [danny-avila/LibreChat#8063] [Troubleshooting]
### What happened?

# Bug Report: azureOpenAI Configuration Rejected in Main Branch

## What happened?

When using the main branch Docker image (`ghcr.io/danny-avila/librechat-dev-api:latest`), the `azureOpenAI` endpoint configuration in `librechat.yaml` is rejected with the error:

```
Unrecognized key(s) in object: 'azureOpenAI'
```

This occurs even though `azureOpenAI` is a documented and valid endpoint type. The same configuration works correctly with the latest stable release (`ghcr.io/danny-avila/librechat:latest`).

**Expected behavior**: The azureOpenAI endpoint configuration should be accepted and parsed correctly, as it is defined in the schema at `packages/data-provider/src/config.ts`.

## Version Information

```
# Working version:
ghcr.io/danny-avila/librechat:latest

# Broken version:
ghcr.io/danny-avila/librechat-dev-api:latest
```

## What browsers are you seeing the problem on?

N/A - This is a backend configuration issue

## Relevant log output

```shell
# Error from api container logs:
2025-06-26 03:16:33 error: Invalid custom config file at /app/librechat.yaml [
  {
    "code": "unrecognized_keys",
    "keys": [
      "azureOpenAI"
    ],
    "path": [
      "endpoints"
    ],
    "message": "Unrecognized key(s) in object: 'azureOpenAI'"
  },
  {
    "code": "unrecognized_keys",
    "keys": [
      "interface",
      "fileConfig"
    ],
    "path": [],
    "message": "Unrecognized key(s) in object: 'interface', 'fileConfig'"
  }
]

# Root cause identified in code:
# File: api/server/services/Config/loadCustomConfig.js, line 71:
const result = configSchema.strict().safeParse(customConfig);

# The .strict() call rejects any unrecognized keys, but the schema definition appears correct
# in packages/data-provider/src/config.ts (line 738):
[EModelEndpoint.azureOpenAI]: azureEndpointSchema.optional(),
```

## Additional Context

Investigation shows:
1. The `configSchema` in `packages/data-provider/src/config.ts` includes `azureOpenAI` at line 738
2. The schema is parsed with `.strict()` in `loadCustomConfig.js` line 71
3. This suggests either:
   - The schema isn't being properly imported/compiled in the main branch build
   - There's a build/bundling issue causing the schema definition to be incomplete
   - The Docker image for main branch has an outdated version of the data-provider package

The same configuration works perfectly with the stable release, indicating this is a regression in the main branch.

## Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Version Information

ghcr.io/danny-avila/librechat-dev                latest          b41808f0f197   16 months ago   1.42GB
librechat-client                                 latest          ff8e078bb80d   16 months ago   22.8MB
ghcr.io/danny-avila/librechat-dev-api            latest          2ab937d01895   16 months ago   1.12G

### Steps to Reproduce

1. Create a `librechat.yaml` file with azureOpenAI configuration:
```yaml
version: 1.2.5
endpoints:
  custom: []
  azureOpenAI:
    titleModel: "gpt-4.1-mini"
    plugins: false
    assistants: false
    groups:
      - group: "eastus2"
        apiKey: "${AZURE_EAST_US2_API_KEY}"
        instanceName: "angelflow-azure-openai-eastus2"
        version: "2025-01-01-preview"
        models:
          gpt-4.1:
            deploymentName: "gpt-4.1"
```

2. Run with the main branch Docker image:
```bash
docker compose up -d
```

3. The API container will fail to start with the validation error shown above.

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
2025-06-26T00:58:13.763Z debug: [requireLocalAuth] Error: No user
2025-06-26T03:15:57.057Z debug: [indexSync] Clearing sync timeouts before exiting...
2025-06-26 03:16:29 info: [Optional] Redis not initialized. Note: Redis support is experimental.
2025-06-26 03:16:33 info: Connected to MongoDB
2025-06-26 03:16:33 debug: [indexSync] There are 677 messages in the database, 677 indexed
2025-06-26 03:16:33 debug: [indexSync] There are 85 convos in the database, 85 indexed
2025-06-26 03:16:33 error: Invalid custom config file at /app/librechat.yaml [
  {
    "code": "unrecognized_keys",
    "keys": [
      "azureOpenAI"
    ],
    "path": [
      ... [truncated]
2025-06-26 03:16:33 info: Server listening on all interfaces at port 3080. Use http://localhost:3080 to access it
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Looking at your error message, the issue isn't with `azureOpenAI` itself. The key clue is in the second error: `"interface", "fileConfig"` at the root level.

`interface` and `fileConfig` are root-level configuration options that should be at the top of your YAML file, not nested under `azureOpenAI` or any other endpoint.

Your file structure should look like this:

```yaml
version: 1.2.5
# Root-level configs (if you have them)
interface:
  # interface settings
fileConfig:
  # file config settings

endpoints:
  azureOpenAI:
    # your azureOpenAI config here
```

The `.strict()` validation in the main branch is now properly enforcing schema structure, catching configuration issues that were silently ignored in the stable release.

Could you share your complete YAML structure (with sensitive values redacted) to confirm this is the issue?

**Reply by danny-avila** [reply]
see for more info:
https://www.librechat.ai/docs/configuration/librechat_yaml/object_structure/config

**Comment by scgreenhalgh** [comment]
I performed a fair amount of testing with only the `azureOpenAi` configuration in the `librechat.yml` file, and I still encountered the same issue. I just put this error from running my current config with the `ghcr.io/danny-avila/librechat-dev-api:latest` branch.

Running the most basic `librechat.yml` with only the `azureOpenAi` config and my oAuth login i get this error:
```
LibreChat-API  | 2025-06-26 04:29:16 error: Invalid custom config file at /app/librechat.yaml [
LibreChat-API  |   {
LibreChat-API  |     "code": "unrecognized_keys",
LibreChat-API  |     "keys": [
LibreChat-API  |       "azureOpenAI"
LibreChat-API  |     ],
LibreChat-API  |     "path": [
LibreChat-API  |       "endpoints"
LibreChat-API  |     ],
LibreChat-API  |     "message": "Unrecognized key(s) in object: 'azureOpenAI'"
LibreChat-API  |   }
LibreChat-API  | ]
LibreChat-API  | 2025-06-26 04:29:16 info: Server listening on all interfaces at port 3080. Use http://localhost:3080 to access it
```

**Reply by scgreenhalgh** [reply]
here is the config file with issues:

```
# Configuration version (required)
version: 1.2.5

# Cache settings: Set to true to enable caching
cache: true

# Interface configuration - CAUSES ERROR IN MAIN BRANCH
interface:
  agents: true
  runCode: false
  # Privacy policy settings
  privacyPolicy:
    externalUrl: 'https://example.com/privacy-policy'
    openNewTab: true

  # Terms of service
  termsOfService:
    externalUrl: 'https://example.com/terms'
    openNewTab: true
    modalAcceptance: true
    modalTitle: "Terms of Service"
    modalContent: |
      # Example Terms of Service
      
      This is example content for the terms of service modal.
      
      By clicking "Accept" or using our services, you acknowledge that you have read, understood, and agree to be bound by these Terms of Service.

# Example Registration Object Structure (optional)
registration:
  socialLogins: ["google"]

# Endpoints configuration
endpoints:
  custom: []
  azureOpenAI:
    titleModel: "gpt-4-turbo"
    plugins: false
    assistants: false
    groups:
      - group: "example-region"
        apiKey: "${AZURE_API_KEY}"
        instanceName: "example-azure-openai-instance"
        version: "2025-01-01-preview"
        models:
          gpt-4:
            deploymentName: "gpt-4"
          gpt-4-turbo:
            deploymentName: "gpt-4-turbo"
          gpt-3.5-turbo:
            deploymentName: "gpt-3.5-turbo"
```
