### DISCUSSION TITLE
Supported mimetypes

### DISCUSSION THREAD

**Discussion by mansiibm** [danny-avila/LibreChat#8077] [Troubleshooting]
Hi for my anthropic endpoint in file config I had the supported mime types set as follows- 

![Image](https://github.com/user-attachments/assets/ce852495-4785-4015-bd39-f239764e86ee)

yet I am able to upload images/pdfs and docs. 

![Image](https://github.com/user-attachments/assets/9f74a951-2fb3-4b16-b50e-f6c4ae4a70bb)

Using the latest tag for LC. 

![Image](https://github.com/user-attachments/assets/6d47bd26-4f99-489f-9850-5aaac8097fdb)

Files get uploaded easily.

**Comment by danny-avila** [comment]
Closed by https://github.com/danny-avila/LibreChat/pull/8089

**Reply by TJKlein** [reply]
@danny-avila 
I am still having the problem. As a matter of fact, the previously working mimetype restriction now gets ignored for all my models:
e.g.
```
 openAI:
      disabled: false  # Disables file uploading to the OpenAI endpoint
      fileLimit: 5
      fileSizeLimit: 10  # Maximum size for an individual file in MB
      totalSizeLimit: 50  # Maximum total size for all files in a single request in MB
      supportedMimeTypes:
        - "application/pdf"
```
allows for the selection of images etc.
