### DISCUSSION TITLE
Model Title Not Generated for OpenAI and Claude on OpenRouter, but Works with DeepSeek

### DISCUSSION THREAD

**Discussion by abdoumin** [danny-avila/LibreChat#8112] [Troubleshooting]
### What happened?

I noticed that when using OpenRouter, model titles don't show up for OpenAI (like GPT-4) and Claude models. Interestingly, this doesn't seem to be an issue with DeepSeek, the title shows up just fine there.

### Version Information

```
ghcr.io/danny-avila/librechat-dev-api            latest          d536c685a0df   19 hours ago    1.19GB
ghcr.io/danny-avila/librechat-dev                latest          3c4ef949ab5f   19 hours ago    1.11GB
ghcr.io/danny-avila/librechat-rag-api-dev-lite   latest          6a1dfa1c7fe0   7 days ago      1.47GB
```

### Steps to Reproduce

1. Load a model like OpenAI or Claude via OpenRouter

2. Try to display or access the model's title.

3. Observe that the title is missing or not displayed.

4. Now switch to DeepSeek (e.g., deepseek-chat).

5. Notice that the title appears as expected.

### Relevant log output

```shell
Please see the screenshot.
```

### Screenshots

![Image](https://github.com/user-attachments/assets/9356e966-c6ec-4959-a45c-965805ad21ae)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
By default, it will use whichever model you have selected as the title model.

This will vary by model/provider, whether or not they support structured output for the selected option. Here I use GPT-4.1:
![image](https://github.com/user-attachments/assets/94840136-cc4c-4798-b74c-3005646ba2b6)

while more title configurations are coming, you can already define which model to use, which is highly recommended as you can dedicate titling to a working/efficient model.

https://www.librechat.ai/docs/configuration/librechat_yaml/object_structure/custom_endpoint#titlemodel

**Reply by abdoumin** [reply]
Hello,

Thanks for your response.

I’ve tested various models, including Mistral and OpenAI, for the title models, but I am still encountering the same issue.

I ran the Docker compose in non-detached mode and noticed the following error in the logs:

```
chat-meilisearch | 2025-06-28T16:56:21.258792Z  INFO index_scheduler: A batch of tasks was successfully completed with 1 successful task and 0 failed tasks.
LibreChat-API | 2025-06-28 16:56:21 error: [api/server/controllers/agents/client.js #titleConvo] Error 400 Provider returned error.
```

I hope this information helps in identifying the problem

**Reply by abdoumin** [reply]
Btw when i use openai provider, i still get an error, has to do with structured outputs just like you've mentionned :

```
chat-meilisearch  | 2025-06-29T13:20:16.398118Z  INFO index_scheduler: A batch of tasks was successfully completed with 1 successful tasks and 0 failed tasks.

LibreChat-API     | 2025-06-29 13:20:16 error: [api/server/controllers/agents/client.js #titleConvo] Error 400 Invalid parameter: 'response_format' of type 'json_schema' is not supported with this model. Learn more about supported models at the Structured Outputs guide: https://platform.openai.com/docs/guides/structured-outputs

```

I dont know how can we change the titleModel in this case since it is not a custom endpoint. 
And for gpt-4.1 using the openrouter ai provider i encounter this weird warn message :
 
`LibreChat-API     | 2025-06-29 13:23:49 warn: [api/server/controllers/agents/client.js #titleConvo] Error getting endpoint config
`

Thank you for your assistance in this matter !

**Reply by genaiservice** [reply]
I am also experiencing this bug when using the AzureOpenAI endpoint.

The issue is that title generation fails with several models. So far, we have detected that models from the `gpt-4.1` and `'o'` series return errors when trying to generate a title. However, models from the `gpt-4o` series are working as expected.

As a temporary workaround, we have set a `gpt-4o` series model as the default for generating all titles, but it would be great if this issue could be resolved.

This error occurs for us on the latest version of the repository (commit: 📝"docs: Update README (f4d97e16725a9e80cf4b7b47b4604a0f26901fee)").

Here is a snippet of our configuration in librechat.yml:

```yaml
azureOpenAI:
  titleModel: "current_model"
  # titleModel: "gpt-4o-mini"
  plugins: true
  assistants: false
  groups:
    - group: "g1"
      apiKey: '${...}'
      instanceName: "..."
      assistants: false
      models:
        gpt-4.1:
          deploymentName: gpt-4.1
          version: "2024-12-01-preview"
        .
        .
        .
    - group: "g2"
      apiKey: '${...}'
      instanceName: "..."
      assistants: false
      models:
        gpt-4o:
          deploymentName: gpt-4o
          version: "2025-01-01-preview"
        .
        .
        .
    - group: "g3"
      apiKey: '${...}'
      instanceName: "..."
      assistants: false
      models:
        o4-mini:
          deploymentName: o4-mini
          version: "2025-01-01-preview"
        .
        .
        .
```

We see the same error:
```
2025-07-07 12:19:45 error: [api/server/controllers/agents/client.js #titleConvo] Error this.client.chat.completions.parse is not a function
```

Hope this information helps!

**Reply by abdoumin** [reply]
Thanks for your input, 
When i apply your solution for an Openrouter model i receive the error below : 
```chat-meilisearch  | 2025-07-15T14:08:40.974269Z  INFO index_scheduler: A batch of tasks was successfully completed with 2 successful tasks and 0 failed tasks.
LibreChat-API     | 2025-07-15 14:08:42 error: [api/server/controllers/agents/client.js #titleConvo] Error Failed to parse. Text: "". Error: SyntaxError: Unexpected end of JSON input
LibreChat-API     | 
LibreChat-API     | Troubleshooting URL: https://js.langchain.com/docs/troubleshooting/errors/OUTPUT_PARSING_FAILURE/
LibreChat-API     | 
```
This is the config json that i have : 

```
version: 1.2.8


cache: true
 
interface:
  webSearch: true
  # Privacy policy settings
  privacyPolicy:
    externalUrl: 'https://librechat.ai/privacy-policy'
    openNewTab: true
 
  # Terms of service
  termsOfService:
    externalUrl: 'https://librechat.ai/tos'
    openNewTab: true
 
registration:
  socialLogins: ["discord", "facebook", "github", "google", "openid"]

 
endpoints:
  agents:
    recursionLimit: 50
    maxRecursionLimit: 100
    disableBuilder: false
    capabilities:
      - "file_search"
      - "artifacts"
      - "actions"
      - "tools"
      - "web_search"

  custom: 
    # OpenRouter.ai
    - name: "OpenRouter"
      apiKey: "{....}"
      baseURL: "https://openrouter.ai/api/v1"
      models:
        default: ["openai/gpt-4.1"]
        fetch: true
      titleConvo: true
      titleModel: "gpt-4o-mini"
      summarize: false
      summaryModel: "mistral-tiny"
      forcePrompt: false
      modelDisplayLabel: "OpenRouter"
```

The thing is when i use another model in Openrouter such as deepseek it generates the title successfuly, so i'm not sure if the titleConvo is taking in consideration for generating the title conversations. 

Thanks for your help!
