### DISCUSSION TITLE
Docker's MongoDB Setting for Raspberry Pi

### DISCUSSION THREAD

**Discussion by haozihong** [danny-avila/LibreChat#93] [Feature Requests & Suggestions]
I tried running the docker image on my raspberry pi 4B, but it turned out that the latest version of MongoDB does not support older ARM CPUs like those found in Raspberry Pis. 

However, I made it work by setting MongoDB's version to `mongo:4.4.18` in `docker-compose.yml`, the most recent version compatible with older CPUs like mine.

Perhaps it would be helpful to include this information in the `README`?

**Comment by danny-avila** [comment]
Thanks for the finding, i will add this

**Comment by HyunggyuJang** [comment]
Indeed, I'm currently using it on my Synology NAS. You might find it helpful: https://github.com/HyunggyuJang/chatgpt-clone/blob/168860e7ca59aea0b7edcb05e3db56878cd7a926/docker-compose.yml, and its corresponding docker file: https://github.com/HyunggyuJang/chatgpt-clone/blob/168860e7ca59aea0b7edcb05e3db56878cd7a926/Dockerfile

**Reply by HyunggyuJang** [reply]
For the host machine, in my case, mac, I have to use https://github.com/HyunggyuJang/chatgpt-clone/blob/5b6e91981f913f910d3f29c361a164ced9fe89c9/docker-compose.yml, as the docker mac version runs on VM, so cannot access host network from the host machine :{.

**Comment by deepanchal** [comment]
Adding this also worked on my RPI 4, 8GB

Ref: https://github.com/linuxserver/docker-unifi-network-application/issues/4#issuecomment-1719400553

```yaml
version: "3"

services:
  db:
    # 4.4.18 is the last version that runs on RPi's ARM.
    # Also, we can't use more than 4.4 for Unifi
    image: arm64v8/mongo:4.4.18
 ```
