### ISSUE TITLE
[Bug]: Running LibreChat against LiteLLM backed by OpenAI/Azure 

### ISSUE THREAD

**Issue by netnem** [danny-avila/LibreChat#1319]
### What happened?

I have a LiteLLM proxy configured with LibreChat being the front end.  On the latest LiteLLM (1.12.0 from pip) and latest LibreChat (recently pulled and redeployed).  

### Steps to Reproduce

install librechat via docker,
in .env file set OPENAI_REVERSE_PROXY=http://192.168.2.142:8000/ (i installed litellm on the docker host)
pip install litellm
pip install async_generator

Create a config.yaml:

```
model_list:
  - model_name: gpt-3.5-turbo 
    litellm_params:
       model: openai/gpt-3.5-turbo
       api_key: sk-<removed>
  - model_name: neural-chat
    litellm_params:
      model: ollama/neural-chat
litellm_settings:
  drop_params: True
  set_verbose: True
```
litellm -c config.yaml

The setup works for calling a localLLM, but when I call either Openai or Azure endpoints LibreChat will error with " Cannot read properties of null (reading 'trim')"

LiteLLM appears to be operating correctly.  I tested with a streaming API call with a python client.

### Relevant log output

```shell
Something went wrong. Here's the specific error message we encountered: Cannot read properties of null (reading 'trim')

userMessage {
  messageId: 'c19ef75d-7bde-4fc0-aa1d-3a795a38b9df',
  parentMessageId: '46006720-6271-47c1-bd4d-23169c994323',
  conversationId: 'bd80a472-b7e0-4251-9637-e994b0f9cf07',
  sender: 'User',
  text: 'hi',
  isCreatedByUser: true,
  tokenCount: 5
}
TypeError: Cannot read properties of null (reading 'trim')
    at OpenAIClient.sendCompletion (/app/api/app/clients/OpenAIClient.js:468:18)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async OpenAIClient.sendMessage (/app/api/app/clients/BaseClient.js:452:24)
    at async /app/api/server/routes/ask/openAI.js:112:20
TypeError: Cannot destructure property 'abortController' of 'abortControllers.get(...)' as it is undefined.
    at abortMessage (/app/api/server/middleware/abortMiddleware.js:14:11)
    at handleAbortError (/app/api/server/middleware/abortMiddleware.js:111:20)
    at /app/api/server/routes/ask/openAI.js:148:5
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Screenshots

Working with ollama/neural-chat:
![image](https://github.com/danny-avila/LibreChat/assets/32517635/7d45c4af-ae79-4607-a5d2-ee494be6f746)

Error with openai endpoint:
![image](https://github.com/danny-avila/LibreChat/assets/32517635/741b70d7-5857-40c3-9170-1a9956c2ba9e)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
