### ISSUE TITLE
Enhancement: Azure OpenAI: Enhance Configuration to Allow Multiple Deployments & Alternative Model Names

### ISSUE THREAD

**Issue by danny-avila** [danny-avila/LibreChat#1390]
### What features would you like to see added?

In https://github.com/danny-avila/LibreChat/pull/1389, and after finally acquiring my own Azure OpenAI access, I've learned that we can effectively reduce all confusion surrounding Azure OpenAI configuration with a singular setup file.

Something like a YAML config file would allow handling of all possible deployment configurations easily and without confusion.

### More details

This is planned, creating an issue for tracking

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Gyarbij** [comment]
I just stumbled on your project and if there's any help I can provide with the Azure bit let me know.

**Comment by danny-avila** [comment]
> I just stumbled on your project and if there's any help I can provide with the Azure bit let me know.

Thanks! I haven't gotten around to this but even some help mapping how this might look in [the config file](https://docs.librechat.ai/install/configuration/custom_config.html) would be really helpful

I was thinking we could treat the existing env variables as the "default" configuration, which each model would default to. However, adding the following to map specific models to specified deployment config:

```yaml
endpoints:
  azureOpenAI:
    deployments:
      - gpt-4-vision-preview:
          # any field omitted would resort to default values from existing env var
          azureOpenAIApiKey: "${YOUR_ENV_VAR_KEY}"
          azureOpenAIApiInstanceName: "some-instance"
          azureOpenAIApiDeploymentName: "some-deployment-name"
          azureOpenAIApiVersion: "some-version"
      - gpt-4-turbo-preview:
          azureOpenAIApiInstanceName: "some-instance"
          azureOpenAIApiDeploymentName: "some-deployment-name"
          azureOpenAIApiVersion: "some-version"
```

That's what I'm thinking but open to ideas

**Comment by Gyarbij** [comment]
I like the idea but to simplify things and since the new Azure AI portal organizes around projects. the 'InstanceName' can be a common variable for azure, just like 'api key'. Since the most likely use case would be deploying all the resources you need in single project or ai resource group unless it's some edge cases around whisper availability which I don't think apply here.

**Comment by danny-avila** [comment]
> I like the idea but to simplify things and since the new Azure AI portal organizes around projects. the 'InstanceName' can be a common variable for azure, just like 'api key'. Since the most likely use case would be deploying all the resources you need in single project or ai resource group unless it's some edge cases around whisper availability which I don't think apply here.

what are you thinking then? I'm unfamiliar with the "projects" structure.

**Comment by danny-avila** [comment]
also I mean to add some clarity with the design I proposed, since "deployment" is a recognized term for Azure OpenAI and wish to avoid confusion with it. 

The point of the following is to map specific models, [their names defined by OpenAI](https://platform.openai.com/docs/models/), to Azure OpenAI configurations.

```yaml
endpoints:
  azureOpenAI:
    model_config:
      gpt-4-vision-preview:
        # any field omitted would resort to default values from existing env var
        apiKey: "${YOUR_ENV_VAR_KEY}"
        instanceName: "some-instance"
        deploymentName: "some-deployment-name"
        version: "some-version"
      gpt-4-turbo-preview:
        instanceName: "some-instance"
        deploymentName: "some-deployment-name"
        version: "some-version"
```

**Comment by Gyarbij** [comment]
Hey, sorry for taking so long to get back you, I'll do a better write up on Wednesday and see what parts of the code I can help with. But for now what I mean was more along the lines of:

```endpoints:
  azureOpenAI:
    instanceName: "some-instance"
    apiKey: "${YOUR_ENV_VAR_KEY}"
    modelConfig: # changed from 'deployments'
      gpt-4-vision-preview:
        # any field omitted would resort to default values from existing env var
        deploymentName: "some-deployment-name"
        version: "some-version"
      gpt-4-turbo-preview:
        deploymentName: "some-deployment-name"
        version: "some-version"
```

To mainly keep things tidy in the compose/config as you'll most likely be keeping the deployments in a single project or what you're referring to as instance which would be the ai resource for that project. It doesn't interfere with your vision which I like as it makes it easier for persons working across both.

So as I said, it mainly cleans up the file as proposed.

**Comment by danny-avila** [comment]
> Hey, sorry for taking so long to get back you, I'll do a better write up on Wednesday and see what parts of the code I can help with. 

Thanks and no worries, look forward to it!

I think we're getting at the same thing, since this bit is essentially handled by the `AZURE_OPENAI_API_INSTANCE_NAME` variable.
```yaml
  azureOpenAI:
    instanceName: "some-instance"
```

I think I will still keep it like this along with what you proposed because I found myself using more than one instance due to the instance/project being locked to 1 region, and certain models being locked by region.

```yaml
      gpt-4-vision-preview:
        # any field omitted would resort to default values from existing env var
        apiKey: "${YOUR_ENV_VAR_KEY}"
        instanceName: "some-instance"
```

I forget which model, but I could only access a specific model via "West US."
![image](https://github.com/danny-avila/LibreChat/assets/110412045/c1e30fc8-0dc9-454d-bb07-b2a4b90bfbde)

**Comment by Gyarbij** [comment]
You're absolutely correct and I overlooked that new accounts also have limits on region availability so making it simple for cases where it's a single instance while maintaining flexibility is much appreciated. 

[Here](https://learn.microsoft.com/en-us/azure/ai-services/openai/concepts/models) is the model availability chart:
![image](https://github.com/danny-avila/LibreChat/assets/49493993/b003ad1c-b8f8-4e77-a1f8-8d6d0796013e)

**Comment by scgreenhalgh** [comment]
> also I mean to add some clarity with the design I proposed, since "deployment" is a recognized term for Azure OpenAI and wish to avoid confusion with it.
> 
> The point of the following is to map specific models, [their names defined by OpenAI](https://platform.openai.com/docs/models/), to Azure OpenAI configurations.
> 
> ```yaml
> endpoints:
>   azureOpenAI:
>     modelConfig: # changed from 'deployments'
>       gpt-4-vision-preview:
>         # any field omitted would resort to default values from existing env var
>         apiKey: "${YOUR_ENV_VAR_KEY}"
>         instanceName: "some-instance"
>         deploymentName: "some-deployment-name"
>         version: "some-version"
>       gpt-4-turbo-preview:
>         instanceName: "some-instance"
>         deploymentName: "some-deployment-name"
>         version: "some-version"
> ```

I am having the same issue with Azure OpenAI, where they seem to have huge amounts of regional availability of different models, etc., so this new layout would be a godsend.

Although it doesn't strictly adhere to DRY i think this layout would work but maybe make it cascading so that you can group models below the deployment name and api key, this way you could then prevent repeating of fields. Also maybe a friendly name field would be nice too (and if needed the Open-AI formatted model).

e.g.

> ```yaml
> endpoints:
>   azureOpenAI:
>     modelConfig: # changed from 'deployments'
>     region: sweedencentral # or maybe even just group name
>.       apiKey: "${YOUR_REGIONAL_KEY}"
>        instanceName: "some-instance"
>          gpt-4-vision-preview:
>            # any field omitted would resort to the values directly one level above, or default values from existing env var
>            deploymentName: "some-deployment-name"
>            version: "some-version"
>          gpt-4-turbo-preview:
>            deploymentName: "some-deployment-name"
>            version: "some-version"
>     region: usa-east2 # or maybe even just group name
>        apiKey: "${YOUR_REGIONAL_KEY}"
>        instanceName: "some-instance"
>          gpt-35-turbo:
>            deploymentName: "some-deployment-name"
>            version: "some-version"
>          gpt-4:
>            deploymentName: "some-deployment-name"
>            version: "some-version"
> ```

**Comment by danny-avila** [comment]
> Although it doesn't strictly adhere to DRY i think this layout would work but maybe make it cascading so that you can group models below the deployment name and api key, this way you could then prevent repeating of fields. Also maybe a friendly name field would be nice too (and if needed the Open-AI formatted model).
> 
> e.g.
> 
> > ```yaml
> > endpoints:
> >   azureOpenAI:
> >     modelConfig: # changed from 'deployments'
> >     region: sweedencentral # or maybe even just group name
> > .       apiKey: "${YOUR_REGIONAL_KEY}"
> >        instanceName: "some-instance"
> >          gpt-4-vision-preview:
> >            # any field omitted would resort to the values directly one level above, or default values from existing env var
> >            deploymentName: "some-deployment-name"
> >            version: "some-version"
> >          gpt-4-turbo-preview:
> >            deploymentName: "some-deployment-name"
> >            version: "some-version"
> >     region: usa-east2 # or maybe even just group name
> >        apiKey: "${YOUR_REGIONAL_KEY}"
> >        instanceName: "some-instance"
> >          gpt-35-turbo:
> >            deploymentName: "some-deployment-name"
> >            version: "some-version"
> >          gpt-4:
> >            deploymentName: "some-deployment-name"
> >            version: "some-version"
> > ```

love this idea to group them by region/group name! Thanks I’m planning to working on this very soon since Assistants API is finally coming to Azure, and will necessitate a multi-deployment/region setup for model variety

**Comment by scgreenhalgh** [comment]
Fantastic! It might even be an idea to split things up into "endpoints" and then maybe "engine name" as a variable because this way around, you could create certain setups. Something like this. It might be a bit too much, but I am forking your code and thinking about modifying it in similar ways because I am hoping to roll it out to the rest of my company with pre-set configurations, which will include some RAG or plugins that enable to make it more user friendly for the non-technical types.

```yaml
endpoints:
  internal-knowledgebase-gpt:
    friendly-name:"Internal Company Knowledgebase"
    engine: "azureOpenAI"
    modelConfig: # changed from 'deployments'
    region: usa-east2 # or maybe even just group name
       apiKey: "${YOUR_REGIONAL_KEY}"
       instanceName: "some-instance"
         gpt-35-turbo:
           deploymentName: "some-deployment-name"
           version: "some-version"
         gpt-4:
           deploymentName: "some-deployment-name"
           version: "some-version"
    plugins:
       azure-ai-search:
          azure_ai_search_service_endpoint: "some-azure-ai-search-endpoint"
          azure_ai_search_index_name: "some-azure-ai-index-name"
          azure_ai_search_api_key: "some-azure-ai-search-api-key"
      force: TRUE
```

Or something like that, hope you can figure out what I am getting at. This way you could also have different AI search endpoints for configurations

Let me know if there is anything I can lend a hand with. I am more of a Python/Django developer for web frameworks, but I am starting to get a bit used to Node/Express.js

**Comment by tttll1091** [comment]
Will this fix be implemented at the same time as Azure assistant API usage?
Until recently, it was possible to switch models in Azure, but it was not possible to switch models in Plugins. Currently, I understand that only one model can be specified. This fix seems to solve many problems.

**Comment by danny-avila** [comment]
> Will this fix be implemented at the same time as Azure assistant API usage?
> Until recently, it was possible to switch models in Azure, but it was not possible to switch models in Plugins. Currently, I understand that only one model can be specified. This fix seems to solve many problems.

This update will precede Azure assistant api usage.

**Comment by danny-avila** [comment]
> ```yaml
> endpoints:
>   internal-knowledgebase-gpt:
>     friendly-name: "Internal Company Knowledgebase"
>     engine: "azureOpenAI"
>     modelConfig: # changed from 'deployments'
>     region: usa-east2 # or maybe even just group name
>        apiKey: "${YOUR_REGIONAL_KEY}"
>        instanceName: "some-instance"
>          gpt-35-turbo:
>            deploymentName: "some-deployment-name"
>            version: "some-version"
>          gpt-4:
>            deploymentName: "some-deployment-name"
>            version: "some-version"
>     plugins:
>        azure-ai-search:
>           azure_ai_search_service_endpoint: "some-azure-ai-search-endpoint"
>           azure_ai_search_index_name: "some-azure-ai-index-name"
>           azure_ai_search_api_key: "some-azure-ai-search-api-key"
>           force: TRUE
> ```
> 

This seems like it's crossing over to the area of System-wide model settings, which are planned: https://github.com/danny-avila/LibreChat/discussions/1291 https://github.com/danny-avila/LibreChat/issues/1617

And going to work on it soon, finally.

> which will include some RAG or plugins

Any contributions for features like this are definitely welcome! Current Roadmap: https://forms.gle/hzn8kiw83TQfWzp98

**Comment by danny-avila** [comment]
Working on this. hoping to finish tomorrow

**Comment by danny-avila** [comment]
Wrapping this up. The most seamless way to integrate this was by "deprecating" almost every Azure env. variable to prefer the `librechat.yaml` configuration.

```.env
# updated .env.example

# Note: these variables are DEPRECATED
# Use the `librechat.yaml` configuration for `azureOpenAI` instead
# You may also continue to use them if you opt out of using the `librechat.yaml` configuration

# AZURE_OPENAI_DEFAULT_MODEL=gpt-3.5-turbo # Deprecated
# AZURE_OPENAI_MODELS=gpt-3.5-turbo,gpt-4 # Deprecated
# AZURE_USE_MODEL_AS_DEPLOYMENT_NAME=TRUE # Deprecated
# AZURE_API_KEY= # Deprecated
# AZURE_OPENAI_API_INSTANCE_NAME= # Deprecated
# AZURE_OPENAI_API_DEPLOYMENT_NAME= # Deprecated
# AZURE_OPENAI_API_VERSION= # Deprecated
# AZURE_OPENAI_API_COMPLETIONS_DEPLOYMENT_NAME= # Deprecated
# AZURE_OPENAI_API_EMBEDDINGS_DEPLOYMENT_NAME= # Deprecated
```

They can still be used as I've left their logic completely untouched. When configuring them via the config file, though, you will get warnings for using them:

```bash
2024-02-21 12:44:00 warn: The `AZURE_API_KEY` environment variable (related to setting a single Azure API key) should not be used in combination with the `azureOpenAI` endpoint configuration, as you will experience conflicts and errors.
# .. and so on
```

### The benefit:
![image](https://github.com/danny-avila/LibreChat/assets/110412045/249b1124-f671-46e0-b1d2-97b95ef9e891)

**I am seamlessly using 2 different deployments on different regions with this configuration in the upcoming update:**

```yaml
endpoints:
  azureOpenAI:
    groups:
    - group: "my-westus-region-group-name"
      apiKey: "${WESTUS_API_KEY}"
      instanceName: "my-westus-region"
      version: "2023-12-01-preview"
      # baseURL: https://prod.example.com
      # additionalHeaders:
      #   X-Custom-Header: value
      models:
        gpt-4-vision-preview:
          deploymentName: gpt-4-vision-preview
          version: "2024-02-15-preview"
        gpt-3.5-turbo:
          deploymentName: gpt-35-turbo
        gpt-3.5-turbo-1106:
          deploymentName: gpt-35-turbo-1106
        gpt-4:
          deploymentName: gpt-4
        gpt-4-1106-preview:
          deploymentName: gpt-4-1106-preview
    - group: "my-eastus-region-group-name"
      apiKey: "${EASTUS_API_KEY}"
      instanceName: "my-eastus-region"
      deploymentName: gpt-4-turbo
      version: "2024-02-15-preview"
      models:
        gpt-4-turbo: true
```

Note how I defined my own API key. group names and api key variable names are arbitrary. The `models` listed must conform to known OpenAI models. Naming groups by region is not necessary and is just convention for grouping.



I'm on to making sure the baseURL, additional headers, DALL-E, and plugins are configurable from this new and improved method of configuration.
