### ISSUE TITLE
Enhancement: adding mistral model family 

### ISSUE THREAD

**Issue by Forbu** [danny-avila/LibreChat#1500]
### What features would you like to see added?

Alonside with openai / google gemini / anthropic claude, there is currently a new plateform : mistral ai plateform that propose (mostly) open-weights models (mistral 7B and mixtral 8x7B). There are currently creating a plateform to serve their model (as open ai) :
https://docs.mistral.ai/platform/client/

I was wondering if you could add their client on your plateform, it will cool to have some api than big tech !

Nice job for the librechat plateform :)
 

### More details

I suppose it will be something like adding a new provider next to openai and co in the top left :)

### Pictures

![image](https://github.com/danny-avila/LibreChat/assets/11457947/48137229-dda8-496c-8b32-310844b50cc6)
(their model perf)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Thanks for checking out the project! For now, this is not planned since it's already possible by copying/adding the example config file to your instance: [See the docs here](https://docs.librechat.ai/install/configuration/custom_config.html#example-config)

![image](https://github.com/danny-avila/LibreChat/assets/110412045/fab572f5-4ce7-4472-b5a2-aed6848d49f1)

You can add any AI provider that follows OpenAI API specifications (like Mistral AI) through the custom configuration file, see the docs I linked above for more info

**Comment by Forbu** [comment]
Woow ! nice job guys

**Comment by cracksauce** [comment]
> Thanks for checking out the project! For now, this is not planned since it's already possible by copying/adding the example config file to your instance: [See the docs here](https://docs.librechat.ai/install/configuration/custom_config.html#example-config)
> 
> ![image](https://private-user-images.githubusercontent.com/110412045/294697620-fab572f5-4ce7-4472-b5a2-aed6848d49f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzNTU0ODgsIm5iZiI6MTcwNTM1NTE4OCwicGF0aCI6Ii8xMTA0MTIwNDUvMjk0Njk3NjIwLWZhYjU3MmY1LTRjZTctNDQ3Mi1iNWEyLWFlZDY4NDhkNDlmMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNVQyMTQ2MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMzUzYjJjOTg2YzMxZmQ3MmQ3NDg3M2ZmMjAxMDM0ZmFkOTkyNWQ5NDlmM2M3OTYxNmY3OTgxYjQ5NGE3OGJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8yQlewc44JG_mRXpoBGm_gNAHwtIJvg3RFFC9dDxHW4)
> 
> You can add any AI provider that follows OpenAI API specifications (like Mistral AI) through the custom configuration file, see the docs I linked above for more info

@danny-avila I am attempting to load a custom config of a locally running LLM (Mistral 7b) using MLC-LLM as backend. It runs the model through an openai compatible API. This doesn't require an API key. Librechat is requiring an API key or it won't function and throws errors left and right.

Tried adjusting custom config related .js to no avail. Assistance would be appreciated here.

**Comment by danny-avila** [comment]
> @danny-avila I am attempting to load a custom config of a locally running LLM (Mistral 7b) using MLC-LLM as backend. It runs the model through an openai compatible API. This doesn't require an API key. Librechat is requiring an API key or it won't function and throws errors left and right.
> 
> Tried adjusting custom config related .js to no avail. Assistance would be appreciated here.

just pass a fake value like this:

```yaml
# Configuration version (required)
version: 1.0.1

# Cache settings: Set to true to enable caching
cache: true

# Definition of custom endpoints
endpoints:
  custom:
    # Mistral AI API
    - name: "Mistral"  # Unique name for the endpoint
      # For `apiKey` and `baseURL`, you can use environment variables that you define.
      # recommended environment variables:
      apiKey: "fake_api_key" # changed this from the example
      baseURL: "https://api.mistral.ai/v1"

      # Models configuration
      models: 
        # List of default models to use. At least one value is required.
        default: ["mistral-tiny", "mistral-small", "mistral-medium"]
        # Fetch option: Set to true to fetch models from API.
        fetch: true  # Defaults to false.

      # Optional configurations
      
      # Title Conversation setting
      titleConvo: true  # Set to true to enable title conversation

      # Title Method: Choose between "completion" or "functions".
      titleMethod: "completion"  # Defaults to "completion" if omitted.

      # Title Model: Specify the model to use for titles.
      titleModel: "mistral-tiny"  # Defaults to "gpt-3.5-turbo" if omitted.

      # Summarize setting: Set to true to enable summarization.
      summarize: false

      # Summary Model: Specify the model to use if summarization is enabled.
      summaryModel: "mistral-tiny"  # Defaults to "gpt-3.5-turbo" if omitted.

      # Force Prompt setting: If true, sends a `prompt` parameter instead of `messages`.
      forcePrompt: false

      # The label displayed for the AI model in messages.
      modelDisplayLabel: "Mistral"  # Default is "AI" when not set.

      # Add additional parameters to the request. Default params will be overwritten.
      addParams:
        safe_mode: true # This field is specific to Mistral AI: https://docs.mistral.ai/api/
        
      # Drop Default params parameters from the request. See default params in guide linked below.
      dropParams: ["stop", "temperature", "top_p"]
      # - stop # dropped since it's not recognized by Mistral AI API
      # `temperature` and `top_p` are removed to allow Mistral AI API defaults to be used:
      # - temperature
      # - top_p
```

@cracksauce is the config file loading at all for you? You should open a Troubleshooting discussion and we can focus on it there:

https://github.com/danny-avila/LibreChat/discussions/new?category=troubleshooting
