### ISSUE TITLE
[Question]: How can I add Mistral to the list of endpoints?

### ISSUE THREAD

**Issue by berceanu** [danny-avila/LibreChat#1558]
### What is your question?

I have recently obtained an API key for Mistral and would like to use it through LibreChat. However, I do not see Mistral in the drop-down list (screenshot below), even though I added said API key to `librechat.yaml` file and ran `docker-compose build --no-cache` afterwards. Using LibreChat v 0.6.5.

### More Details

```
# Configuration version (required)
version: 1.0.0

# Cache settings: Set to true to enable caching
cache: true

# Definition of custom endpoints
endpoints:
  custom:
    # Mistral AI API
    - name: "Mistral"  # Unique name for the endpoint
      # For `apiKey` and `baseURL`, you can use environment variables that you define.
      # recommended environment variables:
      apiKey: "*********************************"
      baseURL: "https://api.mistral.ai/v1"

      # Models configuration
      models:
        # List of default models to use. At least one value is required.
        default: ["mistral-tiny", "mistral-small", "mistral-medium"]
        # Fetch option: Set to true to fetch models from API.
        fetch: true  # Defaults to false.

      # Optional configurations

      # Title Conversation setting
      titleConvo: true  # Set to true to enable title conversation

      # Title Method: Choose between "completion" or "functions".
      titleMethod: "completion"  # Defaults to "completion" if omitted.

      # Title Model: Specify the model to use for titles.
      titleModel: "mistral-tiny"  # Defaults to "gpt-3.5-turbo" if omitted.

      # Summarize setting: Set to true to enable summarization.
      summarize: false

      # Summary Model: Specify the model to use if summarization is enabled.
      summaryModel: "mistral-tiny"  # Defaults to "gpt-3.5-turbo" if omitted.

      # Force Prompt setting: If true, sends a `prompt` parameter instead of `messages`.
      forcePrompt: false

      # The label displayed for the AI model in messages.
      modelDisplayLabel: "Mistral"  # Default is "AI" when not set.

      # Add additional parameters to the request. Default params will be overwritten.
      addParams:
        safe_mode: true # This field is specific to Mistral AI: https://docs.mistral.ai/api/

      # Drop Default params parameters from the request. See default params in guide linked below.
      dropParams: ["stop", "temperature", "top_p"]
      # - stop # dropped since it's not recognized by Mistral AI API
      # `temperature` and `top_p` are removed to allow Mistral AI API defaults to be used:
      # - temperature
      # - top_p

    # OpenRouter.ai Example
    - name: "OpenRouter"
      # For `apiKey` and `baseURL`, you can use environment variables that you define.
      # recommended environment variables:
      # Known issue: you should not use `OPENROUTER_API_KEY` as it will then override the `openAI` endpoint to use OpenRouter as well.
      apiKey: "${OPENROUTER_KEY}"
      baseURL: "https://openrouter.ai/api/v1"
      models:
        default: ["gpt-3.5-turbo"]
        fetch: true
      titleConvo: true
      titleModel: "gpt-3.5-turbo"
      summarize: false
      summaryModel: "gpt-3.5-turbo"
      forcePrompt: false
      modelDisplayLabel: "OpenRouter"

# See the Custom Configuration Guide for more information:
# https://docs.librechat.ai/install/configuration/custom_config.html
```

### Screenshots

<img width="1541" alt="Screenshot 2024-01-15 at 14 36 56" src="https://github.com/danny-avila/LibreChat/assets/4405658/690f63f3-5b2f-4709-b133-6f938ba643b2">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
