### ISSUE TITLE
[Bug]: Custom Endpoint LocalAI "Failed to fetch models from OpenAI API Request failed with status code 404"

### ISSUE THREAD

**Issue by K-J-VV** [danny-avila/LibreChat#1626]
### What happened?

Having a hard time figuring out how to use LocalAI as a custom endpoint with LibreChat

Keep getting an error stating that the models were not able to be fetched, but the model does show in LibreChat and is selectable. Whenever I try to type anything to the chat, the GPT just ends and then this error is displayed in the log

example of .env:

```
PROXY=
OPENAI_FORCE_PROMPT=true
OPENAI_REVERSE_PROXY=https://localai.example.com/v1/chat/completions   # I have tried /v1 as well
OPENAI_MODELS=gpt-3.5-turbo
PLUGIN_MODELS=gpt-3.5-turbo
DEBUG_PLUGINS=true
GALLERIES=[{"name":"model-gallery", "url":"github:go-skynet/model-gallery/index.yaml"}]
PRELOAD_MODELS=[{"url": "github:go-skynet/model-gallery/gpt4all-j.yaml", "name": "gpt-3.5-turbo"}]
```

example of librechat.yaml : 

```
version: 1.0.1
cache: true
endpoints:
  custom:
     # gpt4all-j
    - name: "GPT"
      apiKey: "xxxxx"
      baseURL: "https://localai.example.com/v1/chat/completions"
      models:
        default: ["gpt-3.5-turbo"]
        fetch: true
      titleConvo: true
      titleModel: "gpt-3.5-turbo"
      summarize: true
      summaryModel: "gpt-3.5-turbo"
      forcePrompt: true
      modelDisplayLabel: "GPT"
```

models at https://localai.example.com/v1/models : 

```
{
    "object": "list",
    "data": [
        {
            "id": "gpt-3.5-turbo",
            "object": "model"
        }
    ]
}
```

### Steps to Reproduce

1. Create docker containers for LocalAI and LibreChat
2. Use librechat.yaml to point to custom endpoint of LocalAI models

### Relevant log output

```shell
error: Failed to fetch models from OpenAI API Request failed with status code 404
2024-01-25 02:00:46 error: [MeiliMongooseModel.findOneAndUpdate] Convo not found in MeiliSearch and will index 98932e9c-7f7c-4a08-b087-fbed41f18046 Document `98932e9c-7f7c-4a08-b087-fbed41f18046` not found.
```
```


### Screenshots

![Screenshot 2024-01-24 201808](https://github.com/danny-avila/LibreChat/assets/113187314/c2877ad3-37a2-42db-956e-ed64dcd419a3)


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
