### ISSUE TITLE
[Bug]: Error while using openrouter/gemini-pro-vision

### ISSUE THREAD

**Issue by dannykorpan** [danny-avila/LibreChat#1634]
### What happened?

Hello everyone,

I have connected the [gemini-pro-vision model via openrouter.ai](https://openrouter.ai/models/google/gemini-pro-vision), but I always get the following error message within LibreChat. I've tested it with different images and types (png, jpg...).

'''
Something went wrong. Here's the specific error message we encountered: Error: { "error": { "code": 400, "message": "Provided image is not valid.", "status": "INVALID_ARGUMENT" } } 
'''

Am I doing something wrong, do I need to set an option?

Thanks for your help!

### Steps to Reproduce

1. Create openrouter.ai account
2. Get API key
3. Edit librechat.yaml
4. restart docker container
5. Test gemini-vision-pro

### What browsers are you seeing the problem on?

Firefox

### Relevant log output

```shell
2024-01-25 14:17:52 error: [MeiliMongooseModel.findOneAndUpdate] Convo not found in MeiliSearch and will index b716275d-6e10-4a5b-a4ff-8a5a7a7b20d0 Document `b716275d-6e10-4a5b-a4ff-8a5a7a7b20d0` not found.
2024-01-25 14:17:54 warn: [OpenAIClient.chatCompletion][stream] API error
2024-01-25 14:17:54 warn: [OpenAIClient.chatCompletion][finalChatCompletion] API error
2024-01-25 14:17:54 error: [OpenAIClient.chatCompletion] Unhandled error type Error: {
  "error": {
    "code": 400,
    "message": "Provided image is not valid.",
    "status": "INVALID_ARGUMENT"
  }
}

2024-01-25 14:17:54 error: [handleAbortError] AI response error; aborting request: Error: {
  "error": {
    "code": 400,
    "message": "Provided image is not valid.",
    "status": "INVALID_ARGUMENT"
  }
}
```

### Screenshots

<img width="794" alt="grafik" src="https://github.com/danny-avila/LibreChat/assets/8004507/fe332640-973c-446d-a7df-421be60106a4">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Thanks for your report. I will have to test to be sure but this is likely because gpt-4-vision is being prioritized regardless of you selecting gemini as it is using OpenAI specs, on top of maybe some other outright compatibility.

I'm using this issue to address the core issue, where users would benefit from outright selecting the vision model to be used.

**Comment by danny-avila** [comment]
For now, I also recommend using the Google endpoint as vision is fully supported for Gemini there. Maybe you are region-locked but you could use a VPN to access it. https://docs.librechat.ai/install/configuration/ai_setup.html#generative-language-api-gemini

**Comment by avimar** [comment]
Give the choice between opaquely redirecting the _entire thread_ and an error, I choose to get an error.

This really surprised me when I was trying to test new vision models.

And see my longer comment: https://github.com/danny-avila/LibreChat/issues/2103#issuecomment-2377043246
1. can we update the list of vision models, and have an easy way to automatically update the list?
1. In my tests, the cheapest good model for images is google/gemini-flash-1.5 and I would want that as my default
1. Either disable images on non-supported models, or, have it pass ONLY THE IMAGE to a vision model to "convert it".
1. Here's a prompt to get a vision model to fully describe a picture, so that it can be passed back to a regular model.

**Comment by tinfever** [comment]
I just burned a few dollars in OpenRouter credit because I was using images in a Librechat thread set to use Deepseek R1, but silently all of my messages were using GPT-4.5. If Librechat is going to send my images to a different model, can I at least configure it to not use the most expensive model there is?

**Comment by tsaihsing3** [comment]
> I just burned a few dollars in OpenRouter credit because I was using images in a Librechat thread set to use Deepseek R1, but silently all of my messages were using GPT-4.5. If Librechat is going to send my images to a different model, can I at least configure it to not use the most expensive model there is?

same here. I tested `google/gemini-2.5-pro-preview-03-25` on OpenRouter via first. Then I hope to  use `deepseek/deepseek-chat-v3-0324`(on OpenRouter), but accorrding to my Openrouter logs, messages with image were sent to `google/gemini-2.5-pro-preview-03-25`.

#### One solution:

disable `fetch` in `librechat.yml` for the custom `Openrouter` Endpoint.

```
    - name: 'OpenRouter'
      apiKey: '${OPENROUTER_KEY}'
      baseURL: 'https://openrouter.ai/api/v1'
      models:
        default: ["deepseek/deepseek-chat-v3-0324"] # all models you want to use on Openrouter
        fetch: false 
      titleConvo: true
      titleModel: 'current_model'
      # Recommended: Drop the stop parameter from the request as Openrouter models use a variety of stop tokens.
      dropParams: ['stop']
      forcePrompt : false
      modelDisplayLabel: 'OpenRouter'
```
