### ISSUE TITLE
Enhancement: allow users to setup password on mongodb

### ISSUE THREAD

**Issue by CXwudi** [danny-avila/LibreChat#1723]
### What features would you like to see added?

Support username and password for mongo DB from docker compose

More specifically, support the following mongo DB URI format in `MONGO_URI` environment variables:

```
mongodb://<username>:<password>@<host>/<database>
```

### More details

https://github.com/danny-avila/LibreChat/blob/e7f6b22b5df417af99fde13d3aa832ce0de48b48/docker-compose.yml#L35

It is not secured to run any database without a password. 

However, currently LibreChat doesn't support locally hosted mongo DB with a password. Doing so will results in the following error:

``` log
LibreChat@0.6.6 backend
cross-env NODE_ENV=production node api/server/index.js

2024-02-04 16:42:15 info: [Optional] Redis not initialized. Note: Redis support is experimental.
2024-02-04 16:42:19 error: KeyvMongo connection error: Authentication failed.
2024-02-04 16:42:19 error: There was an uncaught error: Authentication failed.
```

The example docker compose yaml file I used is following:

``` yaml
  librechat:
    # librechat configs...

  mongodb:
    image: mongo
    container_name: librechat-mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=my_admin
      - MONGO_INITDB_ROOT_PASSWORD=my_password
    volumes:
      - librechat-mongodb-data:/data/db
```

And for the LibreChat config, I simply set `MONGO_URI=mongodb://my_admin:my_password@mongodb:27017/LibreChat`

### Which components are impacted by your request?

General

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
This is the perfect use case for using the `docker-compose.override.yml` file: https://docs.librechat.ai/install/configuration/docker_override.html

It's more than possible to authenticate the database and allow passing credentials to the URI. It's not working for you because you need to add the admin user to the database.

This part cannot be automated which is why we use `--no-auth`; otherwise, we would be determining the database password for others which is arguably just as or more insecure: every docker instance of LibreChat would have a default user:pass enabled for their setup. The ports are closed by default to help mitigate access non-authenticated local database.

I'm doing a write up on how to authenticate the DB in response to your concern, as more steps are needed, and the docs are lacking at the moment.

**Comment by Berry-13** [comment]
> It is not secured to run any database without a password

btw @CXwudi, I don't want to be rude, but in our [docker-compopse](https://github.com/danny-avila/LibreChat/blob/main/docker-compose.yml) it wasn't exposed, so even without a password, there wouldn't have been any problems

**Comment by CXwudi** [comment]
@danny-avila thanks for your fast and informative response to my question. I see the problem is still on my side and guess I will have to deep in more to figure out the proper way to setup the mongo DB container with a password. Also thanks for your PR for adding documentation on mongo DB authentication. I will definitely check it out once it is merged. 

@Berry-13 no worry, and yes I knew the port is not exposed, so I am not too worrying. I am just too used to adding an authentication to the database, which I always do when setting up a relational SQL DB container

**Comment by CXwudi** [comment]
Ok, so I am back with a solution. Let's just say docker's official mongo DB is problematic with user setup for authentication

https://github.com/docker-library/mongo/issues/329
https://github.com/docker-library/mongo/issues/174

A simple solution is just switch to [bitnami's mongo DB image](https://github.com/bitnami/containers/blob/main/bitnami/mongodb/README.md) and here is an example docker compose setup

``` yaml
services:
  librechat:
    # other librechat configs...
    env_file:
      - db.env # load env file used by mongodb container to avoid hardcoding MONGO_URI
      - .env
    environment:
      - MONGO_URI=mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@mongodb:27017/${MONGODB_DATABASE}

  mongodb:
    image: bitnami/mongodb
    container_name: librechat-mongodb
    volumes:
      - librechat-mongodb-data:/bitnami/mongodb/
    env_file:
      - db.env

volumes:
  librechat-mongodb-data:
```

where `db.env` is:

``` properties
# either MONGODB_ROOT_PASSWORD=<a root password> or ALLOW_EMPTY_PASSWORD=yes is needed
MONGODB_ROOT_PASSWORD=<a root password>
MONGODB_USERNAME=<your new username>
MONGODB_PASSWORD=<your new password>
MONGODB_DATABASE=LibreChat
```

If offical mongo image is preferred, then you will have to write a simple `.js` file to be loaded by mongodb container at startup to register your own user. https://github.com/docker-library/mongo/issues/174#issuecomment-449984230 shows an example of how to do it
