### ISSUE TITLE
[Doc]: Clarify documentation about overriding values in the override file

### ISSUE THREAD

**Issue by sandipb** [danny-avila/LibreChat#1775]
### What happened?

I uncommented the sections in the override files - I wanted my librechat.yml file to be mounted. I also wanted to use the image from docker and not build it every time.

So I ended up with the following:

```yaml
version: '3.4'

# # TO USE THIS FILE, FIRST UNCOMMENT THE FOLLOWING LINE ('services:')

services:

# # THEN UNCOMMENT ONLY THE SECTION OR SECTIONS CONTAINING THE CHANGES YOU WANT TO APPLY
# # SAVE THIS FILE AS 'docker-compose.override.yaml'
# # AND USE THE 'docker-compose build' & 'docker-compose up -d' COMMANDS AS YOU WOULD NORMALLY DO

# USE LIBRECHAT CONFIG FILE
  api:
    volumes:
      - ./librechat.yaml:/app/librechat.yaml

# # BUILD FROM LATEST IMAGE
#   api:
#     image: ghcr.io/danny-avila/librechat-dev:latest

# # BUILD FROM LATEST IMAGE (NUMBERED RELEASE)
  api:
    image: ghcr.io/danny-avila/librechat:latest
```

But the api server kept complaining that the config file is not present. And running `docker-compose config` showed me that the volume is not being updated.

The second `api:` shouldn't have been uncommented. Now experienced docker users might know that, but it is a gotcha for the rest.

There should be only one `api:` uncommented, otherwise the last one will override the other - they wont be merged.

So the right one is:
```
version: '3.4'

# # TO USE THIS FILE, FIRST UNCOMMENT THE FOLLOWING LINE ('services:')

services:

# # THEN UNCOMMENT ONLY THE SECTION OR SECTIONS CONTAINING THE CHANGES YOU WANT TO APPLY
# # SAVE THIS FILE AS 'docker-compose.override.yaml'
# # AND USE THE 'docker-compose build' & 'docker-compose up -d' COMMANDS AS YOU WOULD NORMALLY DO

# USE LIBRECHAT CONFIG FILE
  api:
    volumes:
      - ./librechat.yaml:/app/librechat.yaml

# # BUILD FROM LATEST IMAGE
#   api:
#     image: ghcr.io/danny-avila/librechat-dev:latest

# # BUILD FROM LATEST IMAGE (NUMBERED RELEASE)
  # api:
    image: ghcr.io/danny-avila/librechat:latest
```

### Steps to Reproduce

Using the example docker-compose.override example file and uncommenting two or more sections with "api:" as the key.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
