### ISSUE TITLE
[Bug]: Custom API streams the chat, but disappears after stop token

### ISSUE THREAD

**Issue by deoxykev** [danny-avila/LibreChat#1794]
### What happened?

I'm trying to configure LibreChat to use [text-generation-webui](https://github.com/oobabooga/text-generation-webui) with the `--api` option. However, there seems to be an issue where the text will begin streaming, then disappear once the stop token is reached.

I'm using the latest version of docker container LibreChat (ghcr.io/danny-avila/librechat-dev-api:latest) `2bf834f78f444cf2de641093ac21029214d32d8cb5fec2b3b7951cb48c3fc3f3`.

### Steps to Reproduce

Librechat.yaml:
```yaml
# Configuration version (required)
version: 1.0.2

# Cache settings: Set to true to enable caching
cache: true

# Example Registration Object Structure (optional)
registration:
  socialLogins: ["github", "google", "discord", "openid", "facebook"]
  # allowedDomains:
    # - "gmail.com"

# Definition of custom endpoints
endpoints:
  custom:
    - name: "Oobabooga"
      apiKey: "x"
      baseURL: "http://oobabooga.example.com:5000/v1"
      models:
        default: ["miqu"]
        fetch: true
      titleConvo: true
      titleModel: "Oobabooga"
      summarize: false
      summaryModel: "model"
      forcePrompt: false
      modelDisplayLabel: "Oobabooga"
```

Docker compose:

```yaml
version: "3.8"
services:
  api:
    # build:
    #   context: .
    #   dockerfile: Dockerfile.multi
    #   target: api-build
    image: ghcr.io/danny-avila/librechat-dev-api:latest
    container_name: LibreChat-API
    ports:
      - 3080:3080
    depends_on:
      - mongodb
    restart: always
    extra_hosts:
    - "host.docker.internal:host-gateway"
    env_file:
      - .env
    environment:
      - HOST=0.0.0.0
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongodb:27017/LibreChat
      - MEILI_HOST=http://meilisearch:7700
    volumes:
      - ./images:/app/client/public/images
      - ./librechat.yaml:/app/librechat.yaml

  client:
    build:
      context: .
      dockerfile: Dockerfile.multi
      target: prod-stage
    container_name: LibreChat-NGINX
    ports:
      - 80:80
      - 443:443
    depends_on:
      - api
    restart: always
    volumes:
      - ./client/nginx.conf:/etc/nginx/conf.d/default.conf

  mongodb:
    container_name: chat-mongodb
    # ports:  # Uncomment this to access mongodb from outside docker, not safe in deployment
    #   - 27018:27017
    image: mongo
    restart: always
    volumes:
      - ./data-node:/data/db
    command: mongod --noauth

  meilisearch:
    container_name: chat-meilisearch
    image: getmeili/meilisearch:v1.0
    # ports: # Uncomment this to access meilisearch from outside docker
    #   - 7700:7700 # if exposing these ports, make sure your master key is not the default value
    env_file:
      - .env
    environment:
      - MEILI_HOST=http://meilisearch:7700
      - MEILI_NO_ANALYTICS=true
    volumes:
      - ./meili_data:/meili_data

  watchtower:
    image: containrrr/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 50000
```

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
024-02-13 17:19:49 info: [Optional] Redis not initialized. Note: Redis support is experimental.
2024-02-13 17:19:52 info: Connected to MongoDB
2024-02-13 17:19:52 info: Loaded custom config file:
2024-02-13 17:19:52 info: {
  "version": "1.0.2",
  "cache": true,
  "registration": {
    "socialLogins": [
      "github",
      "google",
      "discord",
      "openid",
      "facebook"
    ]
  },
  "endpoints": {
    "custom": [
      {
        "name": "Oobabooga",
        "apiKey": "x",
        "baseURL": "http://oobabooga.example.com/v1",
        "models": {
          "default": [
            "miqu"
          ],
          "fetch": true
        },
        "titleConvo": true,
        "titleModel": "Oobabooga",
        "summarize": false,
        "summaryModel": "model",
        "forcePrompt": false,
        "modelDisplayLabel": "Oobabooga",
      }
    ]
  }
}
2024-02-13 17:19:52 info: Server listening on all interfaces at port 3080. Use http://localhost:3080 to access it
2024-02-13 17:29:30 error: [MeiliMongooseModel.findOneAndUpdate] Convo not found in MeiliSearch and will index 4c6f1140-12c8-459d-8c5b-b537f218cde7 Document `4c6f1140-12c8-459d-8c5b-b537f218cde7` not found.
2024-02-13 20:00:12 error: [MeiliMongooseModel.findOneAndUpdate] Convo not found in MeiliSearch and will index 51ba5921-84b4-4192-bd58-cdc3dc30d9fa Document `51ba5921-84b4-4192-bd58-cdc3dc30d9fa` not found.
```

### Screenshots

https://github.com/danny-avila/LibreChat/assets/37129444/781e8ff2-8915-496e-86ce-e577551e7655

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
