### ISSUE TITLE
[Bug]: LibreChat just outputs nonsense text using LiteLLM and Ollama

### ISSUE THREAD

**Issue by Linutux** [danny-avila/LibreChat#1958]
### What happened?

When even asking a simple question, the answer is just nonsense:

> You:
> What's your name?
> 
> AI:
> ::ass:tieWhatassie User youristant your Corieass duass he Wi AssistantistantWhat' Assistant?ass: name:istantsistant User Assistant heWhatistant4:: he Cor:::tass Wi
> ' name Cor

That is my librechat.yaml:

```
version: 1.0.1
cache: true
# see more config in https://docs.librechat.ai/install/configuration/ai_endpoints.html
endpoints:
  custom:
    # LiteLLM
    - name: "XXX.de"
      apiKey: "sk-XXXXXXXXXXXX"
      baseURL: "https://api.xxx.xxx.de"
      models:
        default: ["openhermes:latest", "starling-lm:7b", "openchat:latest", "dolphin-mistral:latest", "mistral-openorca:latest", "stable-code:latest"]
        fetch: true
      titleConvo: true
      titleModel: "openhermes:latest"
      summarize: false
      summaryModel: "openhermes:latest"
      forcePrompt: false
      modelDisplayLabel: "AI"
      drop_params: true
      stream: true
```

### Steps to Reproduce

1. Install LibreChat in docker
2. Connect to LiteLLM in docker
3. Connect LiteLLM to Ollama in docker

### What browsers are you seeing the problem on?

Firefox, Mobile (Android)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
