### ISSUE TITLE
[Bug]: Custom endpoints with same Base URL use first key [LiteLLM]

### ISSUE THREAD

**Issue by kosborn** [danny-avila/LibreChat#1983]
### What happened?

When using custom endpoints with different keys but the same base URL, only the first keys is used. This `baseUrlToNameMap` object groups by base URL only .This breaks down when using a service like LiteLLM, where the base URL is the same, but the API keys allow access to different models.  I would expect `name` or `apiKey` to be the unique key for the map here.

https://github.com/danny-avila/LibreChat/blob/2ea6e8c18a65ccb9c3aa93ea3e3ba9db9ad4adb5/api/server/services/Config/loadConfigModels.js#L45-L69

### Steps to Reproduce

1. Create multiple keys in LiteLLM with access to different models
2. Create associated custom endpoints in LibreChat with different keys but same base_url

```yaml
    - name: "LiteLLM"
      apiKey: "${LITELLM_ALL_MODELS}"
      baseURL: "${LITELLM_HOST}"
    - name: "OpenAI"
      apiKey: "${LITELLM_OPENAI_MODELS}"
      baseURL: "${LITELLM_SECOND_HOST}"
    - name: "Google"
      apiKey: "${LITELLM_GOOGLE_MODELS}"
      baseURL: "${LITELLM_SECOND_HOST}"
```

### Screenshots

![CleanShot 2024-03-05 at 12 31 20@2x](https://github.com/danny-avila/LibreChat/assets/723326/e32a3f59-df71-4bbc-ad4e-8fb24d4ebd98)
![CleanShot 2024-03-05 at 12 36 39@2x](https://github.com/danny-avila/LibreChat/assets/723326/220bd3cf-3539-4cd3-9ce0-f1d9bc116f9b)
![CleanShot 2024-03-05 at 12 36 46@2x](https://github.com/danny-avila/LibreChat/assets/723326/06bccc58-ee88-43c7-84ec-469c3c22d184)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
