### ISSUE TITLE
Getting error while configuring librechat with azure openAI

### ISSUE THREAD

**Issue by Chethanibms** [danny-avila/LibreChat#2221]
We are getting following errors on configuring librechat with azure openAI, Can someone help with this.

LibreChat-API     | 2024-03-27 06:19:39 warn: The `PLUGINS_USE_AZURE` environment variable (related to using Azure for Plugins) should not be used in combination with the `azureOpenAI` endpoint configuration, as you will experience conflicts and errors.
LibreChat-API     | 2024-03-27 06:19:52 error: Failed to fetch models from OpenAI API Something happened in setting up the request Cannot read properties of undefined (reading 'status')
LibreChat-API     | 2024-03-27 06:19:54 error: [MeiliMongooseModel.findOneAndUpdate] Convo not found in MeiliSearch and will index bc68285c-086c-4ff1-b666-21072d3d4dbc Document `bc68285c-086c-4ff1-b666-21072d3d4dbc` not found.
LibreChat-API     | 2024-03-27 06:19:55 warn: [OpenAIClient.chatCompletion][stream] API error
LibreChat-API     | 2024-03-27 06:19:55 error: [handleAbortError] AI response error; aborting request: Connection error.

**Comment by Chethanibms** [comment]
Our configuration file will like this.
We are using the latest version
```
# For more information, see the Configuration Guide:
# https://docs.librechat.ai/install/configuration/custom_config.html

# Configuration version (required)
version: 1.0.5

# Cache settings: Set to true to enable caching
cache: true

# Custom nterface configuration
interface:
  # Privacy policy settings
  privacyPolicy:
    externalUrl: 'https://librechat.ai/privacy-policy'
    openNewTab: true

  # Terms of service
  termsOfService:
    externalUrl: 'https://librechat.ai/tos'
    openNewTab: true

# Example Registration Object Structure (optional)
registration:
  socialLogins: ['github', 'google', 'discord', 'openid', 'facebook']
  # allowedDomains:
  # - "gmail.com"
# rateLimits:
#   fileUploads:
#     ipMax: 100
#     ipWindowInMinutes: 60  # Rate limit window for file uploads per IP
#     userMax: 50
#     userWindowInMinutes: 60  # Rate limit window for file uploads per user

# Definition of custom endpoints
endpoints:
  azureOpenAI:
    titleModel: "gpt-4-turbo"
    plugins: true
    groups:
    - group: "test" # arbitrary name
      apiKey: "xxxxx"
      instanceName: "xxxxx" # name of the resource group or instance
      version: "vision-preview"
      models:
        gpt-4:
          deploymentName: gpt-4
          version: "vision-preview"
```
