### ISSUE TITLE
Enhancement: Expose images as a configureable path

### ISSUE THREAD

**Issue by tip-dteller** [danny-avila/LibreChat#2290]
### What features would you like to see added?

When generating images using an assistant with Code Interperter.
the images are saved to disk at the path - `/client/public/images`

When reloading the container - specifically on Kubernetes platforms, a pod restart erases those images and users are not able to see or access them.

the image save path should be configurable - IMAGES_PATH=/images

### More details

None

### Which components are impacted by your request?

General

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Can't this be resolved by mounting the images path?

from the default compose file
```yaml
    volumes:
      - type: bind
        source: ./.env
        target: /app/.env
      - ./images:/app/client/public/images # relevant item
      - ./logs:/app/api/logs
```
