### ISSUE TITLE
Enhancement: Add Cloudflare Workers AI

### ISSUE THREAD

**Issue by lludlow** [danny-avila/LibreChat#2317]
### What features would you like to see added?

Add support for chat models, but also embedding, image-generating, tts, etc. via plugin for Cloudflare Workers AI

### More details

Cloudflare provides [various AI models](https://developers.cloudflare.com/workers-ai/models/) as well as [generous free allocation](https://developers.cloudflare.com/workers-ai/platform/pricing/). 

### Which components are impacted by your request?

Endpoints

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by whalygood** [comment]
It is already possible to integrate Cloudflare Workers AI with LibreChat by configuring a custom AI provider through the LiteLLM proxy. This translates the OpenAI style calls into something the Workers AI API can understand. 

https://autoize.com/llama-3-on-cloudflare-workers-ai-ai-at-the-edge/

I even have it functioning with the latest model, Llama 3 8B Instruct.

**Comment by HundSimon** [comment]
Cloudflare worker AI has [official OpenAI compatible API support](https://developers.cloudflare.com/workers-ai/configuration/open-ai-compatibility/). 
However, I always encounter the problem
`The response is incomplete; it's either still processing, was cancelled, or censored. Refresh or try a different prompt.` 
I dont's know what's wrong.
Here's my `librechat.yaml` config
```yaml
- name: 'WorkerAI'
  apiKey: '${WORKERAI_KEY}'
  baseURL: 'https://api.cloudflare.com/client/v4/accounts/{my account id}/ai/v1'
  models:
    default: [
      "@cf/qwen/qwen1.5-14b-chat-awq",
      "@hf/meta-llama/meta-llama-3-8b-instruct",
      ]
    fetch: false
  titleConvo: true
  titleModel: 'cf/qwen/qwen1.5-14b-chat-awq'
  # Recommended: Drop the stop parameter from the request as Openrouter models use a variety of stop tokens.
  dropParams: ['stop']
  modelDisplayLabel: 'Worker AI'
```

**Comment by kneelesh48** [comment]
Can someone please add workers ai support in librechat.yml

**Comment by marcozac** [comment]
Hi, I'm using Workers AI without any issues!

This is my `librechat.yaml`:
```yaml
endpoints:
  custom:
    - name: 'WorkersAI'
      apiKey: '${WORKERS_AI_API_KEY}'
      baseURL: 'https://api.cloudflare.com/client/v4/accounts/<account_id>/ai/v1'
      models:
        default: ['@cf/meta/llama-3.1-8b-instruct']
        fetch: true
      titleConvo: true
      titleModel: '@cf/meta/llama-3.1-8b-instruct'
      summarize: false
      summaryModel: '@cf/facebook/bart-large-cnn'
      forcePrompt: false
      modelDisplayLabel: 'Workers AI'
```

I've also written a fetcher for the modules, which you can find here: https://github.com/marcozac/LibreChat/tree/workers-ai.

It seems to work and passes the tests, but I believe it still needs some additional testing and some implementations, such as support for max_input_tokens, max_total_tokens, etc.

Also, I haven't figured out yet why the first message needs to be stopped manually, while all the others work fine without any problems.

![librechat-workersai-prompt](https://github.com/user-attachments/assets/2e2166a3-679a-439d-8c1b-1b45c3b1315a)
