### ISSUE TITLE
[Bug]:  issue while deploying librechat  on kubernetes cluster using helm

### ISSUE THREAD

**Issue by Harishkrishna17** [danny-avila/LibreChat#2352]
### What happened?

We are getting the below error when we deploy librechat on kubernetes clyuster

```
  {
    "code": "unrecognized_keys",
    "keys": [
      "azureOpenAI"
    ],
    "path": [
      "endpoints"
    ],
    "message": "Unrecognized key(s) in object: 'azureOpenAI'"
  },
  {
    "code": "custom",
    "message": "At least one `endpoints` field must be provided.",
    "path": [
      "endpoints"
    ]
  }
]
```

### Steps to Reproduce

1. Helm chart used : git@github.com:therin/librechat-helm-chart.git
2. Values file : 
```
# Default values for librechat.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/danny-avila/librechat
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podLabels: {}

podSecurityContext: {}
# fsGroup: 2000

securityContext: {}
# capabilities:
#   drop:
#   - ALL
# readOnlyRootFilesystem: true
# runAsNonRoot: true
# runAsUser: 1000

networkPolicies:
  enabled: true

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  # kubernetes.io/ingress.class: nginx
  # kubernetes.io/tls-acme: "true"
  hosts:
  - host: librechat-dev.talview.org
    paths:
    - path: /
      pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
# limits:
#   cpu: 100m
#   memory: 128Mi
# requests:
#   cpu: 100m
#   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

persistence:
  enabled: false
  existingClaim: ""
  accessMode: ReadWriteOnce
  size: "50Gi"
  storageClass: "-"

nodeSelector: {}

tolerations: []

affinity: {}

persistence:
  # -- Enable persistence using PVC
  enabled: false
  # -- PVC Access Mode
  accessMode: ReadWriteMany
  ## Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  # -- PVC Storage Class
  storageClass: "-"

  ## Data Persistent Volume existing claim name
  ## Requires persistence.enabled: true
  ## If defined, PVC must be created manually before volume will be bound
  # -- Existing PVC
  existingClaim: ""
  # -- PVC Storage Request
  size: 10Gi
  # -- Additional annotations for PVC
  annotations: {}

config:
  file:
    # Use librechat.yaml config file
    enabled: true
    configMapKeyRef:
      name: librechat-config
      key: librechat.yaml

  envSecrets:
    # Use this when using one k8s secret for multiply env secrets
    secretRef: librechat

    # Use this when using one k8s secret for each env secret
    secretKeyRef:
    #      - name: CREDS_IV
    #        secretName: librechat
    #        secretKey: CREDS_IV

  env:
    # Full list of possible values
    # https://github.com/danny-avila/LibreChat/blob/main/.env.example
    HOST: localhost
    PORT: 3080
    MONGO_URI: mongodb+srv://xxxxxx
    NO_INDEX: true
    DEBUG_LOGGING: true
    DEBUG_CONSOLE: false
    CONFIG_PATH: "/app/librechat.yaml"
    ENDPOINTS: azureOpenAI
    ANTHROPIC_API_KEY: user_provided
    BINGAI_TOKEN: user_provided
    GOOGLE_KEY: user_provided
    OPENAI_API_KEY: user_provided
    DEBUG_OPENAI: false
    ASSISTANTS_API_KEY: user_provided
    DEBUG_PLUGINS: true
    CREDS_KEY: f34be427ebb29de8d88c107a71546019685ed8b241d8f2ed00c3df97ad2566f0
    CREDS_IV: e2341419ec3dd3d19b13a1a87fafcbfb
    OPENAI_MODERATION: false
    BAN_VIOLATIONS: true
    BAN_DURATION: 1000 * 60 * 60 * 2
    BAN_INTERVAL: 20
    LOGIN_VIOLATION_SCORE: 1
    REGISTRATION_VIOLATION_SCORE: 1
    CONCURRENT_VIOLATION_SCORE: 1
    MESSAGE_VIOLATION_SCORE: 1
    NON_BROWSER_VIOLATION_SCORE: 20
    LOGIN_MAX: 7
    LOGIN_WINDOW: 5
    REGISTER_MAX: 5
    REGISTER_WINDOW: 60
    LIMIT_CONCURRENT_MESSAGES: true
    CONCURRENT_MESSAGE_MAX: 2
    LIMIT_MESSAGE_IP: true
    MESSAGE_IP_MAX: 40
    MESSAGE_IP_WINDOW: 1
    LIMIT_MESSAGE_USER: false
    MESSAGE_USER_MAX: 40
    MESSAGE_USER_WINDOW: 1
    ILLEGAL_MODEL_REQ_SCORE: 5
    CHECK_BALANCE: false
    ALLOW_EMAIL_LOGIN: true
    ALLOW_REGISTRATION: true
    ALLOW_SOCIAL_LOGIN: false
    ALLOW_SOCIAL_REGISTRATION: false
    SESSION_EXPIRY: 1000 * 60 * 15
    REFRESH_TOKEN_EXPIRY: (1000 * 60 * 60 * 24) * 7
    JWT_SECRET: 16f8c0ef4a5d391b26034086c628469d3f9f497f08163ab9b40137092f2909ef
    JWT_REFRESH_SECRET: eaa5191f2914e30b9387fd84e254e4ba6fc51b4654968a9b0803b456a54b8418
    APP_TITLE: LibreChat
    HELP_AND_FAQ_URL: https://librechat.ai
meilisearch:
  enabled: false
  image:
    # -- Meilisearch image name
    repository: getmeili/meilisearch
    # -- Meilisearch image tag
    tag: v1.6.2
    # -- Meilisearch image pull policy
    pullPolicy: IfNotPresent
    # -- Secret to authenticate against the docker registry
    pullSecret:

  # Environment loaded into the configMap
  environment:
    # -- Deactivates analytics
    MEILI_NO_ANALYTICS: true
    # -- Sets the environment. Either **production** or **development**
    MEILI_ENV: production
    # For production deployment, the environment MEILI_MASTER_KEY is required.
    # If MEILI_ENV is set to "production" without setting MEILI_MASTER_KEY, this
    # chart will automatically create a secure MEILI_MASTER_KEY and push it as a
    # secret. Otherwise the below value of MEILI_MASTER_KEY will be used instead.
    # MEILI_MASTER_KEY: ""
  # auth:
  #   # -- Use an existing Kubernetes secret for the MEILI_MASTER_KEY
  #   existingMasterKeySecret: "librechat"

  serviceAccount:
    # You can use a specific pre-created service account instead of
    # the one created by this chart.
    # Set create to false to prevent creating a service account and use your own.
    # -- Should this chart create a service account
    create: true
    # -- Custom service account name, if not created by this chart
    name: ''
    # -- Additional annotations for created service account
    annotations: {}

  podAnnotations: {}

  # -- Additional labels to add to the pod(s) only
  podLabels: {}

  # -- Additional labels to add to all resources
  customLabels: {}

  # -- Service HTTP port
  service:
    # -- Kubernetes Service type
    type: ClusterIP
    port: 7700
    # -- Additional annotations for service
    annotations: {}

  container:
    containerPort: 7700

  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    fsGroupChangePolicy: OnRootMismatch

  securityContext:
    capabilities:
      drop:
      - ALL
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true

  ingress:
    # -- Enable ingress controller resource
    enabled: false
    # -- Ingress ingressClassName
    className: nginx
    # -- Ingress annotations
    annotations: {}
    # kubernetes.io/ingress.class: nginx
    # -- Path within the host
    path: /
    # -- List of hostnames
    hosts:
    - meilisearch-example.local
    # -- TLS specification
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local

  persistence:
    # -- Enable persistence using PVC
    enabled: true
    # -- PVC Access Mode
    accessMode: ReadWriteOnce
    ## Persistent Volume Storage Class
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
    ##   GKE, AWS & OpenStack)
    ##
    # -- PVC Storage Class
    storageClass: "-"

    ## Data Persistent Volume existing claim name
    ## Requires persistence.enabled: true
    ## If defined, PVC must be created manually before volume will be bound
    # -- Existing PVC
    existingClaim: ""
    # -- PVC Storage Request
    size: 10Gi
    # -- Additional annotations for PVC
    annotations: {}
    volume:
      name: data
      mountPath: /meili_data

  # -- Resources allocation (Requests and Limits)
  resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

  # -- Additional volumes for pod
  volumes: []

  # -- Additional volumes to mount on pod
  volumeMounts: []

  # -- Additional containers for pod
  containers: []

  # -- Node labels for pod assignment
  nodeSelector: {}

  # -- Tolerations for pod assignment
  tolerations: []

  # -- Affinity for pod assignment
  affinity: {}

  # -- Pod command
  command: []

  # -- Monitoring with Prometheus Operator
  serviceMonitor:
    # -- Enable ServiceMonitor to configure scraping
    enabled: false
    # -- Set of labels to transfer from the Kubernetes Service onto the target
    additionalLabels: {}
    # -- Set scraping frequency
    interval: 1m
    # -- Set scraping timeout
    scrapeTimeout: 10s
    # -- Set path to metrics
    telemetryPath: /metrics
    # -- Set of labels to transfer from the Kubernetes Service onto the target
    targetLabels: []
    # -- MetricRelabelConfigs to apply to samples before ingestion
    metricRelabelings: []
    # -- Set relabel_configs as per https://prometheus.io/docs/prometheus/latest/configuration/configuration/#relabel_config
    relabelings: []

redis:
  enabled: false
  auth:
    enabled: true
    password: 'changeme'
    # name of an existing secret with Redis® credentials (instead of auth.password), must be created ahead of time
    existingSecret: ""
    # Password key to be retrieved from existing secret
    existingSecretPasswordKey: ""

### ref https://github.com/helm/charts/tree/master/stable/mongodb#configuration
##
mongodb:
  ## Enable or disable MongoDB dependency completely.
  enabled: false

  auth:
    # rootPassword:
    usernames:
    - librechat
    # passwords:
    databases:
    - librechat

  architecture: replicaset
  replicaCount: 1
  arbiter:
    enabled: false
    pdb:
      minAvailable: 0
  pdb:
    minAvailable: 0

    # key:

  persistence:
    enabled: true
    ## mongodb data Persistent Volume Storage Class
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
    ##   GKE, AWS & OpenStack)
    ##
    # storageClass: "-"
    accessMode: ReadWriteOnce
    size: 8Gi

  volumePermissions: {enabled: true}
```
My librechat.yaml file :

```
  librechat.yaml: |
    version: 1.0.5
    cache: true
    endpoints:
      azureOpenAI:
        titleModel: "gpt-3.5-turbo-1106"
        titleConvo: true
        plugins: true
        groups:
        - group: "azure-openai"
          apiKey: "zzzzz"
          instanceName: "xxxx-zzzz"
          deploymentName: xxxx
          version: "2024-03-01-preview"
          models:
            gpt-3.5-turbo-1106:
              deploymentName: xxxx
```

Once deployed below is the error 

```


### What browsers are you seeing the problem on?

_No response_

### Relevant log output

```shell
> LibreChat@0.6.10 backend
> cross-env NODE_ENV=production node api/server/index.js

2024-04-08 07:26:24 info: [Optional] Redis not initialized. Note: Redis support is experimental.
2024-04-08 07:26:26 info: Connected to MongoDB
2024-04-08 07:26:26 error: Invalid custom config file at /app/librechat.yaml [
  {
    "code": "unrecognized_keys",
    "keys": [
      "azureOpenAI"
    ],
    "path": [
      "endpoints"
    ],
    "message": "Unrecognized key(s) in object: 'azureOpenAI'"
  },
  {
    "code": "custom",
    "message": "At least one `endpoints` field must be provided.",
    "path": [
      "endpoints"
    ]
  }
]
2024-04-08 07:26:26 error: Invalid custom config file at /app/librechat.yaml [
  {
    "code": "unrecognized_keys",
    "keys": [
      "azureOpenAI"
    ],
    "path": [
      "endpoints"
    ],
    "message": "Unrecognized key(s) in object: 'azureOpenAI'"
  },
  {
    "code": "custom",
    "message": "At least one `endpoints` field must be provided.",
    "path": [
      "endpoints"
    ]
  }
]
```
```


### Screenshots

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
