### ISSUE TITLE
[Bug]: MongoDB Container Requires AVX Support on Non-AVX Systems

### ISSUE THREAD

**Issue by shahabafshar** [danny-avila/LibreChat#2361]
### What happened?

The MongoDB container fails to start on systems that do not support AVX (Advanced Vector Extensions) because MongoDB 5.0+ requires AVX support. This issue is particularly problematic for users running MongoDB in Docker containers on older hardware or virtualized environments that do not expose AVX features to the VM.

I expected the MongoDB container to start without requiring AVX support, or at least to have a clear alternative version of MongoDB that is compatible with non-AVX systems.

The lack of support for non-AVX systems in MongoDB 5.0+ versions causes significant inconvenience for users with older hardware. It would be beneficial to provide a MongoDB image that is compatible with these systems or to document a workaround for affected users.

Suggestion:
It would be beneficial for users with non-AVX compatible systems to have clear documentation or a version tag available for MongoDB images that do not require AVX support. Specifically, using **MongoDB version 4.4.18**, which is the latest version without the AVX requirement, could be highlighted as an alternative for those affected by this hardware compatibility issue.

Here is an example of how the Docker configuration can be adjusted to use **MongoDB 4.4.18**: (TESTED AND WORKS FINE)

```yaml
mongodb:
    container_name: chat-mongodb
    image: mongo:4.4.18
    restart: always
    user: "${UID}:${GID}"
    volumes:
      - ./data-node:/data/db
    command: mongod --noauth

### Steps to Reproduce

1. Attempt to start a MongoDB 5.0+ container on a system without AVX support.
2. Observe the warning message indicating the lack of AVX support.
3. The MongoDB service fails to start.

### What browsers are you seeing the problem on?

_No response_

### Relevant log output

```shell
WARNING: MongoDB 5.0+ requires a CPU with AVX support, and your current system does not appear to have that!
see https://jira.mongodb.org/browse/SERVER-54407
see also https://www.mongodb.com/community/forums/t/mongodb-5-0-cpu-intel-g4650-compatibility/116610/2
see also https://github.com/docker-library/mongo/issues/485#issuecomment-891991814
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
