### ISSUE TITLE
[Bug]: Unexpected Application error on Digital ocean Deploy

### ISSUE THREAD

**Issue by thesantatitan** [danny-avila/LibreChat#2478]
### What happened?

I have followed the steps exactly as given here [deploy](https://docs.librechat.ai/deployment/digitalocean.html). But I am getting this error when trying to access the page 
![image](https://github.com/danny-avila/LibreChat/assets/54684749/69255e7d-aaf2-447a-b563-86e4cf618499)

### Steps to Reproduce

1. Follow the steps in [this doc](https://docs.librechat.ai/deployment/digitalocean.html) 

### What browsers are you seeing the problem on?

Microsoft Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Thanks, I'm aware of this and already looking into fixes. Testing different build images currently, as well.

**Comment by danny-avila** [comment]
The last working image is from 21 hours ago, in case anyone wants to try it in a docker-compose.override.yml file:

```yaml
version: "3.8"
services:
  api:
    # build:
    #   context: .
    #   dockerfile: Dockerfile.multi
    #   target: api-build
    image: ghcr.io/danny-avila/librechat-dev-api:latest
```
