### ISSUE TITLE
[Question]: Order of available the models are random

### ISSUE THREAD

**Issue by simon-franz** [danny-avila/LibreChat#2522]
### What is your question?

I am using different models across AWS Bedrock and Azure OpenAI. Hence, I am using LiteLLM as a proxy. Unfortunately, it does not seem possible to specify the order of the listed models. With each restart of the Docker images, the order of the models is shuffled.

The models are specified in a collection as follows:
default: ["gpt-3.5-turbo","gpt-4","claude-v2.1","claude-v3-haiku","claude-v3-sonnet","mistral-7B","mistral-8x7B"]

However, the result seems to be random (see screenshot at the end)

Is there any way to specify the order of the models?

### More Details

Given that I have to use LiteLLM because of bedrock and azure and simple expense-tracking I would also like to split up the custom endpoint into 3 different endpoints, Like so

```
custom:
    - name: "Openai"
      apiKey: "xx"
      baseURL: "http://host.docker.internal:4000"
      models:
        default: ["gpt-3.5-turbo","gpt-4"]
        fetch: true
      modelDisplayLabel: "Openai"
custom:
    - name: "Antrophic"
      apiKey: "xx"
      baseURL: "http://host.docker.internal:4000"
      models:
        default: ["claude-v2.1","claude-v3-haiku","claude-v3-sonnet"]
        fetch: true
      modelDisplayLabel: "Antrophic"
custom:
    - name: "Mistral"
      apiKey: "xx"
      baseURL: "http://host.docker.internal:4000"
      models:
        default: ["mistral-7B","mistral-8x7B"]
        fetch: true
      modelDisplayLabel: "Mistral"
```

This would also enable to set the correct iconURL:
Maybe I have setup wrong and this is alredy possible?

Thanks in advance for any answer!

### What is the main subject of your question?

UI

### Screenshots

![image](https://github.com/danny-avila/LibreChat/assets/2931971/3f46da2b-b29d-4662-b9c4-8cc6f0fbba02)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
