### ISSUE TITLE
Enhancement: Code formatting for Ollama models

### ISSUE THREAD

**Issue by clstaudt** [danny-avila/LibreChat#2534]
### What features would you like to see added?

![Screenshot 2024-04-25 at 13 21 24](https://github.com/danny-avila/LibreChat/assets/875194/22a7d857-a8f5-4b33-8ed0-208472d4e030)

I have added an Ollama endpoint and am testing it with the orca-mini:13b model.

I would like to see the code in the output properly formatted (font, indentation, syntax highlighting)

### More details

```yaml
    - name: "Ollama"
      apiKey: "ollama"
      # use 'host.docker.internal' instead of localhost if running LibreChat in a docker container
      baseURL: "http://host.docker.internal:11434/v1/chat/completions" 
      models:
        default: [
          "orca-mini:13b",
          "dolphin-mixtral:latest",
          "llama3:latest",
          "starcoder2:15b",
          ]
        fetch: false # fetching list of models is not supported
      titleConvo: true
      titleModel: "orca-mini:13b"
      summarize: false
      summaryModel: "orca-mini:13b"
      forcePrompt: false
      modelDisplayLabel: "Ollama"
```

Not entirely sure if this is an issue of the model or of LibreChat.

### Which components are impacted by your request?

General

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
