### ISSUE TITLE
[Bug]: Autoplay TTS cycles through the voices for OpenAI when voices array is set (voice array throws an error)

### ISSUE THREAD

**Issue by AIndoria** [danny-avila/LibreChat#2842]
### What happened?

TTS cycles through the voice array (external : openAI) rather than sticking to one voice selected in user settings when "Autoplay latest message" is enabled.

That happens after the tts is set to

```
tts:
  openai:
    apiKey: '${TTS_API_KEY}'
    model: 'tts-1'
    voices: ['alloy', 'echo', 'fable', 'onyx', 'nova', 'shimmer']
```

Note `voices` instead of `voice` as mentioned in docs. using `voice` by itself gives the error:

```error: Invalid custom config file at /app/librechat.yaml [
  {
    "code": "invalid_type",
    "expected": "array",
    "received": "undefined",
    "path": [
      "tts",
      "openai",
      "voices"
    ],
    "message": "Required"
  }
]```

### Steps to Reproduce

1. Select a voice (say, Onyx) in user settings.
2. Enable "Autoplay Latest Message."
3. After each playback, the voices cycle through the voices array.

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

_No response_

### Screenshots

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
> TTS cycles through the voice array (external : openAI) rather than sticking to one voice selected in user settings when "Autoplay latest message" is enabled.

I'll look into it, I think I know why

> Edit: One more issue I noticed (do I open a new one for this?) : When autoplay is DISABLED, the "stop button" on TTS doesn't appear - When the LLM starts vocalizing, the button remains as a speaker icon. It only tends to appear when autoplay is enabled.

I can't reproduce this, can you send a video on the latest commit?

**Comment by danny-avila** [comment]
```
tts:
  openai:
    apiKey: '${TTS_API_KEY}'
    model: 'tts-1'
    voices: ['alloy', 'echo', 'fable', 'onyx', 'nova', 'shimmer']
```

On second thought, this is my exact config and I'm not having an issue, have you updated correctly?
