### ISSUE TITLE
[Bug]: Model List Not Updating When Switching to Custom Endpoint in Preset Editor

### ISSUE THREAD

**Issue by RedwindA** [danny-avila/LibreChat#2927]
### What happened?

When editing a Preset, if I switch to a custom endpoint (in the video it's `Claude`), the dropdown menu for the model list does not update to reflect the models available in the selected custom endpoint. I expected the model list to update accordingly.

https://github.com/danny-avila/LibreChat/assets/128586631/1b1fb943-feeb-40e6-bccb-dd8d66dab97b

console error:
![image](https://github.com/danny-avila/LibreChat/assets/128586631/fed57ec5-d2f5-480d-ac34-db8510584cd5)

endpoint config:
```
    - name: "Claude"
      iconURL: anthropic
      apiKey: "xxx"
      baseURL: "https://xxx.top/v1"
      models:
        default: ["claude-3-opus-20240229"]
        fetch: false
      titleConvo: true
      titleModel: "claude-3-opus-20240229"    
      modelDisplayLabel: "Claude"
      dropParams:
        - "stop"
        - "user"
        - "frequency_penalty"
        - "presence_penalty"
```

### Steps to Reproduce

1. Open the Preset editor.
2. Switch to a custom endpoint.
3. Observe that the model list in the dropdown menu does not update to show the models from the custom endpoint.

### What browsers are you seeing the problem on?

Microsoft Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
