### ISSUE TITLE
[Question]: Model specs usage with gptPlugins over Azure AI model issue

### ISSUE THREAD

**Issue by childotg** [danny-avila/LibreChat#3062]
### What is your question?

It may be connected to this #2972 but for me it does not work.
This is the configuration:
```
   - name: "image-generation"
      label: "Image generator"
      description: "Generate images starting form text."      
      preset:
        default: false
        endpoint: "gptPlugins"        
        tools: ["dalle"]                
        model: "gpt-35-turbo-0125"
        maxContextTokens: 8192 # Maximum context tokens
        max_tokens: 4096 # Maximum output tokens
        temperature: 0.3
        modelLabel: "AI"        
        greeting: |          
          Try to be accurate while describing your image and remember that each generation is independent.
```
         
This is the error:
![image](https://github.com/danny-avila/LibreChat/assets/13156626/2f25cf5c-87fc-43fc-a5ea-f9619052c6c7)

This model `gpt-35-turbo-0125` is defined as is:
endpoints:  
  azureOpenAI:    
    plugins: true
    assistants: false
    summarize: true
    summaryModel: "current_model"
    titleConvo: true
    titleModel: "current_model"
    titleMethod: "functions"
    groups:
    - group: "..." # arbitrary name
      apiKey: "..."
      instanceName: "..." # name of the resource group or instance
      version: "2024-03-01-preview"      
      assistants: false             
      models:              
        gpt-35-turbo-0125:
          deploymentName: gpt-35-turbo-0125
        gpt-4o-2024-05-13:
          deploymentName: gpt-4o-2024-05-13

### More Details

-

### What is the main subject of your question?

Endpoints

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
