### ISSUE TITLE
Enhancement: Azure OpenAI STT/TTS

### ISSUE THREAD

**Issue by hofq** [danny-avila/LibreChat#3094]
### What features would you like to see added?

I would love to configure TTS with an Azure Endpoint. I tried the following without success:
```yaml
                - group: "azure-openai" # arbitrary name
                  plugins: true
                  assistants: true
                  apiKey: "${AZURE_CFG_API_KEY}"
                  instanceName: "robads-ai-schweden"  # name of the resource group or instance
                  version: "2024-02-15-preview"
                  models:
                    gpt-3.5-turbo-1106:
                      deploymentName: gpt-35-turbo
                    gpt-4-vision-preview:
                      deploymentName: gpt-4-vision-preview
                    gpt-4o:
                      deploymentName: gpt-4o
                    tts:
                      deploymentName: tts-hd
```

### More details

I would love to use Azure OpenAI as TTS Endpoint

### Which components are impacted by your request?

Endpoints

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
