### ISSUE TITLE
[Bug]: Azureopen ai 404 model not found

### ISSUE THREAD

**Issue by Riser01** [danny-avila/LibreChat#3254]
### What happened?

I am newly setting up the chat ui in local docker , 

i have tested the azureopen ai keys and model deployment with normal python code it works .

but it fails when i add it to the YAML config , its not clear what the error actually is 

LibreChat         | 2024-07-03 13:39:26 warn: [OpenAIClient.chatCompletion][stream] API error
LibreChat         | 2024-07-03 13:39:26 error: [handleAbortError] AI response error; aborting request: 404 Resource not found                                                                                                               
chat-meilisearch  | 2024-07-03T13:39:26.526786Z  INFO HTTP request{method=POST host="meilisearch:7700" route=/indexes/messages/documents query_parameters= user_agent=node status_code=202}: meilisearch: close time.busy=2.84ms time.idle=7.95ms

### Steps to Reproduce

below is the current config librechat.YAML

```
  azureOpenAI:
    titleModel: "gpt-4o"
    titleConvo: true
    plugins: false
    summarize: true
    groups:
      - group: "eastus" # arbitrary name
        apiKey: "xx"
        instanceName: "xx" # name of the resource group or instance
        version: "2024-02-01"
        # baseURL: "https://${INSTANCE_NAME}.openai.azure.com/openai/deployments/${DEPLOYMENT_NAME}"
        models:
          gpt-4o:
            deploymentName: "gpt-4o"
            version: "2024-05-13"
          dall-e-3:
            deploymentName: "dall-e-3"
            version: "3.0"
          gpt-35-turbo:
            deploymentName: "gpt-35-turbo"
            version: "0301"
          gpt-35-turbo-16k:
            deploymentName: "gpt-35-turbo-16k"
            version: "0613"
          text-embedding-3-large:
            deploymentName: "text-embedding-3-large"
            version: "1"
          text-embedding-3-small:
            deploymentName: "text-embedding-3-small"
            version: "1"
          text-embedding-ada-002:
            deploymentName: "text-embedding-ada-002"
            version: "2"
      - group: "francecentral" # arbitrary name
        apiKey: "xx"
        instanceName: "xx" # name of the resource group or instance
        version: "2024-02-15-preview"
        # baseURL: "https://${INSTANCE_NAME}.openai.azure.com/openai/deployments/${DEPLOYMENT_NAME}"
        models:
          gpt-4:
            deploymentName: "gpt-4"
            version: "0613"
          gpt-4-32k:
            deploymentName: "gpt-4-32k"
            version: "0613"
```
docker override config : 
```
services:
  api:
    volumes:
    - type: bind
      source: ./librechat.yaml
      target: /app/librechat.yaml
    image: ghcr.io/danny-avila/librechat:latest
```

### Relevant log output

```shell
LibreChat         | 2024-07-03 13:39:26 warn: [OpenAIClient.chatCompletion][stream] API error
LibreChat         | 2024-07-03 13:39:26 error: [handleAbortError] AI response error; aborting request: 404 Resource not found                                                                                                               
chat-meilisearch  | 2024-07-03T13:39:26.526786Z  INFO HTTP request{method=POST host="meilisearch:7700" route=/indexes/messages/documents query_parameters= user_agent=node status_code=202}: meilisearch: close time.busy=2.84ms time.idle=7.95ms
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
