### ISSUE TITLE
[Bug]: titleConvo not working with assistants

### ISSUE THREAD

**Issue by Riser01** [danny-avila/LibreChat#3258]
### What happened?

title for Conversations not working with assistants 

this is the YAML i am using 
Please let me know of any improvment i can make

```
  azureOpenAI:
    titleModel: "gpt-3.5-turbo"
    summaryModel: "gpt-35-turbo-16k"
    titleConvo: true
    plugins: false
    summarize: true
    assistants: true
    azureAssistants:
  # "retrieval" omitted.
      capabilities: ["code_interpreter", "actions", "tools"]
    groups:
      - group: "eastus" # arbitrary name
        apiKey: "xxx"
        instanceName: "xx-test-oai-1" # name of the resource group or instance
        # deploymentName: "gpt-35-turbo"
        version: "2024-02-15-preview"
        # baseURL: "https://${INSTANCE_NAME}.openai.azure.com/openai/deployments/${DEPLOYMENT_NAME}"
        models:
          gpt-4o:
            deploymentName: "gpt-4o"
            # version: "2024-05-13"
          dall-e-3:
            deploymentName: "dall-e-3"
            # version: "3.0"
          gpt-35-turbo:
            deploymentName: "gpt-35-turbo"
            # version: "0301"
          gpt-35-turbo-16k:
            deploymentName: "gpt-35-turbo-16k"
            # version: "0613"
          text-embedding-3-large:
            deploymentName: "text-embedding-3-large"
            # version: "1"
          text-embedding-3-small:
            deploymentName: "text-embedding-3-small"
            # version: "1"
          text-embedding-ada-002:
            deploymentName: "text-embedding-ada-002"
            # version: "2"
      - group: "francecentral" # arbitrary name
        apiKey: "xxx"
        instanceName: "xx-oai-fc" # name of the resource group or instance
        version: "2024-02-15-preview"
        assistants: true
        # deploymentName: "gpt-4"
        # baseURL: "https://${INSTANCE_NAME}.openai.azure.com/openai/deployments/${DEPLOYMENT_NAME}"
        models:
          gpt-4:
            deploymentName: "gpt-4"
            # version: "0613"
          gpt-4-32k:
            deploymentName: "gpt-4-32k"
            # version: "0613"
```

### Steps to Reproduce

use the above YAML

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
no errors but cant see titles
```

### Screenshots

<img width="224" alt="image" src="https://github.com/danny-avila/LibreChat/assets/21278081/f81e4e59-1ebb-4fd8-9753-f6b720c369a6">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
