### ISSUE TITLE
[Question]: bingAI doesn't work with modelSpecs

### ISSUE THREAD

**Issue by trananhhh** [danny-avila/LibreChat#3300]
### What is your question?

I tried to config bingAI with modelSpecs in .yaml file but it doesn't work. When I select bingAI while another endpoint is selected, it doesn't change the selected value on the dropdown. 

### More Details

This is my config file:

```

modelSpecs:
  enforce: false
  prioritize: true
  list:
    # BingAI
    - name: 'copilot-sydney'
      iconURL: 'bingAI'
      label: 'Copilot Sydney'
      description: 'AI with internet access.'
      default: false
      preset:
        endpoint: 'bingAI'
        model: 'Sydney'
        # temperature: 0.7
        modelLabel: 'Copilot Sydney'
        greeting: |
          AI with internet access.

    - name: 'copilot-bingAI'
      iconURL: 'bingAI'
      label: 'Copilot BingAI'
      description: 'AI with internet access.'
      default: false
      preset:
        endpoint: 'bingAI'
        model: 'BingAI'
        # temperature: 0.7
        modelLabel: 'Copilot BingAI'
        greeting: |
          AI with internet access.
```

### What is the main subject of your question?

Endpoints

### Screenshots

![image](https://github.com/danny-avila/LibreChat/assets/32959690/e98c92a2-7b0c-41bc-9bf6-fc0153154186)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
