### ISSUE TITLE
[Bug]: Abnormal STT function

### ISSUE THREAD

**Issue by Passerby1011** [danny-avila/LibreChat#3404]
### What happened?

My stt function is using an exception always prompts: An error occurred while processing the audio,maybe the audio was too short
This is my configuration file: (TTS function is normal)
In fact, the stt function worked fine in previous versions with this configuration
Version：v0.7.4-rc1
```
version: 1.0.6
cache: true
speech:
  stt:
    openai:
      url: 'http://192.168.31.25:30000/v1/audio/transcriptions'
      apiKey: 'my-api-key'
      model: 'whisper-1'
  tts:
    openai:
      apiKey: 'my-api-key'
      model: 'tts-1'
      voices: ['male-botong', 'Podcast_girl', 'boyan_new_hailuo', 'female-shaonv', 'YaeMiko_hailuo', 'xiaoyi_mix_hailuo', 'xiaomo_sft', 'cove_test2_hailuo', 'scarlett_hailuo', 'Leishen2_hailuo', 'Zhongli_hailuo', 'Paimeng_hailuo', 'keli_hailuo', 'Hutao_hailuo', 'Xionger_hailuo', 'Haimian_hailuo', 'Robot_hunter_hailuo', 'Linzhiling_hailuo', 'huafei_hailuo', 'lingfeng_hailuo', 'male_dongbei_hailuo', 'Beijing_hailuo', 'JayChou_hailuo', 'Daniel_hailuo', 'Bingjiao_zongcai_hailuo', 'female-yaoyao-hd', 'murong_sft', 'shangshen_sft', 'kongchen_sft', 'shenteng2_hailuo', 'Guodegang_hailuo', 'yueyue_hailuo']
      url: "http://192.168.31.25:30000/v1/audio/speech"
```

### Steps to Reproduce

Normal use of STT

### Relevant log output

```shell
2024-07-20 08:24:42 info: Server listening on all interfaces at port 3080. Use http://localhost:3080 to access it
2024-07-20 08:24:56 error: An error occurred while preparing the OpenAI API STT request:  Cannot read properties of undefined (reading 'openai')
2024-07-20 08:24:56 error: An error occurred while processing the audio: Cannot read properties of undefined (reading 'status')
```

### Screenshots

![image](https://github.com/user-attachments/assets/1f84461b-6222-4a1a-b130-17343c5d9493)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
