### ISSUE TITLE
[Question]: Problems in configuring custom endpoint

### ISSUE THREAD

**Issue by poddamatt98** [danny-avila/LibreChat#3454]
### What is your question?

I have some problems configuring a custom endpoint.

### More Details

I have set up an [API gateway](https://github.com/npuichigo/openai_trtllm) translating OpenAI-style APIs to NVIDIA Triton Inference server APIs.
I added the container as a service to the LibreChat's docker compose, ensuring everything is running on the same network.
Then, I added a custom endpoint to the `libreconfig.yaml`:
```

    - name: 'Triton' # Unique name for the endpoint
      apiKey:  "x"
      baseURL: 'https://openai_trtllm:3100/v1'

      models:
        default: ['tensorrt_llm_bls']
        fetch: false

      titleConvo: true
      titleModel: "tensorrt_llm_bls"
      modelDisplayLabel: "Model"
```
I tested the connection and I am able to get the LLM response by posting through curl from LibreChat container to `https://openai_trtllm:3100/v1/chat/completions`.
The problem is that performing a prompt from LibreChat's UI something goes wrong.
The gateway API server does not receive any request, and LibreChats backend returns the following logs:
```
LibreChat        | 2024-07-26 08:57:28 warn: [OpenAIClient.chatCompletion][stream] API error
LibreChat        | 2024-07-26 08:57:28 error: [handleAbortError] AI response error; aborting request: Connection error.
```

I already tried to set `baseURL: 'https://openai_trtllm:3100/v1/chat/completions'` in ``librechat.yaml`, but nothing changed.

### What is the main subject of your question?

Endpoints

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
