### ISSUE TITLE
[Bug]: Title Generation does not work with llama3.1

### ISSUE THREAD

**Issue by Phthisicus** [danny-avila/LibreChat#3510]
### What happened?

I am running gemma2:9b and llama3.1:8b, and gemma2 does create titles. But llama3.1 does not.

My current config:

```
# Configuration version (required)
version: 1.1.5

# Cache settings: Set to true to enable caching
cache: true

endpoints:
  custom:
    - name: "Ollama"
      apiKey: "ollama"
      baseURL: "http://x.x.x.x:11434/v1/"
      models:
        default: [
          "gemma2:9b",
          "llama3.1:8b"
          ]
      fetch: false # fetching list of models is not supported
      titleConvo: true
      titleModel: "current_model"
      summarize: true
      summaryModel: "current_model"
      modelDisplayLabel: "Ollama"
```

### Steps to Reproduce

Switching from gemma2 to llama3.1 in the interface is enough to reproduce the problem.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
