### ISSUE TITLE
[Question]: Cannot Use Assistant if Either modelSelect or sidePanel Is Set to False

### ISSUE THREAD

**Issue by afunworm** [danny-avila/LibreChat#3524]
### What is your question?

Is it possible to create a chat UI, without modelSelect or sidePanel, that uses a default selected Assistant?

### More Details

Hello.

I'd like to just have a simple chat interface with the default assistant (OpenAI) with no sidebar or model select or endpoint select. However, whenever modelSelect or sidePanel is configured to be `false`, the chat won't work since it'll say "Please select an Assistant from the Sidebar menu". Both of these options must be turned on for the Assistant to work, even though there's only 1 Assistant.

Is it possible to select an Assistant by default without modelSelect or sidePanel enabled?

Below is the full `librechat.yml` file:

```
version: 1.0.9

# Cache settings: Set to true to enable caching
cache: true

# File upload
fileStrategy: local

# Custom interface configuration
interface:
  endpointsMenu: false # Different types of bots
  modelSelect: true # If this is false, Assistant won't work
  parameters: false
  sidePanel: true # If this is false, Assistant won't work
  presets: false

# Definition of custom endpoints
endpoints:
  assistants:
    disableBuilder: true # Disable Assistants Builder Interface by setting to `true`
    pollIntervalMs: 1000  # Polling interval for checking assistant updates, default 2000
    timeoutMs: 180000
    supportedIds:
      - "asst_id_goes_here"
    retrievalModels:
      - "gpt-4o"
    capabilities:
      - "code_interpreter"
      - "retrieval"
      - "actions"
      - "tools"
      - "image_vision"
```

### What is the main subject of your question?

UI, Endpoints

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
