### ISSUE TITLE
Enhancement: titleModel to support models from different endpoint providers

### ISSUE THREAD

**Issue by illgitthat** [danny-avila/LibreChat#3746]
### What features would you like to see added?

Currently, the `titleModel` option for each endpoint only supports providing a model that is available from the same provider.

It would be great if we could instead reference a model from a different endpoint.

Example: openai endpoint/provider has a gpt-4o model defined but an admin wants to use a gemini flash model for the title request.

This is a pretty minor enhancement, but would be a nice option.

### More details

Example implementation:

```yml
endpoints:
  custom:
    # Mistral AI API
    - name: "Mistral"
      apiKey: "${MISTRAL_API_KEY}"
      baseURL: "https://api.mistral.ai/v1"
      models:
        default: [
          "mistral-tiny",
          ]
        fetch: true
      titleConvo: true
      titleModel: "mistral-tiny"
      modelDisplayLabel: "Mistral"
      dropParams: ["stop", "user", "frequency_penalty", "presence_penalty"]
 
    # OpenRouter.ai
    - name: "OpenRouter"
      apiKey: "${OPENROUTER_KEY}"
      baseURL: "https://openrouter.ai/api/v1"
      models:
        default: ["openai/gpt-3.5-turbo"]
        fetch: true
      titleConvo: true
      titleModel: "mistral-tiny"
      titleEndpoint: "Mistral"
      summarize: false
      summaryModel: "gpt-3.5-turbo"
      forcePrompt: false
      modelDisplayLabel: "OpenRouter"
```

 (default `titleEndpoint` if null is the parent endpoint)

### Which components are impacted by your request?

Endpoints

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
