### ISSUE TITLE
[Bug]: Missing librechat.yaml docker binding

### ISSUE THREAD

**Issue by michnovka** [danny-avila/LibreChat#3754]
### What happened?

When running `docker compose up`, the api container complains it cannot find /app/librechat.yaml

### Steps to Reproduce

1. clone repo
2. docker compose up

### Relevant log output

```shell
LibreChat         | 2024-08-23 08:36:13 error: Config file YAML format is invalid: ENOENT: no such file or directory, open '/app/librechat.yaml'
```
```


### Screenshots

![image](https://github.com/user-attachments/assets/7a5f8a7b-78a1-498a-94ab-09dbf996b45f)


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by michnovka** [comment]
Adding:

```yaml
services:
  api:
    ....
    volumes:
    ....
      - ./librechat.yaml:/app/librechat.yaml
  
```

fixes the issue
