### ISSUE TITLE
[Question]: can't setup librechat.yaml to work with azureopani for love nor for money.

### ISSUE THREAD

**Issue by thisismygitrepo** [danny-avila/LibreChat#3810]
### What is your question?

I had 4 hours long session trying to configure librechat.yaml to work with my businsess subscription of azureopenai.
After a great deal of twidling I reached a point where the terminal log messages no longer showing any complaint about the syntax of the file. But, I still get `No key found. Please provide a key and try again.` no matter what model I choose.

### More Details

my `.env` is not touched.
My `librechat.yaml` is 

```yaml

endpoints:
  azureOpenAI:
    # Endpoint-level configuration
    titleModel: "shcc-azure-gpt4-turbo"
    plugins: true
    assistants: true
    groups:
    # Group-level configuration
    - group: "readacted1"
      apiKey: "redacted2"
      baseURL: "redacted1.openai.azure.com"
      instanceName: "redacted1"
      version: "1106-Preview"  # tried everything else to no avail.
      deploymentName: "gpt-4-turbo-default"
      assistants: true
      # Model-level configuration
      models:
        # default: ['gpt-4-turbo-default']
        # gpt-4:
        #   deploymentName: "gpt-4-turbo-default"
        #   version: "2024-03-01-preview"
        assistants: true
        gpt-4-turbo: true

```

This is at least one of hundereds of variants. In retrospect, I think the designers overcomplicated the config with the group concept. Any help would be appreciated.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
