### ISSUE TITLE
[Bug]: LibreChat 0.7.5rc Docker Node Build 

### ISSUE THREAD

**Issue by reramjiawan** [danny-avila/LibreChat#3816]
### What happened?

I am unable to create a local docker build since the new release.

I am using the docker.override.yaml

```
version: '3.4'

services:
   api:
     image: librechat
     build:
       context: .
       target: node
     volumes:
      - type: bind
        source: ./librechat.yaml
        target: /app/librechat.yaml
```

Vite seems stuck on transforming the modules. I don't know if this just a problem on my own machine or if others are facing the same issue.

### Steps to Reproduce

1. Use docker.override as shown above
2. docker-compose up
3. Docker is forever stuck same goes for a normal production build

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
