### ISSUE TITLE
Enhancement: Usage of tools (plugins) in modelSpecs for other endpoints (azureOpenAI)

### ISSUE THREAD

**Issue by dareima** [danny-avila/LibreChat#3860]
### What features would you like to see added?

Predefined plugins for everyone when using modelSpecs with the Azure OpenAI endpoint (or all endpoints in general).

### More details

Currently, it seems that tools (plugins) like DALL-E, Google, Web Search etc., can only be predefined via modelSpecs when the 'gptPlugins' endpoint is used. I haven't tried this yet but derived that information from this discussion:

[#2972](https://github.com/danny-avila/LibreChat/discussions/2972)

It would be of great help when the use of certain plugins via the 'tools' preset would also work with modelSpecs in the azureOpenAI endpoint.

Like this:

```
modelSpecs:
  enforce: false
  prioritize: true
  list:
    - name: "some name"
      label: "GPT-4o-mini"
      description: "Fast AI Chatbot"
      iconURL: https://someurl/favicon.ico
      preset:
        default: true
        endpoint: "azureOpenAI"
        model: "ai-hub-swe-gpt-4o-mini"
        tools: ["azure-ai-search", "google", "dalle"]
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
