### ISSUE TITLE
[Bug]: ModelSpec Name not displayed correctly

### ISSUE THREAD

**Issue by SwiftDev29** [danny-avila/LibreChat#4223]
### What happened?

If my model spec’s name is “My custom AI”, then even though i can select that name from the models list, it shows “GPT-4o” as the name of the AI during the chat.
The modelspec is set to a custom OpenAI compatible endpoint with “chatgpt-4o-latest”.
Enforce and prioritize set to true
The chat presets work as expected. (Presets, endpoints etc.)

### Steps to Reproduce

1. Set up a ModelSpec with an OPenAI Compatible endpoint 
2. Set enforce and prioritize to true. 
3. Start a new chat with the ModelSpec.

### What browsers are you seeing the problem on?

Safari, Mobile (iOS), Mobile (Android)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
In the `preset` section of the model spec, you need to explicitly define the `modelLabel`:

```yaml
modelSpecs:
  enforce: true
  prioritize: true
  list:
      - name: "image-generation"
        label: "Image generator"
        description: "Generate images starting form text."      
        preset:
          default: false
          endpoint: "gptPlugins"        
          tools: ["dalle"]                
          model: "gpt-4o-mini"
          temperature: 0.3
          modelLabel: "Image generator"        
          greeting: |          
            Try to be accurate while describing your image and remember that each generation is independent.
          agentOptions:
            model: "gpt-4o-mini"
```
