### ISSUE TITLE
[Bug]: Unexpected Application Error when using `modelSpec` in browser

### ISSUE THREAD

**Issue by sreevatsank1999** [danny-avila/LibreChat#4313]
### What happened?

I get the following error when I try to select a modelSpec from the dropdown menu in the browser

```
Unexpected Application Error!
[ { "received": "None", "code": "invalid_enum_value", "options": [ "azureOpenAI", "openAI", "bingAI", "chatGPTBrowser", "google", "gptPlugins", "anthropic", "assistants", "azureAssistants", "agents", "custom", "bedrock" ], "path": [ "endpointType" ], "message": "Invalid enum value. Expected 'azureOpenAI' | 'openAI' | 'bingAI' | 'chatGPTBrowser' | 'google' | 'gptPlugins' | 'anthropic' | 'assistants' | 'azureAssistants' | 'agents' | 'custom' | 'bedrock', received 'None'" } ]
ZodError
    at get error (https://chat-wcsng.nrp-nautilus.io/assets/vendor.BujiSg_e.js:84:12611)
    at yr.parse (https://chat-wcsng.nrp-nautilus.io/assets/vendor.BujiSg_e.js:84:14848)
    at Q8 (https://chat-wcsng.nrp-nautilus.io/assets/index.js:3365:184842)
    at A7 (https://chat-wcsng.nrp-nautilus.io/assets/vendor.BujiSg_e.js:38:19557)
    at k$ (https://chat-wcsng.nrp-nautilus.io/assets/vendor.BujiSg_e.js:40:3150)
    at Qee (https://chat-wcsng.nrp-nautilus.io/assets/vendor.BujiSg_e.js:40:44947)
    at zee (https://chat-wcsng.nrp-nautilus.io/assets/vendor.BujiSg_e.js:40:39876)
    at pSe (https://chat-wcsng.nrp-nautilus.io/assets/vendor.BujiSg_e.js:40:39799)
    at v2 (https://chat-wcsng.nrp-nautilus.io/assets/vendor.BujiSg_e.js:40:39648)
    at j$ (https://chat-wcsng.nrp-nautilus.io/assets/vendor.BujiSg_e.js:40:36004)
```

Refreshing the screen clears the error

I am experiencing this error after upgrading to the latest main branch commit 2ca257dfb96d97456d1c66e5e38e499a59e3a10b from a version from 2 weeks ago

### Steps to Reproduce

1. Login
2. Select a modelSpec from the dropdown menu

Config files of deployment: 
<details><summary>.env</summary>

```bash
#=====================================================================#
#                       LibreChat Configuration                       #
#=====================================================================#
# Please refer to the reference documentation for assistance          #
# with configuring your LibreChat environment.                        #
#                                                                     #
# https://www.librechat.ai/docs/configuration/dotenv                  #
#=====================================================================#

#==================================================#
#               Server Configuration               #
#==================================================#

HOST=localhost
PORT=3080

MONGO_URI=mongodb://127.0.0.1:27017/LibreChat

DOMAIN_CLIENT=https://chat-wcsng.nrp-nautilus.io
DOMAIN_SERVER=https://chat-wcsng.nrp-nautilus.io

NO_INDEX=true

#===============#
# JSON Logging  #
#===============#

# Use when process console logs in cloud deployment like GCP/AWS
CONSOLE_JSON=true

#===============#
# Debug Logging #
#===============#

DEBUG_LOGGING=false
DEBUG_CONSOLE=true

#=============#
# Permissions #
#=============#

# UID=1000
# GID=1000

#===============#
# Configuration #
#===============#
# Use an absolute path, a relative path, or a URL

# CONFIG_PATH="/alternative/path/to/librechat.yaml"

#===================================================#
#                     Endpoints                     #
#===================================================#

# ENDPOINTS=openAI,assistants,azureOpenAI,bingAI,google,gptPlugins,anthropic
ENDPOINTS=openAI,assistants,bingAI,google,gptPlugins,anthropic

# PROXY=

#===================================#
# Known Endpoints - librechat.yaml  #
#===================================#
# https://www.librechat.ai/docs/configuration/librechat_yaml/ai_endpoints

# ANYSCALE_API_KEY=
# APIPIE_API_KEY=
# COHERE_API_KEY=
# DEEPSEEK_API_KEY=
# DATABRICKS_API_KEY=
# FIREWORKS_API_KEY=
# GROQ_API_KEY=
# HUGGINGFACE_TOKEN=
# MISTRAL_API_KEY=
# OPENROUTER_KEY=
# PERPLEXITY_API_KEY=
# SHUTTLEAI_API_KEY=
# TOGETHERAI_API_KEY=
# UNIFY_API_KEY=

#============#
# Anthropic  #
#============#

# ANTHROPIC_API_KEY=
ANTHROPIC_MODELS=claude-3-5-sonnet-20240620,claude-3-opus-20240229,claude-3-haiku-20240307
# ANTHROPIC_REVERSE_PROXY=
ANTHROPIC_TITLE_MODEL=claude-3-haiku-20240307
#============#
# Azure      #
#============#

# Note: these variables are DEPRECATED
# Use the `librechat.yaml` configuration for `azureOpenAI` instead
# You may also continue to use them if you opt out of using the `librechat.yaml` configuration

# AZURE_OPENAI_DEFAULT_MODEL=gpt-3.5-turbo # Deprecated
# AZURE_OPENAI_MODELS=gpt-3.5-turbo,gpt-4 # Deprecated
# AZURE_USE_MODEL_AS_DEPLOYMENT_NAME=TRUE # Deprecated
# AZURE_API_KEY= # Deprecated
# AZURE_OPENAI_API_INSTANCE_NAME= # Deprecated
# AZURE_OPENAI_API_DEPLOYMENT_NAME= # Deprecated
# AZURE_OPENAI_API_VERSION= # Deprecated
# AZURE_OPENAI_API_COMPLETIONS_DEPLOYMENT_NAME= # Deprecated
# AZURE_OPENAI_API_EMBEDDINGS_DEPLOYMENT_NAME= # Deprecated
# PLUGINS_USE_AZURE="true" # Deprecated

#============#
# BingAI     #
#============#

BINGAI_TOKEN=user_provided
# BINGAI_HOST=https://cn.bing.com

#=================#
#   AWS Bedrock   #
#=================#

# BEDROCK_AWS_DEFAULT_REGION=us-east-1 # A default region must be provided
# BEDROCK_AWS_ACCESS_KEY_ID=someAccessKey
# BEDROCK_AWS_SECRET_ACCESS_KEY=someSecretAccessKey

# Note: This example list is not meant to be exhaustive. If omitted, all known, supported model IDs will be included for you.
# BEDROCK_AWS_MODELS=anthropic.claude-3-5-sonnet-20240620-v1:0,meta.llama3-1-8b-instruct-v1:0

# See all Bedrock model IDs here: https://docs.aws.amazon.com/bedrock/latest/userguide/model-ids.html#model-ids-arns

# Notes on specific models:
# 'ai21.j2-mid-v1', # Not supported, as it doesn't support streaming
# 'ai21.j2-ultra-v1', # Not supported, as it doesn't support conversation history

#============#
# Google     #
#============#

# GOOGLE_KEY=
# GOOGLE_REVERSE_PROXY=

# Gemini API  
GOOGLE_MODELS=gemini-1.5-flash,gemini-1.5-pro
GOOGLE_TITLE_MODEL=gemini-1.5-flash
# Vertex AI
# GOOGLE_MODELS=gemini-1.5-flash-preview-0514,gemini-1.5-pro-preview-0514,gemini-1.0-pro-vision-001,gemini-1.0-pro-002,gemini-1.0-pro-001,gemini-pro-vision,gemini-1.0-pro

# GOOGLE_TITLE_MODEL=gemini-pro

# Google Safety Settings
# NOTE: These settings apply to both Vertex AI and Gemini API (AI Studio)
#
# For Vertex AI:
# To use the BLOCK_NONE setting, you need either:
# (a) Access through an allowlist via your Google account team, or
# (b) Switch to monthly invoiced billing: https://cloud.google.com/billing/docs/how-to/invoiced-billing
#
# For Gemini API (AI Studio):
# BLOCK_NONE is available by default, no special account requirements.
#
# Available options: BLOCK_NONE, BLOCK_ONLY_HIGH, BLOCK_MEDIUM_AND_ABOVE, BLOCK_LOW_AND_ABOVE
#
# GOOGLE_SAFETY_SEXUALLY_EXPLICIT=BLOCK_ONLY_HIGH
# GOOGLE_SAFETY_HATE_SPEECH=BLOCK_ONLY_HIGH
# GOOGLE_SAFETY_HARASSMENT=BLOCK_ONLY_HIGH
# GOOGLE_SAFETY_DANGEROUS_CONTENT=BLOCK_ONLY_HIGH

#============#
# OpenAI     #
#============#

# OPENAI_API_KEY=
OPENAI_MODELS=gpt-4o-mini,o1-mini,o1-preview,gpt-4o,gpt-4

DEBUG_OPENAI=false

TITLE_CONVO=true
OPENAI_TITLE_MODEL=gpt-4o-mini

OPENAI_SUMMARIZE=true
OPENAI_SUMMARY_MODEL=gpt-4o-mini

# OPENAI_FORCE_PROMPT=true

# OPENAI_REVERSE_PROXY=

# OPENAI_ORGANIZATION=

#====================#
#   Assistants API   #
#====================#

ASSISTANTS_API_KEY=user_provided
# ASSISTANTS_BASE_URL=
ASSISTANTS_MODELS=gpt-4o-mini,gpt-4o,gpt-4

#==========================#
#   Azure Assistants API   #
#==========================#

# Note: You should map your credentials with custom variables according to your Azure OpenAI Configuration
# The models for Azure Assistants are also determined by your Azure OpenAI configuration.

# More info, including how to enable use of Assistants with Azure here:
# https://www.librechat.ai/docs/configuration/librechat_yaml/ai_endpoints/azure#using-assistants-with-azure

#============#
# OpenRouter #
#============#
# !!!Warning: Use the variable above instead of this one. Using this one will override the OpenAI endpoint
# OPENROUTER_API_KEY=

#============#
# Plugins    #
#============#

PLUGIN_MODELS=gpt-4o-mini,gpt-4o,gpt-4

DEBUG_PLUGINS=false

# CREDS_KEY=
# CREDS_IV=

# Azure AI Search
#-----------------
# AZURE_AI_SEARCH_SERVICE_ENDPOINT=
# AZURE_AI_SEARCH_INDEX_NAME=
# AZURE_AI_SEARCH_API_KEY=

# AZURE_AI_SEARCH_API_VERSION=
# AZURE_AI_SEARCH_SEARCH_OPTION_QUERY_TYPE=
# AZURE_AI_SEARCH_SEARCH_OPTION_TOP=
# AZURE_AI_SEARCH_SEARCH_OPTION_SELECT=

# DALL·E
#----------------
# DALLE_API_KEY=
# DALLE3_API_KEY=
# DALLE2_API_KEY=
# DALLE3_SYSTEM_PROMPT=
# DALLE2_SYSTEM_PROMPT=
# DALLE_REVERSE_PROXY=
# DALLE3_BASEURL=
# DALLE2_BASEURL=

# DALL·E (via Azure OpenAI)
# Note: requires some of the variables above to be set
#----------------
# DALLE3_AZURE_API_VERSION=
# DALLE2_AZURE_API_VERSION=

# Google
#-----------------
# GOOGLE_SEARCH_API_KEY=
# GOOGLE_CSE_ID=

# SerpAPI
#-----------------
# SERPAPI_API_KEY=

# Stable Diffusion
#-----------------
# SD_WEBUI_URL=

# Tavily
#-----------------
# TAVILY_API_KEY=

# Traversaal
#-----------------
# TRAVERSAAL_API_KEY=

# WolframAlpha
#-----------------
# WOLFRAM_APP_ID=

# Zapier
#-----------------
# ZAPIER_NLA_API_KEY=


#==================================================#
#                      Search                      #
#==================================================#

SEARCH=true
MEILI_NO_ANALYTICS=true
MEILI_HOST=http://127.0.0.1:7700
# MEILI_MASTER_KEY=

#==================================================#
#          Speech to Text & Text to Speech         #
#==================================================#

# STT_API_KEY=
# TTS_API_KEY=

#==================================================#
#                        RAG                       #
#==================================================#
# More info: https://www.librechat.ai/docs/configuration/rag_api

RAG_API_URL=http://127.0.0.1:8000
RAG_PORT=8000 
EMBEDDINGS_PROVIDER=ollama
OLLAMA_BASE_URL=http://xyz:11434
EMBEDDINGS_MODEL=nomic-embed-text

#===================================================#
#                    User System                    #
#===================================================#

#========================#
# Moderation             #
#========================#

OPENAI_MODERATION=false
# OPENAI_MODERATION_API_KEY=
# OPENAI_MODERATION_REVERSE_PROXY=

BAN_VIOLATIONS=true
BAN_DURATION=1000 * 60 * 60 * 2
BAN_INTERVAL=20

LOGIN_VIOLATION_SCORE=1
REGISTRATION_VIOLATION_SCORE=1
CONCURRENT_VIOLATION_SCORE=1
MESSAGE_VIOLATION_SCORE=1
NON_BROWSER_VIOLATION_SCORE=20

LOGIN_MAX=7
LOGIN_WINDOW=5
REGISTER_MAX=5
REGISTER_WINDOW=60

LIMIT_CONCURRENT_MESSAGES=true
CONCURRENT_MESSAGE_MAX=4

LIMIT_MESSAGE_IP=true
MESSAGE_IP_MAX=25
MESSAGE_IP_WINDOW=1

LIMIT_MESSAGE_USER=true
MESSAGE_USER_MAX=25
MESSAGE_USER_WINDOW=1

ILLEGAL_MODEL_REQ_SCORE=5

#========================#
# Balance                #
#========================#

CHECK_BALANCE=true

#========================#
# Registration and Login #
#========================#

ALLOW_EMAIL_LOGIN=false
ALLOW_REGISTRATION=false
ALLOW_SOCIAL_LOGIN=true
ALLOW_SOCIAL_REGISTRATION=true
ALLOW_PASSWORD_RESET=false
ALLOW_ACCOUNT_DELETION=false # note: enabled by default if omitted/commented out
ALLOW_UNVERIFIED_EMAIL_LOGIN=false

SESSION_EXPIRY=(1000 * 60 * 60 * 24) * 3
REFRESH_TOKEN_EXPIRY=(1000 * 60 * 60 * 24) * 7

# JWT_SECRET=
# JWT_REFRESH_SECRET=

# Discord
# DISCORD_CLIENT_ID=
# DISCORD_CLIENT_SECRET=
# DISCORD_CALLBACK_URL=/oauth/discord/callback

# Facebook
# FACEBOOK_CLIENT_ID=
# FACEBOOK_CLIENT_SECRET=
# FACEBOOK_CALLBACK_URL=/oauth/facebook/callback

# GitHub
# GITHUB_CLIENT_ID=
# GITHUB_CLIENT_SECRET=
# GITHUB_CALLBACK_URL=/oauth/github/callback

# Google
GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=
GOOGLE_CALLBACK_URL=/oauth/google/callback

# OpenID
# OPENID_CLIENT_ID=
# OPENID_CLIENT_SECRET=
# OPENID_ISSUER=
# OPENID_SESSION_SECRET=
# OPENID_SCOPE="openid profile email"
# OPENID_CALLBACK_URL=/oauth/openid/callback
# OPENID_REQUIRED_ROLE=
# OPENID_REQUIRED_ROLE_TOKEN_KIND=
# OPENID_REQUIRED_ROLE_PARAMETER_PATH=

# OPENID_BUTTON_LABEL=
# OPENID_IMAGE_URL=

## LDAP
# LDAP_URL=
# LDAP_BIND_DN=
# LDAP_BIND_CREDENTIALS=
# LDAP_USER_SEARCH_BASE=
# LDAP_SEARCH_FILTER=mail={{username}}
# LDAP_CA_CERT_PATH=
# LDAP_TLS_REJECT_UNAUTHORIZED=
# LDAP_LOGIN_USES_USERNAME=true
# LDAP_ID=
# LDAP_USERNAME=
# LDAP_FULL_NAME=

#========================#
# Email Password Reset   #
#========================#

# EMAIL_SERVICE=
# EMAIL_HOST=
# EMAIL_PORT=25
# EMAIL_ENCRYPTION=
# EMAIL_ENCRYPTION_HOSTNAME=
# EMAIL_ALLOW_SELFSIGNED=
# EMAIL_USERNAME=
# EMAIL_PASSWORD=
# EMAIL_FROM_NAME=
# EMAIL_FROM=noreply@librechat.ai

#========================#
# Firebase CDN           #
#========================#

# FIREBASE_API_KEY=
# FIREBASE_AUTH_DOMAIN=
# FIREBASE_PROJECT_ID=
# FIREBASE_STORAGE_BUCKET=
# FIREBASE_MESSAGING_SENDER_ID=
# FIREBASE_APP_ID=

#========================#
# Shared Links           #
#========================#

ALLOW_SHARED_LINKS=true
ALLOW_SHARED_LINKS_PUBLIC=true

#==============================#
# Static File Cache Control    #
#==============================#

# Leave commented out to use defaults: 1 day (86400 seconds) for s-maxage and 2 days (172800 seconds) for max-age
# NODE_ENV must be set to production for these to take effect
# STATIC_CACHE_MAX_AGE=172800
# STATIC_CACHE_S_MAX_AGE=86400

# If you have another service in front of your LibreChat doing compression, disable express based compression here
# DISABLE_COMPRESSION=true

#===================================================#
#                        UI                         #
#===================================================#

APP_TITLE="ChatStudio"
CUSTOM_FOOTER="ChatStudio: A One-Stop Solution for All Your LLM Needs | WCSNG"
HELP_AND_FAQ_URL=https://librechat.ai

SHOW_BIRTHDAY_ICON=true

# Google tag manager id
#ANALYTICS_GTM_ID=user provided google tag manager id

#==================================================#
#                      Others                      #
#==================================================#
#   You should leave the following commented out   #

# NODE_ENV=

# REDIS_URI=
# USE_REDIS=

# E2E_USER_EMAIL=
# E2E_USER_PASSWORD=
```

</details> 

<details><summary>librechat.yaml</summary>

```yaml
# For more information, see the Configuration Guide:
# https://www.librechat.ai/docs/configuration/librechat_yaml

# Configuration version (required)
version: 1.1.5

# Cache settings: Set to true to enable caching
cache: true

# Custom interface configuration
interface:
  # Privacy policy settings
  privacyPolicy:
    externalUrl: 'https://librechat.ai/privacy-policy'
    openNewTab: true

  # Terms of service
  termsOfService:
    externalUrl: 'https://librechat.ai/tos'
    openNewTab: true

  endpointsMenu: true
  modelSelect: true
  parameters: true
  sidePanel: true
  presets: true
  prompts: true
  bookmarks: true
  multiConvo: true

# Example Registration Object Structure (optional)
registration:
  socialLogins: ['google']
  allowedDomains:
  - "ucsd.edu"

rateLimits:
  fileUploads:
    ipMax: 100
    ipWindowInMinutes: 60  # Rate limit window for file uploads per IP
    userMax: 50
    userWindowInMinutes: 60  # Rate limit window for file uploads per user
  conversationsImport:
    ipMax: 100
    ipWindowInMinutes: 60  # Rate limit window for conversation imports per IP
    userMax: 50
    userWindowInMinutes: 60  # Rate limit window for conversation imports per user

# Plugins enabled
includedTools: ["google", "wolfram", "web-browser", "dalle", "stable-diffusion", "scholarai", "askyourpdf", "image_prompt_enhancer"]

# Model Specifications
modelSpecs:
  enforce: false
  prioritize: false
  list:
    - name: defaultgpt
      label: Standard
      description: ""
      default: false
      showIconInMenu: true
      showIconInHeader: false
      preset:
        endpoint: None 
        maxContextTokens: 4096
        resendFiles: false
        imageDetail: "low"
    - name: hushgpt
      label: hushGPT
      description: "A no non-sense model, it is direct and concise"
      iconURL: "https://chat-wcsng.nrp-nautilus.io/assets/hushgpt.svg"
      default: true
      showIconInMenu: true
      showIconInHeader: false
      preset:
        endpoint: None 
        promptPrefix: "Be concise and direct in your response"
        maxContextTokens: 4096
        resendFiles: false
        imageDetail: "low"

# Definition of custom endpoints
endpoints:
  assistants:
  #   disableBuilder: false # Disable Assistants Builder Interface by setting to `true`
    pollIntervalMs: 3000  # Polling interval for checking assistant updates
    timeoutMs: 180000  # Timeout for assistant operations
  #   # Should only be one or the other, either `supportedIds` or `excludedIds`
  #   supportedIds: ["asst_supportedAssistantId1", "asst_supportedAssistantId2"]
  #   # excludedIds: ["asst_excludedAssistantId"]
  #   # (optional) Models that support retrieval, will default to latest known OpenAI models that support the feature
    retrievalModels: ["gpt-4-turbo-preview"]
  #   # (optional) Assistant Capabilities available to all users. Omit the ones you wish to exclude. Defaults to list below.
    capabilities: ["code_interpreter", "retrieval", "actions", "tools", "image_vision"]
  custom:
    - name: "Perplexity"
      apiKey: "${PERPLEXITY_API_KEY}"
      baseURL: "https://api.perplexity.ai/"
      models:
        default: [
          "mistral-7b-instruct",
          "sonar-small-chat",
          "sonar-small-online",
          "sonar-medium-chat",
          "sonar-medium-online"
          ]
        fetch: false # fetching list of models is not supported
      titleConvo: true
      titleModel: "sonar-medium-chat"
      summarize: true
      summaryModel: "sonar-medium-chat"
      forcePrompt: false
      dropParams: ["stop", "frequency_penalty"]
      modelDisplayLabel: "Perplexity"

    - name: "Self Hosted"
      apiKey: "ollama"
      # use 'host.docker.internal' instead of localhost if running LibreChat in a docker container
      baseURL: "http://xyz:11434/v1/chat/completions" 
      models:
        default: [
          "llama3.1:70b",
          "llava:34b",
          "codestral:22b",
          "deepseek-coder:33b",
          "codellama:70b"
          ]
        # fetching list of models is supported but the `name` field must start
        # with `ollama` (case-insensitive), as it does in this example.
        fetch: false
      titleConvo: true
      titleModel: "current_model"
      summarize: true
      summaryModel: "current_model"
      forcePrompt: false
      modelDisplayLabel: "Ollama"

fileConfig:
  endpoints:
    assistants:
      fileLimit: 250
      fileSizeLimit: 15  # Maximum size for an individual file in MB
      totalSizeLimit: 500  # Maximum total size for all files in a single request in MB
      supportedMimeTypes:
        - "image/.*"
        - "application/pdf"
        - "text/.*"
        - "application/msword"
        - "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
    openAI:
      disabled: false  # Disables file uploading to the OpenAI endpoint
    default:
      totalSizeLimit: 200
    # YourCustomEndpointName:
    #   fileLimit: 2
    #   fileSizeLimit: 5
  serverFileSizeLimit: 25000  # Global server file size limit in MB
  avatarSizeLimit: 2  # Limit for user avatar image size in MB
# See the Custom Configuration Guide for more information on Assistants Config:
# https://www.librechat.ai/docs/configuration/librechat_yaml/object_structure/assistants_endpoint

```

</details> 

### What browsers are you seeing the problem on?

Firefox, Microsoft Edge, Mobile (Android)

### Relevant log output

```shell
[Violation] 'message' handler took 156ms
index.js:3004  Illegal target endpoint None [object Object]
V1 @ index.js:3004
js @ index.js:3004
(anonymous) @ index.js:3021
(anonymous) @ vendor.BujiSg_e.js:47
(anonymous) @ vendor.BujiSg_e.js:47
z7 @ vendor.BujiSg_e.js:40
tEe @ vendor.BujiSg_e.js:47
one @ vendor.BujiSg_e.js:47
(anonymous) @ vendor.BujiSg_e.js:47
(anonymous) @ index.js:3021
(anonymous) @ index.js:3365
bE @ vendor.BujiSg_e.js:40
zm @ vendor.BujiSg_e.js:40
vSe @ vendor.BujiSg_e.js:40
_d @ vendor.BujiSg_e.js:40
iB @ vendor.BujiSg_e.js:40
Kf @ vendor.BujiSg_e.js:38
(anonymous) @ vendor.BujiSg_e.js:40
setTimeout
(anonymous) @ vendor.BujiSg_e.js:76
vre @ vendor.BujiSg_e.js:76
mz @ vendor.BujiSg_e.js:76
s @ vendor.BujiSg_e.js:76
i @ vendor.BujiSg_e.js:76
dispatch @ vendor.BujiSg_e.js:76
setData @ vendor.BujiSg_e.js:76
onSuccess @ vendor.BujiSg_e.js:76
v @ vendor.BujiSg_e.js:76
Promise.then
S @ vendor.BujiSg_e.js:76
yre @ vendor.BujiSg_e.js:76
fetch @ vendor.BujiSg_e.js:76
executeFetch @ vendor.BujiSg_e.js:76
setOptions @ vendor.BujiSg_e.js:76
(anonymous) @ vendor.BujiSg_e.js:84
bE @ vendor.BujiSg_e.js:40
zm @ vendor.BujiSg_e.js:40
vSe @ vendor.BujiSg_e.js:40
_d @ vendor.BujiSg_e.js:40
iB @ vendor.BujiSg_e.js:40
Kf @ vendor.BujiSg_e.js:38
(anonymous) @ vendor.BujiSg_e.js:40
XMLHttpRequest.send
xhrSendProcessor @ main.js?attr=UKfjq9D3qWBATyAO28WIEuBuxVMiHw570UfSZ59O3y0uaBhJy1kmYRJ_9lpyWg7O5yEVjl7H8GxgxyBan6xePw:2773
window.XMLHttpRequest.send @ main.js?attr=UKfjq9D3qWBATyAO28WIEuBuxVMiHw570UfSZ59O3y0uaBhJy1kmYRJ_9lpyWg7O5yEVjl7H8GxgxyBan6xePw:2786
(anonymous) @ vendor.BujiSg_e.js:86
xhr @ vendor.BujiSg_e.js:86
Iz @ vendor.BujiSg_e.js:88
_request @ vendor.BujiSg_e.js:89
request @ vendor.BujiSg_e.js:88
(anonymous) @ vendor.BujiSg_e.js:89
(anonymous) @ vendor.BujiSg_e.js:84
(anonymous) @ index.js:3008
(anonymous) @ index.js:3008
(anonymous) @ index.js:3008
(anonymous) @ index.js:3008
fn @ index.js:3008
jh @ index.js:3008
Nh @ index.js:3008
Mw.ie.onMutate @ index.js:3008
fn @ vendor.BujiSg_e.js:76
S @ vendor.BujiSg_e.js:76
yre @ vendor.BujiSg_e.js:76
t @ vendor.BujiSg_e.js:76
execute @ vendor.BujiSg_e.js:76
await in execute
mutate @ vendor.BujiSg_e.js:76
(anonymous) @ vendor.BujiSg_e.js:84
(anonymous) @ index.js:3021
(anonymous) @ index.js:3021
bE @ vendor.BujiSg_e.js:40
zm @ vendor.BujiSg_e.js:40
iB @ vendor.BujiSg_e.js:40
Kf @ vendor.BujiSg_e.js:38
vSe @ vendor.BujiSg_e.js:40
_d @ vendor.BujiSg_e.js:40
jee @ vendor.BujiSg_e.js:40
N @ vendor.BujiSg_e.js:25
u @ vendor.BujiSg_e.js:25
6[Violation] 'setTimeout' handler took <N>ms
[Violation] Forced reflow while executing JavaScript took 79ms
vendor.BujiSg_e.js:40 [Violation] 'requestAnimationFrame' handler took 81ms
vendor.BujiSg_e.js:25 [Violation] 'message' handler took 157ms
index.js:3004  Illegal target endpoint None [object Object]
V1 @ index.js:3004
js @ index.js:3004
(anonymous) @ index.js:3021
(anonymous) @ vendor.BujiSg_e.js:47
(anonymous) @ vendor.BujiSg_e.js:47
z7 @ vendor.BujiSg_e.js:40
tEe @ vendor.BujiSg_e.js:47
one @ vendor.BujiSg_e.js:47
(anonymous) @ vendor.BujiSg_e.js:47
(anonymous) @ index.js:3021
r @ index.js:3365
onClick @ index.js:3365
g @ index.js:3365
Dwe @ vendor.BujiSg_e.js:37
Lwe @ vendor.BujiSg_e.js:37
jwe @ vendor.BujiSg_e.js:37
CF @ vendor.BujiSg_e.js:37
VJ @ vendor.BujiSg_e.js:37
(anonymous) @ vendor.BujiSg_e.js:37
z7 @ vendor.BujiSg_e.js:40
hJ @ vendor.BujiSg_e.js:37
yC @ vendor.BujiSg_e.js:37
m7 @ vendor.BujiSg_e.js:37
eOe @ vendor.BujiSg_e.js:37
vendor.BujiSg_e.js:40  ZodError: [
  {
    "received": "None",
    "code": "invalid_enum_value",
    "options": [
      "azureOpenAI",
      "openAI",
      "bingAI",
      "chatGPTBrowser",
      "google",
      "gptPlugins",
      "anthropic",
      "assistants",
      "azureAssistants",
      "agents",
      "custom",
      "bedrock"
    ],
    "path": [
      "endpointType"
    ],
    "message": "Invalid enum value. Expected 'azureOpenAI' | 'openAI' | 'bingAI' | 'chatGPTBrowser' | 'google' | 'gptPlugins' | 'anthropic' | 'assistants' | 'azureAssistants' | 'agents' | 'custom' | 'bedrock', received 'None'"
  }
]
    at get error (vendor.BujiSg_e.js:84:12611)
    at yr.parse (vendor.BujiSg_e.js:84:14848)
    at Q8 (index.js:3365:184842)
    at A7 (vendor.BujiSg_e.js:38:19557)
    at k$ (vendor.BujiSg_e.js:40:3150)
    at Qee (vendor.BujiSg_e.js:40:44947)
    at zee (vendor.BujiSg_e.js:40:39876)
    at pSe (vendor.BujiSg_e.js:40:39799)
    at v2 (vendor.BujiSg_e.js:40:39648)
    at j$ (vendor.BujiSg_e.js:40:36004)
M$ @ vendor.BujiSg_e.js:40
See.o.componentDidCatch.n.callback @ vendor.BujiSg_e.js:40
jF @ vendor.BujiSg_e.js:38
tB @ vendor.BujiSg_e.js:40
Lee @ vendor.BujiSg_e.js:40
fSe @ vendor.BujiSg_e.js:40
vSe @ vendor.BujiSg_e.js:40
_d @ vendor.BujiSg_e.js:40
iB @ vendor.BujiSg_e.js:40
Kf @ vendor.BujiSg_e.js:38
(anonymous) @ vendor.BujiSg_e.js:40
vendor.BujiSg_e.js:66  React Router caught the following error during render ZodError: [
  {
    "received": "None",
    "code": "invalid_enum_value",
    "options": [
      "azureOpenAI",
      "openAI",
      "bingAI",
      "chatGPTBrowser",
      "google",
      "gptPlugins",
      "anthropic",
      "assistants",
      "azureAssistants",
      "agents",
      "custom",
      "bedrock"
    ],
    "path": [
      "endpointType"
    ],
    "message": "Invalid enum value. Expected 'azureOpenAI' | 'openAI' | 'bingAI' | 'chatGPTBrowser' | 'google' | 'gptPlugins' | 'anthropic' | 'assistants' | 'azureAssistants' | 'agents' | 'custom' | 'bedrock', received 'None'"
  }
]
    at get error (vendor.BujiSg_e.js:84:12611)
    at yr.parse (vendor.BujiSg_e.js:84:14848)
    at Q8 (index.js:3365:184842)
    at A7 (vendor.BujiSg_e.js:38:19557)
    at k$ (vendor.BujiSg_e.js:40:3150)
    at Qee (vendor.BujiSg_e.js:40:44947)
    at zee (vendor.BujiSg_e.js:40:39876)
    at pSe (vendor.BujiSg_e.js:40:39799)
    at v2 (vendor.BujiSg_e.js:40:39648)
    at j$ (vendor.BujiSg_e.js:40:36004) {componentStack: '\n    at Q8 (https://chat-wcsng.nrp-nautilus.io/ass…wcsng.nrp-nautilus.io/assets/index.js:3070:21013)'}
componentDidCatch @ vendor.BujiSg_e.js:66
See.o.componentDidCatch.n.callback @ vendor.BujiSg_e.js:40
jF @ vendor.BujiSg_e.js:38
tB @ vendor.BujiSg_e.js:40
Lee @ vendor.BujiSg_e.js:40
fSe @ vendor.BujiSg_e.js:40
vSe @ vendor.BujiSg_e.js:40
_d @ vendor.BujiSg_e.js:40
iB @ vendor.BujiSg_e.js:40
Kf @ vendor.BujiSg_e.js:38
(anonymous) @ vendor.BujiSg_e.js:40
vendor.BujiSg_e.js:40 [Violation] 'click' handler took 1171ms
bootstrap-autofill-overlay-menu.js:887 [Violation] 'requestIdleCallback' handler took 59ms
```

### Screenshots

![image](https://github.com/user-attachments/assets/70d1c475-25f7-486d-a2a7-064e65791ed0)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
