### ISSUE TITLE
[Bug]: Unsupported Parameter `stream` with o1 Models in Azure OpenAI Integration

### ISSUE THREAD

**Issue by ABHIJITH-EA** [danny-avila/LibreChat#4379]
### What happened?

When using the Azure OpenAI API with the `o1-preview` and `o1-mini` models, an error occurs due to the use of unsupported parameter `stream`. 

Here is the my azure openai endpoint configuration,
```
endpoints:
  azureOpenAI:
    assistants: true
    groups:
      - group: "eu-region-group"
        apiKey: ${...}
        instanceName: ${...}
        version: "2024-05-01-preview"
        assistants: true
        models:
          gpt-4o-mini-assistant:
            deploymentName: gpt-4o-mini
      - group: "jp-region-group"
        apiKey: ${...}
        instanceName${...}
        assistants: false
        version: "2024-05-01-preview"
        models:
          gpt-4o:
            deploymentName: gpt-4o
      - group: "eu2-region-group"
        apiKey: ${...}
        instanceName: ${...}
        version: "2024-09-01-preview"
        assistants: false 
        models:
          o1-mini:
            deploymentName: o1-mini
          o1-preview:
            deploymentName: o1-preview
    plugins: true
    titleConvo: true
    titleModel: gpt-4o-mini
    #summarize: true
  azureAssistants:
    capabilities: ["code_interpreter", "actions", "tools"]

```

### Steps to Reproduce

1. Configure LibreChat to use the Azure OpenAI API with o1 models.
3. Attempt to make an API call for chat completion.

### What browsers are you seeing the problem on?

No response

### Relevant log output

```shell
nginx-client      | 10.92.130.46 - - [10/Oct/2024:10:51:53 +0000] "GET /api/messages/3863ca9f-b613-40fc-82ea-a5b1a141870d HTTP/2.0" 200 402 "https://[MASKED]/c/new" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36" "-"
LibreChat         | 2024-10-10 10:51:53 warn: [OpenAIClient.chatCompletion][stream] API error
LibreChat         | 2024-10-10 10:51:53 error: [handleAbortError] AI response error; aborting request: 400 Unsupported value: 'stream' does not support true with this model. Only the default (false) value is supported.
nginx-client      | 10.92.130.46 - - [10/Oct/2024:10:51:53 +0000] "POST /api/ask/azureOpenAI HTTP/2.0" 200 584 "https://[MASKED]/c/new" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36" "-"
chat-meilisearch  | 2024-10-10T10:51:53.680920Z  INFO HTTP request{method=POST host="meilisearch:7700" route=/indexes/messages/documents query_parameters= user_agent=node status_code=202}: meilisearch: close time.busy=420µs time.idle=5.71ms
chat-meilisearch  | 2024-10-10T10:51:53.776168Z  INFO index_scheduler::batch: document indexing done indexing_result=DocumentAdditionResult { indexed_documents: 1, number_of_documents: 11709 }
chat-meilisearch  | 2024-10-10T10:51:53.804096Z  INFO index_scheduler: A batch of tasks was successfully completed with 1 successful tasks and 0 failed tasks.
```

### Screenshots

![libreach-auzre-o1](https://github.com/user-attachments/assets/a9e56e7c-29a3-40b5-a41a-4bdd6003e513)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
