### ISSUE TITLE
Enhancement: Multitenant OpenID Login with Home Zone Discovery

### ISSUE THREAD

**Issue by leondape** [danny-avila/LibreChat#4544]
### Extend OpenID login to handle multiple OpenID tenants

The login process is currently limited to only one OpenID source specified in .env
This is a limitation if you want to integrate multiple OpenID Providers, which is common for larger organisations. 
I suggest implementing a more detailed setup in librechat.yaml which replaces the settings in .env.

#### Setup for a singular Tenant as it is now

```
OpenID:
  tenants:
    - domains: "" # will direct the auth flow to the issuer for ANY domain
      openid:
        clientId: "client-id-for-example"
        clientSecret: "client-secret-for-example"
        issuer: "https://example.com/oidc"
        callbackUrl: "/oauth/openid/callback"
```

#### Setup for multiple tenants

```
OpenID:
  tenants:
    - domains: "first.com,example.com" # will direct the auth flow to issuer1 only for these domains
      openid:
        clientId: "client-id-for-example"
        clientSecret: "client-secret-for-example"
        issuer: "https://example.com/oidc"
        callbackUrl: "/oauth/openid/callback"
    - domains: "another.com,one.com," will direct the auth flow to issuer2 only for these domains
      openid:
        clientId: "client-id-for-example2"
        clientSecret: "client-secret-for-example2"
        issuer: "https://example.com/oidc2"
        callbackUrl: "/oauth/openid/callback"
```

### More details

When domains are set, a mandatory email field should be visible above the Button. The Action flow would then be: 

1. User Inputs email 
2. User clicks button
3. User gets routed to correct OpenID provider based on domain. Routing to the correct IDP (Home Zone Discovery) is set over the yaml file domain entries.

If no domains are set, multitenant is disabled and the functionality is just the same is it is currently. 

### Which components are impacted by your request?

I'm not sure but probably: 
- api/server/routes/config.js
- SocialLoginRender.tsx
- SocialButton.tsx
- Login.tsx
- AuthLayout.tsx

#### No domains set (Current)

![Bildschirmfoto 2024-10-25 um 07 46 26](https://github.com/user-attachments/assets/93afb449-6466-4fe0-9e7b-2ec891e83d1b)

#### With domains set (Future)

<img width="339" alt="multitenant-mock" src="https://github.com/user-attachments/assets/10bb4fa6-7a65-4f6f-8efe-9bf5267ea55c">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
