### ISSUE TITLE
Enhancement: Add support of VTT format

### ISSUE THREAD

**Issue by DenisPalnitsky** [danny-avila/LibreChat#4562]
### What features would you like to see added?

- support of [VTT](https://support.zoom.com/hc/en/article?id=zm_kb&sysparm_article=KB0064927#:~:text=Audio%20transcription%20automatically%20transcribes%20the,the%20list%20of%20recorded%20meetings.) (Zoom audio transcript) file format 

### More details

VTT is a Zoom audio transcript format which is just a text file with the transcript of Zoom meeting conversation

### Which components are impacted by your request?

General

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by DenisPalnitsky** [comment]
I set up file config like this:
```
fileConfig:
  endpoints:
    assistants:
      fileLimit: 5
      totalSizeLimit: 50 # Maximum total size for all files in a single request in MB
      supportedMimeTypes:
        - "image/.*"        
        - "text/.*"
        - "application/.*"
    openAI:
      disabled: false # Disables file uploading to the OpenAI endpoint
      supportedMimeTypes: 
            - "image/.*"
            - "application/.*"
            - "text/.*"            
    default:
      totalSizeLimit: 20
      fileSizeLimit: 15 # Maximum size for an individual file in MB
      supportedMimeTypes:
         - "image/.*"         
         - "application/.*"
         - "text/.*"
  serverFileSizeLimit: 100 # Global server file size limit in MB
  avatarSizeLimit: 2 # Limit for user avatar image size in MB
```

But it does not seem to have any effect. I'm still getting 
![image](https://github.com/user-attachments/assets/d0543d8b-e650-4f9f-b313-19d52b2f60f5)
