### ISSUE TITLE
[Bug]: Bookmarks button does not disappear when bookmarks is false in librechat.yaml

### ISSUE THREAD

**Issue by MatteoPagliani** [danny-avila/LibreChat#4567]
### What happened?

Hi. I don't know if this is intended, but when librechat.yaml is configured in the following way (with bookmarks equal to false), the bookmarks button on the left side of the screen does not disappear.

```
interface:
  endpointsMenu: false
  modelSelect: true
  parameters: false
  sidePanel: false
  presets: false
  prompts: false
  bookmarks: false
  multiConvo: true
```

### Steps to Reproduce

Run the UI with the above librechat.yaml configuration

### What browsers are you seeing the problem on?

Firefox

### Screenshots

![image](https://github.com/user-attachments/assets/569a79c3-0654-4d2e-bfd0-b9bf6aeb9b76)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
