### ISSUE TITLE
[Bug]: Unable to generate image via dalle using modelspec after updating to 0.7.5

### ISSUE THREAD

**Issue by nathanwong91** [danny-avila/LibreChat#4578]
### What happened?

While being on 0.7.5-rc1 we have been using modelspecs to give users an option for image generation. Here's the config we've been using

```
- name: "Generate Images using DALLE3"
  label: "Image Generation Tool (DALLE3)"
  description: "Generate images using DALLE3"
  preset:
    default: false
    endpoint: "gptPlugins"
    model: "gpt-4o"
    modelLabel: "Image Generation"
    tools: ["dalle"]
    greeting: |
      This assistant will generate images based on your query using DALLE3
    promptPrefix: |
      Taking the users input, generate an image using dalle3
```
Since moving to 0.7.5 this is now broken. We see an error in the logs
```
error: [PluginsClient] executorCall error: Cannot read properties of null (reading 'call')
```
and this error from the UI
```
Something went wrong. Here's the specific error message we encountered: Encountered an error while attempting to respond: Cannot read properties of null (reading 'call')
```

Another issue we've seen is the models are no longer selected properly
<img width="424" alt="image" src="https://github.com/user-attachments/assets/bc3ae98c-8622-4f01-b9d8-614f3d6fa5a4">
Even though we've set the following
```
    modelSpecs:
      enforce: true
      prioritize: true
      list:
        - name: "GPT4"
          label: "Basic (GPT4)"
          description: "Assist users"
          preset:
            default: true
            endpoint: "azureOpenAI"
            model: "gpt-4o"
            ~~~

```

I don't see anything in the changelogs to reflect changes to do with modelspecs other than labels

### Steps to Reproduce

1. Setup ModelSpecs dalle on 0.7.5-rc1
2. Update to 0.7.5 without changing configuration
3. Ask it to generate an image

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
