### ISSUE TITLE
[Bug]: Ollama models missing from selection list if name is capitalized

### ISSUE THREAD

**Issue by RobbySingh** [danny-avila/LibreChat#4654]
### What happened?

![image](https://github.com/user-attachments/assets/57e0ebec-243c-4376-b618-f17c0c835d87)

```yaml
# Definition of custom endpoints                                                                                                                               
endpoints:                                                                                                                                                     
  custom:                                                                                                                                                      
      - name: "Ollama" # "Ollama" -> no models. "ollama" -> models                                                                                                                                         
        apiKey: "ollama"                                                                                                                                       
        baseURL: "http://host.docker.internal:11434/v1/chat/completions"                                                                                       
        models:                                                                                                                                                
          default: [                                                                                                                                           
            "llama3:latest"                                                                                                                                    
          ]                                                                                                                                                    
          fetch: true                                                                                                                                          
        titleConvo: true                                                                                                                                       
        titleModel: "current_model"                                                                                                                            
        summarize: false                                                                                                                                       
        summaryModel: "current_model"                                                                                                                          
        forcePrompt: false                                                                                                                                     
        modelDisplayLabel: "ollama"                                                                                                                            
        capabilities: ["retrieval", "actions", "tools", "image_vision", "code_interpreter"]                                                                    
  ```

When I updated from v0.75.2 -> v0.75, my Ollama model list stopped loading. I saw that my models were loading from the /api/models endpoint correctly, but they were under the key "ollama".

The docs say that this should be case insensitive:

>         # with `ollama` (case-insensitive), as it does in this example.

The example uses the titlecase "Ollama" as the example custom_endpoint name:

https://www.librechat.ai/docs/configuration/librechat_yaml/ai_endpoints/ollama
```yaml
  custom:
    - name: "Ollama"
      apiKey: "ollama"
      # use 'host.docker.internal' instead of localhost if running LibreChat in a docker container
      baseURL: "http://localhost:11434/v1/chat/completions" 
      models:
        default: [
          "llama2",
          "mistral",
          "codellama",
          "dolphin-mixtral",
          "mistral-openorca"
          ]
        # fetching list of models is supported but the `name` field must start
        # with `ollama` (case-insensitive), as it does in this example.
        fetch: true
      titleConvo: true
      titleModel: "current_model"
      summarize: false
      summaryModel: "current_model"
      forcePrompt: false
      modelDisplayLabel: "Ollama"
```

### Steps to Reproduce

1. Setup Ollama using a custom_endpoint and download a model
2. Set the name to "Ollama"
3. -> No models returned
4. Set the name to "ollama"
5. -> All models returned

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
