### ISSUE TITLE
[Bug]: Error When Accessing Azure Serverless Models

### ISSUE THREAD

**Issue by MasterOfWebM** [danny-avila/LibreChat#4767]
### What happened?

When attempting to utilize a serverless model in Azure AI Foundry (Azure OpenAI), I am receiving a 401 error, even though the the API key is verified and correct. 

Config:
```yaml
endpoints:
  azureOpenAI:
    titleModel: 'Meta-Llama-3.1-8B-Instruct'
    plugins: false
    assistants: false
    groups:
    - group: 'Llama'
      serverless: true
      apiKey: '<REDACTED>'
      baseURL: 'https://<REDACTED>.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview'
      models:
        Meta-Llama-3.1-8B-Instruct: true
```

I tried the `baseURL` with and without the query parameter without any luck.

### Steps to Reproduce

1. Create a new serverless model in Azure AI Foundry
2. Copy the `Target URI` in Foundry and use it as the `baseURL`
3. Attempt to query the API endpoint within LibreChat

### Relevant log output

```shell
error: [handleAbortError] AI response error; aborting request: Failed to send message. HTTP 401 - { "statusCode": 401, "message": "Unauthorized. Access token is missing, invalid, audience is incorrect (https://cognitiveservices.azure.com), or have expired." }
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
