### ISSUE TITLE
[Bug]: Environment variables in librechat.yaml for speech settings do not work

### ISSUE THREAD

**Issue by asieverding** [danny-avila/LibreChat#4856]
### What happened?

Want to set configurations for stt & tts in `librechat.yaml` with environment variables like the endpoint api key. But in the speech settings it seems that environment variables are not working. All environment variables are set and available.

### Steps to Reproduce

Config:
```YAML
speech:
  tts:
    azureOpenAI:
      instanceName: '${AZURE_OPENAI_TTS_INSTANCE_NAME}'
      apiKey: '${AZURE_OPENAI_TTS_API_KEY}'
      deploymentName: '${AZURE_OPENAI_TTS_DEPLOYMENT_NAME}'
      apiVersion: '${AZURE_OPENAI_TTS_API_VERSION}'
      model: '${AZURE_OPENAI_TTS_MODEL}'
      voices: ['alloy', 'echo', 'fable', 'onyx', 'nova', 'shimmer']
  stt:
    azureOpenAI:
      instanceName: '${AZURE_OPENAI_STT_INSTANCE_NAME}'
      apiKey: '${AZURE_OPENAI_STT_API_KEY}'
      deploymentName: '${AZURE_OPENAI_STT_DEPLOYMENT_NAME}'
      apiVersion: '${AZURE_OPENAI_STT_API_VERSION}'
``` 

### Relevant log output

```shell
LibreChat         | 2024-12-04 12:37:46 error: STT request failed for provider azureOpenAI: getaddrinfo ENOTFOUND ${azure_openai_stt_instance_name}.openai.azure.com
LibreChat         | 2024-12-04 12:37:46 error: An error occurred while processing the audio: getaddrinfo ENOTFOUND ${azure_openai_stt_instance_name}.openai.azure.com
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
