### ISSUE TITLE
[Bug]: STT Invalid URL?

### ISSUE THREAD

**Issue by awickham10** [danny-avila/LibreChat#4915]
### What happened?

When using OpenAI for SST, I am getting an Invalid URL when trying to use it. TTS works fine.

### Steps to Reproduce

1. Set config yaml to this:
```
speech:
  speechTab:
    conversationMode: true
    advancedMode: true
    speechToText:
      engineSTT: "external"
      languageSTT: "English (US)"
      autoTranscribeAudio: true
      decibelValue: -45
      autoSendText: 0
    textToSpeech:
      engineTTS: "external"
      voice: "alloy"
      languageTTS: "en"
      automaticPlayback: true
      playbackRate: 1.0
      cacheTTS: true
  stt:
    openai:
      url: 'https://api.openai.com/v1/audio/transcriptions'
      apiKey: '${STT_API_KEY}'
      model: 'whisper-1'
  tts:
    openai:
      apiKey: '${TTS_API_KEY}'
      model: 'tts-1'
      voices: ['alloy', 'echo', 'fable', 'onyx', 'nova', 'shimmer']
```
3. Create a new chat
4. Hit the microphone button
5. Observe an in the UI saying an error occurred maybe the audio is too short.

### Relevant log output

```shell
error: STT request failed for provider openai: Invalid URL
error: An error occurred while processing the audio: Invalid URL
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
