### ISSUE TITLE
[Question]: Title Generation - Custom endpoint

### ISSUE THREAD

**Issue by QuartzWarrior** [danny-avila/LibreChat#4924]
### What is your question?

Why am I getting this error, and how can I fix it?

I'm assuming there must be something wrong with the endpoint used, but not entirely sure.

I'm trying to get title generation to work on my custom endpoint ( the only endpoint enabled in my configs ) but always get the following errors, even though I don't have OpenAI enabled.

### More Details

received error
```
2024-12-10 03:25:24 warn: [OpenAIClient.chatCompletion][create] API error
2024-12-10 03:25:24 error: [OpenAIClient.chatCompletion] Unhandled error type Error: 422 status code (no body)
2024-12-10 03:25:24 error: [OpenAIClient] There was an issue generating the title with the completion method Error: 422 status code (no body)
```

librechat.yaml looks similar to this:
```
 custom:
    - name: 'AI'
      apiKey: 'user_provided'
      baseURL: 'http://localhost:800/chat/completions'
      models: []
        fetch: false
      titleConvo: true
      titleModel: 'ministral-3b-latest'
      titleMethod: "completion"
      directEndpoint: true
      modelDisplayLabel: ' AI'
```

yes, I did provide the api key.

My backend is running on localhost:800, frontend running on localhost:900

---

### What is the main subject of your question?

UI, Endpoints

### Screenshots

![image](https://github.com/user-attachments/assets/f7f5433e-18cd-4a13-a4b9-a3966f28af2c)
![image](https://github.com/user-attachments/assets/9f594da3-2ec9-43e7-9d13-fa4509299941)
![image](https://github.com/user-attachments/assets/a47113fa-04a1-4e98-b50e-1313c57f0e2b)
![image](https://github.com/user-attachments/assets/d05c7c0d-ff63-4023-863a-6a22393b11b2)
![image](https://github.com/user-attachments/assets/110e838d-e29a-4e78-b10d-67201efb4f34)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
