### ISSUE TITLE
[Bug]: Cannot get Open AI TTS working with librechat.yaml etc

### ISSUE THREAD

**Issue by jhmonroe** [danny-avila/LibreChat#4983]
### What happened?

Love this project! Thank you so much for creating so we can explore models in one window.

Am trying to add the OpenAI TTS voices as outlined here: https://www.librechat.ai/docs/configuration/stt_tts

I followed and double-checked the steps outlined below but the settings never show up and I get a Docker error pasted below in the output area.

I also searched this repo and saw other issues where you suggested path changes and tried to just change the path to see if anything changed. Same error.

Am I missing something?

Mac here running Docker 4.35.1 and updated to 4.36 to rule that out. :-)

### Steps to Reproduce

- copy/rename **librechat.yaml** in the root as per [instructions](https://www.librechat.ai/docs/configuration/librechat_yaml/setup)
- uncommented this:
```
speech:
  tts:
    openai:
      apiKey: 'API KEY HERE'
      model: 'tts-1'
      voices: ['alloy', 'echo', 'fable', 'onyx', 'nova', 'shimmer']
```

- followed the [docker setup instructions](https://www.librechat.ai/docs/configuration/librechat_yaml/setup) to create **docker-compose.override.yml** with the following uncommented:
```
version: '3.4'
 
services:
  api:
    volumes:
      - type: bind
        source: ./librechat.yaml
        target: /app/librechat.yaml
```
- stopped and restarted the container several times
- still get that warning and still not setting the openAI TTS 
- stop containers, remove those 2 files, restart. no errors

### Relevant log output

```shell
In Docker: "error: Config file YAML format is invalid: ENOENT: no such file or directory, open '/app/librechat.yaml'"
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
