### ISSUE TITLE
Enhancement: Ability to select an agent as the default for new chats

### ISSUE THREAD

**Issue by acehoss** [danny-avila/LibreChat#5000]
### What features would you like to see added?

Maybe agents could appear in the preset list, allowing them to be selected as the default for new chats? Or some other way? But when starting a new chat, I'd like for an agent to be preselected.

### More details

I have an agent that I use for 95% of conversations, and every time I start a new chat I need to @ the agent in the chat box to select it.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dvejsada** [comment]
You can do this using a modelSpec https://www.librechat.ai/docs/configuration/librechat_yaml/object_structure/model_specs

You can set a specific agent as "endpoint" and even make it as default.

**Comment by acehoss** [comment]
@dvejsada thanks for the suggestion! I gave it a try, but I couldn't figure out how to get it to select the agent I built in the agent builder. Additionally, all of the other endpoints disappeared. It seems like I'd have to manually set up model specs for everything I wanted to be able to use if I took this approach.

Additionally, my agent uses some custom actions, which don't appear to be configurable from the model specs.

I'd like to be able to select an agent that I built with the agent builder as the default.

**Comment by danny-avila** [comment]
@acehoss I'm planning on implementing something similar to ChatGPT with the way they allow pinning GPTs:
![firefox_ofKCnG9Sxx](https://github.com/user-attachments/assets/0d777ce8-6256-47ad-836e-b2ad60834bfd)

**Comment by acehoss** [comment]
@danny-avila That sounds even better than presets, the main thing I'd like is one-click activation of an agent. This would allow one-click activation of *various* agents, which is more powerful than default activation of *one* agent. 💯

**Comment by zeitderforschung** [comment]
> You can do this using a modelSpec https://www.librechat.ai/docs/configuration/libre
chat_yaml/object_structure/model_specs
> 
> You can set a specific agent as "endpoint" and even make it as default.

How did you manage to create an agent when modelSpecs were active? Changing the selection to "Agents" to show the Agent Builder was not possible once a modelSpec was configured. Without a modelSpec everything worked fine.

<img width="385" alt="image" src="https://github.com/user-attachments/assets/19f41cf2-634c-415a-869e-8fe19d0f45fe" />


This is my librechat.yml:

```yaml
interface:
  endpointsMenu: true

endpoints:
  azureOpenAI:
  ...
modelSpecs:
  list:
    - name: "yourcompany-gpt"
```

**Comment by dvejsada** [comment]
> > You can do this using a modelSpec https://www.librechat.ai/docs/configuration/libre
> chat_yaml/object_structure/model_specs
> > 
> > You can set a specific agent as "endpoint" and even make it as default.
> 
> How did you manage to create an agent when modelSpecs were active? Changing the selection to "Agents" to show the Agent Builder was not possible once a modelSpec was configured. The menu entry "Agents" was there, but I could not select it. Without a modelSpec everything worked fine. I am already running the latest development build.
> 
> <img width="385" alt="image" src="https://github.com/user-attachments/assets/19f41cf2-634c-415a-869e-8fe19d0f45fe" />
> 
> My environment:
> 
>     ENDPOINTS=azureOpenAI,agents
>     EXPERIMENTAL_AGENTS=true
>      
> My librechat.yaml:
> 
> ```yaml
> interface:
>   endpointsMenu: true
> 
> endpoints:
>   azureOpenAI:
>   ...
> 
> modelSpecs:
>   list:
>     - name: "yourcompany-gpt"
>       preset:
>         default: true
>         endpoint: "azureOpenAI"
> ```

You can do modelSpec with endpoint "agents", which will allow you to create/edit agents. Once you have your agent created, just add the agent_id to keep the modelSpec endpoint for specific agent only (if preferred).

**Comment by Tsounguinzo** [comment]
> > > You can do this using a modelSpec https://www.librechat.ai/docs/configuration/libre
> > > chat_yaml/object_structure/model_specs
> > > You can set a specific agent as "endpoint" and even make it as default.
> > 
> > 
> > How did you manage to create an agent when modelSpecs were active? Changing the selection to "Agents" to show the Agent Builder was not possible once a modelSpec was configured. The menu entry "Agents" was there, but I could not select it. Without a modelSpec everything worked fine. I am already running the latest development build.
> > <img alt="image" width="385" src="https://private-user-images.githubusercontent.com/54367033/396992115-19f41cf2-634c-415a-869e-8fe19d0f45fe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3OTQ2NzQsIm5iZiI6MTczNDc5NDM3NCwicGF0aCI6Ii81NDM2NzAzMy8zOTY5OTIxMTUtMTlmNDFjZjItNjM0Yy00MTVhLTg2OWUtOGZlMTlkMGY0NWZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIxVDE1MTkzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3NDY0N2YzY2Y3ZjNlY2E0NWQyYTQxMDEyNzUxOWY3MGFiZDRiNjVlYzEyZDFhOTg0MzQxMWQ4MzkxMTY1NGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Y-0GEa5QHISvwX0-JnIQRAw3oObpRZSg6kmdWYb9avg">
> > My environment:
> > ```
> > ENDPOINTS=azureOpenAI,agents
> > EXPERIMENTAL_AGENTS=true
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > My librechat.yaml:
> > ```yaml
> > interface:
> >   endpointsMenu: true
> > 
> > endpoints:
> >   azureOpenAI:
> >   ...
> > 
> > modelSpecs:
> >   list:
> >     - name: "yourcompany-gpt"
> >       preset:
> >         default: true
> >         endpoint: "azureOpenAI"
> > ```
> 
> You can do modelSpec with endpoint "agents", which will allow you to create/edit agents. Once you have your agent created, just add the agent_id to keep the modelSpec endpoint for specific agent only (if preferred).

what do you mean by "add the agent_id", where do we get that id from and how do we add that Id in the model spec I cant find it in the docs also can I make that agent as default like we do with other models?

**Comment by mbiskach** [comment]
I too am attempting to create a modelSpec that uses the endpoint "agents" and allows for creating/editing agents. Here is my librechat.yaml as an example:

```yaml
# librechat.yaml
endpoints:

# Example existing custom endpoint
  custom:
  - name: "<redacted>"
  ...
    models:
      default: ["claude-3.5-haiku", ...]

  agents:
    disableBuilder: false

modelSpecs:
  enforce: false
  prioritize: true
  list:
    # Example modelSpec based on custom endpoint
    - name: "<redacted>"
    ...

    # Is the following correct?
    - name: "agents"
      label: "Agents"
      preset:
        endpoint: "agents"
        model: "claude-3.5-haiku"

```

Currently I see both modelSpecs visible in the dropdown select menu, but I can't create/edit agents (agent builder is not visible). When I use endpoints only (instead of modelSpecs), I do see the agent builder.

**Comment by danny-avila** [comment]
@Balzabu @mbiskach That is default behavior for using modelSpecs.

You need to override the default interface settings as mentioned in the docs: https://www.librechat.ai/docs/configuration/librechat_yaml/object_structure/model_specs#overview

https://www.librechat.ai/docs/configuration/librechat_yaml/object_structure/interface

**Comment by mbiskach** [comment]
@danny-avila I added `agentBuilder: true` and `agents: true` to the `interface` settings, but when using modelSpecs, agent builder does not show (for endpoints it does).

```yaml
interface:
  agents: true
  agentBuilder: true

```

The rest of the librechat.yaml continues from [above](https://github.com/danny-avila/LibreChat/issues/5000#issuecomment-2563780545)

**Comment by zeitderforschung** [comment]
This minimal librechat config works for me.

```yaml
interface:
  endpointsMenu: false
  modelSelect: false
  parameters: true  # 👉 Must be enabled, else there is no agent builder!
  agents: true

modelSpecs:
  list:
    - name: "Agents"
      label: "Agents"
      preset:
        endpoint: "agents"
        # Optionally set a default agent, get the id from mongodb > "LibreChat" database > "agents" table
        # agent_id: "agent_NqhNPxoUp9coJ4BFZIEF3"
```

**Comment by danny-avila** [comment]
For what it's worth, I've added URL query params for using agents via links to your instance:
https://www.librechat.ai/docs/features/url_query

I've also extensively updated model specs documentation for correct usage:
https://www.librechat.ai/docs/configuration/librechat_yaml/object_structure/model_specs

you should simply use the following when configuring agents via specs:
```yaml
      preset:
        endpoint: "agents"
        agent_id: "agent_someUniqueId"
```

https://www.librechat.ai/docs/configuration/librechat_yaml/object_structure/model_specs#agent-options
