### ISSUE TITLE
[Bug]: UI does not show default Preset

### ISSUE THREAD

**Issue by xhejtman** [danny-avila/LibreChat#5214]
### What happened?

If I set default preset via modelspec:
```
modelSpecs:
      enforce: false
      prioritize: false
      list:
       - name: llama3.3:latest
         label: "Llama 3.3"
         default: true
         iconURL: https://cdn1.cloud.e-infra.cz/logos/meta-llama.png
         showIconInMenu: true
         preset:
           endpoint: "custom"
           model: "llama3.3:latest"
           maxContextTokens: 128000
           max_tokens: 16384
```

it is default in a new chat, but not displayed as default in UI:
<img width="686" alt="Screenshot 2025-01-08 at 18 25 10" src="https://github.com/user-attachments/assets/1c33447c-5488-49ca-a80e-b1cf2ddc67dc" />

### Steps to Reproduce

See above

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
