### ISSUE TITLE
[Bug]: Unable to chat with an Agent

### ISSUE THREAD

**Issue by LufinityLucas** [danny-avila/LibreChat#5283]
### What happened?

I have enabled the Agent Builder and created an agent named `Test`. However, when chatting with it, I get error `Something went wrong. Here's the specific error message we encountered: No model spec selected`. Indeed no model spec is selected in the top menu:

![image](https://github.com/user-attachments/assets/b0e58ee3-1109-4d55-a27b-54456e880a1c)

If I select a model spec (I have two of them configured in the YAML file), the endpoint changes back to my `Azure OpenAI`. Selecting the `Agent` endpoint again and now a model spec is selected:

![image](https://github.com/user-attachments/assets/2468352c-461f-460f-b796-033c7450c6ce)

However, when chatting now I get error `Something went wrong. Here's the specific error message we encountered: Model spec mismatch`.

Relevant parts from my YAML file:

```
...
interface:
  endpointsMenu: true
  modelSelect: true
  parameters: false
  sidePanel: true
  presets: false
  prompts: true
  bookmarks: true
  multiConvo: false
...
modelSpecs:
  enforce: false
  prioritize: false
  list:
    - name: "ada-gpt"
      label: "Ada"
      preset:
        default: true
      ...
...
```

I don't know if I have a specific set of configuration settings causing this, or if it's actually a bug. I would suspect no model spec to be selected when using your own agent.

### Steps to Reproduce

1. Configure the YAML file as per above
2. Add two specs to the `modelSpecs` section, where one is set to default
3. Go to the web UI and start a new chat.
4. Select `Agent` from the endpoint menu.
5. Select an agent (or create a new one using the Agent Builder and select it)
6. Write something to the bot. Observere the error.
7. Select a model spec, and change back to `Agent` in the endpoint menu.
8. Write something to the bot. Observe the error.

### What browsers are you seeing the problem on?

Microsoft Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
