### ISSUE TITLE
gpt-4o-realtime-preview should not use chat completion

### ISSUE THREAD

**Issue by ineiti** [danny-avila/LibreChat#5326]
I tried using the `gpt-4o-realtime-preview` model in librechat 0.7.6, but I get the following error in the logs:

```
LibreChat         | 2025-01-16 10:00:04 error: [handleAbortError] AI response error; aborting request: 404 This is not a chat model and thus not supported in the v1/chat/completions endpoint. Did you mean to use v1/completions?
```

So I guess that the following condition needs to be updated - is that correct? I couldn't find any reference in the OpenAI documentations about restrictions on the endpoints wrt the models...

https://github.com/danny-avila/LibreChat/blob/aa80e4594eadef113eaca007f9ccfa0823805176/api/app/clients/OpenAIClient.js#L145

**Comment by ineiti** [comment]
I tried to use the following `librechat.yaml` configuration:

```yaml
endpoints:
  custom:
    # GPT realtime preview
    - name: 'gpt-realtime'
      apiKey: '${OPENAI_API_KEY}'
      baseURL: 'https://api.openai.com/v1/completions'
      models:
        default:
          [
            'gpt-4o',
            'gpt-4o-realtime-preview',
          ]
        fetch: false
      titleConvo: true
      titleModel: 'gpt-4o-mini'
      modelDisplayLabel: 'GPT-realtime-display'
```

And now it tells me that it's still not the correct endpoint :(

```
LibreChat         | 2025-01-16 14:40:04 error: [handleAbortError] AI response error; aborting request: Failed to send message. HTTP 404 - {
LibreChat         |   "error": {
LibreChat         |     "message": "This model is not supported in the v1/completions endpoint.",
LibreChat         |     "type": "invalid_request_error",
LibreChat         |     "param": "model",
LibreChat         |     "code": null
LibreChat         |   }
LibreChat         | }
```

I added the `gpt-4o` to be able to compare which one works. When I change the URL to `https://api.openai.com/v1/chat/completions`, it works for `gpt-4o`, but for the `gpt-4o-realtime-preview` I still get the `This is not a chat model` error from before.
