### ISSUE TITLE
[Bug]: Deepseek-reasoner model fails after first message in LibreChat when added to default models

### ISSUE THREAD

**Issue by kihyunnn** [danny-avila/LibreChat#5377]
### What happened?

When using LibreChat with the Deepseek API specifically with the "deepseek-reasoner" model added to the default models configuration, the conversation only works for the first message. Subsequent messages fail with a system message error. Other Deepseek models (deepseek-chat, deepseek-coder) are not affected by this issue.

Configuration where issue occurs:
```
default: ["deepseek-chat", "deepseek-reasoner", "deepseek-coder"]
```

The error message received is:
```
2025-01-21 01:58:37 LibreChat         | 2025-01-20 16:58:37 error: 
2025-01-21 01:58:37 LibreChat         | 2025-01-20 16:58:37 error: [handleAbortError] AI response error; aborting request: 400 The system message of deepseek-reasoner must be put on the beginning of the message sequence.
```

Also tell us, what did you expect to happen?
Expected the deepseek-reasoner model to maintain continuous conversation like the other Deepseek models (deepseek-chat, deepseek-coder), without any system message errors.

### Steps to Reproduce

1. Configure LibreChat with deepseek-reasoner in the default models array
2. Start a new conversation using the deepseek-reasoner model
3. Send first message (works correctly)
4. Attempt to send a second message
5. Observe the system message error

### What browsers are you seeing the problem on?

Chrome

### Relevant log output
```shell
2025-01-21 01:58:37 LibreChat         | 2025-01-20 16:58:37 warn: [OpenAIClient.chatCompletion][stream] API error
2025-01-21 01:58:37 LibreChat         | 2025-01-20 16:58:37 error: 
2025-01-21 01:58:37 LibreChat         | 2025-01-20 16:58:37 error: [handleAbortError] AI response error; aborting request: 400 The system message of deepseek-reasoner must be put on the beginning of the message sequence.
```

### Screenshots

![Image](https://github.com/user-attachments/assets/dbf35d36-818f-4c27-8fce-cfb2691c4f5d)

![Image](https://github.com/user-attachments/assets/4cbf6fd2-8892-4f27-b2ce-40b631901ec9)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by michnovka** [comment]
Hi, I cannot reproduce this on my end:

```yaml
   - name: "Deepseek"
      apiKey: "${DEEPSEEK_API_KEY}"
      baseURL: "https://api.deepseek.com/v1"
      models:
        default: ["deepseek-chat", "deepseek-reasoner", "deepseek-coder"]
        fetch: false
      titleConvo: true
      titleModel: "deepseek-chat"
      summarize: false
      summaryModel: "deepseek-chat"
      forcePrompt: false
      modelDisplayLabel: "Deepseek"
```

notice my endpoint having v1 compared to yours, not sure if its different.

![Image](https://github.com/user-attachments/assets/89332a38-ed45-4cd0-8086-1e0fbce89619)
