### ISSUE TITLE
Enhancement: Add more models to the Github Models option

### ISSUE THREAD

**Issue by kvn8888** [danny-avila/LibreChat#5446]
### What features would you like to see added?

Currently, LibreChat only supports the old GPT 4o and Phi-3 models. While these models are useful, adding support for more models would significantly enhance the platform's versatility and make it more appealing to users who wish to experiment with a broader variety of free models offered on GitHub Models.

### More details

**Describe the solution you'd like**  
Add support for the following models in LibreChat:  
1. GPT 4o mini  
2. o1  
3. o1 mini  
4. o1 preview  
5. Phi-4 
6. Cohere Command models  
7. Llama 3 models  
8. Mistral models  

**Additional context**  
Adding support for these models would align LibreChat with the latest advancements in the open model ecosystem, making the platform a key tool for users interested in experimenting with multiple free models. Users of GitHub Models could benefit greatly from a seamless integration with LibreChat, enabling a unified chat interface for testing and deploying these models.

---

**Priority**  
Medium. With an increasing number of cutting-edge and open models being released (like Llama 3 and Mistral), staying up-to-date with model support will ensure users continue to see value in LibreChat.

---

**Would you be willing to contribute to this feature?**  
Yes

### Which components are impacted by your request?

Endpoints

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by illgitthat** [comment]
You can use any model you want that's available in Github?

Here is an example of how I used `o1` by adding this to `liberchat.yaml`

```yaml
  custom:
    - name: "Github"
      apiKey: "${GITHUB_API_KEY}"
      baseURL: "https://models.inference.ai.azure.com"
      models:
        default: [
          "o1",
          ]
        fetch: false
      titleConvo: false
      #titleModel: "gpt-4o-mini"
      dropParams: ["stop", "user", "frequency_penalty", "presence_penalty"]
      modelDisplayLabel: "Reasoning model"
```

Relevant documentation: https://www.librechat.ai/docs/configuration/librechat_yaml
