### ISSUE TITLE
[Bug]: The `@` lets you selected un supported assistants and throws an error

### ISSUE THREAD

**Issue by AFaulkner1990** [danny-avila/LibreChat#5558]
### What happened?

We have two versions of LibreChat running, one as a general user site that uses ModelSpecs and another power user "admin" site, that lets users create assistants/agents etc. 

My assitants config looks like this:
```
  azureAssistants:
    capabilities: ["code_interpreter", "actions", "tools", "image_vision", "retrieval"]
    disableBuilder: true # Disable Assistants Builder Interface by setting to true
    privateAssistants: false # Enable private assistants by setting to true
    supportedIds: ["asst_xxxxxxxxxxxxx"]
    pollIntervalMs: 3000 # Polling interval for checking assistant updates
    timeoutMs: 180000 # Timeout for assistant operations
```

"Aila code" is the model spec using azures assistants `asst_xxxxxxxxxxxxx`

However when I type `@` as suggested in the chat input box, it shows all the other assistants, which it then obviously fails if you try and use.  

![Image](https://github.com/user-attachments/assets/dbc07bab-fb8d-4653-9fd2-40c313562a68)

![Image](https://github.com/user-attachments/assets/e19b2da0-7e3e-45ac-a38d-4c269c303c15)

Looking at the code this only seems to be for Admin accounts, I am unsure what you want the expected behaviour to be so have not done a fix

### Steps to Reproduce

- Login as an Admin
- Create a couple assistants
- Add only one of them to your `supportedIds` option
- Create a ModelSpec using this Id and set `disableBuilder` to false
- Type `@` into chat input box and see if other assistants show 

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell

```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
