### ISSUE TITLE
Enhancement: Support for Azure Deepseek R1

### ISSUE THREAD

**Issue by DakotaWray2** [danny-avila/LibreChat#5579]
### What features would you like to see added?

Yesterday Microsoft announced DeepSeek R1 availability as an Azure endpoint. It would be great utilize this in LibreChat.

### More details

[https://azure.microsoft.com/en-us/blog/deepseek-r1-is-now-available-on-azure-ai-foundry-and-github/](https://azure.microsoft.com/en-us/blog/deepseek-r1-is-now-available-on-azure-ai-foundry-and-github/)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
You can already do this as a custom endpoint:

```yaml
    - name: "Azure (DeepSeek)"
      apiKey: "${AZURE_DEEPSEEK_API_KEY}" # env. var is arbitrary
      baseURL: "https://your-custom-endpoint.eastus2.models.ai.azure.com/v1/"
      models:
        default: [
          "DeepSeek-R1",
          ]
        fetch: false
      titleConvo: true
      titleModel: current_model
      dropParams: ["stop", "user", "frequency_penalty", "presence_penalty"]
      modelDisplayLabel: "DeepSeek-R1"
```

https://www.librechat.ai/docs/quick_start/custom_endpoints
