### ISSUE TITLE
[Bug]: reasoning_effort parameter not available for omni model via Unify

### ISSUE THREAD

**Issue by illgitthat** [danny-avila/LibreChat#5647]
### What happened?

It looks like `reasoning_effort` parameter should be supported, but I don't see it available when I use the `o3-mini` model via the Unify provider.

Model name: `o3-mini@openai`

Related code: https://github.com/danny-avila/LibreChat/blob/0312d4f4f479f6ffde65c6d617d380ed55d8fec5/api/app/clients/OpenAIClient.js#L109

Maybe this regex just needs to be tweaked?

Relevant discussion: https://github.com/danny-avila/LibreChat/discussions/5623

### Steps to Reproduce

Add the following to your `librechat.yml`:

```yml
    # Unify
    - name: "Unify"
      apiKey: "${UNIFY_API_KEY}"
      baseURL: "https://api.unify.ai/v0/"
      models:
        default: [
          "o3-mini@openai",
          ]
        fetch: false
      titleConvo: false
      dropParams: ["stop", "user", "frequency_penalty", "presence_penalty"]
      iconURL: "https://raw.githubusercontent.com/fuegovic/lc-config-yaml/main/icons/Unify.webp"
```

### Relevant log output

```shell

```

### Screenshots

![Image](https://github.com/user-attachments/assets/2ad56a66-5c10-4536-86c8-a442719bec1d)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
