### ISSUE TITLE
[Enhancement]: Allow selecting Model Spec by URL Query Param

### ISSUE THREAD

**Issue by leejss** [danny-avila/LibreChat#6050]
### What features would you like to see added?

When accessing a page with an assistant_id, for example, via http://example.com/c/new?assistant_id=123456, it seems that the model selection section is not displaying the name defined in modelSpecs but is instead being set to null or undefined.

`localize('com_ui_none_selected')` is being displayed. It appears that the `spec` and `iconURL` in the conversation object are also being set to undefined.

Please revise it so that when accessing with the assistant_id query parameter, the name defined in modelSpecs is displayed.

### More details

The modelSpecs I defined are in the following format.

```yaml
modelSpecs:
  enforce: false
  prioritize: false
  list:
    - name: "Dall-E 3"
      label: "Dall-E 3"
      description: "Image Generator"
      iconURL: "fake_image.png"
      preset:
        endpoint: "assistants"
        assistant_id: "1234567"
        model: "gpt-4o"
    - name: "ServiceDesk"
      label: "Service Desk"
      description: "I am service desk"
      iconURL: "fake_icon.png"
      preset:
        name: "ServiceDesk"
        endpoint: "assistants"
        assistant_id: "12345678"
        model: "gpt-4o"
```
### Which components are impacted by your request?

UI

### Pictures

<img width="600" alt="Image" src="https://github.com/user-attachments/assets/883e8236-8aa7-49ba-9f27-bf3d864c6b4e" />

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
