### ISSUE TITLE
[Bug]: Custom provider with custom model name hits base token count of 4095

### ISSUE THREAD

**Issue by tinuva** [danny-avila/LibreChat#6094]
### What happened?

I set up a new install of LibreChat and wanted to test it with LiteLLM. 

In the message, I asked a simple question:

> which AI are you?

In the logs:
```
LibreChat              | 2025-02-27T16:19:34.225Z debug: [BaseClient] instructions tokenCount: 4959
LibreChat              | 2025-02-27T16:19:34.225Z warn: Instructions token count exceeds max token count (4959 / 4095).
LibreChat              | 2025-02-27T16:19:34.227Z error: [handleAbortError] AI response error; aborting request: { "type": "INPUT_LENGTH", "info": "4959 / 4095" }
```

My configuration file librechat.yaml:
```
version: 1.2.1

# Endpoints configuration
endpoints:
  custom:
    - name: "LiteLLM"
      apiKey: "......."
      baseURL: "http://litellm:4000"
      models:
        default: ["bedrock/us.anthropic.claude-3-7-sonnet-20250219-v1:0"]
        fetch: true
      titleConvo: false
      titleModel: "bedrock/us.anthropic.claude-3-7-sonnet-20250219-v1:0"
      summarize: false
      summaryModel: "bedrock/us.anthropic.claude-3-7-sonnet-20250219-v1:0"
      forcePrompt: false
      modelDisplayLabel: "LiteLLM"
      dropParams: ['stop', 'user', 'frequency_penalty', 'presence_penalty']
```

In litellm the model is configured as:
```
  - model_name: 'Bedrock: Claude-3.7 Sonnet'
    litellm_params:
      model: bedrock/us.anthropic.claude-3-7-sonnet-20250219-v1:0
      aws_region_name: us-east-2
      aws_access_key_id: os.environ/CUSTOM_AWS_ACCESS_KEY_ID
      aws_secret_access_key: os.environ/CUSTOM_AWS_SECRET_ACCESS_KEY
```

Now I have other applications that connects to LiteLLM and can use the models just fine. I only get this error in LibreChat.

I understand the token counts are configured in https://github.com/danny-avila/LibreChat/blob/main/api/utils/tokens.js but I don't really understand what the expected naming convention has to be, and worse, I don't understand why this limit applies to a custom provider.

### Version Information

```
$ sudo docker images | grep librechat
ghcr.io/danny-avila/librechat-dev                latest        eba95556cc47   19 hours ago    881MB
ghcr.io/danny-avila/librechat-rag-api-dev        latest        9a0541a57bb1   2 months ago    7.65GB
ghcr.io/danny-avila/librechat-rag-api-dev-lite   latest        095db2c2ff3b   2 months ago    1.29GB
```

### Steps to Reproduce

1. Use a custom litellm config with custom model names that differ from public available models
2. Add custom endpoint in librechat config
3. Ask a question long enough that go over 4095 tokens somehow.

### Relevant log output

```shell

```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by tinuva** [comment]
ok maybe the mistake was mine for using non-standard naming convention. After changing the names to look similar to what is in https://github.com/danny-avila/LibreChat/blob/main/api/utils/tokens.js I was able to get it to work

Looks like this now:
```
  - model_name: bedrock-claude-3-7-sonnet
    litellm_params:
      model: bedrock/us.anthropic.claude-3-7-sonnet-20250219-v1:0
      aws_region_name: us-east-2
      aws_access_key_id: os.environ/CUSTOM_AWS_ACCESS_KEY_ID
      aws_secret_access_key: os.environ/CUSTOM_AWS_SECRET_ACCESS_KEY
```
