### ISSUE TITLE
[Bug]: Agent using claude-3.7-sonnet not generating convo title

### ISSUE THREAD

**Issue by huzhekun** [danny-avila/LibreChat#6164]
### What happened?

Convo titles are correctly generated when using Claude-3.7-sonnet normally, but when it is being used in an agent (in this case one using google search tool) the title generation doesnt work

Console Error log message:
```
2025-03-03 22:07:47 error: [api/server/controllers/agents/client.js #titleConvo] Error Failed to parse. Text: "{}". Error: [{"code":"invalid_type","expected":"string","received":"undefined","path":["title"],"message":"Required"}]
Troubleshooting URL: https://js.langchain.com/docs/troubleshooting/errors/OUTPUT_PARSING_FAILURE/
```

potentially relevant env vars used for config:
```
            - name: ENDPOINTS
              value: agents,openAI,google,anthropic
            - name: OPENAI_MODELS
              value: chatgpt-4o-latest,o3-mini
            - name: ANTHROPIC_MODELS
              value: claude-3-7-sonnet-latest,claude-3-5-haiku-latest
```

mounted librechat.yaml:
```
    # Configuration version (required)
    version: 1.2.1
    endpoints:
      custom:
        - name: "Deepseek"
          apiKey: "${DEEPSEEK_API_KEY}"
          baseURL: "http://llama-cpp-server.chat-llama/v1"
          models:
            default: ["deepseek-reasoner"]
            fetch: false
          titleConvo: true
          titleModel: "current_model"
          modelDisplayLabel: "Local Deepseek"
```

### Version Information

running in kubernetes, image is librechat-dev:latest as of 3/3/2025 4:32PM

### Steps to Reproduce

1. Create agent with claude-3-7-sonnet
2. Create new convo with agent and ask agent question
3. Title is not updated

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell

```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
