### ISSUE TITLE
[Bug]: speechTab config overrides user settings in advanced panel

### ISSUE THREAD

**Issue by SollalF** [danny-avila/LibreChat#6168]
### What happened?

Setting the defaults for the TTS and STT in the `librechat.yaml` causes the user UI to be overridden with these settings even after being updated by the user.

I believe this PR aimed to fix that issue: https://github.com/danny-avila/LibreChat/pull/3282

Maybe this is intended behavior to prevent users to change the defaults but in that case the fields should be deactivated and the documentation/config updated to reflect wether those settings are for the default settings or to enforce those settings on the users.

I'm inclined to think that this is not expected behavior since changing those settings is possible and they do apply until the tab is reopened

### Version Information

librechat                                        latest    28e87df8f760   47 hours ago    1.57GB
ghcr.io/danny-avila/librechat-dev                latest    b7a847f1be0d   2 days ago      1.5GB
ghcr.io/danny-avila/librechat-rag-api-dev-lite   latest    a6b4babf521f   2 months ago    1.78GB

### Steps to Reproduce

1. Set the speechTab config in `librechat.yaml`

```
speech:
  speechTab: 
    conversationMode: false 
    advancedMode: true
    speechToText:
      engineSTT: 'external'
      languageSTT: 'English (US)'
      autoTranscribeAudio: true
      decibelValue: -45
      autoSendText: 0
    textToSpeech:
      engineTTS: 'external'
      voice: 'alloy'
      languageTTS: 'en'
      automaticPlayback: true
      playbackRate: 1.0
      cacheTTS: true
  tts:
    openai:
      apiKey: '${OPENAI_API_KEY}'
      model: 'tts-1'
      voices: ['alloy', 'echo', 'fable', 'onyx', 'nova', 'shimmer']
  stt:
    openai:
      apiKey: '${OPENAI_API_KEY}'
      model: 'whisper-1
``` 

2. Use the UI to modify a value in settings>speech who's default was defined in the config.
3. Close the speech tab and come back
4. The setting modified should be back to defaults

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
None to note
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
