### ISSUE TITLE
[Enhancement]: Reasoning using LiteLLM configured with VertexAI Claude 3.7

### ISSUE THREAD

**Issue by elvis-cai** [danny-avila/LibreChat#6183]
### What features would you like to see added?

I just saw Librechat support Claude 3.7 with thinking(https://github.com/danny-avila/LibreChat/pull/6008), and that is awesome!
since we are using Litellm as AI gateway configured with VertexAI Claude 3.7, we are curious if we could use it with thinking mode enabled as well
Let me know if you need more info, thanks.

### More details

This is a working example of using OpenAI SDK with Litellm vertexai claude 3.7 configured
```
from openai import OpenAI

client = OpenAI(
  base_url="https://litellm.abc.com",
  api_key="sk-xxxx"
)

response = client.chat.completions.create(
    model="vertex_ai/claude-3-7-sonnet@20250219",
    stream=True,
    messages=[
        {"role": "system", "content": "You are a helpful assistant designed to output JSON."},
        {"role": "user", "content": "Melbourne best coffee shop"}
    ],
    extra_body={
        "thinking": {
            "type": "enabled",
            "budget_tokens": 1024
        }
    }
)
```

print(f"response: {response}")

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by elvis-cai** [comment]
Thanks @danny-avila , in our case, I think we are bit different, we are using openai SDK instead of VertexAI SDk, so it's more like the called using openai compatible SDK slimiar to https://docs.anthropic.com/en/api/openai-sdk#extended-thinking-support

**Comment by elvis-cai** [comment]
Thanks @danny-avila , can confirm it works using litellm as ai proxy and vertexai claude 3.7 as llm provider with librechat configured with 
```
  custom:
    - name: "My LLM"
      apiKey: "${LITELLM_API_KEY}"
      baseURL: "https://litellm.xxx.com
      models:
        default: ["claude-3-7-sonnet"]
        fetch: false
      titleConvo: true
      titleModel: "gpt-4o"
      summarize: false
      summaryModel: "gpt-4o"
      forcePrompt: false
      modelDisplayLabel: "My LLM"
      addParams:
        thinking:
          type: enabled
          budget_tokens: 1024
````

<img width="939" alt="Image" src="https://github.com/user-attachments/assets/e5624720-daca-46b4-86f7-3f0f75678a24" />
