### ISSUE TITLE
I am lost, I give up

### ISSUE THREAD

**Issue by vmajor** [danny-avila/LibreChat#6281]
How can I set up llama-server so that I can use locally hosted model.

Last time I tried LibreChat I successfuly ran R1, well semi-successfully because the session kept getting terminated due to timeout and that was a feature not a bug.

This time I am attempting to deploy the new QwQ-32B model and for the life of me I cannot remember how I deployed R1, or I am doing something extremely wrong as all am I given is a choice of default models in the dropdown, not my custom endpoint that I created in librechat.yaml

docker.compose.override.yal

```
services:
  api:
    volumes:
    - type: bind
      source: ./librechat.yaml
      target: /app/librechat.yaml
    image: ghcr.io/danny-avila/librechat:latest

```

librechat.yaml

```
# Configuration version (required)
version: 1.2.1

# Cache settings: Set to true to enable caching
cache: true


# Definition of custom endpoints
endpoints:
  custom:      
    - name: "llama-server"   
      apiKey: "1234"
      baseURL: "http://localhost:8080/v1"
      models:
        default: ["QwQ-32B"]
        fetch: true
      titleConvo: true
      titleModel: "QwQ-32B.gguf"
      summarize: false
      summaryModel: "QwQ-32B.gguf"
      forcePrompt: false
      modelDisplayLabel: "QwQ-32B"

 # endpointsMenu: true
 # modelSelect: true
  parameters: true
  sidePanel: true
  presets: true
  prompts: true
  bookmarks: true
  multiConvo: true
  agents: true

# Example Registration Object Structure (optional)
registration:
  socialLogins: ['github', 'google', 'discord', 'openid', 'facebook', 'apple']

# Example MCP Servers Object Structure
mcpServers:
  everything:
    # type: sse # type can optionally be omitted
    url: http://localhost:3001/sse
    timeout: 60000  # 1 minute timeout for this server, this is the default timeout for MCP servers.
  puppeteer:
    type: stdio
    command: npx
    args:
      - -y
      - "@modelcontextprotocol/server-puppeteer"
    timeout: 300000  # 5 minutes timeout for this server
  filesystem:
    # type: stdio
    command: npx
    args:
      - -y
      - "@modelcontextprotocol/server-filesystem"
      - /home/user/LibreChat/
    iconPath: /home/user/LibreChat/client/public/assets/logo.svg
  
```

what else do I need to do to make this work?

**Comment by vmajor** [comment]
Here is the configuration for `librechat.yml` that works with `llama-server`.

```
# Configuration version (required)
version: 1.2.1

# Cache settings: Set to true to enable caching
cache: true


# Definition of custom endpoints
endpoints:
  custom:      
    - name: "llama-server"   
      apiKey: "1234"
      baseURL: "http://host.docker.internal:8080/v1"
      models:
        default: ["QwQ-32B-Q6_K.gguf"]
        fetch: false
      titleConvo: true
      titleModel: "QwQ-32B-Q6_K.gguf"
      summarize: false
      summaryModel: "QwQ-32B-Q6_K.gguf"
      forcePrompt: false
      modelDisplayLabel: "QwQ-32B"
```

I also suggest not relying on `docker-compose-override.yml` and instead merging your changes into `docker-compose.yml` like this:

```
...
volumes:
      - type: bind
        source: ./.env
        target: /app/.env
      - type: bind  
        source: ./librechat.yaml
        target: /app/librechat.yaml
      - ./images:/app/client/public/images
      - ./uploads:/app/uploads
      - ./logs:/app/api/logs
...
```
