### ISSUE TITLE
[Bug]: Inconsistent fileConfig Restrictions for Custom Endpoints Between SidePanel and Direct File Upload

### ISSUE THREAD

**Issue by skyking363** [danny-avila/LibreChat#6296]
#### **Description**
While using LibreChat, I’ve noticed that the `fileConfig` settings for custom endpoints (e.g., "Deepseek") correctly restrict file uploads in the SidePanel, but fail to do so in the direct upload interface (e.g., the paperclip icon), allowing unsupported file types to be uploaded. In contrast, other native endpoints (e.g., "bedrock") consistently apply `fileConfig` restrictions in both the SidePanel and direct upload scenarios.

#### **Configuration Details**
Here is the relevant section of my `librechat.yaml` file related to `fileConfig`:

```yaml
fileConfig:
  endpoints:
    bedrock:
      fileLimit: 5
      fileSizeLimit: 1024  # Maximum size for an individual file in MB
      totalSizeLimit: 10240  # Maximum total size for all files in a single request in MB
      supportedMimeTypes:
        - "text/.*"
        - "application/.*"
        - "application/x-sh"
    openAI:
      disabled: true  # Disables file uploading to the OpenAI endpoint
    default:
      fileLimit: 5
      fileSizeLimit: 1024
      totalSizeLimit: 10240
      supportedMimeTypes:
        - "image/.*"
        - "text/.*"
        - "application/.*"
        - "application/x-sh"
    Deepseek:
      fileLimit: 5
      fileSizeLimit: 1024  # Maximum size for an individual file in MB
      totalSizeLimit: 10240  # Maximum total size for all files in a single request in MB
      supportedMimeTypes:
        - "text/.*"
        - "application/.*"
        - "application/x-sh"
```

#### **Problem Details**
- **Behavior in SidePanel**:  
  In the SidePanel, when I attempt to upload an image file (MIME type "image/.*") to the "Deepseek" endpoint, the system correctly blocks the upload and displays an error message. This is expected since "Deepseek"’s `supportedMimeTypes` only allows "text/.*", "application/.*", and "application/x-sh", explicitly excluding "image/.*".

- **Behavior in Direct Upload**:  
  However, when I use the direct upload feature (e.g., clicking the paperclip icon) to upload the same image file to the "Deepseek" endpoint, the system allows the upload to succeed, despite the `fileConfig` explicitly restricting supported MIME types. This behavior is inconsistent with expectations.

#### **Behavior of Other Endpoints**
- **"bedrock" Endpoint**:  
  The "bedrock" endpoint has the same `supportedMimeTypes` as "Deepseek", excluding "image/.*". It’s expected to block image uploads in both the SidePanel and direct upload. However, since the YAML doesn’t clarify whether "bedrock" is a custom endpoint, further confirmation is needed to determine if it exhibits the same inconsistency.

#### **Expected Behavior**
The `fileConfig` settings for custom endpoints (e.g., "Deepseek") should consistently enforce restrictions in both the SidePanel and direct upload interfaces. For example, if "image/.*" is excluded from `supportedMimeTypes`, image uploads should be blocked regardless of the upload method (SidePanel or direct upload).

#### **Request**
Please investigate and fix the issue where custom endpoints fail to apply `fileConfig` settings correctly during direct uploads, ensuring that file upload restrictions are consistently enforced across all upload paths (SidePanel and direct upload).

### Version Information

**LibreChat Version**: v0.7.7

### Steps to Reproduce

1. my `librechat.yaml` file related to `fileConfig`:
```yaml
fileConfig:
  endpoints:
    bedrock:
      fileLimit: 5
      fileSizeLimit: 1024  # Maximum size for an individual file in MB
      totalSizeLimit: 10240  # Maximum total size for all files in a single request in MB
      supportedMimeTypes:
        - "text/.*"
        - "application/.*"
        - "application/x-sh"
    openAI:
      disabled: true  # Disables file uploading to the OpenAI endpoint
    default:
      fileLimit: 5
      fileSizeLimit: 1024
      totalSizeLimit: 10240
      supportedMimeTypes:
        - "image/.*"
        - "text/.*"
        - "application/.*"
        - "application/x-sh"
    Deepseek:
      fileLimit: 5
      fileSizeLimit: 1024  # Maximum size for an individual file in MB
      totalSizeLimit: 10240  # Maximum total size for all files in a single request in MB
      supportedMimeTypes:
        - "text/.*"
        - "application/.*"
        - "application/x-sh"
```
2. **"bedrock" Endpoint**:
- SidePanel : 
![Image](https://github.com/user-attachments/assets/bf773485-466a-42bf-97ec-2a2268feb568)
- Direct upload: 
![Image](https://github.com/user-attachments/assets/8dc907fa-3d04-4eda-8410-db0bd89e9d26)
3. **"Deepseek" endpoint**(Custom Endpoint)**:
- SidePanel : 
![Image](https://github.com/user-attachments/assets/cb018d0c-b281-4ad8-8a76-c000e8d0a2e3)
- Direct upload: 
![Image](https://github.com/user-attachments/assets/5eece4cd-c61a-4346-b0a4-6218e3c1b9da)

### Relevant log output

```shell

```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
