### ISSUE TITLE
[Bug]: No key found for some Agents on 0.7.7

### ISSUE THREAD

**Issue by brentp913** [danny-avila/LibreChat#6559]
### What happened?

After upgrading LibreChat from 0.7.6 to 0.7.7, all of my Agents that used non-OpenAI models give me the error message:
"No key found. Please provide a key and try again."

The console log in docker shows the following:
```
librechat-api  | 2025-03-26 19:22:12 info: ---Invalid conversation ID Params: {
librechat-api  |   "messageId": "e2694118-16e1-4a4f-aa88-39a80e4c8ef9",
librechat-api  |   "parentMessageId": "00000000-0000-0000-0000-000000000000",
librechat-api  |   "unfinished": false,
librechat-api  |   "error": true,
librechat-api  |   "final": true,
librechat-api  |   "text": "{\"type\":\"no_user_key\"}",
librechat-api  |   "isCreatedByUser": false,
librechat-api  |   "user": "6706b6679b4285f3ea3976fa"
librechat-api  | }
librechat-api  | 2025-03-26 19:22:41 error: [handleAbortError] AI response error; aborting request: {"type":"no_user_key"}
```

Additionally, when I try the Deepseek R1 model, I get these errors:
```
librechat-api  | 2025-03-26 20:07:30 error: [api/server/controllers/agents/client.js #sendCompletion] Operation aborted Deepseek API key not found. Please set the DEEPSEEK_API_KEY environment variable or pass the key into "apiKey" field.
librechat-api  | 2025-03-26 20:07:30 error: [api/server/controllers/agents/client.js #sendCompletion] Unhandled error type Deepseek API key not found. Please set the DEEPSEEK_API_KEY environment variable or pass the key into "apiKey" field.
librechat-api  | 2025-03-26 20:07:30 error: [handleAbortError] AI response error; aborting request: Deepseek API key not found. Please set the DEEPSEEK_API_KEY environment variable or pass the key into "apiKey" field.
```

In the previous version of LibreChat, it used the `apiKey`'s that I set in librechat.yaml were used. I suspect that because some of the model names I'm using under `custom` endpoints align with actual services, that 0.7.7 is trying to use the API keys from the environment variables, which I don't set because I use LiteLLM as a proxy.

### Version Information

```
ghcr.io/danny-avila/librechat-rag-api-dev   v0.4.0                        7fd465954a4f   2 weeks ago     7.79GB
ghcr.io/danny-avila/librechat               v0.7.7                        92d57359fc25   2 weeks ago     888MB
```

### Steps to Reproduce

1. Run 0.7.7 through Docker. Using the following `librechat.yaml`:
```
version: 1.2.1
interface:
  endpointsMenu: true
  modelSelect: true
  parameters: true
  sidePanel: true
  presets: true
  prompts: true
  bookmarks: true
  multiConvo: true
  agents: true
endpoints:
  agents:
    disableBuilder: false
    capabilities: []
  custom:
    - name: 'Anthropic'
      apiKey: 'removed-for-privacy'
      baseURL: 'http://our-litellm-server:4000'
      models:
        default:
          - 'anthropic-claude-3-5-sonnet'
          - 'anthropic-claude-3-7-sonnet'
          - 'anthropic-claude-3-opus'
          - 'anthropic-claude-3-5-haiku'
        fetch: false
      titleConvo: true
      titleModel: 'meta-llama3-1-8b-instruct'
      titleMessageRole: 'user'
      summarize: false
      summaryModel: 'meta-llama3-1-8b-instruct'
      forcePrompt: false
      modelDisplayLabel: 'Anthropic'
      dropParams:
        - presence_penalty
        - frequency_penalty
      iconURL: anthropic
```
Note: Our LiteLLM server accesses Claude through AWS Bedrock if that matters at all.

2. Create a new agent
3. In the model settings, select "Provider": "Anthropic", "Model": "anthropic-claude-3-5-sonnet". Alternatively, "Provider": "Deepseek", with "Model": "deepseek-r1" will also fail and give additional error messages.
4. Send anything to the model.

### What browsers are you seeing the problem on?

Microsoft Edge

### Relevant log output

```shell
This error shows up a bunch:

{"level":"error","message":"[handleAbortError] AI response error; aborting request: {\"type\":\"no_user_key\"}","stack":"Error: {\"type\":\"no_user_key\"}\n    at getUserKey (/app/api/server/services/UserService.js:47:11)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async initializeClient (/app/api/server/services/Endpoints/anthropic/initialize.js:12:7)\n    at async initializeAgentOptions (/app/api/server/services/Endpoints/agents/initialize.js:128:19)\n    at async initializeClient (/app/api/server/services/Endpoints/agents/initialize.js:208:25)\n    at async AgentController (/app/api/server/controllers/agents/request.js:47:24)\n    at async /app/api/server/routes/agents/chat.js:37:5"}


This error shows up for Deepseek:

{"level":"error","message":"[api/server/controllers/agents/client.js #sendCompletion] Operation aborted Deepseek API key not found. Please set the DEEPSEEK_API_KEY environment variable or pass the key into \"apiKey\" field.","stack":"Error: Deepseek API key not found. Please set the DEEPSEEK_API_KEY environment variable or pass the key into \"apiKey\" field.\n    at new ChatDeepSeek (/app/node_modules/@langchain/deepseek/dist/chat_models.cjs:371:19)\n    at StandardGraph.initializeModel (/app/node_modules/@librechat/agents/dist/cjs/graphs/Graph.cjs:202:23)\n    at new StandardGraph (/app/node_modules/@librechat/agents/dist/cjs/graphs/Graph.cjs:65:32)\n    at Run.createStandardGraph (/app/node_modules/@librechat/agents/dist/cjs/run.cjs:50:31)\n    at new Run (/app/node_modules/@librechat/agents/dist/cjs/run.cjs:40:39)\n    at Run.create (/app/node_modules/@librechat/agents/dist/cjs/run.cjs:61:16)\n    at createRun (/app/api/server/controllers/agents/run.js:75:14)\n    at runAgent (/app/api/server/controllers/agents/client.js:680:21)\n    at AgentClient.chatCompletion (/app/api/server/controllers/agents/client.js:714:13)\n    at AgentClient.sendCompletion (/app/api/server/controllers/agents/client.js:373:16)"}
{"level":"error","message":"[api/server/controllers/agents/client.js #sendCompletion] Unhandled error type Deepseek API key not found. Please set the DEEPSEEK_API_KEY environment variable or pass the key into \"apiKey\" field.","stack":"Error: Deepseek API key not found. Please set the DEEPSEEK_API_KEY environment variable or pass the key into \"apiKey\" field.\n    at new ChatDeepSeek (/app/node_modules/@langchain/deepseek/dist/chat_models.cjs:371:19)\n    at StandardGraph.initializeModel (/app/node_modules/@librechat/agents/dist/cjs/graphs/Graph.cjs:202:23)\n    at new StandardGraph (/app/node_modules/@librechat/agents/dist/cjs/graphs/Graph.cjs:65:32)\n    at Run.createStandardGraph (/app/node_modules/@librechat/agents/dist/cjs/run.cjs:50:31)\n    at new Run (/app/node_modules/@librechat/agents/dist/cjs/run.cjs:40:39)\n    at Run.create (/app/node_modules/@librechat/agents/dist/cjs/run.cjs:61:16)\n    at createRun (/app/api/server/controllers/agents/run.js:75:14)\n    at runAgent (/app/api/server/controllers/agents/client.js:680:21)\n    at AgentClient.chatCompletion (/app/api/server/controllers/agents/client.js:714:13)\n    at AgentClient.sendCompletion (/app/api/server/controllers/agents/client.js:373:16)"}
{"level":"error","message":"[handleAbortError] AI response error; aborting request: Deepseek API key not found. Please set the DEEPSEEK_API_KEY environment variable or pass the key into \"apiKey\" field.","stack":"Error: Deepseek API key not found. Please set the DEEPSEEK_API_KEY environment variable or pass the key into \"apiKey\" field.\n    at new ChatDeepSeek (/app/node_modules/@langchain/deepseek/dist/chat_models.cjs:371:19)\n    at StandardGraph.initializeModel (/app/node_modules/@librechat/agents/dist/cjs/graphs/Graph.cjs:202:23)\n    at new StandardGraph (/app/node_modules/@librechat/agents/dist/cjs/graphs/Graph.cjs:65:32)\n    at Run.createStandardGraph (/app/node_modules/@librechat/agents/dist/cjs/run.cjs:50:31)\n    at new Run (/app/node_modules/@librechat/agents/dist/cjs/run.cjs:40:39)\n    at Run.create (/app/node_modules/@librechat/agents/dist/cjs/run.cjs:61:16)\n    at createRun (/app/api/server/controllers/agents/run.js:75:14)\n    at runAgent (/app/api/server/controllers/agents/client.js:680:21)\n    at AgentClient.chatCompletion (/app/api/server/controllers/agents/client.js:714:13)\n    at AgentClient.sendCompletion (/app/api/server/controllers/agents/client.js:373:16)"}
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
