### ISSUE TITLE
[Bug]: Azure Foundry endpoint not working

### ISSUE THREAD

**Issue by loureirodnl** [danny-avila/LibreChat#6564]
### What happened?

Hello

Did Azure AI Foundry changed anything recently ?

Because I'm following exactly the explanations you provide on this thread but I'm having the following error :

![image](https://github.com/user-attachments/assets/1587d0a7-fae6-4e8a-8c5b-b9d1ccb2750a)

![image](https://github.com/user-attachments/assets/12325f35-36f0-48fe-8d8a-7ec959c1dffe)

Version: LibreChat v0.7.7 using docker compose and @rubentalstra suggested librechat.yml config above

```
error: [OpenAIClient.chatCompletion] Unhandled error type Invalid URL
error: [handleAbortError] AI response error; aborting request: Invalid URL
```

I tried everything that is explained in this discussion but nothing worked

My Azure AI Foundry setup :
![image](https://github.com/user-attachments/assets/ae21311e-4f13-4634-96a1-2abd415a2742)

Thank you for your help

Linked to discussion: https://github.com/danny-avila/LibreChat/discussions/5924

### Version Information

```
docker images | grep librechat
ghcr.io/danny-avila/librechat-dev                                                                latest             2947f02d5e16   2 weeks ago     876MB
```

### Steps to Reproduce

Put the following config in librechat.yaml

```
endpoints:
  azureOpenAI:
    groups:
      - group: "DeepSeek-R1"
        apiKey: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
        baseURL: "https://XXXXXXXXX.services.ai.azure.com/models/"
        serverless: true
        models:
          DeepSeek-R1: true

```

### Relevant log output

```shell

```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
