### ISSUE TITLE
openAI is not listed in UI group selection

### ISSUE THREAD

**Issue by kmilo9999** [danny-avila/LibreChat#6686]
want to have openAI and 'azure openAI' endpoints in libreachat, but only 1 shows. Taking a look at the documentation is possible to separate them:
This is my librechat.yaml, but only azure is listed:
```
endpoints:
      openAI:
        # Endpoint-level configuration
        titleModel: "gpt-4o"
        fileSizeLimit: 5000
        groups:
        # Group-level configuration
        - group: "gpt-4o"
          apiKey: "${AZURE_OPENAI_API_KEY
          instanceName: "ccv-ai"
          version: "${OPENAI_API_VERSION}"
          # Model-level configuration
          models:
            gpt-4o:
              deploymentName: "gpt-4o"
              version: "${OPENAI_API_VERSION}"
      azureOpenAI:
        # Endpoint-level configuration
        titleModel: "Llama-3.3-70B-Instruct"
        fileSizeLimit: 5000
        groups:
        - group: "Llama-3.3-70B-Instruct"
          apiKey: "${LLAMA_KEY}"
          version: "2024-05-01-preview" 
          serverless: true
          models:
             Llama-3.3-70B-Instruct: true

```
What could I be missing that's causing OpenAI not to show up?

![Image](https://github.com/user-attachments/assets/ba8d7cfc-5099-4a56-91db-05b8ace91a2c)

Thank you for the help in advance
