### ISSUE TITLE
[Bug]: greeting under modelSpecs does not work any more after interface.customWelcome is introduced

### ISSUE THREAD

**Issue by elvis-cai** [danny-avila/LibreChat#6761]
### What happened?

as title, we found after upgrading to latest image, the previous greeting msg does not work any more, no matter we change customWelcome to empty or remove this setting `interface.customWelcome` 

### Version Information

```
 git rev-parse HEAD
175cfe8ffba239b36b3b793857964459a034fbde
```

docker images
```
docker pull ghcr.io/danny-avila/librechat-dev-api
Using default tag: latest
latest: Pulling from danny-avila/librechat-dev-api
Digest: sha256:aa08e6f6abc0a20a38bed55a37f3a1bb93adce5bca37b270170644e807145f43
Status: Image is up to date for ghcr.io/danny-avila/librechat-dev-api:latest
````

### Steps to Reproduce

How to reproduce?
just clone the repo and add https://www.librechat.ai/docs/configuration/librechat_yaml/object_structure/model_specs#example  to the librechat.yaml

```
modelSpecs:
  enforce: true
  prioritize: true
  list:
    - name: "meeting-notes-gpt4"
      label: "Meeting Notes Assistant (GPT4)"
      default: true
      description: "Generate meeting notes by simply pasting in the transcript from a Teams recording."
      preset:
        endpoint: "azureOpenAI"
        model: "gpt-4-turbo-1106-preview"
        maxContextTokens: 128000 # Maximum context tokens
        max_tokens: 4096 # Maximum output tokens
        temperature: 0.2
        modelLabel: "Meeting Summarizer"
        greeting: |
          This assistant creates meeting notes based on transcripts of Teams recordings.
          To start, simply paste the transcript into the chat box.
```
Here's what we can see 

![Image](https://github.com/user-attachments/assets/fd1a06c7-3a9d-4b5d-817c-ea1bcfbafc59)

### Relevant log output

```shell

```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
