### ISSUE TITLE
[Bug]: Title generation fails with MCP servers enabled

### ISSUE THREAD

**Issue by benverhees** [danny-avila/LibreChat#6892]
### What happened?

I get an error on conversation title generation:

`error: [api/server/controllers/agents/client.js #titleConvo] Error 400 Unsupported parameter: 'max_tokens' is not supported with this model. Use 'max_completion_tokens' instead.`

I am using a modelSpec with `model: "o3-mini"`. The model has `titleModel: "gpt-4o-mini”` and `titleConvo: true`

Title generation fails when I have an MCP server selected in the chat. When no MCP servers are selected, title generation works fine.

I expect title generation to work with an MCP server selected as well.

### Version Information

```
ghcr.io/danny-avila/librechat-dev                 latest    9271978cdfd6   2 hours ago     1.6GB
ghcr.io/librechat-ai/codesandbox-client/bundler   latest    3fcab2be887a   4 days ago      206MB
ghcr.io/danny-avila/librechat-rag-api-dev         latest    19f02eaa8345   6 days ago      3.92GB
```

### Steps to Reproduce

Here is a minimal librechat.yml to reproduce the issue

```yml
# For more information, see the Configuration Guide:
# https://www.librechat.ai/docs/configuration/librechat_yaml

# Configuration version (required)
version: 1.2.1

# Cache settings: Set to true to enable caching
cache: true

mcpServers:
  timezoneToolkit:
    command: npx
    args:
      - -y,
      - "@cicatriz/timezone-toolkit@latest"

# Definition of custom endpoints
endpoints:
  azureOpenAI:
    titleModel: "gpt-4o-mini"
    titleConvo: true
    groups:
      - group: "azure-openai" # arbitrary name
        apiKey: "${AZURE_OPENAI_API_KEY}"
        instanceName: "largelanguagemodels-azureopenai-service"
        version: "2025-02-01-preview"
        models:
          o3-mini:
            deploymentName: o3-mini
          gpt-4o-mini:
            deploymentName: 4o-mini
modelSpecs:
  list:
    - name: "Test"
      label: "Test"
      preset:
        endpoint: "azureOpenAI"
        model: "o3-mini"
```

1. Select the `timezoneToolkit` or any other available in your configuration in the MCP Servers dropdown in the chat input.
2. Write and send a message
3. Wait until the reponse is shown
4. See the "New Chat" conversation title in the conversation panel
5. Check the LibreChat logs and find `error: [api/server/controllers/agents/client.js #titleConvo] Error 400 Unsupported parameter: 'max_tokens' is not supported with this model. Use 'max_completion_tokens' instead.`

### Relevant log output

```shell
{
    "attemptNumber": 1,
    "code": "unsupported_parameter",
    "error": {
        "code": "unsupported_parameter",
        "message": "Unsupported parameter: 'max_tokens' is not supported with this model. Use 'max_completion_tokens' instead.",
        "param": "max_tokens",
        "type": "invalid_request_error"
    },
    "headers": {
        "apim-request-id": "ecfdc318-bd56-4efa-86b9-63d6e4204fd1",
        "azureml-model-session": "v20250319-1-164616836",
        "content-length": "245",
        "content-type": "application/json",
        "date": "Tue, 15 Apr 2025 10:12:01 GMT",
        "ms-azureml-model-error-reason": "model_error",
        "ms-azureml-model-error-statuscode": "400",
        "ms-azureml-model-time": "21",
        "strict-transport-security": "max-age=31536000; includeSubDomains; preload",
        "x-aml-cluster": "hyena-swedencentral-02",
        "x-content-type-options": "nosniff",
        "x-envoy-upstream-service-time": "22",
        "x-ms-client-request-id": "ecfdc318-bd56-4efa-86b9-63d6e4204fd1",
        "x-ms-deployment-name": "o3-mini",
        "x-ms-rai-invoked": "true",
        "x-ms-region": "West Europe",
        "x-ratelimit-limit-requests": "109",
        "x-ratelimit-limit-tokens": "1090000",
        "x-ratelimit-remaining-requests": "107",
        "x-ratelimit-remaining-tokens": "1089909",
        "x-request-id": "fe1c2191-4655-478b-bcda-0974c235e12b"
    },
    "level": "error",
    "message": "[api/server/controllers/agents/client.js #titleConvo] Error 400 Unsupported parameter: 'max_tokens' is not supported with this model. Use 'max_completion_tokens' instead.",
    "param": "max_tokens",
    "request_id": "fe1c2191-4655-478b-bcda-0974c235e12b",
    "retriesLeft": 6,
    "stack": "Error: 400 Unsupported parameter: 'max_tokens' is not supported with this model. Use 'max_completion_tokens' instead.\n    at APIError.generate (/app/node_modules/openai/error.js:45:20)\n    at CustomAzureOpenAIClient.makeStatusError (/app/node_modules/openai/core.js:302:33)\n    at CustomAzureOpenAIClient.makeRequest (/app/node_modules/openai/core.js:346:30)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async /app/node_modules/@librechat/agents/node_modules/@langchain/openai/dist/chat_models.cjs:2036:29\n    at async RetryOperation._fn (/app/node_modules/p-retry/index.js:50:12)",
    "status": 400,
    "type": "invalid_request_error"
}
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
