### ISSUE TITLE
[Bug]: Unable to attach MCP Server on windows 11

### ISSUE THREAD

**Issue by usama-dtc** [danny-avila/LibreChat#6923]
### What happened?

I tried to attach MCP server with LibreChat on windows 11

librechat.yaml:
```
mcpServers:
  puppeteer:
    command: npx
    args:
      - -y
      - "@modelcontextprotocol/server-puppeteer"
```

In the logs I see this:
```
LibreChat         | 2025-04-16 21:26:29 info: [MCP] Initializing app-level servers
LibreChat         | 2025-04-16 21:26:39 error: [MCP][puppeteer] Connection failed: Connection timeout
LibreChat         | 2025-04-16 21:26:41 error: [MCP][puppeteer] Connection failed: MCP error -32000: Connection closed
LibreChat         | 2025-04-16 21:26:55 error: [MCP][puppeteer] Connection failed: Connection timeout
LibreChat         | 2025-04-16 21:26:55 error: [MCP][puppeteer] Failed to connect after 3 attempts Connection timeout
LibreChat         | 2025-04-16 21:26:55 error: [MCP][puppeteer] Initialization failed Connection timeout
LibreChat         | 2025-04-16 21:26:55 info: [MCP] Initialized 0/1 app-level server(s)
LibreChat         | 2025-04-16 21:26:55 warn: [MCP] 1/1 app-level server(s) failed to initialize
LibreChat         | 2025-04-16 21:26:55 info: [MCP][puppeteer] ✗ Failed
LibreChat         | 2025-04-16 21:26:55 warn: [MCP] No app-level servers initialized
```

Docker-Compose:
```
services:
  api:
    volumes:
      - ./librechat.yaml:/app/librechat.yaml
```
I have followed the installation instrcutions mentioned in LibreChat Docs

### Version Information

ghcr.io/danny-avila/librechat-dev                latest    9271978cdfd6   38 hours ago    1.6GB
ghcr.io/danny-avila/librechat-rag-api-dev-lite   latest    566585698235   8 days ago      1.85GB

### Steps to Reproduce

docker compose up

### Relevant log output

```shell

```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
