### ISSUE TITLE
[Bug]: default openrouter model invalid

### ISSUE THREAD

**Issue by nexus9111** [danny-avila/LibreChat#7022]
### What happened?

Hello, I'm trying to set only openai/gpt-4.1 and I still got all models and microsoft as default

```yaml
version: 1.2.1

endpoints:
  custom:
    - name: "OpenRouter"
      # For `apiKey` and `baseURL`, you can use environment variables that you define.
      # recommended environment variables:
      apiKey: "${OPENROUTER_KEY}" # NOT OPENROUTER_API_KEY
      baseURL: "https://openrouter.ai/api/v1"
      models:
        default: ["openai/gpt-4.1"]
        fetch: true
      titleConvo: true
      titleModel: "openai/gpt-4.1"
      # Recommended: Drop the stop parameter from the request as Openrouter models use a variety of stop tokens.
      dropParams: ["stop"]
      modelDisplayLabel: "OpenRouter"
```

<img width="783" alt="Image" src="https://github.com/user-attachments/assets/49f21216-d14c-4db4-b1ad-ad4c6aa69dd9" />

### Version Information

ghcr.io/danny-avila/librechat-dev                latest    1f62020d0427   4 days ago      951MB
ghcr.io/danny-avila/librechat-rag-api-dev-lite   latest    817faebddae9   2 weeks ago     1.31GB

### Steps to Reproduce

1. create the yaml file
2. set default models (like in documentation)
3. run librechat

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell

```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
