### ISSUE TITLE
[Enhancement]: Better display of Model Name InferenceProfile in AWS Bedrock

### ISSUE THREAD

**Issue by djuillard** [danny-avila/LibreChat#7065]
### What features would you like to see added?

The endpoint model name in AWS Bedrock with Inference profile is not very friendly. I would like to rename it in a more explicit way like "Claude 3.7 Sonnet".

### More details

I have setup an AWS Bedrock Claude 3.7 endpoint, and it comes with a cross region Inference Profile. 

I works, but the only concern is the way it is displayed in the menu : 

![Image](https://github.com/user-attachments/assets/1cf60681-799f-4fef-a7b7-185bc3266b12)

I have tried a lot of settings in the modelSpecs to try to make it appear in a better way, but no results. 

Is there anything I missed, or is it something to be improved in the future ?

Thanks

### Pictures

![Image](https://github.com/user-attachments/assets/34bc19b5-39da-40fd-ba3b-cd6027b8de2f)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Actually, you can do this pretty well with model specs, here's an example:
```yaml
interface:
  agents: true
  prompts: true
  parameters: true
  presets: true
  runCode: true
  modelSelect: true
  bookmarks: true
  multiConvo: true
modelSpecs:
  enforce: false
  prioritize: true
  addedEndpoints: ["agents"]
  list:
    - name: "Azure OpenAI GPT-4"
      label: "GPT-4o Mini"
      iconURL: "openAI"
      default: false
      description: "OpenAI Fast Model"
      preset:
        endpoint: "azureOpenAI"
        model: "gpt-4o-mini"
        modelLabel: "GPT-4o Mini"        # the model label that will be displayed in the UI
    - name: "Azure OpenAI GPT-4o"
      label: "GPT-4o"
      iconURL: "openAI"
      default: false
      description: "Advanced Conversational AI"
      preset:
        endpoint: "azureOpenAI"
        model: "gpt-4o"
        modelLabel: "GPT-4o"        # the model label that will be displayed in the UI
    - name: "Azure OpenAI o1-mini"
      label: "o1-mini"
      iconURL: "openAI"
      default: false
      description: "Compact, Efficient Language Model"
      preset:
        endpoint: "azureOpenAI"
        model: "o1-mini"
        modelLabel: "o1-mini"        # the model label that will be displayed in the UI
    - name: "Bedrock Anthropic Haiku" # name is arbitrary and specific to bu
      label: "Anthropic Claude 3.5 Haiku" # this is what the user sees
      iconURL: "anthropic" # this comes from the project repo
      description: "Fast, Efficient Conversational AI"
      default: false
      preset:
        endpoint: "bedrock"
        model: "us.anthropic.claude-3-5-haiku-20241022-v1:0" # actual model label
        modelLabel: "Anthropic Claude 3.5 Haiku"        # the model label that will be displayed in the UI
    - name: "Bedrock Nova Model" # name is arbitrary and specific to bu
      label: "AWS Nova Model" # this is what the user sees
      #iconURL: "" # this comes from the project repo
      description: "Fast, Scalable Cloud Model"
      default: false
      preset:
        endpoint: "bedrock"
        model: "amazon.nova-lite-v1:0" # actual model label
        modelLabel: "AWS Nova Model"        # the model label that will be displayed in the UI
    - name: "llama 3.2 Model" # name is arbitrary and specific to bu
      label: "llama 3.2 General Model" # this is what the user sees
      #iconURL: "" # this comes from the project repo
      description: "Advanced Contextual Understanding"
      default: false
      preset:
        endpoint: "bedrock"
        model: "us.meta.llama3-2-1b-instruct-v1:" # actual model label
        modelLabel: "llama 3.2 General Model"        # the model label that will be displayed in the UI
```



![Image](https://github.com/user-attachments/assets/2e766cf1-b664-4cf7-b673-ddf6c77aa9da)

**Comment by djuillard** [comment]
Thanks for your reply. 

But actually, it does not solve it. I think it is something related to Inference Profile.

Here is my librechat.yaml conf : 

```
version: 1.2.1

...

interface:
  customWelcome: "Welcome to LibreChat! Enjoy your experience."
  privacyPolicy:
    externalUrl: 'https://librechat.ai/privacy-policy'
    openNewTab: true
  # Terms of service
  termsOfService:
    externalUrl: 'https://librechat.ai/tos'
    openNewTab: true
  endpointsMenu: true
  modelSelect: true
  parameters: true
  sidePanel: true
  presets: true
  prompts: true
  bookmarks: true
  multiConvo: true
  agents: true


# Definition of custom endpoints
endpoints:
  bedrock:
    availableRegions:
      - "eu-north-1"
      - "eu-central-1"
      - "eu-west-1"
      - "eu-west-3"
    inferenceProfileMapping:
      "bedrock-claude3-7-fr":
        params:
          maxTokens: 200000
          temperature: 0.7
    modelDisplayLabel: "Claude 3.7 Sonnet"
    streamRate: 35
    titleConvo: true
    titleModel: "bedrock-claude3-7-fr"

...

modelSpecs:
  enforce: false
  prioritize: true
  addedEndpoints: ["agents"]
  list:
    - name: "bedrock-claude3-7-fr"
      label: "Claude 3.7 Expert"
      showIconInMenu: true
      showIconInHeader: false
      preset:
        endpoint: "bedrock"
        model: "arn:aws:bedrock:eu-north-1:082282577843:inference-profile/eu.anthropic.claude-3-7-sonnet-20250219-v1:0"
        modelLabel: "Claude 3.7"
        parameters:
          maxTokens: 128000
          temperature: 0.7
...

```

but is still displays the long name (not in the top headed values, but in the menu) : 

![Image](https://github.com/user-attachments/assets/75138063-3510-4e0a-b47e-753dde8821e7)

![Image](https://github.com/user-attachments/assets/982d8977-7acb-4799-8a59-a701e3d2d207)

![Image](https://github.com/user-attachments/assets/01546c56-be2c-4e05-a695-83f9215a505e)
