### ISSUE TITLE
[Bug]: When I use **oneapi** to relay OpenRouter, I can't show the thinking model's thinking label in custom endpoint

### ISSUE THREAD

**Issue by harrisonhxy** [danny-avila/LibreChat#7085]
### What happened?

OpenRouter provides a lot of models, I mainly use one of the thinking models, such as deepseek, grok-3-mini-beta, etc. When I plug OpenRouter into one-api, and use **custom endpoint** in `librechat.yml` to customize the endpoints, the thinking model loses the thinking tag, and doesn't show the contents of the thinking, only the result of the answer.

### Version Information

ghcr.io/danny-avila//librechat                            latest               9b0706aeaa4a   20 hours ago    958MB
ghcr.io/danny-avila/librechat-rag-api-dev-lite   latest               817faebddae9   2 weeks ago     1.31GB
ghcr.io/rubentalstra/librechat-prom-exporter     latest               05eee494c72a   5 weeks ago     245MB

### Steps to Reproduce

For example, when I forward DeepSeek from OpenRouter through oneapi, my custom endpoint is set up as follows:
```yml
    - name: "deepseek"
      apiKey: "${DEEPSEEK_API_KEY}"
      baseURL: "[https://My oneapi proxy address.com/v1]()"
      iconURL: "https://icon.com/file/1736692987753_deepseek.svg"
      models:
        default: [
          "deepseek-v3",
          "deepseek-r1"
          ]
        fetch: false
      userIdQuery: false
      titleConvo: true
      titleMethod: "completion"
      titleModel: "deepseek-v3"
      summarize: false
      summaryModel: "deepseek-v3"
      forcePrompt: false
      modelDisplayLabel: "deepseek"
```

**DeepSeek at this point would not have a thinking process**

<img width="906" alt="Image" src="https://github.com/user-attachments/assets/b96bad5a-7116-4842-b1d0-81844d4a22f0" />

DeepSeek got the thinking process going when I set the `name` field in the custom endpoint, with openrouter (case-insensitive). the custom endpoint settings are shown below:
```yml
    - name: "openrouterdeepseek"
      apiKey: "${DEEPSEEK_API_KEY}"
      baseURL: "[https://My oneapi proxy address.com/v1]()"
      iconURL: "https://icon.com/file/1736692987753_deepseek.svg"
      models:
        default: [
          "deepseek-v3",
          "deepseek-r1"
          ]
        fetch: false
      userIdQuery: false
      titleConvo: true
      titleMethod: "completion"
      titleModel: "deepseek-v3"
      summarize: false
      summaryModel: "deepseek-v3"
      forcePrompt: false
      modelDisplayLabel: "deepseek"
```

I know that the `name` field of the custom endpoint is case-insensitive, so I'm guessing that when I set `name: "deepseek"`, it will automatically go DeepSeek's route. And when I set it to `name: "openrouterdeepseek"`, it may use OpenRouter's routes. This in undoubtedly limits the advantages of custom endpoint, because there are many vendors that provide DeepSeek models, but LibreChat separates them by different vendor channels. even if I use oneapi aggregation on the backend, I can't achieve polling for multiple vendor channels under the same model name

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
Librechat's container logs don't show any error messages
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
