### ISSUE TITLE
[Enhancement]: Adding endpoint for inception lab's mercury

### ISSUE THREAD

**Issue by zhang-yuhui** [danny-avila/LibreChat#7169]
### What features would you like to see added?

It uses standard openai request but current config in `librechat.yaml` does not work:
```yaml
endpoints:
  custom:
    - name: "inception-lab"
      apiKey: "${INCEPTION_API_KEY}"
      baseURL: "https://api.inceptionlabs.ai/v1"
      models:
        default: ["mercury-coder-small"]
      titleModel: "mercury-coder-small"
      modelDisplayLabel: "inception-lab"
```

### More details

More on its [documentation](https://platform.inceptionlabs.ai/docs).

### Which components are impacted by your request?

Endpoints

### Pictures

<img width="845" alt="Image" src="https://github.com/user-attachments/assets/232ec66b-1a8c-4240-8c03-d909aac70925" />

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
