### ISSUE TITLE
[Enhancement]: Lock/Disable parameter component when an override value is provided.

### ISSUE THREAD

**Issue by nhtruong** [danny-avila/LibreChat#7179]
### What features would you like to see added?

When a custom endpoint is provided like this in the `librechat.yaml` like this:
```yaml
    - name: 'Cohere'
      apiKey: '${COHERE_API_KEY}'
      models:
        default: [ 'cohere:command-r-plus' ]
        fetch: false
      titleConvo: true
      titleModel: 'gpt-3.5-turbo'
      summarize: false
      modelDisplayLabel: 'Cohere'
      dropParams: [ 'user' ]
      addParams:
        temperature: 0.22
```

The temperature is locked to 0.22 when Cohere is used. However, you can still update the slider for temperature for this model and when creating a new agent using this model. The value of the slider will still be saved with any value making the user think that they can actually alter this value while in the background, this custom value is ignored and 0.22 is used instead.

The UI should reflects that his value is fixed at 0.22.

### More details

When a parameter, like temperature, is locked to a certain value, the following should happen:
- The slider/input for that parameter is set to that value.
- The slider/input for that parameter is disabled
- Tooltip says that the value is locked.

(Apply to both agent and non-agent parameters)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
