### ISSUE TITLE
[Enhancement]: Parameter range for addParams

### ISSUE THREAD

**Issue by nhtruong** [danny-avila/LibreChat#7180]
### What features would you like to see added?

Right now we can add custom endpoints and provide them with a list of overridden parameter values via `addParams` in the `librechat.yaml`. For example:
```yaml
    - name: 'Cohere'
      ...
      addParams:
        temperature: 0.22
        top_p: 0.5
```

We should expand this feature and allow custom endpoints to set the range and step for each parameter. This allows the admin to prevent users from using dangerous param values but still give the user the flexibility to choose a specific value within the allowed safe range.

### More details

The settings for the endpoints can look like this in `librechat.yaml`:
```yaml
    - name: 'Cohere'
      ...
      addParams:
        temperature:
          - min_range: 0.2
          - max_range: 0.7
          - default: 0.6
          - step: 0.1
        top_p: 0.5
```
Then when the user tries to update `temperature` for Cohere (or create an agent using Cohere), the slider for this value will have the range of 0.2 - 0.7 with default value of 0.6.
Note that the value override for `top_p` is still intact.

---

- [x] I agree to follow this project's Code of Conduct
