### ISSUE TITLE
[Bug]: `includedTools` setting not respected when agents chain is active

### ISSUE THREAD

**Issue by sbruel** [danny-avila/LibreChat#7190]
### What happened?

We use the following settings in `librechat.yml`
```yml
endpoints:
  agents:
    disableBuilder: false
    capabilities:
      - 'file_search'
      - 'actions'
      - 'tools'
      - 'artifacts'
...
includedTools:
  - google
  - dalle
  - calculator

mcpServers:
  some-server:
    ...
```
and everything works as expected.
When adding `chain` to the list of capabilities, as in:
```yml
endpoints:
  agents:
    disableBuilder: false
    capabilities:
      - 'file_search'
      - 'actions'
      - 'tools'
      - 'artifacts'
      - 'chain'
...
includedTools:
  - google
  - dalle
  - calculator

mcpServers:
  some-server:
    ...
```

The `includedTools` list is not respected and the tools from the MCP server don't appear anymore when creating an agent.
All the default tools appear again:

![Image](https://github.com/user-attachments/assets/8149e252-d3a1-4ffe-b285-83fc017bda59)

### Version Information

5efad8f646a8efb7c010e85f355d9ac88b823048

### Steps to Reproduce

1. Add `includedTools` configuration to `librechat.yml`
2. Disable `chain` in  `endpoints.agents.capabilities`
3. Try creating an agent
4. Confirm only the included tools are visible
5. Add `chain` to `endpoints.agents.capabilities`
6. Try creating an agent
7. All the tools are now visible (but not MCP servers provided ones if configured)

### Relevant log output

```shell
N/A
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
