### ISSUE TITLE
[Bug]: Incorrectly uses OpenAI client for the Ollama endpoint

### ISSUE THREAD

**Issue by sreevatsank1999** [danny-avila/LibreChat#7236]
### What happened?

Error on Ollama endpoint 
![Image](https://github.com/user-attachments/assets/ef893b6d-9678-45e7-9891-eba985ccdd61)

### Version Information

Using `main` branch latest  
git commit SHA: fc6e14efe28e0c40f6453c0e5d9943377ccbfacd

### Steps to Reproduce

librechat.yaml

```yaml
  custom:
    - name: "Ollama"
      apiKey: "ollama"
      # use 'host.docker.internal' instead of localhost if running LibreChat in a docker container
      baseURL: "http://127.0.0.1:11434/v1/chat/completions" 
      models:
        default: [
          "deepseek-r1:32b",
          "llama3.3:70b",
          "phi4:14b",
          "llama3.2-vision:90b",
          "llama3.2:3b",
          "llava:34b",
          "qwen2.5-coder:32b",
          "deepseek-coder-v2:16b"
          ]
        # fetching list of models is supported but the `name` field must start
        # with `ollama` (case-insensitive), as it does in this example.
        fetch: false
      titleConvo: true
      titleModel: "qwen2.5:0.5b"
      summarize: true
      summaryModel: "qwen2.5:0.5b"
      forcePrompt: false
      modelDisplayLabel: "Ollama"
```

1. Deploy 
2. Select Ollama endpoint 
3. Type any query

### What browsers are you seeing the problem on?

Microsoft Edge, Firefox, Mobile (Android)

### Relevant log output

```shell
{"level":"warn","message":"[OpenAIClient.chatCompletion][stream] API error","timestamp":"2025-05-06T06:31:23.498Z"}
{"code":null,"error":{"code":null,"message":"model \"llama3.2:3b\" not found, try pulling it first","param":null,"type":"api_error"},"headers":{"content-length":"122","content-type":"application/json","date":"Tue, 06 May 2025 06:31:23 GMT"},"level":"error","message":"","param":null,"status":404,"timestamp":"2025-05-06T06:31:23.500Z","type":"api_error"}
{"code":null,"error":{"code":null,"message":"model \"llama3.2:3b\" not found, try pulling it first","param":null,"type":"api_error"},"headers":{"content-length":"122","content-type":"application/json","date":"Tue, 06 May 2025 06:31:23 GMT"},"level":"error","message":"[AskController] Error handling request 404 model \"llama3.2:3b\" not found, try pulling it first","param":null,"stack":"Error: 404 model \"llama3.2:3b\" not found, try pulling it first\n    at APIError.generate (/app/node_modules/openai/error.js:54:20)\n    at CustomOpenAIClient.makeStatusError (/app/node_modules/openai/core.js:302:33)\n    at CustomOpenAIClient.makeRequest (/a...","status":404,"timestamp":"2025-05-06T06:31:23.500Z","type":"api_error"}
{"code":null,"error":{"code":null,"message":"model \"llama3.2:3b\" not found, try pulling it first","param":null,"type":"api_error"},"headers":{"content-length":"122","content-type":"application/json","date":"Tue, 06 May 2025 06:31:23 GMT"},"level":"error","message":"[handleAbortError] AI response error; aborting request: 404 model \"llama3.2:3b\" not found, try pulling it first","param":null,"stack":"Error: 404 model \"llama3.2:3b\" not found, try pulling it first\n    at APIError.generate (/app/node_modules/openai/error.js:54:20)\n    at CustomOpenAIClient.makeStatusError (/app/node_modules/openai/core.js:302:33)\n    at CustomOpenAIClient.makeRequest (/a...","status":404,"timestamp":"2025-05-06T06:31:23.501Z","type":"api_error"}
{"level":"warn","message":"[OpenAIClient.chatCompletion][stream] API error","timestamp":"2025-05-06T06:34:45.829Z"}
{"code":null,"error":{"code":null,"message":"model \"llama3.2:3b\" not found, try pulling it first","param":null,"type":"api_error"},"headers":{"content-length":"122","content-type":"application/json","date":"Tue, 06 May 2025 06:34:45 GMT"},"level":"error","message":"","param":null,"status":404,"timestamp":"2025-05-06T06:34:45.829Z","type":"api_error"}
{"code":null,"error":{"code":null,"message":"model \"llama3.2:3b\" not found, try pulling it first","param":null,"type":"api_error"},"headers":{"content-length":"122","content-type":"application/json","date":"Tue, 06 May 2025 06:34:45 GMT"},"level":"error","message":"[AskController] Error handling request 404 model \"llama3.2:3b\" not found, try pulling it first","param":null,"stack":"Error: 404 model \"llama3.2:3b\" not found, try pulling it first\n    at APIError.generate (/app/node_modules/openai/error.js:54:20)\n    at CustomOpenAIClient.makeStatusError (/app/node_modules/openai/core.js:302:33)\n    at CustomOpenAIClient.makeRequest (/a...","status":404,"timestamp":"2025-05-06T06:34:45.829Z","type":"api_error"}
{"code":null,"error":{"code":null,"message":"model \"llama3.2:3b\" not found, try pulling it first","param":null,"type":"api_error"},"headers":{"content-length":"122","content-type":"application/json","date":"Tue, 06 May 2025 06:34:45 GMT"},"level":"error","message":"[handleAbortError] AI response error; aborting request: 404 model \"llama3.2:3b\" not found, try pulling it first","param":null,"stack":"Error: 404 model \"llama3.2:3b\" not found, try pulling it first\n    at APIError.generate (/app/node_modules/openai/error.js:54:20)\n    at CustomOpenAIClient.makeStatusError (/app/node_modules/openai/core.js:302:33)\n    at CustomOpenAIClient.makeRequest (/a...","status":404,"timestamp":"2025-05-06T06:34:45.829Z","type":"api_error"}
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
