### ISSUE TITLE
[Enhancement]: Support Bearer Authorization header as custom headers for MCPs

### ISSUE THREAD

**Issue by ala85** [danny-avila/LibreChat#7240]
### What features would you like to see added?

Ability to pass Authorization header to MCPS. Currently only environment variables are supported and sent to MCP , including the Librechat user id.

I would like a more granular and standardized approach so MCPs can then handle token validation on their side.

### More details

As above.

### Which components are impacted by your request?

Other

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Already supported:

```yaml
mcpServers:
  mock_server:
    type: sse
    url: http://localhost:8002/sse
    headers:
      Authorization: "Bearer ${SOME_API_KEY}"
```

```.env
# in your .env file
SOME_API_KEY=test
```
