### ISSUE TITLE
[Bug]: Bug in librechat.yaml config for Azure OpenAI

### ISSUE THREAD

**Issue by apamildner** [danny-avila/LibreChat#7363]
### What happened?

When using a custom key for models( see example), the chat fails with: "Something went wrong. Here's the specific error message we encountered: An error occurred while processing your request. Please contact the Admin."
<img width="933" alt="Image" src="https://github.com/user-attachments/assets/786ca551-c6a5-45b9-a995-3cdac3549c50" />

### Version Information

v.0.7.8

### Steps to Reproduce

This doesn't work:
```yaml
version: 1.2.1
endpoints:
  azureOpenAI:
    plugins: true
    summarize: true
    titleConvo: true
    groups:
      - group: "some-grp"
        apiKey: ${OPENAI_API_KEY}
        instanceName: some-instance-name
        version: 2025-01-01-preview
        models:
          foo: # key differs from deploymentName
            deploymentName: "gpt-4.1"
```

But this works (notice that the name `gpt-4.1` is same for the key and the `deploymentName` under models)

```yaml
version: 1.2.1
endpoints:
  azureOpenAI:
    plugins: true
    summarize: true
    titleConvo: true
    groups:
      - group: "some-grp"
        apiKey: ${OPENAI_API_KEY}
        instanceName: some-instance-name
        version: 2025-01-01-preview
        models:
          gpt-4.1: # Here we use the same name as deploymentName
            deploymentName: "gpt-4.1"
```

### Relevant log output

```shell
error: [handleAbortError] AI response error; aborting request: Failed to send message. HTTP 400 - Unsupported data type
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
