### ISSUE TITLE
[Bug]: Unable to register new users

### ISSUE THREAD

**Issue by looeee** [danny-avila/LibreChat#7545]
### What happened?

I'm unable to register new users. 

![Image](https://github.com/user-attachments/assets/6314fdd1-31ac-42c5-a137-18a9b3085ad6)

### Version Information

docker images | grep librechat
ghcr.io/danny-avila/librechat-dev-api                latest          fe0790de0fb5   5 hours ago     1.11GB
ghcr.io/danny-avila/librechat-rag-api-dev-lite       latest          e7da8e6aca0f   2 weeks ago     1.31GB
ghcr.io/danny-avila/librechat-dev-api                <none>          681d20ba8ee6   2 weeks ago     1.09GB
ghcr.io/danny-avila/librechat-rag-api-dev-lite       <none>          817faebddae9   6 weeks ago     1.31GB

### Steps to Reproduce

1. Use this docker compose and env file to create a librechat instance. 
2. Try to register a new user 

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

Checking the API container logs I see:
```shell

2025-05-25 04:47:49 error: [registerUser] Error in registering user: connect ECONNREFUSED 127.0.0.1:587

2025-05-25 04:47:49 warn: [registerUser] [Email: thom@thomsbakery.cafe] [Temporary User deleted: {"deletedCount":1,"message":"User was deleted successfully."}]

2025-05-25 04:48:04 error: [registerUser] Error in registering user: connect ECONNREFUSED 127.0.0.1:587

2025-05-25 04:48:04 warn: [registerUser] [Email: thom@thomsbakery.cafe] [Temporary User deleted: {"deletedCount":1,"message":"User was deleted successfully."}]
```

Here's my .env file. Note that secrets are managed through portainer (any variables that show "set_in_portainer" here):

```
## Init config

## Secrets

#CREDS_IV=set_in_portainer
#CREDS_KEY=set_in_portainer
#EMAIL_PASSWORD=set_in_portainer
#JWT_REFRESH_SECRET=set_in_portainer
#JWT_SECRET=set_in_portainer
#MEILI_MASTER_KEY=set_in_portainer
#POSTGRES_PASSWORD=set_in_portainer
#RAG_OPENAI_API_KEY=set_in_portainer

POSTGRES_DB=libre
POSTGRES_USER=libre
NODE_ENV=production
HOST=0.0.0.0
PORT=3080

MONGO_URI=mongodb://mongodb:27017/LibreChat

DOMAIN_CLIENT=http://localhost:3080
DOMAIN_SERVER=http://localhost:3080

NO_INDEX=true

DB_HOST=vectordb

CONSOLE_JSON=false

DEBUG_LOGGING=false
DEBUG_CONSOLE=false

ENDPOINTS=google,anthropic

# ANTHROPIC_API_KEY=set_in_portainer
ANTHROPIC_MODELS=claude-3-7-sonnet-latest

# GOOGLE_KEY=set_in_portainer
GOOGLE_MODELS=gemini-pro,gemini-pro-vision,gemini-2.5-pro-preview-03-25

SEARCH=true
MEILI_NO_ANALYTICS=true
MEILI_HOST=http://meilisearch:7700

RAG_API_URL=http://rag_api:8000
RAG_PORT=8000

OPENAI_MODERATION=false
OPENAI_MODERATION_API_KEY=
# OPENAI_MODERATION_REVERSE_PROXY=

BAN_VIOLATIONS=true
BAN_DURATION=1000 * 60 * 60 * 2
BAN_INTERVAL=20

LOGIN_VIOLATION_SCORE=1
REGISTRATION_VIOLATION_SCORE=1
CONCURRENT_VIOLATION_SCORE=1
MESSAGE_VIOLATION_SCORE=1
NON_BROWSER_VIOLATION_SCORE=20

LOGIN_MAX=7
LOGIN_WINDOW=5
REGISTER_MAX=5
REGISTER_WINDOW=60

LIMIT_CONCURRENT_MESSAGES=true
CONCURRENT_MESSAGE_MAX=2

LIMIT_MESSAGE_IP=true
MESSAGE_IP_MAX=40
MESSAGE_IP_WINDOW=1

LIMIT_MESSAGE_USER=false
MESSAGE_USER_MAX=40
MESSAGE_USER_WINDOW=1

ILLEGAL_MODEL_REQ_SCORE=5

#========================#
# Registration and Login #
#========================#

ALLOW_EMAIL_LOGIN=true
ALLOW_REGISTRATION=true
ALLOW_SOCIAL_LOGIN=true
ALLOW_SOCIAL_REGISTRATION=false
ALLOW_PASSWORD_RESET=true
# ALLOW_ACCOUNT_DELETION=true # note: enabled by default if omitted/commented out
ALLOW_UNVERIFIED_EMAIL_LOGIN=true

SESSION_EXPIRY=10000 * 60 * 15
REFRESH_TOKEN_EXPIRY=(10000 * 60 * 60 * 24) * 7

#JWT_SECRET=set_in_portainer
#JWT_REFRESH_SECRET=set_in_portainer

# Discord
DISCORD_CLIENT_ID=
DISCORD_CLIENT_SECRET=
DISCORD_CALLBACK_URL=/oauth/discord/callback

# Facebook
FACEBOOK_CLIENT_ID=
FACEBOOK_CLIENT_SECRET=
FACEBOOK_CALLBACK_URL=/oauth/facebook/callback

# GitHub
GITHUB_CLIENT_ID=
GITHUB_CLIENT_SECRET=
GITHUB_CALLBACK_URL=/oauth/github/callback

# Google
GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=
GOOGLE_CALLBACK_URL=/oauth/google/callback

# OpenID
OPENID_CLIENT_ID=
OPENID_CLIENT_SECRET=
OPENID_ISSUER=
OPENID_SESSION_SECRET=
OPENID_SCOPE="openid profile email"
OPENID_CALLBACK_URL=/oauth/openid/callback
OPENID_REQUIRED_ROLE=
OPENID_REQUIRED_ROLE_TOKEN_KIND=
OPENID_REQUIRED_ROLE_PARAMETER_PATH=
# Set to determine which user info property returned from OpenID Provider to store as the User's username
OPENID_USERNAME_CLAIM=
# Set to determine which user info property returned from OpenID Provider to store as the User's name
OPENID_NAME_CLAIM=

OPENID_BUTTON_LABEL=
OPENID_IMAGE_URL=

# LDAP
LDAP_URL=
LDAP_BIND_DN=
LDAP_BIND_CREDENTIALS=
LDAP_USER_SEARCH_BASE=
LDAP_SEARCH_FILTER=mail={{username}}
LDAP_CA_CERT_PATH=
# LDAP_TLS_REJECT_UNAUTHORIZED=
# LDAP_LOGIN_USES_USERNAME=true
# LDAP_ID=
# LDAP_USERNAME=
# LDAP_EMAIL=
# LDAP_FULL_NAME=

#========================#
# Email Password Reset   #
#========================#

EMAIL_SERVICE=smtp
EMAIL_HOST=mail.thomsbakery.cafe
EMAIL_PORT=587
EMAIL_ENCRYPTION=STARTTLS
# EMAIL_ENCRYPTION_HOSTNAME=
# EMAIL_ALLOW_SELFSIGNED=
EMAIL_USERNAME=info@thomsbakery.cafe

EMAIL_FROM_NAME="LibreChat@Thoms's Sourdough Bakery"
EMAIL_FROM=info@thomsbakery.cafe
# EMAIL_PASSWORD=set_in_portainer

#===================================================#
#                        UI                         #
#===================================================#

APP_TITLE="Thom's Sourdough Bakery Chat"
# CUSTOM_FOOTER="My custom footer"
HELP_AND_FAQ_URL=https://librechat.ai


#========================#
# Shared Links           #
#========================#

ALLOW_SHARED_LINKS=true
ALLOW_SHARED_LINKS_PUBLIC=true
```

Note that I also tried setting EMAIL_ALLOW_SELFSIGNED=true with no change. 

Here's librechat.yml

```yml
# For more information, see the Configuration Guide:
# https://docs.librechat.ai/install/configuration/custom_config.html

# Configuration version (required)
version: 1.1.5

# Cache settings: Set to true to enable caching
cache: true

# Custom interface configuration
interface:
  # Privacy policy settings
  privacyPolicy:
    externalUrl: "https://librechat.ai/privacy-policy"
    openNewTab: true

  # Terms of service
  termsOfService:
    externalUrl: "https://librechat.ai/tos"
    openNewTab: true

  endpointsMenu: true
  modelSelect: true
  parameters: true
  sidePanel: true
  presets: true
  prompts: true
  bookmarks: true
  multiConvo: true
  agents: true

registration:
  allowedDomains: -"thomsbakery.cafe"
```

Note: I also tried `allowedDomains: ["thomsbakery.cafe"]` with the same result. 

Here's my docker compose:

```yml
services:
  api:
    image: ghcr.io/danny-avila/librechat-dev-api:latest
    container_name: LibreChat-API-v2
    ports:
      - 3080:3080
    depends_on:
      # init-config:
      #   condition: service_completed_successfully
      mongodb:
        condition: service_started
      rag_api:
        condition: service_started
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    environment:
      - CREDS_KEY=${CREDS_KEY}
      - CREDS_IV=${CREDS_IV}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
      - RAG_OPENAI_API_KEY=${RAG_OPENAI_API_KEY}
      - NODE_ENV=${NODE_ENV}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - GOOGLE_KEY=${GOOGLE_KEY}
    volumes:
      - /opt/TSB-Tech-Stack/docker/LibreChat/librechat.yaml:/app/librechat.yaml
      - librechat_images:/app/client/public/images
      - librechat_uploads:/app/uploads
      - librechat_logs:/app/api/logs
    networks:
      - proxy-network
      - app-network

  mongodb:
    container_name: LibreChat-mongodb
    # ports:  # Uncomment this to access mongodb from outside docker, not safe in deployment
    #   - 27018:27017
    image: mongo
    restart: always
    environment:
      - CREDS_KEY=${CREDS_KEY}
      - CREDS_IV=${CREDS_IV}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
      - RAG_OPENAI_API_KEY=${RAG_OPENAI_API_KEY}
    volumes:
      - librechat_mongodb:/data/db
    command: mongod --noauth
    networks:
      - app-network

  meilisearch:
    container_name: LibreChat-meilisearch
    image: getmeili/meilisearch:v1.12.8
    restart: always
    # ports: # Uncomment this to access meilisearch from outside docker
    #   - 7700:7700 # if exposing these ports, make sure your master key is not the default value
    env_file:
      - .env
    environment:
      - CREDS_KEY=${CREDS_KEY}
      - CREDS_IV=${CREDS_IV}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
      - RAG_OPENAI_API_KEY=${RAG_OPENAI_API_KEY}
    volumes:
      - librechat_meilisearch_v1_12:/meili_data
    networks:
      - app-network

  vectordb:
    container_name: LibreChat-vectordb
    image: ankane/pgvector:v0.5.1
    env_file:
      - .env
    environment:
      - CREDS_KEY=${CREDS_KEY}
      - CREDS_IV=${CREDS_IV}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
      - RAG_OPENAI_API_KEY=${RAG_OPENAI_API_KEY}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: always
    volumes:
      - librechat_vectordb:/var/lib/postgresql/data
    networks:
      - app-network

  rag_api:
    container_name: LibreChat-rag-api
    image: ghcr.io/danny-avila/librechat-rag-api-dev-lite:latest
    environment:
      - CREDS_KEY=${CREDS_KEY}
      - CREDS_IV=${CREDS_IV}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
      - RAG_OPENAI_API_KEY=${RAG_OPENAI_API_KEY}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: always
    depends_on:
      - vectordb
    env_file:
      - .env
    networks:
      - app-network

volumes:
  librechat_vectordb:
    name: librechat_vectordb
    external: true
  librechat_images:
    name: librechat_images
    external: true
  librechat_uploads:
    name: librechat_uploads
    external: true
  librechat_logs:
    name: librechat_logs
    # external: true
  librechat_mongodb:
    name: librechat_mongodb
    external: true
  librechat_meilisearch_v1_12:
    name: librechat_meilisearch_v1_12
    # external: true

networks:
  app-network:
    name: librechat-network
  proxy-network:
    external: true
```

Let me know if I missed any information. 

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
