### ISSUE TITLE
[Bug]: helm chart librechat installation always return error

### ISSUE THREAD

**Issue by Slach** [danny-avila/LibreChat#7619]
### What happened?

I use following deploy approach
install ollama models with ollama-operator
```bash
kubectl apply --server-side=true -f https://github.com/nekomeowww/ollama-operator/raw/refs/heads/main/dist/install.yaml
kubectl apply -n ollama-operator-system -f librechat/ollama-models.yaml
kubectl apply -n ollama-operator-system -f librechat/ollama-services.yaml
```
install gateway database MCP server
```
rm -rf /tmp/gateway
helm pull oci://ghcr.io/centralmind/gateway-helm/gateway --destination /tmp/ --untar
kubectl create namespace gateway-system || true
helm upgrade --install gateway /tmp/gateway --namespace gateway-system --values "$CUR_DIR/gateway-values.yaml"
```

## install librechat + librechat-rag-api
```bash
git clone https://github.com/danny-avila/LibreChat.git /tmp/LibreChat
helm repo add bitnami https://charts.bitnami.com/bitnami
helm repo add meilisearch https://meilisearch.github.io/meilisearch-kubernetes

# Create namespace for LibreChat
kubectl create namespace librechat || true

# Install LibreChat with Helm
cd /tmp/LibreChat/helm/librechat-rag-api && helm dependency build && cd -
helm upgrade --install librechat-rag-api /tmp/LibreChat/helm/librechat-rag-api \
  --namespace librechat \
  --values "$CUR_DIR/librechat-rag-api-values.yaml"

# Build Helm dependencies
cd /tmp/LibreChat/helm/librechat && helm dependency build && cd -

# Install LibreChat with Helm
helm upgrade --install librechat /tmp/LibreChat/helm/librechat \
  --namespace librechat \
  --values "$CUR_DIR/librechat-values.yaml"

```

**librechat-values.yaml**
```yaml
librechat:
  configEnv:
    PLUGIN_MODELS: "devstral:latest"
    DEBUG_LOGGING: "true"
    DEBUG_CONSOLE: "true"

  configYamlContent: |
    version: "1.2.5"
    interface:
      customWelcome: "Welcome to Altinity ClickHouse LLM Prototype! Enjoy your experience."
      endpointsMenu: true
      modelSelect: true
      parameters: true
      sidePanel: true
      presets: true
      prompts: true
      bookmarks: true
      multiConvo: true
      agents: true    
    endpoints:
      custom:
      - name: ollama
        baseURL: "http://ollama-srv-devstral.ollama-operator-system.svc.cluster.local:11434"
        models:
          default: [ 'devstral:latest' ]
        agentOptions:
          model: "devstral:latest"
  
    mcpServers:
      gateway:
        type: sse
        url: "http://gateway.gateway-system.svc.cluster.local:8080/sse"
        chatMenu: true
```

**librechat-rag-api-values.yaml**
```yaml
global:
  librechat:
    existingSecretName: ""
image:
  repository: danny-avila/librechat-rag-api-dev
  registry: ghcr.io
  pullPolicy: IfNotPresent
  tag: latest

rag:
  enabled: true
  configEnv:
    EMBEDDINGS_PROVIDER: ollama
    OLLAMA_BASE_URL: http://ollama-srv-graphite.ollama-operator-system.svc.cluster.local:11434/
    EMBEDDINGS_MODEL: granite-embedding:278m
```

all pods run

all `ollama` and `gateway` services available 
and `curl -vvv http://ollama-srv-graphite.ollama-operator-system.svc.cluster.local:11434/api/tags` return expected model description

librechat UI run on 3080 port
`kubectl port-forward -n librechat svc/librechat --address 0.0.0.0 3080`

i can login with user which create with npm run create-user
but any chat message return error

inside librchat logs i see only following

```
2025-05-29T11:16:31.504Z debug: Custom config:
{
  version: "1.2.5",
    interface.customWelcome: "Welcome to Altinity ClickHouse LLM Prototype! Enjoy your experience.",
    interface.endpointsMenu: true,
    interface.modelSelect: true,
    interface.parameters: true,
    interface.sidePanel: true,
    interface.presets: true,
    interface.prompts: true,
    interface.bookmarks: true,
    interface.multiConvo: true,
    interface.agents: true,
    // 1 custom(s)
    endpoints.custom: [{"name":"ollama","baseURL":"http://ollama-srv-devstral.ollama-operator-system.svc.cluster.local:11434... [truncated]],
    gateway.type: "sse",
    gateway.url: "http://gateway.gateway-system.svc.cluster.local:8080/sse",
    gateway.chatMenu: true,
}
2025-05-29T11:16:31.504Z debug: [MCP][gateway] Transport sending: {"method":"tools/list","jsonrpc":"2.0","id":3}

2025-05-29T11:19:21.145Z error: [handleAbortError] AI response error; aborting request: Agent not found
2025-05-29T11:19:21.146Z debug: [AgentController] Performing cleanup
2025-05-29T11:19:21.146Z debug: [AgentController] Cleanup completed
```

which Agent shall i add? to allow MCP+Ollama?

### Version Information

```
root@gpu-01:~# minikube image ls | grep libre
ghcr.io/danny-avila/librechat:v0.7.8
ghcr.io/danny-avila/librechat-rag-api-dev:latest
```

### Steps to Reproduce

* install ollama-operator + models
* install gateway database MCP server helm chart
* install librechat + librechat-rag-api helm charts

### Relevant log output

```shell
## cat ./api/logs/error-2025-05-29.log

{"level":"error","message":"[handleAbortError] AI response error; 
aborting request: Agent not found",
"stack":"Error: Agent not found
    at initializeClient (/app/api/server/services/Endpoints/agents/initialize.js:319:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async AgentController (/app/api/server/controlle
rs/agents/request.js:105:20)
    at async controller (/app/api/server/routes/agents/chat.js:27:3)"}
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
