### ISSUE TITLE
[Enhancement]: model spec icons from filesystem

### ISSUE THREAD

**Issue by ion-elgreco** [danny-avila/LibreChat#8006]
### What features would you like to see added?

It's easier to add custom icons to the filesystem in airgapped environments, would be nice if we can point to a local filepath for an icon

### More details

Allow filepaths for icons in model spec.

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Yup, it's supported. You are limited to saving the images to `/LibreChat/client/public` but then you can reference it in `iconURL`:

https://www.librechat.ai/docs/configuration/librechat_yaml/object_structure/model_specs#iconurl

Example for image saved in `/LibreChat/client/public/assets/avatar_1749537695787.png`

```yaml
modelSpecs:
  enforce: false
  prioritize: true
  addedEndpoints: ["agents", "openAI"]
  list:
  - name: "Bedrock Sonnet 4"
    label: "Bedrock Sonnet 4"
    iconURL: "/assets/avatar_1749537695787.png"
    description: "Sonnet 4 via Bedrock"
    default: false
    preset:
      endpoint: "bedrock"
      model: "us.anthropic.claude-sonnet-4-20250514-v1:0"
      modelLabel: "Bedrock Sonnet 4"
      promptPrefix: "End every message with [END]"
```

If using docker, this can be done easily with volume mount mapping and pointing to any directory or files.
