### ISSUE TITLE
[Bug]: /config/Balancing Scripts still use .env setup only and not librechat.yaml

### ISSUE THREAD

**Issue by leondape** [danny-avila/LibreChat#8042]
### What happened?

Trying to use npm run add-balance will fail if CHECK_BALANCE = false. 

### Version Information

[0587a1c](https://github.com/danny-avila/LibreChat/commit/0587a1cc7ca7c9d206e5402ca46fc201cfe081bd)

### Steps to Reproduce

run npm add-balance or set-balance

### Relevant log output

```shell
Set balance to a user account!
--------------------------
Usage: npm run set-balance <email> <amount>
Note: if you do not pass in the arguments, you will be prompted for them.
--------------------------
Error: CHECK_BALANCE environment variable is not set! Configure it to use it: `CHECK_BALANCE=true`
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by dvejsada** [comment]
I can confirm we experience this as well. I had to add back env variable for this to work.

**Comment by danny-avila** [comment]
For these commands, you need to set `CHECK_BALANCE`.  The config will still work with the environment variable set, i.e.:

```yaml
balance:
  enabled: true
  startBalance: 1000000
  autoRefillEnabled: true  # When true, triggers automatic balance refilling
  refillIntervalValue: 4    
  refillIntervalUnit: "hours"  # Refill can occur once every day
  refillAmount: 1000000  
```
