### ISSUE TITLE
[Bug]: The MCP headers are not being sent correctly and impossible to set customUserVars.

### ISSUE THREAD

**Issue by matthisholleville** [danny-avila/LibreChat#8057]
### What happened?

Hello,

I’m using Librechat with SAML. When I try to send the headers using placeholders, only the USER_ID is being sent.

```yaml
# Removed for brevity

    mcpServers:
      sre:
        type: sse
        url: https://sre-url/sse
        timeout: 60000
        headers:
          X-User-ID: "{{LIBRECHAT_USER_ID}}"
          X-User-Email: "{{LIBRECHAT_USER_EMAIL}}"
          X-User-Role: "{{LIBRECHAT_USER_ROLE}}"
        customUserVars:
          USER_BEARER_TOKEN:
            title: "USER JWT Token"
            description: "Your personal JWT Token."
```

Log received from my MCP Server :

```bash
{"log.level":"debug","@timestamp":"2025-06-25T23:03:56.452+0200","message":"Calling tool context func","headers":"map[Accept:[*/*] Accept-Encoding:[br, gzip, deflate] Accept-Language:[*] Content-Length:[127] Content-Type:[application/json] Sec-Fetch-Mode:[cors] User-Agent:[node] X-Forwarded-For:[X.X.X.X] X-Forwarded-Host:[sre] X-Forwarded-Proto:[https] X-User-Email:[{{LIBRECHAT_USER_EMAIL}}] X-User-Id:[684b3859202e1f4cae76b321] X-User-Role:[{{LIBRECHAT_USER_ROLE}}]]","ecs.version":"1.6.0"}
```

Additionally, I’m unable to set a custom var per user.

<img width="112" alt="Image" src="https://github.com/user-attachments/assets/6b085702-7b37-4074-a728-af916decb611" />

I manually assigned my user to the `ADMIN` role in the user document in MongoDB.

### Version Information

`v0.7.8`

### Steps to Reproduce

1. Use SAML as the authentication method.
2. Configure your MCP Server by forwarding the headers as described in the documentation: https://www.librechat.ai/docs/configuration/librechat_yaml/object_structure/mcp_servers#headers

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
N/A
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Actually sorry I thought you were referring to another feature. You need to update to latest and not use the v0.7.8 tag

Updating Instructions (docker):
https://www.librechat.ai/docs/local/docker#update-librechat

**Comment by matthisholleville** [comment]
@danny-avila it's very confusing https://github.com/danny-avila/LibreChat/pkgs/container/librechat

**Comment by matthisholleville** [comment]
@danny-avila I’m currently using the latest configuration version fetched from here https://www.librechat.ai/changelog.

```yaml
  configYamlContent: |
    # For more information, see the Configuration Guide:
    # https://www.librechat.ai/docs/configuration/librechat_yaml

    # Configuration version (required)
    version: 1.2.8
```

But no changes. Can you re-open please

**Comment by matthisholleville** [comment]
@danny-avila Thanks for the clarification. That makes things clearer. However, sending headers from custom_vars doesn’t seem to work as described in the documentation :

```yaml
mcpServers:
      sre:
        type: sse
        url: https://sre-url/sse
        timeout: 60000
        headers:
          X-User-ID: "{{LIBRECHAT_USER_ID}}"
          X-User-Email: "{{LIBRECHAT_USER_EMAIL}}"
          X-User-Role: "{{LIBRECHAT_USER_ROLE}}"
          X-Auth-Token: "{{API_KEY}}" # Uses the API_KEY defined below
        customUserVars:
          API_KEY: # This key will be used as {{API_KEY}} in headers/url
            title: "API Key" # This is the label shown above the input field
            description: "Get your API key <a href='https://example.com/api-keys' target='_blank'>here</a>." # This description appears below the input
```

Log returned from my MCP Server :

```json
{
    "log.level": "debug",
    "@timestamp": "2025-06-26T00:25:09.318+0200",
    "message": "Calling tool context func",
    "headers": "map[Accept:[*/*] Accept-Encoding:[br, gzip, deflate] Accept-Language:[*] Content-Length:[137] Content-Type:[application/json] Sec-Fetch-Mode:[cors] User-Agent:[node] X-Auth-Token:[{{API_KEY}}] X-Forwarded-For:[x.x.x.x] X-Forwarded-Host:[sre-url] X-Forwarded-Proto:[https] X-User-Email:[my-email@gmail.com] X-User-Id:[684b3859202e1f4cae76b321] X-User-Role:[USER]]",
    "ecs.version": "1.6.0"
}
```
