### ISSUE TITLE
[Enhancement]: Display name and description for custom endpoint models

### ISSUE THREAD

**Issue by JanTrichter** [danny-avila/LibreChat#8109]
### What features would you like to see added?

Currently the custom endpoint configuration is quite short when it comes to providing information to (especially non-technical) users.

## Problem

The current config looks like this (via `librechat.yaml`, example from docs):

```yml
models:
  default: [
    "meta-llama/Llama-2-7b-chat-hf",
   ]
   fetch: true
```

This is not really descriptive and looks kinda rough in the UI. I've already had comments from non-technical users to  explain what each model is good at (and why they shouldn't just use the best, most expensive one by default).

## Possible solution

I think the configuration could look something like this:

```yml
endpoints:
  custom:
    # Claude
    - name: "Claude test"
      apiKey: "${ANTHROPIC_API_KEY}"
      baseURL: "https://api.anthropic.com/v1"
      models:
        default:
          - name: "claude-3-5-sonnet-20241022"
            label: "Claude 3.5 Sonnet"
            description: "Good at coding and analysis, but can be verbose. Best for development and complex reasoning tasks."
          - name: "claude-3-5-haiku-20241022"
            label: "Claude 3.5 Haiku"
            description: "Fast and cheap, decent for simple tasks but limited reasoning. Good for basic coding and quick responses."
          - name: "claude-3-opus-20240229"
            label: "Claude 3 Opus"
            description: "Most capable but slow and expensive. Best for complex analysis, creative writing, and challenging problem-solving."
        fetch: false
...
```

Which would then display like this in the UI:

<img width="751" alt="Image" src="https://github.com/user-attachments/assets/28482a04-b5a3-4680-b0a1-a3f4978c79b3" />

## Possible issues or questions

1. Could cause issues with the new vs old configuration format
2. i18n is an issue, what if the users have different preferences for the description, how could this be provided (if at all)?
3. Description needs to be short, otherwise the UI might look kinda bloated and text would be hard to read, there would be quite a bit of scrolling involved
4. Would it make sense to also search the description instead of only the label when a description is provided?

Of course if this is already possible please let me know ^^

### Which components are impacted by your request?

UI, Endpoints

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
